### ISSUE TITLE
ALSA volume mapping

### ISSUE THREAD

**Issue by hifiberry** [Spotifyd/spotifyd#100]
It seems that the volume sent from Spotify is converted internally using an logarithmic function. For my specific use case I would like to disable this conversion.

It would be could to have a configuration option to enable a linear mapping.

**Comment by SimonPersson** [comment]
This has been added as the `alsa_linear` volume controller option.

**Comment by hifiberry** [comment]
Wow, that was extremely fast. Thank you!
