### ISSUE TITLE
radio after playlist?

### ISSUE THREAD

**Issue by cxsmxx** [Spotifyd/spotifyd#1003]
I can't find a way for spotifyd to continue playing radio based on playlist which is a feature i use daily and I would really appreciate having this available. 

I tried device_type as speaker, computer, avr and everything else, none have worked.

Is there something wrong on my end? I can't find any radio settings in documentation.

Awesome work tho!

**Comment by eladyn** [comment]
This started working for me with the latest update. (At least I think that it had not worked before. Probably because of the `librespot 0.2` upgrade.)

Maybe you could try again with Spotifyd 0.3.3?

**Comment by eladyn** [comment]
Not sure, if you are still interested in this, but my previous assumption wasn't correct. Apparently, I had enabled the `--autoplay` flag and the application started the "radio" because of this. See also the PR #1039, which clarifies the documentation strings for this option.

**Comment by slondr** [comment]
#1039 has now been merged, so I'm closing this.
