### ISSUE TITLE
Write programming documentation

### ISSUE THREAD

**Issue by nonetrix** [Spotifyd/spotifyd#1005]
I want to make my own client, but going through the wiki, I can't find anything that would explain how I would go about making something like ```spotify-tui``` or  ```spotify-qt```. 

kinda off topic:

I use C++ mostly rather than Rust so something language agnostic without the use of API wrappers would be great, maybe dbus could get this effect?

**Comment by kraaijmakers** [comment]
Check out the code of [librespot](https://github.com/librespot-org/librespot).

It is also written in Rust, but it's what this software uses as the base.
Good luck and enjoy writing your own client!
