### ISSUE TITLE
spotifyd service didn't active (running) after running spotifyd as a service using systemd

### ISSUE THREAD

**Issue by satriajanaka09** [Spotifyd/spotifyd#1007]
**Description**

spotifyd service didn't active (running) after running spotifyd as a service using systemd

**To Reproduce**
1. Install the requirements
`sudo apt install rustc cargo libasound2-dev libssl-dev pkg-config` 
2. Clone the repo
`git clone https://github.com/Spotifyd/spotifyd.git`
3. Build spotifyd
```
cd spotifyd
cargo build --release
```
4. Copy `contrib/spotifyd.service` file to `/etc/systemd/user/` and `~/.config/systemd/user/`
5. Run the service
```
systemctl --user start spotifyd.service
systemctl --user enable spotifyd.service
```

**Expected behavior**
spotifyd service active (running) after running spotifyd as a service using systemd

**Logs**
<details><summary>Click to show logs</summary>
```● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/etc/xdg/systemd/user/spotifyd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2021-09-25 21:50:17 WIB; 1s ago
       Docs: https://github.com/Spotifyd/spotifyd
    Process: 24014 ExecStart=/usr/bin/spotifyd --no-daemon (code=exited, status=203/EXEC)
   Main PID: 24014 (code=exited, status=203/EXEC)
```</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions**

- OS: Ubuntu 20.04 LTS
- Spotifyd: commit hash f490962
- cargo: 1.51.0

<!-- **Additional context**
Add any other context about the problem here. -->

**Comment by JojiiOfficial** [comment]
Please provide the actual output log from spotifyd, not the systemctl status output. 
Did you adjust the config file?

**Comment by satriajanaka09** [comment]
> Did you adjust the config file?

@JojiiOfficial I already create the config file in `~/.config/spotifyd` named `spotifyd.conf` here's the [config](https://gist.github.com/satriajanaka09/f000e389750fac5838d83f4d7d7969b3.js) file (without my username and pasword).
 
> Please provide the actual output log from spotifyd, not the systemctl status output.

How can I see the log? Sorry but I did not see how to see the log in the [wiki](https://spotifyd.github.io/spotifyd/config/File.html)

**Comment by JojiiOfficial** [comment]
Try `sudo journalctl -u spotifyd`. Also check if it works if you run it from cli via `spotifyd --verbose --no-daemon`.

**Comment by satriajanaka09** [comment]
> Try `sudo journalctl -u spotifyd`. Also check if it works if you run it from cli via `spotifyd --verbose --no-daemon`.

@JojiiOfficial 

Here's the `sudo journalctl -u spotifyd` output :

```
Sep 25 23:45:03 satriajnk-GF63-Thin-9SCSR systemd[39118]: spotifyd.service: Failed to execute command: Permission denied
Sep 25 23:45:03 satriajnk-GF63-Thin-9SCSR systemd[39118]: spotifyd.service: Failed at step EXEC spawning /usr/bin/spotifyd: Permission denied
Sep 25 23:45:03 satriajnk-GF63-Thin-9SCSR systemd[1]: spotifyd.service: Main process exited, code=exited, status=203/EXEC
Sep 25 23:45:03 satriajnk-GF63-Thin-9SCSR systemd[1]: spotifyd.service: Failed with result 'exit-code'.
```

To check the `/usr/bin/spotifyd` directory permission, I run `ls -la spotifyd ` command in `/usr/bin` directory. Here's the output : 

```
drwxrwxrwx 2 root      root       4096 Sep 25 21:46 .
drwxr-xr-x 3 root      root      69632 Sep 25 22:23 ..
-rwxrwxrwx 1 satriajnk satriajnk   292 Sep 25 21:46 spotifyd.service
```
`sudo spotifyd --verbose --no-daemon` output : 

`sudo: spotifyd: command not found`

**Comment by satriajanaka09** [comment]
FInally I managed to make the `spotifyd` service running. What I did is copy the `spotifyd` file to `/usr/local/bin` . Here's the log from `sudo journalctl -u spotifyd` : 

```
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR systemd[1]: Started A spotify playing daemon.
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: No config file specified. Running with default values
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: No username specified. Checking username_cmd
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: No username_cmd specified
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: No password specified. Checking password_cmd
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: No password_cmd specified
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: No proxy specified
Sep 26 11:10:04 satriajnk-GF63-Thin-9SCSR spotifyd[16999]: Using software volume controller.
```

`systemctl status spotifyd` output : 

```
● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/etc/systemd/system/spotifyd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-09-26 11:10:04 WIB; 2min 33s ago
       Docs: https://github.com/Spotifyd/spotifyd
   Main PID: 16999 (spotifyd)
      Tasks: 2 (limit: 9284)
     Memory: 1.0M
     CGroup: /system.slice/spotifyd.service
             └─16999 /usr/local/bin/spotifyd --no-daemon
 ```

But when I tried to play a track in `spotify tui`, I got the message `Spotify API error code 404 : Device not found` . Also, my devices list is empty.
