### ISSUE TITLE
Restart should retain volume

### ISSUE THREAD

**Issue by henningphan** [Spotifyd/spotifyd#101]
Hello
Im happy with spotifyd. I also have an enhancement request.
Sometimes spotifyd crashes (it happens seldomly nowadays), I would like it to have the last volume setting when its restarted instead of having it on full volume.

**Comment by SimonPersson** [comment]
Arew you using the alsa mixer? In that case this has been fixed for some time now. When is your build from? 

For softvol we would have to store the volume state somewhere. I don't use softvol myself though, so it's not prioritised. If you'd like to work on that yourself I could give you some pointers.

**Comment by henningphan** [comment]
`backend = alsa
device = sysdefault:CARD=PCH # default # Given by `aplay -L`
volume-control = alsa_linear #softvol # or softvol
`
For volume control, alsa, doesnt work. Softvol and alsa_linear works.

Scenario:
If I change volume to 50% and use volume control alsa_linear or softvol
Restart spotifyd with systemctl --user restart spotifyd
Then spotify volume is still 100%

I wouldnt mind helping out in this project. But Im as of now not interested in learning rust at all as I have other skills I want to learn. I would gladly help out if you need any help with bash scripting if there is a need for that.

**Comment by bricedp** [comment]
I was in need of this feature as well; after looking at the code it seems it's an issue better solved within librespot. I've submitted a pull request with volume persistence there: [https://github.com/librespot-org/librespot/pull/218](https://github.com/librespot-org/librespot/pull/218). It works similarly to spotifyd's implementation of `--pid` in that it lets the user specify a path for the file.

If and when it gets merged into librespot, I assume that it would be simple to integrate into spotifyd — it just needs to pass the `--persist-volume` flag from the config file or the command line to the updated librespot code.

If that assumption is wrong and it's not trivial to integrate with spotifyd, I could help work on that as well. In that case I might need a few pointers from Simon on how he'd like to see it integrated.

**Comment by bricedp** [comment]
Just an update: this was merged into librespot just now (https://github.com/librespot-org/librespot/pull/220). Rather than requiring a new flag, it caches the volume by default when a cache directory is specified.
