### ISSUE TITLE
MPRIS dbus command play_pause only plays, does not pause

### ISSUE THREAD

**Issue by DhruvaSambrani** [Spotifyd/spotifyd#1018]
**Description**
MPRIS dbus command play_pause only plays, does not pause a playing song.

**To Reproduce**

1. Install playerctl
2. playerctl -p spotifyd play_pause
3. Song plays
4. playerctl -p spotifyd play_pause
5. Song continues playing

**Expected behavior**

Song stops playing

**Compilation flags** 
- AUR Build

**Versions (please complete the following information):**

- OS: Linux 5.10.70-1-MANJARO GNU/Linux
- Spotifyd: 0.3.2
- cargo: AUR Build, not used. 1.55.0

**Additional context**
spotifyd run via systemd
When spotify run without systemd, it does not react to any MPRIS commands

**Comment by NikitaIvanovV** [comment]
The same problem! However, I noticed that `playerctl pause` and `playerctl play` work correctly.

**Comment by pietryszak** [comment]
playerctl --player spotifyd play
playerctl --player spotifyd pause workig fine
playerctl play-pause not working for me.

**Comment by Diaoul** [comment]
I have the same issue. Let me know if there is anything I can do to help fix this.
Maybe an issue upstream with librespot as the code seems to correctly forward the instruction to the lib. I am no Rust dev so my little investigating led me [here](https://github.com/librespot-org/librespot/blob/e064f27c13d1a7277e196b31d7f09c9fb10a5f26/connect/src/spirc.rs#L763-L773) but no luck.
 I can confirm it works from pause to play but not the other way around.

**Comment by Diaoul** [comment]
Actually, this may be already fixed upstream: https://github.com/librespot-org/librespot/commit/392a12af9262dbec25c197f7b4cac37162bdd163

**Comment by pietryszak** [comment]
> Actually, this may be already fixed upstream: [librespot-org/librespot@392a12a](https://github.com/librespot-org/librespot/commit/392a12af9262dbec25c197f7b4cac37162bdd163)
> 
> Edit: Probably fixed with #977

It's merged to spotifyd 17 minutes ago, so we need to test it.

**Comment by NikitaIvanovV** [comment]
Just tested, doesn't seem to work :(

**Comment by Diaoul** [comment]
Indeed, but  I don't even see the option `use-mpris` from the `--help` anymore and `playerctl -l` does not show spotifyd so I think it is not even started for some reason.

**Comment by Diaoul** [comment]
Nevermind I war missing the feature flags to properly build with mpris support... Sorry for the noise. I just tested with the prebuilt binary instead as I have no idea how to activate the feature flags and the wiki is missing instructions on that.

It works fine for me! :tada: 
What binary did you test this with @NikitaIvanovV ?

**Comment by NikitaIvanovV** [comment]
@Diaoul I tested with a binary from AUR package `spotifyd-full-git` in a while after d10216a49119233fa2adbae505827938e2e7d59a was just commited.

**Comment by Diaoul** [comment]
I used the prebuilt binary from the latest release on GitHub :man_shrugging:

**Comment by NikitaIvanovV** [comment]
I tried using the prebilt binary and it worked!

**Comment by Diaoul** [comment]
For those on Arch, the version with the fix is available as regular package and it works.

**Comment by pietryszak** [comment]
I use fedora copr [spotifyd](https://copr.fedorainfracloud.org/coprs/szpadel/spotifyd/) with the newest version spotifyd 0.3.3, and it's working fine.
This issue can be closed.

**Comment by DhruvaSambrani** [comment]
The uldated version works well. I am closing the issue
