### ISSUE TITLE
Noticeable cracking sound with spotifyd + spotify-tui

### ISSUE THREAD

**Issue by Sammyalhashe** [Spotifyd/spotifyd#1022]
**Description**

Apologies for any ignorance here, I am just getting started with spotifyd. I am using it in combination with spotify-tui, currently I just assume that this could be because of spotifyd instead of spotify-tui as the latter is just a client. But when I play songs it works fine, just that there is a noticeable "crackling" sound periodically. This wasn't occurring with the native spotify app (official).
**To Reproduce**

no crackle
**The below is my config for spotifyd (I am on MacOS)**

```
use_keyring = true


use_mpris = true


backend = "portaudio" # use portaudio for macOS [homebrew]

# device = "alsa_audio_device"  # omit for macOS

# control = "alsa_audio_device"  # omit for macOS

# mixer = "PCM"  # omit for macOS

volume_controller = "softvol"  # use softvol for macOS

device_name = "spotifyd_personal"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 160

cache_path = "/Users/<USER>/.cache/spotifyd"
# cache_path = "/Users/<USER>/Library/Application Support/Spotify/PersistentCache/Storage"

# Volume on startup between 0 and 100
# NOTE: This variable's type will change in v0.4, to a number (instead of string)
initial_volume = "90"

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 1234

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, t_v,
# a_v_r (Audio/Video Receiver), s_t_b (Set-Top Box), and audio_dongle.
device_type = "speaker"
```

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [] alsa_backend
- [x] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: MacOS Mojave Version 10.14.6
- Spotifyd: 0.3.2
- cargo: 1.56.0

**Comment by eqixcx** [comment]
Solution:

Disabling 'volume_normalization' and commenting out 'normalization_pregain' fixed it for me, my config now looks like this

`# If set to true, enables volume normalization between songs.
volume_normalization = false

# The normalization pregain that is applied for each song.
# normalization_pregain = -10`

System Info:
macOS 12.1 Beta (21C5045a)
MacBook Pro (16-inch, 2021)
Apple M1 Max

**Comment by Sammyalhashe** [comment]
Thanks a lot @eqixcx! Worked like a charm it seems.

**Comment by benmanone** [comment]
I'm having the same issue, also on MacOS, I changed those settings but the issue is persisting. Anything else I could try?

**Comment by benmanone** [comment]
my config:
```[global]
username = "<username>"
use_keyring = true
use_mpris = true
backend = "portaudio"
volume_controller = "softvol"
device_name = "spotifyd"
bitrate = 160
cache_path = "/Users/<USER>/Library/Application Support/Spotify/PersistentCache/Storage"
no_audio_cache = false
volume_normalisation = false
zeroconf_port = 1234
device_type = "computer"```

**Comment by vargal380** [comment]
This only happens to  me when i use a usb for audio output, with bluetooth it works great
