### ISSUE TITLE
Binary "spotifyd-2018-03-14-armv7.zip" does not work

### ISSUE THREAD

**Issue by fertigfutter** [Spotifyd/spotifyd#103]
Error in latest binary? It starts but connection is refused.
Version 2018-03-03 ("armv6") works with Raspberry Pi3 and the following config. Is there something wrong? Thanks for help.

[global]
username = x
password = y
backend = alsa
device = hw:BossDAC
mixer = Digital
volume-control = alsa
onevent = "sudo systemctl restart mpd"
device_name = MoOde
bitrate = 320
cache_path = /tmp/
volume-normalisation = true
normalisation-pregain = -3

**Comment by SimonPersson** [comment]
Possibly. I don't even have an ARM device to try it on, I just automated the builds because it's a bit painful to cross compile. Perhaps the new DBUS integration is broken? I could try to disable that in the binary releases.

**Comment by fertigfutter** [comment]
Ah, okay. Thanks. I cannot help any further because I am new to Linux and Raspberry.

**Comment by SimonPersson** [comment]
I've pushed a new build. See if that works better.

**Comment by fertigfutter** [comment]
It works well again. Thank you for this very nice program.

**Comment by SimonPersson** [comment]
Fantastic! Thanks for the report.
