### ISSUE TITLE
panic with message: called `Result::unwrap()`

### ISSUE THREAD

**Issue by shendypratamaa** [Spotifyd/spotifyd#1034]
![Screenshot 2022-01-01 at 03 10 18](https://user-images.githubusercontent.com/76093597/147837942-d2931d11-3938-4d95-b63b-34b9c0881549.png)
help me, what should i do ?

on mac os 12.1
using homebrew installation
config path same with wiki spotifyd recomendation

**Comment by eladyn** [comment]
Hi!

This error alone doesn't really provide enough detail to solve your problem. Some more information that might help to narrow down the issue:

- The full log output with the `--verbose` flag, which should include the parsed configuration.
- Information on how to reproduce the problem if possible.
- ...

Essentially it will be easiest for others to help you if you follow the [provided issue template](https://github.com/Spotifyd/spotifyd/blob/master/.github/ISSUE_TEMPLATE/bug-report.md?plain=1).

**Comment by shendypratamaa** [comment]
oh sorry, i will close this issue, and create new one using template
