### ISSUE TITLE
How to you use this with snap

### ISSUE THREAD

**Issue by Aizakkuz** [Spotifyd/spotifyd#1035]
**Description**
I have no clue how to use this using snap, there isn't any documentation telling me how to actually run ``spotifyd`` after installing spotifyd using ``sudo snap install spotifyd``

**Comment by JojiiOfficial** [comment]
You should be able to normally run it from cli, like you would if it was installed from any other source. Maybe you have to add something to your PATH variable

**Comment by Aizakkuz** [comment]
cli, what is that? Also, yeah trying the command ``spotifyd`` didn't work, so you want me to add spotifyd to my PATH if so what's the path to spotifyd after installing using snap

**Comment by Aizakkuz** [comment]
Nevermind, I think I found spotfiyd ``/snap/spotifyd/6/bin/spotifyd``
