### ISSUE TITLE
Add optional integration with notify-send to display notifications on track change (and potentially other stuff)

### ISSUE THREAD

**Issue by Morreski** [Spotifyd/spotifyd#1038]
**Is your feature request related to a problem? Please describe.**
Not a problem, just something I think would be nice for linux desktop users. 

**Describe the solution you'd like**
I like to have a little notification on track change that display track and artist names. This feature could be disabled by default and enabled via the configuration file.

**Describe alternatives you've considered**
At the moment I use `spt` and `spotifyd` to listen to music. I made a dumb python script that polls `spt` every 5 seconds to check what song is playing. If song changes, it calls `notify-send`. This feature could be implemented in the `spt` project but I think it's better to be as close as possible to the playback device. Also it would be better to use in-code events instead of polling in term of resource consumptions.

If this feature is deemed useful I'm willing to work on it (despite my limited Rust skills). I could use some pointers as to where to start.

Side note: maybe we can go further by imagining a "plugin" system that allows user-defined scripts to react to player events ?

Regards,

**Comment by eladyn** [comment]
Hi!

Maybe I'm misunderstanding something, but I think that this should already be possible using the currently provided features:

- through `on_song_change_hook`:
  
  `spotifyd` can be configured to run a script on player events. There is even a wiki page that provides two simple scripts that are registered through the `onevent` / `on_song_change_hook` option, which should solve exactly your problem (I think): https://github.com/Spotifyd/spotifyd/wiki/User-supplied-scripts
- through the MPRIS interface:
  
  With #1025, you should be able to subscribe to player events through the `PropertiesChanged` signal on dbus.

Hope, this helps you somehow!

**Comment by Morreski** [comment]
Hey,

Oh damn. Blind me missed this page on the Wiki... You even have provided a section about dunst (which I use). Well nevermind about this issue it seems this feature got my use-case covered.

Thanks for pointing me in the right direction :)

Cheers,
