### ISSUE TITLE
What does this project actually do?

### ISSUE THREAD

**Issue by gavynriebau** [Spotifyd/spotifyd#104]
Why would I want to run a spotify daemon?
The README.md doesn't really explain what this project does although if I had to guess it will allow you to stream music from spotify to a device which you wouldn't otherwise be able to run the spotify client on?

**Comment by SimonPersson** [comment]
I've updated the README. Does this make it clearer for you?

**Comment by miclill** [comment]
I'm having trouble understanding why you would want to run this as a daemon? My thinking is, that it's a waste of RAM? Am I missing something? Is it accessible via network?

**Comment by SimonPersson** [comment]
It is accessible over the network. As described in the README, you can control it over the Spotify Connect protocol. This means that you can use the Spotify app on Android or iOS to control a Raspberry PI running Spotifyd.

The whole project is inspired by MPD, which works in a similar client/server way. If you want to save on RAM, you can run it with the `--no-daemon` option and just kill it once you are done listening. It uses 20MB of RAM on my machine though, so there's not much point.

**Comment by gavynriebau** [comment]
@SimonPersson thanks for taking the time to update the README.md! 
This provides the needed clarification to interested people who come across this project while browsing github.

**Comment by SimonPersson** [comment]
No worries, thanks for reporting it!
