### ISSUE TITLE
Print failed authentication to console

### ISSUE THREAD

**Issue by g0ierli** [Spotifyd/spotifyd#1040]
Hello, first of all thanks for the great software, it is very very useful.

**Is your feature request related to a problem? Please describe.**
Is there a convenient way (other than a timeout) to
determine if an authentication failed?

I tried --debug-credentials, and --verbose to distinguish between a successful and unsuccessful attempt. But there isn't any useful information other than a timeout when waiting for  'Authenticated as "username" !'.

**Describe the solution you'd like**
It would be very cool, if there is a message for failed authentication (when using [cached] credentials ).

**Describe alternatives you've considered**
Alternativly, password_cmd is called AFTER and if and only if cached credentials failed.

**Additional context**
I use zenity to prompt via 'password_cmd', which works as expected. When i log in the second time, i have to find out somehow that the cached credentials are still valid (any idea how to do this?). Because i don't want to prompt the password every time i connect.

Why do i have to login?
I only see my device with 'spotipy' (sic!), when i successfully authenticated.

**Comment by eladyn** [comment]
Hi!

I just created a PR (#1041), which might address your issue. It errors (and exits) on authentication failures. Not sure though, if it fixes every aspect that you mentioned.

You can try and build from the branch and see if that would work for you.

**Comment by g0ierli** [comment]
Thank you very much!

Works as expected and prints '... Bad credentials'

**Comment by g0ierli** [comment]
Hi, thank you very much!

Works as expected and prints 'Bad credentials' Error

**Comment by eladyn** [comment]
This should now be fixed.
