### ISSUE TITLE
Spotify Premium account dynamically provided from devices

### ISSUE THREAD

**Issue by vaniatoperich** [Spotifyd/spotifyd#1043]
Is it possible not to have spotify username and password for premium account hard coded in config files? 

As user, I would like to have spotifyd acting as homespeaker that all spotify users could use with their own accounts

**Comment by JojiiOfficial** [comment]
Just run it without credentials set up

**Comment by vaniatoperich** [comment]
I tried but then the “speaker” is greyed out in the spotify app

Thanks for your fast reply.

**Comment by JojiiOfficial** [comment]
In that case, please paste your logs since this is another issue

**Comment by vaniatoperich** [comment]
My apologies.. On the second run, to get the logs, it all works perfectly fine.. Thanks!!
