### ISSUE TITLE
Problem with amd64 version

### ISSUE THREAD

**Issue by salicz** [Spotifyd/spotifyd#105]
Hello,
I am sucessfully running amd64 version for about half year. I have updated to recent version. When i run spotifyd, it connect to server and I see in spotify app two same instances of spotify server. When i try to connect to first, spotifyd service hangs:

14:15:27 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 19751896 }
14:15:27 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2230, tv_nsec: 868379480 }
14:15:27 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 25965 }
14:15:27 [DEBUG] librespot_connect::spirc: drop Spirc[0]
14:15:27 [DEBUG] librespot_playback::player: Shutting down player thread ...
14:15:27 [DEBUG] librespot_playback::player: drop Player[0]
14:15:27 [DEBUG] librespot_core::session: drop Session[0]
14:15:27 [DEBUG] librespot::component: drop MercuryManager
14:15:27 [TRACE] tokio_reactor: [<unknown>:330] event Readable Token(0)
14:15:27 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
14:15:27 [DEBUG] tokio_reactor::background: shutting background reactor down NOW
14:15:27 [DEBUG] tokio_reactor::background: background reactor has shutdown
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:871] shutdown; state=State { lifecycle: 0, num_futures: 0 }
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:917]   -> transitioned to shutdown
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:929]   -> shutting down workers
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:933]   -> shutdown worker; idx=3; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:948] signal_stop -- WORKER_SHUTDOWN; idx=3
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:983] worker_terminated; num_workers=3
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:933]   -> shutdown worker; idx=2; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:948] signal_stop -- WORKER_SHUTDOWN; idx=2
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:983] worker_terminated; num_workers=2
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:933]   -> shutdown worker; idx=1; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:948] signal_stop -- WORKER_SHUTDOWN; idx=1
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:983] worker_terminated; num_workers=1
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:933]   -> shutdown worker; idx=0; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:948] signal_stop -- WORKER_SHUTDOWN; idx=0
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:983] worker_terminated; num_workers=0
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:986] notifying shutdown task
14:15:27 [TRACE] tokio_threadpool: [/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.0/src/lib.rs:851] Shutdown::poll
14:15:27 [DEBUG] tokio_core::reactor::timeout_token: cancel timeout 0
14:15:27 [DEBUG] tokio_core::reactor::timeout_token: cancel timeout 1
14:15:27 [DEBUG] librespot_core::session: drop Dispatch

If i try connect to second instance, nothing happends (no hands, no connection...). I use the same settings which i was using about half year (alsa backend, softvol (alsa vol was crashing), default system audio device)...

I would be glad for any hints to get it work again ... thanks

**Comment by SimonPersson** [comment]
Could you try to compile it from source and see if the issue persists?

**Comment by johnhamelink** [comment]
I'm having the same issue with the ARM release on a Raspberry pi zero. It happens for me when I put a space in the `device_name` option.

**Comment by salicz** [comment]
I built from source with exactly same result. However I can confirm, that problem was caused by space in device_name as johnhamelink mentioned. I have fixed it by changin server name. Without space everything is ok. With my previous version from 9.7.2017 spaces in server name did not caused problems... Thank you booth for support.

**Comment by SimonPersson** [comment]
@salicz - I'm glad you got it working!
