### ISSUE TITLE
Prevent spotifyd from being discoverable on WiFi (disable zeroconf)

### ISSUE THREAD

**Issue by ckcr4lyf** [Spotifyd/spotifyd#1057]
**Is your feature request related to a problem? Please describe.**
I am in a coworking space, and when I use spotifyd, potentially anyone in the office could see my daemon and potentially connect to it. This is made worse by other connections crashing spotifyd (https://github.com/Spotifyd/spotifyd/issues/1036)

**The solution I'd like**
Since spotifyd has my credentials, I assume it does not need the Wifi / network discovery at all, since over the internet it should work (Verified: My phone on mobile data and control my spotifyd on wifi)

**Alternatives I;ve considered**
Using iptables or something to block the zeroconf ports - I've not tested this, but I guess it could be a workaround. But would be nice to just not need it

**Comment by eladyn** [comment]
Hi! I just created a PR that should implement more or less the solution that you described (#1059). If you want, you can try that and see if it fixes your problem.

**Comment by ckcr4lyf** [comment]
Confirmed fixed by #1059. 

See: https://github.com/Spotifyd/spotifyd/pull/1059#issuecomment-1046421225
