### ISSUE TITLE
Crash on Connect

### ISSUE THREAD

**Issue by blueo** [Spotifyd/spotifyd#106]
Hi there, I was stoked to come across this project so thanks!
I'm having trouble getting spotify connect working. I'm running on Raspbian GNU/Linux 8 (jessie) (RPi 2) and the latest `spotifyd-2018-03-17-armv6.zip`. 
Start up seems fine with no errors but on connecting from a device the process crashes. I've a sample output with my config file here:
https://gist.github.com/blueo/071e064ac212c78e1b210e60c66a0fe9
I haven't used rust so not exactly sure what I'm looking for but there appears to be a ` Shutting down player thread ...` on line 488 but I'm struggling to trace it back further - if you have any suggestions to debug that would be great.

**Comment by sukkamehu** [comment]
I confirm this issue. Always after around 2 minutes playing it crashes. I'm on RasPi 3 model b with newest Raspian.

**Comment by blueo** [comment]
So an update, I had another crack and found that this was actually a configuration error on my part. I tried with the default settings (ie no config file) and all seems to be working fine! I'm not exactly sure what the config issue was but hey, it works.
