### ISSUE TITLE
Is it possible to prevent spotifyd from controlling the master volume?

### ISSUE THREAD

**Issue by winteriscariot** [Spotifyd/spotifyd#1060]
Before I go into my issue, I want to preface that I don't have a very detailed understanding of the linux sound systems, so it may be that my request is nonsensical in practical terms, in which case that's fine by me. But here goes.

On start, spotifyd will set the volume, changing it from what it was before for other applications (usually resulting in spike of loud music before i turn it down)

is it possible to prevent spotifyd from changing the volume itself entirely, so i can just adjust it for the daemon from something like pavucontrol?

my setup is currently using the default 'alsa' setting for volume controller, but i haven't experimented with the others (i haven't been able to find good definitions of what each do)

**Comment by Lexora** [comment]
I might be completely off off the markhere; but I think it depends on the backend audio you are running: 
```
impl ToString for Backend {
    fn to_string(&self) -> String {
        match self {
            Backend::Alsa => "alsa".to_string(),
            Backend::PortAudio => "portaudio".to_string(),
            Backend::PulseAudio => "pulseaudio".to_string(),
            Backend::Rodio => "rodio".to_string(),
        }
    }
}
```
https://github.com/Spotifyd/spotifyd/blob/master/src/config.rs
https://github.com/Spotifyd/spotifyd/blob/master/src/alsa_mixer.rs 
do you know which one the client is working with on your sys?
