### ISSUE TITLE
Can't start spotifyd

### ISSUE THREAD

**Issue by enrico223** [Spotifyd/spotifyd#1063]
**Description**
I managed to build ```cargo build --release``` with all the flags, I have the config file set up, I copied the ```/target/release/spotifyd``` to ```/usr/bin/```. 

**To Reproduce**
1. ```cargo build --release``` with all the flags
2. set up the config file
3. set up the spotifyd.service
4. launch ```spotifyd```
5. See error 

**Expected behavior**
Spotifyd starting

**Logs**
This is the output of ```spotifyd --verbose```
<details><summary>Click to show logs</summary>

```
Error: 
   0: could not load the config file
   1: invalid TOML value, did you mean to use a quoted string? at line 3 column 13

Location:
   /builddir/build/BUILD/rustc-1.58.1-src/library/core/src/result.rs:1911

note:
   the config format should be valid TOML
   we recently changed the config format, see https://github.com/Spotifyd/spotifyd/issues/765

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
</details>

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Fedora 35
- Spotifyd: 0.3.3
- cargo: 1.58.0

**Additional context**
The following is the output of ```systemctl --user status spotifyd.service```

```
● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/home/enrico/.config/systemd/user/spotifyd.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2022-03-03 18:57:38 CET; 5s ago
       Docs: https://github.com/Spotifyd/spotifyd
    Process: 47539 ExecStart=/usr/bin/spotifyd --no-daemon (code=exited, status=1/FAILURE)
   Main PID: 47539 (code=exited, status=1/FAILURE)
        CPU: 13ms 
```

**Comment by JojiiOfficial** [comment]
Please read the error before creating a new issue:
`   1: invalid TOML value, did you mean to use a quoted string? at line 3 column 13`
