### ISSUE TITLE
Err(Unauthorized) when fetching metadata

### ISSUE THREAD

**Issue by deivi98** [Spotifyd/spotifyd#1074]
I had this running with my own client id for almost 8 hours today. I didn't encounter any rate limits, however there still seem to be some issues. For the most part metadata was working fine but intermittently I got some errors:
```Loading <Way Down We Go - Recorded at Spotify Studios NYC> with Spotify URI <spotify:track:3inSmIa388icRdpDi5ecJd>
<Way Down We Go - Recorded at Spotify Studios NYC> loaded
Running "\"/home/notify-spotifyd.sh\"" using "/usr/bin/zsh" with environment variables {"PLAYER_EVENT": "change", "TRACK_ID": "3inSmIa3↷
Couldn't fetch metadata from spotify: Err(Unauthorized)
Couldn't fetch metadata from spotify: Err(Unauthorized)
Couldn't fetch metadata from spotify: Err(Unauthorized)
Couldn't fetch metadata from spotify: Err(Unauthorized)

... a few more repeats of the "Couldn't fetch metadata line ...

Couldn't fetch metadata from spotify: Err(Unauthorized)
Loading <Mr. Jones - Live At Chelsea Studios, New York/1997> with Spotify URI <spotify:track:0pjOjoHMJrerHhiXNRs3GK>
Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Unhandled DBus message: (Error, None, None, None)
<Mr. Jones - Live At Chelsea Studios, New York/1997> loaded
```
Over the course of the time I had spotifyd running I had this show up twice.
During these error blocks `playerctl metadata` did not return anything.

_Originally posted by @t4k1t in https://github.com/Spotifyd/spotifyd/issues/503#issuecomment-595356352_

**Comment by deivi98** [comment]
Hi there, I am having the exact same issue. It's been happening for a while now, I have not been able to find a reason or a workaround. The only thing that works is manually killing spotifyd and restarting it. With the time, it happens again over and over.

Moving to a separate issue as this is not a bad login or a rate exceeded error.

**Comment by NNEU-1** [comment]
This is a known issue, please look around the issues section.
