### ISSUE TITLE
update rspotify cargo library in Cargo.toml

### ISSUE THREAD

**Issue by wael444** [Spotifyd/spotifyd#1075]
**Description**
from what i assume, Spotify API has added a new type. the old version did not know how to handle it.

**To Reproduce**
1. play anything from the Liked Songs playlist

**Expected behavior**
no errors

**Logs**
<details><summary>Click to show logs</summary>

```
Couldn't fetch metadata from spotify: Err(ErrorMessage { msg: "convert result failed, reason: Error(\"unknown variant `collection`, expected one of `artist`, `album`, `track`, `playlist`, `user`\", line: 8, column: 25); content: [\"{\\n  \\\"timestamp\\\" : 1649369609938,\\n  \\\"context\\\" : {\\n    \\\.... < a bunch of other things.
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [x] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
- OS: Void 5.16.18_1 x86_64
- Spotifyd: 0.3.3
- cargo: 1.57.0

Related: https://github.com/Rigellute/spotify-tui/issues/960

There is also: https://github.com/Rigellute/spotify-tui/issues/912, but i don't know why it still happens.

Updating rspotify in Cargo.toml should fix this.

**Comment by NNEU-1** [comment]
> Updating rspotify in Cargo.toml should fix this.

Why don't you have a go at it and let us know how it went ? 😝 

The new rspotify has broken compatibility with the old version in pretty much every way. It it was as trivial as updating the dependency in the cargo file, I would have done it already.

**Comment by wael444** [comment]
> The new rspotify has broken compatibility with the old version in pretty much every way. If it was as trivial as updating the dependency in the cargo file, I would have done it already.

Oh. Sorry.

**Comment by jennarbates** [comment]
I am also having this issue and am not sure how to fix it
