### ISSUE TITLE
Delay in usage

### ISSUE THREAD

**Issue by stevenveenma** [Spotifyd/spotifyd#108]
Thanks for this very useful spotify daemon that I use frequently. Being able to use the Spotify frontend is very usefull and the daemon is reckognized very fast. But I have one issue with it. Using spotifyd with a RPI thats on for long periods I  found after a longer period some delay occurs when I execute commands in the spotify frontend. Selecting a new piece of music or changing the volume can take seconds of time. When I restart spotifyd the problem is solved. Do you know the reason for this delay and can it be solved?

**Comment by SimonPersson** [comment]
I haven't seen this issue before. You could try to generate a verbose log from when it is slow. Also check how much RAM and CPU is used at that point. Maybe that'll give us some clues.

**Comment by fertigfutter** [comment]
Same issue here. Only the first connection/command of the day is slow, about 5-10s. Maybe Rpi specific or a problem on my client(s) resp. firewalls. Will try to log...

**Comment by stevenveenma** [comment]
I did some tests and it turned out that Spotifyd is not the reason of the delay/latency. This is caused by the ecasound/arta chain (which is complex as this device is used as a dsp). So no blame on Spotifyd, its excellent!

**Comment by SimonPersson** [comment]
@stevenveenma - Thanks for the report. I'll close this then.
