### ISSUE TITLE
Mixer not being recognized in spotifyd.conf

### ISSUE THREAD

**Issue by rwjack** [Spotifyd/spotifyd#1083]
**Description**
Alsa bluetooth mixer doesn't seem to be working on RPi Zero-W
Audio works on the bluetooth speaker:
```
root in devpi in ~/.config/spotifyd ❯ aplay ~/piano2.wav
Playing WAVE '/root/piano2.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
```

**To Reproduce**
```
root in devpi in ~/.config/spotifyd ❯ pactl list cards short
0	bluez_card.B8_D5_0B_12_65_D8	module-bluez5-device.c
```

spotifyd.conf:
```
[global]
username = "x"
password = "x"
backend = "alsa"
device = "sysdefault" # Given by aplay -L # ALSO TRIED pulse
mixer = "bluez_card.B8_D5_0B_12_65_D8" # ALSO TRIED PCM
volume-controller = "alsa" # or alsa_linear, or softvol
#onevent = command_run_on_playback_event
device_name = "devpi"
bitrate = 160 #96|160|320
cache_path = "cache_directory"
volume-normalisation = true
normalisation-pregain = -10
```

**Expected behavior**
Song plays on bluetooth speaker

**Logs**
```
● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/etc/systemd/system/spotifyd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-04-24 14:17:33 BST; 18s ago
       Docs: https://github.com/Spotifyd/spotifyd
   Main PID: 2775 (spotifyd)
      Tasks: 2 (limit: 415)
        CPU: 843ms
     CGroup: /system.slice/spotifyd.service
             └─2775 /usr/local/bin/spotifyd --no-daemon

Apr 24 14:17:34 devpi spotifyd[2775]: Country: "RS"
Apr 24 14:17:34 devpi spotifyd[2775]: Using Alsa sink with format: S16
Apr 24 14:17:51 devpi spotifyd[2775]: Loading <Rise Up (feat. Vamero)> with Spotify URI <spotify:track:46lyJh9GYmWsHez3EsvmAx>
Apr 24 14:17:51 devpi spotifyd[2775]: Resolved 50 tracks from <"spotify:station:playlist:0zLS8rpKCrgl5g8IfFJ0Xn">
Apr 24 14:17:51 devpi spotifyd[2775]: <Rise Up (feat. Vamero)> (182000 ms) loaded
Apr 24 14:17:52 devpi spotifyd[2775]: Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENODEV: No such device'
Apr 24 14:17:52 devpi spotifyd[2775]: Could not start audio: Alsa error: PCM open failed
Apr 24 14:17:52 devpi spotifyd[2775]: Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENODEV: No such device'
Apr 24 14:17:52 devpi spotifyd[2775]: Could not start audio: Alsa error: PCM open failed
Apr 24 14:17:52 devpi spotifyd[2775]: PANIC: Shutting down spotifyd. Error message: called `Option::unwrap()` on a `None` value
```

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
Downloaded from git releases

**Versions (please complete the following information):**

- OS: Raspbian GNU/Linux 11 \n \l
- Spotifyd: v0.3.3

This is very likely a configuration error, but still the documentation remains unclear. What should be put in the mixer variable? pulseaudio is very confusing and `pacmd list sink` returns a bunch of irelevant entries and information.

**Comment by TheBasedDoge** [comment]
did you ever figure this out?

**Comment by rwjack** [comment]
@TheBasedDoge Negative, I'm still at a point where I have the RPi connected to a bluetooth speaker, and see it's name in spotify devices, although as soon as I select it the playback stops and nothing happens.

**Comment by TheBasedDoge** [comment]
I finally got mine to work after i posted that, and I was having the same issue. The problem was it was crashing because of the wrong device. Here is my working config


[global]
username = 
password = 
backend = "alsa"
device = "default"
mixer = "PCM"
volume-controller = "alsa" # or alsa_linear, or softvol
#onevent = command_run_on_playback_event
device_name = "Pipod"
bitrate = 160
cache_path = "cache_directory"
volume-normalisation = true
normalisation-pregain = -10

**Comment by eladyn** [comment]
Hi @rwjack!

I did some testing on my system, and apparently spotifyd doesn't consider an invalid “mixer” parameter a critical error. At least for me, it just prints: `Couldn't set volume: "Couldn't find selem with name 'invalid_mixer'."`

So your real problem seems to be the value of `device` if I'm not mistaken. Would you be able to paste the output of `aplay -L` here?

Apart from that, valid values for `mixer` should be printed by the command `amixer -D <device> scontrols`, where `<device>` is the value that you used for `device` in `spotifyd` as well.

Hope this helps you somehow!

**Comment by rwjack** [comment]
Hey @eladyn,

I'm trying a wired connection now and since I'm using an RPi Zero, I've plugged a cable in the secondary available microUSB port on it and I'm using the Logitech z407 speakers, also plugged into the MicroUSB via an adapter (RPi <- (microUSB <-> USB-A) -> microUSB adapter -> Z407). Here's the output of `aplay -L`

```
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Default Audio Device
sysdefault
    Default Audio Device
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
default:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct sample mixing device
usbstream:CARD=vc4hdmi
    vc4-hdmi
    USB Stream Output
```

Anyways, you were correct! The device part was the issue, and I had a clear understanding that the only available options are Master and Capture after running your command. (Now I'm using `master` in my spotifyd config)
```
root in devpi in ~ took 14s ❯ amixer -D default scontrols
Simple mixer control 'Master',0
Simple mixer control 'Capture',0
```

So now I can change the volume and it seems that the song will continue to play on the RPi, where it crashed spotifyd before, although I'm still getting no output on my speakers. This is probably due to the `device` config parameter. Any ideas what I should be looking for?

**Comment by rwjack** [comment]
After switching the MicroUSB cable for a better one, I can now see the device.

`aplay -L`
```
root in devpi in ~ ❯ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
sysdefault
    Default Audio Device
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct sample mixing device
usbstream:CARD=vc4hdmi
    vc4-hdmi
    USB Stream Output
hw:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    Hardware device with all software conversions
sysdefault:CARD=Z407
    Logi Z407, USB Audio
    Default Audio Device
front:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    Front output / input
surround21:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Z407,DEV=0
    Logi Z407, USB Audio
    Direct sample mixing device
usbstream:CARD=Z407
    Logi Z407
    USB Stream Output
```

`lsusb`
```
root in devpi in ~ ❯ lsusb
Bus 001 Device 003: ID 046d:0a4c Logitech, Inc. Logi Z407
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

So should I use `usbstream` for the `device` parameter in spotifyd?

**Comment by rwjack** [comment]
This is the config that ended up working. Thanks for all the tips, though I still hate pulseaudio, alsa, aplay, amixer and the entire family of confusing commands.
```
device = "default:CARD=Z407" # Given by aplay -L
mixer = "Master"
```

**Comment by eladyn** [comment]
Great to hear that it is working now!

FYI: It seems that the default audio card in your case is the HDMI output, so you should be able to change this to the correct card via [`raspi-config`](https://www.raspberrypi.com/documentation/computers/configuration.html#changing-the-audio-output) or, for example, [this guide](https://www.alsa-project.org/wiki/Setting_the_default_device). Then you could probably just use `default` as output device.

**Comment by vinaynaik121** [comment]
> I finally got mine to work after i posted that, and I was having the same issue. The problem was it was crashing because of the wrong device. Here is my working config
> 
> [global] username = password = backend = "alsa" device = "default" mixer = "PCM" volume-controller = "alsa" # or alsa_linear, or softvol #onevent = command_run_on_playback_event device_name = "Pipod" bitrate = 160 cache_path = "cache_directory" volume-normalisation = true normalisation-pregain = -10

Thanks a lot man !!! its worked
