### ISSUE TITLE
Spotifyd won't load any values from config file

### ISSUE THREAD

**Issue by diniamo** [Spotifyd/spotifyd#1090]
**Description**
Systemd won't load any values from my config file ($HOME/.config/spotifyd/spotifyd.conf)

**To Reproduce**

1. Run `spotifyd`
2. Console says no value found for username, password, etc...

**Expected behavior**

Spotifyd starts working as intended

**Logs**
<details><summary>Click to show logs</summary>

```
Loading config from "/home/diniamo/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: None, username_cmd: None, password: None, password_cmd: None, use_keyring: false, use_mpris: None, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: None, bitrate: None, initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: None } }
Found user shell: Some("/usr/bin/zsh")
No username specified. Checking username_cmd
No username_cmd specified
No password specified. Checking password_cmd
No password_cmd specified
No proxy specified
```

</details>

**Versions (please complete the following information):**

- OS:  Arch Linux 5.8.13
- Spotifyd:  0.3.3
- cargo:  1.61.0

**Comment by diniamo** [comment]
```
username = ""
password = ""

backend = "pulseaudio"

volume_normalisation = false

device_name = "diniamo-PC"
device_type = "computer"
```
The config file if needed

**Comment by eladyn** [comment]
Your problem is almost certainly that you didn't specify the "section", where the values in your configuration file are valid. You'd need to add

```toml
[global] # or [spotifyd]
username = ""
# ...
```

at the beginning. I'm currently wondering whether this is necessary, or if we could also use values that are specified without a containing section.

**Comment by diniamo** [comment]
Hm, seems like I missed that when reading the wiki, thank you.

Although I feel like there should be some kind of feedback instead of just ignoring the config file
