### ISSUE TITLE
Cannot play audio in spotifyd on a macOS with portaudio + skipping

### ISSUE THREAD

**Issue by dechowpen** [Spotifyd/spotifyd#1091]
**Description**
This is a clear replica of #637
When I play any song, it keeps skipping it because it is not able to "load unencrypted file". On top the audio backend does not output any sound.

**To Reproduce**
1. Start `spotifyd --verbose --no-daemon`
2. Open spotify-tui and start a track
3. No audio output, and the song skips in spotify-tui

**Expected behavior**

Audio output in spotify-tui + and no skipping

**Logs**
Abbreviated.... (it loads the config fine)
<details><summary>Click to show logs</summary>
loop poll - 307.893375ms
loop time - Instant { t: 180811555986 }
loop process, 29.791µs
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 184.875µs
loop time - Instant { t: 180811561635 }
loop process, 21.041µs
kMessageTypeLoad "" webapi-a875a327e70b4167a95d53a533999870 98165929 1655808051746 kPlayStatusPlay
State: context_uri: "spotify:playlist:0HdPHsPr2i4vxekMU1EDV9" index: 10 position_ms: 753 status: kPlayStatusPlay position_measured_at: 1655808058376 context_description: "" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 10 track {gid: "\337\262\343\301;\014G\203\214\366\223\322\247\302\353\337"} track {gid: "I}n\\\036nO\333\267\021\304p\231\213'\016"} track {gid: "\231P7\314\032%G&\237\350\020\227h\001\244\360"} track {gid: "\326.k\310\023\200M\341\255\360\030\177\352\346\327:"} track {gid: "saVq\024\261L\332\217:\211\253m\304]H"} track {gid: "\357\250\034\202\223\253CC\272\243\224d\321E\252\340"} track {gid: "\342Q\316MY\342N]\267\321\200\250\305\305N\222"} track {gid: "\366O\351\247\270=KP\204\2126$J\2701;"} track {gid: "\221\265\377\345\342xJ{\210|\325\277\231\017\276W"} track {gid: ">\n\363\301\225\027@\252\202,\006?\313\205\206\317"} track {gid: "4&{\357s\222L\336\211Fu\355\3161\276="} track {gid: "\321\365a5\316\364K=\227\231\303\306\321\004\235\307"}
Frame has 12 tracks
Sending status to server: [kPlayStatusPlay]
command=Load(SpotifyId { id: 69319676769119681209560980879207153213, audio_type: Track }, true, 753)
Sending status to server: [kPlayStatusPlay]
scheduling Read for: 4
flushing framed transport
writing; remaining=1330
framed transport flushed
loop poll - 177.125µs
loop time - Instant { t: 180811594951 }
loop process, 23.208µs
scheduling Read for: 4
flushing framed transport
writing; remaining=83
framed transport flushed
loop poll - 68.458µs
loop time - Instant { t: 180811597607 }
loop process, 23.375µs
event Writable Token(16777220)
loop process - 1 events, 0.000s
event Readable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 23.46ms
loop time - Instant { t: 180812161492 }
loop process, 17.041µs
loop poll - 2.208µs
loop time - Instant { t: 180812162922 }
loop process, 13.708µs
event Writable Token(16777220)
loop process - 1 events, 0.000s
event Readable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 9.552416ms
loop time - Instant { t: 180812392674 }
loop process, 405.958µs
Loading <A R E S> with Spotify URI <spotify:track:1ApbFOjsHJZUbkhQcDnH3v>
new AudioKeyManager
Downloading file 4f46dcb8de05159a4e7adb17a6c1622dcc9c06d6
new ChannelManager
scheduling Read for: 4
flushing framed transport
writing; remaining=102
framed transport flushed
loop poll - 1.053166ms
loop time - Instant { t: 180812428348 }
loop process, 15.541µs
consuming notification queue
loop poll - 39.666µs
loop time - Instant { t: 180812429850 }
loop process, 13.791µs
event Writable Token(16777220)
loop process - 1 events, 0.000s
event Readable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 12.203916ms
loop time - Instant { t: 180812723224 }
loop process, 15.416µs
channel error: 2 1
Unable to load encrypted file.
loop poll - 50.625µs
loop time - Instant { t: 180812725028 }
loop process, 15.875µs
Unable to load <SpotifyId { id: 69319676769119681209560980879207153213, audio_type: Track }>
Skipping to next track

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [x] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: macOS 12.4
- Spotifyd: 0.3.2
- cargo: (pre-built binary)

**Comment by eladyn** [comment]
Hi!

Your logs (and those from the other issue) seem to describe a very similar problem to [this upstream bug](https://github.com/librespot-org/librespot/issues/972). (`channel error: 2 1`)
If that is the case, you can try either [this](https://github.com/librespot-org/librespot/issues/972#issuecomment-1059073001), or [this](https://github.com/librespot-org/librespot/issues/972#issuecomment-1061007499) workaround.

Hope this helps!
