### ISSUE TITLE
Windows version of spotifyd to enable spotify-qt

### ISSUE THREAD

**Issue by the12fear** [Spotifyd/spotifyd#1096]
There is a Windows version of spotify-qt, however there is no Window version of spotifyd to act as a client that it interfaces with.

The reason why I request this is because I am done with the normal Spotify client sucking up all my system resources, and saw this as an integral part of the spotify-qt solution.

spotifyd is an important dependency for the spotify-qt solution to work.

Ideally there would be a version of spotifyd that works on Windows as well as Linux distros.

Is there a possibility/timeline surrounding an outcome for a Windows version?

Thanks

**Comment by eladyn** [comment]
See #602. This has been around for quite a long time and I have no idea, if this is going to.be merged. But you could certainly try to build spotifyd from this PR and see if it works.

Another option would be to just use plain [librespot](https://github.com/librespot-org/librespot), which should work on windows out of the box.

**Comment by the12fear** [comment]
@eladyn you are a legend! thanks, i'll give librespot a try, i had no idea it existed

**Comment by the12fear** [comment]
i'll close this out in lieu of #602
