### ISSUE TITLE
spotifyd connects but not discoverable on local client (spt) until device found on official client

### ISSUE THREAD

**Issue by stevensonmt** [Spotifyd/spotifyd#1098]
I'd like to use spotifyd as the backend for the spotify-tui client. I have set up spotifyd to run as a systemd service.
Steps to reproduce:
1. Check that spotifyd is running with `systemctl --user status spotifyd.service` -- this looks good, connection went through
2. Start spotify-tui and try to play track. Error that no device is available.
3. Open Spotify app on phone. Select device -> list includes spotifyd.
4. Restart spotify-tui and try to play track. All good.
  
How do I make spotifyd discoverable to spotify-tui without having to open the phone app first?

**Comment by firestack** [comment]
@stevensonmt Did you select which device to use in spotify_tui using the "d" key?
Did the errors happen after selecting the device?

**Comment by stevensonmt** [comment]
The device does not appear until after discovered on another client
