### ISSUE TITLE
PANIC: Shutting down spotifyd. Error message: Unknown backend: alsa.

### ISSUE THREAD

**Issue by leephillips** [Spotifyd/spotifyd#1099]
I tried the Linux "full" and "slim" binaries. Both only seem to support pulseaudio. Is there a way to get alsa support, perhaps by compiling?

**Comment by eladyn** [comment]
Hmm, that is strange. When I download [`spotifyd-linux-full.tar.gz`](https://github.com/Spotifyd/spotifyd/releases/download/v0.3.3/spotifyd-linux-full.tar.gz) from [here](https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.3), I get a binary that supports `alsa`, `pulseaudio` and `rodio`.

```console
# ./spotifyd --help
spotifyd 0.3.3
Simon Persson <simon@flaskpost.org>, Sven Lechner <sven.lechner@rwth-aachen.de>
A Spotify daemon
...
OPTIONS:
    -b, --backend <string>
            The audio backend to use [possible values: alsa, pulseaudio, rodio]
...
```

However, you can of course compile `spotifyd` yourself as well: `cargo install spotifyd --features "alsa_backend"`

Hope this helps!

**Comment by leephillips** [comment]
I downloaded raspotify (https://github.com/dtcooper/raspotify) which Just Worked™. Thank you.

**Comment by eladyn** [comment]
Great to hear that! Do you have further interest in investigating the original issue, or can it be closed?
