### ISSUE TITLE
CUR_PLAYING shows current song even when paused.

### ISSUE THREAD

**Issue by jonlorusso** [Spotifyd/spotifyd#11]
Is there anyway to determine if the stream is currently playing/paused?

**Comment by SimonPersson** [comment]
I'll change `CUR_PLAYING` to mention if the stream is paused. I suppose you could do `sc pause && sc pause` until I come up with a fix.

**Comment by jonlorusso** [comment]
Alternatively, you could add a STATUS command.

**Comment by saevarb** [comment]
I disagree that this is an issue, but it would perhaps be nice having a status command as well as having the current time and duration of the currently playing song available. Perhaps that can be included in the status command?

**Comment by PontusPersson** [comment]
I agree with saevarb. A status command that displays the current state of the player and elapsed time and duration of the current song would really be helpfull. Especially if you are writing a "fancier" client than sc.

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
