### ISSUE TITLE
The onevent setting in the suggested configuration crashes spotifyd

### ISSUE THREAD

**Issue by FungusHumungus** [Spotifyd/spotifyd#110]
This line -

onevent = command_run_on_playback_events

It panics with a "no such file" error. Commenting out the setting and it all works fine.

It might be worth making the the documentation a bit more explicit that it shouldn't just be copied straight in as lazy folks such as myself will generally do!

**Comment by Neraeh** [comment]
Maybe replacing it with `onevent = /usr/bin/echo Playback event! #command_run_on_playback_event` can do the trick, and it can help some folks to recognize when this is triggered by checking the logs

**Comment by SimonPersson** [comment]
I've adopted the suggestion by @Neraeh - Now we just hope that any system compatible with spotifyd has a `/usr/bin/echo` binary :)
