### ISSUE TITLE
Call for action/testing

### ISSUE THREAD

**Issue by mainrs** [Spotifyd/spotifyd#1104]
Hello!

A lot of dependabot security warnings popped up for this repository. #1103 should fix a lot of them since they are transitive dependencies of tokio.

The majority of the remaining ones need refactoring since the API surface of the libraries changed (for example `rspotify`). 

It would be great if someone could check the following PRs and see if they work as expected. I do not have access to my Linux machine right now. Thanks!

- [ ] #1103

**Comment by eladyn** [comment]
I compiled and ran that branch successfully (with all features enabled), so everything should be fine. :)

PS: The `rspotify` upgrade is contained in #1079.

**Comment by slondr** [comment]
Looks like dependabot is happy now...
