### ISSUE TITLE
Thread 'main' panicked at 'Couldn't initialize logger'...

### ISSUE THREAD

**Issue by chinchilla-manaka** [Spotifyd/spotifyd#1107]
**Description**

I am using `Linux OTM 5.19.2-artix1-2 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 10:48:27 +0000 x86_64 GNU/Linux` from base and when I configured spotifyd, it showed the following error:
`thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: None })), backtrace: None })', src/main.rs:39:51
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

**To Reproduce**

1. Run spotifyd without [syslog-ng](https://github.com/syslog-ng/syslog-ng) installed
2. See error

**Expected behavior**

spotifyd working

**Logs**

<details><summary>Click to show logs</summary>

```
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }), State { next_error: None, backtrace: Some(   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: main
  10: <unknown>
  11: __libc_start_main
  12: <unknown>
) })), backtrace: Some(   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: main
  10: <unknown>
  11: __libc_start_main
  12: <unknown>
) })', src/main.rs:39:51
stack backtrace:
   0:     0x561c92caba4d - <unknown>
   1:     0x561c92cd3f6c - <unknown>
   2:     0x561c92ca4c61 - <unknown>
   3:     0x561c92cad4a5 - <unknown>
   4:     0x561c92cad1c6 - <unknown>
   5:     0x561c92cada36 - <unknown>
   6:     0x561c92cad927 - <unknown>
   7:     0x561c92cabf04 - <unknown>
   8:     0x561c92cad659 - <unknown>
   9:     0x561c925e53b3 - <unknown>
  10:     0x561c925e54a3 - <unknown>
  11:     0x561c926764cb - <unknown>
  12:     0x561c9265a873 - <unknown>
  13:     0x561c92638a29 - <unknown>
  14:     0x561c92c9d92e - <unknown>
  15:     0x561c926770c2 - main
  16:     0x7f721d1342d0 - <unknown>
  17:     0x7f721d13438a - __libc_start_main
  18:     0x561c925e5655 - <unknown>
  19:                0x0 - <unknown>
```

</details>

**Versions (please complete the following information):**

- OS: 
- Spotifyd: [spotifyd-full-git 0.2.17.7.g8a82bec-1](https://aur.archlinux.org/packages/spotifyd-full-git) & [spotifyd 0.3.3-1](https://archlinux.org/packages/community/x86_64/spotifyd/)
- cargo: 1.63.0

**Additional context**
I think it'd be nice if a more specific error was written. I looked up the line of code where the problem was and I figured out it was because I didn't have **syslog-ng** installed. Since I tested both programs on the latest Artix Linux with Runit, here are the steps I made in order to solve this problem:
`sudo pacman -Syu syslog-ng syslog-ng-runit`
`sudo ln -s /etc/runit/sv/syslog-ng /etc/runit/runsvdir/default`
`sudo sv start syslog-ng`

Once done that, I was able to launch spotifyd without further issues.

**Comment by TornaxO7** [comment]
thank you for pointing this out! I was looking for the issue xD
