### ISSUE TITLE
Play a song from command line

### ISSUE THREAD

**Issue by PaoloRondot** [Spotifyd/spotifyd#1109]
Dear Spotifyd community,

I want to play a specific song or playlist in a script I am writing. For example to play a playlist at bed time and for 1 hour.
I don't know what command to use to play the song or playlist given its URI.

Is it even possible?
Many thanks.
Paolo.

**Comment by eladyn** [comment]
Hi!

You can use the DBus MPRIS interface to control a running `spotifyd` instance. A simple shell script, to do what you describe, could look like this:

```bash
#!/bin/bash
ITEM_URI="spotify:playlist:37i9dQZF1DZ06evO0sWQWQ"

dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:$PLAYLIST_URI"
# sleep for one hour
sleep 3600
# if you want `spotifyd` to quit
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Quit
# instead of `.Quit`, you can also use `.Pause` or `.Stop`
```

This requires the `dbus_mpris` feature to be enabled. (If you're on a headless system, you'll need additional tweaks for this to work.)

Hope this helps you! Let me know if you have any further questions!

**Comment by PaoloRondot** [comment]
Many thanks @eladyn!

I get the following error when I run the first dbus-send command line:
```
pi@raspberrypi:~ $ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:spotify:track:4jB8td98pbRVvTqtQ7I3MI"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotifyd was not provided by any .service files
```
Do I need to configure other things?
Thanks again!

**Comment by eladyn** [comment]
Ah, right. This means that `spotifyd` hasn't registered itself on the session bus. Does it work when you set `use_mpris = true` in the configuration file?

**Comment by PaoloRondot** [comment]
so I just added to `~/.config/spotifyd/spotifyd.conf`, the line `use_mpris = true`. I rebooted my Raspberry, and I get the same error:
```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotifyd was not provided by any .service files
```
Did I add it to the right configuration file?

**Comment by eladyn** [comment]
Hmm, interesting. Would you be able to post the output of `spotifyd --no-daemon --verbose`? This might help us get further.

**Comment by PaoloRondot** [comment]
I have the answer `bash: spotifyd: command not found`. I guess there's an intermediate step I need to do..?

**Comment by eladyn** [comment]
How did you install and start `spotifyd`? You should somewhere have that binary, from where you can execute it.

**Comment by PaoloRondot** [comment]
Okay I was able to run the command. `/home/pi/spotifyd --no-daemon --verbose`
The answer of this command is rather long, I didn't post everything:
```
Loading config from "/home/pi/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, use_mpris: None, on_song_change_hook: None, cache_path: Some("cache_directory"), no-audio-cache: false, backend: Some(Alsa), volume_controller: None, device: None, control: None, mixer: None, device_name: Some("Preset"), bitrate: Some(Bitrate320), initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: None } }
Found user shell: Some("/bin/bash")
No proxy specified
registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
Using software volume controller.
registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
Zeroconf server listening on 0.0.0.0:34075
registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
Connecting to AP "ap.spotify.com:443"
found interface Interface { name: "wlan0", addr: V4(Ifv4Addr { ip: 192.168.1.104, netmask: 255.255.255.0, broadcast: Some(192.168.1.255) }) }
found interface Interface { name: "wlan0", addr: V6(Ifv6Addr { ip: 2a02:aa11:b280:e980:17a4:d941:1bd8:1376, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
sending packet to 224.0.0.251:5353
found interface Interface { name: "wlan0", addr: V4(Ifv4Addr { ip: 192.168.1.104, netmask: 255.255.255.0, broadcast: Some(192.168.1.255) }) }
found interface Interface { name: "wlan0", addr: V6(Ifv6Addr { ip: 2a02:aa11:b280:e980:17a4:d941:1bd8:1376, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
sending packet to [ff02::fb]:5353
received packet from 192.168.1.104:5353
received packet from 192.168.1.104:5353 with no query
received packet from 192.168.1.104:5353
received packet from 192.168.1.104:5353 with no query
received packet from [fe80::a392:747:6edc:f4b8%3]:5353
received packet from [fe80::a392:747:6edc:f4b8%3]:5353 with no query
received packet from [2a02:aa11:b280:e980:17a4:d941:1bd8:1376]:5353
received packet from [2a02:aa11:b280:e980:17a4:d941:1bd8:1376]:5353 with no query
registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
flushing framed transport
writing; remaining=140
framed transport flushed
attempting to decode a frame
frame decoded from buffer
Authenticated as "2123u7qt54jd3sdilikqxajia" !
new Session[0]
flushing framed transport
framed transport flushed
attempting to decode a frame
frame decoded from buffer
Session[0] strong=3 weak=1
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
Country: "FR"
attempting to decode a frame
new Spirc[0]
canonical_username: 2123u7qt54jd3sdilikqxajia
new MercuryManager
flushing framed transport
writing; remaining=11
framed transport flushed
flushing framed transport
writing; remaining=72
framed transport flushed
input volume:65535 to mixer: 65535
flushing framed transport
writing; remaining=358
framed transport flushed
new Player[0]
Using Alsa sink with format: S16
command=AddEventSender
command=VolumeSet(65535)
flushing framed transport
framed transport flushed
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
flushing framed transport
framed transport flushed
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
flushing framed transport
framed transport flushed
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
subscribed uri=hm://remote/user/2123u7qt54jd3sdilikqxajia/ count=0
flushing framed transport
framed transport flushed
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
kMessageTypeNotify "RONDOT" 38121ecc2d703942fbbb168e4b9d827f7ae2502f 1866026381 1661870885512 kPlayStatusStop
received packet from 192.168.1.192:5353
received question: IN _spotify-connect._tcp.local
```

**Comment by eladyn** [comment]
Alright, that clears some things up. There are basically two problems:

- The version that you downloaded (`-slim`) does not contain support for the `dbus_mpris` feature. For this to work, you'd need to download a `-full` binary. If there is no prebuilt binary for your architecture, you might have to compile `spotifyd` yourself. Instructions to do this are [here](https://spotifyd.github.io/spotifyd/installation/Ubuntu.html) (assuming that you are on RaspberryPi OS).
  Now, at the compile step, you just need to add `--features "dbus_mpris"` to the command.

- By default, `spotifyd` needs a running **session** bus for its MPRIS interface.[^1] Since you are running `spotifyd` from a user session, you should be fine here. But if it still doesn't work after the steps outlined above, we might need some additional tweaking.

[^1]: For an explanation of the difference between `session` and `system` buses, see the *DESCRIPTION* section of [this page](https://dbus.freedesktop.org/doc/dbus-daemon.1.html).

**Comment by eladyn** [comment]
Yeah, exactly. If you'd like to further customize the features that you need, have a look at [this section](https://spotifyd.github.io/spotifyd/installation/index.html#feature-flags).

**Comment by PaoloRondot** [comment]
I just tried to compile the files and get the following after a few minutes of compiling:
```
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/home/pi/spotifyd/target/release/build/libdbus-sys-75cb7da35bbd04d7/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }', /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/libdbus-sys-0.2.1/build.rs:6:70
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
any idea where it could come from?

**Comment by eladyn** [comment]
You need the corresponding headers: `sudo apt install libdbus-1-dev`

**Comment by PaoloRondot** [comment]
Alright, it works like a charm. 
I really want to thank you very much for your time and help!
Paolo.

**Comment by eladyn** [comment]
Glad to hear that it's working and that I was able to help! You're welcome.

**Comment by PaoloRondot** [comment]
Hello there, I hope it is okay that I reopen this issue one year later. It is tightly linked
When I run the command: `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:spotify:playlist:1I4a8kzvhUUBRrdCRIpLtT"`, I get the response `method return time=1695143265.871242 sender=:1.10 -> destination=:1.12 serial=5 reply_serial=2` (with incrementing destination each time I run it), but nothing comes out of the speaker (connected by jack directly to the RPI).
Do you have an idea what causes this?

Many thanks.
Paolo

**Comment by eladyn** [comment]
@PaoloRondot At least by the description, I'm rather clueless. Is there something in the output of spotifyd that seems like it could be related?

**Comment by ciembor** [comment]
Actually will publish soon a small tool for playing playlists, albums by name, and basic operations (prev, next, pause, play, shuffle, volume). It doesn't use D-Bus but `spotipy`, that is Spotify API. I started wondering how to get currently playing track without doing request to API each second and this is how I found out spotifyd uses DBus...

**Comment by eladyn** [comment]
Oh, yeah. That behaviour is expected. Before `spotifyd` can start playing, the playback needs to be transferred. We introduced a DBus endpoint for that some time ago. So it might work if you call the method `rs.spotifyd.Controls.TransferPlayback` in `/rs/spotifyd/Controls`?

**Comment by PaoloRondot** [comment]
For the record, the full command is then:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd.instance<> /rs/spotifyd/Controls rs.spotifyd.Controls.TransferPlayback`

**Comment by ciembor** [comment]
Guys, if you are interested, I published spotify-cmd on pip, you may use it without D-Bus:

https://github.com/ciembor/spotify-cmd
