### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by clkamp** [Spotifyd/spotifyd#1110]
Would it be possible, that a new release is created? Version 0.3.3 is now already 8 month old and, e.g. #1025 is still missing therein.

Thanks in advance.

**Comment by georgefst** [comment]
If there is to be a release soon, it would be really great to have AArch64 support (https://github.com/Spotifyd/spotifyd/issues/280).

With Raspberry Pi OS moving to 64-bit earlier this year, this is likely to be increasingly frequently requested.

**Comment by slondr** [comment]
I created a new milestone https://github.com/Spotifyd/spotifyd/milestone/11 and moved all the issues still left over in the v0.3.1 milestone to it.

If there's anything else we want to hash out before bumping the number we can track it there.

**Comment by slondr** [comment]
With the merging of the big mpris bugfix just now, I'm wondering if there's appetite for doing the 0.3.4 release now (well, once we merge the changelog update) and pushing everything else outstanding to 0.3.5.

@Spotifyd/maintainers thoughts on the above? This would have the benefit of putting the mpris updates in the hands of users following stable releases etc.

**Comment by eladyn** [comment]
> With the merging of the big mpris bugfix just now, I'm wondering if there's appetite for doing the 0.3.4 release now (well, once we merge the changelog update) and pushing everything else outstanding to 0.3.5.

Generally, I agree. As you can see [here](https://github.com/Spotifyd/spotifyd/blob/master/CHANGELOG.md#unreleased), the changelog is already quite big for this release. The remaining points in the [next milestone](https://github.com/Spotifyd/spotifyd/milestone/11) seem to be mostly related to CI, however, which might be relevant for the release (so that the binaries are built correctly).

**Comment by wschlich** [comment]
Yes, please!

**Comment by slondr** [comment]
Alright, with some agreement and no dissent yet, I'll move forward with preparing 0.3.4 at the current master + updating the changelog.

**Comment by slondr** [comment]
0.3.4 has now been released.
