### ISSUE TITLE
Fails to compile with pulseaudio on Fedora

### ISSUE THREAD

**Issue by honza** [Spotifyd/spotifyd#1117]
**Description**

**To Reproduce**

1. Clone the repo
2. `cargo build --release --features pulseaudio_backend`
3. Fails to compile with:

```
  = note: /bin/ld: /usr/lib64/libsndfile.so.1: undefined reference to `mpg123_param2'
          /bin/ld: /usr/lib64/libsndfile.so.1: undefined reference to `mpg123_info2'
          collect2: error: ld returned 1 exit status
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Fedora 36
- Spotifyd: 7146f64a819590a16de9991de74f8bc2fea9c2ac
- cargo: `1.63.0`

**Comment by eladyn** [comment]
Hi and thanks for the report!

Unfortunately, I can't reproduce the build error on a fresh Fedora Workstation install. After installing `alsa-lib-devel` and `openssl-devel`, the build process via `cargo build --release --features "pulseaudio_backend"` completes successfully.

So there has to be something special about your system that makes the build process fail. Would you be able to post a bit more of the build output? Something above the `= note: ...` may be interesting as well. Apart from that, maybe you're able to figure out if there are some specialities about your setup, which could make a difference?

**Comment by honza** [comment]
Thanks for the quick reply!

As as often the case, I resolved the compile issue soon after opening the bug. I had upgraded Fedora recently, and libsndfile was updated from `1.0.x` to `1.1.x`. After reporting this bug, I manually downgraded the library to the older version, and now it compiles. 

My actual problem is that after the update, spotifyd now longer works with alsa. So, I tried configuring it to use pulseaudio. I think it's similar to #733 but pulseaudio doesn't work either. I'm not sure how to configure spotifyd to work with the newly updated Fedora.

**Comment by honza** [comment]
With Alsa:

```
Loading config from "/etc/spotifyd.conf"
No username specified. Checking username_cmd
No username_cmd specified
No password specified. Checking password_cmd
No password_cmd specified
No proxy specified
Using software volume controller.
no usable credentials found, enabling discovery
Connecting to AP "ap.spotify.com:443"
Authenticated as "..." !
Country: ".."
Using Alsa sink with format: S16
Loading <some song> with Spotify URI <spotify:track:...>
<Fsome song loaded> (333669 ms) loaded
Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
Could not start audio: Alsa error: PCM open failed
Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
Could not start audio: Alsa error: PCM open failed
PANIC: Shutting down spotifyd. Error message: called `Option::unwrap()` on a `None` value
PANIC: Shutting down spotifyd. Error message: called `Option::unwrap()` on a `None` value
Player thread panicked!
Error from channel for data receiver for range 688128 (+16384).
Error from channel for data receiver for range 671744 (+16384).
```

**Comment by honza** [comment]
With pulseaudio:

Thousands of these lines:

```
Could not start audio: Connection refused
Could not write audio: Not connected to PulseAudio
```

**Comment by honza** [comment]
It compiles fine now.

For some reason, Fedora changed the names of the hardware devices. All I had to do was run `sudo aplay -L`, and use the new name.

**Comment by eladyn** [comment]
Ah, I see. Good to hear that it's working now!
