### ISSUE TITLE
spotifyd does not connect but no error is given

### ISSUE THREAD

**Issue by 0x34cd** [Spotifyd/spotifyd#1119]
**Description**

spotifyd runs, but when using another spotify program like spotify-tui or spotify-qt, there is never any device given. The verbose logs to not show any errors as far as I can tell, though clearly something's not working.

I thought it might be a connection issue, so I disabled both the secondary homevpn interface as well as tried an http proxy, neither of which changed the output much.

**To Reproduce**

**Expected behavior**

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```
$ spotifyd --no-daemon --verbose
Loading config from "/home/user/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, use_mpris: None, on_song_change_hook: None, cache_path: None, no-audio-cache: true, backend: Some(Alsa), volume_controller: Some(SoftVolume), device: Some("default:CARD=Intel"), control: None, mixer: Some("amixer"), device_name: Some("TUI"), bitrate: Some(Bitrate160), initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: Some(Computer) } }
Found user shell: Some("/usr/bin/bash")
No proxy specified
registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
Using software volume controller.
registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
Zeroconf server listening on 0.0.0.0:39377
registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
Connecting to AP "ap.spotify.com:443"
found interface Interface { name: "wlp2s0", addr: V4(Ifv4Addr { ip: 192.168.1.4, netmask: 255.255.255.0, broadcast: Some(192.168.1.255) }) }
found interface Interface { name: "homevpn", addr: V4(Ifv4Addr { ip: 10.0.0.2, netmask: 255.255.255.255, broadcast: None }) }
sending packet to 224.0.0.251:5353
found interface Interface { name: "wlp2s0", addr: V4(Ifv4Addr { ip: 192.168.1.4, netmask: 255.255.255.0, broadcast: Some(192.168.1.255) }) }
found interface Interface { name: "homevpn", addr: V4(Ifv4Addr { ip: 10.0.0.2, netmask: 255.255.255.255, broadcast: None }) }
sending packet to [ff02::fb]:5353
received packet from 192.168.1.4:5353
received packet from 192.168.1.4:5353 with no query
received packet from [fe80::36e1:2436:9419:c864%4]:5353
received packet from [fe80::36e1:2436:9419:c864%4]:5353 with no query
registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
flushing framed transport
writing; remaining=137
framed transport flushed
attempting to decode a frame
frame decoded from buffer
deregistering event source from poller
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS:  Void Linux 
- Spotifyd:  0.3.3
- cargo:

**Comment by eladyn** [comment]
Hi!

Just looking at the logs, it seems quite likely that it's running into a `BadCredentials` error or something similar. The problem with `0.3.3` is that it doesn't report errors when connecting to Spotify and just shuts down. With the current version from `master`, you should be able to debug this more easily and see what's going on.

Hope this helps!

**Comment by 0x34cd** [comment]
Thank you, fortunately I figured out that I had to log in with my *email* as the username. Nothing to do with spotifyd at all. Cheers
