### ISSUE TITLE
[Regression] Non-predictable D-Bus name

### ISSUE THREAD

**Issue by haasn** [Spotifyd/spotifyd#1128]
**Description**

Commit 5270c3a3abcc5f9fec2695804e005299d5badaf7 caused a regression on my end. I can no longer control spotifyd through the D-Bus interface, which I currently do as follows:

```haskell
playerControl :: Client -> String -> X ()
playerControl c m = io . callNoReply c $
    (methodCall path iface member) { methodCallDestination = Just dest }
    where path   = objectPath_ "/org/mpris/MediaPlayer2"
          iface  = interfaceName_ "org.mpris.MediaPlayer2.Player"
          member = memberName_ m
          dest   = busName_ "org.mpris.MediaPlayer2.spotifyd"
```

As you can see, this sends a d-bus event to the `org.mpris.MediaPlayer2.spotifyd` endpoint. But the linked commit removed the ability to refer to spotifyd using a consistent name, instead I now have to traverse the D-Bus tree to find the right endpoint, in the worst case on every single command (even something as simple as changing the volume!).

What was the reasoning for this breaking change? Can it be reverted, or made configurable? Suggestions on a better way to solve my use-case?

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Comment by eladyn** [comment]
Thanks for bringing this up! This is indeed not a regression, but rather a feature :sweat_smile:, and we are aware that this might be a breaking change for some users. (See the [changelog entry](https://github.com/Spotifyd/spotifyd/blob/ddfcbb2eecd3b5be94533f7374180df412659b4e/CHANGELOG.md#changed).)

In the PR that changed that (#1100), we discussed whether a unique bus name (which is, what it is now) should be the hardcoded default or if this should be configurable. (See https://github.com/Spotifyd/spotifyd/pull/1100#discussion_r965418312 for some aspects.) There, we agreed that, even if it might break some setups, it should be easy to adapt to it with some minor changes, which are also noted in the changelog.

All that aside: The new version hasn't yet been released, and there is always room for change / improvement. I don't know, how easy it would be in your case to first list all the bus names and then filter for `spotifyd`, before controlling `spotifyd`?

Happy to read your thoughts, if the new behaviour doesn't work for you (and maybe others) or is too involved to implement, we can surely add a configuration option for that!

**Comment by haasn** [comment]
> I don't know, how easy it would be in your case to first list all the bus names and then filter for spotifyd, before controlling spotifyd?

I suppose I can work-around it on my end. It's a bit ugly, but on the flip side, now my code is more general and supports all media players (not just spotifyd), so I guess this is a win overall:

```python
#!/usr/bin/env python3
import pydbus

bus = pydbus.SessionBus()
dbus = bus.get('org.freedesktop.DBus', '/org/freedesktop/DBus')
metadata = None

for name in dbus.ListNames():
    if name.startswith('org.mpris.MediaPlayer2.'):
        metadata = bus.get(name, '/org/mpris/MediaPlayer2').Metadata
        break

if not metadata:
    print('N/A')
    exit(0)

artist = ", ".join(metadata['xesam:artist'])
title = metadata['xesam:title']
album = metadata['xesam:album']
if album == title:
    album = 'Single'

print('{artist} - {title}  ({album})'.format(
    artist = artist,
    album = album,
    title = title,
))
```

**Comment by haasn** [comment]
I suppose it's just still surprising behavior given that other media players do not seem to do this (e.g. official spotify client just shows up as `org.mpris.MediaPlayer2.spotify`)

**Comment by eladyn** [comment]
Agreed. Still, unique names like we are doing them are recommended for the spec and most tools are handling them fine (e.g. `playerctl -p spotifyd ...` still works).
Thus, I'd leave it like this for the time being, since your issue seems to be resolved. If more people are running into similar problems, we can surely reconsider that.

Thank you!
