### ISSUE TITLE
docs: XDG location for systemd - launched 

### ISSUE THREAD

**Issue by mfeif** [Spotifyd/spotifyd#113]
If people want to use the service file in contrib, they will need to know where to put the spotifyd.conf file; it should live in /etc/xdg/spotifyd.

It'd be nice to put that in the docs.

**Comment by SimonPersson** [comment]
Yeah, that should have been documented. I've added a note in the README.

Actually, `/etc/spotifyd.conf` also work if you prefer. I've added both alternatives to README.
