### ISSUE TITLE
compile error on Raspbian: this version of Cargo is older than the `2021` edition

### ISSUE THREAD

**Issue by stuart12** [Spotifyd/spotifyd#1133]
**Description**

spotifyd does not compile on Raspbian bullseye with the error `this version of Cargo is older than the 2021 edition, and only supports 2015 and 2018 editions` and `failed to download hashbrown v0.12.3`.

Note that c57ab5283fc80b2f99b51105560aec733d9207c6 compiles but the next commit d430360560c1c35c449dfd169c188e552190c3dd does not compile.

**To Reproduce**

1. Update your Raspbian bullseye installation
2. Checkout  ddfcbb2eecd3b5be94533f7374180df412659b4e (or the first failing commit d430360560c1c35c449dfd169c188e552190c3dd)
3. `cargo build --release --no-default-features --features pulseaudio_backend`

**Expected behavior**
spotifyd complies

**Logs**
<details><summary>Click to show logs</summary>

```
+ git log -1
commit ddfcbb2eecd3b5be94533f7374180df412659b4e
Merge: 00f52f9 2670dfd
Author: Robin <robin@robinjint.nl>
Date:   Mon Oct 10 18:07:32 2022 +0200
    Merge pull request #1125 from eladyn/docs_ubuntu_use_rustup
    
    docs: use rustup for ubuntu installation
+ cargo --version
cargo 1.46.0
+ cargo build --release --no-default-features --features pulseaudio_backend
 Downloading crates ...
error: failed to download `hashbrown v0.12.3`
Caused by:
  unable to get packages from source
Caused by:
  failed to parse manifest at `/var/cache/spotifyd-compile/.cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/Cargo.toml`
Caused by:
  failed to parse the `edition` key
Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
- OS:  Raspbian bullseye
- Spotifyd: ddfcbb2eecd3b5be94533f7374180df412659b4e
- cargo: 1.46.0

**Comment by eladyn** [comment]
As noted on [this page](https://spotifyd.github.io/spotifyd/installation/Ubuntu.html), we only support recent rust versions and recommend using `rustup` to install rust. See also #1123 for a similar discussion.

Did you follow any official instructions that live in the documentation or this repo? Because if so, it would be good to change them to reflect the current state.
