### ISSUE TITLE
Cargo build --release hangs

### ISSUE THREAD

**Issue by codingnooob** [Spotifyd/spotifyd#1135]
**Description**
When I build spotifyd using the command `cargo build --release` (as stated by the Installing on Ubuntu wiki), it will hang. Nothing is outputted in the console, and when I check the process, it says that it is sleeping.

**To Reproduce**
1. Install Rust toolchain (good)
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
2. Install requirements (good)
- sudo apt install libasound2-dev libssl-dev pkg-config
3. Clone the repository (good)
- git clone https://github.com/Spotifyd/spotifyd.git
4. Build spotifyd (not good)
- cd spotifyd
- cargo build --release (hangs)

**Expected behavior**
spotifyd gets built

**Logs**
Nothing appears on console. Process elapsed for over 30 minutes with status "Sleeping".

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Pop!_OS 22.04 LTS
- Spotifyd: v0.3.3
- cargo: cargo 1.65.0 (4bc8f24d3 2022-10-20)

**Comment by eladyn** [comment]
Hi!

Did you try compiling different rust projects or running `cargo` with `--verbose` or something similar? If not, maybe that could get us further…

**Comment by slondr** [comment]
If you run the cargo command in strace, does anything look out of sorts? What is it actually blocking on?

**Comment by codingnooob** [comment]
There are a bunch of places where it says ENOENT (No such file or directory) and it appears to hang on 
`poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}], 2, -1)`. I don't have the slightest clue of why it's doing this.

I'll include the entire output of strace for reference:
[spotifyd_build.txt](https://github.com/Spotifyd/spotifyd/files/10080227/spotifyd_build.txt)

**Comment by eladyn** [comment]
I don't think that we can help you here that well. Judging by the `strace` output, `cargo` doesn't seem to get very far and as such, it seems unlikely that this is at all related to `spotifyd`.

For such general rust problems, there are many channels where you can seek for help. I'd assume that you'll find better support over there.
Hope that you get your issue solved! :)
