### ISSUE TITLE
cargo: failed to compile with dependency issue

### ISSUE THREAD

**Issue by apprehensions** [Spotifyd/spotifyd#1138]
**Description**
spotifyd simply fails to compile when installing with `cargo`, with some dependency issue.

**To Reproduce**
1. `cargo install spotifyd`

**Expected behavior**
`spotifyd` is installed

**Logs**
```
~ 101 $ cargo install spotifyd
    Updating crates.io index
  Downloaded spotifyd v0.3.2
  Downloaded 1 crate (79.5 KB) in 0.75s
  Installing spotifyd v0.3.2
error: failed to compile `spotifyd v0.3.2`, intermediate artifacts can be found at `/tmp/cargo-installXtZdz8`

Caused by:
  failed to select a version for the requirement `stream-cipher = "^0.3"`
  candidate versions found which didn't match: 0.99.99, 0.7.1, 0.6.0, ...
  location searched: crates.io index
  required by package `aes-ctr v0.3.0`
      ... which satisfies dependency `aes-ctr = "^0.3"` of package `librespot-audio v0.1.5`
      ... which satisfies dependency `librespot-audio = "^0.1.5"` of package `librespot v0.1.5`
      ... which satisfies dependency `librespot = "^0.1.5"` of package `spotifyd v0.3.2`

```

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: GKISS Linux
- Spotifyd: 0.3.2
- cargo: 1.65.0

**Comment by wael444** [comment]
this problem seems to dissapear when installing (`cargo install --git https://github.com/Spotifyd/spotifyd`) from git.

**Comment by eladyn** [comment]
Thanks for the report!

Unfortunately, that can and will only be fixed by the next release. (Although the crates.io version should ideally have been bumped to 0.3.3 already.)
Let's hope that we'll be able to fix this soon and release the next version!

**Comment by eladyn** [comment]
This should be fixed by the release that happened some time ago.
