### ISSUE TITLE
Supporting multiple users at the same time

### ISSUE THREAD

**Issue by fwyzard** [Spotifyd/spotifyd#114]
Hi,
here's an idea / feature request: supporting more than one user at the same time.

I've set up spotifyd on a Raspberry Pi connected to some speakers in the living room, and it works great.
It would be even nicer if both my girlfriend and I could control it from our Spotify clients, each with our own account.

I've seen that Spotify marked [supporting this in their official Connect devices](https://community.spotify.com/t5/Live-Ideas/Spotify-Connect-Same-Network-Multiple-Accounts/idi-p/967099) as "Not Right Now", but I guess it could be done in spotifyd logging in multiple accounts at the same time...

Anyway, very nice job !

**Comment by romlinch** [comment]
It would be nice feature.
Many thanks for your very nice job. Works like a charm.

**Comment by SimonPersson** [comment]
The difficulty of this depends a bit on your definition of "at the same time". The simplest approach is to use discovery instead of username/password. That still only allows one user at a time to connect, but with some abuse of the event hook you could restart spotifyd whenever one user stops playing so that you can take turns controlling spotifyd:
```
#!/bin/bash
if [ "stop" == "$PLAYER_EVENT" ]; then
        killall spotifyd; spotifyd
fi
```
Of course you might want to make use of the PID file instead of `killall` if you try this out.

The more difficult approach is to have spotifyd signed in on two accounts at the same time, allowing both accounts to skip a song at any time. I think this might be hard to implement using the connect protocol. My understanding is that the protocol relies on a shared context between the devices. This means that the `next` event does not contain the id of the next song, all devices just know which song is coming up based on their shared state. I suspect that it will be very hard to replicate that state between different accounts.

**Comment by fwyzard** [comment]
Indeed, what I had in mind is more along the lines of having `spotifyd` logged in to multiple accounts.
For example:
  - spotifyd is configured to log in two users, Alice and Bob
  - when Bob tells his Spotify client to listen on `spotifyd`, it starts streaming Bob's music, and is fully controlled by Bob's Spotify Connect
  - later, Alice tells her Spotify client to listen on `spotifyd`; now `spotifyd` somehow "disconnects" from Bob's control, and starts streaming Alice's music, and is fully controlled by her Spotify Connect

I guess the complicated parts are
  - keeping two sessions alive for both Alice and Bob
  - keeping track of the "active" one, and answering / syncing only with that account
  - listening to the inactive one(s) to check if they want to start controlling `spotifyd`
  - "disconnecting" one user's music and control without disconnecting the account, i.e. as if the user had told its client not to play on `spotifyd` any more

The simple alternative could be to keep to `spotifyd` daemons running, one for each user, let the software mixer take take of the music and the users figure out a way not to play at the same time :-)

**Comment by doublemcz** [comment]
+1, I just paid Spotify Family account to find out that I cannot play in one daemon song from two accounts - thought that it is somehow connected.

**Comment by gailingmic** [comment]
this is bugging me aswell right now :)
i will try to come up with a solution later today

**Comment by NicoHood** [comment]
I just tried version 0.2.1 and we were able to stream with two different accounts to spotifyd at the same time. The sound overlapped.

The issue I have is that I cannot have multiple spotifyd in my network. I used `--device_name="test"` but the name did not change at all. The first spotifyd "wins" and is listed as spotify speaker. Am I missing something?

**Comment by amirc** [comment]
I'm facing now the same issue. Did anyone figure out a way?

**Comment by NicoHood** [comment]
The problem i was facing got fixed in 0.2.3. The login issue should not be a problem if you dont specify an account for spotifyd.

**Comment by er0k** [comment]
In addition to removing username and password from my config like @NicoHood mentioned, I also had to disable the `cache_path` in the config. It seems that spotifyd caches account credentials, which was causing me problems when switching between accounts. Once I removed the cache option in my config it seems to be working well.

**Comment by SirWindfield** [comment]
We theoretically could introduce new types for `cache_path`, `username` and `password` (along with `password_cmd`.

They could, for example, be a list separated by `,`. They would all have to be of the same length. And Spotifyd forks itself on start if that is the case, running two instances. Now if someone connects to one instance, it would just kill the other one. And if the user disconnects, it could fork again with the new credentials.

On the other side, that sounds so absurd and stupid. It would probably be easier to write a custom script for this one. Just start two Spotifyd instances. You can pass down the config file path using `--config-path` (not sure if that is actually the exact name). The `onevent` could then be used to either mute the second instance of Spotifyd or kill it. The PID of the invoker could be passed down as an environment variable during the script execution to make filtering out easier. This actually sounds more reasonable.

#288 could help here out. Not sure how many hooks are actually possible to act and how deep they can go as we do not directly manage the connection to the connect service.

**Comment by Ru1ah** [comment]
Hi, still no way to enable 2 different user accounts to use spotifyd, when discovery is not working?

**Comment by SirWindfield** [comment]
Nop. no one took the time to investigate.

**Comment by yosukeora** [comment]
I kind of sorted it out with a filthy workaround. I am on Linux.
When you run multiple daemon with multiple configs, you will see multiple processes going on as your `ps` command shows, and this actually works when client paired to them if you are lucky. But will lose your paring maybe the next day.
On this situation, from your client, you will only see 1 client which shows `Spotifyd@machine-name`.
So, to alter this name by process and it works for each of your member's account.

To change this name, you will need to compile from the source at least one of your spotifyd command.
Download source and go to `src/config.rs` and find lines `let device_name ...`, then change the name `Spotifyd` to your member's name or anything else.
Compile it and run it, then you will see `Spotifyd@machine-name` and `NewlyNamed@machine-name` from your client.

**Comment by rp86** [comment]
> I'm running 2 daemons at a time on a rasperrypi so that one can use its own account in the living room on the amplifier.
> the only small issue is that when one account is playing, the others can play too.
> 
> using these services:
> 
>*snip*

This approach worked for me also, but as I am using pulseaudio I had to install the services to /etc/systemd/user and enable with systemctl --user

**Comment by 204504bySE** [comment]
Using zeroconf(don't set id/password to spotifyd) and set RestartSec shorter(about 2sec) is an easy workaround.

When a different user connect to spotifyd, it crashes. It means the first attempt of connect always fails.
... then spotifyd restarts. Users select the device(connect to spotifyd) again. It succeeds.
