### ISSUE TITLE
Allow family and friends to to stream via spotifyd

### ISSUE THREAD

**Issue by rkintzi** [Spotifyd/spotifyd#1142]
I would like my family and friends could connect to and stream via spotifyd. Right now all devices in my local network sees spotifyd, but only those that are logged in using my Spotify account can stream via spotifyd. 

As an example I could point PS5 Spotify client that that has a toggle to enable others in the local network to control playback.

Edit: When I try to connect from device logged into other Spotify account this ends up with `Login error for user "31psjq3vrxt26wyqjppotyva5ygm": MAC mismatch` in spotifyd logs.

**Comment by eladyn** [comment]
Thank you for the report.

In theory, streaming from different accounts should be possible with `spotifyd`. Since the error doesn't actually come from `spotifyd`, but rather from [`librespot`](https://github.com/librespot-org/librespot) (the library, that `spotifyd` uses), would you be able to try that one and see if the problem happens with that as well?

**Comment by HonestJohn61** [comment]
> I would like my family and friends could connect to and stream via spotifyd.

That's why I use Spotify, and for me it works as documented. Simply delete or comment out the userid and password lines. Or have you done that already?

**Comment by rkintzi** [comment]
So I finally got some time to test librespot. I didn't manage send the stream to the actual sound card but I could dump it to the stdout. With librespot, the Spotify client on my iPhone shows the toggle that allows for sharing the device. And to my surprise after switching back to spotifyd the toggle is still there. Don't know what exactly happened, but I can now share the device with my family and friends. 

Thanks for your suggestion. I will close the ticket as this is no longer an issue for me. Will reopen if the problem reappears.
