### ISSUE TITLE
Cannot install on aarch64

### ISSUE THREAD

**Issue by DrCWO** [Spotifyd/spotifyd#1146]
**Description**
As there is no binary for ARMv8 (Dietpi Buster on Pi4) I tried to build by myself but no success.
Installation did not come to an end :-(

**To Reproduce**

1. apt-get install cargo --> OK
2. cd /tmp
3. git clone https://github.com/Spotifyd/spotifyd.git
4. cd spotifyd
5. cargo build --release

**Expected behavior**
**Will install as described here:
https://spotifyd.github.io/spotifyd/installation/Ubuntu.html**

**Logs**
```
root@rooExtend:/tmp/spotifyd# cargo build --release
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
```
**Those two lines are repeated endlessly**

**No Idea where to put the flags, not in description here:
https://spotifyd.github.io/spotifyd/installation/Ubuntu.html**

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: 
uname -a
Linux 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

- cargo: 
No idea how to get it. Starting cargo I always get:
```
cargo -h
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
```

Help would be appreciated :-)

**Comment by slondr** [comment]
This looks like an issue with cargo, not spotifyd. Try uninstalling apt's version and trying again using rustup (https://rustup.rs/).
