### ISSUE TITLE
Debian 11: GLIBC 32 Missing

### ISSUE THREAD

**Issue by sebi-vscode2** [Spotifyd/spotifyd#1147]
**Description**
I wanted to run spotifyd in debian11 but i got a error.

**To Reproduce**
1. Run the spotifyd file from spotifyd-linux-default.tar.gz
2. See error 

**Expected behavior**
Spotifyd should run fine

**Logs**
<details><summary>Click to show logs</summary>

```
./spotifyd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./spotifyd)
./spotifyd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./spotifyd)
./spotifyd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./spotifyd)

```

</details>

**Versions**

- OS: Debian 11 (Bullseye)
- Spotifyd: Release v0.3.4

**Comment by slondr** [comment]
What version of glibc does Debian 11 ship with?

**Comment by sebi-vscode2** [comment]
Hello, thanks for your answer, it ships with GLIBC 31

**Comment by slondr** [comment]
Yeah that's pretty outdated, glibc 2.32 has been out for nearly two and a half years now. 

You can probably get Spotifyd running if you compile it from source (assuming rust supports glibc that old) or run it in a container, ymmv as I've personally never tried the latter.

**Comment by sebi-vscode2** [comment]
I tried compiling it but it gave me a error, how can i run it in a container?

**Comment by slondr** [comment]
Hmm, what error did you get while compiling?

**Comment by sebi-vscode2** [comment]
Hello, I forgot installing  essential build tools but now Spotifyd runs fine

**Comment by cobalt2727** [comment]
What OS are the binaries being built on right now? I'd say it's worth compiling the release files on an older distro to ensure compatibility with more platforms...

**Comment by sebi-vscode2** [comment]
Hello, I built them in debían 11, the problem was that the guide didn't included build essential packages.
