### ISSUE TITLE
add website link to the github about section

### ISSUE THREAD

**Issue by Rdkang** [Spotifyd/spotifyd#1148]
It would be great to easily find the link to the website. As otherwise you will have to read the readme to find the small link.

So adding the link https://spotifyd.github.io/spotifyd/ to the **about** section would be great
![image](https://user-images.githubusercontent.com/68774237/208322528-4e377ec3-1494-4eb7-b9db-e5789c7445ed.png)

**Comment by slondr** [comment]
Fair enough! I think we need @PontusPersson specifically to edit that repo setting (other maintainers don't have access to project-level configuration).

**Comment by PontusPersson** [comment]
Good suggestion, link to website added to "about" section.
