### ISSUE TITLE
Local file from other device sync and play

### ISSUE THREAD

**Issue by imhemish** [Spotifyd/spotifyd#1149]
If local files are enabled on any of desktop or mobile official client, they appear in local files section, but the clients have a feature to add those local files in your playlists, as soon as you add a local file to a playlist, and download that playlist on other device, if both are on same network, the file gets saved to to other device, and if we play that playlist on other device, the local files are playable.

While I understand that downloading all playlist if out of scope, would there be some feature regarding pulling local files from same network (that would require some reverse engineering probably) devices' clients so that those files in playlist are also playable.

**Comment by eladyn** [comment]
Thank you for the report. As `spotifyd` is built on `librespot`, we can only support what is available over there and as such it would be great, if you could see if there are already open issues about this over there or open a new one, if not.

**Comment by eladyn** [comment]
Going to close this for now, as it's primarily a librespot issue (and I seem to not be able to reproduce the behaviour). Feel free to report back, if you got anything new regarding the issue!
