### ISSUE TITLE
Error sending open URI message over dbus

### ISSUE THREAD

**Issue by JamsheedMistri** [Spotifyd/spotifyd#1159]
**Description**
I am trying to play a playlist over dbus, but I am getting an error.
```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:spotify:playlist:1gUpTWqszJtx5wKligLrYv"

Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotifyd was not provided by any .service files
```

**To Reproduce**
1. Clone `spotifyd` repository.
2. Install dependencies via `sudo apt install` as specified on wiki.
3. Build with `dbus_mpris` flag: `cargo build --release --features "dbus_mpris"`.
4. Copy binary from `target/release/spotifyd` to `/usr/bin/spotifyd`.
5. Start `spotifyd` service as user: `systemctl --user start spotifyd`.
6. Verify service is running correctly.
7. Send `dbus-send` command above.

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions:**
- OS: Raspbian Buster
- Spotifyd: 0.3.4
- cargo: 1.66.0

**Additional context**
Note: I am able to play songs from my Spotify client and select the device on the Spotify client, so I know spotifyd is working correctly, but I would like to queue playlists/songs via the command line as well.

**Comment by eladyn** [comment]
We recently changed the dbus name of `spotifyd` to avoid potential ambiguity. You can have a look at the changelog for details and possible fixes.
Hope, this helps!

**Comment by JamsheedMistri** [comment]
Thanks! For those that are stuck, you can do `qdbus | grep "org.mpris.MediaPlayer2.spotifyd"` for the updated package name.
