### ISSUE TITLE
No sound when running as a service on RaspberryPi (v0.3.3)

### ISSUE THREAD

**Issue by MisterMorgan** [Spotifyd/spotifyd#1160]
**Description**
When I run spotifyd from the command line, everything works as intended. When I set it up as a service using the provided spotifyd.service, there is no sound. systemctl --user status spotifyd.service shows the service running without any error messages.

**To Reproduce**

Run spotifyd --no-daemon from the command line
Use the Spotify app to connect to the Pi's spotifyd
Play music.
Kill the process and run systemctl --user start spotifyd.service
Check that everything started correctly with systemctl --user status spotifyd.service
Use the Spotify app to connect to the Pi's spotifyd
No sound!

**Expected behavior**
I'm expecting the service to run similarly to what I'm doing from the command line, and so I'm expecting either sound or at least an error message.

The same problem is documented in the issue #658

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: 
- Spotifyd: 
- cargo:

**Comment by bobbymcqueen** [comment]
I can confirm this.

OS: Raspberry Pi OS with the latest packages
Cargo: 1.66.1
Spotifyd: 0.3.4

**Comment by MisterMorgan** [comment]
Hey guys,

I could fixed that service problem with the help of @bobbymcqueen .

For the spotifyd.service I created a seperate spotifyd.conf at the path `/etc/spotifyd.conf` and added the line `device = "sysdefault:CARD=Headphones"` after that I could hear the sound after every reboot.

Thanks @bobbymcqueen!
