### ISSUE TITLE
Problems with MPRIS D-Bus (playerctl)

### ISSUE THREAD

**Issue by lenlennart** [Spotifyd/spotifyd#1168]
**Description**
`spotifyd` cannot be found by `playerctl` on pi4, regardless of setting `use_mpris` and `dbus_type`

**To Reproduce**
1. install `spotifyd` on pi4 running Raspbian
2. start with `/spotifyd --no-daemon`
3. install playerctl
4. use `playerctl -l`to list available players
5. adding `use_mpris = true` and/or `dbus_type = "system"` to config

**Expected behavior**
`spotifiyd`player is found

**Logs**

**Versions (please complete the following information):**
- OS: Raspbian GNU/Linux 10
- Spotifyd: [spotifyd-linux-armv6-slim.tar.gz](https://github.com/Spotifyd/spotifyd/releases/download/v0.3.4/spotifyd-linux-armv6-slim.tar.gz)
- cargo: 

<!-- **Additional context**

**Comment by eladyn** [comment]
Thank you for the report. Unfortunately, when going for the headless variant and relying on the system bus, you won't be able to use `playerctl`, since that has the `session` bus hardcoded. You can however set off your own dbus commands like this:

```bash
# guessing the used dbus name (alternative is to list all dbus names and grep that)
spotifyd="org.mpris.MediaPlayer2.spotifyd.instance$(pidof spotifyd)"

# getting metadata of current playing song
dbus-send --print-reply=literal --dest=$spotifyd /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata


```
