### ISSUE TITLE
Rust build fails on Raspberry Pi 4 

### ISSUE THREAD

**Issue by microfx** [Spotifyd/spotifyd#1169]
Hey!

Trying to build librespot but the raspberry always crashes on the way (no connection possible anymore). 

Build command used:
```cargo build --no-default-features --features rodiojack-backend --locked```

This is the last step before crashing:
```^C  Building [======================>  ] 321/346: libgit2-sys(build), librespot-protocol, rustls-native-certs, rustls, rustls```

System: 
```
Linux 5.15.36-rt41-v7+ armv7l GNU/Linux
rustup 1.25.1 (bb60b1e89 2022-07-12)
cargo 1.66.0 (d65d197ad 2022-11-15)
```

Any clue? 

Cheers!

**Comment by slondr** [comment]
It's failing building librespot? What's the actual compilation error?

**Comment by microfx** [comment]
Oh I'm sorry – I forgot I still have the error message from the first build try:

```
321/346: libgit2-syerror: could not compile `librespot-protocol`

Caused by:
  process didn't exit successfully: `rustc --crate-name librespot_protocol --edition=2021 protocol/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=57bb787e4ee14170 -C extra-filename=-57bb787e4ee14170 --out-dir /home/patch/librespot/target/debug/deps -C incremental=/home/patch/librespot/target/debug/incremental -L dependency=/home/patch/librespot/target/debug/deps --extern protobuf=/home/patch/librespot/target/debug/deps/libprotobuf-0bb14020e8640280.rmeta` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
Connection to microlabs-p3.local closed by remote host.t2-sys(build), rustls-native-certs, rustls, rustls       
```

**Comment by slondr** [comment]
Ok, that looks like an error with librespot, and not Spotifyd. I believe they'll be of more help than we could: https://github.com/librespot-org/librespot

**Comment by microfx** [comment]
oh... lol where am I here – so sorry :D thx
