### ISSUE TITLE
Can't restrict or disable cache

### ISSUE THREAD

**Issue by andatche** [Spotifyd/spotifyd#117]
It doesn't appear possible to restrict the maximum cache size or disable caching entirely (which is supported by librespot).

I'm running spotifyd on a raspberry pi and looking to reduce unnecessary writes to the SD card. I can mount a tmpfs ramdisk at the cache location, but as soon as it becomes full, spotifyd errors:

> [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 28, message: "No space left on device" } }

**Comment by SimonPersson** [comment]
When I leave out the `cache_path` option, I don't get caching. Are you seeing cached files somewhere even if you don't specify `cache_path`?

And what is respotify?

**Comment by andatche** [comment]
Thanks! You are correct, if `cache_path` is unset then tracks are downloaded to /tmp and then immediately removed. I already have a tmpfs mounted there so that solves my problem.
