### ISSUE TITLE
Could not start audio: Alsa error: PCM open failed

### ISSUE THREAD

**Issue by 5ug4md** [Spotifyd/spotifyd#1171]
It shows the daemon on spotify connect but whenever i try to switch to spotifyd from my phone it shows error as

<Sorrow> (524753 ms) loaded
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM spotifyd
Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
Could not start audio: Alsa error: PCM open failed
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM spotifyd
Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
Could not start audio: Alsa error: PCM open failed
![image](https://user-images.githubusercontent.com/73983080/222347015-49e0c22c-ff31-4aaa-ac51-54fc2cfd857e.png)

**Comment by eladyn** [comment]
Hi!

The value, you put in for `device` should be a valid entry from `aplay -L` (usually `default` should do) and not `spotifyd`. (The error message says that it can't find the device with name `spotifyd`.
