### ISSUE TITLE
spotifyd won't run (Couldn't connect to syslog)

### ISSUE THREAD

**Issue by JaceReid** [Spotifyd/spotifyd#1180]
**Description**
After building and install spotifyd I try to run it and get an error. I also have tried install from arch repos. Same error:

Error: 
   0: Couldn't connect to syslog instance: Initialization

Location:
   src/main.rs:53

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->Error: 
   0: Couldn't connect to syslog instance: Initialization

Location:
   src/main.rs:53

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: main<unknown>
      at <unknown source file>:<unknown line>
   2: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions**
- OS: artix linux 
- Spotifyd: 0.3.4
- cargo: 1.67.1

**Comment by eladyn** [comment]
Thank you for the report. As the error says, `spotifyd` needs a running `syslog` instance, when run as a daemon. So you can either run it with `--no-daemon` or install a syslog equivalent for your system.
See also https://github.com/Spotifyd/spotifyd/issues/1107.

**Comment by eladyn** [comment]
I think we can close this? If you have any further questions, feel free to raise them or ask in the matrix chat.
