### ISSUE TITLE
0.3.5 Release

### ISSUE THREAD

**Issue by slondr** [Spotifyd/spotifyd#1184]
Creating this as a meta-issue for releasing a 0.3.5 version.

Unless we manage to set up #345 soon (which I may work on anyway) I think there's some benefit in packaging minor releases fairly often as new functionality is implemented. For this one, we'll already have the TransferPlayback dbus method and the "none" audio mixer; soon we should have the Librespot 0.4 + other dependency upgrades as well. 

Also, with #1172, a new minor release might draw some attention to the new Matrix channel.

Is there anything else we want to see merged in before the next minor release?

**Comment by eladyn** [comment]
Sounds good! As a reminder to myself or anyone else: We should populate the changelog with these changes before publishing the next version.

I'd also self-promote #1174 which includes some upstream fixes and #1145, which fixes compilation errors, when compiling without `--locked`. Although you have already reviewed them, so this is blocking on one of the other maintainers…

**Comment by slondr** [comment]
> As a reminder to myself or anyone else: We should populate the changelog with these changes before publishing the next version.

Yep, for sure.  I  created  #1189 to  track that  specifically.

**Comment by eladyn** [comment]
The new version has been [released](https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.5). :tada: I'll also try to update the crate on crates.io.
