### ISSUE TITLE
Cannot Build with dbus_mpris

### ISSUE THREAD

**Issue by klay2000** [Spotifyd/spotifyd#1194]
**Description**
Compiling with dbus_mpris enabled fails with the following errors:

```
error[E0404]: expected trait, found enum `PlayContextId`
   --> src/dbus_mpris.rs:352:41
    |
352 |             struct AnyContextId(Box<dyn PlayContextId>);
    |                                         ^^^^^^^^^^^^^ not a trait

error[E0404]: expected trait, found enum `PlayContextId`
   --> src/dbus_mpris.rs:363:18
    |
363 |             impl PlayContextId for AnyContextId {}
    |                  ^^^^^^^^^^^^^ not a trait

error[E0404]: expected trait, found enum `PlayableId`
   --> src/dbus_mpris.rs:366:34
    |
366 |                 Playable(Box<dyn PlayableId>),
    |                                  ^^^^^^^^^^ not a trait
```

**To Reproduce**
`cargo build --features dbus_mpris`

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Ubuntu 20.04.5 LTS
- Spotifyd: commit hash e640aca
- cargo: cargo 1.63.0 (fd9c4297c 2022-07-01)

**Comment by eladyn** [comment]
That semver breaking `rspotify 0.11.6` release / the temporary workaround is really causing a lot of problems. :sweat_smile:

This issue has been raised in #1193, #1144 and will be fixed with #1145. The last mentioned PR should be merged within the next few days.
