### ISSUE TITLE
Sound crackles and cuts when starting or ending a track

### ISSUE THREAD

**Issue by binatrix** [Spotifyd/spotifyd#1204]
**Description**
When a song starts or changes between tracks there are crackles and cuts in the audio, but when is on the middle it sounds good.

**To Reproduce**
Starting a new song

**Expected behavior**
No crackles in sound when change between tracks

**Versions (please complete the following information):**
- OS: Banana PI M2 Zero W (4.4.55-BPI-M2Z-Kernel #1 SMP PREEMPT Fri Apr 10 16:05:55 HKT 2020 armv7l)
- Spotifyd: 0.3.4

<!-- **Additional context**
[global]
username = "xxxxxxxxxx"
password = "xxxxxxxxxxxx"
device_name = "spotifyd"
bitrate = 160
initial_volume = "10"
volume_normalisation = false
#normalisation_pregain = 1
device_type = "speaker"

**Comment by slondr** [comment]
Do you have song crossfading enabled in Spotify?

Also, can you reproduce the issue in spotifyd 0.3.5?

**Comment by binatrix** [comment]
Hi, thanks for your message.
On my mobile device crossfading is disabled (0 seconds). Is there a way to disable this feature on Spotifyd? Apparently it is not possible to disable it from the mobile when Spotifyd is playing.
I haven't tried version 0.3.5 yet. Do you recommend it?.

**Comment by binatrix** [comment]
I've been doing some tests and found that the crackles start when "librespot" preloads the next song. While playing, everything sounds fine, but when the "Loading" event appears, the crackles start. Seems a problem with "librespot" trying to buffering the next song while playing the current song. 
```
[2023-07-04T23:02:46Z INFO  librespot_playback::player] <Urgent> (271200 ms) loaded
[2023-07-04T23:05:08Z INFO  librespot_playback::player] Loading <I'm Gonna Win> with Spotify URI <spotify:track:0JaQc8LCU9DHMIc2vYaP9K>
[2023-07-04T23:05:09Z INFO  librespot_playback::player] <I'm Gonna Win> (292973 ms) loaded
```
I've tried several options in "librespot" to disable this preload feature but none seems to work. Probably Banana PI may not be able to perform both actions at the same time.

**Comment by binatrix** [comment]
Is a "RPi zero" and "librespot" related problem. No solution in sight

https://github.com/librespot-org/librespot/issues/532
