### ISSUE TITLE
Dies after suspending OS

### ISSUE THREAD

**Issue by sprnza** [Spotifyd/spotifyd#1208]
**Description**
After suspending laptop spotifyd dies with this log (see below)

**To Reproduce**
1. Start and enable spotifyd using systemd
2. Suspend OS
3. Resume OS
4. See the logs

**Expected behavior**
Spotifyd resumes working after resuming OS

**Logs**
```

May 06 16:11:42 sdg-dell spotifyd[619811]: Couldn't fetch metadata from spotify: Http(Transport(Transport { kind: Dns, message: Some("resolve dns name 'api.spotify.com:443'"), url: Sort(Transport { kind: Dns, message: Some("resolve dns name 'api.spotify.com:443'"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.spotify.com")), port: None, path: "/v1/me/player/currently-playing", query: None>omain("api.spotify.com")), port: None, path: "/v1/me/player/currently-playing", query: None, fragment: None }), source: Some(Custom { kind: Uncategorized, error: "failed to lookup add fragment: None }), source: Some(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }) }))
```

**Versions (please complete the following information):**
- OS: ArchLinux
- Spotifyd:0.3.5
- cargo: 1.69.0

**Comment by eladyn** [comment]
Hi!

This is probably a duplicate of https://github.com/Spotifyd/spotifyd/issues/573. The error you posted in your logs are only a side effect of not having internet for MPRIS, this shouldn't make `spotifyd` die.

What exactly do you mean by “dies”. Does the process crash, or does it just no longer play any music / can't be connected to?

**Comment by sprnza** [comment]
yep, it's a duplicate. Closing. Thank you!
