### ISSUE TITLE
Connection to Spotify lost after sleeping

### ISSUE THREAD

**Issue by TheDcoder** [Spotifyd/spotifyd#1210]
**Description**
Spotify no longer shows the device after it is put to sleep and then woken up later.

**To Reproduce**

spotifyd detects that the connection is lost and attempts to reconnect automatically.

**Logs**

I don't think we need logs since this issue is very easy to reproduce, the default output doesn't contain anything aside from the songs I played.

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [x] rodio_backend

I installed it from Arch Linux's package repository: https://gitlab.archlinux.org/archlinux/packaging/packages/spotifyd/-/blob/main/PKGBUILD

**Versions (please complete the following information):**

- OS: Arch Linux
- Spotifyd: `spotifyd 0.3.5`
- cargo:  N/A

**Comment by TheDcoder** [comment]
I ran `spotifyd --no-daemon --verbose` just to see if the logs output anything useful, but they don't. There's literally no output after the system woke up. I am not sharing the logs because it has a lot of sensitive information.

**Comment by eladyn** [comment]
This issue is probably the same as #573 and #903, we're currently waiting for an upstream release of `librespot` which would fix part of the problem.
