### ISSUE TITLE
add service for runit 

### ISSUE THREAD

**Issue by twoneis** [Spotifyd/spotifyd#1213]
from my understanding spotifyd can be run as a service on systems using systemd. however there appears to be no folder created in /etc/sv/ to allow it to be run as a runit service easily. 

i hope even though it only affects a tiny percentage of the users, it may be possible to address this issue and create a working service for runit by default that is maintained as part of the project. 

i have tried writing a simple script to do that job myself, however, i am not very experienced with this and it showed quickly. i never got something to run in  a way that would be usable. help with that would also be appreciated, although i hope such changes could be pushed to the official version. 

os: void linux (glibc); version: 0.3.5 (through xbps)

**Comment by slondr** [comment]
Hmm, who maintains spotifyd in xbps?

**Comment by twoneis** [comment]
it appears to be [Andrew Benson](https://github.com/abenson)
