### ISSUE TITLE
Does not work with bluetooth devices

### ISSUE THREAD

**Issue by luispl77** [Spotifyd/spotifyd#1223]
Hello, it seems the spotify player does not stream the audio to bluetooth devices. Is there a way to fix this? When I run 'aplay -L' I don't get the bluetooth device so it seems impossible to make it stream to the device even though it is paired and connected. Would appreciate fixing this thank you

**Comment by kolos26** [comment]
I removed every device related lines from config file, and the system default did ti well

**Comment by luispl77** [comment]
I tried the system default but did not remove the device related lines, will try that soon thank you

**Comment by eladyn** [comment]
This can also depend on the audio server, you're using. So this might be valuable information, if it still doesn't work with the hint from above.

**Comment by luispl77** [comment]
yes it did fix the problem, it now plays to the connected device when I comment the device and control lines. to also be able to control volume, i also needed to control that line. the volume control is not the best, 90% is like 0 volume, and 100 is like all the volume, 50 is the same as 90. But this might be an issue with my bluetooth speaker and not the volume controller, so dont pay much attention to that

**Comment by eladyn** [comment]
The volume issue is probably not you, but `spotifyd` and should hopefully be fixed soon.
