### ISSUE TITLE
After uninstall, systemd still trying to start the spotifyd service

### ISSUE THREAD

**Issue by nevillepark** [Spotifyd/spotifyd#1226]
**Description**

I installed and uninstalled spotifyd months ago (stopped paying for Premium). I thought I removed everything—the binary, the config files, the systemd service, etc. However, when I check the system logs with `journalctl`, systemd is still constantly trying to restart the service (and failing). See the log section for details.

I've grep'd my entire system looking for any file with "spotify" in it, I can't find anything. There's nothing in `/etc/systemd/user/` or `~/.config/systemd/user/` or any of the directories in my $PATH. But just to make sure: which directories are spotifyd files stored in? Are there any other directories/files that were recommended in older versions?

Thanks in advance.

**Logs**
<details><summary>Click to show logs</summary>
<code>Oct 06 15:44:34 [hostname] systemd[688]: Started A spotify playing daemon.
Oct 06 15:44:34 [hostname] systemd[499478]: spotifyd.service: Failed to locate executable /usr/bin/spotifyd: No such file or directory
Oct 06 15:44:34 [hostname] systemd[499478]: spotifyd.service: Failed at step EXEC spawning /usr/bin/spotifyd: No such file or directory
Oct 06 15:44:34 [hostname] systemd[688]: spotifyd.service: Main process exited, code=exited, status=203/EXEC
Oct 06 15:44:34 [hostname] systemd[688]: spotifyd.service: Failed with result 'exit-code'.
Oct 06 15:44:47 [hostname] systemd[688]: spotifyd.service: Scheduled restart job, restart counter is at 53092.
Oct 06 15:44:47 [hostname] systemd[688]: Stopped A spotify playing daemon.
</code>
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Elementary OS 7.1 Horus, based on Ubuntu 22.04.3 LTS. Kernel: Linux 6.2.0-33-generic
- Spotifyd: 
- cargo:

**Comment by slondr** [comment]
How did you install spotifyd?

**Comment by nevillepark** [comment]
Honestly, it was so long ago I don't even remember. I think I may have compiled it from source.

**Comment by nevillepark** [comment]
Update: at some point in the past few days it fixed itself?? I think running `systemctl reset-failed` may have done it, as per [this StackExchange post](https://unix.stackexchange.com/a/418797).

Thanks!
