### ISSUE TITLE
Annoying switching behavior

### ISSUE THREAD

**Issue by natinusala** [Spotifyd/spotifyd#123]
When shutting down Spotify on PC without explicitly pausing playback, it automatically switches to the spotifyd device and resumes playback where it left. This is especially annoying when shutting the PC down as I have to use my phone to silence spotifyd. If the raspberry pi is not plugged to my jack speakers it will continuously play overnight without me even noticing.

I don't know if this behavior is inherent to Spotify Connect or if it comes from spotifyd, but if there is a way to fix it that would be awesome.

**Comment by natinusala** [comment]
It does the same on my tablet occasionnally

**Comment by SirWindfield** [comment]
Good to know, so it's actually not related. It might be a bad internet connection however as I had similar behaviour on cellular data (provider had not that great of a coverage)
