### ISSUE TITLE
Audio Sink Error Connection Refused

### ISSUE THREAD

**Issue by StijnKitsvanHeijningenPXL** [Spotifyd/spotifyd#1233]
**Description**
Running spotifyd manually via command `spotifyd --no-daemon --config-path=/etc/spotifyd.conf` works, however when started as a service using systemd, the error `Audio Sink Error Connection Refused: <PulseAudioSink> Connection refused` is received followed by a crash when trying to play a song.

**To Reproduce**

**Logs**
<details><summary>Click to see logs</summary>

```
Nov 10 16:04:03 spotifyd[10396]: == Starting sink ==
Nov 10 16:04:03 spotifyd[10396]: Audio Sink Error Connection Refused: <PulseAudioSink> Connection refused
Nov 10 16:04:03 systemd[1]: spotifyd.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 16:04:03 systemd[1]: spotifyd.service: Failed with result 'exit-code'.
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Linux 6.5.9-arch2-1 x86_64

- Spotifyd: spotifyd 0.3.5
- cargo: N/A

.service file looks like this: 
```[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/spotifyd --no-daemon --verbose
Restart=always
RestartSec=12
User=root
Group=audio

[Install]
WantedBy=default.target
```

**Comment by eladyn** [comment]
Running `spotifyd` as system service is not something we actively encourage, as you can see in our docs, the recommended way to run `spotifyd` is through a systemd user service. If you still want to go for the system service option, have you made sure that a system-wide pulse audio instance is running? (see e.g. [here](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/))
