### ISSUE TITLE
error: package `time v0.3.28` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.66.1 Either upgrade to rustc 1.67.0 or newer, or use cargo update -p time@0.3.28 --precise ver where `ver` is the latest version of `time` supporting rustc 1.66.1

### ISSUE THREAD

**Issue by rendisadia** [Spotifyd/spotifyd#1234]
error: package `time v0.3.28` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.66.1
Either upgrade to rustc 1.67.0 or newer, or use
cargo update -p time@0.3.28 --precise ver
where `ver` is the latest version of `time` supporting rustc 1.66.1

**Comment by eladyn** [comment]
As you can see in Cargo.toml, the minimum supported rust version is 1.67.0, so you need to `rustup update` in order to compile.
