### ISSUE TITLE
Service stops after user session

### ISSUE THREAD

**Issue by Rocreex** [Spotifyd/spotifyd#124]
Contrary to what the Raspberry Pi Tutorial [here](https://github.com/Spotifyd/spotifyd/wiki/Installing-on-a-Raspberry-Pi) states, the daemon does not stay active after log off. As soon as the user session is finished the service stops as well. Is there any way to solve this issue without defining a root service?

**Comment by blueo** [comment]
I had some success moving the file to `/etc/systemd/system/spotifyd.service` and using the User/Group config and changing the install directive to `multi-user.target`:

```
[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd

[Service]
ExecStart=/usr/bin/spotifyd --no-daemon
Restart=always
RestartSec=12
User=myusername
Group=audio

[Install]
WantedBy=multi-user.target
```

this starts on boot and allows playing without having to log in

**Comment by Rocreex** [comment]
I used the same strategy. Maybe the instructions should be adjusted.

**Comment by flokli** [comment]
@Rocreex, @blueo: most likely your user is currently not allowed to linger.
Try the following:
```
sudo loginctl enable-linger myuser
```
