### ISSUE TITLE
Crash as user service

### ISSUE THREAD

**Issue by Drexel2k** [Spotifyd/spotifyd#1244]
**Description**
Hello,

when I configure spotifyd as a user servie on a Raspberry Pi  as described here: https://docs.spotifyd.rs/installation/Raspberry-Pi.html with

```
sudo loginctl enable-linger <username>
systemctl --user enable spotifyd.service
```

it crashes on start with the following error: 

Message: called 'Result::unwrap()' on an 'Err' value: DnsSdError(Os { code: 19, kind: Uncategorized, message: "No such device" }):

I don't have this problem as system daemon, first I thought this is a syslog issues which is not installed on Raspberry by default, but even with syslog up and running it happtens.

**To Reproduce**
1. Create spotifyd.service: sudo nano /etc/systemd/user/spotifyd.service

```
[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/spotifyd --no-daemon

[Install]
WantedBy=default.target
```

3. Enter 

```
sudo loginctl enable-linger <username>
systemctl --user enable spotifyd.service
```

4. Reboot
5.  Enter

```
ps -aux | grep spot
systemctl --user status spotifyd.service
```

6. You see the process is not running and it crashed

**Expected behavior**
The process should be running

**Logs**
<details><summary>Click to show logs</summary>

```
× spotifyd.service - A spotify playing daemon
     Loaded: loaded (/etc/xdg/systemd/user/spotifyd.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-12-08 13:55:13 CET; 26min ago
   Duration: 411ms
       Docs: https://github.com/Spotifyd/spotifyd
    Process: 810 ExecStart=/usr/bin/spotifyd --no-daemon (code=exited, status=101)
   Main PID: 810 (code=exited, status=101)
        CPU: 29ms

Dec 08 13:55:13 raspifm spotifyd[810]: Using software volume controller.
Dec 08 13:55:13 raspifm spotifyd[810]: no usable credentials found, enabling discovery
Dec 08 13:55:13 raspifm systemd[756]: Started spotifyd.service - A spotify playing daemon.
Dec 08 13:55:13 raspifm spotifyd[810]: The application panicked (crashed).
Dec 08 13:55:13 raspifm spotifyd[810]: Message:  called `Result::unwrap()` on an `Err` value: DnsSdError(Os { code: 19, kind: Uncategorized, message: "No such device" })
Dec 08 13:55:13 raspifm spotifyd[810]: Location: src/setup.rs:105
Dec 08 13:55:13 raspifm spotifyd[810]: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Dec 08 13:55:13 raspifm spotifyd[810]: Run with RUST_BACKTRACE=full to include source snippets.
Dec 08 13:55:13 raspifm systemd[756]: spotifyd.service: Main process exited, code=exited, status=101/n/a
Dec 08 13:55:13 raspifm systemd[756]: spotifyd.service: Failed with result 'exit-code'.

```

</details>

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
cat: command: No such file or directory

spotifyd:https://github.com/Spotifyd/spotifyd/commit/5565f24b5adb0665c5e17de842019727e7456571
cargo: 1.74.1 (ecb9851af 2023-10-18)

Thank you in advance for any help!

**Comment by Drexel2k** [comment]
Related https://github.com/Spotifyd/spotifyd/issues/1227

**Comment by eladyn** [comment]
Indeed, that seems to be the same issue and there's already a workaround implemented (which still needs to be merged and released, however). I'll close this in favour of the other one.
