### ISSUE TITLE
Client becomes invisible for other devices after an undefined time.

### ISSUE THREAD

**Issue by Rocreex** [Spotifyd/spotifyd#127]
I am having the issue that after some time, the Spotify Connect device is not visible anymore on other clients. The only thing to make it reappear is restarting the spotifyd service. The standard logs don't give away anything. It seems like the daemon runs normally. I have yet to figure out an event in the verbose log that might be the cause.

**Comment by zjttoefs** [comment]
Same problem. I also have the playing interrupted mid-song. Same version of spotifyd that worked fine (perfectly in fact - thanks to all committers!) for months. I suspect some recent change on the Spotify side.

**Comment by bertptrs** [comment]
For me, it seems to consistently happen when I log in with Spotifyd on a different device (different hostname as well) then the old one disappears. Restarting the daemon on the original device brings that one back up and hides the other one.

**Comment by boennhoff** [comment]
I got the the similar behaviour like @Rocreex. I currently have no clue or trace to the problem, just the missing _spotify connect device_, which pops up again only after `systemctl --user restart spotifyd`. Host has fixed IP on wired Ethernet. Oh, and there is only one _spotifyd_ daemon running that uses my spotify account.

**Comment by SirWindfield** [comment]
> while with the wireless, I've noticed that when my wifi loose connection and reconnect (due to other problems it happens a lot) spotifyd goes to un-working state.

This happens when the daemon looses network access. The underlying library, `librespot`, fails to reconnect. Nothing we can really do about it on our side (that would be clean to implement).
