### ISSUE TITLE
systemd unit crashes immediately when trying to play anything

### ISSUE THREAD

**Issue by burdoto** [Spotifyd/spotifyd#1274]
**Description**
When started using the provided systemd unit file, regardless of whether being started as a user or root process, spotifyd always crashes trying to find an audio device, regardless of the executing user and group.

**To Reproduce**
1. Start with the provided systemd service
2. Try to change playback to spotifyd
3. Crash

**Expected behavior**
no crash

**Logs**
<details><summary>Click to show logs</summary>

```
Apr 04 18:34:39 netzteil systemd[1]: spotifyd.service: Scheduled restart job, restart counter is at 1.
Apr 04 18:34:39 netzteil systemd[1]: Stopped A spotify playing daemon.
Apr 04 18:34:39 netzteil systemd[1]: Started A spotify playing daemon.
Apr 04 18:34:39 netzteil spotifyd[2444]: Loading config from "/root/.config/spotifyd/spotifyd.conf"
Apr 04 18:34:39 netzteil spotifyd[2444]: No proxy specified
Apr 04 18:34:39 netzteil spotifyd[2444]: Using software volume controller.
Apr 04 18:34:39 netzteil spotifyd[2444]: Ignoring blacklisted access point ap-gew4.spotify.com:4070
Apr 04 18:34:39 netzteil spotifyd[2444]: Ignoring blacklisted access point ap-gew4.spotify.com:443
Apr 04 18:34:39 netzteil spotifyd[2444]: Ignoring blacklisted access point ap-gew4.spotify.com:80
Apr 04 18:34:39 netzteil spotifyd[2444]: Ignoring blacklisted access point ap-gue1.spotify.com:443
Apr 04 18:34:39 netzteil spotifyd[2444]: Failed to resolve Access Point: Unable to resolve any viable access points.
Apr 04 18:34:39 netzteil spotifyd[2444]: Using fallback "ap.spotify.com:443"
Apr 04 18:34:39 netzteil spotifyd[2444]: Connecting to AP "ap.spotify.com:443"
Apr 04 18:34:40 netzteil spotifyd[2444]: Authenticated as "11131851148" !
Apr 04 18:34:40 netzteil spotifyd[2444]: Country: "DE"
Apr 04 18:34:40 netzteil spotifyd[2444]: Mixing with softvol and volume control: Log(60.0)
Apr 04 18:34:40 netzteil spotifyd[2444]: Converting with ditherer: tpdf
Apr 04 18:34:40 netzteil spotifyd[2444]: Using AlsaSink with format: S16
Apr 04 18:35:54 netzteil spotifyd[2444]: Loading <Never Gonna Give You Up> with Spotify URI <spotify:track:4PTG3Z6ehGkBFwjybzWkR8>
Apr 04 18:35:55 netzteil spotifyd[2444]: <Never Gonna Give You Up> (213573 ms) loaded
Apr 04 18:35:55 netzteil spotifyd[2444]: Audio Sink Error Connection Refused: <AlsaSink> Device default May be Invalid, Busy, or Already in Use, ALSA function 'snd_pcm_open' failed with error 'UnknownErrno: Unknown errno'
Apr 04 18:35:55 netzteil systemd[1]: spotifyd.service: Main process exited, code=exited, status=1/FAILURE
Apr 04 18:35:55 netzteil systemd[1]: spotifyd.service: Failed with result 'exit-code'.
```

</details>
This log was gathered from a systemd unit that explicitly starts the service as `root` in the `root` group. No difference when starting as a user or with the `audio` group.

Please note that when started manually from a terminal, spotifyd works just fine as expected. Its __specifically__ the systemd situation that does not work at all.

**Versions (please complete the following information):**
- OS: Raspbian GNU/Linux 11 (bullseye) armv6l
- Spotifyd: 0.3.5
- cargo: none; installed from .tar.gz archive obtained from release

**Comment by eladyn** [comment]
Hmm, that is strange. Have you made sure that the configuration file that is used is the same? To debug the problem, maybe you can try something like replacing the `ExecStart` with `aplay -L` or `aplay -D default /dev/urandom` (**warning**: potentially loud noise coming out of your speaker) and see if this works.

**Comment by burdoto** [comment]
thanks for the advice; i will try once i get the cance because i recently killed the pi that this issue was occurring on 😅😂

**Comment by eladyn** [comment]
Thank you for reporting back. That means, that it is not `spotifyd` at fault here, since `aplay` cannot play audio either. So it's indeed some systemd / audio issue.

**Comment by eladyn** [comment]
If you want, you can join the matrix server, and we can try troubleshooting over there. That is usually easier than through GitHub issues.

**Comment by burdoto** [comment]
I never used matrix before or know how to join, but i'd like to follow that offer.
