### ISSUE TITLE
Volume sets to 0 unexpectedly

### ISSUE THREAD

**Issue by 0xbrayo** [Spotifyd/spotifyd#1288]
**Description**
I set up a systemd service to always start the service on startup. Every single time it starts or I restart the service the volume drops to 0. Ideally it should maintain my current volume setting.

**To Reproduce**
Set up a systemd service to launch spotifyd. Volume changes randomly to 0.

**Expected behavior**
Maintain the current volume setting.

**Versions (please complete the following information):**
spotifyd v0.3.5 (full version from releases)

<!-- **Additional context**
Fedora 40.

**Comment by eladyn** [comment]
Sorry for the long delay!

Might be related to https://github.com/Spotifyd/spotifyd/issues/1222? Otherwise I would guess that you have some weird volume levels defined in your config? Can you maybe paste that here (with sensitive values removed!)?

**Comment by brayo-pip** [comment]
Sorry I distro hopped. Will try setting it up again to see if I can reproduce.

**Comment by eladyn** [comment]
If you got any further feedback or the problem re-occurs, feel free to re-open! :)
