### ISSUE TITLE
Notifications makes spotifyd crash

### ISSUE THREAD

**Issue by 0xbrayo** [Spotifyd/spotifyd#1289]
**Description**
Any audible notification cause spotifyd to crash/exit.

**To Reproduce**
Play music on spotifyd.  
Get an audible notification such as from discord.
Spotifyd crashes/ exits.

**Expected behavior**
Music continues playing after notification.

**Versions (please complete the following information):**
- OS: Fedora 40
- Spotifyd: v0.3.5(full version from releases)

**Comment by eladyn** [comment]
Sorry for the long response time.

Can you provide any logs from `spotifyd`, preferably with `--verbose` turned on?

**Comment by brayo-pip** [comment]
No longer have the same OS installed. Will try to reproduce and send logs.

**Comment by eladyn** [comment]
Please re-open, whenever you got around to reproducing this bug!
