### ISSUE TITLE
Install on macOS

### ISSUE THREAD

**Issue by tnguyen14** [Spotifyd/spotifyd#129]
Is there any chance this library could be made to work on macOS?

**Comment by SimonPersson** [comment]
Yes, it should not be too much work. You could try to just disable the alsa option, and enable the `portaudio` backend in the librespot dependency. It might just be some modifications to `Cargo.toml`. Feel free to ask more questions if you run into issues, and to submit a PR if you get it working :)

**Comment by tnguyen14** [comment]
Thanks. I could confirm that it compiles successfully with 
```
brew install portaudio
cargo build --release --no-default-features --features portaudio_backend
```

@SimonPersson when I run `target/release/spotifyd`, with the configuration file, it just exits right away with 0 exit code. Is that to be expected?

**Comment by SimonPersson** [comment]
Great!

Yes, spotifyd daemonizes by default. Try running with `--no-daemon`.

**Comment by Crazybus** [comment]
@SimonPersson Small update from me. I have been using it for a few days now and it has been stable without any skipping or anything too. So it is working beautifully on OSX as expected :)

**Comment by tnguyen14** [comment]
Thanks @SimonPersson. I created https://github.com/Spotifyd/spotifyd/issues/143 to track that. I am not familiar with Rust and librespot. Will take some time playing around with it.
