### ISSUE TITLE
Spotifyd not an executable?

### ISSUE THREAD

**Issue by stevenveenma** [Spotifyd/spotifyd#1294]
**Description**
After downloading and installing spotifyd the file is there but not starting up:
which spotifyd gives /usr/bin/spotifyd proves the file is there
/usr/bin $ spotifyd --no-daemon gives bash: /usr/bin/spotifyd: No such file or directory
ldd /usr/bin/spotifyd gives not a dynamic executable
/usr/bin $ ls -l /usr/bin/spotifyd
-rwxr-xr-x 1 1001 saned 16183544 May  3  2023 /usr/bin/spotifyd again proves the file is there and rights are ok.

**To Reproduce**
0. use  /usr/bin folder
1 sudo wget https://github.com/Spotifyd/spotifyd/releases/download/v0.3.5/spotifyd-linux-armv6-slim.tar.gz
2. sudo tar xzf spotifyd-linux-armv6-slim.tar.gz
3.  A proper .conf file and spotify.services have been made

**Expected behavior**
Spotify should start up and should be visible in clients

**Logs**
-- verbose is not usable as the file reports as a non-executable

**Versions (please complete the following information):**
- Spotifyd: 3.5
- Raspberry Pi 3 Model B Rev 1.2
- OS: Debian 20231012~bullseye v11
- Backend is alsa and an external soundcard

<!-- **Additional context**
I have used spotifyd for many years on a RPI 2 and love it. Unfortunately upgrade is not possible on this system and I moved to a RPI3B and a recent version of Debian.

**Comment by eladyn** [comment]
You're probably running aarch64 on your Pi, right? In this case, you'd need to enable the 32bit architecture first. I hope to merge this PR soon, but in the meantime, see https://github.com/Spotifyd/spotifyd/pull/1243 for documentation.

**Comment by stevenveenma** [comment]
Thanks for your quick reply. I am surprised, why is aarch64 not supported by default? And why is this not mentioned in the wiki? It took me hours and hours trying and debugging yesterday. I knew it should work and was working well on my old setup, but I think many first time users would have quit. I am aware spotifyd is a community effort and this is done by people in their spare time, but one additional sentence in the wiki.....

Using the modified documentation you referred to I first tried ## Option 1: Compiling the 64 bit version but the rust toolchain doesn't want to be installed and my RPI crashed twice. ## Option 2: Add the 32 bit architecture is easier and succeeded in a few minutes. Spotify finally showed up in my client.

I spent some time figuring out my ecasound and alsa setup and installed my biquads and finally my active 4 channel digital filtered speakers are playing again with Spotify as source.

**Comment by eladyn** [comment]
I'm sorry this caused you so much trouble. I hope to be able to merge the mentioned PR in the next few days. And the docs really need some love, for sure! I'm not entirely sure on the aarch64 situation, it has been some time since I last looked at our workflows. But there's a tracking issue for that one [here](https://github.com/Spotifyd/spotifyd/issues/280).

And good point regarding the order of the options. I will make sure to swap them and/or mark the one as recommended when I merge it.
