### ISSUE TITLE
Message 'Cache couldn't be initialized: File exists (os error 17)' on startup

### ISSUE THREAD

**Issue by janui** [Spotifyd/spotifyd#1296]
**Description**
The message 'Cache couldn't be initialized: File exists (os error 17)'  is reported consistently on startup. This happens when the cache_path and max_cache_size entries in spotifyd.conf are commented out. Adding 'no_audio_cache = true' makes no difference.

**To Reproduce**
1. In spotifyd.conf comment out cache_path, max_cache_size and no_audio_cache entries in spotifyd.conf
2. start spotifyd

**Expected behavior**
The message 'Cache couldn't be initialized: File exists (os error 17)' should not be present when the cache is disabled.

**Logs**
Aug 06 10:23:13 pi4 systemd[1]: Starting spotifyd.service - Spotifyd - A spotify playing daemon - Spotify Connect Receiver...
Aug 06 10:23:13 pi4 spotifyd[19919]: Loading config from "/etc/spotifyd.conf"
Aug 06 10:23:13 pi4 spotifyd[19919]: **Cache couldn't be initialized: File exists (os error 17)**
Aug 06 10:23:13 pi4 spotifyd[19919]: No proxy specified
Aug 06 10:23:13 pi4 spotifyd[19919]: Using alsa volume controller.
Aug 06 10:23:13 pi4 spotifyd[19919]: Ignoring blacklisted access point ap-gew4.spotify.com:4070
Aug 06 10:23:13 pi4 spotifyd[19919]: Ignoring blacklisted access point ap-gew4.spotify.com:443
Aug 06 10:23:13 pi4 spotifyd[19919]: Ignoring blacklisted access point ap-gew4.spotify.com:80
Aug 06 10:23:13 pi4 spotifyd[19919]: Ignoring blacklisted access point ap-gue1.spotify.com:4070
Aug 06 10:23:13 pi4 spotifyd[19919]: Connecting to AP "ap-gew1.spotify.com:443"
Aug 06 10:23:14 pi4 spotifyd[19919]: Authenticated as "xxx" !
Aug 06 10:23:14 pi4 spotifyd[19919]: Country: "XY"
Aug 06 10:23:14 pi4 spotifyd[19919]: Converting with ditherer: tpdf
Aug 06 10:23:14 pi4 spotifyd[19919]: Using AlsaSink with format: S16
Aug 06 10:23:14 pi4 spotifyd[19919]: Running "/srv/http/command/spotify_connect_command.sh" using "/usr/bin/bash" with environment variables {"PLAYER_EVENT">....
Aug 06 10:23:14 pi4 spotifyd[19919]: 1
Aug 06 10:23:14 pi4 spotifyd[19919]: 2

**Compilation flags** 
Unknown - I can find out if required

**Versions (please complete the following information):**
- Operating System: Raspbian GNU/Linux 12 (bookworm)
- Kernel: Linux 6.6.28+rpt-rpi-v8 (32-bit)
- Spotifyd: spotifyd 0.3.5
- cargo: Unknown - I can find out if required

**Comment by eladyn** [comment]
Could you maybe run `spotifyd` with the `--verbose` flag to get the debug logs and/or upload the config file (with sensitive values removed!)?

**Comment by janui** [comment]
Hi eladyn,

Thanks for the response.
Normally spotifyd runs as a systemd unit with user: spotifyd and groep: spotifyd.
In this case for debugging, this is the command I used to start spotifyd from the cli:
`sudo -u spotifyd /usr/bin/spotifyd --no-daemon --verbose -c /etc/spotifyd.conf > /home/spotifyd.log
`
This the contents of /etc/passwd for user spotifyd:
`spotifyd:x:1003:1003:spotifyd systemd user:/dev/null:/usr/bin/bash
`
And the output of: id spotifyd:
`uid=1003(spotifyd) gid=1003(spotifyd) groups=1003(spotifyd),29(audio)
`
And the output of: groups spotifyd:
`spotifyd : spotifyd audio`

This is my config file:
```
[global]
autoplay = true
backend = "alsa"
bitrate = 320
# Disable the cache, it uses too much memory
# cache_path = "/tmp/spotifyConnectCache"
# Maximum cache size 50Kb, defined in bytes
# max_cache_size = 50000
device = "hw:CARD=sndrpihifiberry"
device_name = "Pi4"
device_type = "speaker"
# initial_volume gets used when spotifyd starts, not when the stream starts
initial_volume = "100"
mixer = "Digital"
normalisation-pregain = 0
onevent = "/srv/http/command/spotify_connect_command.sh"
use_mpris = false
volume-control = "alsa"
volume-normalisation = false
```

This is the first part of the log:
```
Loading config from "/etc/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: None, username_cmd: None, password: None, password_cmd: None, use_keyring: false, use_mpris: Some(false), dbus_type: None, on_song_change_hook: Some("/srv/http/command/spotify_connect_command.sh"), cache_path: Some("/etc/spotifyd.conf"), no-audio-cache: false, backend: Some(Alsa), volume_controller: Some(Alsa), device: Some("hw:CARD=sndrpihifiberry"), control: None, mixer: Some("Digital"), device_name: Some("Pi4"), bitrate: Some(Bitrate320), audio_format: None, initial_volume: Some("100"), volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: Some(Speaker), autoplay: true, max_cache_size: None } }
Cache couldn't be initialized: File exists (os error 17)
Found user shell: Some("/usr/bin/bash")
No username specified. Checking username_cmd
No username_cmd specified
No password specified. Checking password_cmd
No password_cmd specified
No proxy specified
Using alsa volume controller.
no usable credentials found, enabling discovery
Using device id 'c3ddfc476c3a414a6faa1ce0f3837850eb39722e'
Zeroconf server listening on 0.0.0.0:38977
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
sending packet to 224.0.0.251:5353
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
sending packet to [ff02::fb]:5353
error sending packet Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.13:5353
received question: IN wpad.local
received packet from 192.168.2.11:5353
received question: IN _companion-link._tcp.local
received question: IN _rdlink._tcp.local
received question: IN _homekit._tcp.local
received question: IN _sleep-proxy._udp.local
received packet from 192.168.2.11:5353
received question: IN _companion-link._tcp.local
received question: IN _rdlink._tcp.local
received question: IN _homekit._tcp.local
received question: IN _sleep-proxy._udp.local
received packet from 192.168.2.13:5353
received question: IN hifi.local
received packet from 192.168.2.13:5353
received question: IN hifi.local
received packet from 192.168.2.13:5353
received question: IN hifi.local
received packet from 192.168.2.13:5353
received question: IN hifi.local
received packet from 192.168.2.13:5353
received question: IN hifi.local
received packet from 192.168.2.13:5353
received question: IN hifi.local
received packet from 192.168.2.10:5353
received packet from 192.168.2.10:5353 with no query
received packet from 192.168.2.13:5353
received question: IN pi4.local
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
received packet from 192.168.2.14:5353
received question: IN pi4.local
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
received packet from 192.168.2.13:5353
received question: IN pi4.local
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
sending packet to 224.0.0.251:5353
sending packet to 224.0.0.251:5353
sending packet to 224.0.0.251:5353
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
received packet from 192.168.2.13:5353
received question: IN pi4.local
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
received packet from 192.168.2.13:5353
received question: IN pi4.local
found interface Interface { name: "eth0", addr: V4(Ifv4Addr { ip: 192.168.2.14, netmask: 255.255.255.0, broadcast: Some(192.168.2.255) }) }
sending packet to 224.0.0.251:5353
sending packet to 224.0.0.251:5353
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
Shutting down discovery server
sending packet to 224.0.0.251:5353
sending packet to [ff02::fb]:5353
error sending packet Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }
received packet from 192.168.2.14:5353
received packet from 192.168.2.14:5353 with no query
```

Note: I am now using spotifyd in discovery mode. Previously a username and password was used until that stopped working. This has no effect on the  'Cache couldn't be initialized: File exists (os error 17)' message. And regardless of the message 'error sending packet Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }' spotifyd works fine. 

janui

**Comment by eladyn** [comment]
Oh, I see now. Your problem is the `-c`, which is not a shorthand for `--config-path` but rather for `--cache-path`. (See the dumped config in the second line of your log: `... cache_path: Some("/etc/spotifyd.conf"), ...`)

**Comment by janui** [comment]
Hi eladyn,

Many thanks, thats fixed it. Closing the issue.

janui
