### ISSUE TITLE
Multiple processes listed

### ISSUE THREAD

**Issue by randompersondude** [Spotifyd/spotifyd#1303]
**Description**

When I enter "spotifyd" in my terminal, and then run ps -aux | grep spot, it shows two processes, spotifyd, and /usr/bin/spotifyd --no-daemon.

if i play music, and kill the /usr/bin/spotifyd --no-daemon one, the music continues, however the process pops up again after a few seconds.

if i kill the one thats just spotifyd, the music stops. the other process stays running though.

I'm wondering what the purpose of these are?

**To Reproduce**
run spotifyd.

run ps -aux | grep spot

**Expected behavior**

one process?

**Versions (please complete the following information):**

- OS:  arch
- Spotifyd:  spotifyd 0.3.5
- cargo:  cargo 1.80.1 (376290515 2024-07-16)

**Comment by eladyn** [comment]
Are you sure that nothing just starts another instance of `spotifyd` automatically? To me, it sounds like `systemd` is just restarting `/usr/bin/spotifyd --no-daemon` as soon as it stops.

**Comment by eladyn** [comment]
If there's anything else we can help with or you're still running into the problem, feel free to re-open.
