### ISSUE TITLE
Panic on ChannelError

### ISSUE THREAD

**Issue by deify** [Spotifyd/spotifyd#131]
spotifyd is sporadically crashing during playback.

I am getting the following errors messages: 

> **17:40:24 [INFO] Loading track "21st Century Liability" with Spotify URI "spotify:track:5WAsLiCOLiz2iwJLcuJEgb"**
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:185] writing; remaining=49
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 559164 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 407262389 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 161979 }
> 17:40:24 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
> 17:40:24 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 42202857 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 449713370 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 163957 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 28020 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 450111128 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 163697 }
> 17:40:24 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
> 17:40:24 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 88427672 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 538781872 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 184010 }
> 17:40:24 [DEBUG] librespot_audio::fetch: Downloading file 9d855ab455403b8700f3af18299930983f628192
> 17:40:24 [TRACE] librespot_audio::fetch: [/home/mitch/.cargo/git/checkouts/librespot-06fda9f186b35c32/817dff0/audio/src/fetch.rs:173] requesting chunk 0
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:185] writing; remaining=53
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 774736 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 539850252 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 275467 }
> 17:40:24 [DEBUG] tokio_core::reactor: consuming notification queue
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 141770 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 540443739 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 158801 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 14635 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 540696237 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 156979 }
> 17:40:24 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
> 17:40:24 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
> 17:40:24 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:24 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:24 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 158025181 }
> **[ERROR] channel error: 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 699198551 }
> 2 1**
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 202707 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 17760 }
> **17:40:24 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError**
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 699512091 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 166666 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 16406 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 699804902 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 240520 }
> 17:40:24 [DEBUG] librespot_playback::player: drop Player[0]
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 7709 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 700236775 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 216040 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 6146 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93621, tv_nsec: 700572242 }
> 17:40:24 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 159999 }
> 17:40:50 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
> 17:40:50 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:40:50 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:50 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
> 17:40:50 [DEBUG] librespot_core::session: Session[0] strong=2 weak=4
> 17:40:50 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:185] writing; remaining=11
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:50 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 25, nanos: 872005877 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93647, tv_nsec: 572819055 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 170468 }
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:50 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 156301 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93647, tv_nsec: 573237021 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 146562 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 14844 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93647, tv_nsec: 573476968 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 151770 }
> 17:40:50 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
> 17:40:50 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:40:50 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:50 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
> 17:40:50 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:40:50 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:40:50 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 43941749 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93647, tv_nsec: 617648612 }
> 17:40:50 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 217291 }

Process aborted by user using CTRL+C at this point

> 17:42:37 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(12582915)
> 17:42:37 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:42:37 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 106, nanos: 512648505 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93754, tv_nsec: 130634147 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 222446 }
> 17:42:37 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:42:37 [TRACE] tokio_io::framed_write: [<unknown>:185] writing; remaining=1442
> 17:42:37 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:42:37 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 471456 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93754, tv_nsec: 131778099 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 159790 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 15209 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93754, tv_nsec: 132061639 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 156718 }
> 17:42:37 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
> 17:42:37 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:42:37 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:42:37 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
> 17:42:37 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
> 17:42:37 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
> 17:42:37 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
> 17:42:37 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 50111700 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 93754, tv_nsec: 182409171 }
> 17:42:37 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 162551 }
> 17:42:37 [DEBUG] librespot_connect::spirc: drop Spirc[0]
> 17:42:37 [DEBUG] librespot_playback::player: Shutting down player thread ...
> **17:42:37 [ERROR] Player thread panicked!**
> 17:42:37 [DEBUG] librespot_core::session: drop Session[0]
> 17:42:37 [DEBUG] librespot::component: drop AudioKeyManager
> 17:42:37 [DEBUG] librespot::component: drop ChannelManager
> 17:42:37 [DEBUG] librespot::component: drop MercuryManager
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:64] shutdown; state=State { lifecycle: 0, num_futures: 0 }
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:110]   -> transitioned to shutdown
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:122]   -> shutting down workers
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=3; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=3
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=3
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=2; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=2
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=2
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=1; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=1
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=1
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=0; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=0
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=0
> 17:42:37 [TRACE] tokio_threadpool::inner: [<unknown>:179] notifying shutdown task
> 17:42:37 [TRACE] tokio_threadpool::shutdown: [<unknown>:38] Shutdown::poll
> 17:42:37 [TRACE] tokio_reactor: [<unknown>:345] event Readable Token(4194303)
> 17:42:37 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
> 17:42:37 [DEBUG] tokio_reactor::background: shutting background reactor down NOW
> 17:42:37 [DEBUG] tokio_reactor::background: background reactor has shutdown
> 17:42:37 [DEBUG] librespot_core::session: drop Dispatch
> 

This error is happening after some songs have been played from the playlist. After restarting the daemon  and playing the exact same song, the playback is beeing resumed.

**Comment by luzik** [comment]
Same here:

```
13:25:37 [INFO] Loading track "Na Skróty" with Spotify URI "spotify:track:4CHkLjSEGnMQobnTCpeWGH"
13:25:38 [ERROR] channel error: 2 1
13:25:38 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
15:55:40 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
15:55:40 [ERROR] Player thread panicked!
```

**Comment by DvdChe** [comment]
Hello ! Same here too : 

```
May 08 12:24:05 raspberrypi spotifyd[7209]: 12:24:05 [ERROR] channel error: 2 1
May 08 12:24:05 raspberrypi spotifyd[7209]: 12:24:05 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
```

Result of lsof : 
```
COMMAND   PID USER   FD      TYPE     DEVICE SIZE/OFF  NODE NAME
spotifyd 7209 root  cwd       DIR      179,2     4096     2 /
spotifyd 7209 root  rtd       DIR      179,2     4096     2 /
spotifyd 7209 root  txt       REG      179,2 11531590  6962 /usr/bin/spotifyd
spotifyd 7209 root  mem       REG      179,2    75608  1967 /lib/arm-linux-gnueabihf/libresolv-2.24.so
spotifyd 7209 root  mem       REG      179,2    18012  1941 /lib/arm-linux-gnueabihf/libnss_dns-2.24.so
spotifyd 7209 root  mem       REG      179,2     9572  1946 /lib/arm-linux-gnueabihf/libnss_mdns4_minimal.so.2
spotifyd 7209 root  mem       REG      179,2    38560  1942 /lib/arm-linux-gnueabihf/libnss_files-2.24.so
spotifyd 7209 root  mem       REG      179,2    38588  1950 /lib/arm-linux-gnueabihf/libnss_nis-2.24.so
spotifyd 7209 root  mem       REG      179,2    71604  1939 /lib/arm-linux-gnueabihf/libnsl-2.24.so
spotifyd 7209 root  mem       REG      179,2    26456  1940 /lib/arm-linux-gnueabihf/libnss_compat-2.24.so
spotifyd 7209 root  mem       REG      179,2   452152  1930 /lib/arm-linux-gnueabihf/libm-2.24.so
spotifyd 7209 root  mem       REG      179,2   116372  1918 /lib/arm-linux-gnueabihf/libgcc_s.so.1
spotifyd 7209 root  mem       REG      179,2   127300  1964 /lib/arm-linux-gnueabihf/libpthread-2.24.so
spotifyd 7209 root  mem       REG      179,2    26632  1968 /lib/arm-linux-gnueabihf/librt-2.24.so
spotifyd 7209 root  mem       REG      179,2     9800  1912 /lib/arm-linux-gnueabihf/libdl-2.24.so
spotifyd 7209 root  mem       REG      179,2  1234700  1903 /lib/arm-linux-gnueabihf/libc-2.24.so
spotifyd 7209 root  mem       REG      179,2   902752 10593 /usr/lib/arm-linux-gnueabihf/libasound.so.2.0.0
spotifyd 7209 root  mem       REG      179,2    21868 10591 /usr/lib/arm-linux-gnueabihf/libarmmem.so
spotifyd 7209 root  mem       REG      179,2   138576  1855 /lib/arm-linux-gnueabihf/ld-2.24.so
spotifyd 7209 root    0r      CHR        1,3      0t0  1028 /dev/null
spotifyd 7209 root    1u     unix 0xb8bad800      0t0 45601 type=STREAM
spotifyd 7209 root    2u     unix 0xb8bad800      0t0 45601 type=STREAM
spotifyd 7209 root    3u  a_inode       0,11        0  4977 [eventpoll]
spotifyd 7209 root    4r     FIFO       0,10      0t0 41639 pipe
spotifyd 7209 root    5w     FIFO       0,10      0t0 41639 pipe
spotifyd 7209 root    6u     IPv4      41642      0t0   TCP *:35739 (LISTEN)
spotifyd 7209 root    7u     IPv4      41643      0t0   UDP *:mdns 
spotifyd 7209 root    8u     IPv6      41644      0t0   UDP *:mdns 
spotifyd 7209 root    9u     unix 0xb8914c00      0t0 41645 type=STREAM
spotifyd 7209 root   10u     unix 0xb8914300      0t0 41646 type=STREAM
spotifyd 7209 root   11u     IPv4      41651      0t0   TCP 192.168.0.3:35996->97.64.199.104.bc.googleusercontent.com:4070 (ESTABLISHED)
```

Result of strace : 
```
futex(0x7681e064, FUTEX_WAIT_PRIVATE, 25301, NUL
```

**Comment by Schlump** [comment]
After a few songs: 
May 10 16:01:43 raspberrypi spotifyd[432]: 14:01:43 [ERROR] channel error: 2 1
May 10 16:01:43 raspberrypi spotifyd[432]: 14:01:43 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError

**Comment by dvtkrlbs** [comment]
I get the similar error with 
20:34:04 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Invalid number of channels

**Comment by dvtkrlbs** [comment]
when i try to pause 
20:36:54 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
20:36:54 [ERROR] Player thread panicked!

**Comment by SirWindfield** [comment]
Has been some time. Do you guys still encounter this problem? If not I'll just close it up.

**Comment by joeysapp** [comment]
I'm getting something similar:
Sep 22 22:36:53 foo Spotifyd[1032]: Caught panic with message: called `Result::unwrap` on an `Err` value: "SendError(..)"
Sep 22 22:36:53 foo Spotifyd[1032]: Player thread panicked!

**Comment by SirWindfield** [comment]
Any way I can reproduce it? I run the daemon 24/7 on my machine (connected via ethernet) and it works without problems :(

**Comment by Mitschmaster** [comment]
I had the same error. spotifyd stopped working completely. workaround is to set the bitrate from 320 to 160 bps.

**Comment by zkiiito** [comment]
i also have this issue, mainly when i listen to new songs, that i haven't heard before, very low listen counts, and i think they are "not ready" for this?

**Comment by xpressio** [comment]
I'm also encountering the issue described above: Suddenly, no more sound output; on the client player, playback appears to continue normally. Only solution so far: `systemctl restart spotifyd`. The problem typically occurs after one hour of playback.

Syslog reads:
```
spotifyd[29199]: channel error: 2 1
spotifyd[29199]: error from channel
...
 spotifyd[29199]: error from channelspotifyd[29199]: channel error: 2 1
```
I am currently using 320 bitrate, I will now set 160 to and verbose logging to further investigate.

Seeing that this issue is still marked as 'open', are people still experiencing this issue? Any workarounds or clues what's causing this?

**Comment by Mitschmaster** [comment]
i must say that i did not have this problem since.

**Comment by RAR27** [comment]
I am getting this as well. However, I think it only occurs when I play very small tracks (< 10 seconds). Hasn't happened with me with bigger tracks.

**Comment by zjttoefs** [comment]
I also get this. Even somewhat reproducibly with spotify:track:27M2m1NzEmCkzb9kzTLqzT

All of the five recent tracks that this happened with are less than a minute in length 0:59, 0:40, 0:39. So @RAR27 could be on to something that length has an impact.

Out of interest: What's the rationale for spotify to continue running after a panic? If the process died, systemd would spawn a new one and things would be back to working and one could resume playback from normal spotify controls. As it is manual intervention on the command line is required (or some automated script logic based on the panic log message).

**Comment by hlbstd** [comment]
I can reproduce the issue 100% with this track:
Loading <Visions fugitives, Op. 22: V. Molto giocoso> with Spotify URI <spotify:track:5p8xMndyt5UJElmtcdPMVv>
channel error: 2 0
It is is a 34 seconds track.

**Comment by SirWindfield** [comment]
@zjttoefs Not gonna lie, I didn't look that much into the playback code. Most of the work I've done is in the MPRIS/config department. I will get back to the project once I can update librespot, we are still waiting for a particular PR and I do not really want to rely on the `master` branch of them.

It's interesting though that it happens with songs shorter than a minute. and @hlbstd, thanks for the find. Makes it a lot of easier later on to debug it with a song that can reproduce it 100% of the time. Mind sharing your spotifyd configuration as well? Alongside the backend you're using and OS. :)

**Comment by mbarton** [comment]
I can also reproduce with a 34 second long track:

```
Jul 12 11:27:27 raspberrypi spotifyd[589]: Loading <Avalanche Rock> with Spotify URI <spotify:track:7semwZGt9Q285eonEMJrgx>
Jul 12 11:27:27 raspberrypi spotifyd[589]: channel error: 2 0
Jul 12 11:27:27 raspberrypi spotifyd[589]: Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
Jul 12 11:27:34 raspberrypi spotifyd[589]: Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
Jul 12 11:27:34 raspberrypi spotifyd[589]: Player thread panicked!
```

I'm running Raspbian 10 (Buster) on a Raspberry Pi 3:

`Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux`.

spotifyd config:

```
device_name = stanmore_via_pi
bitrate = 320
username = <redacted>
password = <redacted>
```

I'm using the alsa backend.

**Comment by slondr** [comment]
Can confirm I'm also having this issue now, it happens immediately when I play any song.

**Comment by nefh** [comment]
Confirming, the problem exist for me as well:

channel error: 2 0
Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
Player thread panicked!

**Comment by nefh** [comment]
I used daemon argument to auto restart process after crash („-r”)
 
![CC84790C-0D23-4863-A56B-BA7BFFA0A0CF](https://user-images.githubusercontent.com/35170530/90308901-bc850c80-dee3-11ea-98ba-8e4d48eb761b.jpeg)

However now when ChannelError occurs, the service is not being killed, it is still listed on spotify connect devices, only speakers remain silent. The service is not being restarted. Logs:

<spotify:track:5VPBbqrApOqpp4olQPvrG2>
channel error: 2 0
error from channel
Loading config from "/usr/local/etc/spotifyd.conf"

Config loading is from manual service restart, without it, it stays at „error from channel”.

**Comment by stateisbad** [comment]
Same here. Thought I was certainly going to be alone on this, but happy in some ways to see it's not just me. This started happening pretty recently, like the last week or two, like others have mentioned. Using the alsa backend through a hifiberry. Worked great for a long time, then out of nowhere it stopped. I'm assuming something RPi OS-related broke maybe something, like a kernel update or something?

**Comment by awerlang** [comment]
It's also reported when spotifyd isn't involved. See https://github.com/librespot-org/librespot/issues/519.

The Java port doesn't uses channels, but CDN instead and seems to not have this issue.

**Comment by stateisbad** [comment]
So seems like a rust developer needs to fix and PR librespot. :(
