### ISSUE TITLE
Problem at installation in raspberry pi

### ISSUE THREAD

**Issue by AndresAyala32** [Spotifyd/spotifyd#1313]
Hello, im not sure what did I miss or did wrong, not an expert at all.
I wanted to install spotifyd on my raspberry pi 4 (raspbian arm64) and I tried what is on the docs:
https://docs.spotifyd.rs/installation/Raspberry-Pi.html
but when running './spotifyd --no-daemon' it outputs './spotifyd: cannot execute: required file not found', it is a fresh install.
Any idea of what went wrong? Even tried to make a file 'spotifyd.config' but nothing, and there are not logs since I just downloaded the repository and extracted it.
Thanks

**Comment by jroth2** [comment]
Having the same issue.

Using raspberry pi zero 2 w
most recent spotifyd-linux-armv6-slim.tar.gz binary
Raspberry Pi OS Lite 64 bit

**Comment by Plasmaman916** [comment]
Having the same issue as well.

Tried using pi 3 and pi 4.
Tried armhf and armv6 with v0.3.3, v0.3.4, and 0.3.5

Raspberry Pi OS (64-bit)

**Comment by jroth2** [comment]
@AndresAyala32 I was able to setup raspotify for my raspberry pi. I was running it headless, so if that's what you need it for try that in the meantime. I was trying to set this up as a gift for my wife on our new receiver/speaker combo, needed a quick alternative for Christmas if you wanted to try that instead.

https://github.com/dtcooper/raspotify

**Comment by eladyn** [comment]
Sorry for not responding earlier. This is a long-standing issue, unfortunately (https://github.com/Spotifyd/spotifyd/issues/280). It can be worked around using [this guide](https://github.com/Spotifyd/spotifyd/blob/bd2592e6da3325be9de455aaf6bde0e7eb44ea03/docs/src/installation/Raspberry-Pi-64_ARM64.md), which unfortunately still hasn't made its way to the docs yet.
