### ISSUE TITLE
Error on external device event

### ISSUE THREAD

**Issue by SnouF** [Spotifyd/spotifyd#136]
Hello

Since today spotifyd carsh with on an "external device event" (Android, or linux client)

`[ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))`

The bug is sytematic
I run spotifyd `spotifyd --no-deamon`
I run spotify on android -> crash (without connection request spotify-connect)
I run spotify on linux same thing.

Yesterday everything worked

**Comment by SnouF** [comment]
and  #137

**Comment by SimonPersson** [comment]
This issue is fixed by #135. Thanks for reporting.
