### ISSUE TITLE
WireError(InvalidEnumValue(14))

### ISSUE THREAD

**Issue by uweschmitt** [Spotifyd/spotifyd#140]
I just installed the [latest release](https://github.com/Spotifyd/spotifyd/releases/tag/untagged-c16e4f3b11b9c06ccf49) and when I try to connect I get
 
`Caught panic with message: called "Result::unwrap()" on an "Err" value: WireError(InvalidEnumValue(14))
`

**Comment by Sudiukil** [comment]
Same issue here with latest release

**Comment by praul** [comment]
You can build yourself with rustup nightly, or use the build I compiled on sunday (armhf, working)
https://github.com/Spotifyd/spotifyd/files/2034467/spotifyd_armhf_180518.zip

**Comment by Sudiukil** [comment]
@praul Thanks, I'll try that

**Comment by devhen** [comment]
I'm getting the same error. I'm trying to build on Fedora and I get:

    error: process didn't exit successfully: `rustc -vV` (exit code: 101)
    --- stdout
    rustc 1.26.0
    binary: rustc
    commit-hash: unknown
    commit-date: unknown
    host: x86_64-unknown-linux-gnu
    release: 1.26.0
    
    --- stderr
    error: failed to find a `codegen-backends` folder in the sysroot candidates:
    * /usr
    * /usr

Anyone know how I can fix this? Thanks.

**Comment by SimonPersson** [comment]
How strange, it almost looks like a bug with Travis. I ran the build again and the latest release works on x86 at least. Can you confirm that it works om ARM as well?

**Comment by bertptrs** [comment]
I've rebuilt it on a Raspberry Pi 2b (rustc 1.26, Arch Linux Arm) and now it works.

**Comment by SimonPersson** [comment]
@bertptrs - I meant that I think the binary release should work now. Unfortunately I don't have an ARM device around to test it on.

**Comment by bertptrs** [comment]
@SimonPersson I misunderstood. I've tested the most recent binary release and it works.

**Comment by SimonPersson** [comment]
Thanks! I'll close this then.
