### ISSUE TITLE
Enable http proxy configuration

### ISSUE THREAD

**Issue by tnguyen14** [Spotifyd/spotifyd#143]
Currently, spotifyd doesn't work with `https_proxy` setting.

https://github.com/Spotifyd/spotifyd/issues/129#issuecomment-392869695 by @tnguyen14
>```[WARN] Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }```
> It is likely due to the fact that I have a work VPN on. I do have https_proxy set to go to the Internet. Do you know if Spotifyd would work with proxy?

and https://github.com/Spotifyd/spotifyd/issues/129#issuecomment-392871871 by @SimonPersson 

>@tnguyen14 - We don't have proxy support, but it would be simple to add. See https://github.com/Spotifyd/spotifyd/blob/master/src/config.rs if you want to hack on it. Essentially we just need to add it as a config option and pass it along to librespot.

**Comment by Starkstromkonsument** [comment]
It would be great if you could implement this! Same with #265

**Comment by SirWindfield** [comment]
Well, I tried it. It's currently not really possible as `librespot` uses `serde@0` which implies `url@1.7`. They are incompatible with the crate versions currently used in this library.

**Comment by meain** [comment]
I do not have a VPN, but I am still hitting this issue. I am on `macOS` though.
