### ISSUE TITLE
Loading any track in spotifyd kills machine ethernet connection after a few seconds

### ISSUE THREAD

**Issue by m1nde** [Spotifyd/spotifyd#144]
I have no idea whats going on behind the scenes here. Yet, this issue persists after multiple reboots, cache clears and is 100% reproducible for me.
I use spotifyd-bin from the AUR on Arch Linux. That is spotifyd 0.2.1-1_amd64.
I start spotifyd with `spotifyd --no-daemon`, it starts up without a problem, it shows up as a Spotify Connect Client on my phone, I can start playing music over it.

And apparently, spotifyd loads it without a problem:
```
19:57:17 [INFO] Using software volume controller.
19:57:17 [INFO] Connecting to AP "gew1-accesspoint-b-vdsm.ap.spotify.com:4070"
19:57:17 [INFO] Authenticated as "xxx" !
19:57:17 [INFO] Using alsa sink
19:57:17 [INFO] Country: "DE"
20:05:58 [INFO] Loading track "Low Rider" with Spotify URI "spotify:track:1c3XhGFr9CDZ7YVIhx1131"
20:06:00 [INFO] Track "Low Rider" loaded

```
Just a couple of seconds later, my internet connection drops, and naturally, a minute later spotifyd playback stops:
```
20:06:00 64 bytes from 8.8.8.8: icmp_seq=550 ttl=59 time=29.5 ms
20:06:01 64 bytes from 8.8.8.8: icmp_seq=551 ttl=59 time=27.8 ms
20:06:02 64 bytes from 8.8.8.8: icmp_seq=552 ttl=59 time=36.4 ms
20:06:03 64 bytes from 8.8.8.8: icmp_seq=553 ttl=59 time=34.4 ms
20:06:05 64 bytes from 8.8.8.8: icmp_seq=554 ttl=59 time=277 ms
20:06:06 64 bytes from 8.8.8.8: icmp_seq=555 ttl=59 time=193 ms
20:06:07 64 bytes from 8.8.8.8: icmp_seq=556 ttl=59 time=185 ms
20:06:08 64 bytes from 8.8.8.8: icmp_seq=557 ttl=59 time=98.1 ms
20:06:08 64 bytes from 8.8.8.8: icmp_seq=558 ttl=59 time=66.7 ms
20:06:09 64 bytes from 8.8.8.8: icmp_seq=559 ttl=59 time=52.0 ms
20:06:11 64 bytes from 8.8.8.8: icmp_seq=560 ttl=59 time=121 ms
20:06:12 64 bytes from 8.8.8.8: icmp_seq=561 ttl=59 time=92.6 ms
20:06:13 64 bytes from 8.8.8.8: icmp_seq=562 ttl=59 time=165 ms
20:06:14 64 bytes from 8.8.8.8: icmp_seq=563 ttl=59 time=241 ms
20:06:15 64 bytes from 8.8.8.8: icmp_seq=564 ttl=59 time=111 ms
20:06:16 64 bytes from 8.8.8.8: icmp_seq=565 ttl=59 time=231 ms
20:07:11 From 192.168.178.52 icmp_seq=617 Destination Host Unreachable
20:07:11 From 192.168.178.52 icmp_seq=618 Destination Host Unreachable
20:07:11 From 192.168.178.52 icmp_seq=619 Destination Host Unreachable
20:07:14 From 192.168.178.52 icmp_seq=620 Destination Host Unreachable
20:07:14 From 192.168.178.52 icmp_seq=621 Destination Host Unreachable
20:07:17 From 192.168.178.52 icmp_seq=623 Destination Host Unreachable
20:07:20 From 192.168.178.52 icmp_seq=626 Destination Host Unreachable
```
Look at the times. 16 seconds after loading a track in spotifyd, my machine loses its network connection. Reproducibly. For any track that I try to load. There's no error message anywhere. spotifyd shows no error in the log. There is nothing in journalctl for systemd-network or dmesg. I can only restore my connection by physically replugging the ethernet cable, killing spotifyd has no effect on restoring it. Also, I do not only lose my internet connection, but the connection to the whole LAN. I cannot ping my gateway or hosts in the network.

`ip link` and `ip address` show nothing out of the ordinary after losing my connection:
```
$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp12s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:25:22:ad:a9:41 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.52/24 brd 192.168.178.255 scope global dynamic enp12s0
       valid_lft 3440sec preferred_lft 3440sec
    inet6 fe80::225:22ff:fead:a941/64 scope link 
       valid_lft forever preferred_lft forever
```
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp12s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:25:22:ad:a9:41 brd ff:ff:ff:ff:ff:ff
```

Does anyone have any idea what could be the cause of spotifyd killing my ethernet connection?

**Comment by SimonPersson** [comment]
Wow! I really don't know how to debug this. I guess I would start with running spotifyd through `strace` to see if something looks strange there. Wireshark might also show us something. I really have no clue though.

**Comment by NicoHood** [comment]
Which DE are you using and which dhcp/dns software? Network manager? I once had problems with disconnects when i enable dnsmasq caching via NetworkManager. But only in one WLAN environment.

**Comment by SirWindfield** [comment]
This one is super old so I will just close it up. Feel free to open it up again if you still have this problem or something similar.
