### ISSUE TITLE
Crossfade songs

### ISSUE THREAD

**Issue by bertptrs** [Spotifyd/spotifyd#145]
Desktop Spotify has an option to cross fade songs when they end, so the sound continues even when a song ends in a fade-out. Could spotifyd also support that?

**Comment by SimonPersson** [comment]
It's possible to support, but there's a quite a bit of work involved. There's some discussion here: https://github.com/plietar/librespot/issues/18

**Comment by muffin4** [comment]
The linked discussion has been moved to https://github.com/librespot-org/librespot/issues/21 and the feature has been merged on Feb 27 https://github.com/librespot-org/librespot/pull/430.

**Comment by kolaente** [comment]
Just wondering, is there any update to this?

**Comment by robinvd** [comment]
If upstream supports it then we should be able to add it

**Comment by robinvd** [comment]
looking at the pr linked, it only implements gapless playback and not crossfade. A quick search shows this issue https://github.com/librespot-org/librespot/issues/32

**Comment by kolaente** [comment]
Should this issue still be kept open?
