### ISSUE TITLE
Space in device_name cause exit of spotifyd when playing

### ISSUE THREAD

**Issue by yadomi** [Spotifyd/spotifyd#146]
Look like if there is a space in the `device_name` option in the `spotifyd.conf` the dameon will crash or quit without any message/log.

```
[...]
device_name = Some Space
```

Is this a restriction from Spotify Connect or from spotifyd ? 

Anyway, it works like a charm without space 👍

**Comment by SimonPersson** [comment]
This is actually mentioned in the README already. I'm not sure if the issue is inherent to the connect protocol though.

Feel free to make a PR if you can think of a way to make this clearer in the documentation.

**Comment by SimonPersson** [comment]
I clarified this by adding a comment in the default configuration file.

**Comment by NicoHood** [comment]
I have the problem, that the device name change is not recognized at all (via command line). How is it expected to look like? https://github.com/Spotifyd/spotifyd/issues/169
