### ISSUE TITLE
Plain text password

### ISSUE THREAD

**Issue by NicoHood** [Spotifyd/spotifyd#148]
The password is stored in plain text in the config file. Is there any chance to store a hashed version of the password?

I also tried to run without a user/password and it works perfect. This might be only working in the local network. No matter why, you should add this to the readme, which is an extremely nice feature. You write "Every field is optional; Spotifyd can even run without a configuration file.", but I was not aware that this means no authentification is required at all. Even more: two different accounts can stream to the same spotifyd, which is extremely great for us, as everyone can use the kitchen speakers now, no need to login with a single account.

Great software, thanks for sharing!

**Comment by NicoHood** [comment]
Storing a hash rathe then a plain text password is better, because users who do not use random passwords, or similar passwords (which I can imagine for spotify, as you might want to login on someone else PC without havin your keypass next to you). In this case you might be able to login, but you do not see the users password pattern.

Now a linux user who uses the software should be aware of this issue, but a) I still would not want to store the password in plain text and b) the super easy 1 click raspberry pi tutorials will come and not tell you about risks.

So if there is a hash option, go for it. Especially because you also dont want to send the password in plaintext over the network. I cannot imagine this. The desktop app also uses hashed credentials.

About the keyring: You are right, that this is uncomfortable.

**Comment by Mange** [comment]
But hashes are not usable and they are one-way by design so the password cannot be read from a config with a hashes value. What you want in that case is encryption, which means you need a password to unlock your Spotify password.

This is what Keyrings give you, an encrypted password storage that is unlocked when you log in.

What if there was support for Keyrings and plaintext passwords? I would be using this on my main desktop so I would have a Keyring.

**Comment by NicoHood** [comment]
But how does the password exchange work? Doesnt spotifyd hash the password? Does it send it in plain text!?

**Comment by SimonPersson** [comment]
No, the password is sent to Spotify over an encrypted connection.

**Comment by SimonPersson** [comment]
I think @Mange's suggestion of having support for both Keyrings and plaintext passwords would be ideal. It looks like it would be pretty easy to set up with keyring-rs.

**Comment by hwchen** [comment]
Hey, author of keyring-rs here. I'm a happy user of spotifyd :) If there's something I can do to help with integration, let me know.

**Comment by SirWindfield** [comment]
Doesn't Spotify Connect only work if you are already signed in? You only see the devices when using a valid account. So I guess it's actually needed to announce yourself as a potential playback device @RlndVt.

**Comment by RlndVt** [comment]
No it's not needed. I have spotifyd set-up without an account and everyone
on the local network (that has spotify premium) can connect to it.

The second part of my statement is true though. If I had set up
spotifyd/librespot with a valid account I would be able to play music from
that device from anywhere. E.g. the device being at home while I'm at work.

RlndVt

**Comment by SirWindfield** [comment]
@RlndVt Hey again!

I am currently implementing password requesting to prevent the plain text password issue.
The only problem that I have right now is that I can't reproduce your scenario on my machine. My config file looks like this:

```conf
[global]
backend = pulseaudio
mixer = PCM
volume-control = alsa
device_name = tokyo-daemon
bitrate = 320
cache_path = /home/sven/music/spotifyd-offline-cache
volume-normalisation = false
```

But it does not show up on my local network to any client that is logged in using a premium account. 
I get the following log output (tokyo being my hostname):
```
Mar 23 00:15:39 tokyo systemd[1062]: Started A spotify playing daemon.
Mar 23 00:15:39 tokyo spotifyd[1442]: 00:15:39 [INFO] Using software volume controller.
```
