### ISSUE TITLE
spotifyd-pulseaudio and spotifyd conflict when installing

### ISSUE THREAD

**Issue by dcov** [Spotifyd/spotifyd#151]
As the title states I was unable to install it on Arch using the makepkg tool. 
Steps to reproduce:
1. Clone https://aur.archlinux.org/spotifyd.git
2. cd to the clone directory
3. Run makepkg -s
4. Run makepkg -i - THIS FAILS

Error messages:

error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: spotifyd-pulseaudio and spotifyd are in conflict

I was however able to install it by modifying the PKGBUILD file. I had to remove the package_() function of the package I didn't want, as well as the package name from the pkgname variable. This works for both packages (I tested it).

**Comment by NicoHood** [comment]
This is not an issue of this software, this should be reported on the AUR page.

Also this if not an issue in general, as this is a split package, providing an alsa only backend package and one with pulseaudio enabled. All correct.

**Comment by dcov** [comment]
Ah ok I wasn't aware of split packages, I'm still new to arch and everything in general. Thanks for the info!
