### ISSUE TITLE
Doesn't seem to reply to dbus messages

### ISSUE THREAD

**Issue by j605** [Spotifyd/spotifyd#153]
I am opening this separately from #152 as it relates to a possible mistake in implementing `dbus_mpris`. When `spotifyd` starts up it fails to reply to certain messages causing `plasmashell` to not classify it as a media player.

I am linking the kde bug report since a developer help track down the exact problem, https://bugs.kde.org/show_bug.cgi?id=395744#c7

**Comment by SirWindfield** [comment]
@j605 Hey! It took some time to come around this issue. If you are still using spotifyd and plasma, would you mind testing out if PR #346 solves the issue and report back on this issue?

**Comment by taigrr** [comment]
@SirWindfield I was able to test this and it works for me now.
