### ISSUE TITLE
Pipe audio backend

### ISSUE THREAD

**Issue by pirogoeth** [Spotifyd/spotifyd#155]
Is there any interest in implementing a pipe audio backend, similar to what [shairport-sync](https://github.com/mikebrady/shairport-sync/blob/master/audio_pipe.c) has? It might be a useful feature for some people and I'd be more than willing to give the implementation a shot!

**Comment by pirogoeth** [comment]
Never mind, just dug in to librespot and saw that it supports playback to a pipe backend! 
Thanks for the hard work on spotifyd and librespot! ❤️

**Comment by SimonPersson** [comment]
I think the pipe backend is supported for audio. For metadata, you could perhaps use a script with the onevent configuration option?
