### ISSUE TITLE
Volume changes too loud when selecting (spotifyd) device

### ISSUE THREAD

**Issue by Juno72** [Spotifyd/spotifyd#160]
Changed the config volume to:
  volume-normalisation = false
  normalisation-pregain = 1
However selecting the device in spotify causes the deamon volume to go to 50%, and sometimes it is even 100%...

Maybe it is possible to filter the spotify volume commands, so it prevents the volume is set to 100%, or 50% (or any other volume) during a (configurable) time after connecting Spotify, or changing a song.

**Comment by SirWindfield** [comment]
I think as of today, the underlying library does actually cache the last used volume and will re-use it if you specify a cache path in the config file. I'll close this for now.

**Comment by bxabi** [comment]
I have the version v0.2.24, but the daemon is always starting with maximum volume.
