### ISSUE TITLE
Compilation fails for extprim

### ISSUE THREAD

**Issue by tylkie** [Spotifyd/spotifyd#162]
I know it doesn't belong here. It's my first time building with cargo/rust. I wouldn't use it if it wasn't for spotifyd... so I'll bother you directly, sorry... ;-)

Doing "cargo build --release", I always get stuck as follows... searched two hours and couldn't find anything about it. I'm also kind of confused as those "missing" functions actually "are" implemented. Just don't understand why they're out of scope...

`error[E0599]: no function or associated item named `to_u128` found for type `num_traits::ToPrimitive` in the current scope
   --> /home/tylk/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/traits.rs:250:9
    |
250 |         ToPrimitive::to_u128(self).map(u128::from_built_in)
    |         ^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `num_traits::ToPrimitive`
    |
    = note: the method `to_u128` exists but the following trait bounds were not satisfied:
            `num_traits::ToPrimitive : traits::ToExtraPrimitive`
            `&num_traits::ToPrimitive : traits::ToExtraPrimitive`
            `&mut num_traits::ToPrimitive : traits::ToExtraPrimitive`
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `to_u128`, perhaps you need to implement it:
            candidate #1: `traits::ToExtraPrimitive`
    = help: did you mean `to_u16`?

error[E0599]: no function or associated item named `from_built_in` found for type `u128::u128` in the current scope
   --> /home/tylk/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/traits.rs:250:40
    |
250 |         ToPrimitive::to_u128(self).map(u128::from_built_in)
    |                                        ^^^^^^^^^^^^^^^^^^^ function or associated item not found in `u128::u128`
    | 
   ::: /home/tylk/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/u128.rs:46:1
    |
46  | pub struct u128 {
    | --------------- function or associated item `from_built_in` not found for this

error[E0599]: no function or associated item named `to_i128` found for type `num_traits::ToPrimitive` in the current scope
   --> /home/tylk/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/traits.rs:254:9
    |
254 |         ToPrimitive::to_i128(self).map(i128::from_built_in)
    |         ^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `num_traits::ToPrimitive`
    |
    = note: the method `to_i128` exists but the following trait bounds were not satisfied:
            `num_traits::ToPrimitive : traits::ToExtraPrimitive`
            `&num_traits::ToPrimitive : traits::ToExtraPrimitive`
            `&mut num_traits::ToPrimitive : traits::ToExtraPrimitive`
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `to_i128`, perhaps you need to implement it:
            candidate #1: `traits::ToExtraPrimitive`
    = help: did you mean `to_i16`?

error[E0599]: no function or associated item named `from_built_in` found for type `i128::i128` in the current scope
   --> /home/tylk/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/traits.rs:254:40
    |
254 |           ToPrimitive::to_i128(self).map(i128::from_built_in)
    |                                          ^^^^^^^^^^^^^^^^^^^ function or associated item not found in `i128::i128`
    | 
   ::: /home/tylk/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/i128.rs:44:1
    |
44  | / pub struct i128(
45  | |     #[doc(hidden)]
46  | |     pub u128,
47  | | );
    | |__- function or associated item `from_built_in` not found for this

error: aborting due to 4 previous errors

error: Could not compile `extprim`.
warning: build failed, waiting for other jobs to finish...
error: build failed
`
Sorry to bother, but I'd appreciate any hint. Cargo is 0.26 and rustc 1.25.0.

**Comment by tylkie** [comment]
Upgrading rust to 1.27.x solved the problem.

**Comment by tylkie** [comment]
Great work btw... gotta love you for this :-)

**Comment by SimonPersson** [comment]
Sorry I didn't reply before, I've been on vacation. Glad you like it!
