### ISSUE TITLE
Spotify access token instead of plain text credentials

### ISSUE THREAD

**Issue by Thierry-Gls** [Spotifyd/spotifyd#163]
Hi,

I was wondering if there is a possibility to implement use of access token to connect a spotify account to spotifyd, because storing plain text credentials datas can be a really huge security gap.

I've already seen in the issue #148 that it might be difficult to change the way it works, but instead of using a hashed password, is this not possible to use the access token from spotify web api ?

**Comment by SimonPersson** [comment]
The spotify web api does not allow for streaming/playback, so I don't think access tokens from there are useful for our purposes. I think the keychain proposal in #148 is the way forward.

**Comment by HowToMeetLadies** [comment]
No need for personal credentials, tokens or whatever:
https://www.spotify.com/account/set-device-password/

**Comment by NicoHood** [comment]
This link seems to not work for me. What is displayed there?

**Comment by tjorim** [comment]
That generates a device password. However, this is only for Spotify accounts opened with a Facebook account. Still, that are still plain text credentials, to be used when you delete or lose access to your Facebook account.

**Comment by SirWindfield** [comment]
Ok, looks like you have to declare each close separately in a PR. This can be closed now, as keyring support has been added with the latest commit.
