### ISSUE TITLE
Daemon crashes when local (non-accessable/deleted) song is played in playlist

### ISSUE THREAD

**Issue by fronbasal** [Spotifyd/spotifyd#164]
Hey!
I have a playlist which includes a deleted local song which can't be removed from the playlist.
As soon as this song get's selected by spotify the daemon crashes.

**Comment by fronbasal** [comment]
I have attached the log of `journalctl` regarding this issue.

```
Aug 24 13:47:56 raspberrypi spotifyd[9395]: 13:47:56 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: SpotifyIdError
Aug 24 13:47:56 raspberrypi systemd[1]: spotifyd.service: Main process exited, code=exited, status=101/n/a
Aug 24 13:47:56 raspberrypi systemd[1]: spotifyd.service: Unit entered failed state.
Aug 24 13:47:56 raspberrypi systemd[1]: spotifyd.service: Failed with result 'exit-code'.
```

**Comment by SirWindfield** [comment]
Hey!

Can you help me out on this one? So I added a new folder as my local file source in the official Spotify app. I then selected the daemon as my playback device and started to play a playlist where two songs are in. The first one is a Spotify song, the second was the local file. 
Each time I skip the first one, the second one doesn't even start to play. The daemon output says: `12:23:18 [WARN] Skipping track "spotify:local:::SampleAudio_0.7mb:45" at position [1] of 2`. 

I can't even check if spotifyd supports local files. Every one of my local files got skipped on.

**Comment by SimonPersson** [comment]
I think I recall that when I looked into this, the crash did not happen if you skipped to the local file. The crash only occurred if you finished the previous song in the playlist.

**Comment by SirWindfield** [comment]
Thanks! Just a quick question thrown in, can you play local files with spotifyd? Because I can't manage to make it work @SimonPersson.

**Comment by SimonPersson** [comment]
No, I don't think that is supported by librespot, unless it's been added recently.

**Comment by fronbasal** [comment]
I suppose we can close this issue then.
