### ISSUE TITLE
Cannot have multiple spotifyd in network

### ISSUE THREAD

**Issue by NicoHood** [Spotifyd/spotifyd#169]
It looks like The `--device_name` parameter is not functional in version 2.2 (have not tried older versions). It always shows as spotifyd, without my custom name. On top of that I cannot have multiple spotifyd in the network. I'd love to have a spotifyd for each room of my apartment.

I try to run it with:
```
spotifyd --bitrate 320 --device_name "Test_Name" --no-daemon --backend pulseaudio --verbose --volume-normalisation true
```

**Comment by bjo81** [comment]
Does it work with a config file?

**Comment by NicoHood** [comment]
Yes it works! This must be a bug!

**Comment by NicoHood** [comment]
When looking at the help page there are multiple parameters with the param `DEVICE`. Maybe that is the problem, that it all maps to the --device parameter and mixer, bitrate und device_name params are skipped?

```
        --device DEVICE Audio device, given by aplay -L.
        --mixer DEVICE  Audio mixer
        --bitrate DEVICE
                        Any of 96, 160, and 320.
        --pid PID-FILE  Path to PID file.
        --device_name DEVICE
                        Name of this Spotify device.
```

**Comment by ismacasti** [comment]
I have the same problem, --device_name is ignored in v0.2.2

**Comment by NicoHood** [comment]
Fixed in https://github.com/Spotifyd/spotifyd/pull/195

@ismacasti thanks!
