### ISSUE TITLE
Using specifying backend through command line does not work

### ISSUE THREAD

**Issue by bobvanderlinden** [Spotifyd/spotifyd#170]
Whenever I run spotifyd using `--backend pulseaudio` (and without specifying it in a configuration file) it outputs the following:

```
No backend specified, defaulting to: alsa.
```

Whenever I specify the backend in a configuration file it works without problems. Example of configuration file:

```
[global]
backend=pulseaudio
```

**Comment by vace117** [comment]
Verified. I'm having exactly the same problem.

**Comment by SirWindfield** [comment]
How did you compile spotifyd @vace117?

**Comment by vace117** [comment]
> How did you compile spotifyd @vace117? What features did you enable or disable?

`cargo build --release --features "pulseaudio_backend, alsa_backend"`

**Comment by SirWindfield** [comment]
@vace117 this would actually not work as alsa should override every other backend. The above command would still use the alsa backend.

**Comment by vace117** [comment]
@SirWindfield Hmm, I don't think that's true - I'm using the resulting binary with PulseAudio right now. I made a Docker image that allows you to run the binary in either mode, and I've tested it in both modes.

You can examine the binary and the image for yourself, if you are curious: 
[https://github.com/vace117/spotify-connect-server](https://github.com/vace117/spotify-connect-server)
[https://hub.docker.com/r/vace117/spotify-connect-server](https://hub.docker.com/r/vace117/spotify-connect-server)

Note that this Docker image specifies:
```
[global]
backend=pulseaudio
```
in `spotifyd.conf`, which means that the container will use PulseAudio by default. But it can also use ALSA if I specify `--backend alsa` on the command line. I have tested this with both options, and they both work.

**Comment by bobvanderlinden** [comment]
https://github.com/Spotifyd/spotifyd/pull/230 should fix this problem in this PR. It would be great if anyone could give it a try.

**Comment by SirWindfield** [comment]
@vace117 You're right. I was testing multiple backends out by passing --backend to the binary but it looks like it wasn't implemented until now.
