### ISSUE TITLE
D-Bus MPRIS does not work with default device name

### ISSUE THREAD

**Issue by bobvanderlinden** [Spotifyd/spotifyd#171]
By default my device name is `Spotifyd@bob-laptop`. This is fine, but whenever I send a pause command through dbus I get the following error:

```
response: Response { url: "https://api.spotify.com/v1/me/player/pause?device_id=Spotifyd@bob-laptop", status: NotFound, headers: {"Content-Type": "application/json; charset=utf-8", "Cache-Control": "private, max-age=0", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Accept, Authorization, Origin, Content-Type, Retry-After", "Access-Control-Allow-Methods": "GET, POST, OPTIONS, PUT, DELETE, PATCH", "Access-Control-Allow-Credentials": "true", "Access-Control-Max-Age": "604800", "Date": "Sat, 22 Sep 2018 16:57:13 GMT", "Via": "1.1 google", "Alt-Svc": "clear", "Transfer-Encoding": "chunked"} }
content: "{\n  \"error\" : {\n    \"status\" : 404,\n    \"message\" : \"Device not found\"\n  }\n}"
```

As you can see `Spotifyd@bob-laptop` is being used as-is without uri encoding. Whenever I manually set my device_name to `something_else` it works without problems.

**Comment by SirWindfield** [comment]
Thanks for the catch! I didn't know that it had to be URI encoded. Do you have a resource that shows that the name has to be URI encoded? Or is it something that you know from experience?
