### ISSUE TITLE
Insecurity

### ISSUE THREAD

**Issue by CrafterSvK** [Spotifyd/spotifyd#172]
Well, a lot of friends on same network can start spotifyd daemon on my computer without my knowing from another spotify account.

**Comment by salevdns** [comment]
This is also the case with any official Spotify Connect implementation. Also this is not really insecure. No data can be accessed. The worst thing that could happen is that your friend plays a song that you don't like.

**Comment by SimonPersson** [comment]
Exactly, this is just how Spotify Connect works.

**Comment by CrafterSvK** [comment]
They can run application which is not started on my pc. It's not about song. I have a PC on a network with spotifyd not enabled or started and they can run it without problem.

**Comment by SimonPersson** [comment]
That is simply not possible. Either spotifyd is running, or someone would have to hack your computer to start it.
