### ISSUE TITLE
OpenSSL issue

### ISSUE THREAD

**Issue by xR34ct** [Spotifyd/spotifyd#173]
My spotifyd can't compile since it panics at my OpenSSL version, which is OpenSSL 1.1.1. How to solve this?

**Comment by NicoHood** [comment]
I've requested rspotify to tag a new release. I could not find any releases for librespot, how did the download work in first place? via current master?

**Comment by bertptrs** [comment]
Seems like it does, but the current HEAD does not compile, so that's why I tagged a commit.

**Comment by NicoHood** [comment]
But the current master is quite old.  How old is the commit you took? I am a bit confused which version was taken before and why it did(not) build.

**Comment by bertptrs** [comment]
Note: this project has been using a fork of librespot, since the original was abandoned. The commit I took (well, not exactly me, but someone who commented on the AUR package) was made on July 3rd, and directly after was the commit that broke the build.

See the fork: https://github.com/librespot-org/librespot.git. The commit specified by the lock file was made on May 18th.

**Comment by NicoHood** [comment]
Now I understand, thanks. I missed "Aug 17" As 2017, but its 17.8.2018. So your fix sounds good, but we should report the build error upstream. Did you do that yet? they should also provide a proper tag if possible.

**Comment by bertptrs** [comment]
This _is_ upstream in this case I guess, but since this is technically unrelated to OpenSSL it deserves its own issue.

**Comment by NicoHood** [comment]
https://github.com/samrayleung/rspotify/pull/18#issuecomment-427362874

0.2.5 can be used now.

**Comment by SimonPersson** [comment]
I updated the dependencies and pushed a new release. See if that works for you!

**Comment by bertptrs** [comment]
@SimonPersson I can confirm that this works, thank you!

Small nitpick (please don't do a new release for this): you forgot to bump the version in the Cargo.toml to 0.2.3. This is just a cosmetic issue.

**Comment by NicoHood** [comment]
The package compiles for me.

**Comment by AlanWood12** [comment]
I have tips on how to stay up to date on price changes at all times. You can use something like the [best crypto exchange for day trading](https://tradersunion.com/ratings/crypto/common/) where read reviews about different exchanges. I've noticed a useful update to these knowledge that makes it even more convenient to use.

**Comment by ErwinSmith135** [comment]
I have tips on how to stay up to date on price changes at all times. You can use something like the [best crypto exchange for day trading](https://tradersunion.com/ratings/crypto/common/) where read reviews about different exchanges. I've noticed a useful update to these knowledge that makes it even more convenient to use.
