### ISSUE TITLE
[ERROR] Caught panic with message: connection closed

### ISSUE THREAD

**Issue by Trobolit** [Spotifyd/spotifyd#175]
After leaving spotifyd running for a few days this message usually shows up along with a crash.
```
[ERROR] Caught panic with message: connection closed
```

I run it on a Ubuntu 16.04.5 LTS server in a VM in proxmox.

To see these crashes I always run it in with this:
```
./spotifyd/target/release/spotifyd --no-daemon --bitrate 320
```

It would be nice if it didn't crash but just reconnected instead, or had the option to shutdown or reconnect on lost connection.

kind regards
Robert

**Comment by SirWindfield** [comment]
This is actually a missing feature of the underlying library `librespot` that is used here. As far as I could tell they still debate on how to make it happen.

**Comment by NicoHood** [comment]
Could you please link the bugreport of the librespot library, so we can watch the fixing progress?

**Comment by SirWindfield** [comment]
If someone in this issue still encounters disconnects that do not reconnect by itself, please re-open this issue!

**Comment by Joshua-Hwang** [comment]
I believe I'm still getting the issued described. After having spotifyd running for about a minute I get the following message
`Caught panic with message: connection closed`
