### ISSUE TITLE
Build failed on ubuntu 18.04

### ISSUE THREAD

**Issue by pasdVn** [Spotifyd/spotifyd#176]
I tried to build spotifyd from source (current masters HEAD) on ubuntu 18.04, as described in your [wiki](https://github.com/Spotifyd/spotifyd/wiki/Installing-on-Ubuntu-%28from-source%29).

I get the following build error:
```
(...)
   Compiling parking_lot v0.6.4
   Compiling tokio-fs v0.1.3
   Compiling tokio-reactor v0.1.6
error[E0658]: use of unstable library feature 'thread_local_state': state querying was recently added (see issue #27716)
   --> /home/tobias/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/sharded_rwlock.rs:158:18
    |
158 |     REGISTRATION.try_with(|reg| reg.index).unwrap_or(0)
    |                  ^^^^^^^^

error: aborting due to previous error

error: Could not compile `tokio-reactor`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by MarkRijckenberg** [comment]
It seems that the newest version of the cargo compiler compiles the dependencies in a different order, compared to the older cargo compiler. 
Please execute the following Terminal commands to upgrade to the newest version of the cargo and rustc packages:
sudo add-apt-repository ppa:ubuntu-mozilla-security/rust-next
sudo apt-get update
sudo apt-get install rustc cargo

Then please try again.

**Comment by SimonPersson** [comment]
Yes, the error indicates that your version of the rust compiler is too old. I'm not familiar with Ubuntu, so if @MarkRijckenberg's advice does not work I can only suggest the rust website: https://www.rust-lang.org/en-US/.

**Comment by SirWindfield** [comment]
This should actually got "passively" fixed by pinning down the toolchain version from my commit.
