### ISSUE TITLE
Install Spotifyd with Pulse and MPRIS Support

### ISSUE THREAD

**Issue by 8sd** [Spotifyd/spotifyd#177]
I want to install spotifyd on `ArchLinux` with `pulseaudio` and `MPRIS` support.
When executing `cargo build --release --features pulseaudio_backend --features dbus_mpris`  I receive an error.

Is it possible to build it with both features?

**Comment by SimonPersson** [comment]
Try `--features pulseaudio_backend,dbus_mpris`.

**Comment by 8sd** [comment]
I did and it compiled but `playerctl pause` fails with `Connection to player failed: No players found` :|

**Comment by SirWindfield** [comment]
If you use a custom backend, make sure to also pass down `--no-default-features` as their is actually a race condition currently in the code that might end up with the `alsa_backend` anyway.

No, dbus_mpris is currently buggy. I am in the works of fixing some problems though.
