### ISSUE TITLE
Not specified account kills spotifyd

### ISSUE THREAD

**Issue by ploth** [Spotifyd/spotifyd#181]
Using the prebuild arm6 binaries for the raspberry-pi.
I have specified my credentials in the configuration. The Spotify Connect Device is visible on all devices. But if I want to play music from a Spotify app that belongs to another premium account, then spotifyd crashes. If I play music from a device on which my account is set up, this is no problem. No error log at all.

EDIT: It does not even work if I not specify any account in the spotifyd configuration file.

**Comment by cg505** [comment]
I am experiencing the same issue on a raspberry pi 3 running Arch Linux ARM. I compiled manually using [spotifyd from AUR](https://aur.archlinux.org/packages/spotifyd/).

**Comment by ploth** [comment]
For me it's Arch Linux ARM on Raspberry Pi B.

On November 20, 2018 12:01:13 AM UTC, Christopher Cooper <notifications@github.com> wrote:
>I am experiencing the same issue on a raspberry pi 3 running Arch Linux
>ARM. I compiled manually using [spotifyd from
>AUR](https://aur.archlinux.org/packages/spotifyd/).

-- 
Sent from mobile device. Please excuse my brevity.

**Comment by cg505** [comment]
Actually, my guess is that discovery is broken for Facebook accounts in librespot. If I do not specify credentials in the config file, I can delete credentials.json and still connect just fine.

**Comment by Jalle19** [comment]
Same thing here

**Comment by Jalle19** [comment]
Tried this on x86-64 and the issue is the same, the software just quits with no error or stack trace.

**Comment by totalizator** [comment]
I have no credentials specified in the config file and spotifyd dies a lot when I'm using two different premium accounts interchangeably.

**Comment by hillbicks** [comment]
I'm facing the exact same issue. Anything we can do to help debug the problem? I think I have to switch to chromecast implementation on the pi for the time being.

**Comment by SirWindfield** [comment]
This is a limitation of `librespot` IIRC. Once you are logged in, you can only use that one account to connect to the connection point. I will test this out with their client though. If that's the case there too, I'll close the issue.
