### ISSUE TITLE
Audiocard is not shown on pulseaudio controls.

### ISSUE THREAD

**Issue by dovydasgulbinas** [Spotifyd/spotifyd#182]
## Setup

* `debian 9` host w/ `xfce4` desktop environment
* docker container running `spotifyd` on host

## Issue

After installing and running this program `spotifyd` music streaming works.  The issue that I face is that when `spotifyd` is running, `pulseaudio` on my desktop environment does not see my audio card.  Even though that card is plugged in & playing Spotify no problem.

## Hypothesis 

Maybe some of you know how should I be able to use `spotifyd` with my desktop env?
I have a hunch that it is due to the fact that audio stream from the card is being streamed to the root user thus I can't access the card with any other user. 

I'm new to pulseaudio & alsa stack so could anyone please help me out and guide me on what may cause this issue?

**Comment by ronnsn** [comment]
(typically) you have only one audio-output-hardware,
and if you havn't configured a software mixer in your alsa config (ie /etc/asound.conf) only user/app can have access the hardware at a time.

here is a good example for using the alsa dmix plugin as software mixer named "dmixer".

https://wiki.ubuntuusers.de/.asoundrc/#Stereo

"dmixer"  is then the prefereable device for spotifyd and other audio apps. (spotifyd.conf  device=dmixer)
