### ISSUE TITLE
PermissionDenied message after start

### ISSUE THREAD

**Issue by toomyem** [Spotifyd/spotifyd#184]
When I try to start spotifyd, I'm getting Permission Denied error. It used to work several days ago, but recently I noticed that I can't connect to my daemon and then I found the following in my log. I have spotify premium.

```
12:22:37 [INFO] Using software volume controller.
12:22:37 [WARN] Failed to register IPv6 receiver: Os { code: 97, kind: Other, message: "Address family not supported by protocol" }
12:22:37 [INFO] Connecting to AP "gew1-accesspoint-b-k99h.ap.spotify.com:80"
12:22:38 [INFO] Authenticated as "toomyem" !
12:22:38 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
```

**Comment by bertptrs** [comment]
I've had this happen when the user running the daemon is not part of the `audio` group, thus not allowed to touch the sound card. Can you verify this?

**Comment by realG** [comment]
I was seeing the same (my user account is in the `audio` group) but then I noticed I hadn't set the `cache_path` in the spotifyd.conf. I created a dir in /var/tmp and set that in the conf and next time I fired up the spotifyd process (with `systemctl --user start spotifyd.service` ) it came good, so I assume the permissions errors I was seeing were related to that... would be useful to have the error message a bit more verbose about what exactly it can't do.

**Comment by toomyem** [comment]
I can confirm that my user is in audio group, and it has write access to directory pointed by cache_dir in config. But still only running as root allows me to start spotifyd successfully.

**Comment by tomodachi** [comment]
I noticed two things

1.  If you ran spotifyd with the  same cache path as another user,  the files created by will not be 
readable / writeable so make sure they have the proper permission as well 

2. If one run spotify as a daemon , spotifyd still expects a home path
or you get this:
```Failed to create secure directory (/home/spotifyd/.config/pulse): No such file or directory```

It still works but you might want to give the user a home folder.

**Comment by SirWindfield** [comment]
The problem probably occurs because you first run `spotifyd` as root and it created the cache directory under those permissions, as @tomodachi mentioned. You can't access them as a normal user and therefore the daemon fails. Just delete the directory and run it as a normal user again.
I'll close it as resolved. If you are sure it's unrelated to `spotifyd`, feel free to re-open.
