### ISSUE TITLE
allow setting pid option on config file

### ISSUE THREAD

**Issue by zanona** [Spotifyd/spotifyd#190]
Firstly, thanks for the great work on this application.
 
Secondly, it seems that at the moment, the `--pid` option can only be passed through command line but not as an option under the config file?

#### ~/.config/spotifyd/spotifyd.conf
```
[global]
pid = /var/run/spotifyd.pid
```

When invoking `spotifyd` it seems the pid option is not used?
I only managed to get it working by calling `spotifyd --pid /var/run/spotifyd.pid`.

Perhaps there's a better way to make sure the pid file is always in the same location?

**Comment by zanona** [comment]
Thanks for your reply rnnsn.
My use case would be to using it with `i3-status` where there's an option to monitor a specific path to a PID file to check whether a process is running or stopped and display the info in the i3 status bar. :)

**Comment by Mange** [comment]
Maybe a script like this could solve that problem?

```bash
#!/use/bin/env bash
echo "$$" > /path/to/spotifyd.pid
exec spotifyd
```

I typed this up on my phone so I haven't tested it, but I think it would work. The script outputs its own PID to a file, and then replaces itself with spotifyd which means spotifyd keeps the PID.

**Comment by zanona** [comment]
Thanks so much @Mange I will give that a shot ;)

**Comment by SimonPersson** [comment]
@zanona - I pushed a new release, setting the pid option in the config file should work now. Thanks for the report!
