### ISSUE TITLE
spotifyd consistently crashes on specific songs

### ISSUE THREAD

**Issue by zkrx** [Spotifyd/spotifyd#192]
Hi,

Spotifyd works great for a while (hours) and then suddenly crashes.
It looks like some specific songs make it crash each and every time.

**Setup**
Arch Linux ARM on Raspberry Pi 3b (armv7h) with Pulseaudio (spotifyd-pulseaudio package from the AUR: https://aur.archlinux.org/packages/spotifyd-pulseaudio/ )

**Logs**
Here are the logs of the same bug twice, the 2nd paste being with the -v parameter (sorry for the control characters ...)
https://pastebin.com/raw/ME7gZLZA
https://pastebin.com/X00ahRtj

**Config**
https://pastebin.com/raw/1AskQCf7

**Example song that makes it crash**
Astral Tales - Ivory Gardens
https://open.spotify.com/track/76SOCUGCiF3tgkm9FwEPSG

Can someone reproduce? I can provide more details if you need.

Cheers!

**Comment by erikj** [comment]
Encountering same error on Raspbian w/ Sweetest Tempest - Mine

https://open.spotify.com/track/6O3jpB8l8AYJ5ah49eexId

**Comment by hajdbo** [comment]
confirmed on my ubuntu desktop with pulseaudio backend

**Comment by SirWindfield** [comment]
Hey, do you guys still experience crashes with the exact songs you linked here? It would be great if you could check it again to make sure it was not some `librespot` problem or upstream problem from Spotify's part.

**Comment by erikj** [comment]
I did not encounter an error today when I played the track that I cited above. Thanks.

**Comment by SirWindfield** [comment]
I'll close this one then. Feel free to open up the issue again if you encounter the error.
