### ISSUE TITLE
Snap App doesn't play audio

### ISSUE THREAD

**Issue by kat953162** [Spotifyd/spotifyd#197]
It appears that it is an audio package issue or something, but when attempting to use the Snap Package on Ubuntu 18.10, no audio comes from the speakers. The ability to "cast" using the spotify protocol from other Spotify apps work fine, but no actual music plays. I've attempted messing with config files with no success.

Am I doing something wrong, or is the snap app a placeholder?

**Comment by SimonPersson** [comment]
I think the snap app should work. Any ideas, @popey?

**Comment by Dubatan** [comment]
Same issue here on Ubuntu 18.10, too. Looks like a problem only on this Distribution :/

**Comment by popey** [comment]
Sorry, I missed the notification. I'll take a look.

**Comment by SirWindfield** [comment]
Any feedback on this? Does it work on Ubuntu now? Does it work on other distros?

**Comment by SirWindfield** [comment]
Looks like it is Ubuntu specific. I will close it in favour of #237.
