### ISSUE TITLE
usage of pipe backend

### ISSUE THREAD

**Issue by deisi** [Spotifyd/spotifyd#198]
I don't quite understand howto use the pipe backed. I want to be able to pipe the output into `/tmp/fifo` how can I do this? ~~And this there a way to not run spotifyd in the background but in the foreground?~~

I found the --no-daemon

**Comment by deisi** [comment]
I currently made it work by using alsa and a config like https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#alsa however I would be glad if I could remove alsa from the equation, since it is rather oversized in comparison to what I want it to do.

**Comment by SimonPersson** [comment]
Hi! I'm not actively using the pipe backend, and I'm not sure how well it works. However, this seems to play back music for me:
```
$ mkfifo /tmp/fifo
$ spotifyd --no-daemon --backend pipe > /tmp/fifo
```
And in a different terminal:
```
aplay -c 2 -r 48000 -f S16_BE /tmp/fifo
```

**Comment by deisi** [comment]
ah okay, thx. I will test it. thanks a lot.

**Comment by dflvunoooooo** [comment]
Can I specify the pipe file in the config file? I want to start spotifyd with systemd and pipe the audio to /tmp/snapfifo-Spotify, which I created before.

**Comment by deisi** [comment]
Don't know but you can for sure change the `spotifyd.service` file and and append the above to the `ExecStart` line.

**Comment by TacoDog311** [comment]
Should this still work?  I get this error when I try:

```
> spotifyd --no-daemon --backend pipe 
error: 'pipe' isn't a valid value for '--backend <string>'
        [possible values: alsa]


USAGE:
    spotifyd --backend <string> --no-daemon

For more information try --help

```
