### ISSUE TITLE
Add ability to move songs in queue

### ISSUE THREAD

**Issue by carnager** [Spotifyd/spotifyd#20]
I am trying to write a soundrop clone using this. For this to be somewhat worthy its needed to be able to move songs up in the queue. 

Can this be added?

**Comment by SimonPersson** [comment]
Cool!

Sure, that should be possible. What do you reckon would be the cleanest interface? A `swap n p` where n and p are track numbers in the queue?

**Comment by carnager** [comment]
something like "sc move n" i guess. 
also maybe an option to add a song after the currently one playing

**Comment by SimonPersson** [comment]
Yes, but at which position would song n end up? The way I see it, you either need two parameters, like my `swap` command. Or, you have two commands `move up` and `move down` and call those repetitively in order to make a song go to the right place.

**Comment by carnager** [comment]
both solutions sound fine to me. about the 2nd request. i will make an extra ticket. sorry for spamming :)

**Comment by SimonPersson** [comment]
No worries! It's nice that I get it all collected here.
