### ISSUE TITLE
initial volume 65535 with pipe backend

### ISSUE THREAD

**Issue by mfauvain** [Spotifyd/spotifyd#200]
Hi, couldn't find an open issue on this so : when using pipe backend, default initial volume is set (in cache directory/volume) to 65535 and there is no option in spotifyd.conf to set it to a different value. Tried many different way around this but to no avail. Librespot has the --initial-volume option. Would it be possible to add this to the list of available options in spotifyd?
thx

**Comment by SirWindfield** [comment]
I'm using pulseaudio as my backend and it uses the volume I set on my system every time.

**Comment by mfauvain** [comment]
Hi, in the end compiled librespot with pulseaudio support and using this now. volume can be set with `--intial-volume=XX` and works

**Comment by SirWindfield** [comment]
Mind closing the issue then? :smile:

**Comment by mfauvain** [comment]
not at all. thank you

**Comment by sflip** [comment]
I implemented `initial_volume` as a config option [here](#623).
