### ISSUE TITLE
build failed - attribute is experimental

### ISSUE THREAD

**Issue by seniorgod** [Spotifyd/spotifyd#201]
Dear all,

i try to build spotifyd on my Sparky SBC und DietPi (a minimal debian)

i get following error:

   Compiling try-lock v0.1.0
error: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `crossbeam-utils`.
warning: build failed, waiting for other jobs to finish...

**Comment by seniorgod** [comment]
versions:
rustc 1.24.1
cargo 0.25.0

**Comment by goug71** [comment]
Hi,

I ran into the same issue, but needed pulseaudio, so could not use same fix.

I removed stretch-packaged rust, then tried to get a fresher packaged rust toolchain from backports, but it does not seem to be backported.

I finally decided to go for rustup, then with this version
```
# rustc  -vV
rustc 1.28.0 (9634041f0 2018-07-30)
binary: rustc
commit-hash: 9634041f0e8c0f3191d2867311276f19d0a42564
commit-date: 2018-07-30
host: x86_64-unknown-linux-gnu
release: 1.28.0
LLVM version: 6.0

```
I run into another building issue : 
```
error[E0494]: cannot refer to the interior of another static, use a constant instead
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_rs-0.8.14/src/lib.rs:928:42    
    |                     
928 |     variant: VariantEncoding::SingleByte(&data::SINGLE_BYTE_DATA.ibm866, 0x0440, 96, 16),
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<...>
               error: aborting due to 28 previous errors                                           
                                                                                                   
For more information about this error, try `rustc --explain E0494`.
error: Could not compile `encoding_rs`.                                                             
warning: build failed, waiting for other jobs to finish...                        

```
A bit more digging brought me to https://github.com/rust-lang/cargo/issues/6556, and eventually to https://github.com/rust-lang/cargo/issues/5654

But then it's way out of my league (rust newbie over here). Any clue how to work this around?
Thanks
