### ISSUE TITLE
How does spotifyd stream music

### ISSUE THREAD

**Issue by hackedWifi** [Spotifyd/spotifyd#202]
It is not clear to me how does the spotifyd work to stream music. I know it can be used as connect to another device. But can this daemon stream music like the app on the background and be control via CLI.
thanks in advance.

**Comment by Avi-D-coder** [comment]
Configure your username and password. Run `spotifyd` open your Spotify app of choice click the icon that looks like a monitor and a speaker. Pick Spotifyd from the list of devices.

You can use an playerctl to control playback from the command line.

**Comment by hackedWifi** [comment]
So if that is the case what is the purpose of this daemon. If I am gonna have open the Spotify app. I can simply use playerctl without this daemon. I can use web connect through the wifi connection too.
I thought this daemon will let me stream music without using the Spotify app and save some resources

**Comment by SimonPersson** [comment]
One use case is that your computer cannot run Spotify, for example a raspberry pi or a desktop running BSD. Personally I have it running on a raspberry pi plugged in to my stereo system.

If you just want to save resources, you can build a command line client interface to Spotify's web APIs (https://developer.spotify.com/documentation/web-api/reference-beta/) which you can use to control the daemon.

**Comment by Avi-D-coder** [comment]
If your like me you don't like running an instance of chrome/electron just for the web player. Less memory, cpu and battery usage is a win.
