### ISSUE TITLE
AddrNotAvailable error once per minute or so

### ISSUE THREAD

**Issue by aksel** [Spotifyd/spotifyd#203]
[Here's a snippet of the log](https://pastebin.com/raw/tZ9FGenQ)

It's being sent about once per minute.

Music is still playing just fine. No noticeable issues.

Any idea what could be causing this? I notice the error message is also mentioned in #143. My network is not behind a proxy, as far as I'm aware.

**Comment by SirWindfield** [comment]
If it has no impact I would just close this issue. No idea what is going on but it doesn't effect the playback ....
