### ISSUE TITLE
Can't change playlist

### ISSUE THREAD

**Issue by stevenveenma** [Spotifyd/spotifyd#205]
Today I discovered an issue using spotifyd daemon: I can't play music that is not in the current playlist. So it's not possible to switch to another playlist or to play music that was searched.  This happens when I control the daemon both with an android or windows version of Spotify app. This behaviour only occurs with the spotifyd daemon not when I use the remote functionality to control 'no-linux' devices. I installed the latest version of spotifyd daemon with the same result. Has Spotify changed something that affects spotifyd?

There is a workaround for this by going back to the device, play music there, change the playlist and then go back to spotifyd again, but this is very annoying.

**Comment by aksel** [comment]
I believe this is related to this issue: librespot-org/librespot#288

**Comment by christopher-dG** [comment]
There's now a fix for that issue in librespot, which is working for me. Could we get the `Cargo.lock` rebuilt to bump the commit?

**Comment by woftor** [comment]
I have tested the new Cargo.lock.
It works! issue seems to be gone.

**Comment by armin1975** [comment]
Hi!

When can a new spotifyd release live 2.4.1 can be expected which resolves that issue?

Thx and best regards,
Armin

**Comment by SimonPersson** [comment]
I merged the PR for @aksel and tagged a new release.

**Comment by armin1975** [comment]
Thank you so much, works on my RestekMAMS+ just verified!

 

Great work!!!!

 

THX again from Vienna

 

Gesendet: Montag, 25. Februar 2019 um 21:19 Uhr
Von: "Simon Persson" <notifications@github.com>
An: Spotifyd/spotifyd <spotifyd@noreply.github.com>
Cc: armin1975 <amoesslacher@gmx.at>, Comment <comment@noreply.github.com>
Betreff: Re: [Spotifyd/spotifyd] Can't change playlist (#205)


I merged the PR for @aksel and tagged a new release.

**Comment by stevenveenma** [comment]
I tested this and it worked fine for me too. Thank you so much! I really appreciate that, although there is a small usergroup, this tool is updated.
