### ISSUE TITLE
'--version'?

### ISSUE THREAD

**Issue by erikj** [Spotifyd/spotifyd#208]
Is there a way to ascertain the version of a `spotifyd` binary (besides consulting sizes or checksums from the releases page?) If not, a `--version` flag seems like it would be handy for this.

(Also, it looks like the configured Cargo package version isn't up to date w/ the version number of the release? E.g. release 0.2.4: https://github.com/Spotifyd/spotifyd/blob/2abc39285d95481d5ae359a5d641c08663cd4f02/Cargo.toml#L3 )

Thanks for developing, sharing, maintaining and supporting `spotifyd`. I use `spotifyd` every day and am exceptionally happy w/ its utility and performance.

**Comment by SirWindfield** [comment]
I can tackle this down on monday :smile:
