### ISSUE TITLE
Ability to remove played songs from Queue.

### ISSUE THREAD

**Issue by carnager** [Spotifyd/spotifyd#21]
Since spotifyd always repeats the playlist, can there be an option to remove songs, once they finished playing and/or got skipped?

**Comment by SimonPersson** [comment]
I wonder if it would be more intuitive to have a `repeat` on and off switch.

I suppose that if you're writing a client to communicate with spotifyd, it would be nice if spotifyd informed the client on events such as skipping a song. I always planned to implement this but I'm writing my thesis right no so there is only so much time. What are you doing now, polling with some interval?

**Comment by carnager** [comment]
my "client" is a dmenu script, so some kind of idle event is more or less impossible in that case, still it would be very useful.

A repeat on/off switch definately could be nice. still i think a consuming play mode would be nice, like mpd provides it. But yeah, this is quite a specific use-case :)

**Comment by SimonPersson** [comment]
Ah, I see. Some where talking about creating ncurses interfaces, web interfaces and the likes, it would make more sense there.

I'll look into both a consuming mode and repeating then!

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
