### ISSUE TITLE
playerctl next and previous don't affect spotifyd with dbus_mpris

### ISSUE THREAD

**Issue by Poccket** [Spotifyd/spotifyd#211]
Whenever I use `playerctl previous` or `playerctl next`, playerctl exists successfully, and spotifyd only says "Couldn't fetch metadata from spotify: Ok(None)" and then nothing else happens. 

When allowing song to progress to the next naturally, it works, and skipping from my phone works. The pause/play functions work, but the position one doesn't either.

**Comment by SirWindfield** [comment]
There generally seems to be a delay compared to the OG client from Spotify. Around 300ms maybe.
Btw, prev and next don't work either for me.

**Comment by superzei** [comment]
Currently having same problem. Initially play/pause didn't worked as well until I changed "device_name" to something else in conf.


`May 01 18:54:51 b-manjaro spotifyd[2254]: 18:54:51 [WARN] Unhandled dbus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameA>  
`

`
May 01 18:54:51 b-manjaro spotifyd[2254]: 18:54:51 [INFO] Couldn't fetch metadata from spotify: Ok(None)`

**Comment by nikplx** [comment]
Same Issue here. Play / Pause / Metadata / Stop work as expected, but all the other playerctl functions fail without any error message.

**Comment by aksel** [comment]
Some commands work, some don't.

Next and previous seem to send a message. There's a short delay before exiting. But nothing happens. The spotifyd log doesn't seem to output anything.

shuffle, loop, volume and position report current values, but changes don't have any effect.

Can someone point me in the right direction for debugging this?

**Comment by SirWindfield** [comment]
@aksel Probably something like https://wiki.ubuntu.com/DebuggingDBus would work.

**Comment by aksel** [comment]
That does indeed work for me!

**Comment by SirWindfield** [comment]
I thought so... I will take a closer look at it next week :smile:

**Comment by treeshateorcs** [comment]
> There generally seems to be a delay compared to the OG client from Spotify. Around 300ms maybe.
> Btw, prev and next don't work either for

what's the reason for the delay? it may be up to a few seconds on my machine. i think it may be considered a bug as well

**Comment by SirWindfield** [comment]
I think that it might has to do with the main loop that runs the application. I didn't take a look into the code but it's quite often the case that event loops don't run on full power. They generally poll after a certain amount of time. Maybe something like this is happening here...

It might also be something within dbus_mpris itself, the crate that we use to provide this feature.

**Comment by treeshateorcs** [comment]
I did a quick grep on "sleep" and "time" and I didn't seem to find anything wrong

**Comment by SirWindfield** [comment]
Ye, you 're right, I probably just had super bad internet connection :)
Still, the issue with previous and next remains though...

**Comment by treeshateorcs** [comment]
I've noticed the delay is this bad only when using playerctl. with a dbus command there's no delay

**Comment by treeshateorcs** [comment]
apparently it is playerctl that is faulty. this tool https://github.com/mariusor/mpris-ctl works perfectly
