### ISSUE TITLE
Raspbian 

### ISSUE THREAD

**Issue by bhalee** [Spotifyd/spotifyd#212]
I installed spotifyd to my raspberry and its working nice but i had lots of issue when i tried install playerctl. So how i can controll spotifyd without playerctl? Any alternative for playerctl?

**Comment by SimonPersson** [comment]
If you build spotifyd with DBUS MPRIS support, it should work with compatible software. I haven't really tested any, but googling around I saw this one: https://github.com/primejyothi/Dbus-MPRIS-MusicPlayer-Controller.

You can also control spotifyd using the official client on your phone, or the web client https://open.spotify.com.
