### ISSUE TITLE
Unable to change song once playback has started

### ISSUE THREAD

**Issue by patrickjane** [Spotifyd/spotifyd#214]
I can connect to `spotifyd` with my phone and start playback, however once it runs, I cannot pick any other songs. If trying, the current song just restarts. I have to disconnect the phone, change the song, and connect it again.

When trying to pick a different song, the syslog also shows the current song is retried:
```
Mar 11 18:57:15 pi3HA spotifyd[670]: 18:57:15 [INFO] Loading track "Monsters" with Spotify URI "spotify:track:5wDeE5s3Vq6F3hfzq8XCCx"
Mar 11 18:57:16 pi3HA spotifyd[670]: 18:57:16 [INFO] Track "Monsters" loaded
Mar 11 18:57:22 pi3HA spotifyd[670]: 18:57:22 [INFO] Loading track "Monsters" with Spotify URI "spotify:track:5wDeE5s3Vq6F3hfzq8XCCx"
Mar 11 18:57:23 pi3HA spotifyd[670]: 18:57:23 [INFO] Track "Monsters" loaded
```

**Comment by bjo81** [comment]
Same issue here, and not only with the phone, also with the Linux client.

**Comment by wvangeit** [comment]
I have the same issue (from iphone)

**Comment by wackazong** [comment]
Update to the latest release which includes a new librespot version. That fixes it.

**Comment by woftor** [comment]
See: https://github.com/Spotifyd/spotifyd/issues/205
This was fixed in latest release as @wackazong already pointed out.
