### ISSUE TITLE
Firing dunst notifications

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#216]
Would it be possible to integrate dunst notifications like the OG client does?
If you guys can show me how to do it (like which libraries you prefer, how the API should be designed and if you want to have flags to disable it (or feature), I can give it a go next week :smile:).

**Comment by SimonPersson** [comment]
I would try to implement that using the onevent option in the configuration file. That is, let an external tool send the notifications, and let spotifyd be focused on playing the music. Unix principle and all that :)

**Comment by SirWindfield** [comment]
Thanks for replying that fast! That was my first thought too. But I couldn't find a way to use spotifyd to retrieve the currently playing song and its information like title, artist and album art.

**Comment by SimonPersson** [comment]
That data is not directly available, but you do have the Spotify track ID available as `TRACK_ID` environment variable. You could use that to fetch more data from Spotifys public api. I would also be happy to accept a PR to add more metadata in the event environment.

**Comment by SirWindfield** [comment]
Thanks! I'll try to come up with something more elegant. Took a look into the [player_event_handler.rs](https://github.com/Spotifyd/spotifyd/blob/dd2c203df01afff5577583155d448e6bf17578ae/src/player_event_handler.rs#L15) file where you actually set the `TRACK_ID` environment variable but it seems that there isn't really a way to get more data through the passed event struct.

And by taking a quick look it looks like the networking code for `rspotify` is basically hid behind the `mpris_dbus` feature flag. 

My idea would be to create a new feature called `metadata-fetching` or something similar that offers all code needed for actually fechting the metadata from spotify. And `mpris_dbus` would just enable that feature if it gets enabled too. Some new environment variables could then be set without interfearing with the logic of `mpris_dbus`.

What are your opinions? It's quite a big undergoing and I do not want to sink in some work without first discussing if this is even in your interest or if you have other plans.

**Comment by SimonPersson** [comment]
I think rspotify doesn't even have to be behind a feature flag, it doesn't pull in any big dependencies, does it?

Your plan sounds good, feel free to go for it!

**Comment by SirWindfield** [comment]
It shouldnt. I mean, if people really want a flag it can be done afterwards too.

I'll give it a go next week then^^

**Comment by albuic** [comment]
Hey all,
I just used the TRACK_ID and Spotify APIs to show a notification on music change with dunst.
You need to add the line ```onevent = "bash /home/YOU_USER/bin/spotifyNotifications.sh"``` in your spotifyd.conf and following content in the corresponding file.

```
user_id=YOUR_USER_ID # generated on https://developer.spotify.com/dashboard/applications
secret_id=YOUR_SECRET_ID
myToken=$(curl -s -X 'POST' -u $user_id:$secret_id -d grant_type=client_credentials https://accounts.spotify.com/api/token | jq '.access_token' | cut -d\" -f2)
RESULT=$?
if [ $RESULT -eq 0 ]; then
    curl -s -X 'GET' https://api.spotify.com/v1/tracks/$TRACK_ID -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization:\"Bearer $myToken\"" | jq '.name, .artists[].name, .album.name, .album.release_date, .track_number, .album.total_tracks' | xargs printf "\"Playing '%s' from '%s' (album: '%s' in %s (%s/%s))\"" | xargs notify-send --urgency=low --expire-time=3000 --app-name=spotifyd spotifyd
else
    echo "Cannot get token"
fi
```

I will add the use of PLAYER_EVENT when I got the time.

**Comment by SimonPersson** [comment]
@albuic - cool! Maybe we should create a page on the wiki for little user supplied scripts like this? Your script is a good starting point for a last.fm scrobbler, and other cool things like that!

**Comment by albuic** [comment]
Updated script:

```
user_id=YOUR_USER_ID # generated on https://developer.spotify.com/dashboard/applications
secret_id=YOUR_SECRET_ID

myToken=$(curl -s -X 'POST' -u $user_id:$secret_id -d grant_type=client_credentials https://accounts.spotify.com/api/token | jq '.access_token' | cut -d\" -f2)
RESULT=$?

if [ "$PLAYER_EVENT" = "start" ];
then
    if [ $RESULT -eq 0 ]; then
        curl -s -X 'GET' https://api.spotify.com/v1/tracks/$TRACK_ID -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization:\"Bearer $myToken\"" | jq '.name, .artists[].name, .album.name, .album.release_date, .track_number, .album.total_tracks' | xargs printf "\"Playing '%s' from '%s' (album: '%s' in %s (%s/%s))\"" | xargs notify-send --urgency=low --expire-time=3000 --app-name=spotifyd spotifyd
    else
        echo "Cannot get token."
    fi
elif [ "$PLAYER_EVENT" = "change" ];
then
    if [ $RESULT -eq 0 ]; then
        curl -s -X 'GET' https://api.spotify.com/v1/tracks/$TRACK_ID -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization:\"Bearer $myToken\"" | jq '.name, .artists[].name, .album.name, .album.release_date, .track_number, .album.total_tracks' | xargs printf "\"Music changed to '%s' from '%s' (album: '%s' in %s (%s/%s))\"" | xargs notify-send --urgency=low --expire-time=3000 --app-name=spotifyd spotifyd
    else
        echo "Cannot get token."
    fi
elif [ "$PLAYER_EVENT" = "stop" ];
then
    if [ $RESULT -eq 0 ]; then
        curl -s -X 'GET' https://api.spotify.com/v1/tracks/$TRACK_ID -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization:\"Bearer $myToken\"" | jq '.name, .artists[].name, .album.name, .album.release_date, .track_number, .album.total_tracks' | xargs printf "Stoping music (Last song: '%s' from '%s' (album: '%s' in %s (%s/%s)))\"" | xargs notify-send --urgency=low --expire-time=3000 --app-name=spotifyd spotifyd
    else
        echo "Cannot get token."
    fi
else
    echo "Unkown event."
fi
```
Don't forget to also add the line ```onevent = "bash /home/YOU_USER/bin/spotifyNotifications.sh"``` to your ```spotifyd.conf``` file.

**Comment by Marc3lX** [comment]
When I pause the music I'm getting this error:
```
mpc spotifyd[31033]: xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
mpc spotifyd[31033]: Invalid number of options.
```

**Comment by unmanagedtn** [comment]
I have fallowed this in the wiki and here and it does not seem to do anything and I cant redirect the script output at all acts like its not doing anything on track change...

**Comment by unmanagedtn** [comment]
This script is producing out of sync track names... it quit a few song behind what's actually playing ... any idea why?

**Comment by joaoeudes7** [comment]
@albuic The value of PLAYER_EVENT is always null here, where do I set it automatically?

**Comment by jrgiacone** [comment]
I get null as well anyone get this working?
