### ISSUE TITLE
make QPRINT an option rather than a toggle

### ISSUE THREAD

**Issue by carnager** [Spotifyd/spotifyd#22]
it would be nice if one could properly set the QPRINT option from scripts, without guessing what the current QPRINT state is.

something like "sc qprint {first,current}"

**Comment by SimonPersson** [comment]
That seams reasonable.

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
