### ISSUE TITLE
Daemon panics when queue is empty and XFAudioPlayNext gets pressed

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#224]
While trying to find the cause for #164 I came across some weird bug. After randomly clicking on the local song in one of my playlists rapidly, the `Spotifyd` queue gets rid of that song and will create a queue of length 0. Pressing skip now does actually crash the client with a panic. The cause is an access operation at index 0 with an array length of 0.

**Comment by SimonPersson** [comment]
I guess this is a bug in librespot, and we should look into fixing it there. However, given that librespot can be a bit unstable, we should discuss how we handle it in spotifyd. Should we catch the panic within spotifyd? Should we just rely on systemd/runit to restart spotifyd if it crashes?

**Comment by SirWindfield** [comment]
The easiest and fastest would be to just use `Restart: on-failure` and let systemd handle it. But since it is an actual bug it would be the best to fix it upstream. 

I have no reliable way to reproduce it though. It worked only twice now and it is really random (at least I can't find any pattern).

**Comment by slondr** [comment]
Is this still a problem? Has the upstream bug in librespot been resolved?
