### ISSUE TITLE
Cannot change volume in web player

### ISSUE THREAD

**Issue by Hoeze** [Spotifyd/spotifyd#229]
Hi, I built spotifyd with pulseaudio_backend and ran spotify with the following command:
```bash
> spotifyd --no-daemon --backend="pulseaudio"
19:13:29 [INFO] Using software volume controller.
19:13:29 [INFO] Connecting to AP ...
```
However, changing the volume in the web player does not affect the spotifyd volume at all.

**Comment by SirWindfield** [comment]
Is this still the case?

**Comment by Hoeze** [comment]
@SirWindfield No, it works for now.
Thanks for asking!
