### ISSUE TITLE
Unify config file key names

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#233]
As of now, some config file key names have different styles, e.g. underscore vs. hyphen.

**Comment by SimonPersson** [comment]
There have also been quite a few bugs where one option was available as a command line argument, but not a config file option, or vice versa.

I think we should rework configuration in general. My current thinking is that we should have a definition of the options, their descriptions, and their types, written in a declarative style. The implementations of command line and config file parsing could then be based on the same definitions, making mismatches impossible.

**Comment by SirWindfield** [comment]
This is actually possible using clap and clap_derive. You define a struct holding your options and clap does the parsing for your Cli. The struct also derives from serde and we could use the ini backend for that one then.

**Comment by SimonPersson** [comment]
Cool! Clap_derive does not seem to be published to crates.io yet, but otherwise seems like a good solution.
