### ISSUE TITLE
[ERROR] Alsa error PCM open -2

### ISSUE THREAD

**Issue by b0nete** [Spotifyd/spotifyd#234]
Hi, I'm having problems with spotifyd in docker.

I found and choice this alternative why try run spotify in my server without desktop environment, only CLI.

spotifyd its running perfectly but not have sound. Looking the container logs i get the follow errors:

> ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
21:07:09 [ERROR] Alsa error PCM open -2
21:07:09 [ERROR] Could not start audio: Alsa error: PCM open failed
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave

I tryied set other default card in many files without success. Anyone know can where going the problem?

My aplay list.

> **** List of PLAYBACK Hardware Devices ****
Home directory not accessible: Permission denied
card 0: Generic [HD-Audio Generic], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: SB [HDA ATI SB], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: SB [HDA ATI SB], device 1: ALC892 Digital [ALC892 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

The device that i'm using is ALC892 Analog (card1)

My asound.conf

> pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw           
    card 1
}

My aplay -L

> Home directory not accessible: Permission denied
Home directory not accessible: Permission denied
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
hdmi:CARD=Generic,DEV=0
    HD-Audio Generic, HDMI 0
    HDMI Audio Output
dmix:CARD=Generic,DEV=3
    HD-Audio Generic, HDMI 0
    Direct sample mixing device
dsnoop:CARD=Generic,DEV=3
    HD-Audio Generic, HDMI 0
    Direct sample snooping device
hw:CARD=Generic,DEV=3
    HD-Audio Generic, HDMI 0
    Direct hardware device without any conversions
plughw:CARD=Generic,DEV=3
    HD-Audio Generic, HDMI 0
    Hardware device with all software conversions
sysdefault:CARD=SB
    HDA ATI SB, ALC892 Analog
    Default Audio Device
front:CARD=SB
    HDA ATI SB, ALC892 Analog
    Default Audio Device
surround21:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Digital
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    Direct sample mixing device
dmix:CARD=SB,DEV=1
    HDA ATI SB, ALC892 Digital
    Direct sample mixing device
dsnoop:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    Direct sample snooping device
dsnoop:CARD=SB,DEV=1
    HDA ATI SB, ALC892 Digital
    Direct sample snooping device
hw:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    Direct hardware device without any conversions
hw:CARD=SB,DEV=1
    HDA ATI SB, ALC892 Digital
    Direct hardware device without any conversions
plughw:CARD=SB,DEV=0
    HDA ATI SB, ALC892 Analog
    Hardware device with all software conversions
plughw:CARD=SB,DEV=1
    HDA ATI SB, ALC892 Digital
    Hardware device with all software conversions

I hope help from you. Thanks! Sorry for my bad english.

**Comment by b0nete** [comment]
Add this following..

For discard problems points i have build spotifyd.. I downloaded this repository and build packet with cargo build --release, i create manually the spotifyd.conf file in /etc/xdg/spotifyd/ and execute but problem persist.

I leave my configuration file.

> [global]
username = USER
password = PASS
backend = alsa
device = default # alsa_audio_device # Given by `aplay -L`
mixer = PCM
volume-control = alsa # or alsa_linear, or softvol
#onevent = command_run_on_playback_event
device_name = docker
bitrate = 96 # |160|320
cache_path = /tmp # cache_directory
volume-normalisation = true
normalisation-pregain = -3

Thanks!

**Comment by SirWindfield** [comment]
Not sure if that is the reason but my PC lists an explicit PCM device too.

**Comment by SirWindfield** [comment]
Could you solve the problem?

**Comment by SirWindfield** [comment]
@b0nete I wasn't sure and checked again. It looks like docker container's can play audio. You need to map the audio device into the container though. 

I found [this](https://stackoverflow.com/questions/41083436/how-to-play-sound-in-a-docker-container) stackoverflow question which is quite similar. It's probably not a Spotifyd issue so I will close this one.

Would be nice if you could update and tell us if it worked out for you to map it.
