### ISSUE TITLE
Snap install broken on Ubuntu

### ISSUE THREAD

**Issue by saenglert** [Spotifyd/spotifyd#237]
Hello everyone,
I'm trying to install via snap and spotifyd won't load after install. Looking into the snap directory there's only empty folders:
```
~/snap/spotifyd/
    6/ - empty
    common/ - empty
    current/ - symlink to 6/
```

**Comment by SirWindfield** [comment]
Are you running Ubuntu by any chance?

**Comment by saenglert** [comment]
I am indeed

**Comment by SirWindfield** [comment]
This seems to be a common problem on Ubuntu specifically. I'll try to take a closer look at it in a VM. Which version are you running specifically?

**Comment by saenglert** [comment]
Ubuntu 18.04.3 LTS

**Comment by SirWindfield** [comment]
I cannot boot Ubuntu based VMs on my PC at home. No idea why this is happening. I have to first figure out what problems Virtualbox has before tackling this one down 😄 :

**Comment by slondr** [comment]
Reference #296
