### ISSUE TITLE
Wrong snap permissions for config file

### ISSUE THREAD

**Issue by tonimelisma** [Spotifyd/spotifyd#238]
The ubuntu snap package starts automatically and according to strace, searches for the config file in the usual non-snap locations:

execve("/snap/spotifyd/6/bin/spotifyd", ["/snap/spotifyd/6/bin/spotifyd", "--no-daemon"], 0x7ffc8bbb6588 /* 54 vars */) = 0                                                                      
stat("/home/user/.config/spotifyd/spotifyd.conf", 0x7fffb38f76b0) = -1 ENOENT (No such file or directory)                                                                                        
stat("/etc/xdg/spotifyd/spotifyd.conf", 0x7fffb38f76b0) = -1 ENOENT (No such file or directory)
stat("/etc/spotifyd.conf", 0x7fffb38f77e0) = -1 ENOENT (No such file or directory)

However, snap packages don't have rights to read stuff in user home dirs or /etc:

2019-04-11T21:44:34Z Spotifyd[741]: Detached from shell, now running in background.
2019-04-11T21:44:34Z Spotifyd[741]: Couldn't read configuration file, continuing with default configuration: 0:0 Unable to open `"/etc/spotifyd.conf"`: Permission denied (os error 13)
2019-04-11T21:44:34Z Spotifyd[741]: Using software volume controller.

As snap starts the daemon automatically, there's no option of changing the command line parameters to tell it to read another config file.

Can you make the snap read it's config file from the user's home directory's snap directory, as snaps are supposed to do?

**Comment by villahousut** [comment]
Is this documented somewhere for the snap? I can't find a readme or the like
