### ISSUE TITLE
Unable to build without alsa backend

### ISSUE THREAD

**Issue by edaubert** [Spotifyd/spotifyd#239]
I try to build spotifyd without the alsa backend as a try.

I use the following command:
`cargo build --release --no-default-features --features pulseaudio_backend`

```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
  --> src/setup.rs:53:30
   |
53 |         Box::new(|| Box::new(mixer::softmixer::SoftMixer::open()) as Box<Mixer>)
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error: aborting due to previous error
```

Does it mean that alsa is mandatory ?

Even with this issue, I really like the work you've done on this project.
Keep going !!

**Comment by SimonPersson** [comment]
Sorry about that, it's supposed to work with only pulseaudio. I've pushed a fix.
