### ISSUE TITLE
Ubuntu 18.10 snap neither alsa nor pulseaudio work

### ISSUE THREAD

**Issue by ghost** [Spotifyd/spotifyd#242]
Using alsa backend it can't find the mixer file (even though for all devices I tried, I can play via aplay)

Apr 23 21:53:26 Spotifyd[30961]: Using alsa volume controller.
Apr 23 21:53:26 systemd[1]: Started Service for snap application spotifyd.spotifyd.
Apr 23 21:53:26 Spotifyd[30961]: Couldn't read volume from alsa device with name "dmix".
Apr 23 21:53:26 Spotifyd[30961]: Couldn't read volume from alsa device with name "dmix".
Apr 23 21:53:26 Spotifyd[30961]: Couldn't set volume: Error("snd_mixer_attach", Sys(ENOENT))

I've tried all devices I can see with aplay -l or -L

If I try to use softvol, it starts OK but never plays properly:
Apr 23 22:08:17 Spotifyd[17950]: Using software volume controller.
Apr 23 22:08:18 purkki Spotifyd[17950]: Using alsa sink
Apr 23 22:08:33 purkki Spotifyd[17950]: Loading track "You've Got The Love" with Spotify URI 
Apr 23 22:08:34 purkki Spotifyd[17950]: Track "You've Got The Love" loaded
Apr 23 22:08:34 purkki Spotifyd[17950]: Alsa error PCM open -2
etc ad infinitum

pulseaudio backend just gives:

Spotifyd[29587]: Could not start audio: Connection refused

**Comment by nbrownus** [comment]
Same story on 19.04

**Comment by SirWindfield** [comment]
I will install a VM and try it out myself.

**Comment by villahousut** [comment]
Still a bug for me on latest Ubuntu:

Sep  5 23:45:54 Spotifyd[9272]: Loading track "This Must Be Love - 2015 Remastered" with Spotify URI "spotify:track:3X3mc51tFREQ1jmgsgYaXm"
Sep  5 23:45:55 Spotifyd[9272]: Track "This Must Be Love - 2015 Remastered" loaded
Sep  5 23:46:08 Spotifyd[9272]: Could not start audio: Connection refused
Sep  5 23:46:08 kernel: [  398.239834] audit: type=1400 audit(1567716368.012:39): apparmor="DENIED" operation="mkdir" profile="snap.spotifyd.spotifyd" name="/run/user/0/" pid=9318 comm="spotifyd" requested_mask="c" denied_mask="c" fsuid=0 ouid=0

**Comment by villahousut** [comment]
> The audio problem might still be a separate issue though. Can you verify that spotifyd actually tries to connect to the right audio source?

As you can see from the bug report you linked as a copy, I tried several audio systems and several audio sources as well.

It might be an issue with access rights.

**Comment by SirWindfield** [comment]
I think I've read somewhere that Ubuntu does not need users to be in the audio group, they have a special user called `pulse`. That should be the only one listed in `/etc/group`. You can check it with something like `grep audio /etc/group`.

I am mainly using ArchLinux so I would have to try and error too though.

**Comment by villahousut** [comment]
I'm talking about ACLs and possible chroots or other restrictions related to snaps. Please see the logs in my previous bug entry.

**Comment by villahousut** [comment]
I'm not talking about user groups. I'm talking about the kernel apparmor audit statement you can see above.

**Comment by SirWindfield** [comment]
Ups, missed that one :D

**Comment by kwodzicki** [comment]
Any updates on this? Having the same issue on CentOS 8. I can use `aplay -D sysdefault` to play sounds when SSHd into the machine, but when running the daemon under systemd, I get the same error as above.

**Comment by SirWindfield** [comment]
No, not really. The there is PR to update the snap file but I can't actually publish it due to missing rights :)
