### ISSUE TITLE
[ERROR] "Address already in use"

### ISSUE THREAD

**Issue by Ema82** [Spotifyd/spotifyd#247]
Hello,
I'm trying to install Spotifyd on a Raspberry Pi 3 Model B with RuneAudio (http://www.runeaudio.com/). 
I followed all the instructions of the related Wiki page but if I check Spotifyd status after starting it, this is what I get: 

```
[root@runeaudio ~]# /usr/bin/spotifyd --no-daemon
22:41:13 [INFO] Using software volume controller.
22:41:13 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
```
Could anyone help me figure out what the problem might be?

Thanks in advance
Ema

**Comment by Ema82** [comment]
Solved killing all the active processess. After restarting the Raspberry, spotifyd works correctly.

**Comment by Ema82** [comment]
I had to reinstall Runeaudio and Spotifyd and I had the problem above again. This time using killall -u root to kill all the active processess doesn't solve the problem. 
Any help?

Thanks

**Comment by elju** [comment]
There is a process listening on that specific port. You can investigate with `ss -tulpn`. Maybe there is still the executable running from RAM. Is the problem still there after a reboot?

**Comment by Ema82** [comment]
Thanks for your answer elju. 
Reboot doesn't solve the problem. 

This is what I have with `ss -tulpn`:

`[root@runeaudio ~]# ss -tulpn
Netid State      Recv-Q Send-Q                                         Local Address:Port                                                        Peer Address:Port

tcp   LISTEN     0      128                                                127.0.0.1:6379                                                                   *:*                   users:(("redis-server",pid=30774,fd=4))
tcp   LISTEN     0      50                                                         *:139                                                                    *:*                   users:(("smbd",pid=360,fd=32))
tcp   LISTEN     0      128                                                        *:5355                                                                   *:*                   users:(("systemd-resolve",pid=259,fd=13))
tcp   LISTEN     0      128                                                        *:80                                                                     *:*                   users:(("nginx",pid=286,fd=6),("nginx",pid=285,fd=6))
tcp   LISTEN     0      128                                                        *:81                                                                     *:*                   users:(("nginx",pid=286,fd=7),("nginx",pid=285,fd=7))
tcp   LISTEN     0      128                                                        *:82                                                                     *:*                   users:(("nginx",pid=286,fd=8),("nginx",pid=285,fd=8))
tcp   LISTEN     0      128                                                        *:22                                                                     *:*                   users:(("sshd",pid=262,fd=3))
tcp   LISTEN     0      50                                                         *:445                                                                    *:*                   users:(("smbd",pid=360,fd=31))
tcp   LISTEN     0      5                                                          *:6600                                                                   *:*                   users:(("mpd",pid=30853,fd=10))
`
I have no idea of which is the service that occupies the door that spotifyd trying to reach nor what I can do if there is actually an overlap

**Comment by SirWindfield** [comment]
It is probably the 5355 one as the port range for the discovery service is is somewhere between 5000-5400 most of the time. It can get higher though. 

You can try to run `netstat -ltnp | grep -w ':5355'` to check what program listens on that port. Additionally, `lsof -I :5355` tells you what service listens to the port.

`netstat` is part of `net-tools` on ubuntu/deb. `lsof` is a package by itself. They are available for almost any Linux distro in some way or another.

**Comment by SirWindfield** [comment]
I am closing the issue for now. Feel free to re-open it if you need more help.

**Comment by xaltsc** [comment]
I can't reopen this issue, however, I'm having the same problem, I tried to investigate ports with netstat, but the only program listening is sshd on another port.

I'm launching `spotifyd` with `./spotifyd --no-daemon --verbose -b pulseaudio -p pwd -u login -d device`.
