### ISSUE TITLE
Need help on setup aur:spotifyd-full and aur:sp

### ISSUE THREAD

**Issue by loeschzwerg** [Spotifyd/spotifyd#248]
# Setup
Manjaro
`pamac build spotifyd-full`
`pamac build sp`

I've made the config as given in the README
```
[global]
username = <myuser>
use-keyring = true
backend = pulseaudio
device = pulse # as received with aplay -L
volume-control = alsa
device_name = some_name
bitrate = 320
cache_path = /var/tmp/spotify/
volume_normalisation = true
normalisatIon_pregain = -10
#onevent = "bash ~/.config/spotifyd/notification_script.sh"
```
the keyring was set up with the given command:
`secret-tool store --label=spotifyd application rust-keyring service spotifyd username <myuser>`
I entered the password for spotify and then entered a global password.

# Run
When running the `spotifyd -v --no-daemon` I receive one error: 
`[ERROR] caught panic with message: pulseaudio sink does not support specifying a device name` plus, when I connect via the Spotify app to the daemon, the daemon exits with error code 101, with
`[ERROR] Player thread panicked`
after
`[ERROR] Caught panick with message: called 'Result::unwrap()' on an 'Err' value: "SendError(..)"`
Which kind of makes sense, given the Pulseaudio error. However, this may be related to #247 #126

# sp
Otherwise, while runnning, when I try to `sp search monster` (which should play the best match on the query) or do any other command with sp, I receive:
`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files.`
In the sp script i changed
`SPOTIFY_PID="$(pid of -s spotifyd || pidof -s spotify || pidof -s .spotify-wrapped)"`

# Systemctl
Last, the `systemctl -a` doesn't hold a spotifyd.service, when I start it with 
`systemctl --user start spotifyd.service` or
`systemctl --user start spotifyd`
I also couldn't `locate spotifyd`. Which would be necessary, if I have to add it to `.config/systemd/users`. `which spotifyd` actually gives me `/usr/bin/spotifyd`

Thank you in advance!

**Comment by jackun** [comment]
* delete `device_name` line
* `systemctl -a --user`

**Comment by SimonPersson** [comment]
I looked in to this `sp` script. It looks like it's not working anymore, because spotify started requiring authorization for the search API. Maybe there is a more up to date script that does this?

I don't use neither pulseaudio nor systemd myself, I can't help you much with those issues I'm afraid.

**Comment by loeschzwerg** [comment]
So it would probably be a good idea to remove sp from the Readme, because otherwise I wouldn't have tried that one.
Thank you Simon. I will try to use it otherwise then.

**Comment by lssimoes** [comment]
Hi, I think a workaround to this problem might be to change `org.mpris.MediaPlayer2.spotify` to `org.mpris.MediaPlayer2.spotifyd` in the `sp` script

However, I then get another error:
```Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply.```

I am running on Arch Linux with the systemd service (with `--no-daemon` flag)

**Comment by lssimoes** [comment]
Ops, found out what was missing. Just connecting through my phone hehe

So, it does work with the sp script. My setup: `Spotify app on cellphone -> spotifyd receive the transmission -> sp to command things`
