### ISSUE TITLE
arm binaries

### ISSUE THREAD

**Issue by Mitschmaster** [Spotifyd/spotifyd#249]
The binaries provided for arm are a bit old. As it takes forever to compile them on my raspberry id like to ask if they could be updated.

**Comment by SimonPersson** [comment]
I just tried to make a new release, which automatically builds the ARM binaries. It seems like the script that cross compiled the ARM binaries on travis-ci has stopped working for some reason. I bet it's not too hard to get something working again, but unfortunately I don't own any ARM hardware anymore, so I wont be able to fix it.

If anyone wants to work on this, I would be more than happy to accept a PR for automatic ARM builds!

**Comment by Mitschmaster** [comment]
So i'll make my first contribution to github with trying to supply a .travis.yml that builds both releases.

**Comment by Mitschmaster** [comment]
i think i got my .travis.yml almost done.
@SimonPersson maybe you would like to have a look at it?
it builds both platforms x86 and arm but lacks the deploy part.

**Comment by SimonPersson** [comment]
Sure, please share it. We can give it a try, not big deal if it fails as the current travis setup is broken anyway. Thanks for working on this!

**Comment by Mitschmaster** [comment]
hi.
i have a fork of spotifyd in my repositories. how do i share that to the
public? i think it should already be visible.

Am Di., 4. Juni 2019 um 18:14 Uhr schrieb Simon Persson <
notifications@github.com>:

**Comment by SimonPersson** [comment]
I see. You can create a pull request then. When you load your fork on GitHub, there should be an option to create a pull request.

**Comment by SimonPersson** [comment]
ARM builds are up to date again.
