### ISSUE TITLE
support for last.fm scrobbling

### ISSUE THREAD

**Issue by carnager** [Spotifyd/spotifyd#25]
Well title says it all. For the nerds of us who love their stats, last.fm would be a mandatory feature :)

**Comment by SimonPersson** [comment]
This would, in my opinion, be better as an external application. I imagine
that spotifyd would emit a signal on changes and some program would listen
to that and send the songs to last.fm.

**Comment by SimonPersson** [comment]
This now seems feasible to implement, using the [librespot](https://github.com/plietar/librespot) library to listen for what song that is currently playing.

**Comment by SimonPersson** [comment]
With [Spotify's API](https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/) and the `onstart`/`onstop` handlers this should now be simple to implement. I have no plans to integate it in `Spotifyd` though, so I'll close this issue.
