### ISSUE TITLE
version identifier needs update

### ISSUE THREAD

**Issue by erikj** [Spotifyd/spotifyd#253]
Version `0.2.9` is available under releases. Downloading version `0.2.9` of the arm executable and running w/ `--version` reports `0.2.8`

```
./spotifyd --version
spotifyd version 0.2.8
```

Likely affects all architectures, because `Cargo.tml` has `version` set to `0.2.8`

https://github.com/Spotifyd/spotifyd/blob/master/Cargo.toml#L5

**Comment by woftor** [comment]
Confirmed (ARMV6, on a Raspberry 3b+).

**Comment by SimonPersson** [comment]
Fixed now.
