### ISSUE TITLE
Crash on playerctl command

### ISSUE THREAD

**Issue by swalladge** [Spotifyd/spotifyd#258]
When running a command from `playerctl` (over dbus), spotifyd crashes with 

```
[ERROR] 11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" }), "https://api.spotify.com/v1/me/player")
```

This is git master at the time of writing with all features enabled.

More debug log for context:
```
...
11:47:05 [DEBUG] tokio_core::reactor: loop poll - 1.597µs
11:47:05 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2643, tv_nsec: 516027470 }
11:47:05 [DEBUG] tokio_core::reactor: loop process, 8.665µs
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [DEBUG] dbus_tokio::adriver: D-Bus i/o poll ready: 29 is Ready(Readable)
11:47:07 [DEBUG] dbus_tokio::adriver: D-Bus i/o unix ready: 29 is Readable | Aio
11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
11:47:07 [DEBUG] dbus_tokio::adriver: handle_msgs: (MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll"))
11:47:07 [DEBUG] tokio_core::reactor: loop poll - 1.603341812s
11:47:07 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2645, tv_nsec: 119382030 }
11:47:07 [DEBUG] tokio_core::reactor: loop process, 9.295µs
11:47:07 [DEBUG] dbus_tokio::adriver: Polling message stream
11:47:07 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll")))))
11:47:07 [TRACE] mio::poll: [<unknown>:787] registering with poller
11:47:07 11:47:07 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(4194303)
[ERROR] 11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" }), "https://api.spotify.com/v1/me/player")
11:47:07 [TRACE] reqwest::client: [<unknown>:578] response receiver is canceled
11:47:07 [TRACE] tokio_reactor: [<unknown>:390] loop process - 0 events, 0.000s
11:47:07 [DEBUG] librespot_connect::spirc: drop Spirc[0]
11:47:07 [DEBUG] librespot_playback::player: Shutting down player thread ...
11:47:07 [DEBUG] librespot_playback::player: drop Player[0]
11:47:07 [DEBUG] librespot_core::session: drop Session[0]
11:47:07 [DEBUG] librespot::component: drop AudioKeyManager
11:47:07 [DEBUG] librespot::component: drop ChannelManager
11:47:07 [DEBUG] librespot::component: drop MercuryManager
11:47:07 [DEBUG] dbus_tokio::adriver: Dropping AMessageStream
11:47:07 [DEBUG] dbus_tokio::adriver: AMessageStream telling ADriver to quit
11:47:07 [TRACE] tokio_threadpool::pool: [<unknown>:138] shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
11:47:07 [TRACE] tokio_threadpool::pool: [<unknown>:186]   -> transitioned to shutdown
11:47:07 [TRACE] tokio_threadpool::pool: [<unknown>:207]   -> shutting down workers
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 0
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 3
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 1
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 2
11:47:07 [DEBUG] librespot_core::session: drop Dispatch
11:47:07 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 5
11:47:07 [DEBUG] tokio_reactor: dropping I/O source: 4
```

**Comment by ritualz** [comment]
gets the same error: 

`15:58:36 [DEBUG] dbus_tokio::adriver: D-Bus i/o poll ready: 23 is Ready(Readable)
15:58:36 [DEBUG] dbus_tokio::adriver: D-Bus i/o unix ready: 23 is Readable | Aio
15:58:36 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(25165828)
15:58:36 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
15:58:36 [DEBUG] dbus_tokio::adriver: handle_msgs: (MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll"))
15:58:36 [DEBUG] dbus_tokio::adriver: handle_msgs: (MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll"))
15:58:36 [DEBUG] tokio_core::reactor: loop poll - 12.325823ms
15:58:36 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 3372, tv_nsec: 849950738 }
15:58:36 [DEBUG] tokio_core::reactor: loop process, 9.885µs
15:58:36 [DEBUG] dbus_tokio::adriver: D-Bus i/o poll ready: 23 is Ready(Readable)
15:58:36 [DEBUG] dbus_tokio::adriver: D-Bus i/o unix ready: 23 is Readable | Aio
15:58:36 [DEBUG] tokio_reactor::registration: scheduling Read for: 4
15:58:36 [DEBUG] tokio_core::reactor: loop poll - 18.502µs
15:58:36 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 3372, tv_nsec: 849985057 }
15:58:36 [DEBUG] tokio_core::reactor: loop process, 7.767µs
^C15:58:38 [TRACE] tokio_reactor: [<unknown>:376] event Readable | Writable Token(12582915)
15:58:38 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
15:58:38 [DEBUG] tokio_reactor::registration: scheduling Read for: 3
15:58:38 [DEBUG] tokio_core::reactor: loop poll - 1.43861386s
15:58:38 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 3374, tv_nsec: 288610511 }
15:58:38 [DEBUG] tokio_core::reactor: loop process, 24.154µs
15:58:38 [DEBUG] dbus_tokio::adriver: Polling message stream
15:58:38 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired")))))
15:58:38 [WARN] Unhandled dbus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
15:58:38 [DEBUG] dbus_tokio::adriver: Polling message stream
15:58:38 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired")))))
15:58:38 [WARN] Unhandled dbus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
15:58:38 [DEBUG] dbus_tokio::adriver: Polling message stream
15:58:38 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("Get")))))
15:58:38 [DEBUG] dbus_tokio::adriver: Polling message stream
15:58:38 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll")))))
15:58:38 [DEBUG] dbus_tokio::adriver: Polling message stream
15:58:38 [DEBUG] dbus_tokio::adriver: msgstream found Ok(Ready(Some((MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Properties"), Some("GetAll")))))
15:58:38 [TRACE] mio::poll: [<unknown>:787] registering with poller
15:58:38 [ERROR] Caught panic with message: 15:58:38 [TRACE] tokio_reactor: [<unknown>:376] event Readable Token(4194303)
called `Result::unwrap()` on an `Err` value: Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" }), "https://api.spotify.com/v1/me/player")
15:58:38 [TRACE] tokio_reactor: [<unknown>:390] loop process - 1 events, 0.000s
15:58:38 [DEBUG] librespot_connect::spirc: drop Spirc[0]
15:58:38 [DEBUG] librespot_playback::player: Shutting down player thread ...
15:58:38 [TRACE] reqwest::client: [<unknown>:578] response receiver is canceled
15:58:38 [DEBUG] librespot_playback::player: drop Player[0]
15:58:38 [TRACE] tokio_reactor: [<unknown>:390] loop process - 0 events, 0.000s
15:58:38 [DEBUG] librespot_core::session: drop Session[0]
15:58:38 [DEBUG] librespot::component: drop MercuryManager
15:58:38 [DEBUG] dbus_tokio::adriver: Dropping AMessageStream
15:58:38 [DEBUG] dbus_tokio::adriver: AMessageStream telling ADriver to quit
15:58:38 [TRACE] tokio_threadpool::pool: [<unknown>:138] shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
15:58:38 [TRACE] tokio_threadpool::pool: [<unknown>:186]   -> transitioned to shutdown
15:58:38 [TRACE] tokio_threadpool::pool: [<unknown>:207]   -> shutting down workers
15:58:38 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
15:58:38 [DEBUG] tokio_reactor: dropping I/O source: 0
15:58:38 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
15:58:38 [DEBUG] tokio_reactor: dropping I/O source: 1
15:58:38 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
15:58:38 [DEBUG] tokio_reactor: dropping I/O source: 2
15:58:38 [DEBUG] librespot_core::session: drop Dispatch
15:58:38 [TRACE] mio::poll: [<unknown>:907] deregistering handle with poller
15:58:38 [DEBUG] tokio_reactor: dropping I/O source: 5
15:58:38 [DEBUG] tokio_reactor: dropping I/O source: 4
15:58:38 [DEBUG] tokio_reactor: dropping I/O source: 3
`

**Comment by taigrr** [comment]
Bump. This started happening for me now after the latest version.

**Comment by taigrr** [comment]
This still happens whenever I upgrade to latest. I have to fall back to the above version for things to work properly.

**Comment by SirWindfield** [comment]
@taigrr Does this happen with any command you send or only some specifics? Super hard to tackle this one down to be honest :(

**Comment by taigrr** [comment]
@SirWindfield Give me a moment, I'll update this comment with some log files. Currently switching back to latest from 0.2.10...

**Comment by taigrr** [comment]
@SirWindfield It seems it crashes without calling playerctl at all now. So it's hard to test and see what it was, as a new bug must have been introduced in the meantime. Before, `playerctl metadata` was crashing it, but now it crashes without running `playerctl`.

**Comment by taigrr** [comment]
My config file, in case it's relevant (doubtful):
```|
1 [global]
2 username = ####
3 password = ####
4 device_name = ####
5 volume-normalisation = true
6 normalisation-pregain = 5
```
Version: `spotifyd 0.2.17`

**Comment by taigrr** [comment]
It looks like https://github.com/seanmonstar/reqwest/issues/541 may be related.

**Comment by SirWindfield** [comment]
It’s probably the underlying library that we use to access the web api, rspotify. Taking a look at the reqwest version changes, the version got bumped right before releasing v0.2.11 ([here](https://github.com/Spotifyd/spotifyd/blame/af819bea7d7e987a4f9b959e98c95072c8e66212/Cargo.lock#L2010)). This might be the problem :thinking:

**Comment by taigrr** [comment]
Nice. I'll test it out now...

**Comment by taigrr** [comment]
Awesome! Can confirm it doesn't crash on start, and playerctl metadata works as it used to.
