### ISSUE TITLE
Wrong architecture from v0.2.9 up

### ISSUE THREAD

**Issue by nicokaiser** [Spotifyd/spotifyd#259]
Release 0.2.5 is the last that runs on the Raspberry Pi 1.
Release 0.2.8 has no binaries.
Release 0.2.9 and up only produce "Segmentation fault" or "Illegal instruction".

I assume something happened to the build pipeline, so the "armv6" binaries are no armv6 binaries anymore. I did not test them on armv7 yet, but will do soon.

Any chances that there will be armv6 binaries for Raspberry Pi 1 / Zero etc.? (If not, it might be a good idea to rename the build artifacts to prevent misunderstandings)

**Comment by nicokaiser** [comment]
Confirmed: the binary works on Raspberry Pi 3, so it is most probably armv7 instead of armv6.

**Comment by SirWindfield** [comment]
Hi all! I can take an hour or two to figure it out completely.
I just noticed though that Github is introducing [Github Actions](https://github.com/features/actions), a pipeline that can be used to run Ci tasks too.
If I get it working without much of a hassle, I'll push a change upstream. But if it takes more time to fix I would propose to wait until we can get access to Github Actions. 

I signed up for the beta already. Not sure how it works with organizations though. @SimonPersson do you have any idea? Did you sign up for it too?`What do you think of my idea to move to Github Acitons?

**Comment by nicokaiser** [comment]
Isn't this was `.travis.yml` does? The "ARM Build" section in this file is supposed to build an ARMv6 build, but I'm not sure if `TARGET=arm-unknown-linux-gnueabihf` really outputs an ARMv6 binary (I have no idea about Rust to be honest).

Maybe the previous builds were ARMv6 compatible by coincidence (they were built for armhf, which is the Debian/Ubuntu platform for ARMv7+VFP3) and just did not use v7-specific commands?

**Comment by SirWindfield** [comment]
The target is certainly the right one. I did some research and it looks like it depends on the toolchain used to cross compile. Ubuntu's `armhf` doesn't only implement hard-floating specific instruction sets for ARMv7, it adds some instructions outside of the `hf` scope too, which makes it incompatible with ARMv6 chips that supported the `hf` instruction set. I remember seeing a toolset that allowed to compile for ARMv6 specifically...

**Comment by opsydev** [comment]
Hey,

Is there any update on this?

**Comment by rprofijt** [comment]
Hi, it seems that after v0.2.19 there are no arm builds anymore, is that related?

**Comment by nicokaiser** [comment]
Yes, working on this.

**Comment by rprofijt** [comment]
oh sorry, just seeing #479 right now :) thanks for the effort!

**Comment by SirWindfield** [comment]
Release incoming.
