### ISSUE TITLE
Unexplained config option

### ISSUE THREAD

**Issue by bphermansson** [Spotifyd/spotifyd#260]
Hi!

What does "cache_path = cache_directory" in the config-file mean? I have a large directory on my machine, "/cache_directory", is that spotifyd:s cache dir?

**Comment by SirWindfield** [comment]
It's the cache used to store spotify songs. They get cached for a certain valid amount of time and get re-used if you re-listen to the same song again.

**Comment by bphermansson** [comment]
Ok, so I can put it somewhere else? Like setting "cache_path = /mount/disk/spotifyCache"?

**Comment by SirWindfield** [comment]
Yes, I put it onto my hard drive instead of my SSD. Probably not the smartest idea as a cache should be fast... :)

**Comment by bphermansson** [comment]
Ok, good!
