### ISSUE TITLE
password command in configuration

### ISSUE THREAD

**Issue by muradm** [Spotifyd/spotifyd#262]
Currently `spotifyd` supports passing username / password credentials in 3 ways:
* configuration file (plain text username and password, problems obvious plain text password stored on disk)
* command line arguments (plain text username and password, problems obvious plain text password is shown in process list)
* gnome-keyring service

People not running gnome, may not want to use gnome-keyring service. There are alternative password managers like [`pass`](https://password-store.org). Raw `GnuPG` also a way.

For such cases it would be useful to have configuration were provided password is a command. For instance for [`pass`](https://password-store.org) it could be like:

```
[global]
password_cmd = pass show social/spotify/user-name
```

When `spotifyd` is starting, it will invoke the command to acquire standard output of that command and use it as a password. It will be responsibility of command to read password from storage, make any necessary user prompts like master password or alike. If command is failed with non zero exit code, `spotifyd` daemon will fail with appropriate log message.

**Comment by SirWindfield** [comment]
Spotifyd doesn't explicitly support gnome keyring only. I just use it (even though my DE is i3).

It supports every password manager that implements the Linux Secret Services API, a Dbus API that clients can register themselves to, making them discoverable. It's basically an abstraction layer for various password managers.
As far as I know, `pass` was just a bash script, so it probably won't support the API.

I am currently re-writing most of spotifyd to get rid of some bugs and bring in consistency for the configuration (alongside of introducing new exiting `features`). 

I can take a look at it. Im not sure if it will happen soon though as I would put it as a low priority feature.

**Comment by muradm** [comment]
Great, then `password_cmd` could be a good candidate for this. It will reduce binary dependency with `use_keyring`. Since it can be used with `secret-tool` or virtually any other password manager that has some kind of CLI to show password. Another use-case would be to use command to show password from container secret vault when running in container. Normally it is as simple as `cat /run/secret/some-key`.

Of course, there would be an issue if daemon is running under `root`, but same issue is applicable for keyring service as well.

I'm also on `i3` and trying to stay away from DBus Secrets API. Last years I found GnuPG to be better and safer way of managing identities and storing credentials with `pass` tool.

Is there any other service (other than `gnome-keyring`) that implements [DBus Secrets API](https://freedesktop.org/wiki/Specifications/secret-storage-spec/secrets-api-0.1.html)? (at least I'm not aware of any).

**Comment by SirWindfield** [comment]
> Is there any other service (other than `gnome-keyring`) that implements [DBus Secrets API](https://freedesktop.org/wiki/Specifications/secret-storage-spec/secrets-api-0.1.html)? (at least I'm not aware of any).

Not that I am aware of to be honest. Some bigger tools might implement them. `seahorse` has support but afaik it uses gnome-keyring under the hood. Maybe KeyPass or Bitwarden actually do implement it but I never bothered checking.

**Comment by bcmyers** [comment]
Hey all. I just started using `spotifyd` and noticed this is a feature I'd like to have; so I created a [fork](https://github.com/bcmyers/spotifyd/tree/password_cmd) yesterday that implements it (`password_cmd` config entry). The commit messages are terrible and I probably made too many changes to master (as I was playing around with the code to see how it works); so I wouldn't submit a PR for this in it's current state. That said, I figured I would reach out here to see if you'd be interested in a cleaned-up PR at some point, even though you have a rewrite of the config planned. I'm cool either way, as I'm happy continuing to just use my fork. Let me know! :)

**Comment by SimonPersson** [comment]
@SirWindfield 
> I am currently re-writing most of spotifyd to get rid of some bugs and bring in consistency for the configuration (alongside of introducing new exiting features).

Sounds cool! Do you have any code to look at yet? I've been meaning to rewrite the configuration subsystem for some time, but if you have good progress I can just wait for a PR :)

@muradm - I don't mind having a `password_cmd` config option. I guess it never occurred to me as a viable alternative, as I tend to start Spotifyd automatically on the devices where I use it, which is not really compatible with manual user input at start.

@bcmyers - A cleaned up PR would be most welcome!

**Comment by SirWindfield** [comment]
@SimonPersson I just started. I am basically just using one struct for both that implements `StructOpt` from `clap` as well as `Deserialize` and `Serialize` from `serde`. 
I do not have __that__ much time right now, I ocassionaly squeeze an hour or two into the project each weekend. I only did implement the struct itself for now. 

If you have more time __and__ want to work on it, go ahead :smile: I probably need two or three weeks until I get everything right I guess... :)

**Comment by SirWindfield** [comment]
> Substantive differences with master are concentrated in [`config.rs`](https://github.com/bcmyers/spotifyd/blob/password_cmd/src/config.rs), [`error.rs`](https://github.com/bcmyers/spotifyd/blob/password_cmd/src/error.rs) and [`process.rs`](https://github.com/bcmyers/spotifyd/blob/password_cmd/src/process.rs).

One should still be able to get a diff view and basically just copy it into a clean commit (or squash all the commits into one) and create a PR :smile:

**Comment by muradm** [comment]
> @SirWindfield
> 
> @muradm - I don't mind having a `password_cmd` config option. I guess it never occurred to me as a viable alternative, as I tend to start Spotifyd automatically on the devices where I use it, which is not really compatible with manual user input at start.

Actually `password_cmd` is a way to avoid user input :) Will it prompt for user if necessary, pull it out of secret store or over the network, does not matter, depends what command actually is, thus if necessary avoiding user interaction. Which is my case, I just want it to startup automatically after I login to my system. But countless uses.

Btw, @SirWindfield, I just noticed that `spotifyd` stores `.cache/spotifyd/credentials.json`. Is it really  necessary? Would be good to have an option to avoid that as well.

**Comment by SirWindfield** [comment]
I am not sure but out of my memory those are the spotify credentials used to authenticate if you have a premium account. It's actually just an access token with a validity of one hour iirc. The underlying implementation using that token is one of our dependencies, `librespot`.

Out of curiosity, why would you want to not cache them? I think the library just saves them by itself, we do not have any influence on it... But maybe @SimonPersson knows more about it...
