### ISSUE TITLE
Support for zeroconf flag in librespot

### ISSUE THREAD

**Issue by akaessens** [Spotifyd/spotifyd#265]
When using a firewall, the spotifyd client cannot be found by other devices. 
librespot allows using a [flag that sets a port value](https://github.com/librespot-org/librespot/issues/91).

It would be nice to have this flag in spotifyd too.

**Comment by scaronni** [comment]
Stumbled upon this when I was looking for exactly the same thing.

**Comment by Starkstromkonsument** [comment]
I have the same problem. I had to open ports 30000:50000 to get this working :-(
