### ISSUE TITLE
SIGTRAP on adding some playlists to queue

### ISSUE THREAD

**Issue by Paspartout** [Spotifyd/spotifyd#27]
When adding a specific playlist to my queue, spotifyd crashes with the following backtrace:

```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x000000000094e749 in ?? ()
(gdb) bt
#0  0x000000000094e749 in ?? ()
#1  0x00007ffff7ac9b49 in sp_track_release () from /usr/local/lib/libspotify.so.12
#2  0x00000000004033b9 in queue_del_track (trackn=0) at src/queue.c:155
#3  0x0000000000403ebc in command_qaddpl (command=0x7fffe4000cf0) at src/commands.c:325
#4  0x000000000040543a in commandq_execute_command (session=0x62dc00, command=0x7fffe4000cf0)
    at src/commandq.c:186
#5  0x0000000000405002 in commandq_execute_front (session=0x62dc00) at src/commandq.c:64
#6  0x000000000040780a in main () at src/spotifyd.c:156
```

To reproduce the problem you may try to add the following playlist twice to your queue:

```
$ sc pl

...
45 | Music for Programming | spotify:user:redconfetti:playlist:03bKMoeCxREu1jKjPvCXwD | PLAYLIST
...

$ sc qaddpl 45
$ sc qaddpl 45
```

Also to get the gdb output I had to remove the _deamonize()_ function in _spotifyd.c_ .

I currently don't have the time to look into the bug but in a few weeks I may try to fix it, if you don't have the time either :)

**Comment by SimonPersson** [comment]
So, it crashes when a track is removed from the current playlist. To debug further, perhaps you could add the playlist to the queue, and then remove songs one by one? Something like:
```for i in `seq 0 NUMBER_OF_SONGS`; do sc qrm $i; done```
And then see if it crashes on some perticular song.

I'll see if I can get to it soon :)

**Comment by Paspartout** [comment]
I did remove every song one by one and got the following backtrace now:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ac9b46 in sp_track_release () from /usr/local/lib/libspotify.so.12
(gdb) bt
#0  0x00007ffff7ac9b46 in sp_track_release () from /usr/local/lib/libspotify.so.12
#1  0x00000000004033b9 in queue_del_track (trackn=632) at src/queue.c:155
#2  0x000000000040362d in command_qrm (session=0x62dc00, command=0x7fffe4000cf0)
    at src/commands.c:91
#3  0x00000000004053cf in commandq_execute_command (session=0x62dc00,
    command=0x7fffe4000cf0) at src/commandq.c:174
#4  0x0000000000405002 in commandq_execute_front (session=0x62dc00) at src/commandq.c:64
#5  0x000000000040780a in main () at src/spotifyd.c:156
```

Track no. 632 is the following:
```
632 | Hunting and Fishing | Vitalic | spotify:track:7vpeWtZ0SplENa3CubOzAz | TRACK
```
Weird thing is that removing this single song only won't cause the SIGSEGV or SIGTRAP.

It probably is some kind of bug in the spotify library and related to removing a lot of songs in sequence.
Could you try to somehow reproduce the bug to make sure this don't only happens on my system?

**Comment by SimonPersson** [comment]
I get the same stack trace, so it's not only you.

Perhaps I'll find time to investigate further this weekend.

**Comment by SimonPersson** [comment]
I've looked into it a bit more. Now, another song is causing the problem for me!

I'll look into it a bit more but it's a bit hard debugging with libspotify being closed source :-1:

**Comment by Paspartout** [comment]
I know the closed source part is making things harder.

Since the actual segfault happens in the spotify library itself, it may be a good idea to report the
bug upstream to their library instead of trying to work around it tho.

**Comment by SimonPersson** [comment]
The bug segfault happening in libspotify doesn't mean much though, it could just mean that we're asking libspotify to release a song that is already free'd or something. I don't see why it would be only some songs though.

I would report it upstream, except that libspotify is deprecated. They're not developing it any more. It says that they are releasing a new library later this year though. With any luck, the new library will provide at least the same functionality and be supported on the same platforms so I can rewrite the project for the new library. :)

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
