### ISSUE TITLE
Errors flooding syslog when playing podcasts

### ISSUE THREAD

**Issue by jskvbinmv** [Spotifyd/spotifyd#273]
I'm using spotifyd on a raspberry pi 3 for some days now and just tried to play podcasts. 
However this causes hundreds of errors per second:

`
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:59YVIjEgeSbuduO07dXfLS" at position [0] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:5X8fgyTPPLS9qKPw7EIb6y" at position [1] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:25cZkH0OTjmgh2fQ6mSdgq" at position [2] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:1uBkkEqm6Pm59FijZvmhJf" at position [3] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:7iCiwHissyOcasKPdO72ME" at position [4] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:2m1WnM40BxVUJvbESG0x77" at position [5] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:7vfDBRWJ4exOLpmBDE30YF" at position [6] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:7FQeSRIJDVCdEHyzixV4Vf" at position [7] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:6T8iaPTmbsreJyR2Lxcsps" at position [8] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:6yudpj2TsuHuHtHTfLvbJ2" at position [9] of 11
Jul 13 09:44:03 openhab spotifyd[27508]: 09:43:52 [WARN] Skipping track "spotify:episode:3JdQ1pvvTgiHWIP8A4ePjk" at position [10] of 11
`

This causes cpu load going up, making the system almost inusable.

I remember that I've listened to podcasts before and there was no issue that I'm aware of.

Is there something I can do to prevent this error or at least stopping it from causing the rpi to become unusable?

**Comment by SirWindfield** [comment]
Either I am missing something or I'm just plain stupid but it looks like the underlying library we use [doesn't actually has merged podcast support](https://github.com/librespot-org/librespot/issues/90). So why does playback work anyway? 

If they didn't merge then it would probably explain the CPU overload and errors. I don't think Spotifyd does anything special to the audio data and most of the stuff concerning audio is handled by `librespot`.

**Comment by slondr** [comment]
I'm fairly certain that podcasts work as of v0.2.25, so I'm closing this — if this issue still exists for you @jskvbinmv please let us know
