### ISSUE TITLE
Choosing output bit depth resolution

### ISSUE THREAD

**Issue by tirook** [Spotifyd/spotifyd#274]
Hi,
First thanks for the great job, and second sorry if it's not the place. It's more a request than an issue.
I was wondering if you could had a bith depth option as good players do.
Even if the resolution of the song is 16b, I suppose that the internal job is done in 32b float (pregain, normalisation). 
And it would be great to not loss data with an ultimate cast to 16b before outputing song.
I can actually send 24b to my dac with asoundrc plughw and format command, but if i use plughw device from the spotifyd.conf, resolution is still 16bit. That's why I suppose that there is an ultimate conversion at the original format, or worse if all the spotifyd conversion is done with 16 bit resolution if the song is 16bit ?
Thanks by advance.
Christophe

**Comment by SimonPersson** [comment]
Hi! If you really care about the audio quality, I suggest that you set `volume-normalisation=false`, and `volume-control = alsa`. Spotifyd should not do any audio processing whatsoever with those settings, and you will get the original stream from Spotify. By using `softvol` you are throwing away data anyway, the bit depth simply isn't relevant.
