### ISSUE TITLE
Can't find spotifyd in playerctl 

### ISSUE THREAD

**Issue by qmager** [Spotifyd/spotifyd#276]
Hi, I can't seem to find spotifyd in playerctl, at the moment I can only control it with Spotify connect.
I used the precompiled binary and "playerctl status" returned "No players found"

I then tried to build it with: 
cargo build --release --features="dbus_mpris" and ran the compiled binary but it didn't work either.

Did I do anything wrong?

**Comment by SirWindfield** [comment]
Nop. See here for a temporal fix: https://github.com/Spotifyd/spotifyd/issues/271#issuecomment-522946256

The dependency got updated and probably broke something down the line

**Comment by SirWindfield** [comment]
v0.2.18 fixes a lot of MPRIS related issues, alongside your described one.

**Comment by qmager** [comment]
Weird, I compiled the newest git commit and tried the release binary, both didn't work for me

**Comment by deisi** [comment]
I also have the same Issue. For me spotifyd doesn't register any service in dbus.

**Comment by kamek-pf** [comment]
Same here, tried grabbing the latest realse and building using cargo, nothing in dbus.

**Comment by SirWindfield** [comment]
See #434 for further details. This is not only the case for spotifyd so I'll move discussions over to that issue.
