### ISSUE TITLE
can't connect to my pi

### ISSUE THREAD

**Issue by marcintosh1** [Spotifyd/spotifyd#277]
So i can see my spotifyd client in spotify on mc pc, but if i click it to connect, it just dont.

[global]
username = asdasd
password = asdasd
backend = alsa
device = hw:1
mixer = PCM
volume-control = softvol
device_name = raspberry
bitrate = 160
cache_path = cache_directory
volume-normalisation = true
normalisation-pregain = -10

i have my raspberry connected via bluealsa to my bluetooth speaker.
how can i change the config to backend=bluetooth?

**Comment by SirWindfield** [comment]
You don't. There is no backend called Bluetooth. My guess is that bluealsa is the normal alsa backend. Haven't tried it though
________________________________

**Comment by marcintosh1** [comment]
Ok, thank you!
But why can i not connect in spotify itself, my raspberry pops up and everythink seems to work

**Comment by SirWindfield** [comment]
> how can i change the config to backend=bluetooth?

The config file path is mentioned in the readme file. Take a look there. Open it in some text editor and change the values as you please. You do need to change your back-end to `pulseaudio` probably though.

>  But why can i not connect in Spotify itself, my raspberry pops up and everything seems to work.

I am no magician. You could upload your log files though os we can take a closer look. Either start `spotifyd` using the terminal via `./spotifyd --no-daemon > log.txt` or something similar. Upload that file to `pastebin` and comment with the link to it.

You can also check your system logger for the logging output if you configured the logger to start on login. More information is in the [readme](https://github.com/Spotifyd/spotifyd#logging) as well.

**Comment by dniHze** [comment]
I can also reproduce this issue on mine Pi 3 B+ w/ v 0.2.11. Will try to reproduce it and upload log files later today after some changes in the config file.

**Comment by SirWindfield** [comment]
Any updates on this one?

**Comment by marcintosh1** [comment]
I gave up

Sven Lechner <notifications@github.com> schrieb am Di., 10. Sep. 2019,
00:56:
