### ISSUE TITLE
can't compile on RHEL

### ISSUE THREAD

**Issue by tbrandysky** [Spotifyd/spotifyd#28]
[root@host spotifyd-master]# make
make: **\* No rule to make target `/usr/include/stdc-predef.h', needed by`build/audio.o'.  Stop.

in RHEL there is glibc-devel which doesn't include stdc-predef.h file.

**Comment by tbrandysky** [comment]
I see it isn't only problem when trying to compile on RHEL (different libraries etc..) - is there any way the project would be rewritten so it could be easy compiled on any distribution ?

**Comment by SimonPersson** [comment]
So you solved the issue with stdc-predef.h?

What was the other issues you ran into?

The ambition certainly is that the project should work on any distribution,
I'm just not able to test it everywhere. I will consider rewriting some
parts if needed to support rhel.

**Comment by tbrandysky** [comment]
I didn't solve the issue as I have no coding skills. I just tried to google around and found out there is no such file in RHEL - this file probably comes with libc6 lib with RHEL doesn't use it uses glibc instead. I just tried to remove the path to this file from .deps file in build folder but there are many more files which can't be found. I was trying to compile .c files separately to see if any of these can be compiled RHEL but I didn't succeeded (I was probably doing it wrong just like gcc audio.c -o audio.o which returns 
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
/tmp/cciiwhh2.o: In function `audio_get':
audio.c:(.text+0x45): undefined reference to `snd_pcm_close'
collect2: ld returned 1 exit status
)

**Comment by SimonPersson** [comment]
The command would be `gcc -c audio.c -o audio.o`. I guess you could try to compile files like that. With any luck there's just an issue with the Makefile and not the actual code. In any case, I'll have to install CentOS to investigate this one day.

**Comment by tbrandysky** [comment]
It really seems there is a problem with Makefile.
I had to change few things in .h files which tried to include files from wrong locations in RHEL/Centos - e.g. #include <asoundlib.h> to  #include <alsa/asoundlib.h>

After this I was able to compile all .c files to .o files by gcc -c <file>.c -o <file.o>
Once I changed the line in Makefile in build section to:
@echo "  CC $<"; $(CC) $(CFLAGS) -c -o $@ $<

 I'm also able to build whole project without errors:
[root@dev_server127 spotifyd-master]# make clean
  Cleaning...
[root@host spotifyd-master]# make
  CC src/audio.c
  CC src/callbacks.c
  CC src/helpers.c
  CC src/playlist.c
  CC src/commands.c
  CC src/parser.c
  CC src/commandq.c
  CC src/alsa-audio.c
  CC src/socket.c
  CC src/spotifyd.c
  CC src/queue.c
  CC src/search.c
  CC src/session.c
  CC src/config.c
ld -r -b binary -o build/appkey.o src/appkey.key
  Linking 'spotifyd'...

Only problem is when I try to run spotifyd it doesn't start nor it returns any errors.
I'm trying to run it as root with ~/spotifyd.rc file containing valid configuration:
username <myusername>
password <mypass>
port 8080
log /tmp/spotifyd-log

[root@host spotifyd-master]# ./spotifyd 
[root@host spotifyd-master]# echo $?
0


but actually it doesn't listen on port 8080 nor it creates the logfile in tmp. 
The same thing is when I try to change port to socket.

Only idea I have is that it doesn't run because the server I'm running it on is actually a VPS (Centos 6) for testing purposes (RPM building) without sound card. I'd suppose it would just end with some error. 

thank you

Tomas

**Comment by SimonPersson** [comment]
What changes did you have to do to the includes? I suspect this is because you compiled by hand and then pkg-config didn't give the right search paths to the compiler.

As for the server not running, does it crash? Could you take a look using `ps aux | grep spotifyd` to see if it is still running or not? Logging and error reporting is admittedly a bit poor, unfortunately... I just pushed a small change that let's you run as `./spotifyd --no-daemon`, and the process will stay in the foreground. Perhaps that will give you some more error messages!

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
