### ISSUE TITLE
Unify error types

### ISSUE THREAD

**Issue by mainrs** [Spotifyd/spotifyd#284]
Currently there are two different error types within `error.rs`. They can be merged into an enum called `SpotifydErrors` or something similar using the `failure` crate.

**Comment by SirWindfield** [comment]
I like the assign command. Maybe there is a github action for it 🤔

**Comment by vladdoster** [comment]
> I like the assign command. Maybe there is a github action for it

This is the [package](https://github.com/kubernetes/test-infra/tree/master/prow#bots-home) that enables the /foo commands

**Comment by oriolval** [comment]
I would like to assign the issue to myself becuse I think that this user is not working on it.

**Comment by SirWindfield** [comment]
`failure` is deprecated now so maybe switching to `thiserror` would be good as well. That way the derives don't have to be written by hand. Not sure how relevant this is, maybe a maintainer can chime in, as I haven't worked on the code for a long time :( @Spotifyd/maintainers.

**Comment by robinvd** [comment]
we already use https://docs.rs/eyre/0.6.5/eyre/, which and has a Report type that is a dynamic error type (if you need that in the refactor). It does not include any derive mechanism, but it also recommends `thiserror`

**Comment by oriolval** [comment]
Sorry for the delay, I'm working on it. Hope I have an update soon.
