### ISSUE TITLE
Move logging to fern

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#285]
`fern` is able to log to stdout as well as system logs by attaching handlers during the initialisation. This would move our logging dependency to one crate instead of two and would remove the awkward logging code in `main.rs`. Yes, `fern` does use `syslog` under the hood but it would clean up the `setup_logger` function to only use crate calls from `fern` instead of two different crates.

**Comment by mh84** [comment]
I likely would take care of this. :)

**Comment by SirWindfield** [comment]
Nice!

A side note from me: `fern` exposes a package called `syslog` which is basically the same crate. The idea was to get rid of all those silly if statements and differentiations between the two packages and somehow merge the logger creation together. You could, for example, create a base configuration and check if we are running in verbose mode. If that is the case, just add another pipe to the config that uses the syslogger.

I have some prototype lying around but I am pretty sure I won't find it on my drives as my organisation is totally horrible :D
