### ISSUE TITLE
Provide optimised arm binaries

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#286]
armv7 allows for further optimisation during compilation. We currently only offer armv6 binaries, which run on armv7 too though.

**Comment by juliangaal** [comment]
Which optimizations are these exactly? Getting an armv7 device in the mail today :D

**Comment by SirWindfield** [comment]
That's a hard one I think. At least I couldn't really figure it out. Cross compilation is a bitch sometimes >.>

We currently are on the move to Github Actions (GA) but still use the good old Travis CI. `ci.yml` does some linting and formatting checks for PRs, `cd.yml` does the binary compilation for linux and macos. The ARM binaries are still compiled on Travis CI. 

So this issue would mean to first move the compilation of the ARM binaries to GA. You probably have to create a new workflow as you can't have arm and amd64 binaries installed on the same instance, something like `cd_armv7`. 

> Which optimizations are these exactly?

Ideally you would create three new workflows (armv6, armv7 and aarch64). In theory, armv6 can run on all of them, but each new version introduces new instructions and optimizations the compiler can do. So separate binaries would be ideal. 

Currently, only armv7 gets build on Travis CI.

> But how do I test workflows?

What a great question to ask! You would create a fork of Spotifyd, push a new workflow and create a PR. Make sure to set the trigger to `pull_requests` for testing purposes. Remove the old workflows to shorten run-time. Each new commit to the same PR will trigger a new workflow run. Quite cumbersome yes.

I think the key/trick is to create a workflow for each architecture. I already tried arm compilation but was super greedy and created one workflow for all of them, which didn't work. So I gave up for now :)
