### ISSUE TITLE
Provide more events that people can use to script

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#288]
like on-login-hook or on-device-connected-hook, meaning that people can create more custom scripts to show notifications or do other stuff

**Comment by tuxfamily** [comment]
I would love to have events for:
- on connect
- on disconnect
- on volume up
- on volume down
This way I would be able to turn on/off my amplifier and change volume on the amplifier rather than the Pi.

**Comment by SirWindfield** [comment]
__Note:__ This has to be (mostly) implemented inside of librespot

**Comment by DaAwesomeP** [comment]
This might help: https://github.com/librespot-org/librespot/pull/452

**Comment by DaAwesomeP** [comment]
Is it possible to make use of the events added in https://github.com/librespot-org/librespot/pull/452?
