### ISSUE TITLE
Lock file was not updated on release 0.2.12.

### ISSUE THREAD

**Issue by bertptrs** [Spotifyd/spotifyd#291]
Similar to #255, the lock file was again not updated for release, making reproducible builds impossible.

**Comment by SirWindfield** [comment]
Hm, weird that this happens. Pretty sure I re-generated it.

**Comment by SirWindfield** [comment]
Does [this](https://github.com/SirWindfield/spotifyd/commit/4f275763514d04567515c09641b8ffdd1a47aca6) commit work for you now?

**Comment by bertptrs** [comment]
> Hm, weird that this happens. Pretty sure I re-generated it.

I can reproduce this easily:
```
curl -Ls https://github.com/Spotifyd/spotifyd/archive/0.2.12.tar.gz | tar -xz; cd spotifyd-0.2.12; cargo build --locked
error: the lock file /home/bert/Downloads/spotifyd-0.2.12/Cargo.lock needs to be updated but --locked was passed to prevent this
```

> Does [this](https://github.com/SirWindfield/spotifyd/commit/4f275763514d04567515c09641b8ffdd1a47aca6) commit work for you now?

Yes, I can successfully build that one.

**Comment by SirWindfield** [comment]
I will push a new tag then. Thanks for letting me know!

**Comment by bertptrs** [comment]
Thank you for the quick resolution.

**Comment by SirWindfield** [comment]
No problem. I just noticed that I forgot to bump the version to 0.2.13. Doesn't really matter as more changes are coming, I'll just fix it then :)

**Comment by SirWindfield** [comment]
@bertptrs As you happen to use the `--locked` function of cargo, would it be a good idea to use that flag too during the CI builds?

**Comment by bertptrs** [comment]
I think it would be. That way, failing to update the lock file would fail the build.
