### ISSUE TITLE
spotifyd increased volume on startup

### ISSUE THREAD

**Issue by hifiberry** [Spotifyd/spotifyd#295]
spotifyd automatically increased the volume when starting up.
This is especially problematic when the daemon crashes several times and gets restarted as this will increase the volume until maximum volume is reached

```
$ amixer sget Digital
Simple mixer control 'Digital',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 207
  Mono:
  Front Left: Playback 77 [37%] [-65.00dB] [on]
  Front Right: Playback 77 [37%] [-65.00dB] [on]
```
```
$ /usr/bin/spotifyd --no-daemon
14:07:06 [INFO] Using alsa volume controller.
14:07:06 [INFO] Connecting to AP "gew1-accesspoint-a-9t34.ap.spotify.com:443"
14:07:06 [INFO] Using alsa sink
```

```
$ amixer sget Digital
Simple mixer control 'Digital',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 207
  Mono:
  Front Left: Playback 125 [60%] [-41.00dB] [on]
  Front Right: Playback 125 [60%] [-41.00dB] [on]
```
```
$ /usr/bin/spotifyd --no-daemon
14:07:14 [INFO] Using alsa volume controller.
14:07:14 [INFO] Connecting to AP "gew1-accesspoint-a-qtdc.ap.spotify.com:443"
14:07:14 [INFO] Using alsa sink
```
```
$ amixer sget Digital
Simple mixer control 'Digital',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 207
  Mono:
  Front Left: Playback 155 [75%] [-26.00dB] [on]
  Front Right: Playback 155 [75%] [-26.00dB] [on]
```
```
$ /usr/bin/spotifyd --no-daemon
14:07:22 [INFO] Using alsa volume controller.
14:07:22 [INFO] Connecting to AP "gew1-accesspoint-c-0x6f.ap.spotify.com:443"
14:07:23 [INFO] Using alsa sink
```
```
$ amixer sget Digital
Simple mixer control 'Digital',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 207
  Mono:
  Front Left: Playback 174 [84%] [-16.50dB] [on]
  Front Right: Playback 174 [84%] [-16.50dB] [on]
```

**Comment by SirWindfield** [comment]
Could you please try out version `0.2.11` and see if it happens there too? I did some major refactoring and I might have screwed up something.

**Comment by hifiberry** [comment]
Seems to be an older issue. I tested it now with 0.2.10 (that's the version I just had at hand)

**Comment by SirWindfield** [comment]
Thanks for checking this one out! I think it's an issue with either how we use librespot or how librespot caches the volume. I'll do some research.

**Comment by bxabi** [comment]
I see the same, the daemon always starts with maximum volume.

**Comment by SirWindfield** [comment]
By always you mean even after changing it and restarting or just the first time?

**Comment by bxabi** [comment]
Yes, every time the daemon is started, it's on maximum volume. It doesn't remember that it was set lower at a previous run.

**Comment by geoffrays** [comment]
Same Issue here. Would love to be able to choose the default volume level.

**Comment by MikaelElkiaer** [comment]
I came here after opening: https://github.com/Rigellute/spotify-tui/issues/373
This issue might actually be the correct one.

It might also be worth mentioning other settings than just volume - such as Shuffle, Repeat, and perhaps others still.
