### ISSUE TITLE
Update snap release

### ISSUE THREAD

**Issue by RlndVt** [Spotifyd/spotifyd#296]
Can the snap release be updated? 0.2.3 is pretty outdated imo.

Don't know if this is the best place to 'report' this but I'm having issues with the snap version that have been fixed in later releases. (In addition the building of a new snap release doesn't work for me, tried on Ubuntu 18.04, 16.04 in VM, and on arch. Error below is from 18:04.)

```
Pulling spotifyd 
Downloading 'rustup.sh'[==================================================================================================] 100%
/home/$USER/.cargo/rustup.sh -y --no-modify-path --channel nightly
info: downloading installer
error: Found argument '--channel' which wasn't expected, or isn't valid in this context

USAGE:
    rustup-init --no-modify-path -y

For more information try --help
Sorry, an error occurred in Snapcraft:
Failed to run '/home/$USER/.cargo/rustup.sh -y --no-modify-path --channel nightly' for 'spotifyd': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 86 (delta 55), reused 51 (delta 23), pack-reused 0
Unpacking objects: 100% (86/86), done.
From https://github.com/Spotifyd/spotifyd
   4204ae7..909ff52  master     -> origin/master
 * [new tag]         0.2.12     -> 0.2.12
 * [new tag]         v0.2.13    -> v0.2.13
warning: refname '0.2.11' is ambiguous.
D       snap/snapcraft.yaml
Switched to branch '0.2.11'
Sorry, an error occurred in Snapcraft:
[Errno 2] No such file or directory: '/tmp/tmpt2j4_9cu/function_call'
You can find the traceback in file '/tmp/tmphhdnrnvf/trace.txt'.
```

**Comment by SirWindfield** [comment]
Does snap download the packages pre-made or do users compile them on their local machine?

**Comment by RlndVt** [comment]
Premade as far as I know.

**Comment by SirWindfield** [comment]
If they are premade I can't update them as I have no access to the Ubuntu snap repository.

**Comment by SirWindfield** [comment]
TODO: investigate if it is possible to make snap packages on the CI server.

**Comment by RlndVt** [comment]
Any update on this?

Is there a way I can help to figure this out?

**Comment by SirWindfield** [comment]
Not really. There is a webhook installed on this repo which should get triggered on tagged releases that follow the pattern `v*.*.*` but that didn't happen. I can't really take a look at it as the account that is used to set it up is tight to @SimonPersson. Maybe he can add me somehow as a collaborator? My username over there is `sirwindfield`.

**Comment by hurricanehrndz** [comment]
@SirWindfield 

Please see the following:
https://github.com/Rigellute/spotify-tui/pull/295

**Comment by slondr** [comment]
@SirWindfield Has any progress been made on this & #237?
