### ISSUE TITLE
Make CLI flags feature aware

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#297]
As of now, the CLI's help page always displays all flags, regardless of whether they are applicable or not. For example, if the `dbus_keyring` feature has not been specified, the CLI still shows the flag. This happens with the possible values for `backend` as well.

**Comment by jackloughran** [comment]
@SirWindfield I didn't use the correct closing issue keyword in my pr, so this didn't close.

**Comment by SirWindfield** [comment]
Oh yeah. Thanks again!
