### ISSUE TITLE
Unable to make on Raspberry Pi

### ISSUE THREAD

**Issue by Halloran** [Spotifyd/spotifyd#31]
Trying to make on Raspberry Pi; kernel 3.12, and I get:

$ sudo make  
`Linking 'spotifyd'...    
/usr/bin/ld: build/helpers.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line    
collect2: ld returned 1 exit status    
Makefile:13: recipe for target 'spotifyd' failed    
make: *** [spotifyd] Error 1`
Any suggestion as to what to try much appreciated! Thanks for what looks like a great project.

**Comment by Halloran** [comment]
I was able to resolve this by adding -lrt to line 4 of the Makefile:
`LIBS    := `pkg-config --libs $(PKGS)` -lpthread -pthread -lrt`
Since I can't validate if this works as expected on other platforms, I did not do a pull request.....

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
