### ISSUE TITLE
Consider changing default audio backend to rodio

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#310]
In theory, this would also allow creating a windows service, ultimately porting spotifyd to windows. The Wiki entry relevant to this: https://github.com/librespot-org/librespot/wiki/Audio-Backends

**Comment by b0rna** [comment]
I had horrible audio corruption with alsa + kubuntu on an old dual core AMD system using the pre built binary and HDMI output.

Recompiled with pulse and working flawlessly so far.
