### ISSUE TITLE
Provide binary assets for 0.2.14

### ISSUE THREAD

**Issue by jonkerj** [Spotifyd/spotifyd#325]
Hi,

I noticed the 0.2.14 release did not provide binary assets on GitHub. I know I can compile them myself, but being a bit lazy it makes a great convenience is they are provided through GitHub releases :-)

Thanks,

Jorik

**Comment by SirWindfield** [comment]
There have been recent changes to the CI server. The problem is our scripts currently fail because of a dependency having some problems. The binaries get only uploaded during successful builds.

I might some code today (or tmrw) that fixes some bugs so I can bump the version number and provide the binaries manually :)

I could also just compile them and upload them manually for 0.2.14 too 🤔

**Comment by SirWindfield** [comment]
Do you need the ARM binaries? macOS and Linux are being built right now.

**Comment by jonkerj** [comment]
Thanks! ARM and x86_64. I'll await the builds then.

**Comment by SirWindfield** [comment]
Check the v0.2.15 release. ARM is on its way after I ate :)

**Comment by jonkerj** [comment]
Bon apetit, Sir :-) This is a good example why open source is great!

**Comment by SirWindfield** [comment]
Having some problems cross compiling for ARM >.>

**Comment by jonkerj** [comment]
Found them! Thanks again! One itty bitty thingy, though:

```
jorik@boron:~$ curl -Lso /tmp/s.tgz https://github.com/Spotifyd/spotifyd/releases/download/v0.2.15/spotifyd-armv7-slim.tar.gz
jorik@boron:~$ tar -C /tmp -zxf /tmp/s.tgz
jorik@boron:~$ /tmp/spotifyd --version
spotifyd 0.2.14
```
Note the difference in version numbers in URL (ie, release) and reported by the binary. 

Not a big deal, but my ansible role managing the various spotifyd's in my house make the upgrade decision based on `spotifyd --version`. I'll work around this with some logic, checksum chekcing instead of version reporting is much more robust anyways.

**Comment by SirWindfield** [comment]
Ye, I actually forgot to update it in the code :(
