### ISSUE TITLE
MPRIS commands trigger panic

### ISSUE THREAD

**Issue by treeshateorcs** [Spotifyd/spotifyd#328]
https://gist.github.com/treeshateorcs/85cda230359f277037cb9d9075d2b713

**Comment by treeshateorcs** [comment]
v0.2.13 just panics right off the bat
https://gist.github.com/treeshateorcs/8c9156d156ee261c16394346264081c0

**Comment by SirWindfield** [comment]
Ah my bad, sorry. I messed v0.2.13 up! v0.2.11, could you check that one? It was the last one released by Simon.

**Comment by treeshateorcs** [comment]
I can't find 0.2.11 in tags, anyway I think it worked fine just a couple weeks ago

**Comment by treeshateorcs** [comment]
0.2.1 (the closest to 0.2.11) doesn't compile

**Comment by SirWindfield** [comment]
https://github.com/Spotifyd/spotifyd/releases/tag/0.2.11 :)

**Comment by treeshateorcs** [comment]
nope, it panics on 0.2.11

**Comment by SirWindfield** [comment]
Ye thought so, it's been in there for some time. I started a PR over at #324. I just layed down some general "layout". Tackling those bugs down is part of the PR :)

**Comment by treeshateorcs** [comment]
hm. weird. I'm sure I used it without issues in August

**Comment by SirWindfield** [comment]
what do you use to control it? playerctl? There have been some bugs reported about it too. You would have to had v0.2.11 or prior installed then.

**Comment by treeshateorcs** [comment]
mpris-ctl and mpris-control work fine, playerctl doesn't

sure i'd be happy to test it for you, if I'm still using it by then

**Comment by treeshateorcs** [comment]
for some reason mpris-control doesn't work as a i3wm hotkey, works in terminal just fine

**Comment by taigrr** [comment]
@SirWindfield Would appreciate a ping as well. I use spotifyd-full daily, and it's now completely broken. To be clear, I'm not complaining, as I didn't write a line of it and am just freeloading, but if you do happen to get it fixed, I'd be happy to help test it out for you! I run lastest archlinux at all times, so it's no bother to frequently update it or even clone and test pre-release tags.

**Comment by taigrr** [comment]
@SirWindfield Hmm. On second inspection, perhaps this isn't the right issue to comment on after all. It looked similar to what I was facing but I may just open a new one. I do have issues querying metadata but I think I may have a more significant error happening here. Thanks, I'll look into it some more then maybe report back.

**Comment by taigrr** [comment]
@treeshateorcs see https://github.com/Spotifyd/spotifyd/issues/258

**Comment by taigrr** [comment]
@SirWindfield can confirm works now after #346
