### ISSUE TITLE
Connection works but search results are empty

### ISSUE THREAD

**Issue by uweschmitt** [Spotifyd/spotifyd#33]
I tried the examples with `sc` provided at the web site but I get empty search results. The client is connected according to the log file and my mpd client can connect to port 12345. Any idea how to debug this ? I built it on a Rasperry Pi 2, and `make`  and  `make install` worked without any error messages.

**Comment by SimonPersson** [comment]
Yes, unfortunately Spotify have turned off the API that was used for
searching: https://developer.spotify.com/web-api/migration-guide/.

This project will need a rewrite to work again. Hopefully, I will find time
for that one day...

Sorry I can't be of more help!

**Comment by uweschmitt** [comment]
Thanks for the fast answer, but nice idea anyway :)
