### ISSUE TITLE
Multiple Instances on Same Network Stomping on Each Other

### ISSUE THREAD

**Issue by br00tal** [Spotifyd/spotifyd#332]
Hi all. First I want to say this software is awesome and use it all the time.

I have two rpis running `spotifyd` on my network, one serving my garage (named `garage`), and the other serving my living room (named `house`). Both used to show up in the devices list in the official `Spotify` client just fine, and worked perfectly. I recently upgraded to newer versions of this software, and since at least `0.2.13`, there's an issue where only one of the instances shows up. I noticed that, upon initial startup of the official client, if I quickly go to the devices list, I first see one of the devices (`house`), but then it is quickly replaced with my other device (`garage`), which then stays listed as is usable. If I shutdown the device that stays listed, the one that disappears shows up in the list again and is usable. I should also mention that if I'm fast enough to click on the first device that eventually disappears, I am able to connect to it and use it.

The only config option that seemed somewhat relevant was the `zeroconf_port`, which I set to an explicit port on the `garage` instance, but that didn't help.

Any ideas as to why this would be happening all of a sudden? Thanks again for the great software!

**Comment by SirWindfield** [comment]
Sounds like both devices get the same external ID or something. Based on your description I would say Spotify things that both devices are the same. I might have messed some ID related code up. I can take a look later on.

**Comment by SirWindfield** [comment]
Found the problem. I refactored a large part. The device_id (the one Spotify sees) got updated after changing the device_name. I forgot to do that in the new code. [These](https://github.com/Spotifyd/spotifyd/blob/caefa87426442c961f9133b49a9e88dab7cef68b/src/config.rs#L196) are the relevant lines before I pushed the changes with v0.2.13.

I have to do some stuff for university. I should be able to squish out 10 minutes later on and push a new minor release. The arm binary workflow that automatically compiles new releases is currently in the works, I will provide them myself after I cross compiled them. it might take some time after I pushed a new release though.

**Comment by SirWindfield** [comment]
@br00tal the CI servers are currently building the binaries. Won't take much longer :)

**Comment by br00tal** [comment]
Awesome! Thanks for so much for looking into this and for fixing it so fast. :)

**Comment by SirWindfield** [comment]
No problem! If you still encounter problems, open another issue :smile:
