### ISSUE TITLE
spotifyd + vlc

### ISSUE THREAD

**Issue by Cherkah** [Spotifyd/spotifyd#339]
hi guys.
this is not an issue but an HowTo asking.
related to #202  and [this topic](https://github.com/jonas-lundqvist/vlc-spotify/issues/2).

How to run spotify via spotifyd over vlc?
i'm running manjaro os and i've installed spotify & spotifyd. 
in spotifyd.conf should i choose a port then create it in iptables then set vlc on it,  or anything else?
if someone know about what im talking, do not shy ;)

 post #202  will finds an other argue to install spotifyd  less spotify.
regards

**Comment by SirWindfield** [comment]
What do you mean by "over vlc" ? Spotifyd announces itself as a spotify connect device that you can choose to stream to from the official apps. Start spotifyd, start the app on your phone and play a song. You can then choose spotifyd as the playback device. It will then play the song on the PC you run it on instead of your phone. There is no need for vlc.

**Comment by Cherkah** [comment]
"over vlc" or with vlc = via vlc !
i know that it is possible to use vlc to search/play/use spotify cache/... instead of use/install the app on my pc.
 just to know does it possible? and how do it?

**Comment by SirWindfield** [comment]
I never heard of this nor do I have any idea how to accomplish this.

**Comment by Cherkah** [comment]
Did you looked the second link i put in my first message ?

**Comment by Cherkah** [comment]
i understand that some possibilities should not have to be publish on github/spotifyd place. but my intentions about this howto are clean.

**Comment by SirWindfield** [comment]
> but my intentions about this howto are clean.

They might be clear for you, but I still do not understand what your goal is. Yes, I took a look. The project seems to be dead anyway as the maintainer didn't want to continue developing it. If VLC can read the cache you can set a `cache_path` in the config file. More on that in the readme file of `spotifyd`. 

I still don't understand why you want to use both. Like, the whole point of spotifyd is to run in the background and play music. It literally can't do anything else.

**Comment by Cherkah** [comment]
please, don't be so "simple-mind" respectfully...
> I still do not understand what your goal is ... I still don't understand why you want to use both.
my answer has already been put.

> You can then choose spotifyd as the playback device. It will then play the song on the PC you run it on instead of your phone. There is no need for vlc.
why maintain spotifyd if nowadays each linux-os  -> users have access to official spotify app by several ways

> I have any idea how to accomplish this.
that's enough for me. if you do not know maybe someone else know...

forget about, i'll looks for outside github.com/Spotifyd place.
regards

**Comment by SirWindfield** [comment]
Yeah... If you seek help from others you should probably stop calling people simple minded in the first place.
