### ISSUE TITLE
Make runs and installs without issue, but no output when running spotifyd

### ISSUE THREAD

**Issue by hatten33** [Spotifyd/spotifyd#34]
I was able to run make and make install fine, but when I try to execute ./spotifyd or spotifyd on the command line, I get no output and I can't access the server or logfiles. What am I doing wrong?

**Comment by SimonPersson** [comment]
I'm not sure what you're issue is exactly, but this project is broken due to Spotify closing down the API I was using. See #33 for details.

I'll add a notice to the readme.

**Comment by SimonPersson** [comment]
As Spotifyd had to be rewritten entirely from scratch, this bug report is no longer relevant. Feel free to try out the new version and report any issues.

Closing.
