### ISSUE TITLE
error: Invalid value for '--pid <pid>': invalid digit found in string

### ISSUE THREAD

**Issue by stuart12** [Spotifyd/spotifyd#340]
hello, my [systemd config](https://github.com/stuart12/stuart-system/blob/master/kooka/etc/systemd/system/spotifyd-run.service) contains

`ExecStart=/tmp/spotifyd --no-daemon --config-path %t/%N/spotifyd.conf --pid %t/%N/pid $backend --bitrate 320 --volume-control softvol`

and now I get the error message: `error: Invalid value for '--pid <pid>': invalid digit found in string`. I'm confused. I've always been passing a filename to the `pid` argument. Why does it now want a number? I don't understand the new help message either `--pid <pid>                                Process id to launch the daemon on`. Why can we no longer pass a filename to the `--pid` option?

**Comment by SirWindfield** [comment]
I didn’t know that passing a file worked as well. I refactored the whole config Code and just assumed that digits were the only argument that would make sense.

How exactly does a file as a pid work? Does it use the file as a lock under Linux?

**Comment by stuart12** [comment]
spotifyd used to store the pid of the daemon process (ie after the fork) into the filename given to the `--pid` option. This is important when running spotifyd from systemd so that systemd can monitor the spotifyd process correctly. As far as I know it never made any sense to pass digits to `--pid`.

**Comment by SirWindfield** [comment]
Ah I misunderstood the flag than. I can fix that tomorrow and push a new release.

**Comment by stuart12** [comment]
thanks, I had to go back to the tag `0.2.11` to get a version that accepts a filename passed to the `--pid` option.  I just realised that I do not currently need the `--pid` option as I'm currently using `--no-daemon` so no rush for me.  I'll keep following the `master` branch.

**Comment by SirWindfield** [comment]
Hey @stuart12, would you mind testing out PR #342 and see if the fix works for you?
