### ISSUE TITLE
Add `debug` CLI config that prevents logging from taking out values for privacy

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#355]
This would be a nice to have feature to make debugging `BadCredentials` during the login step of the daemon easier to debug. It would allow people to see their password and username used within the configuration.

How to implement:
- Add a boolean flag (name is up for discussion) to the `SharedConfigValues` struct.
- Check for the flag [in this method](https://github.com/Spotifyd/spotifyd/blob/ea66c13a0288c0b8ec39c857fcf5b354ceb070b0/src/config.rs#L315) and change the values accordingly.

**Comment by olavbm** [comment]
I'd like to contribute here.

**Comment by SirWindfield** [comment]
Someone created a PR linked above (#360). We came to the conclusion that it would be better to move our Debug implementation one scope up in the chain. See https://github.com/Spotifyd/spotifyd/issues/360#issuecomment-539150809 for more information. 

I am not sure how much experience you have with Rust. This might be a harder issue to resolve than other issues I marked with “good first issue”. Feel free to give it a try though! 

You can open a new PR after you implemented it. Make sure to link back to this issue and the PR I mentioned above.

**Comment by SirWindfield** [comment]
Correction on my part. The Debug implementation doesn’t need to be moved. CliConfig just needs one too that call the one of SharedConfigValues. 

I am typing this up form my memory. So if you think I am talking gibberish, please let me know :)
I just don’t want you people wasting time on an issue that might actually not work as I imagine it right now. That’s why I wrote in #360 that I’ll take a closer look myself :)

**Comment by Iselk** [comment]
Hi @SirWindfield ! Can I help out with this issue?
Should I do as you stated in the first comment?

**Comment by robinvd** [comment]
@Iselk yes that should do it! If you need any help you can ping me here or in a pr

**Comment by jackvstrickland** [comment]
> Hi @SirWindfield ! Can I help out with this issue?
> Should I do as you stated in the first comment?

have you started yet? If not, I wouldn't mind taking a crack at it

**Comment by SirWindfield** [comment]
I'm not actively developing anymore, just keeping a watchful eye around here ;) I've assigned @Iselk as they offered their help first. If we do not receive any updates you can gladly take over @jackvstrickland.

In the meantime, there are other issues that need help :)

**Comment by Iselk** [comment]
Hi @jackvstrickland 

> have you started yet? If not, I wouldn't mind taking a crack at it

I am. It *will* be done this week, *probably* on Friday.
