### ISSUE TITLE
Spotifyd no longer available after a few tracks

### ISSUE THREAD

**Issue by Karrq** [Spotifyd/spotifyd#361]
Hello,
today I started using this software so I could get rid of the official client in my machine but unfortunately I've encountered an issue.
After a number of tracks  (usually 2) I notice the music stops and if I check on other clients it doesn't show up in the 'Spotify Connect' devices anymore. The system logs don't report anything.
To get spotifyd to show up again I have to restart the daemon and then connect to the device.

Is this a known issue? Am I using it incorrectly? Thank you

**Comment by SirWindfield** [comment]
Sounds like your WiFi drops (or ether). If that happens, the daemon basically blocks. There is currently no way to make it auto-reconnect as the underlying library we use doesn't support this.

**Comment by Karrq** [comment]
I see. Thank you. 
It would be useful to log this event to aid external troubleshooting ([akin](https://gist.github.com/JeremieRapin/bc35a2632c072a082d48f5503270df16) to how a user has done already)

Link to relevant librespot [issue](https://github.com/librespot-org/librespot/issues/134)

EDIT: I actually noticed a 
`03:36:40 [ERROR] Os { code: 110, kind: TimedOut, message: "Connection timed out" }`
but the previous log message (when a 2 minute track started playing) was at `03:16:40`, so the timeout is 20 minutes?

**Comment by SirWindfield** [comment]
I never looked too much into it as it has to be done in `librespot` and I had no time to get familiar with their code. But it is weird that the timeout message shows up that much later...

**Comment by slondr** [comment]
Should be resolved by the new v0.2.25 release, which included #511 — let us know if the issue pops up again
