### ISSUE TITLE
Arrow keys not bound

### ISSUE THREAD

**Issue by ay3w** [Spotifyd/spotifyd#362]
Arrow keys aren't bound to the "move selection" functions as described in the help menu. The vim binds (hjkl) work fine however, as do ctrl-n and ctrl-p.

**Comment by ay3w** [comment]
just tested in a different terminal emulator - this appears to be a issue specific to yakuake.

**Comment by SirWindfield** [comment]
I think you are posting the issue on the wrong repo anyway :smile:
