### ISSUE TITLE
Investigate if spotifyd can be used without an account specified

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#366]
We had quite a few issues concerning this. A lot of people claim that they can't see the device on the network if no login has been specified or can't connect to the daemon from other accounts even though they are on the same network.
I remember that this was mentioned and possible by just not logging in with the daemon. That way, it would only work on the local network.

This might be due to a change in the Connect API or librespot. There is a PR over at #365 but I had no time to test it out. It might fix it though. 

Related issues are #181, #246, #290.

**Comment by juliangaal** [comment]
and #373, for reference.

**Comment by Yarn** [comment]
This seems to be working on master after bumping the librespot version.

**Comment by SirWindfield** [comment]
Interesting, so they probably changed the protocols or something similar. Thanks for helping out @Yarn!

**Comment by juliangaal** [comment]
Can you confirm this on a device running spotifyd @Yarn ? Sry for confirming it to work initially @SirWindfield, but after running it for multiple days it stopped working reliably. Sometimes even a restart doesn't enable discovery mode.

Following this, I tried to use librespot (librespot-org) directly, master branch. Same issue. 

I would suggest communicating with the librespot-org team further.

**Comment by Yarn** [comment]
Running https://github.com/librespot-org/librespot/ directly seems to work for me. It seems to be working with the version of spotifyd in master as well. Does it not work consistently or only some of the time? I can try leaving it running for a while and see if it stops working.

If you can reproduce the issue try running spotifyd with `--no-daemon` and see if there is anything interesting in the output.

**Comment by juliangaal** [comment]
> Running https://github.com/librespot-org/librespot/ directly seems to work for me. 
For me it doesn't: I'm using `./target/release/librespot -n "Librespot" -b 320 -c ./cache --enable-volume-normalisation --initial-volume 75 --device-type computer` to run. I assume this is the "discovery mode" you were talking about? 

>  Does it not work consistently or only some of the time? 
consistently doesn't. What may have happened was that it used my old config file, after which i assumed discovery mode works.

[my log](https://paste.gg/p/anonymous/81dad25a161345479635e235bd47aac9) doesn't look off to me, but have to investigate further later

**Comment by Yarn** [comment]
Just doing `cargo run -- --name test` works for me with librespot master so it looks like there is something wrong at the librespot level. Maybe it's something with your network? I'm not sure how that varies if you have an account specified.

Can you try running it on a different network?

**Comment by juliangaal** [comment]
I think you're right, it looks like network troubles. Everything works fine with username/passwd. I don't know much about networking, any ideas what the problem(s) could be?

I'll try on a different network tomorrow.

**Comment by SirWindfield** [comment]
Do you block incoming connections by default using iptabled/firewall?

Try to disable those rules and see if it works then

**Comment by SirWindfield** [comment]
My guess would be that spotifyd using an account uses the normal 22 port for http. But running on a local network actually uses a port somewhere between 3500-5000 iirc
