### ISSUE TITLE
Spotifyd not opening

### ISSUE THREAD

**Issue by burnerdog** [Spotifyd/spotifyd#367]
Here are the logs I get when I try to open it:

> 10/10/19 6:32 PM	Spotifyd	Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by SirWindfield** [comment]
The cache directory is not created if it doesn't exist.

**Comment by bencikdesign** [comment]
having same issue after first install from AUR.

**Comment by SirWindfield** [comment]
As I said above, I think it's the config_path folder not existing during startup. Make sure to check that and create it beforehand. If that's not the issue, please add a full log to this issue and make sure to run `spotifyd --no-daemon --verbose` to get some more detailed output.

**Comment by SirWindfield** [comment]
Hey, did you guys resolve this issue? I would like to close the issue if the above (or something else) resolved this.
