### ISSUE TITLE
No --backends argument

### ISSUE THREAD

**Issue by nickcorona** [Spotifyd/spotifyd#370]
❯ spotifyd --backends
error: Found argument '--backends' which wasn't expected, or isn't valid in this context
	Did you mean --backend?

USAGE:
    spotifyd --backend <string>

For more information try --help

**Comment by SirWindfield** [comment]
Yes, the argument doesn’t exist anymore. Passing down `—help` will show all available backends.

**Comment by mysolarium** [comment]
@SirWindfield it appears to me that -h is not showing available backends: 

`    -b, --backend <string>                         The audio backend to use [possible values: ]`

**Comment by SirWindfield** [comment]
That just means that you compiled a binary with no backends.

**Comment by nickcorona** [comment]
Mmm, should be removed from the config comment then.

**Comment by SirWindfield** [comment]
Yep, definitely. I had a new readme going on anyway that explains every variable in detail. But that is still WIP. I'll remove it then. If you want you can create a PR andI'll merge it :)
