### ISSUE TITLE
Can't run spotifyd

### ISSUE THREAD

**Issue by nickcorona** [Spotifyd/spotifyd#371]
`21:49:53 [ERROR] Couldn't read volume from alsa device with name "pulse".`

Receive this error from using `pulse` or `default` as alsa_audio_device in config.
`aplay -L` returned these as possible values.

What am I doing wrong?

Tried `pulseaudio` as well:
<pre><font color="#B48EAD">❯</font> <font color="#A3BE8C">spotifyd</font> --verbose --no-daemon | <font color="#A3BE8C">grep</font> ERROR
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL pulseaudio
21:57:41 <font color="#BF616A">[ERROR] </font>Couldn&apos;t read volume from alsa device with name &quot;pulseaudio&quot;.
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL pulseaudio
21:57:42 <font color="#BF616A">[ERROR] </font>Couldn&apos;t read volume from alsa device with name &quot;pulseaudio&quot;.
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL pulseaudio
21:57:42 <font color="#BF616A">[ERROR] </font>Couldn&apos;t set volume: Error(&quot;snd_mixer_attach&quot;, Sys(ENOENT))
</pre>

What are valid alsa_audio_devices? I don't get it. Nothing I'm entering is working.

**Comment by SirWindfield** [comment]
First off, running `spotify —help` prints all available options to the terminal. Under backends you’ll find every backend that the binary supports. By default, that’s ALSA on Linux. It seems that you use pulseaudio, so you’d have to either recompile the bineaery yourself and specifying the pulseaudio_backend feature or correctly configure your ALSA device. The readme contains an example configuration file. There is mentioned what to use for the device and control fields. The readme also goes into detail on how to compile the binary yourself and enabling features during compilation.

**Comment by SirWindfield** [comment]
Just saw that we had a similar issue some time ago https://github.com/Spotifyd/spotifyd/issues/87. Make sure that you also specify the correct control device. It is usually the same as the device but in some cases it might differ.

**Comment by nickcorona** [comment]
Figured out what the issue was. Installed spotifyd from AUR instead of spotifyd-full which includes the feature for using `pulseaudio` as a backend.

Specifying `pulseaudio` as backend worked. Thanks.
