### ISSUE TITLE
How to run in discovery mode? 

### ISSUE THREAD

**Issue by juliangaal** [Spotifyd/spotifyd#373]
I came across this in #114 when trying to connect from different phones

> The simplest approach is to use discovery instead of username/password. That still only allows one user at a time to connect, but with some abuse ...
_Originally posted by @SimonPersson in https://github.com/Spotifyd/spotifyd/issues/114#issuecomment-375103720_

How exactly do i start spotifyd in discovery mode? Just leave out username and password? When running spotifyd with username/password, everything works perfectly, but without them no device (iOS, ubuntu desktop) finds the device spotifyd is running on

Thanks a lot!

**Comment by SirWindfield** [comment]
Yes, originally, running without a username/password would put the daemon into discovery mode and allow everybody on the same network to connect to it. That doesn't work as of lately. I think it's a change on Spotify's side. But I had no time to investigate it further.

**Comment by juliangaal** [comment]
aha! Thought I missed something in the docs. Maybe consider [my pr](https://github.com/Spotifyd/spotifyd/pull/375) for others with the same issue?

**Comment by SirWindfield** [comment]
See #366

**Comment by juliangaal** [comment]
Great, thanks for the fast help!
