### ISSUE TITLE
Only allow non-empty device names

### ISSUE THREAD

**Issue by juliangaal** [Spotifyd/spotifyd#378]
I was able to start and use `spotifyd` without a device name, while using user/password. It appears as *blank* in the spotify device list. Can/does this have any negative effects? 

Thanks

**Comment by SirWindfield** [comment]
By default it should use `Spotifyd@hostname`. Did you set the device_name field in the config to `device_name = `?

**Comment by juliangaal** [comment]
No, I'm ran with command line args, from within a script. By mistake I didn't set set device name, and used this **unitialized** bash variable `DEVICE_NAME` like so `spotifyd --device_name <DEVICE_NAME>`.

**Comment by SirWindfield** [comment]
Maybe [this](https://doc.rust-lang.org/std/option/enum.Option.html#method.filter) comes in handy:
```rust
let mut device_name = config 
     .shared_config 
     .device_name
	 .filter(|s| !s.is_empty())
     .unwrap_or_else(|| format!("{}@{}", "Spotifyd", gethostname().to_string_lossy()));
```

**Comment by juliangaal** [comment]
> Maybe [this](https://doc.rust-lang.org/std/option/enum.Option.html#method.filter) comes in handy:
> 
> ```rust
> let device_name = config 
>      .shared_config 
>      .device_name
> 	 .filter(|s| !s.is_empty())
>      .unwrap_or_else(|| format!("{}@{}", "Spotifyd", gethostname().to_string_lossy()));
> ```
Sweet! Gotta do some more rust in my free time...

> Got some free time on the weekend and will try to tackle this one down.
Sounds great! Have a good one

**Comment by juliangaal** [comment]
I'll try to commit the change before the end of the week, if you don't mind the help (although this bug is enhancement is very minor)

**Comment by SirWindfield** [comment]
Doesn't matter how large it is. If everybody who uses the software would commit one line we would probably have all enhancements and issues resolved :smile: I really appreciate the help. And no pressure, if you need two weeks it's fine too!

But remember, Hacktober doesn't last forever ;)

**Comment by juliangaal** [comment]
sounds great!
