### ISSUE TITLE
cli config option seems to be ignored

### ISSUE THREAD

**Issue by jagsta** [Spotifyd/spotifyd#38]
Firstly thanks for writing this, in general it's working great for me.

I have a problem with specifying a config file, it seems to ignore this option. If I name the config spotifyd.conf and place in either /etc/ or in $HOME/.config/spotifyd/ the log shows it finding and using the config file, any other name or location for the config with the -c or --config option results in "Couldn't find config file, continuing with default configuration."

I don't know rust but the config.rs seems to be using a constant "spotifyd.conf" and looking in either /etc/ or $HOME/.config/spotifyd/ for it.

**Comment by SimonPersson** [comment]
Hi!

Thank you, I'm glad it's working for you.

I can confirm your issue, I must have overlooked it. I have pushed a new commit, hopefully that should fix the issue. If not, feel free to reopen this issue.

**Comment by jagsta** [comment]
Thanks, that's now working as expected.
