### ISSUE TITLE
acknowledging contributors publicly

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#386]
We currently got quite a lot of PRs and I feel like some way of a acknowledging their contributions is a good idea. There are some projects that solely focus on this, for example [all-contributors](https://github.com/all-contributors/all-contributors).

The only con that I have might be a cluttered README if too many actually contribute. But that can be fixed by using a specific file like `CONTRIBUTORS.md`.

Integration is trivial, almost all tools have some kind of bot that can be used via commands to add people to the list. People can add themselves and the bot creates a PR that can be merged. 
It's a nice-to-have "feature".

Everybody, feel free to agree or disagree, I just want to get some opinions going :)

**Comment by slondr** [comment]
I definitely like the idea of having a write-only CONTRIBUTORS file that shows off the names of people who have contributed code.

**Comment by SirWindfield** [comment]
Done!
