### ISSUE TITLE
PortAudio write underflow

### ISSUE THREAD

**Issue by giovannigiordano** [Spotifyd/spotifyd#389]
Hi,
I have the following configuration and I have MacOS.
[global]
username = ****
password = *****
backend = portaudio
device - SoundPEATS TrueFree+ R
mixer = PCM
volume_controller = softvol
device_name = mac_daemon             
bitrate = 160                       
no_audio_cache = true              
volume_normalisation = true
normalisation_pregain = -10

When i try to play music, I can listen to the song I played but there are some strange sounds and there is the following error in output:
[ERROR] PortAudio write underflow

Another request, but I can open another issue, can you add a wiki for MacOS configuration? I would like to know how to avoid to change the device in the yml and picking it directly from the OS's default.

**Comment by SirWindfield** [comment]
Never ever encountered this error on my Mac. Does it happen on certain songs or after a certain amount of time? Underflowing generally means that no audio data is being send to the audio sink. Maybe it happens when no network is available.

I think this is currently not possible as the device gets set once at the start and doesn't change.

**Comment by giovannigiordano** [comment]
It happens always.

**Comment by Yarn** [comment]
These issues will likely be solved by the rodio backend (including using the default device, it won't switch after being started though). There is no CD for the rodio backend currently (so no release binary). If @SirWindfield wants I can add that.

I've attached a debug build incase you're into running binaries from strangers on the internet and want to try it (or you can build what's in master with `cargo build --features rodio_backend --no-default-features`). You'll need to pass `--backend rodio` or change the backend in your config.
[spotifyd_rodio.zip](https://github.com/Spotifyd/spotifyd/files/3748493/spotifyd_rodio.zip)

**Comment by SirWindfield** [comment]
@Yarn feel free to update the workflow file if you already have a working one for rodio as well! :)

**Comment by Yarn** [comment]
Nope, I never even installed the portaudio libs.

**Comment by Yarn** [comment]
Made a PR adding CD builds for mac builds with rodio, #406

**Comment by Yoelio** [comment]
I'm having this issue as well on my Mac with a short clipping noise on every portaudio write underflow. @giovannigiordano, did you end up resolving the issue?

**Comment by Yarn** [comment]
@Yoelio can you try one of the macos-rodio builds, those should work

**Comment by Yoelio** [comment]
@Yarn yup that did the trick!

**Comment by gugahoi** [comment]
Also had the same problem with underflow and noise clipping constantly and the rodio slim version seems to have fixed it. 

One thing I did notice is disconnecting a bluetooth headset makes the output move to the internal speakers as expected but upon reconnecting the headset I've been unable to use it as the output unless I restart spotifyd.

**Comment by Yarn** [comment]
> One thing I did notice is disconnecting a bluetooth headset makes the output move to the internal speakers as expected but upon reconnecting the headset I've been unable to use it as the output unless I restart spotifyd.

I'm fairly sure that would be a librespot or rodio issue. Afaik rodio doesn't handle switching devices so I would guess librespot but I'm not sure.
