### ISSUE TITLE
AMD64 Binary won't execute

### ISSUE THREAD

**Issue by hughwilliams94** [Spotifyd/spotifyd#39]
The binary file simply fails with: 'No such file or directory'. Happens on both an Ubuntu and Arch machine.

EDIT: COmpiling my own seems to work on Arch haven't yet tried on Ubuntu machine

**Comment by SimonPersson** [comment]
Thanks for this report! Something is indeed wrong here. I meant for the binary to be statically linked, but somehow it can't execute due to a linker problem. For now I suggest that you compile it by yourself, which should work, as you found by yourself.

**Comment by SimonPersson** [comment]
Binaries are no longer statically linked. This means that they still might not work on any system, but they seem to execute on my systems now at least.
