### ISSUE TITLE
Disable Volume Control & always play @ 100%

### ISSUE THREAD

**Issue by Ru1ah** [Spotifyd/spotifyd#391]
Hi,

Is there a way to disable Spotifyd´s Volume Control and make it always to play @ 100%? 
I definitely don´t want Spotify controls to modify my usb-sound cards volume, which it´s doing now.

**TL;DR Requesting similar feature as shairport-sync has for maximum alsa performance 
ignore_volume_control = "yes"; // set this to "yes" if you want the volume to be at 100% no matter what the source's volume control** 

These are the settings i have now in spotifyd.conf

backend = alsa
device = sysdefault:HD
control = hw:HD                          
mixer = PCM
volume_controller = alsa

If i comment out #mixer = PCM , i cannot change volume, but i get Errors.
11:58:39 [ERROR] Couldn't read volume from alsa device with name "hw:HD".
11:58:39 [ERROR] Couldn't set volume: "Couldn\'t find selem."
11:58:52 [ERROR] Couldn't set volume: "Couldn\'t find selem."
11:58:52 [ERROR] Couldn't set volume: "Couldn\'t find selem."
11:58:53 [ERROR] Couldn't set volume: "Couldn\'t find selem."
....

**Comment by SirWindfield** [comment]
I didn't dig too deep into this, but I think the volume control feature is part of the Spotify Connect protocol that is used to advertise the daemon as a speaker. Changing the volume on your phone changes the volume of the daemon. I do, however, am sure that the daemon volume is not the same as the system volume. If I understand you correctly, you could just crank up the volume through your phone or another device, which shouldn't affect your system volume.

If I understood the issue wrong, let me know :) I am not quite sure if I understood the usb card part right 🤔

**Comment by Ru1ah** [comment]
With those settings i pasted above if i stream spotify to spotifyd and change volume, it´s directly modifying my ALSA device volume settings, which i would like to lock these (below), as i control the volume on my pre-amp, not the usb dac.

Simple mixer control 'PCM',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right - Rear Left - Rear Right - Front Center - Woofer - Side Left - Side Right
  Limits: Playback 0 - 126
  Mono:
  Front Left: Playback 126 [100%] [0.00dB] [on]
  Front Right: Playback 126 [100%] [0.00dB] [on]
  Rear Left: Playback 0 [0%] [-63.00dB] [off]
  Rear Right: Playback 0 [0%] [-63.00dB] [off]
  Front Center: Playback 0 [0%] [-63.00dB] [off]
  Woofer: Playback 0 [0%] [-63.00dB] [off]
  Side Left: Playback 0 [0%] [-63.00dB] [off]
  Side Right: Playback 0 [0%] [-63.00dB] [off]

Not sure how pulseaudio helps, and i would really like to avoid unnecessary processing on the sound, maybe just getting the Error´s i the way forward?

**Comment by SirWindfield** [comment]
Can you show the output of `aplay -l`?

**Comment by Ru1ah** [comment]
Hi,

I think my initial configuration is correct, and as you said it expected Spotify Connect behavior. I setup just now shairport-sync ( https://github.com/mikebrady/shairport-sync ) to enable Airplay, and in those configurations there is a specific setting to totally ignore volume control, which is what i´m after, and do not know if it exists for Spotifyd.

Here are the settings i have for shairport and it works like a charm

general =
{
name = "%H";
output_backend = "alsa";
ignore_volume_control = "yes"; // set this to "yes" if you want the volume to be at 100% no matter what the source's volume control is set to.
};

alsa =
{
  output_device = "sysdefault:HD"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
  mixer_control_name = "PCM"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
  mixer_device = "hw:HD"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
};

**Comment by SirWindfield** [comment]
Out of curiosity, does PCH instead of PCM work for you? None of your cards actually mentions PCM, maybe it's some internal controller that modifies everything.

**Comment by Ru1ah** [comment]
Nope, 
mixer = PCH
19:09:52 [ERROR] Couldn't read volume from alsa device with name "hw:HD".
19:09:52 [ERROR] Couldn't set volume: "Couldn\'t find selem."
mixer = PCM
Works

**Comment by woftor** [comment]
On a Rpi I set "volume-control" to "softvol" if I want to control volume with my phone and I 
set it to "alsa" if I don't want that (volume control is disabled then)... that works for me.

**Comment by Ru1ah** [comment]
You probably have different setup, the alsa setup is modifying my usb dac volume, as you can see in the 3rd post.

**Comment by slondr** [comment]
I believe the default behavior mentioned by OP was rendered moot by #697, so I'm closing this.

If this is still an issue you want addressed please bump this issue
