### ISSUE TITLE
Spotifyd.service not launching 

### ISSUE THREAD

**Issue by Ru1ah** [Spotifyd/spotifyd#393]
Hi, 

I´m having troubles to get the spotifyd.service to work, to be able to launch the application on boot.

systemctl --user start spotifyd.service  <- Nothing happens
systemctl --user enable spotifyd.service  <- same story

spotifyd.service file copied as instructed here:
.config/systemd/user$ ls
default.target.wants  spotifyd.service

sudo nano spotifyd.service

[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/spotifyd --no-daemon
Restart=always
RestartSec=12

[Install]
WantedBy=default.target

I have MOST LIKELY done something wrong when i built it from source with this guide, i didn´t find a deb package :( https://github.com/Spotifyd/spotifyd/wiki/Installing-on-Ubuntu-%28from-source%29 
I need to manually launch it from here ./spotifyd/target/release/spotifyd

**Comment by SirWindfield** [comment]
The `Wants` and `After` lines specify after which other services spotifyd should start. Those targets are only available if you run it with the system bus. You used the `--user` flag, which moves the service launch to the user bus. Those targets are not available there.

You got two options from here on:

1) `sudo systemctl enable spotifyd.service`, which is totally fine to use.
2) Create your own targets called `network-online` and `sound`. You can probably get some scripts when googling for terms similar to `systemctl user network-online target`.

**Comment by Ru1ah** [comment]
Just followed the instructions, most likely no need to run it as --user.

This gives this the following error, i think i tried that yesterday as well, and should have mentioned it.
sudo systemctl start spotifyd.service
Failed to start spotifyd.service: Unit spotifyd.service not found.

**Comment by SirWindfield** [comment]
You need to move the service file to 
```
~/.config/systemd/system
```

**Comment by SirWindfield** [comment]
Or 
```
/etc/systemd/system
```

**Comment by SirWindfield** [comment]
I have to admit, stuff like this should be in the readme, therefore the refactoring mentioned in #395

**Comment by SirWindfield** [comment]
Systemd basically differentiates by the folder name whether the service is a system one or user one

**Comment by Ru1ah** [comment]
Moved the file to /etc/systemd/system, this other directory does not exist for me.
sudo systemctl start spotifyd.service 
processing for maybe 5secs, no error, but does not start the Spotifyd

**Comment by Ru1ah** [comment]
Maybe this helps for troubleshooting?
sudo systemctl status spotifyd.service
● spotifyd.service - A spotify playing daemon
   Loaded: loaded (/etc/systemd/system/spotifyd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-10-18 10:00:12 EEST; 9s ago
     Docs: https://github.com/Spotifyd/spotifyd
 Main PID: 894 (code=exited, status=203/EXEC)

spotifyd.service: Unit entered failed state.
spotifyd.service: Failed with result 'exit-code'.

**Comment by Ru1ah** [comment]
Hmm, there is no spotifyd in this directory /usr/bin/ that the service is pointing to :O  ExecStart=/usr/bin/spotifyd --no-daemon

Compared to my MPD it´s point here ExecStart=/usr/local/bin/mpd  
and the mpd is in that directory

**Comment by Ru1ah** [comment]
If i modify the spotiyd.service like below, i can start it, but not sure if this is correct way. 

[Service]
ExecStart=/home/username/spotifyd/target/release/spotifyd --no-daemon

**Comment by SirWindfield** [comment]
Yes it is. Our service file assumes that you copy the file to /usr/bin. You can do it like you did without problems.
I would just copy the spotifyd file to /usr/local/bin and set ExecStart to that path, e.g. /usr/local/bin/spotifyd. You can alle d your desired arguments then.

**Comment by SirWindfield** [comment]
I am investigating the possibilities to provide official distro packages through our CI infrastructure. In the future you could just use apt, PacMan or similar package managers to install Spotifyd.

**Comment by eyadsibai** [comment]
> You need to move the service file to
> 
> ```
> ~/.config/systemd/system
> ```

this won't work

**Comment by SirWindfield** [comment]
Is `~/.config/systemd/user` the only directory that would work there? My bad :)

**Comment by MEXdave1997** [comment]
So I'm not sure if this is still an ongoing issue, or if I'm missing something, but I have used the service file provided in `contrib/spotifyd.service`, and it still refuses to launch (the service file is in the second location listed in the README, btw).

If this helps, I have actually tried manually launching spotifyd from the terminal (`spotifyd --no-daemon`), and it experiences this error:

```
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }
```

**Comment by morpheusthewhite** [comment]
Hi, I also found this error when launching the service as a user one

```
● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/usr/lib/systemd/user/spotifyd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-03-28 09:56:28 CET; 4>
       Docs: https://github.com/Spotifyd/spotifyd
    Process: 28973 ExecStart=/usr/bin/spotifyd --no-daemon (code=exited, status=101)
   Main PID: 28973 (code=exited, status=101)

Mar 28 09:56:28 mtwarch systemd[1354]: spotifyd.service: Changed running -> failed
Mar 28 09:56:28 mtwarch systemd[1354]: spotifyd.service: Unit entered failed state.
Mar 28 09:56:28 mtwarch systemd[1354]: spotifyd.service: Changed failed -> auto-restart
Mar 28 09:56:28 mtwarch systemd[1354]: spotifyd.service: Control group is empty.
```

But I was able to solve it by copying the service to `/etc/systemd/system`, enabling and starting it. 

Note: I am running Arch Linux and installed `spotifyd` through the AUR

**Comment by JohanAke1** [comment]
> EDIT: To add more detail, I am running this on an Archlinux system, running kernel 5.5.11, installed with yay from the AUR (since that seems to be the only place spotifyd is available on Arch), and have added my username and password to the config file.

A bit late, but if there is people with this problem, the solution might be to comment out the proxy in the spotifyd.conf file.

**Comment by eeneg** [comment]
> > So I'm not sure if this is still an ongoing issue, or if I'm missing something, but I have used the service file provided in `contrib/spotifyd.service`, and it still refuses to launch (the service file is in the second location listed in the README, btw).
> > If this helps, I have actually tried manually launching spotifyd from the terminal (`spotifyd --no-daemon`), and it experiences this error:
> > ```
> > Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }
> > ```
> > 
> > 
> > EDIT: To add more detail, I am running this on an Archlinux system, running kernel 5.5.11, installed with yay from the AUR (since that seems to be the only place spotifyd is available on Arch), and have added my username and password to the config file.
> 
> A bit late, but if there is people with this problem, the solution might be to comment out the proxy in the spotifyd.conf file.

Thank you very much

**Comment by andersfylling** [comment]
I can say that this is a still a issue. I felt fairly confused why spotifyd wouldn't start, and why my service file was not found. Even when placed in the directories specified in the README.

System: arch linux

**Comment by andersfylling** [comment]
I can also confirm that there is no issue if the file is moved to `/etc/systemd/system/` and ran under sudo.

**Comment by andersfylling** [comment]
Another update:
placing the file in `.config/systemd/user/` and running `systemctl --user enable spotifyd --now
`, sets up the symlink and allows systemctl to run it.


It however fails, here is the log:
```
➜ journalctl -u spotifyd
-- Logs begin at Thu 2019-07-18 17:56:12 CEST, end at Mon 2020-11-16 23:49:15 CET. --
nov. 16 23:39:38 anders-i3 systemd[1]: Started A spotify playing daemon.
nov. 16 23:39:38 anders-i3 spotifyd[88962]: No config file specified. Running with default values
nov. 16 23:39:38 anders-i3 spotifyd[88962]: No proxy specified
nov. 16 23:39:38 anders-i3 spotifyd[88962]: Using software volume controller.
nov. 16 23:40:47 anders-i3 systemd[1]: Stopping A spotify playing daemon...
nov. 16 23:40:47 anders-i3 systemd[1]: spotifyd.service: Succeeded.
nov. 16 23:40:47 anders-i3 systemd[1]: Stopped A spotify playing daemon.
```

**Comment by andersfylling** [comment]
Okay, updating the service file to point to my config file fixed this. Would be great if the log would display this as the issue though.

**Comment by tbjgolden** [comment]
Changed my service file to be like yours, had the same result

Service running now, but spotify-tui not seeing it

**Comment by Adam-Kadmon** [comment]
Same problem, finally got spotifyd running but now it's not showing up in spotify-tui. Official Android client sees my spotifyd device but can't play from it.

Arch Linux running LTS kernel with everything up to date. Installed spotifyd from repo.

**Comment by joaofl** [comment]
I also have problems when running spotifyd as a service on a Debian embedded (armbian).  It crashes a second after I try to connect with it on my phone. It fails to initialize DBus it seems. Any clues?
(Works just fine when I run it on foreground)

`journalctl -u spotifyd`

```
Mar 13 14:34:46 musicbox spotifyd[9177]: Connecting to AP "gew1-accesspoint-e-wj86.ap.spotify.com:443"
Mar 13 14:34:46 musicbox spotifyd[9177]: Authenticated as "user" !
Mar 13 14:34:46 musicbox spotifyd[9177]: Country: "BR"
Mar 13 14:34:46 musicbox spotifyd[9177]: Using alsa sink
Mar 13 14:34:46 musicbox spotifyd[9177]: Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
Mar 13 14:34:46 musicbox systemd[1]: spotifyd.service: Main process exited, code=exited, status=101/n/a
Mar 13 14:34:46 musicbox systemd[1]: spotifyd.service: Failed with result 'exit-code'.
Mar 13 14:34:59 musicbox systemd[1]: spotifyd.service: Scheduled restart job, restart counter is at 1.
Mar 13 14:34:59 musicbox systemd[1]: Stopped A spotify playing daemon.
Mar 13 14:34:59 musicbox systemd[1]: Started A spotify playing daemon.
Mar 13 14:34:59 musicbox spotifyd[9190]: No config file specified. Running with default values
Mar 13 14:34:59 musicbox spotifyd[9190]: No proxy specified
Mar 13 14:34:59 musicbox spotifyd[9190]: Using software volume controller.
Mar 13 14:35:08 musicbox spotifyd[9190]: Connecting to AP "gew1-accesspoint-e-k1dg.ap.spotify.com:443"
Mar 13 14:35:08 musicbox spotifyd[9190]: Authenticated as "user" !
```

**Comment by UdittLamba** [comment]
> You need to move the service file to
> 
> ```
> ~/.config/systemd/system
> ```

the docs were saying to move it to  ~/.config/systemd/user and that had me hella confused.
