### ISSUE TITLE
Installing on Ubuntu (from source) - compile errors

### ISSUE THREAD

**Issue by martinbrennan** [Spotifyd/spotifyd#396]
I followed your instructions to install on Ubuntu on two different Linux machines and both generate errors in the crate build step. First error was compiling percent-encoding. Martin

https://github.com/Spotifyd/spotifyd/wiki/Installing-on-Ubuntu-%28from-source%29

**Comment by SirWindfield** [comment]
First off, it is way easier if you can provide more information on how you compiled the binary and on what system exactly.

Could you add the following information? OS version (18.04, 16.04 etc.), Rust version, commit/branch used as well as the log of the compiling process.

Second, if you don't want to compile the binary, just grab `spotifyd-linux-full` from the release section and you are good to go.

I think Ubuntu has an older version of Rust in their repository which fails to compile this project. It may work if get the installer from https://rustup.rs

**Comment by martinbrennan** [comment]
Hi SirWindfield
Thank you for the quick reply. It was the Rust compiler version that was the problem.
apt-get installed versions 1.28.1 and 1.31.0 on my two machines and neither compiled this code.
https//rustup.rs installed version 1.38.0 and that compiled OK
(I had to remove the old version with sudo apt-get remove rustc in case anybody else encounters this)
Thanks again.
Martin
