### ISSUE TITLE
Artist/Track Information

### ISSUE THREAD

**Issue by postacey** [Spotifyd/spotifyd#40]
Thank you for your work on this, it is working well for me on a Raspberry Pi 3. I would like to display artist and track information on an LCD but I can't find any way of getting this. Would it be possible to have something like the mpc --format option to allow a script to get the metadata in a defined format? Or alternatively just export the data for the current track to a text file where it could be read by another script?
Many thanks
Peter

**Comment by SimonPersson** [comment]
That sounds like a cool project!

My intention is for Spotifyd to just play music, and for [spotifyd-http](https://github.com/Spotifyd/spotifyd-http) to be the user interfacing API. In your case, you should be able to get the information you need by running spotifyd-http along with spotifyd and polling http://localhost:6767/device_id/tracks, then using the Spotify web API to get whatever metadata you want for the tracks.

I'll close this issue, feel free to open a new issue in spotifyd-http if there is something missing to solve your problem.

**Comment by postacey** [comment]
Ok, thank you, I'll try and get that to work. As spotifyd already logs the
track title on starting to play I thought there might be a simpler way. I'm
only really interested in artist, track title and album title.
