### ISSUE TITLE
Add Support For TRX

### ISSUE THREAD

**Issue by unmanagedtn** [Spotifyd/spotifyd#401]
I am trying to get TRX working to do whole house audio and would be a neat feature to add.... I have to use the alsa-loop module and am having a bit of issues with its use but its a PEBCAK or PICNIC issue as spotifydit is working great on a VIA Artigo a1150 unit with Debian...

[http://www.pogo.org.uk/~mark/trx/](url)
[http://www.pogo.org.uk/~mark/trx/streaming-desktop-audio.html](url)

**Comment by SirWindfield** [comment]
As far as I can tell from the second link, it seems that it re-directs the ALSA output. I don't think that we have to implement something special here. Maybe I'm just not understanding how this works though...

**Comment by unmanagedtn** [comment]
It uses the opus codec to transmit audio over the network. If you set it up
to do multicast you could have speakers located on the network that would
just receive audio just by powering them on ... and have multi room
networked audio  ... and yes it is taking redirected alsa output and
sending it via UDP over a private network to one host or many via
multicast.... :)
