### ISSUE TITLE
Can't play podcasts

### ISSUE THREAD

**Issue by noir-Z** [Spotifyd/spotifyd#407]
The Android app just says "Can't play this right now".
This only happens with podcasts, music plays just fine.

**Comment by SirWindfield** [comment]
https://github.com/librespot-org/librespot/issues/90

Might be an API change again. It worked for some time though.

**Comment by SirWindfield** [comment]
Looks like it still does work on their side. Which podcast did you try out? Which android client version do you use? And which daemon version from the release page do you use?

**Comment by noir-Z** [comment]
Hi, i haven't found a working podcast so far but you can try to reproduce it with "Fest & Flauschig". On Android I use version 8.5.27.957 and the version of the daemon is 0.2.18 since that is the version of the AUR package.

**Comment by SirWindfield** [comment]
Looks like it is probably an API change. Librespot, the underlying library, has to update its protocols to have this working again.

**Comment by noir-Z** [comment]
Idk if this is important but i just want to mention that i have a wifi speaker that supports connect and podcasts work with it.

**Comment by stevensonmt** [comment]
https://github.com/spotify/web-api/issues/551

Suggests that the web api was not intended to make the podcast endpoints available.

**Comment by Aimmig** [comment]
> [spotify/web-api#551 (comment)](https://github.com/spotify/web-api/issues/551#issuecomment-486898766)
> Suggests that the web api was not intended to make the podcast endpoints available.

This thread has been updated & it seems like there's an (unoffical?) documentation for this endpoint which might worth looking into
https://github.com/spotify/web-api/issues/551#issuecomment-583748908

**Comment by Zadagu** [comment]
I had the same problem and found a workaround.
First play music and switch to your spotfiyd device.
Then start the podcast you want to listen. -> The podcast should now be played back by spotfiyd.
