### ISSUE TITLE
Help on config

### ISSUE THREAD

**Issue by sdomotica** [Spotifyd/spotifyd#41]
Where I can find how fill these parameters?
onstart = command_run_on_playback_start
onstop = command_run_on_playback_stop
Thks
Sandro

**Comment by joerg-krause** [comment]
https://github.com/plietar/librespot/commit/1d3c387fed809240c002f04cfe11175c26f8d83f

For example:
onstart = "/usr/bin/logger -t librespot Starting playback"
onstop = "/usr/bin/logger -t librespot Stopping playback"

**Comment by SimonPersson** [comment]
What @joerg-krause suggested should work, so I will close this. Feel free to reopen if you still have issues!
