### ISSUE TITLE
Ubuntu source install creates non-working executable

### ISSUE THREAD

**Issue by cramermarius** [Spotifyd/spotifyd#414]
I followed the project's link for Ubuntu source install closely and the compilation worked flawlessly. Afterwards I tried to execute the file created from the compilation but it threw the following error. I looked around in the existing issues but didn't find anything resembling my issue. If there is one and I missed it, my apologies. 
Here is the error message:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("INI syntax error: variable assignment missing \'=\'")', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

edit:
OS: popOS 19.04
version: the latest github repo, no singular release. I followed your 'Compile on Ubuntu'-wiki.
log for ./spotifyd --no-daemon
`08:30:49 [INFO] Loading config from "/etc/xdg/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("INI syntax error: variable assignment missing \'=\'")', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`
config: I never made one and didn't have any in the file tree either.
I also tried downloading the Linux 'Full' binary, but for some reason I couldn't get make it executable.

**Comment by SirWindfield** [comment]
Hey @cramermarius!

Could you provide more information to make it easier to help you out? I've created an issue template for that :)

Just edit your previous message and add the following information to it: OS, spotifyd version, the full log when running spotifyd using `spotifyd --no-daemon <your other flags>` and your config file (make sure to delete password/username or other information if you don't want us to have them :))

**Comment by cramermarius** [comment]
I fixed the issue for my system. I followed some instructions on [here](https://blog.katriel.co.uk/spotifyd). Consider adding the install (`cargo install --path .`) documentation to your 'Compile on Ubuntu (from Source)'-wiki article. Thank you for your help, this can be closed.
