### ISSUE TITLE
Wrong verison number in release binary

### ISSUE THREAD

**Issue by deisi** [Spotifyd/spotifyd#415]
I think there is something wrong with the release binary. Latest release currently points to [v.2.19](https://github.com/Spotifyd/spotifyd/releases/tag/v0.2.19). But if you download e.g. spotifyd-linux-full.tar.gz and call `spotifyd --version` it will say: `spotifyd 0.2.18`

**Comment by SirWindfield** [comment]
Yep, I forgot to update it. Thanks!
