### ISSUE TITLE
spotifyd panic after build

### ISSUE THREAD

**Issue by ssleifjsldifje** [Spotifyd/spotifyd#419]
**Description**
Cannot start spotifyd with or without passing configuration after build with cargo (thread panic)

**To Reproduce**
- start spotifyd

**Expected behavior**
- spotify should start normally and run as a service

**Logs**

1. panic when starting spotifyd
<details><summary>Click to show logs</summary>
$ ./spotifyd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: librespot_core::cache::Cache::new
  12: spotifyd::config::get_internal_config
  13: spotifyd::main
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  18: std::panicking::try
             at src/libstd/panicking.rs:275
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</details>

2. output with rust_backtracke=full environment

<details><summary>Click to show logs</summary>
./spotifyd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x5585a14d31eb - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5585a14d31eb - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5585a14d31eb - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5585a14d31eb - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5585a14d31eb - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5585a14d2ec6 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5585a14d395d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5585a14d34e2 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5585a14d33c6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5585a14f4e4d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x5585a14f4f47 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x5585a11d3ba2 - librespot_core::cache::Cache::new::h1a34fda4a5c8a96f
  12:     0x5585a1082b46 - spotifyd::config::get_internal_config::hffaed3a3d1e03599
  13:     0x5585a108c398 - spotifyd::main::hf5ebc5a2a3018f9c
  14:     0x5585a106a9e3 - std::rt::lang_start::{{closure}}::h5fa234662e5f696c
  15:     0x5585a14d3363 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  16:     0x5585a14d3363 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  17:     0x5585a14dccba - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  18:     0x5585a14d3e6d - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  19:     0x5585a14d3e6d - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  20:     0x5585a14d3e6d - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  21:     0x5585a108c9b2 - main
  22:     0x7f4bbdf1ab97 - __libc_start_main
  23:     0x5585a1055dfa - _start
  24:                0x0 - <unknown>
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Spotifyd:    0301e29..d8efb31  master     -> origin/master
- cargo: cargo 1.38.0 (23ef9a4ef 2019-08-20)

**Comment by Yarn** [comment]
It looks like it's related to the cache, can you make sure path to the cache is correct and everything in the path but the cache folder itself exists? If that doesn't work try running it with the `--no-audio-cache` param.

https://github.com/librespot-org/librespot/blob/551daadc44a39336e1c643d1e300d38cdd8426d5/core/src/cache.rs#L29

**Comment by SirWindfield** [comment]
Yes, NoSuchFile is 100% cache related. Most likely the folder has not been created.

**Comment by SirWindfield** [comment]
I’ll close it for now as you didn’t provide any feedback and I’ll just assume that it works again :)

**Comment by ssleifjsldifje** [comment]
hi - sorry for the delay, i was absent. 

your solution was right ! i run into the error because i used the old flag "-c" for config file. now with new flags it works !

again -thanks for the info !
