### ISSUE TITLE
Stop working after 5 songs

### ISSUE THREAD

**Issue by sdomotica** [Spotifyd/spotifyd#42]
I tried the compiled version on my RPI3 untagged-8d1809f9710e3af4cda7
And after 5 songs (or 5 playlist or 5 next) managed with official iOs app, the server stop working.
What should test for identify the problem?
Bye
Sandro

**Comment by SimonPersson** [comment]
Try to run with `--no-daemon` and `-v` and upload the output to pastebin or something and I will take a look at it.

**Comment by sdomotica** [comment]
I think is a librespot issue, I tried librespot too with the same issue. 
Here the log
22:39:52 [DEBUG] eventual::core: Core::consumer_await
22:39:52 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=ProducerWait] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - notifying producer
22:39:52 [DEBUG] eventual::core: Core::notify_producer
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - Invoking producer; state=State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::future: Complete::poll; is_ready=true
22:39:52 [DEBUG] eventual::core: Core::producer_poll; state=State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=New] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - Producer invoked; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_await - parking thread
22:39:52 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:52 [DEBUG] eventual::core:   - notifying consumer
22:39:52 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=true; producing=false; lifecycle=Ready]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=true; producing=false; lifecycle=Ready] to State[count=1; consuming=true; producing=false; lifecycle=New] (consuming value)
22:39:52 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:52 [DEBUG] eventual::core:   - notifying consumer
22:39:52 [DEBUG] eventual::core: Core::consumer_await - unparking thread
22:39:52 [DEBUG] eventual::core:   - consumer notified
22:39:52 [DEBUG] eventual::core:   - consumer notified
22:39:52 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=Ready] to State[count=1; consuming=false; producing=false; lifecycle=New] (consuming value)
22:39:52 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 80
22:39:52 [DEBUG] librespot::audio_file2: Got channel 80
22:39:52 [DEBUG] eventual::core: Core::producer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=New] to State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core: Core::producer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=New] to State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=ProducerWait] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - notifying producer
22:39:52 [DEBUG] eventual::core: Core::notify_producer
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - Invoking producer; state=State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::future: Complete::poll; is_ready=true
22:39:52 [DEBUG] eventual::core: Core::producer_poll; state=State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=New] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - Producer invoked; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_await
22:39:52 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=ProducerWait]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=ProducerWait] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - notifying producer
22:39:52 [DEBUG] eventual::core: Core::notify_producer
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - Invoking producer; state=State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::future: Complete::poll; is_ready=true
22:39:52 [DEBUG] eventual::core: Core::producer_poll; state=State[count=1; consuming=false; producing=true; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:52 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=New] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core:   - Producer invoked; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:52 [DEBUG] eventual::core: Core::consumer_await - parking thread
22:39:53 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:53 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:53 [DEBUG] eventual::core:   - notifying consumer
22:39:53 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=true; producing=false; lifecycle=Ready]
22:39:53 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=true; producing=false; lifecycle=Ready] to State[count=1; consuming=true; producing=false; lifecycle=New] (consuming value)
22:39:53 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:53 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:53 [DEBUG] eventual::core:   - notifying consumer
22:39:53 [DEBUG] eventual::core: Core::consumer_await - unparking thread
22:39:53 [DEBUG] eventual::core:   - consumer notified
22:39:53 [DEBUG] eventual::core:   - consumer notified
22:39:53 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:53 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=Ready] to State[count=1; consuming=false; producing=false; lifecycle=New] (consuming value)
22:39:53 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 81
22:39:53 [DEBUG] librespot::audio_file2: Got channel 81
22:39:53 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 82
22:39:53 [DEBUG] librespot::audio_file2: Got channel 82
22:39:53 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 83
22:39:53 [DEBUG] librespot::audio_file2: Got channel 83
22:39:53 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 84
22:39:53 [DEBUG] librespot::audio_file2: Got channel 84
22:39:53 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 85
22:39:53 [DEBUG] librespot::audio_file2: Got channel 85
22:39:53 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 86
22:39:53 [DEBUG] librespot::audio_file2: Got channel 86
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:54] error: 4 0
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 87
22:39:54 [DEBUG] librespot::audio_file2: Got channel 87
22:39:54 [INFO] Running /usr/bin/logger -t librespot Starting playback
22:39:54 [INFO] Exit status: exit code: 0
22:39:54 [DEBUG] eventual::core: Core::consumer_ready; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:54 [DEBUG] eventual::core: Core::consumer_wait; state=State[count=0; consuming=false; producing=false; lifecycle=New]
22:39:54 [DEBUG] eventual::core:   - transitioned from State[count=0; consuming=false; producing=false; lifecycle=New] to State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]
22:39:54 [INFO] Load Done
22:39:54 [DEBUG] librespot::spirc: kMessageTypeNotify "Sdomotica" d8538f9f09YYYYYYYYYYYYYYYYYYYb3a4a46a 10 1489531194140
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 88
22:39:54 [DEBUG] librespot::audio_file2: Got channel 88
22:39:54 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:54 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:54 [DEBUG] eventual::core:   - notifying consumer
22:39:54 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=true; producing=false; lifecycle=Ready]
22:39:54 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=true; producing=false; lifecycle=Ready] to State[count=1; consuming=true; producing=false; lifecycle=New] (consuming value)
22:39:54 [DEBUG] eventual::core:   - consumer notified
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 89
22:39:54 [DEBUG] librespot::audio_file2: Got channel 89
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 90
22:39:54 [DEBUG] librespot::audio_file2: Got channel 90
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 91
22:39:54 [DEBUG] librespot::audio_file2: Got channel 91
22:39:54 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 92
22:39:54 [DEBUG] librespot::audio_file2: Got channel 92
22:39:55 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 93
22:39:55 [DEBUG] librespot::audio_file2: Got channel 93
22:39:55 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 94
22:39:55 [DEBUG] librespot::audio_file2: Got channel 94
22:39:55 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 95
22:39:55 [DEBUG] librespot::audio_file2: Got channel 95
22:39:55 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 96
22:39:55 [DEBUG] librespot::audio_file2: Got channel 96
22:39:55 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 97
22:39:55 [DEBUG] librespot::audio_file2: Got channel 97
22:39:56 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 98
22:39:56 [DEBUG] librespot::audio_file2: Got channel 98
22:39:56 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 99
22:39:56 [DEBUG] librespot::audio_file2: Got channel 99
22:39:56 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 100
22:39:56 [DEBUG] librespot::audio_file2: Got channel 100
22:39:56 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 101
22:39:56 [DEBUG] librespot::audio_file2: Got channel 101
22:39:56 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 102
22:39:56 [DEBUG] librespot::audio_file2: Got channel 102
22:39:57 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 103
22:39:57 [DEBUG] librespot::audio_file2: Got channel 103
22:39:57 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 104
22:39:57 [DEBUG] librespot::audio_file2: Got channel 104
22:39:57 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 105
22:39:57 [DEBUG] librespot::audio_file2: Got channel 105
22:39:57 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 106
22:39:57 [DEBUG] librespot::audio_file2: Got channel 106
22:39:57 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 107
22:39:57 [DEBUG] librespot::audio_file2: Got channel 107
22:39:58 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 108
22:39:58 [DEBUG] librespot::audio_file2: Got channel 108
22:39:58 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 109
22:39:58 [DEBUG] librespot::audio_file2: Got channel 109
22:39:58 [DEBUG] librespot::spirc: kMessageTypeNext "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 11 0
22:39:58 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 110
22:39:58 [DEBUG] librespot::audio_file2: Got channel 110
22:39:58 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 111
22:39:58 [DEBUG] librespot::audio_file2: Got channel 111
22:39:59 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 112
22:39:59 [DEBUG] librespot::audio_file2: Got channel 112
22:39:59 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 113
22:39:59 [DEBUG] librespot::audio_file2: Got channel 113
22:39:59 [TRACE] librespot::stream: [/home/pi/.cargo/git/checkouts/librespot-88dc5c33d49326b7/aa499e0/src/stream.rs:125] allocated stream 114
22:39:59 [DEBUG] librespot::audio_file2: Got channel 114
22:39:59 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:59 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:59 [DEBUG] eventual::core:   - notifying consumer
22:39:59 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=true; producing=false; lifecycle=Ready]
22:39:59 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=true; producing=false; lifecycle=Ready] to State[count=1; consuming=true; producing=false; lifecycle=New] (consuming value)
22:39:59 [DEBUG] eventual::core: Core::complete; state=State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait]; success=true; last=true
22:39:59 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=false; producing=false; lifecycle=ConsumerWait] to State[count=1; consuming=false; producing=false; lifecycle=Ready]
22:39:59 [DEBUG] eventual::core:   - notifying consumer
22:39:59 [DEBUG] eventual::core: Core::consumer_poll; state=State[count=1; consuming=true; producing=false; lifecycle=Ready]
22:39:59 [DEBUG] eventual::core:   - transitioned from State[count=1; consuming=true; producing=false; lifecycle=Ready] to State[count=1; consuming=true; producing=false; lifecycle=New] (consuming value)
22:39:59 [DEBUG] eventual::core:   - consumer notified
22:39:59 [DEBUG] eventual::core:   - consumer notified
22:40:03 [DEBUG] librespot::spirc: kMessageTypeNext "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 12 0
22:40:06 [DEBUG] librespot::spirc: kMessageTypeNext "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 13 0
22:40:08 [DEBUG] librespot::spirc: kMessageTypePrev "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 14 0
22:40:10 [DEBUG] librespot::spirc: kMessageTypePrev "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 15 0
22:40:11 [DEBUG] librespot::spirc: kMessageTypePrev "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 16 0
22:40:15 [DEBUG] librespot::spirc: kMessageTypeHello "iPhone6Plus" 84698XXXXXXXXXXXXXXXXXXXXX1627e4c9 58 1489531194140

**Comment by sdomotica** [comment]
I uninstalled Pulseaudio and the problem has been solved. 
Please close this issue.
Bye
Sandro

**Comment by SimonPersson** [comment]
Great!
