### ISSUE TITLE
Latest ARM build

### ISSUE THREAD

**Issue by er0k** [Spotifyd/spotifyd#425]
I noticed there is no official ARM build for v0.2.20 on the [releases](https://github.com/Spotifyd/spotifyd/releases) page :cry:

Maybe it is an issue with the CD workflow?

**Comment by er0k** [comment]
I tried compiling myself on a Pi but I couldn't get it to build, using Raspbian buster:

```
$ uname -srm
Linux 4.19.75+ armv6l

$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)

$ cargo --version
cargo 1.38.0 (23ef9a4ef 2019-08-20)

$ git show --summary
commit c1afcda5205ddff38d0d84588484afa662dea88e (HEAD -> master, tag: v0.2.20, origin/master, origin/HEAD)
Author: Sven Lechner <SirWindfield@users.noreply.github.com>
Date:   Sun Nov 3 16:53:48 2019 +0100

    bump version to v0.2.20

$ cargo build --release                                                                                                         
   Compiling semver-parser v0.7.0
error: Could not compile `semver-parser`.

Caused by:
  process didn't exit successfully: `rustc --crate-name semver_parser /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.7.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=d61c05a509e7bd82 -C extra-filename=-d61c05a509e7bd82 --out-dir /home/pi/spotifyd/target/release/deps -L dependency=/home/pi/spotifyd/target/release/deps
--cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by SirWindfield** [comment]
Yep, I noticed that the build failed but I have no clue why. It might be that some library needs a bump. Not sure in what changelogs I've read it but someone mentioned that they had to bump libc to make it compile on ARM again. This is probably happening here :(

**Comment by er0k** [comment]
I used the workaround mentioned in https://github.com/rust-lang/rust/issues/62896#issue-471671543 and added the following to Cargo.toml

```
[profile.release]
codegen-units = 1
```

I'm new to rust and that thread is a bit over my head, but this seems to at least get past the previous error and it is now compiling... I'll update in a bit if it finishes successfully

**Comment by boisei0** [comment]
I don't know if this is relevant or will help, but I just succeeded in building 0.20.0 on ARM64 (aarch64). Sounds like an issue specific to the other ARM architectures. Here's my set up:
```
$ uname -srm 
Linux 5.3.0-1012-raspi2 aarch64
$ rustc --version
rustc 1.39.0 (4560ea788 2019-11-04)
$ cargo --version
cargo 1.39.0 (1c6ec66d5 2019-09-30)
$ git show --summary
commit c1afcda5205ddff38d0d84588484afa662dea88e (HEAD -> master, tag: v0.2.20, origin/master, origin/HEAD)
Author: Sven Lechner <SirWindfield@users.noreply.github.com>
Date:   Sun Nov 3 16:53:48 2019 +0100

    bump version to v0.2.20
```
Not a single error or warning appeared during compiling. Running on ubuntu server 19.10, arm64, on a Pi 4 4gb edition.

**Comment by er0k** [comment]
Looks like this was fixed upstream. I did `rustup update` to get the same version of rustc/cargo as @boisei0 and now I can build on ARMv7 without the workaround I mentioned above :tada:

**Comment by SirWindfield** [comment]
perfect. Glad that it works again!

**Comment by er0k** [comment]
@SirWindfield assuming this was the problem with the CD workflow not building the latest ARM binary for the releases page, if you kick off a new workflow now, it should fix that, right?

**Comment by SirWindfield** [comment]
I started the builds again but IIRC they will always checkout the commit that triggered them, meaning that a fix wouldn't be applied to them. However, in the case of the ARM builds this shouldn't be a problem.

**Comment by bjo81** [comment]
What about ARM builds for 0.2.23?
