### ISSUE TITLE
`password_cmd` with 1Password CLI tool fails

### ISSUE THREAD

**Issue by alichtman** [Spotifyd/spotifyd#428]
I have this line in my `~/.config/spotifyd/spotifyd.conf` file.

`password_cmd = "op get item Spotify | jq -r '.details.fields[1].value'"`

This command prints my Spotify password, stored in 1Password, to stdout.

```bash
$ spotifyd --no-daemon
07:32:17 [INFO] Loading config from "/Users/alichtman/.config/spotifyd/spotifyd.conf"
07:32:17 [INFO] No password specified. Checking password_cmd
07:32:17 [INFO] Running "\"op get item Spotify | jq -r \'.details.fields[1].value\'\"" using "/usr/local/bin/zsh"
07:32:17 [ERROR] Failed to execute "\"op get item Spotify | jq -r \'.details.fields[1].value\'\"" using "/usr/local/bin/zsh". Error: Failed to execute "\"op get item Spotify | jq -r \'.details.fields[1].value\'\"" using "/usr/local/bin/zsh". Error: zsh:1: command not found: op get item Spotify | jq -r '.details.fields[1].value'

07:32:17 [INFO] Using software volume controller.
07:32:17 [WARN] Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
07:32:17 [ERROR] No password found.
```

Here is the error that I'm receiving. Am I doing something incorrectly?

I'm using `spotifyd 0.2.20` version from the `macos-full` prebuilt binary on macOS 10.14.6.

**Comment by alichtman** [comment]
I've got this part of the process working with `pass`, but I don't really want to have two separate password managers...

**Comment by SirWindfield** [comment]
The double quotes should not be added as INI assumes everything is a string in the first place.

No idea if that fixes it though. I always thought that shells init themselves if called and read the needed profile files. It sounds like op is a function/alias you've written and zsh doesn't know it when called. Or maybe a binary that gets added to the path in your zshrc or profile file.

**Comment by alichtman** [comment]
`op` is a binary on my path. No aliases are used in that line. Removing the quotes does not fix the issue.

It's authenticating with my workaround, but this is still an issue.

**Comment by SirWindfield** [comment]
Looks like the cmd is interpreted as one single command and not two that are piped together.

**Comment by alichtman** [comment]
@SirWindfield

**Comment by SirWindfield** [comment]
Note: `/bin/sh -c` and `cmd.exe /C`
