### ISSUE TITLE
Crash From Tilde Characters in Paths

### ISSUE THREAD

**Issue by DavidBittner** [Spotifyd/spotifyd#429]
**Description**
If any supplied paths use tilde instead of manually specifying the home directory (I.E. `~/.cache/spotifyd` instead of `/home/<username>/.cache/spotifyd`) then the files will not be able to be opened. In the case of the audio cache, this causes the program to panic. This panic is located in the `get_internal_config` function at line 503 of `config.rs`.

This is because if you pass a PathBuf to `librespot::core::cache::Cache::new` and that path cannot contains a character such as the tilde character, spotifyd will panic due to an unwrap in `librespot` at line 30 of `librespot/core/cache.rs`. I will file an issue there as well, to maybe get this fixed, but it seems they knowingly unwrap there as the function does not even return a result.

Either way, that's the problem, from what I could figure out.

**To Reproduce**
1. Create the default config file
2. Set the audio cache path to something containing a tilde
3. Make sure the audio cache does not exist.

As a side note, this can also be done by setting the config file path with a command line arg and passing a path with the tilde in it as well. With this, there is no panic but the error could give some more info. It says:
`Failed to open config file at {:?}, err was: {}.`

**Expected behavior**
A non-panic for the audio cache path (maybe by just making sure it exists before it's passed to librespot), and a better error message so we can see why it's actually failing to open it. This could happen with wrong permissions as well.

**Logs**
<details><summary>Click to show logs</summary>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Arch Linux 5.3.8-arch1-1
 - Spotifyd: 0.2.19-1
- cargo: `cargo 1.40.0-nightly (5da4b4d47 2019-10-28)`

**Comment by SirWindfield** [comment]
Yup. I think there was a method on path called relativize or something that actually expands the path. But this is, as for now, intentional behavior. Filing an issue over there might get it fixed.

**Comment by SirWindfield** [comment]
BTW, it is mentioned in the readme file under the configuration section where each config key has a description :)

**Comment by DavidBittner** [comment]
That's fair. That's filesystem stuff is a little lacking in that regard imo. Could the panic from librespot be avoided though? Took me a while to realize what was actually wrong.

**Comment by Yarn** [comment]
It's worth noting that most programs don't do path expansion, usually only shells do, and only sometimes (e.g. bash doesn't expand ~ in single or double quotes). Paths can contain "~" so just always expanding it isn't really a great solution.

Fixing the error message is probably not hard though (or checking for the folder before calling librespot).

**Comment by SirWindfield** [comment]
@Yarn a better error message is probably the way to go.
