### ISSUE TITLE
Build fails. Possible due to conflicting version of `syntex_syntax`.

### ISSUE THREAD

**Issue by wedi** [Spotifyd/spotifyd#43]
Hi!
After reading #37 I decided to go with a source build of spotifyd on my Raspi 2. Unfortunately the build fails. Probably because two versions of `syntex_syntax` are getting installed. At least https://github.com/phildawes/racer/issues/388 and https://github.com/Aaronepower/tokei/issues/42 suggest this.
    
    $ cargo build —release
    ...
    Downloading syntex_syntax v0.50.0
    Downloading syntex_syntax v0.52.0
    Downloading syntex_syntax v0.54.0
    ...
    Compiling syntex_syntax v0.50.0
    Compiling syntex_syntax v0.52.0
    ...
    error: Could not compile `syntex_syntax`.

    $ uname -a
    Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

    $ rustc -V
    rustc 1.16.0 (30cf806ef 2017-03-10)

For completeness: there are more dependencies that get installed in multiple versions, but there hasn’t been an error compiling those (yet):

     Downloading aster v0.34.0
     Downloading aster v0.36.0
     Downloading bitflags v0.4.0
     Downloading bitflags v0.7.0
     Downloading byteorder v0.5.3
     Downloading byteorder v1.0.0
     Downloading syntex v0.50.0
     Downloading syntex v0.52.0
     Downloading syntex v0.54.0
     Downloading syntex_errors v0.50.0
     Downloading syntex_errors v0.52.0
     Downloading syntex_errors v0.54.0
     Downloading syntex_pos v0.50.0
     Downloading syntex_pos v0.52.0
     Downloading syntex_pos v0.54.0
     Downloading unicode-xid v0.0.3
     Downloading unicode-xid v0.0.4
     Downloading url v0.5.10
     Downloading url v1.2.4

**Comment by SimonPersson** [comment]
I'll look into this sometime. I have to bring the librespot dependency up to date anyway, so it'll come up then I guess.

However, as you can see in my last comment in #37, the automated builds should be fixed by now. Please try it out if you haven't already :)

**Comment by SimonPersson** [comment]
Latest commit should build. It works on my machine and on travis. Feel free to reopen if you still have issues!
