### ISSUE TITLE
Error reusing cache after version bump

### ISSUE THREAD

**Issue by anderslundstedt** [Spotifyd/spotifyd#433]
**Description**
After upgrading 0.2.19 → 0.2.20 I got the following error upon starting spotifyd using `spotifyd --no-daemon --cache-path /var/cache/spotifyd`:

```
[ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
```

The error went away when I cleared out `/var/cache/spotifyd`. Previously, I have been able to reuse the cache between version upgrades.

**To Reproduce**
I am unable to reproduce this. I have tried starting up a 0.2.16 and a 0.2.19 with clean cache and then playing some songs to populate the cache, then starting up 0.2.20 with the same cache. This did not reproduce the error. Unfortunately I did not keep a copy of the old problematic cache.

**Expected behavior**
I do not know, perhaps somehow recognize that the cache is incompatible/corrupt  and clear it (and perhaps make a backup of it)?

**Logs**
As I cannot reproduce this and was too quick to clear out the cache, I cannot provide any logs ...

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: NixOS 20.03.git.7827d3f
 - Spotifyd: 0.2.20
- cargo: unknown, but could try to look it up if it would matter

**Comment by SirWindfield** [comment]
Weird. The cache is setup inside of `librespot` and out-of-reach. We just pass down the path and whether it is a credentials-only cache. They might have changed something or the Spotify cache format changed altogether as a change Spotify themselves made. 

We would need the stacktrace during the crash to determine where exactly this Result gets unwrapped, e.g. running spotifyd with `RUST_BACKTRACE=1` as environment variable. 

This sounds like something that would only happen once so I will mark this as an advice for now. If it does however happen more often or multiple times in a row, then we'll have to investigate further.
