### ISSUE TITLE
FR: Give precedence to command line arguments over config file

### ISSUE THREAD

**Issue by wedi** [Spotifyd/spotifyd#44]
I’d like to suggest giving precedence to command line arguments over a config file.
For some reason my password from the config file wasn’t accepted. So I just added it to the command line but still the one from the config file was used.

**Comment by SimonPersson** [comment]
Ah, good call! I will look into that.

**Comment by SimonPersson** [comment]
This should be fixed now, feel free to reopen if the issue persists!
