### ISSUE TITLE
Not building with pulseaudio_backend

### ISSUE THREAD

**Issue by JBlocklove** [Spotifyd/spotifyd#440]
**Description**
When trying to build with cargo I am adding `--no-default-features` and `--features pulseaudio_backend` but it still seems to only use the alsa backend. 
When I run `spotifyd -h` it says that `alsa` is the only backend available.

**To Reproduce**

1. Clone the master branch of the repo
2. Run `cargo build --release --no-default-features --features pulseaudio_backend`
3. Run `cargo install --path .`
4. Run `spotifyd -h`

***Note***
I get the same result when putting `pulseaudio_backend` in quotes. The README has discrepencies on whether or not to use them.

**Expected behavior**
Rather than show the usable backen is alsa, it should show that it can use pulseaudio.

**Logs**
There are no useful logs for this bug

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

***Note***
I've also compiled with the `dbus_mpris` flag included. It shows no notable difference.

**Versions (please complete the following information):**
 - OS: Arch
 - Spotifyd: master branch, spotifyd version 
- cargo: 1.39.0

**Comment by SirWindfield** [comment]
Are you sure that you do not have multiple spotifyd instances installed on your system? Checking the code that adds the help options ([here](https://github.com/Spotifyd/spotifyd/blob/45705bacf484375a72c25c5629c183a6a43d0978/src/config.rs#L30-L32)) definitely adds the right string.

Instead of running `cargo build` use `cargo run` and see if this still happens.

**Comment by JBlocklove** [comment]
It appears to work correctly when I use `cargo run`. How could I have multiple instances installed? I ran `cargo uninstall` before re-installing this last time and it still gave me the same issue.

**Comment by SirWindfield** [comment]
You could run `which spotifyd` and see what path it displays.

**Comment by JBlocklove** [comment]
`which spotifyd` just gives me `/home/jason/.cargo/bin/spotifyd`. If I run `cargo uninstall` it says `spotifyd not found`. I don't think I ever installed it through any other method, and this only points to a single binary.

**Comment by SirWindfield** [comment]
I mean, the easy fix is to just delete that file: `rm ~/.cargo/bin/spotifyd`. `spotifyd` is just a single binary and that should get rid of the old version.

If you run `cargo install`, `cargo uninstall` should trigger definitely. Maybe it works after you delete the old copy. But this is definitely not a `spotifyd` issue.
