### ISSUE TITLE
Initial volume always at 100%

### ISSUE THREAD

**Issue by mzanetti** [Spotifyd/spotifyd#445]
When starting spotifyd the initial volume setting is always 100%. This might be *very* loud, depending on the speakers.

Now, in addition to that, spotifyd seems to crash rather often and is respawned by systemd, which causes volume to reset itself to 100%.

Shouldn't the last used volume be cached somehow and restored on startup?

**Comment by SirWindfield** [comment]
It should be restored, yes. IIRC this is handled inside of `librespot` as well. Do you have crash logs available? `systemd` should contain some logging output. Make sure to start the daemon using `RUST_BACKTRACE=1 spotifyd --verbose` so I get additional output :)

**Comment by uiii** [comment]
The same is happening to me. E.g. when I start the RPi.

**Comment by mzanetti** [comment]
Ok, Sure, I can report the crashes too. But this actually bug is not about crashes. It also happens on restarts, as @uiii reported too. Also if I just ctrl+c spotifyd and start it again. Volume is always at 100%.

**Comment by mzanetti** [comment]
> It should be restored, yes. 

Ok, so that's a bug then, it clearly is not.

**Comment by mzanetti** [comment]
Is this still waiting for feedback for real or just hasn't been updated yet?

**Comment by mirko** [comment]
I'd be also *very* happy about this - e.g. librespot starts with 50% by default.
Just a config option which defines the default startup volume level would be fine (for now) - in case restoring volume is more / too much effort.

**Comment by Mxbonn** [comment]
@SirWindfield any updates on this?

**Comment by SirWindfield** [comment]
Currently in finals so I don't have time to work on it, sorry.

**Comment by mzanetti** [comment]
Either spotifyd will kill my cats or they will kill me eventually, as every morning music starts playing at 100% volume and the whole house is shaking until I managed to find the slider in the app 😂😂😂

**Comment by wilbertduenk** [comment]
You could set the normalisation_pregain to -10 or -20 or something to lower the maximum volume that spotifyd will play. Little workaround but it does the trick for me.

**Comment by sflip** [comment]
I implemented `initial_volume` as a config option [here](#623).

**Comment by SirWindfield** [comment]
Merged #623.
