### ISSUE TITLE
Crash when playing a downloaded song from android app

### ISSUE THREAD

**Issue by mzanetti** [Spotifyd/spotifyd#447]
**Description**
Sportifyd crash.

**To Reproduce**
1. Start spotifyd on some host
2. Open Spotify app on Android
3. Select some Album
4. Check the "download" switch and wait for the app to finish downloading the album
5. Start playing a song of that album
6. Move sound over to spotifyd
7. Skip to next song.

**Expected behavior**
It seems it goes wrong already at step 6, as the android app pretends it'd be playing on remote spotifyd, however, no sound output from spotify.
Then, at step 7, spotifyd crashes

**Logs**
<details><summary>Click to expand</summary>
08:57:38 [DEBUG] (1) mdns::fsm: received question: IN _spotify-connect._tcp.local
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:183] found interface Interface { name: "eno1", addr: V4(Ifv4Addr { ip: 10.10.10.10, netmask: 255.255.255.0, broadcast: Some(10.10.10.255) }) }
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:183] found interface Interface { name: "eno1", addr: V6(Ifv6Addr { ip: 2a02:8070:d185:82f0:ccc0:c5ef:e0f3:a8dd, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:183] found interface Interface { name: "eno1", addr: V6(Ifv6Addr { ip: 2a02:8070:d185:82f0:7b7e:f391:c5dd:acdf, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:183] found interface Interface { name: "eno1", addr: V6(Ifv6Addr { ip: fd02:a321:5d61:0:ccc0:c5ef:e0f3:a8dd, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:183] found interface Interface { name: "eno1", addr: V6(Ifv6Addr { ip: fd02:a321:5d61:0:e85f:bca4:b4b6:e177, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
08:57:38 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 1
08:57:38 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 1
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:247] sending packet to V4(224.0.0.251:5353)
08:57:38 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 2
08:57:38 [DEBUG] (1) tokio_core::reactor: loop poll - 581.290719ms
08:57:38 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 61340, tv_nsec: 298788083 }
08:57:38 [DEBUG] (1) tokio_core::reactor: loop process, 48.218µs
08:57:38 [TRACE] (2) tokio_reactor: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:376] event Readable | Writable Token(4194305)
08:57:38 [TRACE] (2) tokio_reactor: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:390] loop process - 1 events, 0.000s
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:77] received packet from V4(10.10.10.10:5353)
08:57:38 [TRACE] (2) tokio_reactor: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:376] event Writable Token(4194305)
08:57:38 [TRACE] (2) tokio_reactor: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:390] loop process - 1 events, 0.000s
08:57:38 [TRACE] (1) mdns::fsm: [/home/kodi/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/66a7403/src/fsm.rs:88] received packet from V4(10.10.10.10:5353) with no query
08:57:38 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 1
08:57:38 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 1
08:57:38 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 2
08:57:38 [DEBUG] (1) tokio_core::reactor: loop poll - 250.301µs
08:57:38 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 61340, tv_nsec: 299115858 }
08:57:38 [DEBUG] (1) tokio_core::reactor: loop process, 29.142µs
08:57:39 [TRACE] (2) tokio_reactor: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:376] event Readable | Writable Token(33554437)
08:57:39 [TRACE] (2) tokio_reactor: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:390] loop process - 1 events, 0.000s
08:57:39 [TRACE] (1) tokio_io::_tokio_codec::framed_read: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_read.rs:193] attempting to decode a frame
08:57:39 [TRACE] (1) tokio_io::_tokio_codec::framed_read: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_read.rs:196] frame decoded from buffer
08:57:39 [TRACE] (1) tokio_io::_tokio_codec::framed_read: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_read.rs:193] attempting to decode a frame
08:57:39 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 5
08:57:39 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:189] flushing framed transport
08:57:39 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:213] framed transport flushed
08:57:39 [DEBUG] (1) tokio_core::reactor: loop poll - 770.668744ms
08:57:39 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 61341, tv_nsec: 69828693 }
08:57:39 [DEBUG] (1) tokio_core::reactor: loop process, 82.684µs
08:57:39 [DEBUG] (1) librespot_connect::spirc: kMessageTypeNext "Pixel 3" 75784926ef88ec06a28d63579645fe6f161bc3a0 1776345836 1575881857033
08:57:39 [ERROR] Caught panic with message: index out of bounds: the len is 0 but the index is 0
08:57:39 [DEBUG] (1) librespot_connect::spirc: drop Spirc[0]
08:57:39 [DEBUG] (1) librespot_playback::player: Shutting down player thread ...
08:57:39 [DEBUG] (7) librespot_playback::player: drop Player[0]
08:57:39 [DEBUG] (1) librespot_core::session: drop Session[0]
08:57:39 [DEBUG] (1) librespot::component: drop MercuryManager
08:57:39 [TRACE] (1) tokio_threadpool::pool: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/pool/mod.rs:139] shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
08:57:39 [TRACE] (1) tokio_threadpool::pool: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/pool/mod.rs:187]   -> transitioned to shutdown
08:57:39 [TRACE] (1) tokio_threadpool::pool: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/pool/mod.rs:208]   -> shutting down workers
08:57:39 [DEBUG] (1) tokio_reactor: dropping I/O source: 3
08:57:39 [TRACE] (1) mio::poll: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:907] deregistering handle with poller
08:57:39 [DEBUG] (1) tokio_reactor: dropping I/O source: 0
08:57:39 [TRACE] (1) mio::poll: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:907] deregistering handle with poller
08:57:39 [DEBUG] (1) tokio_reactor: dropping I/O source: 1
08:57:39 [TRACE] (1) mio::poll: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:907] deregistering handle with poller
08:57:39 [DEBUG] (1) tokio_reactor: dropping I/O source: 2
08:57:39 [DEBUG] (1) librespot_core::session: drop Dispatch
08:57:39 [TRACE] (1) mio::poll: [/home/kodi/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:907] deregistering handle with poller
08:57:39 [DEBUG] (1) tokio_reactor: dropping I/O source: 5
</details>

- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

(happens with both, alsa and pulseaudio backends)

**Versions (please complete the following information):**
 - OS: ubuntu 18.04
 - Spotifyd: 0a1e578

**Comment by SirWindfield** [comment]
In all honesty, I have no clue if own songs would even work. My guts tell me no. You could try to add your offline songs to a custom playlist. That way, Spotify will definitely upload them into the cloud and make them available for other devices as well. I think just selecting an album wouldn't work (as you already figured out).

**Comment by mzanetti** [comment]
It's beyond me why I could play a song fine, then I download it and then I can't play it any more... But it seems it's upstream Spotify weirdness...

In any case, spotifyd should probably not crash on it anyways but just not work and wait for the next working song...

**Comment by mzanetti** [comment]
FWIW, the issue that downloaded songs can't be played has been fixed by spotify: https://community.spotify.com/t5/Ongoing-Issues/Connect-Can-t-play-songs-saved-to-Your-Library-on-Connect/idi-p/4825190/page/21#comments

So it's harder to reproduce this now but probably still happens if a song can't be played for whatever reason.
