### ISSUE TITLE
Restore session after restart

### ISSUE THREAD

**Issue by LanderMoerkerke** [Spotifyd/spotifyd#448]
_Is it possible to restart playing after reloading or restarting spotifyd?_

I like to restore the last session by calling play via mpris. Now I need to start playing a song via the Spotify app or program.

Great program!

**Comment by SirWindfield** [comment]
https://github.com/librespot-org/librespot/pull/427

**Comment by slondr** [comment]
#511 was included in the new v0.2.25 release, so I'm assuming this is resolved — if it's not, please let us know
