### ISSUE TITLE
Unable to Play:Connection reset by peer

### ISSUE THREAD

**Issue by PMaynard** [Spotifyd/spotifyd#449]
**Description**
Unable to keep playing songs due to fatal error.

**To Reproduce**
Play songs, after 2-4 songs it dies. 
Might have something to do with running on Gentoo ? 

**Expected behavior**
Play next song

**Logs**
<details><summary>
[ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
</summary>
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:654] flushed State { reading: Init, writing: Init, keep_alive: Busy, error: None }
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:337] wants_read_again? false
11:54:52 [DEBUG] (1) tokio_core::reactor: loop poll - 291.451µs
11:54:52 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 7494330, tv_nsec: 294454367 }
11:54:52 [DEBUG] (1) tokio_core::reactor: loop process, 46.457µs
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:193] Conn::read_head
11:54:52 [DEBUG] (1) hyper::proto::h1::io: read 223 bytes
11:54:52 [TRACE] (1) hyper::proto::h1::role: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/role.rs:46] Request.parse([Header; 100], [u8; 223])
11:54:52 [TRACE] (1) hyper::proto::h1::role: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/role.rs:50] Request.parse Complete(223)
11:54:52 [TRACE] (1) hyper::header: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/header/mod.rs:355] maybe_literal not found, copying "Keep-Alive"
11:54:52 [DEBUG] (1) hyper::proto::h1::io: parsed 6 headers (223 bytes)
11:54:52 [DEBUG] (1) hyper::proto::h1::conn: incoming body is content-length (0 bytes)
11:54:52 [TRACE] (1) hyper::proto: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/mod.rs:133] expecting_continue(version=Http11, header=None) = false
11:54:52 [TRACE] (1) hyper::proto: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/mod.rs:122] should_keep_alive(version=Http11, header=Some(Connection([KeepAlive]))) = true
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:317] read_keep_alive; is_mid_message=true
11:54:52 [TRACE] (1) hyper::proto: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/mod.rs:122] should_keep_alive(version=Http11, header=None) = true
11:54:52 [TRACE] (1) hyper::proto::h1::role: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/role.rs:129] Server::encode has_body=true, method=Some(Get)
11:54:52 [TRACE] (1) hyper::proto::h1::encode: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/encode.rs:100] encoding chunked 449B
11:54:52 [DEBUG] (1) hyper::proto::h1::io: flushed 545 bytes
11:54:52 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 4
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:460] maybe_notify; read_from_io blocked
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:654] flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:337] wants_read_again? false
11:54:52 [DEBUG] (1) tokio_core::reactor: loop poll - 690.847µs
11:54:52 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 7494330, tv_nsec: 295217562 }
11:54:52 [DEBUG] (1) tokio_core::reactor: loop process, 48.064µs
11:54:52 [TRACE] (2) tokio_reactor: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:376] event Readable | Writable Token(125829124)
11:54:52 [TRACE] (2) tokio_reactor: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:390] loop process - 1 events, 0.000s
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:193] Conn::read_head
11:54:52 [DEBUG] (1) hyper::proto::h1::io: read 0 bytes
11:54:52 [TRACE] (1) hyper::proto::h1::io: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/io.rs:127] parse eof
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:904] State::close_read()
11:54:52 [DEBUG] (1) hyper::proto::h1::conn: read eof
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:317] read_keep_alive; is_mid_message=true
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:654] flushed State { reading: Closed, writing: Init, keep_alive: Disabled, error: None }
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:337] wants_read_again? false
11:54:52 [TRACE] (1) hyper::proto::h1::conn: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.27/src/proto/h1/conn.rs:662] shut down IO
11:54:52 [TRACE] (1) mio::poll: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:907] deregistering handle with poller
11:54:52 [DEBUG] (1) tokio_reactor: dropping I/O source: 4
11:54:52 [DEBUG] (1) tokio_core::reactor: loop poll - 3.630228ms
11:54:52 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 7494330, tv_nsec: 298919147 }
11:54:52 [DEBUG] (1) tokio_core::reactor: loop process, 49.054µs
11:55:22 [DEBUG] (1) tokio_core::reactor: loop poll - 29.587647386s
11:55:22 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 7494359, tv_nsec: 886633768 }
11:55:22 [DEBUG] (1) tokio_core::reactor: loop process, 96.955µs
11:55:22 [DEBUG] (1) librespot_connect::spirc: At track 22 of 50 <"spotify:artist:2CWWgbxApjbyByxBBCvGTm"> update [false]
11:55:22 [WARN] Skipping track "spotify:meta:page:3" at position [22] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:4" at position [23] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:5" at position [24] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:6" at position [25] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:7" at position [26] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:8" at position [27] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:9" at position [28] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:10" at position [29] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:11" at position [30] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:12" at position [31] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:13" at position [32] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:14" at position [33] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:15" at position [34] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:16" at position [35] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:17" at position [36] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:18" at position [37] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:19" at position [38] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:20" at position [39] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:21" at position [40] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:22" at position [41] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:23" at position [42] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:24" at position [43] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:25" at position [44] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:26" at position [45] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:27" at position [46] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:28" at position [47] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:29" at position [48] of 50
11:55:22 [WARN] Skipping track "spotify:meta:page:30" at position [49] of 50
11:55:22 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 5
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:189] flushing framed transport
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:192] writing; remaining=1562
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:213] framed transport flushed
11:55:22 [DEBUG] (1) tokio_core::reactor: loop poll - 190.737µs
11:55:22 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 7494359, tv_nsec: 887579821 }
11:55:22 [DEBUG] (1) tokio_core::reactor: loop process, 40.747µs
11:55:22 [DEBUG] (7) librespot_playback::player: command=Load(SpotifyId(u128!(126738930226510372960726548416879707255)), true, 0)
11:55:22 [DEBUG] (1) tokio_reactor::registration: scheduling Read for: 5
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:189] flushing framed transport
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:192] writing; remaining=83
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_write: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_write.rs:213] framed transport flushed
11:55:22 [DEBUG] (1) tokio_core::reactor: loop poll - 1.325819ms
11:55:22 [DEBUG] (1) tokio_core::reactor: loop time - Instant { tv_sec: 7494359, tv_nsec: 888968745 }
11:55:22 [DEBUG] (1) tokio_core::reactor: loop process, 49.728µs
11:55:22 [TRACE] (2) tokio_reactor: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:376] event Readable | Writable Token(20971525)
11:55:22 [TRACE] (2) tokio_reactor: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:390] loop process - 1 events, 0.000s
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_read: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_read.rs:193] attempting to decode a frame
11:55:22 [TRACE] (1) tokio_io::_tokio_codec::framed_read: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.12/src/_tokio_codec/framed_read.rs:196] frame decoded from buffer
11:55:22 [ERROR] Caught panic with message: Spotify servers returned an error. Restart librespot.
11:55:22 [DEBUG] (1) librespot_core::session: drop Dispatch
11:55:22 [TRACE] (1) mio::poll: [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:907] deregistering handle with poller
11:55:22 [DEBUG] (1) tokio_reactor: dropping I/O source: 5
11:55:22 [DEBUG] (1) librespot_connect::spirc: drop Spirc[0]
11:55:22 [DEBUG] (1) librespot_playback::player: Shutting down player thread ...

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions:**
 - OS: Gentoo
 - Spotifyd: 1df80b4bf38656e6f4f162748b4fbd0b5260a69a
- cargo: 1.37.0

**Additional context**
See issues on librespot - https://github.com/librespot-org/librespot/issues/350#issuecomment-559447468

**Comment by SirWindfield** [comment]
I don't think that this is an error on our side to be honest.

**Comment by PMaynard** [comment]
@SirWindfield Yeah, its a tricky one. I also don't think its you. I'll continue digging and update this issue with anything I find. If you like you can close it.

**Comment by SirWindfield** [comment]
Sure, no problem :)

**Comment by ngrande** [comment]
i get the same errors
> ERROR librespot_core::session] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

it was running fine for a whole day (on a raspi) and since the next day i am unable to get it to work again at all - no connection between the client and the librespot possible (or only for a sec and as soon as i want to play a song it disconnects from the spotify client).
When i connect it only shows:

> INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-b-3ml0.ap.spotify.com:4070"

Any hints?
