### ISSUE TITLE
Allow `#` in passwords or document that it doesn’t work.

### ISSUE THREAD

**Issue by wedi** [Spotifyd/spotifyd#45]
Hi. One more thing.
Adding my password `8/8#Yo@P` to the config file did not work. So I successfully tested `RfegYKcE` and `Xh%+2aTc`. I realized it is the hash getting parsed as comment introduction. Testing with `BUJEg#ky` confirmed that.

The config file code is the culprit, because it works with a hash on both the command line prompt as well as the command line parameter.

Maybe you should change this behavior as well or at least document it.

While testing this I was wondering how to smoothly exit the --no-daemon process without killing it? I tried <kbd>STRG+C</kbd> and <kbd>STRG+D</kbd> and only after doing it often enough and/or waiting a random time the process finally terminates.

**Comment by lschuermann** [comment]
Hi!
I had the same issue, just surround the password with double-quotes (e.g. `"`). :)

**Comment by SimonPersson** [comment]
I've documented this in the README now, thanks for the report.

Latest commit should also close on `^C`.
