### ISSUE TITLE
add support for device-type

### ISSUE THREAD

**Issue by wdehoog** [Spotifyd/spotifyd#450]
Librespot has the option to specify the device type:

```
The displayed device type in Spotify clients. Can be unknown, computer, tablet, smartphone, speaker, tv, avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle. Defaults to speaker 
```

I am running spotifyd on my UBports phone and it would be nice to be able to configure it to `smartphone`.

If this is not yet possible how could it be added?

**Comment by SirWindfield** [comment]
You'd have to add a new configuration to the `SharedConfigValues` struct:
https://github.com/Spotifyd/spotifyd/blob/a789b49c3d8bd0e4efdbb41587e5f4f61f602ff4/src/config.rs#L207-L208.

Additionally, all possible values would have to be listed inside of an `enum` (for example called `DeviceType`) similar to the `backend` and `bitrate` options:
https://github.com/Spotifyd/spotifyd/blob/a789b49c3d8bd0e4efdbb41587e5f4f61f602ff4/src/config.rs#L120-L151

The important part is to implement `From<DeviceType> for librespot::core::config::DeviceType` as that allows to convert the values without much of an effort when passing down to `librespot`.

You'd then have to add a new field to the `SpotifydConfig` struct that holds the device type. Inside of `setup.rs` the main loop state is created. The value has to be set in there as well using a new struct field. The last step would be to pass down that value inside of `main_loop.rs`:
https://github.com/Spotifyd/spotifyd/blob/a789b49c3d8bd0e4efdbb41587e5f4f61f602ff4/src/main_loop.rs#L166-L172

**Comment by wdehoog** [comment]
Hi. I have done some work already. Please see https://github.com/wdehoog/spotifyd/tree/add_device-type 
But I cannot build the armhf version I'd like to test on my phone so I did not make a PR yet.

**Comment by SirWindfield** [comment]
Ah, fair enough! Let me know if you make any progress!
