### ISSUE TITLE
Proxy command line option conflict

### ISSUE THREAD

**Issue by justin-gerhardt** [Spotifyd/spotifyd#451]
**Description**
The commit that added proxy support defined a command line option "proxy". The short version of that option "p" conflicts with the existing "password" option.

https://github.com/Spotifyd/spotifyd/blob/76ce4ca209f59bc36d90ee0946d18a1578a0c104/src/config.rs#L293

**To Reproduce**
1. run spotifyd --help (or any other command)

**Expected behavior**
The command should output command options
**Logs**
<details><summary>Click to show logs</summary>
thread 'main' panicked at 'Argument short must be unique

	-p is already in use', /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:186:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:335
  13: clap::app::parser::Parser::debug_asserts
             at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:186
  14: clap::app::parser::Parser::add_arg
             at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:294
  15: clap::app::App::arg
             at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/mod.rs:785
  16: spotifyd::config::SharedConfigValues::augment_clap
             at src/config.rs:207
  17: spotifyd::config::CliConfig::augment_clap
             at src/config.rs:201
  18: <spotifyd::config::CliConfig as structopt::StructOpt>::clap
             at src/config.rs:177
  19: structopt::StructOpt::from_args
             at /home/justin/.cargo/git/checkouts/structopt-7fc81727a7a36832/0c888e9/src/lib.rs:730
  20: spotifyd::main
             at src/main.rs:47
  21: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  25: std::panicking::try
             at src/libstd/panicking.rs:271
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

</details>

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Arch
 - Spotifyd: Every commit since 76ce4ca209f59bc36d90ee0946d18a1578a0c104
- cargo: cargo 1.39.0 (1c6ec66d5 2019-09-30)

**Comment by SirWindfield** [comment]
I should probably add a CI check to see if `spotifyd --help` exists with 0...
