### ISSUE TITLE
Unable to follow with playerctl

### ISSUE THREAD

**Issue by shanedabes** [Spotifyd/spotifyd#455]
**Description**
Unable to use playerctl's `-F` flag to follow spotifyd and automatically print metadata and status of playing music.

**To Reproduce**
Run: `playerctl metadata -p spotifyd --format '{{ status }} {{ artist }} - {{ title }}' -F`

**Expected behavior**
playerctl should update and post another line containing status and metadata when song status or song changes.

**Logs**
Seems to be standard logging, not sure what I should include

**Compilation flags** 
- [x] dbus_mpris
- [X] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [x] rodio_backend

**Versions (please complete the following information):**
 - OS: Arch Linux
 - Spotifyd: 0.2.20
- cargo: 1.39.0

Playertl version is 2.0.2

**Comment by justin-gerhardt** [comment]
Spotifyd doesn't raise the org.freedesktop.DBus.Properties.PropertiesChanged when the metadata changes so playerctl doesn't know to update/requery.

**Comment by SirWindfield** [comment]
I didn't even know that this as a thing. It should be enough to raise it at every song change.

**Comment by shanedabes** [comment]
Was there any progress in solving this issue?
