### ISSUE TITLE
Which Backend to Use?

### ISSUE THREAD

**Issue by idofr** [Spotifyd/spotifyd#456]
I'm using an external usb sound card on Nvidia's Jetson Nano (Ubuntu 18.04)
I've successfully compiled and executed the programme and am seeing it as an option in the device list on my laptop, for example, yet I get no sound.
My first assumption is that I'm using the wrong backend. I started with the default and also tested with pulseaudio, none of them seems to work.
Any ideas where and for what to look further?

**Comment by SirWindfield** [comment]
You need to configure your backends if you use alsa or pulseaudio using some config files. This has nothing to do with spotifyd itself. If you configured them to use the sound card, make sure to configure spotifyd afterwards using a config file (see readme for more information) on what card to use.

It should be picked up if you have configured everything correctly.

**Comment by SirWindfield** [comment]
Configuring ALSA is something that should be done on every system to get proper sound working. It's kind of mandatory
