### ISSUE TITLE
Process doesnt exit on errors and doesn't automatically reconnect

### ISSUE THREAD

**Issue by hiredman** [Spotifyd/spotifyd#458]
**Description**
I see 

> 05:10:38 [ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

about once a day in my log file. Afterwards the spotifyd instance is no longer visible as a device in spotify apps. The process doesn't exit, so I can't just restart it when it exits, and the process itself doesn't appear to try and reconnect.

**To Reproduce**

I run spotifyd like:
`nohup ./spotifyd -u ... -p '...' --no-daemon --pid spotify.pid > spotifyd.log &`

**Expected behavior**
I expect the process to exit on non-recoverable errors, so whatever launched the process (maybe systemd, or even just a shell while loop) can make decisions about restarting it or not.

**Versions (please complete the following information):**
 - OS: Fedora 30
 - Spotifyd: v0.2.20 spotifyd-linux-full.tar.gz from github

**Comment by SirWindfield** [comment]
Sounds like your router reconnects to your IPS once a day to obtain a new IP address. If spotifyd loses its conenction, it can't reconnect by itself and has to be restarted.

**Comment by SirWindfield** [comment]
If someone in this issue still encounters disconnects that do not reconnect by itself, please re-open this issue!

**Comment by blueForestIcarus** [comment]
I am having this issue with spotifyd 0.2.24

> Apr 12 01:16:00 daedalus spotifyd[1014]: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> Apr 12 01:16:19 daedalus spotifyd[1014]: Couldn't fetch metadata from spotify: Err(RateLimited(Some(5)))

**Comment by samm81** [comment]
I'm still getting this on `spotifyd` 0.2.24 as well. I get the `ConnectionReset` error only after hitting Ctrl+C (I run it with `--no-daemon`

```bash
Loading <Mood Indigo> with Spotify URI <spotify:track:2XxxMVXA87XgcJqmBHhFMH>
<Mood Indigo> loaded
^COs { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
^C
```

**Comment by 20NE** [comment]
This issue still unfixed. happens very frequently.
spotifyd 0.2.24
