### ISSUE TITLE
Device parameter with alsa

### ISSUE THREAD

**Issue by kajaba** [Spotifyd/spotifyd#46]
Hi I have a problem on my raspberry. On alsamixer I see that my default card is PulseAudio (have also kodi installed and pulseaudio is installed probably by kodi). I would like to use device 0 (bcm235 trough hdmi). 
When I launch spotifyd --device 0 as pi user, it crashes
When I launch spotifyd with sudo, everything works

Thank you for your help and great work

**Comment by SimonPersson** [comment]
I think that the device names are given by `aplay -L`. Can you play audio on the right device using `aplay -D [device_name] /usr/share/sounds/alsa/Front_Center.wav`?

**Comment by kajaba** [comment]
aplay gives me 
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0


when I try 
aplay -D default it works.. but no matter I try I get ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM ....

Anyway, when I comment the device line in config.. it works even with standard user

**Comment by SimonPersson** [comment]
Notice the capital `-L` :)

**Comment by kajaba** [comment]
OMG, sorry for my stupid comments
Thanks Simon :)

**Comment by SimonPersson** [comment]
I'm glad it worked out for you!

**Comment by joerg-krause** [comment]
Note, that `-L` only lists the ALSA devices having a `hint` section. Most ALSA PCM plugins don't have one.
