### ISSUE TITLE
automate upload to crates.io

### ISSUE THREAD

**Issue by infinity0** [Spotifyd/spotifyd#462]
~Hi, please upload this to crates.io - we need this in order to package it for Debian~

Automate the upload as well.

**Comment by SimonPersson** [comment]
Hi! I've wanted to do this for a long time, but we had dependencies that were not yet on crates.io which blocked it. That doesn't seem to be an issue any more. I've updated our git dependencies to use crates.io dependencies, and made a release here: https://crates.io/crates/spotifyd.

Tell me if there is anything else we need to do in order for you to package spotifyd, it would be really helpful for our users!

**Comment by SirWindfield** [comment]
Is it possible that I can upload to crates as well? Or can github maintainers upload there too?

**Comment by infinity0** [comment]
Awesome, thanks a lot! In general keeping your dependencies up-to-date also makes packaging easier for us, as we then don't have to maintain old versions of crates. There is a tool, [cargo-outdated](https://github.com/kbknapp/cargo-outdated) that can help with that.

**Comment by SirWindfield** [comment]
We have an integration in the repo (dependabot) but the current open PRs from it involve some refactoring (some are just import changes). The dbus related ones actually involve re-writing `dbus_mpris.rs` again. The ones that pass the CI pipeline are usually updated though.

**Comment by SirWindfield** [comment]
https://github.com/actions-rs/meta/issues/6#issuecomment-536440911
