### ISSUE TITLE
spotifyd-linux-full release seems to be missing flags

### ISSUE THREAD

**Issue by nivekuil** [Spotifyd/spotifyd#464]
I noticed that I didn't have the pulseaudio backend available from spotifyd-bin-full from the AUR.

Looking at this CI run: https://github.com/Spotifyd/spotifyd/runs/338348234 

It appears that the same build command is used for both slim and full: `/usr/share/rust/.cargo/bin/cargo +stable build --locked --release --target x86_64-unknown-linux-gnu --no-default-features --features ,alsa_backend`

Building spotifyd-full from source does include the flags.

**Comment by ptrk96** [comment]
I see this issue has been closed but linux-full binaries still don't compile with any backend other then alsa. Is this the expected behavior?

**Comment by gatorget** [comment]
+1 for adding ALL flags to full build
