### ISSUE TITLE
Cannot get it to work consistantly

### ISSUE THREAD

**Issue by GideonWolfe** [Spotifyd/spotifyd#466]
I don't really know if it qualifies as a "bug report". but I have had very mixed results running the `spotifyd-full-git` package on Arch Linux.

When I follow the instructions to install it as a service, It creates the service but everytime I try to check on it with a `systemctl status spotifyd` it claims the service does not exist. I have tried using `/etc/systemd/user/` and `~/.config/systemd/` and I cannot get it to run as a service.

*One time* I got it to run by issuing the `spotifyd` command and I could see it in spotify-tui. But I could not get it to replicate, because even after a reboot I get the following error every time I try to run the executable.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kin
stack backtrace:
   0:     0x55e1a3919aa4 - <unknown>
   1:     0x55e1a393ea9c - <unknown>
   2:     0x55e1a39134c7 - <unknown>
   3:     0x55e1a391c2ce - <unknown>
   4:     0x55e1a391bfc1 - <unknown>
   5:     0x55e1a391c9cb - <unknown>
   6:     0x55e1a391c56e - <unknown>
   7:     0x55e1a391c456 - <unknown>
   8:     0x55e1a393aa0e - <unknown>
   9:     0x55e1a393ab07 - <unknown>
  10:     0x55e1a35aa3c2 - <unknown>
  11:     0x55e1a31dba8e - <unknown>
  12:     0x55e1a31e8f07 - <unknown>
  13:     0x55e1a31bbe33 - <unknown>
  14:     0x55e1a391c3f3 - <unknown>
  15:     0x55e1a3925f4a - <unknown>
  16:     0x55e1a391cf6d - <unknown>
  17:     0x55e1a31e9552 - main
  18:     0x7fe4d8991153 - __libc_start_main
  19:     0x55e1a31a810e - <unknown>
  20:                0x0 - <unknown>

```

I don't think it's a backend or authentication issue, I just can't get it to start... This is the only way spotify-tui is worth using because if I can't get spotifyd working then I would be forced to run the full GUI client anyways...

**Comment by SirWindfield** [comment]
Can you post the full log from systemd? I think some lines are missing

**Comment by GideonWolfe** [comment]
So I got the error above to go away by removing one line at a time from the config file until I removed the line where I set the device name to `spotifyd`.

Now the issue I am facing is the `spotifyd` command will execute successfully and run the first time. But when I killed the process in order to rename the device, it just wouldn't start again.

I would run `spotifyd --verbose`` and then get no output when I ran it, as well as no results for `ps aux | grep spotifyd`. 

There are no errors/logs, so I don't really know what's going on

**Comment by SirWindfield** [comment]
Quite stupid questions but just to make sure:

- Do you use alsa as your audio output library? Linux provides others as well (pulseaudio)
- Is your device name __really__ available? If yes, does your ALSA control device has a different name? There is a config entry for that as well. If you don't specify it, the name defaults to your audio device name.
- Make sure that the mixer is right as well

Generally speaking, almost 90% of the time `unwrap()` errors are the cause of wrongly configured audio backends. There is currently no error checking in those parts. It's on the todo list right now though. I don't have much time until mid february because I got my finals upcoming :)

**Comment by GideonWolfe** [comment]
> Do you use ALSA as your audio output library? 

I don't believe so. I am using pulseaudio. When I run `pactl list` I get copious output, but `aplay -l` isn't even a recognized command on my Arch system. But I am getting output from `pactl` that include my Sink #1 name as ` alsa_output.pci-0000_00_1b.0.analog-stereo` so I have no idea what's going on.

> Is your device name really available?

Not quite sure what you mean by this. I would assume nothing else is named spotifyd.

Is there an example configurations or a set of commands I need to run to get the correct values for my backend variables? My audio config shouldn't be abnormal and no other program has had issue outputting audio. Is there just a default config for pulseaudio?

**Comment by SirWindfield** [comment]
If you run pulseaudio, make sure that the `pulseaudio_backend` feature is available. If that is the case, `spotifyd --help` should list `pulseaudio` as an available `--backend` value. 

If that is not the case (not sure if the AUR version compiles with that flag), you can compile spotifyd yourself. Clone the repo, cd into it and run `cargo run --no-default-features --features pulseaudio_backend -- --backend pulseaudio`, this will compile the daemon and run it. If that works, you can create a binary with `cargo build --release --no-default-features --features pulseaudio_backend`.

You can also download pre-built binaries from our release page (spotifyd-linux-full). This contains all available backends.

**Comment by GideonWolfe** [comment]
> If that is the case, spotifyd --help should list pulseaudio as an available --backend value

It doesn't look like pulseaudio is listed :/

> You can also download pre-built binaries from our release page (spotifyd-linux-full). This contains all available backends.

I tried to download the binary into a folder, and ran `./spotifyd --help` and even then pulseaudio is missing. Even the AUR package `spotifyd-full-git` does not have the backend.

I did finally get it working by building from source...

**Comment by SirWindfield** [comment]
Looks like the CI stuff isn't working. I don't have a lot of time now due to finals but can fix it later on mid February. Sorry for the inconvenience.

**Comment by GideonWolfe** [comment]
Glad we were able to narrow down the issue. I got it working now, no worries. Good luck with finals :+1:
