### ISSUE TITLE
use_keyring should be default config

### ISSUE THREAD

**Issue by stevensonmt** [Spotifyd/spotifyd#468]
storing password in a text file is inherently bad practice and I can't imagine a linux distro that doesn't use the secret service and dbus keyring already. For users wanting to use 3rd party app like pass or who choose to store credentials as text, okay, but it seems the most secure option should be the default.

**Comment by SimonPersson** [comment]
> I can't imagine a linux distro that doesn't use the secret service and dbus keyring already

This has nothing to do with distributions. You can use dbus and secret service in any distribution, some just require you to install it.

My position is that the default configuration should require as few dependencies as possible, as one of the main use cases for the project is to run in a headless, embedded environment.

**Comment by stevensonmt** [comment]
> the default configuration should require as few dependencies as possible

Fair enough, but even at the expense of security?

**Comment by SirWindfield** [comment]
The current implementation doesn't work if you run on headless. Making use keyring the defaukt would break on servers.
