### ISSUE TITLE
`Illegal instruction.` on CentOS 7

### ISSUE THREAD

**Issue by lschuermann** [Spotifyd/spotifyd#47]
Hello,

I've got the following problem with spotifyd:

When running spotifyd on my homeserver (CentOS 7), it connects to my spotify-account, but as soon as I try to play a track it crashes with the following error-message:
```
[root@hostname ~]# ./spotifyd -c spotifyd.conf --no-daemon
10:00:36 [INFO] Connecting to AP "lon2-accesspoint-a4.ap.spotify.com:4070"
10:00:36 [INFO] Authenticated as "myaccount" !
10:00:36 [INFO] Using alsa sink
10:00:43 [INFO] Loading track "The Stars Are Mine"
Illegal instruction
```

This behavior occurs with the pre-built binaries as well as with self-compiled versions.
On my personal ArchLinux Machine, spotifyd runs without any problems.
I tried this in a KVM-Guest and on the host, as root and as an unprivileged user.

My configuration:
```
[global]
username = myaccount
password = "hah, nice try :)"
backend = alsa
device = default
device_name = fancyvaluehere
bitrate = 320
cache = /home/spotifyd/spotify_cache
```

I attached the verbose-output just before the crash as a file, as it was quite long. [verbose-output.txt](https://github.com/Spotifyd/spotifyd/files/949558/verbose-output.txt)
Additionally, `dmesg` outputs the following:
```
[217153.691879] traps: spotifyd[7260] trap invalid opcode ip:7fa62f04fbf1 sp:7fa62d98ffb0 error:0 in spotifyd[7fa62edb5000+4c9000]
```

The installed packages:
- `alsa-lib-devel@1.1.1`
- `rust@1.16.0`
- `cargo@0.17.0`

Do you know what is going on here? Can you guide me in the right direction? Am I missing out something?

Thanks!
Leon

**Comment by SimonPersson** [comment]
Hi! Could you also give me a GDB backtrace? Build a debug build, and run:
```
$ gdb ./spotifyd
(gdb) run --no-daemon
```

Start playing a song, and write `bt` to get the backtrace.

**Comment by lschuermann** [comment]
I really can't believe what I'm seeing now.
I just tested everything before running it with gdb and I got the same error.

Then, with gdb enabled, everything worked fine.
Running it standalone again, everything works.
Running the release version, everything works.

This is really weird, but I'm happy that it works now. (Even from inside a QEMU/KVM Guest)
I will reopen the issue as soon as I can reproduce it.

Thanks!

**Comment by henningphan** [comment]
Hello,
I got the same issue. How do I build a debug build?

**Comment by SimonPersson** [comment]
Hi! Just run `cargo build` in the repository.

**Comment by henningphan** [comment]
``(gdb) run --no-daemon
Starting program: /home/henning/containers/spotifyd/spotifyd/target/release/spotifyd --no-daemon
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
00:39:43 [INFO] Couldn't find config file, continuing with default configuration.
00:39:43 [INFO] Using software volume controller.
00:39:43 [INFO] No backend specified, defaulting to: alsa.

Program received signal SIGILL, Illegal instruction.
0x0000555555865a51 in rust_crypto_aesni_setup_working_key_128 ()
(gdb)

**Comment by SimonPersson** [comment]
It looks like you're CPU does not support AVX instructions. I've pushed a fix.
