### ISSUE TITLE
macOS issues with spotifyd

### ISSUE THREAD

**Issue by johnalanwoods** [Spotifyd/spotifyd#487]
**Description**
The Documentation for macOS is prohibitively bad.

**To Reproduce**
* Try to setup keyChain support on macOS, try every permutation of 

```
application: rust-keyring
service: spotifyd
username: <your-spotify-username>
```

..., still cannot get it to work.
 
* No docs on using Launchctl instead of systemctrl

* No docs on how to configure the config file on macOS from ALSA to Portaudio, which caused me to spend hours debugging the config file, searching code for answers.

**Expected behavior**
A clear and concise description of what one needs to do to use this app on macOS

Great project, but too hard to use.

**Comment by johnalanwoods** [comment]
Like which values should these items have in the config file:



```
 27 # The alsa audio device to stream audio to. To get a
 28 # list of valid devices, run `aplay -L`,
 29 device = alsa_audio_device
 30
 31 # The alsa control device. By default this is the same
 32 # name as the `device` field.
 33 control = alsa_audio_device
```

I constantly see:

`Caught panic with message: Could not find device`


My backend is set to 'portaudio'

**Comment by johnalanwoods** [comment]
I've finally got it working (sans the Launchctl) and happy to contribute a PR if that's helpful.

Any advice on using brew services or launchctrl would be appreciated.

**Comment by SirWindfield** [comment]
Great yo hear that you figured it out. I don't think that any active contributor uses macOS which contributes to the lacking documentation.

I never used launchctl so I can't help you out on that, sorry. I know that brew is the de-facto package manager for macOS right now and we are currently looking into integrating `spotifyd` with it.

**Comment by johnalanwoods** [comment]
thanks @SirWindfield! Ok, let me see what I can contribute, building was easy on macOS but config not so much. I will try and write it up in detail and make a PR.

By the way, I just commented out the device/control sections and all seemed well, other than a `Failed to register IPv6 receiver` warning... that sound about right?

**Comment by SirWindfield** [comment]
Yes, the fields that contain ALSA in their description only apply for builds that use the `alsa_backend` feature. macOS currently only works with `portaudio` and `rodio`. Those fields should be left out respectively. 

I admit though that the naming is odd and an issue is already open for that (see [v1.0](https://github.com/Spotifyd/spotifyd/milestone/5)). A lot of those changes are breaking and thus will only happen on the v1.0 move.

**Comment by johnalanwoods** [comment]
@SirWindfield thanks, closing this for now, will create a PR when I have the whole end to end flow sussed.

Thanks for quick help.

**Comment by SirWindfield** [comment]
No problem

**Comment by garymh** [comment]
@johnalanwoods Did you ever figure out the launchctl process? I'm in the same boat atm...

**Comment by johnalanwoods** [comment]
@garymh yup sure did. It took me about 2 hours to figure out.

Got it working now as a system daemon, and it's nice.

Do you just need the plist for launchctl or do you need a full guide?

**Comment by garymh** [comment]
@johnalanwoods Excellent! Just the plist would be great!

**Comment by johnalanwoods** [comment]
@garymh no probs bro...


Few gotchas, to bring to your attention...

1) I run it under my username "John", rather than root. I feel it's better contained. So you should update "John" with your username for macOS below (or remove "UserName" to run as root.

2) It doesn't seem to be able to see the config file, so I had to explicitly tell it where to find it in `ProgramArguments`, you need to update that with your config file location.

3) you might be wondering why I have `<string>--no-daemon</string>` when running in daemon mode?! - well without it, launchctl doesn't get a PID for the process and loses it's remit over it. So it's best to include it, there will be no difference in use, nor will you see any log output.

4) macOS tries to start the daemon immediately, and Spotifyd fails if Wifi isn't connected. So I have a keep alive (which retries if it fails to launch on boot), and retries after 30 seconds, which is enough for wifi etc to boot up.

Man it was a ball ache to get this working... works well now tho.



```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>rustlang.opensrc.spotifyd</string>
		<key>ProgramArguments</key>
		<array>
			<string>/usr/local/bin/spotifyd</string>
			<string>--config-path=/users/john/.config/spotifyd/spotifyd.conf</string>
			<string>--no-daemon</string>
		</array>
		<key>UserName</key>
		<string>john</string>
		<key>KeepAlive</key>
		<true/>
		<key>ThrottleInterval</key>
		<integer>30</integer>
	</dict>
</plist>
```

**Comment by garymh** [comment]
Awesome! Thanks so much!

**Comment by johnalanwoods** [comment]
@garymh no probs! shout if you need any help... I run it as a Global Daemon under /Library/LaunchDaemons, 👍

**Comment by SirWindfield** [comment]
> you might be wondering why I have <string>--no-daemon</string> when running in daemon mode?! - well without it, launchctl doesn't get a PID for the process and loses it's remit over it. So it's best to include it, there will be no difference in use, nor will you see any log output.

By default `spotifyd` will fork itself and launch as a daemon. Passing down the `--no-daemon` flag prevents this behaviour. Programs like `launchd` or `systemd` expect the running program to be in the foreground, which means that you need the flag here.

Kind of non-intuitive I guess :D
