### ISSUE TITLE
Need to install dbus to run the daemon

### ISSUE THREAD

**Issue by m3at** [Spotifyd/spotifyd#490]
**Description**
When following the **Installation** instructions on macOS, I got a core dump as `dbus` was not installed.  
This is normal, but I think adding a line suggesting to run `brew install dbus` on macOS might be useful.

**To Reproduce**
1. Download the latest release on a mac were `dbus` has not yet been installed
2. Extract and run `./spotifyd --help`

**Expected behavior**
(work as expected)

**Logs**
<details><summary>Click to show logs</summary>
% ./spotifyd --help
dyld: Library not loaded: /usr/local/opt/dbus/lib/libdbus-1.3.dylib
  Referenced from: /Users/paulelix/Downloads/./spotifyd
  Reason: image not found
[1]    71816 abort (core dumped)  ./spotifyd --help
</details>

**Versions (please complete the following information):**
 - OS: macOS Mojave, 10.14.6
 - Spotifyd: v0.2.24
- cargo: cargo 1.40.0 (bc8e4c8be 2019-11-22)

**Suggested fix**
Add a line such as:
```
On macOS, you might need to install dbus first with `brew install dbus`.
```
This is a very minor nitpick, I imagine most users of spotifyd would be able to find the issue by themselves in a few minutes anyway, so feel free to discard this issue.

**Comment by SirWindfield** [comment]
Which flavour did you download, `full` or `slim`?

**Comment by m3at** [comment]
I downloaded full: `spotifyd-macos-full.tar.gz`

**Comment by andrewkro** [comment]
I had the same as above (downloaded full on macos as well), but also needed to install portaudio

```$ ./spotifyd --help
dyld: Library not loaded: /usr/local/opt/portaudio/lib/libportaudio.2.dylib
  Referenced from: /Users/akroenert/Downloads/./spotifyd
  Reason: image not found
Abort trap: 6
$ brew install portaudio

**Comment by SirWindfield** [comment]
For macOS, portaudio is needed if you use the `portaudio` backend, I think rodio doesn't need it.

**Comment by jveiga** [comment]
Hi, I can't install it on macos Catalina 10.15.3
I tried compilling from tag v0.2.24 
with portaudio 19.6.0 installed, I run spotifyd and it terminates with error code 0
with rodio, I see the same behaviour. 
Let me know if I should create a separate issue Great project!

**Comment by SirWindfield** [comment]
Did you use `cargo build --release --no-default-features --features "portaudio_backend"`?
Termination with exit code 0 sounds good. By default spotifyd will fork itself and run in the background. You can pass down `--no-daemon` to prevent forking, which will display log output to stdout.

**Comment by SirWindfield** [comment]
Commenting on the original issue:
`full` has all optional features enabled, meaning that `dbus_{keyring,mpris}` are getting compiled. That's why you need `dbus` as well (see https://github.com/Spotifyd/spotifyd/blob/9a4e5bac9d55acd5a97d51781c229f670fad9c88/.github/workflows/cd.yml#L21)

In theory MPRIS does work on macOS, but the media buttons on macOS do not send commands over the dbus. I was looking into adding this but couldn't find a rust library that allowed me to listen for keystrokes of those keys.

**Comment by jveiga** [comment]
with --no-daemon, I managed to understand what was wrong 👍

**Comment by xartuu** [comment]
> In theory MPRIS does work on macOS, but the media buttons on macOS do not send commands over the dbus. I was looking into adding this but couldn't find a rust library that allowed me to listen for keystrokes of those keys.

Any updates?
I'm not hiding the fact that this would be a key feature - controlling music with multimedia keys from the keyboard on MacBook.

**Comment by eladyn** [comment]
In theory, there are crates that offer cross-platform ways to offer media key handling (like [`souvlaki`](https://crates.io/crates/souvlaki)). Unfortunately, Windows as well as macOS [seem to require an open window](https://github.com/Sinono3/souvlaki/issues/23#issuecomment-1144243919) for media keys to work? Which obviously isn't a thing, we want to do with `spotifyd`.

But you have different ideas, how this could be achieved, I'm open to suggestions!
