### ISSUE TITLE
Replace non Rust native dependencies

### ISSUE THREAD

**Issue by marcelbuesing** [Spotifyd/spotifyd#497]
**Is your feature request related to a problem? Please describe.**
Cross compilation is a real pain whenever you have libraries which rely on some C library that is called via FFI.  What could be a simple `cargo build --release --target arm-unknown-linux-gnueabihf` becomes a fight where you end up setting up a custom Docker image that provides all the dependencies you need. Same in the CI e.g. [here](https://github.com/Spotifyd/spotifyd/blob/a789b49c3d8bd0e4efdbb41587e5f4f61f602ff4/.github/workflows/cd.yml#L73).

**Describe the solution you'd like**
Replace dependencies that rely on such libraries or use a particular feature e.g. spotify requires libssl due to rspotify, if rspotify would allow using rustls ([MR](https://github.com/ramsayleung/rspotify/pull/76)) one would no longer need the library to build spotifyd (but if you prefer openssl you could still default to openssl but allow rustls via a feature).
```
cargo tree -p openssl-sys -i
openssl-sys v0.9.53
├── native-tls v0.2.3
│   ├── hyper-tls v0.3.2
│   │   └── reqwest v0.9.17
│   │       └── rspotify v0.7.0
│   │           └── spotifyd v0.2.24 (/home/abc/github-thirdparty/spotifyd)
│   └── reqwest v0.9.17 (*)
└── openssl v0.10.26
    └── native-tls v0.2.3 (*)
```

I think this is a long term thing since for crates such as dbus there are no stable alternatives yet, although e.g. [zbus](https://gitlab.freedesktop.org/zeenix/zbus) might be soon. 

**Describe alternatives you've considered**
One could provide custom images based on the existing [cargo cross](https://github.com/rust-embedded/cross#custom-docker-images)-images.

**Additional context**
```
cargo build --release --target arm-unknown-linux-gnueabihf                                            
...
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/abc/github-thirdparty/spotifyd/target/release/build/alsa-sys-5d1f37a332999f03/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys v0.9.53`

Caused by:
  process didn't exit successfully: `/home/abc/github-thirdparty/spotifyd/target/release/build/openssl-sys-8b8450416f811259/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR
ARM_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR
ARM_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_DIR
ARM_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = arm-unknown-linux-gnueabihf
openssl-sys = 0.9.53

', /home/abc/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.53/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by SirWindfield** [comment]
I've actually tried to use `cross` prior but it didn't work properly since some dependencies were not available for the used ubuntu version. The author doesn't bump up the version to keep the needed `libc` version as low as possible (iirc).

I guess something like this can be put behind feature flags as well, making it optional for people to use. I do agree though that it would help out cross compilation as well as it being a long term thing

**Comment by slondr** [comment]
rspotify merged https://github.com/ramsayleung/rspotify/pull/76 back in June, is this still an issue?
