### ISSUE TITLE
Panic on `Result::unwrap()` / Error "Protocol not available" 

### ISSUE THREAD

**Issue by iafan** [Spotifyd/spotifyd#50]
I'm getting this immediately after launching `spotifyd --no-daemon`:

```
00:05:07 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 92, message: "Protocol not available" } }
```

Any ideas what might be the reason? I'm running the latest binary (spotifyd-2017-04-23-armv7.zip) on Orange Pi Lite / Armbian, and have the config file properly configured. I'm a premium Spotify user. Adding `--verbose` flag doesn't help much (I only see that the config values are being picked up properly).

**Comment by SimonPersson** [comment]
Is that with spotifyd in discovery mode, or with username and password specified? I've seen some issues like that with discovery mode.

**Comment by iafan** [comment]
That's with username/password specified.

**Comment by SimonPersson** [comment]
Then I have no idea. You could try to build from source instead, I wouldn't be surprised if there are issues with cross compilation.

**Comment by iafan** [comment]
Is the `{ code: 92, message: "Protocol not available" }` response coming from the Spotify server itself? This looks more like an unexpected error that spotifyd gets from the server for whatever reason (which is not surprising knowing that it's an unofficial client, and Spotify might want to block requests from such clients).

**Comment by SimonPersson** [comment]
No, I'm quite sure that message is from the kernel. Perhaps some syscall got messed up in cross compilation, or something.

**Comment by iafan** [comment]
I found this relevant discussion:  http://stackoverflow.com/questions/37514180/python-server-socket-error-errno-92-protocol-not-available

Specifically:

> In my case it ended up being the eventlet library, which is only compatible with Linux Kernel versions >= 3.9. (As found in source code of this file: https://github.com/eventlet/eventlet/blob/f9a3074a3b75f17f76cc04a693dc48a367b99861/eventlet/convenience.py which tried to run sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)).

> In my case I was using Flask-SocketIO also was able to switch to gevent, which does not have this limitation.

So the question is: does spotifyd use eventlet library as well? Because the Armbian system that I have uses 3.4.113 kernel, and that would explain the issue.

**Comment by SimonPersson** [comment]
No, eventlet is only for Python as far as I know. It is possible that some library indirectly used by spotifyd makes use of more modern kernel features. Perhaps conditionally, meaning it'd work if you compile it yourself on an older kernel.

**Comment by iafan** [comment]
@SimonPersson thanks, that gives me some hope! )

**Comment by SimonPersson** [comment]
Could you check if the latest version has this issue as well? If the issue persists, could you try to build from source? There have been issues related to the automated cross compiling.

**Comment by iafan** [comment]
Yes, the latest release gives exactly the same error.

I also tried building from source, but get some obscure error:
```
error: failed to run custom build command for `alsa-sys v0.1.1`
process didn't exit successfully: `/home/pi/spotifyd/spotifyd-master/target/release/build/alsa-sys-827209bf5f925246/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Not sure which 'alsa' library it complains about and how to install it.

**Comment by SimonPersson** [comment]
The compilation error is because you're missing the alsa library. On Debian
base distros, it's installed with `apt-get install alsa-lib-dev`.

**Comment by molikuner** [comment]
Hello,
I have the same problem. I cloned the latest git (master) and compiled it with cargo.
I had no compilation error. I'm on a Debian (all up to date)

**Comment by iafan** [comment]
Finally managed to build this from sources on Orange Pi, but still get exactly the same error as originally reported.

**Comment by therealmuffin** [comment]
Same error here on runtime. Got a fresh clone from github, compiled on Raspbian Jessie. All went without errors (though had to set debug to false and opt-level to 1 or less to prevent errors). Also compiled on Voyage Linux (Debian based), same error on runtime

**Comment by f-breidenstein** [comment]
Hi,
I also get the `Protocol not available` error on my OrangePI running Debian 8.9.
Regardless of using the provided arm binary or compiling by myself.

If this is a kernel problem, maybe it's the fault of the really old 3.4 kernel in the OrangePI images?
I will try with one of the OrangePI Dev-Images running a 4.11 kernel, and report back if this solved the issue.

**Comment by HausnerR** [comment]
Hi,
I had the same issue and it's probably related with librespot becouse raspotify have exact same problems.

Orange PI + Armbian.

And as @therealmuffin said - disabling discovery workaround issue - if alsa plays something else and then librespot try to play something too - again unwrap problem appears (but in different place).

**Comment by f-breidenstein** [comment]
Just flashed a new SD Card with Ubuntu Xenial for my OrangePi PC and downloaded the precompiled armv7 binary. Works like a charm now :)

**Comment by SimonPersson** [comment]
I'll close this issue, feel free to reopen if this is still an issue on the latest commit on master!
