### ISSUE TITLE
Running Spotifyd headless on RaspberryPi

### ISSUE THREAD

**Issue by johnalanwoods** [Spotifyd/spotifyd#504]
**Description**
When running the latest release of Spotifyd headless (without desktop env) on RpiB, I get this error on launch: `D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`

**To Reproduce**
Run latest release on RpiB

**Expected behavior**
Launch without issue

**Logs**
Config:

```
[global]
username = xxx
password = yyy
backend = alsa
device = alsa_audio_device
mixer = PCM
volume-control = softvol
#onevent = command_run_on_playback_event
device_name = SpotiPi
bitrate = 320
cache_path = /home/pi/.spotifycache
volume-normalisation = true
```

<!-- if you compiled spotifyd yourself. Alsa backend enabled by default unless compiled with the 
**Versions (please complete the following information):**
OS: Linux Rpi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Spotifyd: spotifyd 0.2.24

**Error Message**
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)

**Comment by johnalanwoods** [comment]
@SirWindfield - does Spotifyd work without a desktop env on the raspberry pi?

**Comment by SirWindfield** [comment]
It should work yes, but MPRIS will not work without a user dbus session. Someone posted a workaround here though: https://github.com/Spotifyd/spotifyd/issues/244#issuecomment-579456290

**Comment by johnalanwoods** [comment]
@SirWindfield thanks for the help!

I got further, i.e. the app now starts! :)

However seeing this error and no sound is coming out of the Pi (running Rasbian)...

```
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Using alsa sink
Invalid CTL alsa_audio_device
Couldn't read volume from alsa device with name "alsa_audio_device".
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL alsa_audio_device
Couldn't set volume: Error("snd_mixer_attach", Sys(ENOENT))

ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM alsa_audio_device
Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
Could not start audio: Alsa error: PCM open failed
```

Any ideas?

**Comment by johnalanwoods** [comment]
Cracked it! 

@SirWindfield - working perfectly now!

just needed to set the `device = default`, which is the ALSA device name on the Pi.

This is too cool.
