### ISSUE TITLE
add a way to let users use their own Spotify client id for API requests

### ISSUE THREAD

**Issue by SirWindfield** [Spotifyd/spotifyd#507]
Currently one single token for all users is used and the rate limit can be reached that way. Users should be able to use their own client id.

Should the current one be removed completely?

**Comment by roqueeee** [comment]
Ok, so I created my own client id at [https://developer.spotify.com/dashboard/applications](url).

Now when I set my own client id as an environment variable or if I change the client id in dbus_mpris.rs and compile from source, spotifyd panics and restarts when I try to connect to it.

journalctl output:

`error 400 for uri hm://keymaster/token/authenticated?client_id=*redacted*&scope=user-read-playback-state,user-read-private,user-read-birthdate,user-read-email,playlist-read-private,user-library-read,user-library-modify,user-top-read,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-read,user-follow-modify,user-read-currently-playing,user-modify-playback-state,user-read-recently-played

Caught panic with message: called `Result::unwrap()` on an `Err` value: MercuryError`

Any ideas?

**Comment by SirWindfield** [comment]
I actually didn't test it as I was pretty sure that it would work. I just changed the client id that is being used. I am testing it right now. No clue what is going wrong though :)

**Comment by SirWindfield** [comment]
I don't think that it is a normal CLIENT_ID that can be created at the page you linked earlier @roqueeee. `librespot-java` has an embedded ID as well and that one works too.

I think it's a special idea that has been generated. No clue where though. @SimonPersson could you help us out?

**Comment by roqueeee** [comment]
Alright, I believe I found the issue.

https://github.com/Spotifyd/spotifyd/blob/47bb59f4f5a752170dea12b38448f205c2c30036/src/dbus_mpris.rs#L41

user-read-birthdate is not a scope listed in [Authorization Scopes](https://developer.spotify.com/documentation/general/guides/scopes/).

When I tried to create an access token through [Authorization Code Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow) with the scopes in dbus_mpris.rs the server gave me an "Illegal scope" response. Without user-read-birthdate it worked.

After compiling without the user-read-birthdate scope in dbus_mpris.rs and with my own client id there's no more errors and apparently no more rate limiting happening.

Maybe spotifyd uses a client id from when user-read-birthdate was a thing?

**Comment by SirWindfield** [comment]
Yep, seems that that is the case! Great finding, thank you!

**Comment by varac** [comment]
@SirWindfield I consider this a very useful addition which should be handled (also) by the config file, not only by an EVN variable. What do you think ? (And no sorry, I don't speak rust at all)

**Comment by SirWindfield** [comment]
The current env variable is more of a hot fix than anything else. There are some methods inside of `librespot` that would allow us to fetch some metadata from there. I'd rather not introduce a new config value to just remove it later on.

The goal would probably be to make changes to upstream `librespot` to allow it to provide all metadata we need.

**Comment by AndydeCleyre** [comment]
I don't think this is yet documented anywhere.
