### ISSUE TITLE
Could not set to repeat one song

### ISSUE THREAD

**Issue by hulloanson** [Spotifyd/spotifyd#514]
**Description**
I could not set spotifyd to repeat one song through other devices.

**To Reproduce**
1. Build a release from the master branch (It was commit 006306edb1102c17e1585cad8cc5b7d6efcefa15)
2. Launch spotifyd with the following configuration file:
```
[global]
username = [hidden]
password = [hidden]
backend = pulseaudio
device_name = spotifyd
bitrate = 320
cache_path = /home/ycl/.spotifyd_cache
no_audio_cache = false
volume_normalisation = false
zeroconf_port = 1234
device_type = computer
```
3. Select spotifyd as play device
4. Play a song.
5. Click repeat button until repeat one sign appears.
![image](https://user-images.githubusercontent.com/9977536/74454779-5a5d3780-4ebf-11ea-8e6c-fa0102e625bc.png)

**Expected behavior**
Repeat one sign should appear at most 2 clicks (no-repeat -> repeat -> repeat-one).

**Logs**
The log was too long to be pasted here. See here: [spotifyd.log](https://github.com/Spotifyd/spotifyd/files/4199492/spotifyd.log)

**Versions (please complete the following information):**
 - OS: Debian Buster
 - Spotifyd: 006306edb1102c17e1585cad8cc5b7d6efcefa15
- cargo: cargo 1.41.0 (626f0f40e 2019-12-03)

**Additional notes**
I tried changing repeat mode on both my Android and web spotify clients.

**Comment by AlekEagle** [comment]
Same issue

**Comment by robinvd** [comment]
we use librespot for playback, and i dont see any option there for single repeat. repeat is a bool and thus has only on/off, so i think it might be a missing feature from them

**Comment by MonstrousOgre** [comment]
It seems to work fine in ncspot and I know they use librespot as well

**Comment by robinvd** [comment]
@MonstrousOgre thanks! that is very good to known. Ill investigate what we do differently, as this is definitly a nice feature to have

**Comment by OrangeFran** [comment]
`ncspot` does not use spotify connect but something different from the librespot library. I think this is the reason.

**Comment by robinvd** [comment]
from a quick look they seem to use librespot for the playback, but control the next/prev themselves. We could also do that (PRs welcome), but ill mark this as blocked by librespot for now
