### ISSUE TITLE
amd64 binary segfaults with --no-daemon

### ISSUE THREAD

**Issue by zjttoefs** [Spotifyd/spotifyd#52]
According -v it does not always crash in exactly the same place.

Otherwise it runs and registers, but dies when asked to play sound.

**Comment by SimonPersson** [comment]
Could you try to run it through GDB to generate a stack trace? Compiling it by yourself might work better as well.

**Comment by zjttoefs** [comment]
Did some testing with the prebuild binary. Inconclusive. Got it to crash with and without --no-daemon.

If I was seriously interested in running on amd64, I'd rebuild there and have a look. For the moment my conclusion would be not to use the binaries (remove them maybe?).
