### ISSUE TITLE
spotifyd not shown as device after starting/enabling service.

### ISSUE THREAD

**Issue by myahenochs** [Spotifyd/spotifyd#521]
Hi!
spotifyd.service is in /etc/systemd/user, and 
`systemctl --user enable spotifyd.service` and
`systemctl --user start spotifyd.service` 
have been run as per instructions.
From both the Spotify application and spt, spotifyd is not shown as a device, despite the daemon showing in my processes.
The contents of my config:
```
username = **username**
password = **password**
backend = pulseaudio
device_name = homePC-spotifyd
bitrate = 320
volume-normalisation = true
normalisation-pregain = -10
```
Issue #393 seems very similar, except the spotifyd binary is indeed present in /usr/bin.

**Comment by andevellicus** [comment]
I'm having the exact same issue.

**Comment by Pi-George** [comment]
Same issue

**Comment by Spinnerthing** [comment]
I have a similar issue, maybe not exactly the same though, spt and web spotify cannot see the spotifyd device, that is until I log in to the proper spotify client which can see it and then after that spt and web client can see it too straight away.

**Comment by Spinnerthing** [comment]
My issue turned out to be config file not in the right location meaning it seemed to be in discovery mode because of no username/password set.

**Comment by myahenochs** [comment]
@Spinnerthing Where did you put the config file? I have it in ~/.config/spotifyd.

**Comment by myahenochs** [comment]
After running 'spotifyd --config-path ~/.config/spotifyd/spotifyd.config --no-daemon' (an idea after looking at #523 haha), this message hangs here:
```
$ spotifyd --config-path ~/.config/spotifyd/spotifyd.config --no-daemon
Loading config from "/home/myah/.config/spotifyd/spotifyd.config"
No proxy specified
Using software volume controller.
```
The command goes through when I omit `--no-daemon`, but no fix.
Quite honestly, I'm assuming user error on my part and something is wrong with my config.

**Comment by Spinnerthing** [comment]
@myahenochs For me it was a silly typo for  ~/.config/spotify/ instead of spotifyd but yours does still sound like a config issue as it sounds similar to what problems I had when my config was wrong and it was going in to discovery mode. Is it the official spotify client you've tried to connect up with it to on the same network to test?

**Comment by Pi-George** [comment]
Same reason for me, typo in the config path. Now it's working

**Comment by arpena** [comment]
Just my .02, when you set spotifyd as an user based service using systemctl, the user should be logged in for the service to be running. Look at my changes to https://github.com/Spotifyd/spotifyd/wiki/Installing-on-a-Raspberry-Pi, specifically you should run "sudo loginctl enable-linger <username>" to let systemd to run the service with no user logged in

**Comment by myahenochs** [comment]
@arpena I'm on my own desktop computer, so I'm always logged in. But thank you for the tip!

**Comment by myahenochs** [comment]
@Spinnerthing Official client (from my PC and my phone) only show each other and the random devices from the rest of the building. Really I'm wondering what could be wrong in my config. I've changed it around and tried things since my first post, and no configuration seems to allow it to load, not even empty or with just my username/password. Is hanging on that command something that happens when the config is wrong? Or could it be something else that makes it hang?

**Comment by myahenochs** [comment]
I ran `spotifyd --config-path ~/.config/spotifyd/spotifyd.config --no-daemon --verbose` and...
```
Loading config from "/home/myah/.config/spotifyd/spotifyd.config"
CliConfig { config_path: Some("/home/myah/.config/spotifyd/spotifyd.config"), no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: None, password: None, password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: None, bitrate: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None } }
Found shell "/bin/bash" using SHELL environment variable.
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=16
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:35751
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
adding I/O source: 8388610
registering with poller
loop process - 1 events, 0.000s
event Writable Token(8388610)
loop process - 1 events, 0.000s
adding I/O source: 12582915
registering with poller
event Writable Token(12582915)
loop process - 1 events, 0.000s
consuming notification queue
scheduling Read for: 0
scheduling Read for: 1
```
With a poll loop after.

**Comment by myahenochs** [comment]
Just running the regular `spotifyd --config-path ~/.config/spotifyd/spotifyd.config` after that seemed to allow the device to be shown, but now I have no audio, like @Pi-George. That's a different issue so as far as I'm concerned, this is solved. Thank you everyone for your help!

**Comment by Spinnerthing** [comment]
@myahenochs Just a heads up the reason you have to use the --config-path is because the config file should be called spotifyd.conf and not spotifyd.config

**Comment by Pi-George** [comment]
> Just running the regular `spotifyd --config-path ~/.config/spotifyd/spotifyd.config` after that seemed to allow the device to be shown, but now I have no audio, like @Pi-George. That's a different issue so as far as I'm concerned, this is solved. Thank you everyone for your help!

I solved my no sound issue by compiling from source with pulse audo feature flag then setting pulse audio as the device. Don't know if this helps you.

**Comment by myahenochs** [comment]
@Pi-George My issue was solved by using alsa backend and having `default` for my device, so it just goes through my system default. I switch between devices a lot and it works like a charm.

@Spinnerthing I realized that when I saw the name of the configuration files in other issues, and figured I was running the command to change the config path anyway so I left it. I changed it back to the default since then.

**Comment by SirWindfield** [comment]
You guys can use the `rodio_backend`, which shouldn't require any configuration and work out of the box as far as I know.

**Comment by gloatoriginal** [comment]
Hey I wasn't able to get spotifyd to work without using `--no-daemon` 
_example_: `spotifyd --no-daemon` this caused a massive amount of text to be splurted to the screen so I found a SO post that mentioned using `setsid` to allow process to run in the background, this finally works -> `setsid spotifyd --no-daemon &>/dev/null`

**Comment by yaayimanalien** [comment]
this is how far i got. can't really figure out what's wrong with it :/
```sh
$ spotifyd --config-path ~/.config/spotifyd/spotifyd.conf --no-daemon
Loading config from "/home/winter/.config/spotifyd/spotifyd.conf"
Using alsa volume controller.
Failed to resolve Access Point: error trying to connect: dns error: failed to lookup address information: Name or service not known
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
Using proxy "http://proxy.example.org:8080/"
failed to connect to spotify: Cannot create session: failed to lookup address information: Name or service not known
```
