### ISSUE TITLE
error sending packet Os

### ISSUE THREAD

**Issue by varac** [Spotifyd/spotifyd#532]
**Description**

On startup I always get this error msg:

`spotifyd[24427]: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }`

**To Reproduce**
1. start spotifyd
2. examine logs

**Expected behavior**

There should not be error msgs on startup, or at least some guidance what this is about.

**Logs**
<details><summary>Click to show logs</summary>

  

❯ /home/varac/bin/spotifyd --no-daemon --verbose
Loading config from "/home/varac/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: None, password_cmd: Some("taken out for privacy"), use_keyring: false, on_song_change_hook: None, cache_path: Some("/home/varac/.cache/spotifyd"), no-audio-cache: true, backend: Some(PulseAudio), volume_controller: Some(SoftVolume), device: None, control: None, mixer: None, device_name: Some("spt"), bitrate: Some(Bitrate160), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: None, proxy: None, device_type: Some(Computer) } }
Found user shell: Some("/bin/zsh")
No password specified. Checking password_cmd
Running "pass show --password www/spotify.com/..." using "/bin/zsh"
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=4
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:40913
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
adding I/O source: 8388610
registering with poller
loop process - 1 events, 0.000s
event Writable Token(8388610)
loop process - 1 events, 0.000s
adding I/O source: 12582915
registering with poller
event Writable Token(12582915)
loop process - 1 events, 0.000s
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://apresolve.spotify.com/")
resolving host="apresolve.spotify.com", port=80
consuming notification queue
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 2
sending packet to V6([ff02::fb]:5353)
error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
scheduling Read for: 3
loop poll - 956.457µs
loop time - Instant { tv_sec: 96556, tv_nsec: 368306179 }
loop process, 18.788µs
received packet from V4(192.168.178.42:5353)
received packet from V4(192.168.178.42:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 151.696µs

</details>

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: ubuntu 19.10
 - Spotifyd: dde6e6f8676f357f96aaf974248d66c34b5be204
- cargo: 1.39.0

**Comment by waylandc** [comment]
Getting same error


> 
> Using alsa volume controller.
> error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
> Failed to resolve Access Point: HTTP error
> Using fallback "ap.spotify.com:443"
> Connecting to AP "ap.spotify.com:443"
> Using proxy "http://localhost/callback:8080"
> Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
 
OS: archlinux 5.6.2
cargo: 1.44 nightly
Spotify: 0.2.24  99f058a7010e5da5425b7c572efb9f1ed8f866e8 (compiled from src)


`
backend = alsa

device = hw:v15 # omit for macOS

control = hw:v15 # omit for macOS

mixer = PCM

volume_controller = alsa  # use softvol for macOS

on_song_change_hook = command_to_run_on_playback_events

device_name = thelab

bitrate = 320

cache_path = /home/wayc/.cache/spotify/Storage

no_audio_cache = true

volume_normalisation = true

normalisation_pregain = -10

zeroconf_port = 1234

proxy = http://localhost/callback:8080

device_type = speaker`
