### ISSUE TITLE
Consider allowing (only) Spotify Connect for free accounts

### ISSUE THREAD

**Issue by coxackie** [Spotifyd/spotifyd#536]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but here is a use-case to consider: someone with Spotify free account wants to use an external client (for example, mobile app) and cast music to the desktop. If `spotifyd` allows the use of Spotify Connect for free accounts, this could be possible. Right now this is possible using the official Spotify client, but the latter uses up so many resources and memory that it is really preposterous.

**Describe the solution you'd like**
Not sure if this is possible, but one may *only* allow Spotify Connect for free accounts. It is understandable that you do not want to use the daemon to fetch music with free accounts, but only allowing it to stream from other official Spotify apps (that would play all the ads and everything) should not violate any terms of service.

**Describe alternatives you've considered**
Getting a Premium account - obviously    :P

**Comment by SirWindfield** [comment]
In order to make this work the whole ad system and restricted skips have to be implemented and as far as I know no one has even started to work on them. It’s a huge pain to reverse engineer it and with little effective value gain. I’m sorry but I do not see this being implemented in the near future.

**Comment by coxackie** [comment]
I fully understand that one cannot expect that the whole ad system and restricted skips are implemented for free accounts in `spotifyd`. I am sorry for following up on this, and this may be naive, but I was just asking whether *only* the spotify connect protocol from an outside source to desktop/laptop could be implemented for free accounts. Maybe I am mistaken, but if one would connect (say) a phone to desktop via spotify connect, would it not still be the phone that controls the streaming? If this is the case, why would the ad system and restricted skips need to be implemented?

**Comment by SirWindfield** [comment]
Maybe I am just not understanding it correctly.

So your exact goal is to start `spotifyd` on a device (say a computer named `A`). You then want to connect to `A` through your phone and use `A` as the playback device but keep fetching songs from your phone. Am I right?

> If this is the case, why would the ad system and restricted skips need to be implemented?

Spotify Connect works by telling a protocol compatible device your current listening context. It then passes full control over it to the client, meaning your phone/tablet that you used to select the connect device is not actively responsible for fetching songs. That control is handed over to the device you selected.

> [...] would it not still be the phone that controls the streaming?

The controlling of the playback on `A` (doesn't matter which app or program you use) is fully done through their Web API calls. The API then tells the connect device to skip or pause. So yes, technically, controlling is still done by the phone or other clients. But that doesn't help us with free accounts.

That means that there is literally no way to stream audio from the server over your phone to your speaker using `spotifyd`.

There are other alternatives though. You can just use Bluetooth for example. It's literally your use case. You just want to get audio from your phone to another device. Dongles are around 10 bucks each.

**Comment by coxackie** [comment]
Thanks for the clarification. I did not know that Spotify Connect passes full control over it to the new client. I understand now better. Of course I can stream through bluetooth, but this means fast phone batter depletion and crappy connections. I was hoping that wifi takes care of the streaming, but control on what is played stays with the initial client. Oh, well...

**Comment by SirWindfield** [comment]
Sorry to disappoint you. Sadly, Chromecast (/Audio) only works with premium as well.

**Comment by niizam** [comment]
> In order to make this work the whole ad system and restricted skips have to be implemented and as far as I know no one has even started to work on them. It’s a huge pain to reverse engineer it and with little effective value gain. I’m sorry but I do not see this being implemented in the near future.

this is the best spotify adblock for linux, maybe useful to use
https://github.com/abba23/spotify-adblock-linux

**Comment by coxackie** [comment]
@niizam Yeah, well, quite off topic here, and not the point of the post.
