### ISSUE TITLE
Cargo build aborts due to error on Ubuntu 19.10

### ISSUE THREAD

**Issue by jrswab** [Spotifyd/spotifyd#538]
**Description**
`cargo build --release` fails and aborts due to error on Ubuntu 19.10

**To Reproduce**
Install Ubuntu 19.10
Follow the build from source instructions for Ubuntu.

**Expected behavior**

**Logs**
<details><summary>Click to show logs</summary>

error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
    --> /home/jaron/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
       |
130 |             len: bytes.len(),
       |                   ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Ubuntu 19.10
 - Spotifyd: Pulled from repo to bulid from source
- cargo: 1.38.0

**Comment by SirWindfield** [comment]
Update your rust installation :)
