### ISSUE TITLE
spotifyd errors on start

### ISSUE THREAD

**Issue by wozniak** [Spotifyd/spotifyd#539]
**Description**

**To Reproduce**
1. Clone the repo
2. `cargo run`
4. spotifyd errors

**Expected behavior**
spotifyd starts

**Logs**
<details>
<summary>Click to show logs (with RUST_BACKTRACE=full)</summary> 
<pre><code>
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: Some(stack backtrace:
   0: error_chain::make_backtrace
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.11.0/src/lib.rs:616
   1: <error_chain::State as core::default::Default>::default
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.11.0/src/lib.rs:710
   2: syslog::errors::Error::from_kind
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/<::error_chain::error_chain::impl_error_chain_processed macros>:72
   3: <syslog::errors::Error as core::convert::From<std::io::error::Error>>::from
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/errors.rs:1
   4: <T as core::convert::Into<U>>::into
             at /usr/src/rustc-1.40.0/src/libcore/convert.rs:547
   5: syslog::unix_connect
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/lib.rs:210
   6: syslog::unix::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/lib.rs:180
   7: core::result::Result<T,E>::or_else
             at /usr/src/rustc-1.40.0/src/libcore/result.rs:761
   8: syslog::unix
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/lib.rs:177
   9: spotifyd::setup_logger
             at src/main.rs:40
  10: spotifyd::main
             at src/main.rs:63
  11: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: std::rt::lang_start
             at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  16: main
  17: __libc_start_main
  18: _start
) })), backtrace: Some(stack backtrace:
   0: error_chain::make_backtrace
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.11.0/src/lib.rs:616
   1: <error_chain::State as core::default::Default>::default
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.11.0/src/lib.rs:710
   2: syslog::errors::Error::from_kind
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/<::error_chain::error_chain::impl_error_chain_processed macros>:72
   3: <syslog::errors::Error as core::convert::From<std::io::error::Error>>::from
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/errors.rs:1
   4: <T as core::convert::Into<U>>::into
             at /usr/src/rustc-1.40.0/src/libcore/convert.rs:547
   5: syslog::unix_connect
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/lib.rs:210
   6: syslog::unix::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/lib.rs:180
   7: core::result::Result<T,E>::or_else
             at /usr/src/rustc-1.40.0/src/libcore/result.rs:761
   8: syslog::unix
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syslog-4.0.1/src/lib.rs:177
   9: spotifyd::setup_logger
             at src/main.rs:40
  10: spotifyd::main
             at src/main.rs:63
  11: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: std::rt::lang_start
             at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  16: main
  17: __libc_start_main
  18: _start
) })', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55fde03b1e04 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6001c6574450335d
   1:     0x55fde03ca63d - core::fmt::write::h1371734f6a7c7bc2
   2:     0x55fde03afbd5 - std::io::Write::write_fmt::h5ee928f19b08369c
   3:     0x55fde039a99e - std::panicking::default_hook::{{closure}}::h6b521085a6513c53
   4:     0x55fde039a6b0 - std::panicking::default_hook::h3e3fe9b536fd99f6
   5:     0x55fde039b09b - std::panicking::rust_panic_with_hook::h3d899269d6b7f8f7
   6:     0x55fde039ac3e - std::panicking::continue_panic_fmt::h22635bd1aa2db87e
   7:     0x55fde039ab26 - rust_begin_unwind
   8:     0x55fde03cec0e - core::panicking::panic_fmt::h47a8c62224276236
   9:     0x55fde03c9b17 - core::result::unwrap_failed::hacfad02119053b92
  10:     0x55fddf459030 - core::result::Result<T,E>::expect::h27fa5d5aa4a9d67a
                               at /usr/src/rustc-1.40.0/src/libcore/result.rs:960
  11:     0x55fddf44e5c3 - spotifyd::setup_logger::h67f208487d1f1007
                               at src/main.rs:40
  12:     0x55fddf44e802 - spotifyd::main::hebfc65739fd712e0
                               at src/main.rs:63
  13:     0x55fddf4875a0 - std::rt::lang_start::{{closure}}::h305030bcf3db15a6
                               at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  14:     0x55fde039aac3 - std::panicking::try::do_call::h405fa073712ab5d5
  15:     0x55fde03b4d5a - __rust_maybe_catch_panic
  16:     0x55fde03a32e9 - std::rt::lang_start_internal::he63ceb3eba03dd55
  17:     0x55fddf487579 - std::rt::lang_start::h48cf6bd141113cd5
                               at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  18:     0x55fddf44f21a - main
  19:     0x7f367cde0e0b - __libc_start_main
  20:     0x55fddf4191fa - _start
  21:                0x0 - <unknown>
</code></pre>
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Debian GNU/Linux bullseye/sid
 - Spotifyd: commit 99f058a7010e5da5425b7c572efb9f1ed8f866e8
- cargo: 1.39.0

**Additional context**
- run on a chroot from KISS Linux
- `--help` works

**Comment by Yarn** [comment]
My guess for what is happening here is that a call to https://docs.rs/syslog/5.0.0/syslog/fn.unix.html is failing since `/dev/log` and `/var/run/syslog` don't exist.

Could you try it with `cargo run -- --no-daemon`. It looks like it shouldn't use syslog in in that mode.

Assuming that's the issue I guess we would add to param to disable all logging targets? I don't think silently doing no logging at all is a good idea. We would probably want to provide a better error that suggests using the parameter.

**Comment by sirtomato999** [comment]
that works, not very ideal though
