### ISSUE TITLE
device_name not honoured

### ISSUE THREAD

**Issue by zjttoefs** [Spotifyd/spotifyd#54]
Minor issue:

Despite using device_name in the config file the daemon still registers as "Spotifyd".
Defaulting to the hostname might be a sensible choice as well (that's what I'm trying to set).

**Comment by zjttoefs** [comment]
Looks like setting on the command line doesn't work either. 

Again, cosmetic problem. This is lightweight and quite awesome!

**Comment by wedi** [comment]
This was working in an earlier version. After upgrading to the [current release](https://github.com/Spotifyd/spotifyd/releases/tag/untagged-b5f358442cf723fb9b50) this went away.

I extracted the version this was working in from a file called `spotifyd-2017-03-27-armv7.zip`. But this does not correspond to a [release](https://github.com/Spotifyd/spotifyd/releases) date...

**Comment by xmarinusx** [comment]
Looks like this is fixed in the latest release!

**Comment by zjttoefs** [comment]
Yup, works! Thanks everyone!
