### ISSUE TITLE
Cannot compile "missing field `autoplay` in initializer of `librespot_core::config::ConnectConfig`

### ISSUE THREAD

**Issue by stevensonmt** [Spotifyd/spotifyd#541]
**Description**

Trying to update from v0.2.23 to v0.2.24 cargo returns the error in the tittle related to two instances at `src/setup.rs:90:9` and `src/main_loop.rs:166:21`.

**To Reproduce**

`cargo install-update spotifyd`

**Expected behavior**

Successful compilation.

**Versions (please complete the following information):**
 - OS: Manjaro 
 - Spotifyd: 0.2.24
- cargo: 1.41.0

The source code on github for setup.rs and main_loop.rs seems to provide the asked for autoplay field in the ConnectConfig struct. Is the wrong version pushed to crates.io somehow?

**Comment by stevensonmt** [comment]
when I clone the repo and build locally, everything compiles successfully.

**Comment by stevensonmt** [comment]
Using the `cargo-download` subcommand I downloaded the version that crates.io is shipping. Indeed `main_loop.rs:166` creates a ConnectConfig struct without an autoplay field:
```
let (spirc, spirc_task) = Spirc::new(
                    ConnectConfig {
                        name: self.spotifyd_state.device_name.clone(),
                        device_type: DeviceType::default(),
                        volume: mixer.volume(),
                        linear_volume: self.linear_volume,
                    },
                    session.clone(),
                    player,
                    mixer,
                );
```
and `setup.rs:90` has 
```
#[allow(clippy::or_fun_call)]
    let discovery_stream = discovery(
        &handle,
        ConnectConfig {
            name: config.device_name.clone(),
            device_type: DeviceType::default(),
            volume: mixer().volume(),
            linear_volume,
        },
        device_id,
        zeroconf_port,
    )
    .unwrap();
```
The date stamp of both `main_loop.rs` and `setup.rs` is 2019-12-07 02:36 when downloaded from crates.io, but the most recent versions in the repo are from a 2020-02-10 commit. Indeed the `autoplay` change occurred in that commit:
https://github.com/Spotifyd/spotifyd/commit/2b91a0c11d01807a3220d1177008c80a8dcc2662#diff-e1bc7cdd237f6a2102093f1dd05cc91d

**Comment by SirWindfield** [comment]
Something didn't go right during publishing. I can take a look tmrw :)

**Comment by jslpc** [comment]
Any update on this? Running into the same error with no luck.

**Comment by jslpc** [comment]
Any update on this?

**Comment by SirWindfield** [comment]
I will push a new release once a new feature has been added. I still do not know why the crates.io version differs. Maybe I set the git tags wrong and that caused it.

**Comment by SirWindfield** [comment]
I will publish a new release this weekend if there aren't any compilation errors happening due to the wrong protobuf version :)
