### ISSUE TITLE
Provide spotifyd-linux-armv6-full binary

### ISSUE THREAD

**Issue by bluepuma77** [Spotifyd/spotifyd#545]
My Raspberry Pi Zero fails building the sources, specifically `librespot-protocol`. I think it's a memory issue with only 512MB RAM, during compilation you can watch how memory is eaten up.

```
$ cargo build --release --no-default-features --features pulseaudio_backend,dbus_keyring,dbus_mpris
[...]
   Compiling librespot-protocol v0.1.1
error: could not compile `librespot-protocol`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name librespot_protocol /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C codegen-units=1 -C metadata=23756c3a70c8e08f -C extra-filename=-23756c3a70c8e08f --out-dir /home/pi/spotifyd/target/release/deps -L dependency=/home/pi/spotifyd/target/release/deps --extern protobuf=/home/pi/spotifyd/target/release
```

```
LLVM ERROR: out of memory
error: could not compile `librespot-protocol`
```

Could you add the full `spotifyd-linux-armv6-full` to the binary releases, as you have the build pipeline for `spotifyd-linux-armv6-slim` already set up? Or a "medium" version with ALSA and DBUS?

Thanks
bluepuma

**Comment by Yarn** [comment]
https://github.com/Spotifyd/spotifyd/blob/master/.github/workflows/cd.yml#L49

A comment in the code indicates it's not just a matter of enabling it.

**Comment by bluepuma77** [comment]
Ok, let's forget about it.
