### ISSUE TITLE
doc: add screenshots to the readme

### ISSUE THREAD

**Issue by hugolgst** [Spotifyd/spotifyd#547]
It would be great to add a few screenshots inside the README.md to show new users what the application looks like.
PS: Congratulations on your work, a great piece of software here.

**Comment by SimonPersson** [comment]
Hi,

What do you expect the screenshot to contain? This project is a daemon, there's nothing to look at really.

On 20 March 2020 15:32:32 CET, Hugo Lageneste <notifications@github.com> wrote:
>It would be great to add a few screenshots inside the README.md to show new users what the application looks like.
>PS: Congratulations on your work, a great piece of software here.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spotifyd/spotifyd/issues/547
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hugolgst** [comment]
I'm sorry, I totally misunderstood. Wrong repo
