### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by haight6716** [Spotifyd/spotifyd#55]
I followed the directions, installing cargo (I know next to nothing about rust).  When I run the build command:

```
$ cargo build --verbose
    Updating git repository `https://github.com/astro/libpulse-sys`
failed to parse registry's information for: serde_derive

Caused by:
  the given version requirement is invalid
```
Result is the same with or without the --release flag.

This looks cool, I hope to get it working.

**Comment by SimonPersson** [comment]
Which version of Cargo are you running?

**Comment by haight6716** [comment]
From ubuntu 16.04:
```
$ cargo -V
cargo 0.8.0 (built 2016-03-22)
```

**Comment by SimonPersson** [comment]
I think this might be your issue. Rust has been moving pretty quickly, so using over a year old tooling might cause some issues. If Ubuntu does not offer a later version, you could try to uninstall the version they provide and install Rust using the instructions here instead: https://www.rust-lang.org/en-US/install.html

Hopefully that should solve the issue you're seeing! :)

**Comment by haight6716** [comment]
Thanks much for the help.
