### ISSUE TITLE
crash on start - please help

### ISSUE THREAD

**Issue by Tuetenk0pp** [Spotifyd/spotifyd#550]
**Description**
Spotifyd wont start. Things I checked:

`sudo aplay -D front:CARD=Generic_1,DEV=0 file.wav` actually plays the file, so the audio device works!

I also ran `/opt/spotifyd --config-path=/etc/spotifyd.conf`

I made shure to `sudo ufw allow 1234`

here is my config, located at `/etc/spotifyd.conf`
<details><summary>Click to show config</summary>
[global]
username = MYUSER
password = MYPASSWORD
backend = alsa
device = front:CARD=Generic_1,DEV=0
control = front:CARD=Generic_1,DEV=0
mixer = Front
volume_controller = alsa
device_name = NAME
bitrate = 320
cache_path = /opt/spotifyd-cache
no_audio_cache = false
volume_normalisation = true
normalisation_pregain = -10
zeroconf_port = 1234
device_type = speaker
</details>

**I also provided the startup log below but I think that the issue is somewhere around here:**

`Loading config from "/etc/spotifyd.conf"
No proxy specified
Using alsa volume controller.
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL front:CARD=Generic_1,DEV=0
Couldn't read volume from alsa device with name "front:CARD=Generic_1,DEV=0".
Connecting to AP "gew1-accesspoint-b-dr9l.ap.spotify.com:443"
Authenticated as "MYUSER" !
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Using alsa sink
Invalid CTL front:CARD=Generic_1,DEV=0
Couldn't read volume from alsa device with name "front:CARD=Generic_1,DEV=0".
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL front:CARD=Generic_1,DEV=0
Couldn't set volume: Error("snd_mixer_attach", Sys(ENOENT))
Country: "DE"
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)`

**Startup Logs**
<details><summary>Click to show logs</summary>
sudo /opt/spotifyd --verbose --no-daemon
Loading config from "/etc/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: Some("/opt/spotifyd-cache"), no-audio-cache: false, backend: Some(Alsa), volume_controller: Some(Alsa), device: Some("front:CARD=Generic_1,DEV=0"), control: Some("front:CARD=Generic_1,DEV=0"), mixer: Some("Front"), device_name: Some("OpasHiFi"), bitrate: Some(Bitrate320), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: Some(1234), proxy: None } }
Found shell "/bin/bash" using SHELL environment variable.
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=4
registering with poller
Using alsa volume controller.
starting background reactor
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL front:CARD=Generic_1,DEV=0
Couldn't read volume from alsa device with name "front:CARD=Generic_1,DEV=0".
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:1234
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
adding I/O source: 8388610
registering with poller
loop process - 1 events, 0.000s
event Writable Token(8388610)
loop process - 1 events, 0.000s
adding I/O source: 12582915
registering with poller
event Writable Token(12582915)
loop process - 1 events, 0.000s
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://apresolve.spotify.com/")
consuming notification queue
resolving host="apresolve.spotify.com", port=80
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 2
sending packet to V6([ff02::fb]:5353)
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
scheduling Read for: 3
loop poll - 892.72µs
loop time - Instant { tv_sec: 9692, tv_nsec: 81539531 }
loop process, 11.241µs
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
received packet from V4(192.168.178.54:5353)
received packet from V4(192.168.178.54:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
received packet from V6([fe80::aaa1:59ff:fe0c:6c0c]:5353)
received packet from V6([fe80::aaa1:59ff:fe0c:6c0c]:5353) with no query
scheduling Read for: 2
scheduling Read for: 2
loop poll - 50.855µs
loop time - Instant { tv_sec: 9692, tv_nsec: 81612136 }
loop process, 6.482µs
loop poll - 16.618844ms
loop time - Instant { tv_sec: 9692, tv_nsec: 98240879 }
loop process, 23.824µs
connecting to 34.98.74.57:80
adding I/O source: 16777220
registering with poller
scheduling Write for: 4
event Writable Token(16777220)
loop process - 1 events, 0.000s
loop poll - 10.898488ms
loop time - Instant { tv_sec: 9692, tv_nsec: 109277084 }
loop process, 22.883µs
read_keep_alive; is_mid_message=false
scheduling Read for: 4
should_keep_alive(version=Http11, header=None) = true
Client::encode has_body=false, method=None
reclaiming write buf Vec
flushed 47 bytes
flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 108.863µs
loop time - Instant { tv_sec: 9692, tv_nsec: 109456329 }
loop process, 13.395µs
event Readable | Writable Token(16777220)
loop process - 1 events, 0.000s
Conn::read_head
read 648 bytes
Response.parse([Header; 100], [u8; 648])
Response.parse Complete(230)
maybe_literal not found, copying "Via"
parsed 7 headers (230 bytes)
incoming body is content-length (418 bytes)
expecting_continue(version=Http11, header=None) = false
should_keep_alive(version=Http11, header=None) = true
Conn::read_body
decode; state=Length(418)
flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 19.96495ms
loop time - Instant { tv_sec: 9692, tv_nsec: 129441697 }
loop process, 9.578µs
Conn::read_body
decode; state=Length(0)
incoming body completed
scheduling Read for: 4
maybe_notify; read_from_io blocked
read_keep_alive; is_mid_message=false
scheduling Read for: 4
signal: Want
flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
wants_read_again? false
poll_want: taker wants!
pool dropped, dropping pooled ("http://apresolve.spotify.com")
loop poll - 174.496µs
loop time - Instant { tv_sec: 9692, tv_nsec: 129664013 }
loop process, 10.099µs
Connecting to AP "gew1-accesspoint-b-zqpq.ap.spotify.com:443"
adding I/O source: 20971525
registering with poller
scheduling Write for: 5
read_keep_alive; is_mid_message=false
scheduling Read for: 4
client tx closed
State::close_read()
State::close_write()
flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 4
signal: Closed
loop poll - 98.575µs
loop time - Instant { tv_sec: 9692, tv_nsec: 142956278 }
loop process, 14.176µs
event Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 17.693494ms
loop time - Instant { tv_sec: 9692, tv_nsec: 160670981 }
loop process, 12.484µs
scheduling Read for: 5
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 18.00707ms
loop time - Instant { tv_sec: 9692, tv_nsec: 184451877 }
loop process, 17.953µs
flushing framed transport
writing; remaining=138
framed transport flushed
scheduling Read for: 5
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 119.435903ms
loop time - Instant { tv_sec: 9692, tv_nsec: 313051173 }
loop process, 23.764µs
attempting to decode a frame
frame decoded from buffer
Authenticated as "MYUSER" !
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
new Session[0]
new Player[0]
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL front:CARD=Generic_1,DEV=0
Using alsa sink
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
Couldn't read volume from alsa device with name "front:CARD=Generic_1,DEV=0".
new Spirc[0]
new MercuryManager
input volume:0 to mixer: 65
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL front:CARD=Generic_1,DEV=0
Couldn't set volume: Error("snd_mixer_attach", Sys(ENOENT))
attempting to decode a frame
frame decoded from buffer
Session[0] strong=4 weak=2
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
Country: "DE"
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
writing; remaining=879
framed transport flushed
loop poll - 233.747µs
loop time - Instant { tv_sec: 9692, tv_nsec: 314055300 }
loop process, 14.527µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 17.957397ms
loop time - Instant { tv_sec: 9692, tv_nsec: 332034378 }
loop process, 10.379µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 5.153566ms
loop time - Instant { tv_sec: 9692, tv_nsec: 337206849 }
loop process, 10.009µs
subscribed uri=hm://remote/user/MYUSER/ count=0
loop poll - 1.633µs
loop time - Instant { tv_sec: 9692, tv_nsec: 337249649 }
loop process, 9.788µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 17.319875ms
loop time - Instant { tv_sec: 9692, tv_nsec: 354586405 }
loop process, 14.116µs
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop MercuryManager
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
drop Dispatch
deregistering handle with poller
dropping I/O source: 5

</details>

**Versions:**
 - OS: Ubunt-server 4.15.0-91-generic x86_64
 - Spotifyd: 0.2.24

**Comment by JimMorrison723** [comment]
+
i ain't no linux expert, and i just cannot make spotifyd run. i tried binaries, from source, nothing happens :( 
Ubuntu 19.10 as well.

**Comment by Tuetenk0pp** [comment]
Well, seems like I had the wrong precompiled package...
followed the wiki about compiling on Ubuntu and compiled with
`sudo cargo build --release --no-default-features --features alsa_backend && sudo cargo install --path .`
the daemon still errors something about an `Invalid CTI` but it works!
