### ISSUE TITLE
Getting the error: Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" } when strying to start spotifyd

### ISSUE THREAD

**Issue by MitraMai** [Spotifyd/spotifyd#551]
**Description**

Getting the following error when trying to start the service, either from the commandline or by trying to start the service through systemd: Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }

I've tried with both the binary and to compile it by myself. Getting the same error on both.
I somehow think this related to Zeroconf, but I'm no expert and don't really know how to debug the issue.

**To Reproduce**

1. Go to 'Start the service througj the commandline with "sudo systemctl start spotifyd.service'
2. Click on 'Start spotifyd through service or commandline'
4. See error -->Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }

**Expected behavior**

spotifyd should start
**Logs**
<details>Loading config from "/home/kodi/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: Some("command_to_$
Found user shell: Some("/bin/bash")
registering with poller
registering with poller
build; num-workers=2
registering with poller
Using alsa volume controller.
starting background reactor
Couldn't read volume from alsa device with name "hw:CARD,0=II".
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:5353
adding I/O source: 4194305
registering with poller
adding I/O source: 8388610
registering with poller
event Writable Token(4194305)
event Writable Token(8388610)
loop process - 2 events, 0.000s
adding I/O source: 12582915
registering with poller
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://proxy.example.org:8080/")
event Writable Token(12582915)
loop process - 1 events, 0.000s
consuming notification queue
resolving host="proxy.example.org", port=8080
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 2
sending packet to V6([ff02::fb]:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 3
loop poll - 902.604µs
loop time - Instant { tv_sec: 132773, tv_nsec: 695097980 }
loop process, 22.853µs
received packet from V4(192.168.1.8:5353)
received packet from V4(192.168.1.8:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
scheduling Read for: 2
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
received packet from V6([fe80::c23f:d5ff:fe60:3da9]:5353)
received packet from V6([fe80::c23f:d5ff:fe60:3da9]:5353) with no query
scheduling Read for: 2
scheduling Read for: 2
loop poll - 344.54µs
loop time - Instant { tv_sec: 132773, tv_nsec: 695478055 }
loop process, 25.538µs
scheduling Read for: 1
scheduling Read for: 2
loop poll - 29.497µs
loop time - Instant { tv_sec: 132773, tv_nsec: 695544790 }
loop process, 19.38µs
loop poll - 7.872358ms
loop time - Instant { tv_sec: 132773, tv_nsec: 703446615 }
loop process, 55.252µs 
Failed to resolve Access Point: HTTP error
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
Using proxy "http://proxy.example.org:8080/"
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0 
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2

<summary>Click to show logs</summary>

  

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: 
Ubuntu 18.04 LTS
 - Spotifyd: 
v0.2.24
- cargo: 
cargo 1.39.0

**Comment by Orion1** [comment]
Hi MitraMai,
it seems that you are trying to use the http-proxy using the placeholder config, look at the log:
```
failed to resolve Access Point: HTTP error Using fallback "ap.spotify.com:443" Connecting to AP "ap.spotify.com:443" Using proxy "http://proxy.example.org:8080/"
```
Comment out the proxy line in **spotifyd.conf**

**Comment by MitraMai** [comment]
:/ Oh! Sorry! Thanks. It works now

**Comment by fabben69** [comment]
What should/could you change it to? Can it be empty?

**Comment by MitraMai** [comment]
You just comment it out with # in the beginning.
