### ISSUE TITLE
Make the point of the [global] and [spotifyd] sections clear

### ISSUE THREAD

**Issue by maringuu** [Spotifyd/spotifyd#552]
I haven't had the time to look in the source code on how exactly config loading is done, but from the readme I don't get the point for the speration of these two sections.

I guess is that the global section shall provide some general configuration (audio subsystem, proxy, etc) and that the spotifyd section shall provide a user/instance specific configuration.
Also I think that config variables set in the spotifyd section will override the ones in global.

When this is the case wouldn't it be simpler to omit the idea of sections and instead load two config files where one takes the place of the global section and the other of the spotifyd section?

Is this right? Is there anything I forgot?
Any comments on using two config files?

I would like to document the indended behavior.

**Comment by SimonPersson** [comment]
Great question, I think the two sections are useless. I can't even remember the original justification. Maybe [spotifyd-http](https://github.com/Spotifyd/spotifyd-http) used the same config file at some point?

I would welcome a PR to remove the distinction.

**Comment by maringuu** [comment]
Nice, I'd like to do that PR.
Through that might take me a while since I haven't used rust for anything of relevant size.
Also since this will already beak old config files I'd like to use toml instead of ini because toml is well-defined as compared to ini.
