### ISSUE TITLE
'snd_pcm_hw_params_set_buffer_size_near' failed with error 'EINVAL: Invalid argument

### ISSUE THREAD

**Issue by markerdmann** [Spotifyd/spotifyd#556]
**Description**
I'm getting this error when I try to play music while running jack:

```
Alsa error PCM open ALSA function 'snd_pcm_hw_params_set_buffer_size_near' failed with error 'EINVAL: Invalid argument'
Could not start audio: Alsa error: PCM open failed
```

I'm running a fairly vanilla Arch system. spotifyd works when it's using only alsa and jack isn't running. As soon as I start jack and try to play audio, I get this error message. Other apps like chromium and firefox are not having any trouble.

This is my /etc/asound.conf (from https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit#Playing_nice_with_ALSA):

```
# convert alsa API over jack API
# use it with
# % aplay foo.wav

# use this as default
pcm.!default {
    type plug
    slave.pcm "jack"
    hint.description "Jack Audio"
}
```

**To Reproduce**
1. Start jack with qjackctl.
2. Start spotifyd.
3. Play some music with spotify-tui.
4. See error -->

**Expected behavior**

**Logs**
<details><summary>Click to show logs</summary>

loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.141628ms
loop time - Instant { tv_sec: 4445, tv_nsec: 968101392 }
loop process, 7.599µs
loop poll - 17.568µs
loop time - Instant { tv_sec: 4445, tv_nsec: 968130239 }
loop process, 7.21µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 510.798µs
loop time - Instant { tv_sec: 4445, tv_nsec: 968651547 }
loop process, 7.47µs
loop poll - 10.569µs
loop time - Instant { tv_sec: 4445, tv_nsec: 968673496 }
loop process, 6.789µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.197643ms
loop time - Instant { tv_sec: 4445, tv_nsec: 970881048 }
loop process, 6.939µs
loop poll - 12.399µs
loop time - Instant { tv_sec: 4445, tv_nsec: 970905506 }
loop process, 8.629µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.339421ms
loop time - Instant { tv_sec: 4445, tv_nsec: 972256936 }
loop process, 7.61µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 3.61028ms
loop time - Instant { tv_sec: 4445, tv_nsec: 975879575 }
loop process, 6.999µs
loop poll - 11.009µs
loop time - Instant { tv_sec: 4445, tv_nsec: 975901643 }
loop process, 6.939µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 905.697µs
loop time - Instant { tv_sec: 4445, tv_nsec: 976817299 }
loop process, 6.559µs
loop poll - 23.938µs
loop time - Instant { tv_sec: 4445, tv_nsec: 976851426 }
loop process, 7.16µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 8.641743ms
loop time - Instant { tv_sec: 4445, tv_nsec: 985503148 }
loop process, 9.979µs
chunk 77 / 83 complete
requesting chunk 78
loop poll - 27.848µs
loop time - Instant { tv_sec: 4445, tv_nsec: 985544885 }
loop process, 5.899µs
scheduling Read for: 5
flushing framed transport
writing; remaining=53
framed transport flushed
loop poll - 36.337µs
loop time - Instant { tv_sec: 4445, tv_nsec: 985590391 }
loop process, 6.399µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 24.29017ms
loop time - Instant { tv_sec: 4446, tv_nsec: 9890790 }
loop process, 9.729µs
loop poll - 5.109µs
loop time - Instant { tv_sec: 4446, tv_nsec: 9910228 }
loop process, 6.64µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.599291ms
loop time - Instant { tv_sec: 4446, tv_nsec: 12519979 }
loop process, 7.799µs
loop poll - 21.198µs
loop time - Instant { tv_sec: 4446, tv_nsec: 12553416 }
loop process, 7.909µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.937213ms
loop time - Instant { tv_sec: 4446, tv_nsec: 14501638 }
loop process, 8.84µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.086223ms
loop time - Instant { tv_sec: 4446, tv_nsec: 15601400 }
loop process, 6.899µs
loop poll - 22.138µs
loop time - Instant { tv_sec: 4446, tv_nsec: 15634597 }
loop process, 6.889µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.527226ms
loop time - Instant { tv_sec: 4446, tv_nsec: 18171822 }
loop process, 7.3µs
loop poll - 13.799µs
loop time - Instant { tv_sec: 4446, tv_nsec: 18198050 }
loop process, 6.07µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.663256ms
loop time - Instant { tv_sec: 4446, tv_nsec: 19870446 }
loop process, 7.089µs
loop poll - 19.738µs
loop time - Instant { tv_sec: 4446, tv_nsec: 19901293 }
loop process, 6.26µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.212692ms
loop time - Instant { tv_sec: 4446, tv_nsec: 21123394 }
loop process, 6.09µs
loop poll - 22.718µs
loop time - Instant { tv_sec: 4446, tv_nsec: 21156402 }
loop process, 6.169µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 21.56211ms
loop time - Instant { tv_sec: 4446, tv_nsec: 42727891 }
loop process, 7.33µs
loop poll - 10.87µs
loop time - Instant { tv_sec: 4446, tv_nsec: 42750120 }
loop process, 5.779µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.72987ms
loop time - Instant { tv_sec: 4446, tv_nsec: 44488989 }
loop process, 7.419µs
loop poll - 17.059µs
loop time - Instant { tv_sec: 4446, tv_nsec: 44517607 }
loop process, 7.229µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.061494ms
loop time - Instant { tv_sec: 4446, tv_nsec: 45589310 }
loop process, 6.599µs
loop poll - 29.438µs
loop time - Instant { tv_sec: 4446, tv_nsec: 45628957 }
loop process, 6.969µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.757158ms
loop time - Instant { tv_sec: 4446, tv_nsec: 47396134 }
loop process, 7.269µs
loop poll - 16.719µs
loop time - Instant { tv_sec: 4446, tv_nsec: 47423782 }
loop process, 6.449µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 12.872222ms
loop time - Instant { tv_sec: 4446, tv_nsec: 60305313 }
loop process, 8.289µs
chunk 78 / 83 complete
requesting chunk 79
loop poll - 25.128µs
loop time - Instant { tv_sec: 4446, tv_nsec: 60345110 }
loop process, 6.239µs
scheduling Read for: 5
flushing framed transport
writing; remaining=53
framed transport flushed
loop poll - 40.187µs
loop time - Instant { tv_sec: 4446, tv_nsec: 60394996 }
loop process, 6.029µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 23.501703ms
loop time - Instant { tv_sec: 4446, tv_nsec: 83906178 }
loop process, 9.51µs
loop poll - 5.28µs
loop time - Instant { tv_sec: 4446, tv_nsec: 83925017 }
loop process, 6.629µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.767487ms
loop time - Instant { tv_sec: 4446, tv_nsec: 85702853 }
loop process, 6.77µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.521287ms
loop time - Instant { tv_sec: 4446, tv_nsec: 88237379 }
loop process, 6.95µs
loop poll - 10.909µs
loop time - Instant { tv_sec: 4446, tv_nsec: 88259407 }
loop process, 7.06µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.913736ms
loop time - Instant { tv_sec: 4446, tv_nsec: 90183372 }
loop process, 10.019µs
loop poll - 37.837µs
loop time - Instant { tv_sec: 4446, tv_nsec: 90236798 }
loop process, 9.239µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.580151ms
loop time - Instant { tv_sec: 4446, tv_nsec: 92830098 }
loop process, 7.41µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.86436ms
loop time - Instant { tv_sec: 4446, tv_nsec: 94705757 }
loop process, 9.54µs
loop poll - 20.899µs
loop time - Instant { tv_sec: 4446, tv_nsec: 94740635 }
loop process, 6.459µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.157527ms
loop time - Instant { tv_sec: 4446, tv_nsec: 95907361 }
loop process, 8.639µs
loop poll - 28.847µs
loop time - Instant { tv_sec: 4446, tv_nsec: 95949187 }
loop process, 10.519µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.314814ms
loop time - Instant { tv_sec: 4446, tv_nsec: 97279210 }
loop process, 10.019µs
loop poll - 13.999µs
loop time - Instant { tv_sec: 4446, tv_nsec: 97307598 }
loop process, 8.099µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 5.670482ms
loop time - Instant { tv_sec: 4446, tv_nsec: 102990119 }
loop process, 7.13µs
loop poll - 9.479µs
loop time - Instant { tv_sec: 4446, tv_nsec: 103010688 }
loop process, 7.619µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 431.755µs
loop time - Instant { tv_sec: 4446, tv_nsec: 103453862 }
loop process, 7.549µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.516356ms
loop time - Instant { tv_sec: 4446, tv_nsec: 105982317 }
loop process, 9.38µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.908686ms
loop time - Instant { tv_sec: 4446, tv_nsec: 107905092 }
loop process, 8.569µs
loop poll - 21.948µs
loop time - Instant { tv_sec: 4446, tv_nsec: 107940249 }
loop process, 7.989µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 250.26µs
loop time - Instant { tv_sec: 4446, tv_nsec: 108202228 }
loop process, 9.189µs
loop poll - 19.048µs
loop time - Instant { tv_sec: 4446, tv_nsec: 108234825 }
loop process, 8.08µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.763007ms
loop time - Instant { tv_sec: 4446, tv_nsec: 111009621 }
loop process, 7.45µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 242.52µs
loop time - Instant { tv_sec: 4446, tv_nsec: 111263931 }
loop process, 10.499µs
loop poll - 20.778µs
loop time - Instant { tv_sec: 4446, tv_nsec: 111299568 }
loop process, 8.549µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 5.375556ms
loop time - Instant { tv_sec: 4446, tv_nsec: 116687633 }
loop process, 8.39µs
chunk 79 / 83 complete
requesting chunk 80
loop poll - 20.779µs
loop time - Instant { tv_sec: 4446, tv_nsec: 116721891 }
loop process, 7.369µs
scheduling Read for: 5
flushing framed transport
writing; remaining=53
framed transport flushed
loop poll - 38.937µs
loop time - Instant { tv_sec: 4446, tv_nsec: 116771627 }
loop process, 9.999µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 23.889013ms
loop time - Instant { tv_sec: 4446, tv_nsec: 140675348 }
loop process, 11.469µs
loop poll - 6.55µs
loop time - Instant { tv_sec: 4446, tv_nsec: 140699536 }
loop process, 8.339µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 915.646µs
loop time - Instant { tv_sec: 4446, tv_nsec: 141626871 }
loop process, 7.99µs
loop poll - 11.179µs
loop time - Instant { tv_sec: 4446, tv_nsec: 141650079 }
loop process, 5.9µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.388367ms
loop time - Instant { tv_sec: 4446, tv_nsec: 144047036 }
loop process, 11.449µs
loop poll - 12.549µs
loop time - Instant { tv_sec: 4446, tv_nsec: 144075014 }
loop process, 7.859µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.620979ms
loop time - Instant { tv_sec: 4446, tv_nsec: 145708152 }
loop process, 10.279µs
loop poll - 32.248µs
loop time - Instant { tv_sec: 4446, tv_nsec: 145758018 }
loop process, 7.549µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.787015ms
loop time - Instant { tv_sec: 4446, tv_nsec: 148556432 }
loop process, 8.18µs
loop poll - 9.059µs
loop time - Instant { tv_sec: 4446, tv_nsec: 148577741 }
loop process, 7.489µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.727481ms
loop time - Instant { tv_sec: 4446, tv_nsec: 150316751 }
loop process, 6.949µs
loop poll - 16.798µs
loop time - Instant { tv_sec: 4446, tv_nsec: 150344198 }
loop process, 7.06µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.256349ms
loop time - Instant { tv_sec: 4446, tv_nsec: 151611056 }
loop process, 9.549µs
loop poll - 29.687µs
loop time - Instant { tv_sec: 4446, tv_nsec: 151654362 }
loop process, 9.32µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.182845ms
loop time - Instant { tv_sec: 4446, tv_nsec: 152850776 }
loop process, 9.529µs
loop poll - 7.769µs
loop time - Instant { tv_sec: 4446, tv_nsec: 152872254 }
loop process, 9.439µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.694933ms
loop time - Instant { tv_sec: 4446, tv_nsec: 154580846 }
loop process, 7.74µs
loop poll - 8.69µs
loop time - Instant { tv_sec: 4446, tv_nsec: 154601985 }
loop process, 8.109µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 3.3402ms
loop time - Instant { tv_sec: 4446, tv_nsec: 157954514 }
loop process, 8.09µs
loop poll - 8.12µs
loop time - Instant { tv_sec: 4446, tv_nsec: 157974883 }
loop process, 6.459µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 290.336µs
loop time - Instant { tv_sec: 4446, tv_nsec: 158274318 }
loop process, 8.53µs
loop poll - 15.399µs
loop time - Instant { tv_sec: 4446, tv_nsec: 158303326 }
loop process, 7.739µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 2.910565ms
loop time - Instant { tv_sec: 4446, tv_nsec: 161226040 }
loop process, 9.589µs
loop poll - 12.129µs
loop time - Instant { tv_sec: 4446, tv_nsec: 161251438 }
loop process, 7.669µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 1.842851ms
loop time - Instant { tv_sec: 4446, tv_nsec: 163106618 }
loop process, 9.269µs
chunk 80 / 83 complete
loop poll - 41.856µs
loop time - Instant { tv_sec: 4446, tv_nsec: 163162063 }
loop process, 9.1µs
File cd528702c984a27c85a07f116f6fc8f4a6823fb7 complete
loop poll - 27.658µs
loop time - Instant { tv_sec: 4446, tv_nsec: 163203650 }
loop process, 8.329µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(10.5.50.137:5353)
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 12.411322254s
loop time - Instant { tv_sec: 4458, tv_nsec: 574538023 }
loop process, 11.969µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(10.5.50.137:5353)
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 984.011µs
loop time - Instant { tv_sec: 4458, tv_nsec: 575540652 }
loop process, 9.949µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(10.5.50.137:5353)
received packet from V4(10.5.50.137:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 1.432894ms
loop time - Instant { tv_sec: 4458, tv_nsec: 576990944 }
loop process, 9.909µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(10.5.50.137:5353)
received packet from V4(10.5.50.137:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 882.209µs
loop time - Instant { tv_sec: 4458, tv_nsec: 577888862 }
loop process, 7.799µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(10.5.50.57:5353)
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 611.245521ms
loop time - Instant { tv_sec: 4459, tv_nsec: 189146812 }
loop process, 11.589µs
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
scheduling Read for: 1
received packet from V6([fe80::108a:6e1c:797:3a1d]:5353)
scheduling Read for: 2
scheduling Read for: 2
loop poll - 481.341µs
loop time - Instant { tv_sec: 4459, tv_nsec: 189646552 }
loop process, 8.379µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(10.5.50.165:5353)
received packet from V4(10.5.50.165:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 307.961388ms
loop time - Instant { tv_sec: 4459, tv_nsec: 497621439 }
loop process, 12.949µs
^Cevent Readable | Writable Token(12582915)
loop process - 1 events, 0.000s
scheduling Read for: 3
loop poll - 1.893212153s
loop time - Instant { tv_sec: 4461, tv_nsec: 390852471 }
loop process, 12.909µs
Polling message stream
msgstream found Ok(NotReady)
Polling message stream
msgstream found Ok(NotReady)
scheduling Read for: 5
flushing framed transport
writing; remaining=479
framed transport flushed
loop poll - 60.495µs
loop time - Instant { tv_sec: 4461, tv_nsec: 391003489 }
loop process, 7.169µs
Polling message stream
msgstream found Ok(NotReady)
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 21.379581ms
loop time - Instant { tv_sec: 4461, tv_nsec: 412409728 }
loop process, 12.689µs
Polling message stream
msgstream found Ok(NotReady)
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop AudioKeyManager
drop ChannelManager
drop MercuryManager
Dropping AMessageStream
AMessageStream telling ADriver to quit
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 4
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
dropping I/O source: 3
drop Dispatch
deregistering handle with poller
dropping I/O source: 5
  

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: arch-1.3.5-12
 - Spotifyd: 0.2.24
- cargo: 1.42.0

**Comment by mattheasboelter** [comment]
Any chance you've found a solution to this? I'm having the same problem on a very similar system. (Although no audio works without jack, as alsa is always trying to push audio through jack). Most applications are working, although mpd seems to have similar problems.

**Comment by markerdmann** [comment]
@mattheasboelter I ended up using librespot directly and compiling it with the rdio backend option. I posted some details here:

https://github.com/librespot-org/librespot/issues/333#issuecomment-608990452

This is where I found the instructions for compiling librespot with rdio support:

https://github.com/librespot-org/librespot/wiki/Compiling

**Comment by mattheasboelter** [comment]
Thanks for the info! I appreciate it.

**Comment by mr-berndt** [comment]
I have the same problem using the latest alsa library and alsa plugins (1.2.2). Help would be greatly appreciated.
