### ISSUE TITLE
spotifyd from command line crashes on first connect on LibreElec.

### ISSUE THREAD

**Issue by voltagex** [Spotifyd/spotifyd#558]
**Description**

Running spotifyd from the command line on a Pi LibreElec install causes it to exit/crash on first connect

**To Reproduce**

1. Download and unpack spotifyd to a writable path on the LE install - I used /storage/bin
2. Run ./spotifyd --no-daemon
3. Play music via e.g. an Android phone.

```
LibreELEC:~/bin # ./spotifyd --no-daemon
No config file specified. Running with default values
No proxy specified
Using software volume controller.
Connecting to AP "gae2-accesspoint-b-vpx4.ap.spotify.com:443"
Authenticated as "voltagex_us" !
Using alsa sink
Country: "AU"
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
```

if I add DISPLAY=0 to the command line, the crash is

```
Caught panic with message: Failed to initialize DBus connection: D-Bus error: /usr/bin/dbus-launch terminated abnormally with the following error: Autolaunch requested, but X11 support not compiled in.
Cannot continue.
 (org.freedesktop.DBus.Error.Spawn.ExecFailed)
```

**Expected behavior**
Music to play? I'm not sure why an X11 display is required here.,

**Logs**
<details>

```
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop MercuryManager
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 0
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
drop Dispatch
deregistering handle with poller
dropping I/O source: 5
```

</details>

**Versions (please complete the following information):**
 - OS: LibreElec 9.2.1
 - Spotifyd: spotifyd 0.2.24

- cargo:

**Comment by SimonPersson** [comment]
Is your X server running? Are you running spotifyd from a terminal inside that X server? If not, you might have to set the DISPLAY variable manually, details: https://askubuntu.com/questions/432255/what-is-the-display-environment-variable#432257. Or just build spotifyd without dbus support, if you are going for a headless setup anyway.

Cheers,
Simon

**Comment by voltagex** [comment]
@SimonPersson I edited the issue after trying with DISPLAY set - I get a different error. I am rebuilding spotifyd now, this issue was raised with the -full build downloaded from releases.

**Comment by SimonPersson** [comment]
@voltagex - Looks like you're running some setup without Xorg support in dbus. I recommend that you either make a build yourself, or download the `-slim` release from the release page.

**Comment by voltagex** [comment]
Okay, I'm happy with that - closing this now
