### ISSUE TITLE
Reproducible crash when internet connection goes away

### ISSUE THREAD

**Issue by wedi** [Spotifyd/spotifyd#56]
Hi,

once a day my ISP forces a reconnect. (Probably to prevent people from having a quasi static ip as if anyone would rely on this…)

When the reconnect takes more than a few seconds spotifyd crashes reproducibly:
> `14:27:36 ^[[31m[ERROR] ^[(B^[[mCaught panic with message: Unknown error type, can't produce message.`

I am happy to provide the verbose log file from a reproduction but I am not sure if my spotify credentials might be hidden in there. Grepping for `login` suggested that and this might not be the only line?

> `14:27:32 [TRACE] hyper::http::h1::parse: [/home/***/.cargo/git/checkouts/hyper-817b53a166fc1c58/e81184e/src/http/h1/parse.rs:21] parse(b"POST\x20/\x20HTTP/1.1\r\nHost:\x20192.168.178.13:33004\r\nUser-Agent:\x20Spotify/105500487\x20OSX/0\x20(MacBookPro12,1)\r\nKeep-Alive:\x200\r\nConnection:\x20keep-alive\r\nAccept-Encoding:\x20gzip\r\nContent-Type:\x20application/x-www-form-urlencoded\r\nContent-Length:\x20615\r\n\r\naction=addUser&userName=***&blob=***&clientKey=***&deviceName=***&deviceId=***&version=2.5.1“)`

**Comment by SimonPersson** [comment]
Should be fixed on master now, feel free to reopen otherwise!

**Comment by bjo81** [comment]
I had this issue last night with the binary-build some days old: ` Caught panic with message: Unknown error type, can't produce message.` after reconnecting my internet connection.

**Comment by bjo81** [comment]
Issue still exists:
```16:20:07 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:87] received packet from V6([fe80::d250:99ff:fe71:14a1]:5353) with no query
16:20:07 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 4689757 }
16:20:07 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 160830, tv_nsec: 649431193 }
16:20:07 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 116875 }
16:20:14 [TRACE] tokio_reactor: [<unknown>:330] event Readable | Writable | Error | Hup Token(5)
16:20:14 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
16:20:14 [DEBUG] librespot_core::session: drop Dispatch
16:20:14 [TRACE] mio::poll: [<unknown>:905] deregistering handle with poller
16:20:14 [DEBUG] tokio_reactor: dropping I/O source: 4
16:20:14 [ERROR] Caught panic with message: Unknown error type, can't produce message.
16:20:14 [DEBUG] librespot_connect::spirc: drop Spirc[0]
16:20:14 [DEBUG] librespot_playback::player: Shutting down player thread ...
16:20:14 [DEBUG] librespot_playback::player: drop Player[0]
16:20:14 [TRACE] tokio_reactor: [<unknown>:330] event Readable Token(0)
16:20:14 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
16:20:14 [DEBUG] tokio_reactor::background: shutting background reactor down NOW
16:20:14 [DEBUG] tokio_reactor::background: background reactor has shutdown```

**Comment by bjo81** [comment]
@SimonPersson or @wedi Could you reopen this issue? Or should I create a new one?

**Comment by SimonPersson** [comment]
@bjo81 - I think this is the issue reported in #119, so we can track the issue there.
