### ISSUE TITLE
Add Homebrew for Mac users

### ISSUE THREAD

**Issue by patricksamson** [Spotifyd/spotifyd#561]
Hi!

I recently discovered Spotifyd and managed to run it successfully on macOS. I had some issues in the beginning with missing dbus and portaudio dependencies and figured adding Spotifyd to a package manager would make things easier.

So, I forked the Homebrew tap of a similar project (spotify-tui) and made the necessary adjustments to make Spotifyd work correctly.

Users can install Spotifyd using `brew install Lykegenes/tap/spotifyd`. You could fork [my repo](https://github.com/Lykegenes/homebrew-tap) to have `brew install Spotifyd/tap/spotifyd` if you want.

Here are a few things to note :
- Homebrew will install Spotifyd using the binaries from your repo.
- There is a script to make updating the version in the formula easier
- Homebrew does not support SHA512, so the script computes a new SHA256 from the binary

Some improvements that could be made :
- Generate a default config file (not sure how)
- Run Spotifyd as a service (Homebrew supports this)

**Comment by SirWindfield** [comment]
Sorry for the silence. I had a lot of stuff to do IRL and the time I had went into various free time projects :)

I would rather add the tap into the organization if you are OK with that!
I'll clean up issues and do more over eastern :)

**Comment by Lykegenes** [comment]
No problem! The repository must be named `homebrew-tap`, and it should work right away once you fork it. If you don't have a Mac to test it, I can confirm that everything works properly.

Happy easter! :)

**Comment by SirWindfield** [comment]
Forked, I will have to test it though before giving the go. Do you happen to know if SHA512 is landing on homebrew or work is being done? 
If not, maybe computing SHA256 would be a good idea.

**Comment by Lykegenes** [comment]
I'm not sure about SHA512 support, it's been this way for a few years. 
The update script modifies the Cask to use the new URLs from Github, and computes the SHA256.

**Comment by antizo** [comment]
good job!

**Comment by SirWindfield** [comment]
As far as I remember, the script inside the tap has to be run for each release. Maybe it's possible to somehow run this using CI on a scheduler? So every day, it checks the repo for a new release and updates the tab accordingly?

**Comment by patricksamson** [comment]
That should be possible, yes.
- The job would need to be able to push a commit or a PR to the [Spotifyd/homebrew-tap](https://github.com/Spotifyd/homebrew-tap) repo
- It's possible to run a GH Action on a schedule : [link to docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule)
```yaml
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
```
But this could also be done as a part of the build/release process (in the `cd.yaml` workflow).

I wanted to do it manually this time, but it looks like the builds are not attached to the new release.

**Comment by SirWindfield** [comment]
Ye, CD broke, but there is already a PR open to fix this: #761.

**Comment by SirWindfield** [comment]
@patricksamson If you're interested, I'd give you access to Spotifyd/homebrew-tab and you could update it there. I'd like to make it the "official" homebrew tab. Once documentation moved to a better place than the readme, we can include the tab in there as well.

**Comment by patricksamson** [comment]
Sure, I'd be happy to!

**Comment by SirWindfield** [comment]
Awesome, really appreciate the help!

**Comment by robinvd** [comment]
the builds from ci are available here https://github.com/robinvd/spotifyd/releases/tag/v0.2.33. But maybe its best to wait for #761 to be approved by 2 people

**Comment by SirWindfield** [comment]
> 
> 
> the builds from ci are available here https://github.com/robinvd/spotifyd/releases/tag/v0.2.33. But maybe its best to wait for #761 to be approved by 2 people

Ye we should probably wait till we merge the release and push a new tag (increase the patch) to trigger a new build.

**Comment by robinvd** [comment]
@patricksamson  https://github.com/Spotifyd/spotifyd/releases/tag/v0.2.25-1 :tada:

**Comment by SirWindfield** [comment]
v0.3.0 is even out. I'll close this as it has been added by @patricksamson :)
