### ISSUE TITLE
[DBUS] Connection error on OS X

### ISSUE THREAD

**Issue by voldemortensen** [Spotifyd/spotifyd#562]
**Description**
On OS X, running spotifyd (`spotifyd --no-daemon`) fails with a DBus connection error.

**To Reproduce**
1. Run `spotifyd --no-daemon` with a default config (I've supplied my username/password and changed defaults to their OS X equivalent).

**Logs**
<details><summary>Click to show logs</summary>

Loading config from "/Users/<REDACTED>/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false,
on_song_change_hook: None, cache_path: Some("/Users/<REDACTED>/.spotifyd/cache"), no-audio-cache: true, backend: Some(PortAudio), volume_controller: Some(SoftVolume), device: None, control: None, mixer: None, device_name: Some("machine"), bitrate: Some(Bitrate160), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: Some(12321), proxy: None } }
Found shell "/usr/local/bin/zsh" using SHELL environment variable.
No proxy specified
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
build; num-workers=12
registering; token=Token(<REDACTED>); interests=Readable
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
registering; token=Token(0); interests=Readable | Writable | Error | Hup
Zeroconf server listening on 0.0.0.0:12321
adding I/O source: <REDACTED>
registering with poller
registering; token=Token(<REDACTED>); interests=Readable | Writable | Error | Hup
event Writable Token(<REDACTED>)
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
loop process - 1 events, 0.000s
adding I/O source: <REDACTED>
registering with poller
registering; token=Token(<REDACTED>); interests=Readable | Writable | Error | Hup
park; waiting for idle connection: "http://apresolve.spotify.com"
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
Http::connect("http://apresolve.spotify.com/")
resolving host="apresolve.spotify.com", port=80
consuming notification queue
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
scheduling Read for: 2
loop poll - 30.652786ms
loop time - Instant { t: 1846809762189 }
loop process, 6.175µs
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
connecting to 34.98.74.57:80
adding I/O source: <REDACTED>
registering with poller
registering; token=Token(<REDACTED>); interests=Readable | Writable | Error | Hup
scheduling Write for: 3
received packet from V4(192.168.1.121:5353)
received packet from V4(192.168.1.121:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
loop poll - 34.352µs
loop time - Instant { t: 1846809958901 }
loop process, 3.205µs
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
loop poll - 31.695373ms
loop time - Instant { t: 1846841659277 }
loop process, 10.988µs
read_keep_alive; is_mid_message=false
scheduling Read for: 3
should_keep_alive(version=Http11, header=None) = true
Client::encode has_body=false, method=None
reclaiming write buf Vec
flushed 47 bytes
flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 119.818µs
loop time - Instant { t: 1846841893669 }
loop process, 4.039µs
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
Conn::read_head
read 648 bytes
Response.parse([Header; 100], [u8; 648])
Response.parse Complete(230)
maybe_literal not found, copying "Via"
parsed 7 headers (230 bytes)
incoming body is content-length (418 bytes)
expecting_continue(version=Http11, header=None) = false
should_keep_alive(version=Http11, header=None) = true
Conn::read_body
decode; state=Length(418)
flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 68.888296ms
loop time - Instant { t: 1846910788425 }
loop process, 9.351µs
Conn::read_body
decode; state=Length(0)
incoming body completed
scheduling Read for: 3
maybe_notify; read_from_io blocked
read_keep_alive; is_mid_message=false
scheduling Read for: 3
signal: Want
flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
wants_read_again? false
poll_want: taker wants!
pool dropped, dropping pooled ("http://apresolve.spotify.com")
loop poll - 164.283µs
loop time - Instant { t: 1846911047095 }
loop process, 24.34µs
Connecting to AP "guc3-accesspoint-b-xbl8.ap.spotify.com:443"
adding I/O source: <REDACTED>
registering with poller
registering; token=Token(<REDACTED>); interests=Readable | Writable | Error | Hup
scheduling Write for: 4
read_keep_alive; is_mid_message=false
scheduling Read for: 3
client tx closed
State::close_read()
State::close_write()
flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 3
signal: Closed
loop poll - 82.988µs
loop time - Instant { t: 1846927792580 }
loop process, 6.892µs
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
loop poll - 61.689346ms
loop time - Instant { t: 1846989492843 }
loop process, 21.977µs
scheduling Read for: 4
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
loop poll - 63.747129ms
loop time - Instant { t: 1847064135246 }
loop process, 68.192µs
flushing framed transport
writing; remaining=145
framed transport flushed
scheduling Read for: 4
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
event Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
loop poll - 197.748674ms
loop time - Instant { t: 1847273268383 }
loop process, 16.058µs
attempting to decode a frame
frame decoded from buffer
Authenticated as "<REDACTED>" !
new Session[0]
new Spirc[0]
new MercuryManager
new Player[0]
Using PortAudio sink
input volume:65535 to mixer: 65535
attempting to decode a frame
frame decoded from buffer
Session[0] strong=4 weak=2
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
Country: "US"
attempting to decode a frame
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
writing; remaining=874
framed transport flushed
loop poll - 211.224µs
loop time - Instant { t: 1847274899562 }
loop process, 5.337µs
event Readable | Writable Token(<REDACTED>)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 61.450205ms
loop time - Instant { t: 1847336358465 }
loop process, 3.796µs
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 2.984024ms
loop time - Instant { t: 1847339349164 }
loop process, 3.224µs
subscribed uri=hm://remote/user/<REDACTED>/ count=0
loop poll - 899ns
loop time - Instant { t: 1847339376492 }
loop process, 2.773µs
event Readable Token(<REDACTED>)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 56.642731ms
loop time - Instant { t: 1847396023387 }
loop process, 6.952µs
dbus[7732]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Not enough memory (org.freedesktop.DBus.Error.NoMemory)
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop MercuryManager
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 2
deregistering handle with poller
dropping I/O source: 1
drop Dispatch
deregistering handle with poller
dropping I/O source: 4
</details>

**Compilation flags** 
Using the provided "macos full" binary.

**Versions (please complete the following information):**
 - OS: OS X 10.15.4
 - Spotifyd: 0.2.24
- cargo: N/A

I have installed DBus using macports. I've verified that dbus-system and dbus-session are both loaded and running using `launchctl`.

**Comment by ciehanski** [comment]
Experiencing this exact issue as well.

**Comment by ciehanski** [comment]
@voldemortensen try the steps listed out [here](https://github.com/Spotifyd/spotifyd/issues/565#issuecomment-619467945). This got it working for me.

**Comment by barelnir** [comment]
I managed to fix it and now I spotifyd working as expected

steps to fix this:

```
brew install dbus
ls -l /private/tmp/com.apple.launchd*
```
now take the newest folder, this will be the unix path dbus is looking for..
now run the following command:
`launchctl setenv DBUS_LAUNCHD_SESSION_BUS_SOCKET /private/tmp/com.apple.launchd.TCJHik8MxN/unix_domain_listener`

now if you run dbus-monitor it should work and you will see something like that:
`signal time=1588455097.816802 sender=org.freedesktop.DBus -> destination=:1.0 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.0"
signal time=1588455097.816840 sender=org.freedesktop.DBus -> destination=:1.0 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.0"`

now go back to spotifyd and run the following:
`./spotifyd --config-path=/Users/<USER>/.config/spotifyd/spotifyd.conf --no-daemon --backend portaudio`

**Comment by crispamares** [comment]
In order to run the dbus daemon I needed to do `brew services start dbus` as said in the [documentation](https://github.com/zbentley/dbus-osx-examples/blob/master/installation/README.md#session-bus)

**Comment by rhelmke** [comment]
> I managed to fix it and now spotifyd working as expected
> 
> steps to fix this:
> `brew install dbus`
> Take the newest folder from here:
> `ls -l /private/tmp/com.apple.launchd*`
> This will be the unix path dbus is looking for... now run the following command:
> `launchctl setenv DBUS_LAUNCHD_SESSION_BUS_SOCKET /private/tmp/com.apple.launchd.TCJHik8MxN/unix_domain_listener`
> 
> now if you run dbus-monitor it should work and you will see something like that:
> `signal time=1588455097.816802 sender=org.freedesktop.DBus -> destination=:1.0 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired string ":1.0" signal time=1588455097.816840 sender=org.freedesktop.DBus -> destination=:1.0 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost string ":1.0"`
> 
> now go back to spotifyd and run the following:
> `./spotifyd --config-path=/Users/<USER>/.config/spotifyd/spotifyd.conf --no-daemon --backend portaudio`

Following up to this *workaround* provided by @barelnir:

In case you guys verified that the dbus-session has successfully launched by launchd but `launchctl getenv DBUS_LAUNCHD_SESSION_BUS_SOCKET` returns nothing, **this may very well be an issue with iTerm2**.

[Issue 7654](https://gitlab.com/gnachman/iterm2/-/issues/7654) discusses that iTerm's session bootstrapping feature breaks `launchctl getenv/setenv`, as the environment is not properly being updated.

As stated by George Nachman in the previously mentioned issue, you may fix this by disabling the feature in iTerm2:

`Prefs > Advanced > Allow sessions to survive logging out and back in`

**Keep in mind that this will also come with its obvious caveats.**

**Comment by jrejaud** [comment]
> launchctl setenv DBUS_LAUNCHD_SESSION_BUS_SOCKET /private/tmp/com.apple.launchd.TCJHik8MxN/unix_domain_listener

In my situation, I needed to update dbus to version 1.12.20 first

`brew upgrade dbus`

as neither of the `com.apple.launchd.*` dirs contained the `unix_domain_listener` file.

However, the new `com.apple.launchd.*` dir created after updating did contain this file.

Running `dbus-monitor` on my system returns the same output you listed above, but trying to run:

`sudo spotifyd --no-daemon` (I already have a config file)

still returns:

```
Loading config from "/Users/jrejaud/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
Connecting to AP "*********.spotify.com:443"
Authenticated as "*********" !
Country: "US"
dbus[72463]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Not enough memory (org.freedesktop.DBus.Error.NoMemory)
```

Please advise, I'm unsure what to try next :)
