### ISSUE TITLE
spotifyd does not start - spotifyd --no-daemon starts

### ISSUE THREAD

**Issue by taschenlampe** [Spotifyd/spotifyd#564]
I have compile the program today(20200411) version spotifyd 0.2.24 @  ubuntu 20.04
 I used: cargo build --release ; cargo install --path .  
No additional flags were used. Then I placed the app in /usr/bin.
When I start it, it crashes without any notification, ps -aux shows no spotifyd.
Running it via spotifyd --no-daemon gives following:

Loading config from "/home/random_dude/.config/spotifyd/spotifyd.conf"
No proxy specified
Using alsa volume controller.
Connecting to AP "gew1-accesspoint-b-01g8.ap.spotify.com:443"
Authenticated as "random_dude" !
Using alsa sink
Country: "DE"

This is actually working and I am able connect spotifyd with spt with success. Please let me know where to find the needed logs that might be helpful.

Cheers!   

(side note: I have un-commented the section proxy, device and control, as I was not able to define a working device -not sure what spotifyd actually wants)

**Comment by clarios6** [comment]
I get this error on Ubuntu 20.04 as well. I used `cargo install spotifyd --locked --features "pulseaudio_backend"` to install. Whenever I tried to add to $PATH or to systemd the changes didn't persist so I wrote a small script and made an alias for it, figure it might help someone else out.
```
#!/bin/bash

if [ ! $(pgrep "spotifyd") ]; then
	gnome-terminal --tab -e "bash -c spt"
	~/.cargo/bin/spotifyd --no-daemon
else
	spt
fi
```
