### ISSUE TITLE
Not working as daemon and system service on macOS

### ISSUE THREAD

**Issue by johnnypea** [Spotifyd/spotifyd#565]
**Description**
Everything works fine when running `spotifyd --no-daemon` but it crashes when running without `--no-daemon` or as system service.

```
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

```
com.apple.xpc.launchd[1] (rustlang.spotifyd): Service only ran for 0 seconds. Pushing respawn out by 30 seconds.
com.apple.xpc.launchd[1] (rustlang.spotifyd[62686]): Service exited with abnormal code: 101
```

**Compilation flags** 
- [ ] dbus_mpris
- [x] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [x] rodio_backend

(I tried as well with the "portaudio" backend, both full and slim binaries but the same results.)

**Versions:**
 - OS: macOS Catalina 10.15.4
 - Spotifyd: 0.2.24

**Comment by voldemortensen** [comment]
I had this issue as well. I haven't been able to identify what the problem is exactly, but compiling from master fixed this for me.

**Comment by SirWindfield** [comment]
Weird that the pre-compiled package didn't work out. I can test this later this week and take a look.

**Comment by dubcdr** [comment]
I'm seeing the same error: 

mac 10.15.4

**Comment by arcin** [comment]
I was seeing this issue with the following setup yesterday

- macOS: **10.15.3.**
- cargo: **1.42.0**
- rustup: **1.21.0**

**build**
```bash
cargo build --release --no-default-features --features portaudio_backend,dbus_keyring
```

**run**
```
sudo ./target/release/spotifyd --config-path=/users/me/.config/spotifyd/spotifyd.conf --no-daemon --backend portaudio 
```

Tried building with HEAD at the following releases but that didn't work either
- tags/v0.2.19
- tags/v0.2.24
- master

**Comment by arcin** [comment]
Just got it working.

**It was a permissions issue with `spotifyd.conf`.**

I tried:
1. `chown -R root:root ~/.config/spotifyd/`
2. `sudo ./target/release/spotifyd --config-path=/users/me/.config/spotifyd/spotifyd.conf --no-daemon --backend portaudio`

And got it working. To confirm I tried:
1. `chown -R me:me ~/.config/spotifyd/`
2. `./target/release/spotifyd --config-path=/users/me/.config/spotifyd/spotifyd.conf --no-daemon --backend portaudio`

both times got:

```
Loading config from "/users/me/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
Connecting to AP "****.spotify.com:443"
Authenticated as "**********" !
Country: "US"
```

Still got the error about the address not being available but its not affecting usability.
spotifyd just fell back to IPv4
```
$ lsof -nP -iTCP:1234 | grep LISTEN | awk '{print $1, $5, $9}'
spotifyd IPv4 *:1234
```

**Comment by arcin** [comment]
Also last note,

I rebuilt `tags/v0.2.19`, `tags/v0.2.24`, and master and got them all working.
I was unable to get it working with the  macos binaries (full or slim) provided on the release page.

**Comment by slondr** [comment]
I still get the "Failed to register Ipv6 receiver..." message on v0.3, but macOS pops up with a message box asking me to allow it. When I hit "Okay" spotifyd does not crash or report any errors.
![Screen Shot 2021-01-17 at 4 42 44 PM](https://user-images.githubusercontent.com/13040688/104856927-2d8d7d80-58e3-11eb-8bc1-f54dfec6720f.png)
