### ISSUE TITLE
Any chance for spotifyd to work also in free mode (no premium account)?

### ISSUE THREAD

**Issue by pms967** [Spotifyd/spotifyd#566]
The subj. says it all: are there any chance for spotifyd to possibly work also in "free" (ads...) mode, that is without a premium account?

**Comment by zsolt-donca** [comment]
I am not the maintainer of any of these libraries (so forgive me if I get this wrong), but I think this is because of [librespot](https://github.com/librespot-org/librespot):

> Note: librespot only works with Spotify Premium. This will remain the case for the foreseeable future, as we are unlikely to work on implementing the features such as limited skips and adverts that would be required to make librespot compliant with free accounts.

**Comment by SirWindfield** [comment]
https://github.com/Spotifyd/spotifyd/issues/536
https://github.com/librespot-org/librespot/issues/415
