### ISSUE TITLE
Cargo build takes a long time to build

### ISSUE THREAD

**Issue by gearhead** [Spotifyd/spotifyd#569]
**Is your feature request related to a problem? Please describe.**
I build this for RaspberryPi and have a build environment set up to use distccd and many packages build very quickly on my distributed build network. This package does not because it uses 'cargo' build. I have no idea what cargo is other than it cannot use a distributed build network

**Describe the solution you'd like**
Can this be alternately built using standard build commands supported by distccd? I believe even meson and ninja builds are supported. I would like to see an alternate build suggestion on the main page which would support make, ninja or meson.

**Describe alternatives you've considered**
I build it natively on the RPI which takes hours. 

<!-- **Additional context**
My system is a RPI3+ as a build environment and 2 Arch x64 machines as slaves to facilitate building all the packages I need for the Audio appliance I am developing. I build for armv6 and armv7. I have a chroot environment for armv6 so I can build those packages on the armv7. Cargo build does not seem to be supported by distccd which causes it to build completely on the RPi. Can you suggest other build instructions which use make, ninja or meson? I am not well versed in this aspect of building packages. I am not interested in any of the binaries other than the main spotifyd package.

**Comment by SirWindfield** [comment]
There is no other way to compile Rust right now (as far as I know). The compiler itself, `rustc` can be invoked but the command line is rather ambiguous. `cargo` is the package manager of the Rust ecosystem. It is also used to run test code, compile your binary for debugging and release mode. Under the hood, it just invokes `rustc`. `cargo` already does a great job when compiling, compiling multiple dependencies in parallel and using all available system resources. 

However, after some research, I couldn't find any distributed solution. `distccd` would have to implement the support, but they referred in https://github.com/rust-lang/cargo/issues/7046 to another project. I stumbled across https://github.com/sgeisler/cargo-remote as well. This allows you to send the compilation to just one other machine, but that would probably still help you out as compilation on the PI is rather slow. 

We offer pre-compiled binaries through Github Actions. You can use those if they happen to match your arch and feature set you want to use.
