### ISSUE TITLE
Panic with message: subscritpion terminated

### ISSUE THREAD

**Issue by xmarinusx** [Spotifyd/spotifyd#57]
All of a sudden Spotifyd won't work anymore. Log:
`15:48:09 [INFO] Connecting to AP "gew1-accesspoint-a-0cpb.ap.spotify.com:4070"
15:48:10 [INFO] Authenticated as "<username>" !
15:48:10 [INFO] Using alsa sink
15:48:10 [ERROR] Caught panic with message: subscription terminated`

Seems to be an issue with Librespot: https://github.com/plietar/librespot/issues/185 
Looks like they've fixed it already, is there anything I can do to fix this?

**Comment by SimonPersson** [comment]
You could try to update the librespot dependency and rebuild. It might be as easy as `cargo update; cargo buil`, but more likely there will be some breakage. I don't have time to look into it at the moment, unfortunately, but will accept pull requests :)

**Comment by rickbrandt** [comment]
I was having the same issues. I was just using the preompiled binary, getting the lastest indeed solved it. 

Is there a tut on how to compile it myself so I can cargo update and get it to work again myself? 

Cheers

**Comment by SimonPersson** [comment]
You need to install Rust (https://www.rust-lang.org/en-US/install.html), then you run `cargo build --release` inside this repository. I haven't included instructions, as the steps are the same for any project written in rust.
