### ISSUE TITLE
Can't start spotifyd without --no-daemon

### ISSUE THREAD

**Issue by gregf** [Spotifyd/spotifyd#576]
Using FreeBSD 13-current.
rustc 1.42.0

Running spotifyd --no-daemon starts and I'm able to use spotify-tui to play music.

```
RUST_BACKTRACE=full spotifyd
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: Some(stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
) })), backtrace: Some(stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
) })', src/main.rs:40:26
stack backtrace:
   0:          0x1a33b97 - <unknown>
   1:          0x1a5492e - <unknown>
   2:          0x1a30042 - <unknown>
   3:          0x1a1e25d - <unknown>
   4:          0x1a1df54 - <unknown>
   5:          0x1a1e8d1 - <unknown>
   6:          0x1a1e4c1 - <unknown>
   7:          0x1a59b00 - <unknown>
   8:          0x1a59b86 - <unknown>
   9:          0x13fa7ec - <unknown>
  10:          0x1422b76 - <unknown>
  11:          0x1a1e388 - <unknown>
  12:          0x1a393cb - <unknown>
  13:          0x1a22402 - <unknown>
  14:          0x13faa4a - <unknown>
  15:          0x13c9c9f - <unknown>
```

**Comment by MatthiasGrandl** [comment]
Having exactly the same issue on Void Linux (from the official repo)

**Comment by galmio** [comment]
Same problem with `spotifyd 0.2.24` and `rustc 1.41.1` in Void Linux. Have had to resort to run it in the background with `screen` with the `--no-daemon` flag.

**Comment by sirtomato999** [comment]
Exact same issue from Void official repo and when built.

**Comment by SirWindfield** [comment]
I am not that familiar with Linux internals, but does running it as a daemon make it somehow have different access to the file system? It works when run normally without daemonizing it.

What if you guys leave out the `--no-daemon` flag __but__ pass down all relevant arguments over the CLI? Might be a better idea to use `password_cmd` instead of `password` to not make your pw appear in your history.

**Comment by gregf** [comment]
@SirWindfield not for me, my cache path exists I just looked into it, and that gives a different error than what I get.

**Comment by elianiva** [comment]
also facing the same issue here. I'm using Artix runit and spotifyd is compiled with rust 1.44.1
It's running when using --no-daemon flag but doesn't get detected on spotify-tui as a device

**Comment by rolfrb** [comment]
Had the same problem for Void Linux. I believe it might be cause by [Void not having a syslog damon by default](https://docs.voidlinux.org/config/services/logging.html) ? After installing socklog-unix, I can start spotifyd without --no-daemon.

**Comment by gregf** [comment]
@rolfrb I'm on FreeBSD and I have a syslog server by default.

**Comment by MatthiasGrandl** [comment]
@rolfrb Thanks for the hint, it's been a while since I tried changing something with the spotifyd setup, but yeah now with socklog enabled, it works.

**Comment by SirWindfield** [comment]
@gregf looks like it fails during logging initialization. I literally can't come up with anything other than:
1) You miss permissions to actually use the syslog server instance.
2) It somehow doesn't detect the server. 

As far as I can tell, the library we use though supports FreeBSD, or at least no issues have been opened regarding FreeBSD.

@MatthiasGrandl Great that it works now for you! It might be worth adding an entry into the wiki for people that have the same problem ;)

**Comment by gregf** [comment]
@SirWindfield I'll take another look soon, might be something I'm overlooking with how my syslog is set up. Thank you for your hard work.

**Comment by SirWindfield** [comment]
any news @gregf?

I get the feeling that this issue might be a good idea to implement some kind of detection algorithm before initializing the `syslog` logger. On that note, I opened up discussion for a more sophisticated solution using `tracing` at #634.

**Comment by gregf** [comment]
@SirWindfield Sorry for the delay, I happened to need a reinstallation on my system, so I did that the other day. Since then, it's been starting fine. I believe it may be a sysctl.conf setting I had before, but I haven't enabled my file to track down which one was causing it just yet.

**Comment by SirWindfield** [comment]
No problem! Glad that it works now! I'll close the issue for now and mark it as `advice`.

**Comment by jbg** [comment]
I'm using it on a minimal Alpine system that doesn't have a syslog daemon and I have this problem too. Maybe logging could be configurable? (If you don't want to impl any other backends than the syslog socket, maybe just the ability to turn it off?)

**Comment by SirWindfield** [comment]
#654

**Comment by viktor-ku** [comment]
I've had the same issue on artix (arch with runit), solved by installing `syslog-ng` from aur. Might be helpful for someone.
