### ISSUE TITLE
inexistant gist in the wiki

### ISSUE THREAD

**Issue by ChausseBenjamin** [Spotifyd/spotifyd#580]
**The wiki mentions a gist for notifications (under user made scripts). The script doesn't exist anymore...**

[Here is the page I am refering to.](https://github.com/Spotifyd/spotifyd/wiki/User-supplied-scripts)
Perhaps the script should not be a gist but simply pasted in raw format in the wiki...

**Comment by awerlang** [comment]
link fixed.
