### ISSUE TITLE
spotifyd silently stops playing music and vanishes from device list

### ISSUE THREAD

**Issue by tfc** [Spotifyd/spotifyd#586]
**Description**

I have started using spotifyd regularly as a systemd user service and use other spotify devices to remote control its playlist. That generally works flawlessly.

But from time to time, spotifyd simply stops playing music.
This happens *always* after a suspend&resume cycle, where it first finishes playing the song that was already playing before suspend. Then it stops and also vanishes from the device list on other spotify devices.

It does also randomly stop after a few hours.

In order to make it play again, i restart the systemd process via `systemctl --user restart spotifyd.service`. Then it pops up in the device list on other devices again and i can restart the music.

There are *no* error messages in spotifyd's output. `--verbose` makes no difference.

**To Reproduce**

1. Run spotifyd with music regularly, see it stopping a few times per day
2. Run spotifyd with music, then suspend laptop, then resume, then wait until it stops playing after the currently playing song.

**Expected behavior**

I expect spotifyd to at least detect this failure. There are different ways that would help:

- Detect this problem and give me the possibility to restart the process after matching some kind of error log line.
- Detect this behavior and reset/restart the connection itself, ideally resume song automatically.
- Fix the problem in a way that it does not occur at all.

**Logs**
<details><summary>Click to show logs</summary>

  

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

cargo build flags are `[ "--no-default-features" "--features" "alsa_backend,pulseaudio_backend," ]`, as defined in: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/spotifyd/default.nix

**Versions (please complete the following information):**
 - OS: NixOS 20.03
 - Spotifyd: 0.2.24
- cargo: 1.41.0 (NixOS 20.03 default)

**Comment by SirWindfield** [comment]
A lot of stuff is probably happening here. A log would be nice so I can filter out some of the things. Problems that might occur here:
- RateLimit errors. The binary uses a CLIENT_ID that is the same for all users of the daemon. You can specify your own using SPOTIFYD_CLIENT_ID env variable (iirc). If rate limits are hit the daemon can stop working.
- Network disconnects (which can easily happen if going to sleep) will result in the daemon hard-locking. The underlying library does handle reconnects (I think) but it's not merge yet, as I had no time at all for spotifyd the last couple weeks. Uni takes most of my time now and the bits of spare time is dedicated to reading to be honest.

**Comment by idofr** [comment]
Right, so i've been seeing the same behaviour with my systems as well.
It throws `Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }` and crushes.

For testing, I've stopped the systemctl service and just executed it manually from the command line. I'm not using a config file, but rather the following command line arguments
`--backend alsa --bitrate 160 --no-daemon --verbose --device-type speaker` (and, of course, username and password)
I'd also prefer playing music at 320bps but this seems to increase and crushes

**Comment by tfc** [comment]
@SirWindfield i ran spotifyd with the `--verbose` flag and waited until it crashed. the log is extremely long and contains so many things that i don't even know where to cut it off in order to reduce it.
It also seems to contain information specific to my user account... so i feel like it's not a cool idea to openly share it here, but if it helps i would send it to you via email.

**Comment by jakkul** [comment]
I have this on Ubuntu 20.04 64 bit with the latest 0.2.24, slim binary from the releases page.

Running using:
sudo -u spotifyd /home/spotifyd/spotifyd --device default:CARD=HUDmx1 -B 320 --no-daemon

last few lines of the log:

ALSA lib pcm_direct.c:589:(snd_pcm_direct_slave_recover) recover: unable to prepare slave
ALSA lib pcm_direct.c:589:(snd_pcm_direct_slave_recover) recover: unable to prepare slave
ALSA lib pcm_direct.c:589:(snd_pcm_direct_slave_recover) recover: unable to prepare slave
ALSA lib pcm_direct.c:589:(snd_pcm_direct_slave_recover) recover: unable to prepare slave
ALSA lib pcm_direct.c:589:(snd_pcm_direct_slave_recover) recover: unable to prepare slave
Caught panic with message: called `Result::unwrap()` on an `Err` value: Error("snd_pcm_recover", Sys(EIO))
error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"

the "error sending packet" message is not important - this happens from time to time.

**Comment by ah-** [comment]
I'm seeing the same, with regular `Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }` in the logs while spotifyd restarts and stops playing.

Is this what 
>The underlying library does handle reconnects (I think) but it's not merge yet
mentions? Is the any way of testing by building with a newer librespot?

**Comment by SirWindfield** [comment]
@ah- I do thing you even linked to a fork yourself that did update librespot to a newer version. As far as I remember the librespot library just specified a bool flag that has to be set.

**Comment by nelson-liu** [comment]
now that #596 is in, should we expect the next release to resolve this issue (and support network reconnects)?

**Comment by busybox11** [comment]
Any update on this?

**Comment by numero69** [comment]
updates?

**Comment by eladyn** [comment]
As far as I'm concerned, `spotifyd` does handle connection losses now more gracefully (unreleased). The situation is still not ideal, however, that will require improvements in `librespot`.
