### ISSUE TITLE
Premium only?

### ISSUE THREAD

**Issue by Hoeze** [Spotifyd/spotifyd#59]
I'm using spotifyd + Spotify web player as alternative to the desktop client, because I cannot install it on some of my linux systems.
This worked great some weeks ago, however, when I tried to use it again today the web player does not recognize it any more.

Using the spotify Desktop client on a windows machine, I get the info, that spotifyd is "Premium-users only".
Is it possible that Spotify blacklisted spotifyd?

**Comment by SimonPersson** [comment]
Yes, spotifyd requires premium. I'm a bit surprised that it worked for you
before!

**Comment by SuperKenVery** [comment]
Without premium I get Spotify connect. 

The AV receiver in my home does not need logging in but shows up in Spotify connect. So I guess without premium and logging-in it should be able to show up. 

However connecting to a **phone** using Spotify connect is a premium-only feature. Maybe you could try changing Spotifyd's device to something else?
