### ISSUE TITLE
DBus Play/Pause actions are very slow

### ISSUE THREAD

**Issue by phenax** [Spotifyd/spotifyd#591]
**Description**
All actions taken via the dbus api are very slow and take at least 2 seconds to reflect

**To Reproduce**
- I installed `spotifyd-dbus-mpris` from AUR
- I ran `playerctl play-pause`

**Expected behavior**
I'd expect the interaction to be instant

**Versions (please complete the following information):**
 - OS: Arch 
 - Spotifyd: 0.2.24
- cargo: 1.43.0

**Comment by awerlang** [comment]
For me `sp play` is instant (media key still pressed when playback resumes), `sp pause` takes about a second, so I guess it's a buffer thing. Using alsa backend. Which backend are you running?

**Comment by awerlang** [comment]
I tried with the pulseaudio backend, and now both pause/resume is instant.

**Comment by phenax** [comment]
I'm using alsa. I'll try using pulseaudio.

**Comment by karl-malakoff** [comment]
I'm also having this issue using the same versions using pulseaudio. I've tried both playerctl and sp.

**Comment by phenax** [comment]
Yeah pulseaudio didn't work either. Any ideas?

**Comment by karl-malakoff** [comment]
It works quickly when using https://github.com/hugosenari/mpris2 in iPython

It must be an issue with playerctl/sp and the way they use dbus, they could be making a new connection each time which would take time.

**Comment by phenax** [comment]
I'm not sure if its a playerctl thing. I use playerctl for the official spotify client and other media as well without any delay. I've only noticed it with spotifyd.

**Comment by ayosec** [comment]
If you monitor the D-Bus messages with `dbus-monitor` you can see that every time playerctl is executed it tries to get all properties from spotifyd. The metadata property (and maybe something else) requires a call to the Spotify API. I think that this is the cause of the issue with playerctl.

Now I'm using a [simple script](https://gist.github.com/ayosec/bf6f608c3c4871325293d1ea43e8452e) to invoke the D-Bus methods (play, next, etc) with `dbus-send`, so no metadata is required. playerctl is still used to get the player name, but this operation is always fast.

**Comment by 7ijme** [comment]
Has anyone found a fix for this? I'm still experiencing slow play and pause times.

**Comment by eladyn** [comment]
This should hopefully be fixed in the next release. If you want, you can try one of these PRs: #1317 or #1321. They both include a change to do all the MPRIS handling without the Web API.
