### ISSUE TITLE
Connecting from other devices hangs

### ISSUE THREAD

**Issue by JunichiSugiura** [Spotifyd/spotifyd#592]
**Description**
I tried to connect from web/iOS app after successfully starting the daemon. spotifyd shows up as a device but it hangs on "Connecting..." after selecting.

**To Reproduce**

Connect and start playing song.

**Logs**
<details><summary>Click to show logs</summary>

>  spotifyd --verbose --no-daemon
Loading config from "/Users/xxx/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: None, password_cmd: None, use_keyring: true, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: Some(PortAudio), volume_controller: Some(SoftVolume), device: None, control: None, mixer: Some("PCM"), device_name: Some("spotifyd"), bitrate: Some(Bitrate320), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: Some(1234), proxy: None } }
Found shell "/bin/zsh" using SHELL environment variable.
No proxy specified
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
build; num-workers=8
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
registering; token=Token(0); interests=Readable | Writable | Error | Hup
Zeroconf server listening on 0.0.0.0:1234
adding I/O source: 4194305
registering with poller
registering; token=Token(4194305); interests=Readable | Writable | Error | Hup
event Writable Token(4194305)
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
loop process - 1 events, 0.000s
Checking keyring for password
adding I/O source: 8388610
registering with poller
registering; token=Token(8388610); interests=Readable | Writable | Error | Hup
event Writable Token(8388610)
loop process - 1 events, 0.000s
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://apresolve.spotify.com/")
resolving host="apresolve.spotify.com", port=80
consuming notification queue
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
scheduling Read for: 2
loop poll - 167.932µs
loop time - Instant { t: 93912174740916 }
loop process, 8.289µs
event Readable Token(4194305)
loop process - 1 events, 0.000s
received packet from V4(192.168.1.11:5353)
received packet from V4(192.168.1.11:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
loop poll - 51.12µs
loop time - Instant { t: 93912174805758 }
loop process, 2.539µs
loop poll - 828.823µs
loop time - Instant { t: 93912175638582 }
loop process, 7.069µs
connecting to 34.98.74.57:80
adding I/O source: 12582915
registering with poller
registering; token=Token(12582915); interests=Readable | Writable | Error | Hup
scheduling Write for: 3
event Writable Token(12582915)
loop process - 1 events, 0.000s
loop poll - 25.064573ms
loop time - Instant { t: 93912200803963 }
loop process, 20.037µs
read_keep_alive; is_mid_message=false
scheduling Read for: 3
should_keep_alive(version=Http11, header=None) = true
Client::encode has_body=false, method=None
reclaiming write buf Vec
flushed 47 bytes
flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 296.578µs
loop time - Instant { t: 93912201307106 }
loop process, 12.399µs
event Writable Token(12582915)
loop process - 1 events, 0.000s
event Readable Token(12582915)
loop process - 1 events, 0.000s
Conn::read_head
read 648 bytes
Response.parse([Header; 100], [u8; 648])
Response.parse Complete(230)
maybe_literal not found, copying "Via"
parsed 7 headers (230 bytes)
incoming body is content-length (418 bytes)
expecting_continue(version=Http11, header=None) = false
should_keep_alive(version=Http11, header=None) = true
Conn::read_body
decode; state=Length(418)
flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 24.71061ms
loop time - Instant { t: 93912226038772 }
loop process, 13.792µs
Conn::read_body
decode; state=Length(0)
incoming body completed
scheduling Read for: 3
maybe_notify; read_from_io blocked
read_keep_alive; is_mid_message=false
scheduling Read for: 3
signal: Want
flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
wants_read_again? false
poll_want: taker wants!
pool dropped, dropping pooled ("http://apresolve.spotify.com")
loop poll - 195.719µs
loop time - Instant { t: 93912226337328 }
loop process, 27.389µs
Connecting to AP "gew1-accesspoint-b-9f0d.ap.spotify.com:443"
adding I/O source: 16777220
registering with poller
registering; token=Token(16777220); interests=Readable | Writable | Error | Hup
scheduling Write for: 4
read_keep_alive; is_mid_message=false
scheduling Read for: 3
client tx closed
State::close_read()
State::close_write()
flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 3
signal: Closed
loop poll - 118.735µs
loop time - Instant { t: 93912254308213 }
loop process, 9.969µs
event Writable Token(16777220)
loop process - 1 events, 0.000s
loop poll - 122.22102ms
loop time - Instant { t: 93912376544713 }
loop process, 17.297µs
scheduling Read for: 4
event Readable | Writable Token(16777220)
loop process - 1 events, 0.000s
loop poll - 121.478337ms
loop time - Instant { t: 93912510499531 }
loop process, 66.546µs
flushing framed transport
writing; remaining=123
framed transport flushed
scheduling Read for: 4
event Writable Token(16777220)
loop process - 1 events, 0.000s
event Writable Token(16777220)
loop process - 1 events, 0.000s
event Readable Token(16777220)
loop process - 1 events, 0.000s
loop poll - 147.396706ms
loop time - Instant { t: 93912670865714 }
loop process, 19.483µs
attempting to decode a frame
frame decoded from buffer
Authenticated as "1298588441" !
new Session[0]
new Spirc[0]
new MercuryManager
new Player[0]
Using PortAudio sink
input volume:65535 to mixer: 65535
attempting to decode a frame
frame decoded from buffer
Session[0] strong=4 weak=2
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
Country: "DE"
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
writing; remaining=871
framed transport flushed
loop poll - 318.686µs
loop time - Instant { t: 93912671861572 }
loop process, 15.322µs
event Readable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 1.064662ms
loop time - Instant { t: 93912672950681 }
loop process, 9.768µs
event Readable | Writable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 33.842936ms
loop time - Instant { t: 93912706809320 }
loop process, 3.416µs
subscribed uri=hm://remote/user/1298588441/ count=0
loop poll - 1.557µs
loop time - Instant { t: 93912706838410 }
loop process, 17.061µs
event Readable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 77.682796ms
loop time - Instant { t: 93912784539714 }
loop process, 13.795µs
k^Cevent Readable Token(8388610)
loop process - 1 events, 0.000s
V^Cevent Readable Token(8388610)
loop process - 1 events, 0.000s

  

</details>

**Versions (please complete the following information):**
 - OS: macOS Catalina v 10.15.4
 - Spotifyd: v0.2.24

installed by `brew install Spotifyd/tap/spotifyd`

**Comment by awerlang** [comment]
Do you have a firewall set up? If yes, you need to open 2 TCP/UDP ports, I guess only 5353/UDP is open, and you need to specify a `zeroconf-port` and open that TCP port.

**Comment by jgabriel98** [comment]
> I tried to connect from web/iOS app after successfully starting the daemon. spotifyd shows up as a device but it hangs on "Connecting..." after selecting.

Same happening here, it happens when running as a service. 
But when spotifyd is launched by CLI command it will connect successfully.

i am running the spotifyd in a raspberry, with raspberry OS (raspbian), with no firewall.

I don't know which logs or infos would be relevant for this issue, so feel free to ask for some.

**Comment by jgabriel98** [comment]
here some usefull info:

When i ran was a system service, and try to connect to it as a **spotify connect device**, i get the following journalctl logs:
```
-- Logs begin at Thu 2019-02-14 08:11:59 -02. --
jul 23 12:13:36 raspberrypi systemd[1]: spotifyd.service: Succeeded.
jul 23 12:13:36 raspberrypi systemd[1]: Stopped A spotify playing daemon.
jul 23 12:13:36 raspberrypi systemd[1]: Started A spotify playing daemon.
jul 23 12:13:36 raspberrypi spotifyd[2297]: No config file specified. Running with default values
jul 23 12:13:36 raspberrypi spotifyd[2297]: No username specified. Checking username_cmd
jul 23 12:13:36 raspberrypi spotifyd[2297]: No username_cmd specified
jul 23 12:13:36 raspberrypi spotifyd[2297]: No password specified. Checking password_cmd
jul 23 12:13:36 raspberrypi spotifyd[2297]: No password_cmd specified
jul 23 12:13:36 raspberrypi spotifyd[2297]: No proxy specified
jul 23 12:13:36 raspberrypi spotifyd[2297]: Using software volume controller.
jul 23 12:13:44 raspberrypi spotifyd[2297]: Caught panic with message: index 16 out of range for slice of length 0
jul 23 12:13:44 raspberrypi systemd[1]: spotifyd.service: Main process exited, code=exited, status=101/n/a
jul 23 12:13:44 raspberrypi systemd[1]: spotifyd.service: Failed with result 'exit-code'.
jul 23 12:13:56 raspberrypi systemd[1]: spotifyd.service: Service RestartSec=12s expired, scheduling restart.
jul 23 12:13:56 raspberrypi systemd[1]: spotifyd.service: Scheduled restart job, restart counter is at 1.
jul 23 12:13:56 raspberrypi systemd[1]: Stopped A spotify playing daemon.
jul 23 12:13:56 raspberrypi systemd[1]: Started A spotify playing daemon.
jul 23 12:13:56 raspberrypi spotifyd[2321]: No config file specified. Running with default values
jul 23 12:13:56 raspberrypi spotifyd[2321]: No username specified. Checking username_cmd
jul 23 12:13:56 raspberrypi spotifyd[2321]: No username_cmd specified
jul 23 12:13:56 raspberrypi spotifyd[2321]: No password specified. Checking password_cmd
jul 23 12:13:56 raspberrypi spotifyd[2321]: No password_cmd specified
jul 23 12:13:56 raspberrypi spotifyd[2321]: No proxy specified
jul 23 12:13:56 raspberrypi spotifyd[2321]: Using software volume controller.
```
the relevant lines are:
jul 23 12:13:44 raspberrypi systemd[1]: **spotifyd.service: Main process exited, code=exited, status=101/n/a**
jul 23 12:13:44 raspberrypi systemd[1]: **spotifyd.service: Failed with result 'exit-code'.**

does any one knows what "status=101/n/a" means?

**Comment by jgabriel98** [comment]
Update:

after enabling verbose log, the problem was with DBUS:

```
jul 23 12:26:35 raspberrypi spotifyd[2644]: Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
jul 23 12:26:35 raspberrypi spotifyd[2644]: drop Spirc[0]
jul 23 12:26:35 raspberrypi spotifyd[2644]: Shutting down player thread ...
```

**Comment by SirWindfield** [comment]
Yep, we use the session bus type. You can try to run it as described in this comment:
https://github.com/Spotifyd/spotifyd/issues/244#issuecomment-583881263

**Comment by jgabriel98** [comment]
for now we can only enable system dbus by changing the code right?
there is no CLI flag or settings in `.conf` file to set it?

**Comment by SirWindfield** [comment]
Yes
