### ISSUE TITLE
spotifyd not showing in spotify-tui devices

### ISSUE THREAD

**Issue by Fraemwerk** [Spotifyd/spotifyd#593]
Hi, this is only my third day using linux so I would really appreciate it if you could help inform me on how to provide the correct information/logs for this.
I've got spotify-tui running fine and spotifyd set up as a service but when I open up spotify-tui there are no devices listed. If i open spotify on my phone it shows up and then acts as a controller for my phone but I cannot get spotify to play directly on my PC.

 Running `systemctl --user status spotifyd.service` shows this
```
● spotifyd.service - A spotify playing daemon
     Loaded: loaded (/etc/xdg/systemd/user/spotifyd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2020-05-22 22:52:07 BST; 2s ago
       Docs: https://github.com/Spotifyd/spotifyd
    Process: 232407 ExecStart=/usr/bin/spotifyd --no-daemon (code=exited, status=101)
   Main PID: 232407 (code=exited, status=101)

```

**Comment by awerlang** [comment]
The service is dead, watch out for issues in the journal:

`journalctl --user -b -u spotifyd.service`

I suspect it didn't find the spotifyd binary, it's not usually in /usr/bin.

**Comment by jacobhilker1** [comment]
I'm also having the problem.

**Comment by acgollapalli** [comment]
Thirded. I've got this problem as well.  journalctl results:

```
May 30 21:00:16 nixbox spotifyd[21404]: No proxy specified
May 30 21:00:16 nixbox spotifyd[21404]: Using software volume controller.
May 30 21:00:16 nixbox spotifyd[21404]: error sending packet Os { code: 99, kind: AddrNotAvai>
May 30 21:00:17 nixbox spotifyd[21404]: Connecting to AP "guc3-accesspoint-b-tb5z.ap.spotify.>
May 30 21:00:17 nixbox spotifyd[21404]: Authenticated as "<redacted>" !
May 30 21:00:17 nixbox spotifyd[21404]: Country: "US"
May 30 21:02:35 nixbox spotifyd[21404]: Os { code: 104, kind: ConnectionReset, message: "Conn>

```

**Comment by s1aught** [comment]
Having the same problem

**Comment by Purgeme** [comment]
Mine doesn't even start, when I do "spotifyd -V" it gives me the verion number and thats it

**Comment by laurinneff** [comment]
@Purgeme that's intended. If you want verbose output, use --verbose.

**Comment by Cardosaum** [comment]
I'm also having this very same issue.

**Comment by EsmailELBoBDev2** [comment]
i'ts because the service file looking in wrong place about your installation 
```
[Service]
ExecStart=/usr/bin/spotifyd --no-daemon

``` 
to fix it, just replace it with your dir of spotifyd (ex: /home/esmailelbob/Desktop/spotifyd/target/release/spotifyd)

**Comment by CaptainAsbestos** [comment]
getting the exact same problem still. running on the most recent manjaro.

**Comment by IJustDev** [comment]
I had the exact same issue also on Manjaro. It seemed like it was because of the missing credentials passed to the `spotifyd` program.

You may want to add them when running `spotifyd -u USERNAME -p PASSWORD`.

**Comment by Eteaisme** [comment]
Has anyone found a fix for this?
