### ISSUE TITLE
Proxy Authentication isn't working

### ISSUE THREAD

**Issue by KebabMasquay** [Spotifyd/spotifyd#595]
**Description**
I can't use my proxy with credentials when I try to use the daemon. I have this error : Proxy responded with 407: Proxy Authentication Required

**To Reproduce**
1. spotifyd --no-daemon --proxy http://proxyUser:proxyPass@ProxyIP:ProxyPort/
2. See logs :
`No config file specified. Running with default values
Using software volume controller.
Failed to resolve Access Point: invalid JSON
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
Using proxy "http://proxyUser:proxyPass@ProxyIP:ProxyPort/"
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Proxy responded with 407: Proxy Authentication Required" }
` 

**Expected behavior**

**Logs**
<details><summary>Click to show logs using verbose</summary>
No config file specified. Running with default values
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: Some("Poulet2"), bitrate: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: Some("http://proxyUser:proxyPass@ProxyIP:ProxyPort") } }
Found shell "/bin/bash" using SHELL environment variable.
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=4
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:42389
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
loop process - 1 events, 0.000s
adding I/O source: 8388610
registering with poller
event Writable Token(8388610)
loop process - 1 events, 0.000s
adding I/O source: 12582915
registering with poller
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://proxyUser:proxyPass@ProxyIP:ProxyPort/")
connecting to ProxyIP:ProxyPort
event Writable Token(12582915)
loop process - 1 events, 0.000s
adding I/O source: 16777220
registering with poller
scheduling Write for: 4
consuming notification queue
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 2
sending packet to V6([ff02::fb]:5353)
scheduling Read for: 3
loop poll - 1.415899ms
loop time - Instant { tv_sec: 7577, tv_nsec: 71080900 }
loop process, 162.714µs
received packet from V4(192.168.127.129:5353)
received packet from V4(192.168.127.129:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
scheduling Read for: 2
loop poll - 154.847µs
loop time - Instant { tv_sec: 7577, tv_nsec: 71412547 }
loop process, 88.138µs
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
scheduling Read for: 1
received packet from V6([fe80::20c:29ff:fe61:710d]:5353)
received packet from V6([fe80::20c:29ff:fe61:710d]:5353) with no query
scheduling Read for: 2
scheduling Read for: 2
loop poll - 650.485µs
loop time - Instant { tv_sec: 7577, tv_nsec: 72163946 }
loop process, 10.619µs
event Readable Token(0)
loop process - 1 events, 0.000s
scheduling Read for: 0
loop poll - 953.378µs
loop time - Instant { tv_sec: 7577, tv_nsec: 73133869 }
loop process, 54.174µs
Conn::read_head
adding I/O source: 20971525
registering with poller
scheduling Read for: 5
flushed State { reading: Init, writing: Init, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 321.295µs
loop time - Instant { tv_sec: 7577, tv_nsec: 73520521 }
loop process, 20.949µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
Conn::read_head
read 225 bytes
Request.parse([Header; 100], [u8; 225])
Request.parse Complete(225)
maybe_literal not found, copying "Keep-Alive"
parsed 6 headers (225 bytes)
incoming body is content-length (0 bytes)
expecting_continue(version=Http11, header=None) = false
should_keep_alive(version=Http11, header=Some(Connection([KeepAlive]))) = true
read_keep_alive; is_mid_message=true
should_keep_alive(version=Http11, header=None) = true
Server::encode has_body=true, method=Some(Get)
encoding chunked 444B
flushed 540 bytes
scheduling Read for: 5
maybe_notify; read_from_io blocked
flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
wants_read_again? false
loop poll - 678.955µs
loop time - Instant { tv_sec: 7577, tv_nsec: 74294576 }
loop process, 30.229µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
Conn::read_head
read 0 bytes
parse eof
State::close_read()
read eof
read_keep_alive; is_mid_message=true
flushed State { reading: Closed, writing: Init, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 5
loop poll - 51.428604ms
loop time - Instant { tv_sec: 7577, tv_nsec: 125765877 }
loop process, 23.619µs
event Writable Token(16777220)
loop process - 1 events, 0.000s
loop poll - 11.985838ms
loop time - Instant { tv_sec: 7577, tv_nsec: 137783888 }
loop process, 48.32µs
read_keep_alive; is_mid_message=false
scheduling Read for: 4
should_keep_alive(version=Http11, header=None) = true
Client::encode has_body=false, method=None
reclaiming write buf Vec
flushed 75 bytes
flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 250.523µs
loop time - Instant { tv_sec: 7577, tv_nsec: 138211518 }
loop process, 44.87µs
event Readable | Writable Token(16777220)
loop process - 1 events, 0.000s
Conn::read_head
read 407 bytes
Response.parse([Header; 100], [u8; 407])
Response.parse Complete(152)
maybe_literal not found, copying "Proxy-Authenticate"
maybe_literal not found, copying "Proxy-Connection"
parsed 3 headers (152 bytes)
neither Transfer-Encoding nor Content-Length
incoming body is until end-of-file
expecting_continue(version=Http10, header=None) = false
should_keep_alive(version=Http10, header=None) = false
Conn::read_body
decode; state=Eof(false)
flushed State { reading: Body(Eof(false)), writing: KeepAlive, keep_alive: Disabled, error: None }
wants_read_again? false
loop poll - 101.14155ms
loop time - Instant { tv_sec: 7577, tv_nsec: 239405740 }
loop process, 18.81µs
Conn::read_body
decode; state=Eof(false)
read 0 bytes
incoming body completed
State::close()
read_keep_alive; is_mid_message=true
flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 4
signal: Closed
loop poll - 175.28µs
loop time - Instant { tv_sec: 7577, tv_nsec: 239663318 }
loop process, 12.578µs
Failed to resolve Access Point: invalid JSON
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
Using proxy "http://proxyUser:proxyPass@ProxyIP:ProxyPort/"
adding I/O source: 25165828
registering with poller
scheduling Write for: 4
loop poll - 2.528µs
loop time - Instant { tv_sec: 7577, tv_nsec: 239915194 }
loop process, 18.587µs
event Writable Token(25165828)
loop process - 1 events, 0.000s
loop poll - 55.010563ms
loop time - Instant { tv_sec: 7577, tv_nsec: 294950725 }
loop process, 36.842µs
scheduling Read for: 4
event Readable | Writable Token(25165828)
loop process - 1 events, 0.000s
loop poll - 121.650379ms
loop time - Instant { tv_sec: 7577, tv_nsec: 416740906 }
loop process, 124.517µs
deregistering handle with poller
dropping I/O source: 4
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Proxy responded with 407: Proxy Authentication Required" }
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
deregistering handle with poller
dropping I/O source: 0 

</details>

**Versions (please complete the following information):**
 - OS: Kali/GNU Linux 2020.1
 - Spotifyd: full v0.2.24

**Additional context**
My proxy is working, I tried it just before.

**Comment by brolyxxx** [comment]
Hi, I can confirm the same happens to me, I tried to use a proxy server as a work-around solution to the VPN issue (see for example #601 )
