### ISSUE TITLE
Thread Panic on MacOS Catalina

### ISSUE THREAD

**Issue by tysaya123** [Spotifyd/spotifyd#597]
**Description**
Getting the following error when I run spotifyd
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/tychoyacub/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.1/src/cache.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
I have also checked and that file does exist at that location on my machine.

**Logs**
The exact same output is given with verbose.

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [x] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Spotifyd: spotifyd 0.2.24
- cargo: cargo 1.43.0 (2cbe9048e 2020-05-03)

**Comment by DerDoni** [comment]
The exact same error also occurs for me with Arch Linux

**Comment by tysaya123** [comment]
I fixed my issue by removing the use of cache from my config. Not sure yet if it was an issue with the specific folder I was pointing to or something else.

**Comment by tysaya123** [comment]
Ultimately it turned out that I had misspelled my cache directory. If, it works when you turn off cache then I feel confident saying its an issue with the directory yours using. If your still having the issue I would check that spotifyd will have permission to edit and that your not using $HOME or ~ or just being dumb like me.

**Comment by PlayerPL** [comment]
Hi 

i am pretty sure that my cache directory is correct. 

`cache_path = "/SpotifyCache/"`


`bash-3.2$ spotifyd --no-daemon
Loading config from "/Users/adam/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.0/src/cache.rs:30:35
stack backtrace:
   0:        0x104a9354b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7017b8ae60900b6b
   1:        0x104aaf3cd - core::fmt::write::h894d1da6a20f9776
   2:        0x104a7afeb - std::io::Write::write_fmt::ha636655ad3c17e54
   3:        0x104a81165 - std::panicking::default_hook::{{closure}}::h14b439755e59a6f3
   4:        0x104a80e6a - std::panicking::default_hook::hd0130cc02b18eabf
   5:        0x104a816cb - std::panicking::rust_panic_with_hook::h747c3c133ec2d635
   6:        0x104a81292 - rust_begin_unwind
   7:        0x104ac902f - core::panicking::panic_fmt::hbb3ec5057209c7fb
   8:        0x104ac90a5 - core::result::unwrap_failed::h046cd7c222b54140
   9:        0x10476a134 - librespot_core::cache::Cache::new::h1916348255cb26a8
  10:        0x1046069e2 - spotifyd::config::get_internal_config::he0e8d64f45981aa1
  11:        0x104616b1a - spotifyd::main::had9729e889f91998
  12:        0x1045f6366 - std::rt::lang_start::{{closure}}::h8b3172f288988805
  13:        0x104a81934 - std::rt::lang_start_internal::hf93faf993997e0c4
  14:        0x104617199 - main
`


`bash-3.2$ spotifyd --no-daemon --cache-path /SpotifyCache/
Loading config from "/Users/adam/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
Connecting to AP "gew1-accesspoint-b-jb5p.ap.spotify.com:443"
Authenticated as "xxxxxxx" !
Country: "PL"`
