### ISSUE TITLE
Additional event hooks

### ISSUE THREAD

**Issue by noelhibbard** [Spotifyd/spotifyd#599]
I see there is a on_song_change_hook. Could we get some additional hooks. For example:

**on_vol_change_hook**: With a parm that contains the volume level. I would like to use this to send REST calls to my surround receiver to change change the volume.

**on_connect_hook**: Called when client connects. I want to use this to send a REST call to turn on my surround receiver.

Thanks so much for this project. It's working great. I am coming from shairport-sync which is also a great project but AirPlay 1 requires the phone to do all the work which wastes battery and WiFi bandwidth. The responsiveness of Spotify Connect is a big improvement over AirPlay 1 too.

**Comment by ah-** [comment]
Have a look at https://github.com/marcelbuesing/spotifyd/commit/fdf086c2a3eb38b60b9445948d9f2f351196f1ff, that does seem to at least have the volume change hook already.

I'm not sure if there's an on_connect hook, I'm using the start/stopped hooks to turn on my stereo.

**Comment by noelhibbard** [comment]
> 
> 
> Have a look at [marcelbuesing@fdf086c](https://github.com/marcelbuesing/spotifyd/commit/fdf086c2a3eb38b60b9445948d9f2f351196f1ff), that does seem to at least have the volume change hook already.
> 
> I'm not sure if there's an on_connect hook, I'm using the start/stopped hooks to turn on my stereo.

Currently, there is not, I am asking if they could be added. librespot has hooks for just about every event so for now I have switched to librespot and have it turning my receiver on/off and forwarding volume events to the receiver perfectly.

**Comment by noelhibbard** [comment]
Okay this fork works perfect for my needs. It has volumeset/start/stop which is all I need.

In case others stumble on this thread. on_song_change_hook (There is a more logical alias for this config option named onevent) isn't just called on song changes. It is also called when starting, stopping, pausing, playing, setting the volume, ect. When your process is called it also sets some environment variables which you can read. Here is a list:
PLAYER_EVENT: This will be start/stop/load/play/pause/preload/endoftrack/volumeset
TRACK_ID
PLAY_REQUEST_ID
POSITION_MS
DURATION_MS
VOLUME

**Comment by ah-** [comment]
Thank @marcelbuesing for this work and hope https://github.com/Spotifyd/spotifyd/pull/596 is merged soon :)

**Comment by SirWindfield** [comment]
Sorry that I wasn't really active on this repo anymore. Uni takes most of my time right now. I'll take the time and merge wednesday evening anything that is mergable at that point. A lot of the issues are probably fixed by just bumping the versions of our dependencies.

Not sure if you remember, but you send me my current Anne V1 over @ah- :D I still owe you for that one! Great to see you using spotifyd :D

**Comment by SirWindfield** [comment]
So it looks like the PR form librespot didn't get merge so #596 will stay open until that happens, sadly.
