### ISSUE TITLE
Cannot start playback on device running spotifyd without a Spotify client

### ISSUE THREAD

**Issue by awerlang** [Spotifyd/spotifyd#609]
**Description**
Cannot start playback on device running spotifyd without another Spotify client.

It seems running spotifyd doesn't select the device as a playback device. Possibly the protocol requires a command to pick it as playback device.

**To Reproduce**
1. Start `spotifyd --no-daemon --username ... --password_cmd ...`
2. Run `sp wonderwall`
  2.1. Outcome: `Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`
3. Open a Spotify client on local network
4. Run `sp wonderwall`
  4.1. Outcome: nothing
5. Show available devices on Spotify client from step 3
6. Run `sp wonderwall`
  6.1. Outcome: playback starts on Spotify client
7. Select the spotifyd device
8. Run `sp wonderwall`
  8.1. Outcome: playback starts on spotifyd client

**Expected behavior**
Be able to start playback on spotifyd through DBUS MPRIS (steps 1-2).

**Logs**
<details><summary>Click to show logs</summary>

<STEP 1>
jun 12 16:49:53: No config file specified. Running with default values
jun 12 16:49:53: No password specified. Checking password_cmd
jun 12 16:49:53: Running "pass" using "/bin/bash"
jun 12 16:49:53: No proxy specified
jun 12 16:49:53: Using software volume controller.
jun 12 16:49:54: Connecting to AP "guc3-accesspoint-b-f29x.ap.spotify.com:443"
jun 12 16:50:00: Authenticated as "awerlang" !
jun 12 16:50:00: Country: "BR"
<STEP 2>
<STEP 3>
<STEP 4>
<STEP 5>
jun 12 16:51:52: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
jun 12 16:51:52: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
jun 12 16:51:53: Couldn't fetch metadata from spotify: Ok(None)
jun 12 16:51:54: Couldn't fetch metadata from spotify: Ok(None)
jun 12 16:51:54: Unhandled DBus message: (Error, None, None, None)
jun 12 16:51:55: Unhandled DBus message: (Error, None, None, None)
jun 12 16:52:08: Couldn't fetch metadata from spotify: Ok(None)
<STEP 6>
<STEP 7>
jun 12 16:56:10: Loading <Wonderwall - Remastered> with Spotify URI <spotify:track:5wj4E6IsrVtn8IBJQOd0Cl>
jun 12 16:56:13: <Wonderwall - Remastered> loaded
<STEP 8>
jun 12 16:56:26: Loading <Wonderwall - Remastered> with Spotify URI <spotify:track:5wj4E6IsrVtn8IBJQOd0Cl>
jun 12 16:56:28: <Wonderwall - Remastered> loaded

</details>

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Spotifyd: v0.2.24
- cargo: 1.43.0

**Comment by awerlang** [comment]
Maybe this is missing: https://developer.spotify.com/documentation/web-api/reference/player/transfer-a-users-playback/

**Comment by SirWindfield** [comment]
As of now, spotifyd runs in the background once it starts. You need to actively change the audio device using some other client (app, web, whatever).

It might be possible to automatically change the active device but this is something I'd need to investigate

**Comment by awerlang** [comment]
I managed to start playback using the Web API docs as a client.

1) Get a User's Available Devices: https://developer.spotify.com/console/get-users-available-devices/
2) Transfer a User's Playback: https://developer.spotify.com/console/put-user-player/
3) Then sp works (sp asks for client-credentials, but not user scopes, so it can't do it on its own)

I guess the majority of users are using another full-blown client. I was using the Android app to bootstrap the spotifyd device, but I've found it unreliable, not keeping playback state in sync and "forgetting" the playback device was set to spotifyd after a while.

The Web API requires the OAuth workflow, but since librespot supports username/password authentication I believe there's hope. There's this librespot sample which makes me believe it is supported already: https://github.com/librespot-org/librespot/blob/dev/examples/play.rs

It shouldn't steal the playback from another device when spotifyd is launched, but in case it's the single online device for the user account, then it could become the active device. From that point DBUS MPRIS is responsive.

Do you think this makes sense for spotifyd?

**Comment by awerlang** [comment]
Further information:

https://github.com/Spotifyd/spotifyd/blob/5db64d0a62f76a2814bd0b29d7ebc4c4a3e9c53c/src/dbus_mpris.rs#L340

It wouldn't be enough to remove the condition `.is_active`, as the dbus is not even activated yet. DBUS needs needs to be activated sooner.

The Android app plays in the active device, but activates itself in case there's none. I think this behavior can be matched. Or else ignore the `.is_active` flag and start playback on its device id (calling `sp.transfer_playback()` if required, but I don't think so).

**Comment by marcelbuesing** [comment]
Not 100% sure but my experience was when using `rspotify` that the device is not even part of the response when querying the [users device api](https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/). So I assume it won't help to ignore the is_active.

Besides that I see the same behavior, once you start playback via the desktop spotify or android spotify client, the device is listed when you query the users device api and you can start spotifyd playback via the spotify api.

Maybe this is also related to [this](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/). 

> Connect Web API relies on local network connections to discover and interact with some devices...

**Comment by awerlang** [comment]
> Not 100% sure but my experience was when using `rspotify` that the device is not even part of the response when querying the [users device api](https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/). So I assume it won't help to ignore the is_active.

But I'm not relying on local connections. I started spotifyd and these steps worked:
https://github.com/Spotifyd/spotifyd/issues/609#issuecomment-643671083

That said, I attempted to add the transfer playback call but it didn't worked. Probably I did something wrong.
