### ISSUE TITLE
DBus MPRIS control?

### ISSUE THREAD

**Issue by WhyNotHugo** [Spotifyd/spotifyd#61]
First of all, I've to say, I've been really liking `spotifyd`. Super lightweight, works just as promised! Thanks!

Onto the topic of this issue: I'm wondering if it's possible to implement the [MPRIS DBus protocol](https://specifications.freedesktop.org/mpris-spec/latest/). It's a standard protocol (at least on modern Unix-like desktops) to control media players.

Lots of tools use this to control the music players. eg: Gnome and KDE will send a pause call when the media key is pressed on the desktop, and `playerctl` could be used for similar commands too.

The end-goal here is to be able to play/pause using media keys.

[This](https://github.com/diwic/dbus-rs#server) should be really useful. Geez, I wish I'd time to sit down and learn rust, since it looks so well done!

**Comment by SimonPersson** [comment]
I'm glad you like it!

It's certainly possible, but I would prefer not to add a dbus dependency, as spotifyd is not only intended for desktop environments. Instead, I suggest that such functionality could be implemented in a separate daemon, built on top https://github.com/Spotifyd/spotifyd-http, or the new spotify connect api (although I haven't had time to look into that yet): https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/. As both APIs are HTTP, you could build this as a simple app in any language that you are comfortable in and has good dbus bindings.

**Comment by hobarrera** [comment]
Makes sense. A separate daemon is actually best, probably. The "official" API has the downside of all the OAuth dance, but it might be the best choice in general.

I'll see if I can write something up.

**Comment by hobarrera** [comment]
OTOH, a DBus API would make it possible to "start deamon when a play event is emitted" (eg: keypress, or a DE's media controls). I've mixed feelings there.

**Comment by SimonPersson** [comment]
I've changed my mind regarding this - I think it can be implemented behind a cargo feature so that the dependency is not pulled in for those who don't want it. I'll look into it.

**Comment by SimonPersson** [comment]
I've started working on this in the `dbus-mpris` branch. I notice that some methods of the spec are not possible to implement at the moment. I wonder what will break existing tools the least, exposing methods that do nothing or just not implementing them?

**Comment by SimonPersson** [comment]
@WhyNotHugo - Experimental support is now on the master branch. You can try it out by adding `--features dbus_mpris` when compiling.

**Comment by lukeab** [comment]
Added this cargo features flag to the PKGBUILD in the arch AUR (spotifyd-pulseaudio-git) and it worked perfectly. Gnome 3.26.2, play/pause media key is so required. Also running just fine as systemd unit `systemctl --user start spotifyd` 
thanks so much for this, Such a bonus to work with music wihtout eating X00MB ram for the fat electron client. Also great use of Rust!

**Comment by Fale** [comment]
Would it be possible to enable this feature in the builds?

**Comment by SimonPersson** [comment]
It was originaly enabled in the binary builds, but some people had issues. I'll reenable it once this has received some more testing.

**Comment by SimonPersson** [comment]
One outstanding feature is signals. We should ideally signal clients on song changes and other events. As it is, media buttons will work fine, but software that displays the currently playing song might not work.

**Comment by Fale** [comment]
I'm using it to control the player and it works great (if not the I was not able to make `org.mpris.MediaPlayer2.Player.Previous` work at all)

**Comment by mariusor** [comment]
If spotifyd is made to export the MPRIS interface data, it can be used in together with two of my projects: 

 * mpris-ctl - offers similar functionality as playerctl only in a smaller package.
 * mpris-scrobbler - daemon for submitting tracks to last.fm, libre.fm and listenbrainz.org.

**Comment by SimonPersson** [comment]
@mariusor - I bet mpris-ctl already works. I tested the mpris support using playerctl, which should work more or less the same I guess.

What do we need for mpris-scrobbler to work though? Spotifyd currently exposes metadata, but doesn't signal any changes. I guess that is needed to have mpris-scrobbler work?

**Comment by mariusor** [comment]
Ideally implement the whole MPRIS spec. :D

But in order for the scrobbler to work, adding support for the `Player` interface[1] and the DBUS signal `PropertiesChanged` on it should be enough. 

Of the Player properties that should be sent for the signal, `Player.Metadata` and `Player.PlaybackStatus` are needed. If your spotify library provides this information, I would like to see `Player.Position` which is used for some calculations if present. (The official spotify client doesn't provide it for example[2].)  

[1] https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html

[2] https://community.spotify.com/t5/Desktop-Linux/MPRIS-properties-Volume-and-Position-are-not-populated/m-p/1727179

**Comment by SimonPersson** [comment]
@mariusor - Thanks for the info. The `Player.Metadata` and `Player.PlaybackStatus` properties were already there. I just added the `Player.Position` property, along with the `mpris:length` field to the metadata. I'll figure out how to send the `PropertiesChanged` signal using the dbus library some other day, and then we should have working scrobbling!

**Comment by mariusor** [comment]
Hi @SimonPersson. Sorry to be pushy, but any news on implementing the `PropertiesChanged` signal? :D

I've looked over the code and unfortunately Rust is so foreign to me that I can't begin to contribute a patch. :(

**Comment by boonto** [comment]
Integration with [xfce4-pulseaudio-plugin](https://github.com/xfce-mirror/xfce4-pulseaudio-plugin) would be nice. However, I don't know on which side the changes would have to be made.

**Comment by Ayplow** [comment]
Its a shame to see this peter off. Any plans to return to it?

**Comment by SirWindfield** [comment]
Well, it's an open source project. People use their free time to work on the project. And it looks like no one has time to work on the project right now. Feel free to open a PR though if you want to work on it. Just tag it with [WIP] :smile: @Ayplow

**Comment by mariusor** [comment]
If I can make a suggestion for anyone interested in working on a PR, there's already similar functionality in [ncspot](https://github.com/hrkfdn/ncspot/blob/develop/src/mpris.rs#L402).

I have no idea clue about rust, or I would take a stab at it.

**Comment by SirWindfield** [comment]
Thanks @mariusor, there code is way cleaner than ours. I always wondered on how to clean our dbus code section up.

**Comment by SirWindfield** [comment]
See latest commits on the development branch.
