### ISSUE TITLE
Create binaries for aarch64 (eg. for Raspberry PI 4)

### ISSUE THREAD

**Issue by toabctl** [Spotifyd/spotifyd#613]
It's great that you already provide [prebuilt binaries](https://github.com/Spotifyd/spotifyd/releases) but binaries for ARM 64-bit (aarch64 or arm64) are missing. Would be cool to have those binaries.

**Comment by SirWindfield** [comment]
Duplicate of https://github.com/Spotifyd/spotifyd/issues/280
