### ISSUE TITLE
Implement Stop() method on MPRIS

### ISSUE THREAD

**Issue by jgabriel98** [Spotifyd/spotifyd#615]
Now days, when the Quit() method (from Mpris interface implementation) is called, the process is finished.

I think it would be better to Quit() only disconnect from the current connected "spotify client", and then keep running, becoming available for new connections.

I makes more sense, since only the player (and nothing more) is quitting, and the process/daemon keeps running because it is not a player, but a service/daemon that contains a player.

UPDATE: see the [next comment below](https://github.com/Spotifyd/spotifyd/issues/615#issuecomment-647194572)

**Comment by jgabriel98** [comment]
I did some reasearch about the players with mpris implemented.
In the end Quit() method is supposed to behave like it behaves now (ending the whole process).
And Stop() method is the one to "disconnect" the device from the player (like in [Shairport-sync](https://github.com/mikebrady/shairport-sync/issues/1028#issuecomment-647177346)).

so i will change this issue from "new behavior for MPRIS Quit() method" to implement Stop() method, since spotifyd currently implements Stop() by just calling Pause().

**Comment by SirWindfield** [comment]
Sounds like a good idea!
