### ISSUE TITLE
Using pass gives BadCredentials

### ISSUE THREAD

**Issue by Purgeme** [Spotifyd/spotifyd#617]
When using pass spotify for the password command, it returns an error.
spotifyd doesn't work without the --no-daemon for me.
Also, if I give the same password as normal text in the config file, it runs, no issues.

`Caught panic with message: Authentication failed with reason: BadCredentials`

**Versions :**
 - OS: Arch Linux x86_64
 - Spotifyd: 0.2.24
- cargo: 1.44.1

**Comment by maschhoff** [comment]
Hi,

if you use --verbose --no-daemon together it will work

Cheers

**Comment by maschhoff** [comment]
got the same problem with user credentials and with device credentials

**Comment by xdefrag** [comment]
Fix it by removing any other information from credential file.

From
```
<password>
user: <user>
```
To simple
```
<password>
```

Still an unpleasant bug.

**Comment by SirWindfield** [comment]
Could you explain this further? I am not familiar with pass @xdefrag :) Would make fixing it easier for me

**Comment by xdefrag** [comment]
@SirWindfield I guess spotifyd takes all input from pass and pass can contain metadata like user, email, notes etc, not only password.

**Comment by SirWindfield** [comment]
If that is the case, then users should just change their `password_cmd` to only return the password by piping it through other programs to only return the first line.
`password_cmd` does take everything it returns as the password, that would explain the bad credentials error :)

**Comment by xdefrag** [comment]
@SirWindfield Yeah, in that case it all makes sense. 

Other software for similar feature awaits call to pass and get only first line. I think from here we have misunderstanding.

**Comment by SirWindfield** [comment]
I'll close this then :) Thanks for helping and figuring this out!

**Comment by Solay07** [comment]
This not work when runing spotifyd as service.

I added `password_cmd = "pass show spotify.com/solay | head -n 1"` to config file, then run `systemctl --user start spotifyd`

**Logs**
<details><summary>Click to show logs</summary>

    Oct 22 16:51:43 spotifyd[79452]: Loading config from "/home/ernest/.config/spotifyd/spotifyd.conf"
    Oct 22 16:51:43 systemd[483]: Started A spotify playing daemon.
    Oct 22 16:51:43 systemd[483]: Stopped A spotify playing daemon.
    Oct 22 16:51:43 systemd[483]: spotifyd.service: Scheduled restart job, restart counter is at 15.
    Oct 22 16:51:31 systemd[483]: spotifyd.service: Failed with result 'exit-code'.
    Oct 22 16:51:31 systemd[483]: spotifyd.service: Main process exited, code=exited, status=101/n/a
    Oct 22 16:51:31 spotifyd[79099]: Caught panic with message: Authentication failed with reason: BadCredentials
    Oct 22 16:51:30 spotifyd[79099]: Connecting to AP "guc3-accesspoint-b-xbl8.ap.spotify.com:443"
    Oct 22 16:51:30 spotifyd[79099]: Using alsa volume controller.
    Oct 22 16:51:30 spotifyd[79099]: No proxy specified
    Oct 22 16:51:30 spotifyd[79099]: Running "pass show spotify.com/solay | head -n 1" using "/bin/bash"
    Oct 22 16:51:30 spotifyd[79099]: No password specified. Checking password_cmd
</details>

But if I run directly `spotifyd --no-daemon --config-path "path_to_config_file"` its works

**Versions**
- OS: Arch Linux with kernel 5.9.1
- Spotifyd: 0.2.24
