### ISSUE TITLE
GNOME MPRIS: No Metadata or old data shown

### ISSUE THREAD

**Issue by Maik1999** [Spotifyd/spotifyd#618]
**Description**

In GNOME there is no metadata or some old data like songs played many minutes ago shown.
As far as I noticed the old data mostly is the first song started(by spotify-tui). Also tried it with some GNOME MPRIS extensions but they show the same data.
I am using my own client id and playerctl shows correct data when I run it.
The play button does not show the right icon. But clicks on play, next and prev buttons are working fine.

**To Reproduce**

1. Start a song with spotify-tui (others should work too)
2. Check the GNOME notification panel
3. There is old data shown(maybe needs one song change) or not know artist and song

**Expected behavior**

It should show the actual playing song data.

**Compilation flags** 
Installed spotifyd-full from AUR (Manjaro)
- [x] dbus_mpris
- [x] dbus_keyring
- [x] alsa_backend
- [x] portaudio_backend
- [x] pulseaudio_backend
- [x] rodio_backend

**Versions (please complete the following information):**
 - OS: 5.4.44-1-MANJARO
 - Spotifyd: 0.2.24
- cargo: 1.44.0

**Comment by SirWindfield** [comment]
The MPRIS implementation is kind of a mess right now. Some stuff changed behind the scenes and I have to wait until `librespot` merges a PR to make changes and actually start fixing bugs.

**Comment by Maik1999** [comment]
Thanks for the answer.
Hope they merge it quickly.
By the way thanks for the awesome work. I really like spotifyd and use it daily.

**Comment by Maik1999** [comment]
I just investigated a bit and it seems that spotifyd does not trigger the _org.freedesktop.DBus.Properties.PropertiesChanged_ event when the track or playback status changes. Since GNOME does not pull metadata it does not update the song data in the notification area.

The official Spotify Client for example does trigger the event and GNOME updates the metadata. Also if you restart GNOME (run _r_ in Alt+F2 window) it does pull the metadata and shows the correct data from the time it was restarted.

**Comment by SirWindfield** [comment]
I think that there was a PR for this, not entirely sure though.

**Comment by Maik1999** [comment]
You are right. #575 does implement the event. I build the branch and it seems to update the play button and the title. Unfortunately it does not update the artist name as far as I can see it. Will post this in the PR too. I also tested it with the PR merged into the current master and got the same behaviour.

**Comment by fsevenm** [comment]
Was it merged? I use the latest version but can't see the song metadata in MPRIS gnome shell.
