### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by hobarrera** [Spotifyd/spotifyd#62]
Looks like this project doesn't include a licence.

My suggestion is usually [ISC](https://choosealicense.com/licenses/isc/), which is functionally equivalent to BSD/MIT, but avoids redundant language. But it's really a thing of preference, so feel free to ignore the suggestion if you already have a preference.

You should probably include a LICENCE file though, whichever your preference.

**Comment by SimonPersson** [comment]
Thanks, I meant to add it, but wanted to check all dependencies to see that they were compatible with the GPLv3 first. It's added now.
