### ISSUE TITLE
Spotifyd unable to open config file

### ISSUE THREAD

**Issue by chrfrancis** [Spotifyd/spotifyd#625]
**Description**
Trying to run spotifyd and it is unable to open the config file.

./spotifyd --config-path /home/pi/.config/spotifyd/spotifyd.config --no-daemon --verbose
Loading config from "/home/pi/.config/spotifyd/spotifyd.config"
Failed to open config file at "/home/pi/.config/spotifyd/spotifyd.config"
CliConfig { config_path: Some("/home/pi/.config/spotifyd/spotifyd.config"), no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: None, password: None, password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: None, bitrate: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None } }

I've tried both by setting the owner and group to pi/pi and root/root with the same outcome.

pi@raspberrypi:~/.config/spotifyd $ ls -la
total 12
drwxr-xr-x  2 pi   pi   4096 Jul  2 22:10 .
drwx------ 12 pi   pi   4096 Jul  3 15:07 ..
-rw-r--r--  1 root root  590 Jul  2 22:10 spotifyd.conf

**Comment by chrfrancis** [comment]
Here is the contents of my config file with the username and pw scrubbed

[global]
# Your Spotify account name.
username = 

# Your Spotify account password.
password = 

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = alsa

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 320

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 8888

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, tv,
# avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
device_type = computer

**Comment by SirWindfield** [comment]
You pass down `spotifyd.config` as the file name in the CLI command but `ls` lists the file as `spotify.conf`.

**Comment by chrfrancis** [comment]
Understood, just fixed that. now I receive the following. (I appreciate the help btw)

Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop MercuryManager
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
drop Dispatch
deregistering handle with poller

**Comment by SirWindfield** [comment]
You're running headless, meaning you don't have a window manager installed (probably RPi). The DBUS implementation won't work in this case and you have to compile without the `dbus_mpris` feature or use another pre-compiled version.

This will get fixed in v1.0

**Comment by chrfrancis** [comment]
Correct, I am using RPi. Is there a pre-compiled version you recommend?

**Comment by SirWindfield** [comment]
Depends on the audio backend you want. But IIRC the slim versions do not have MPRIS compiled into them.

You can try the command here: https://github.com/Spotifyd/spotifyd/issues/244#issuecomment-583881263
This starts the dbus correctly and worked in my instance.

**Comment by chrfrancis** [comment]
This is what happens now

pi@raspberrypi:~ $ dbus-run-session ./spotifyd --no-daemon
Loading config from "/home/pi/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Caught panic with message: called `Result::unwrap()` on an `Err` value: Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })


And when I run the original command...

pi@raspberrypi:~ $ sudo ./spotifyd --config-path /home/pi/.config/spotifyd/spotifyd.conf --no-daemon --verbose
Loading config from "/home/pi/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: Some("/home/pi/.config/spotifyd/spotifyd.conf"), no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: Some(Alsa), volume_controller: None, device: None, control: None, mixer: None, device_name: None, bitrate: Some(Bitrate320), volume_normalisation: false, normalisation_pregain: None, zeroconf_port: Some(8888), proxy: None } }
Found shell "/bin/bash" using SHELL environment variable.
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=4
registering with poller
Using software volume controller.
starting background reactor
Caught panic with message: called `Result::unwrap()` on an `Err` value: Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers

**Comment by SirWindfield** [comment]
You have something else running on port 8888 that you specified in your config. Maybe take a look at the output of `lsof -i:8888`. The only other port that is being used by the daemon is 443 which is the default ap_port.
