### ISSUE TITLE
build crashes at alsa-sys

### ISSUE THREAD

**Issue by HeinrichDerTote** [Spotifyd/spotifyd#632]
**Description**
When I try to compile Spotifyd on Windows 10, it crashes while compiling alsa-sys v0.1.2.

**To Reproduce**
1. run _git clone https://github.com/Spotifyd/spotifyd/_
2. go to spotifyd
3. run _cargo build --release_
4. See error: _error: failed to run custom build command for `alsa-sys v0.1.2`_

**Expected behavior**

It should not have ended with an error, I guess.

**Logs**
<details><summary>Click to show logs</summary>

  
### many "Compiling ..." lines ###

Compiling idna v0.1.5
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
process didn't exit successfully: `C:\Users\user\spotifyd\target\release\build\alsa-sys-6e499960604f54e7\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1
--- stderr
Package alsa was not found in the pkg-config search path.\r
Perhaps you should add the directory containing `alsa.pc\'\r
to the PKG_CONFIG_PATH environment variable\r
No package \'alsa\' found\r
"', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\alsa-sys-0.1.2\build.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions:**
 - OS: Windows 10
 - Spotifyd: v0.2.24
- cargo: 1.44.1

**Additional context**
The error pops up for me at the current version, v0.2.24, v0.2.23 and probably multiple more.
When running with --no-default-features it spits 14 errors more.
And I do not have any knowledge of rust and how I can set a global variabe for Rust.

**Comment by SirWindfield** [comment]
That's because spotifyd doesn't run on Windows (yet). ALSA is an audio library for linux.

**Comment by SirWindfield** [comment]
You can, however, check out this fork which has added Windows support on master:
https://github.com/JCapucho/spotifyd

I didn't test it myself or can provide any information on how to compile it properly. But a simple `cargo run --features rodio_backend --no-default-features` should work I think.

Here is the PR to include it in our repository: https://github.com/Spotifyd/spotifyd/pull/602

**Comment by HeinrichDerTote** [comment]
ok, thank you.

**Comment by SirWindfield** [comment]
You can run it inside of WSL (Windows Subsystem Linux) IIRC. I'd just use the rodio_backend for it. So running `cargo run --no-default-features --features rodio_backend` should work. Note that DBUS is not supported inside of WSL so you can't use MPRIS.

**Comment by kmccmk9** [comment]
Can confirm building/running with those flags does work under Windows 64 Bit.
