### ISSUE TITLE
Random crashes during song play back.

### ISSUE THREAD

**Issue by Jihakuz** [Spotifyd/spotifyd#643]
- spotifyd 0.2.24
- Linux arch 5.7.9-arch1-1
- pulseaudio backend

Log before crashing:

```
...
scheduling Read for: 1
received packet from V6([fe80::22bc:5a77:8857:eed7]:5353)
received packet from V6([fe80::22bc:5a77:8857:eed7]:5353) with no query
scheduling Read for: 2
scheduling Read for: 2
loop poll - 418.321µs
loop time - Instant { tv_sec: 1098, tv_nsec: 330338733 }
loop process, 33.533µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
Caught panic with message: connection closed
drop Dispatch
deregistering handle with poller
dropping I/O source: 5
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop AudioKeyManager
drop ChannelManager
drop MercuryManager
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
```

This will normally happen a few minutes into the first song, although I have seen it take longer.

**Comment by trmckay** [comment]
This is happening to me too. Exact same situation as @Jihakuz describes. Happens when running as a systemd service or when calling it directly. Usually crashes in the first minute or so.

- spotifyd 0.2.24
- Arch Linux
- 5.8.3-zen1-1-zen kernel

My config file:
```
[global]
username = ***
password = ***
device_name = spotifyd
device_type = computer
bitrate = 320
initial_volume = 100
volume_normalisation = true
normalisation_pregain = -10
backend = alsa
```

stdout:
```
loop poll - 20.982614ms
loop time - Instant { tv_sec: 4229, tv_nsec: 748476347 }
loop process, 5.871µs
loop poll - 731ns
loop time - Instant { tv_sec: 4229, tv_nsec: 748484402 }
loop process, 4.208µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
Caught panic with message: connection closed
drop Dispatch
deregistering handle with poller
dropping I/O source: 5
drop Spirc[0]
Shutting down player thread ...
drop Player[0]
drop Session[0]
drop AudioKeyManager
drop ChannelManager
drop MercuryManager
Dropping AMessageStream
AMessageStream telling ADriver to quit
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
dropping I/O source: 4
```

**Comment by istride** [comment]
I think I have experienced the same issue, in particular, I also receive the message `Caught panic with message: connection closed`. I use a VPN (NordVPN), and this issue seems to disappear if I do not use it. Incidentally, a similar disconnection issue occurs with the official Spotify client, and is the reason I've been trying out alternatives like spotifyd. Sadly, I've also found [evidence that Spotify does not officially support using their service through a VPN](https://community.spotify.com/t5/Desktop-Windows/Spotify-program-showing-as-offline-when-connected-to-vpn/td-p/4878869). Maybe it's time to consider alternatives to Spotify.

**Comment by trmckay** [comment]
I also use a VPN: Surfshark VPN over UDP to a server about 150 miles away, if that's relevant. I'll do some testing and see if the issue goes away without it.

**Comment by exciteabletom** [comment]
I can confirm that I no longer get this issue after switching off my VPN.

- Manjaro Linux (5.8.16)
- spotifyd 0.2.24
- NordVPN 3.8.5

**Comment by trmckay** [comment]
As far as I can tell my problem goes away as well. Is there maybe some work around by maybe making `spotifyd` use another network interface, rather than the tunnel opened by OpenVPN?

**Comment by exciteabletom** [comment]
After some testing, the order in which the programs are started makes a difference:

If I start my VPN **before** spotifyd; I get the same crash as described by @trmckay and @Jihakuz.

If I start my VPN **after** spotifyd: spotifyd stops being recognised as a Spotify connect device and audio stops. It makes no indication there was an error (as far as I can tell), and it is only recognised by Spotify connect again if i restart it. [Relevant stdout of `spotifyd --no-daemon --verbose`](https://pastebin.com/wkU4fV91)
