### ISSUE TITLE
Couldn't Initialize Logger

### ISSUE THREAD

**Issue by rouncewell** [Spotifyd/spotifyd#644]
**Description**
I'm trying to get spotifyd working so I can utilize Spotify-TUI which works fine. I just don't want to have the Spotify client open. 
I'm not quite sure what to do, and there is not much information on running this with other distributions. Any help would be appreciated. 
**Logs**
<details><summary>Click to show logs</summary>

spotifyd -b pulseaudio
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: None })), backtrace: None })', src/main.rs:40:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: 
 - Spotifyd: 
- cargo:

**Comment by SirWindfield** [comment]
Take a look at https://github.com/Spotifyd/spotifyd/issues/576 and see if this applies to you.
