### ISSUE TITLE
Builds fine but install errors

### ISSUE THREAD

**Issue by Rik-de-Kort** [Spotifyd/spotifyd#647]
**Description**
Trying to install spotifyd on Arch, cloned most recent source. Command I use to build:

`cargo build --release --no-default-features --features alsa_backend,dbus_keyring,dbus_mpris`

This is fine. However, when I then run 

`cargo install --path .`

Cargo starts recompiling, and errors out with the following error:

`error[E0063]: missing field `gapless` in initializer of `librespot_playback::config::PlayerConfig`

**Expected behavior**
I expect cargo to just install the compiled binary, or at the very least to compile an identical binary. I don't know how to configure `cargo install` because it doesn't accept `--no-default-features`.

This might be a cargo install "feature", [see here](https://doc.rust-lang.org/cargo/commands/cargo-install.html), but if so, I think it's important to update the manual in the README.

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Arch Linux
 - Spotifyd: 9981a14
- cargo: 1.45.0 (744bd1fbb 2020-06-15)

**Logs**
<details><summary>Click to show full error</summary>

````
[rik@rik spotifyd]$ cargo install --path .
  Installing spotifyd v0.2.24 (/home/rik/spotifyd)
    Updating crates.io index
   Compiling spotifyd v0.2.24 (/home/rik/spotifyd)
error[E0063]: missing field `gapless` in initializer of `librespot_playback::config::PlayerConfig`
   --> src/config.rs:732:24
    |
732 |         player_config: PlayerConfig {
    |                        ^^^^^^^^^^^^ missing `gapless`

error[E0027]: pattern does not mention fields `play_request_id`, `position_ms`
  --> src/process.rs:65:9
   |
65 |         PlayerEvent::Started { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing fields `play_request_id`, `position_ms`

error[E0027]: pattern does not mention field `play_request_id`
  --> src/process.rs:69:9
   |
69 |         PlayerEvent::Stopped { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing field `play_request_id`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0027, E0063.
For more information about an error, try `rustc --explain E0027`.
error: failed to compile `spotifyd v0.2.24 (/home/rik/spotifyd)`, intermediate artifacts can be found at `/home/rik/spotifyd/target`

Caused by:
  could not compile `spotifyd`.

To learn more, run the command again with --verbose.
````
</details>

**Comment by SirWindfield** [comment]
`cargo install --path . --locked`

**Comment by SirWindfield** [comment]
Could you create a PR and add the locked flag to the readme file?
