### ISSUE TITLE
Thread MAIN panicked at 'Couldn't Initialise Logger'

### ISSUE THREAD

**Issue by no-112** [Spotifyd/spotifyd#652]
Hi there. Just having a spot of trouble with getting spotifyd to work on FreeBSD. My system version is 12.1 stable, and the error along with RUST_BACKTRACE=full is as below.

```
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: Some(stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
) })), backtrace: Some(stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
) })', src/main.rs:40:26
stack backtrace:
   0:          0x16d1b6b - <unknown>
   1:          0x16fd80d - <unknown>
   2:          0x16b9c14 - <unknown>
   3:          0x16bd1e8 - <unknown>
   4:          0x16bceed - <unknown>
   5:          0x16bd857 - <unknown>
   6:          0x16bd44c - <unknown>
   7:          0x16fc630 - <unknown>
   8:          0x16fc6b6 - <unknown>
   9:          0x12a16c6 - <unknown>
  10:          0x127fff6 - <unknown>
  11:          0x16d876f - <unknown>
  12:          0x12a18fa - <unknown>
  13:          0x12700c2 - <unknown>
```

Not sure if its user error or not, but some help would be appreciated. Thank you for your time!

**Comment by no-112** [comment]
Edited to fix code block

**Comment by SirWindfield** [comment]
Check if you have a system logger installed. This is proabbly the reason why it fails. A lot of Void linux users had the same problem, because the distro doesn't ship with one pre-installed.

**Comment by no-112** [comment]
Okay, a little bit of playing and it gets past that with ` --no-daemon ` but now it is failing on "Address already in use".

**Comment by no-112** [comment]
@SirWindfield Figured that out, thank you! Right now I'm having issues with port allocation but I think I have it figured out. For now I'll close the issue. Thanks!

**Comment by JanzenJohn** [comment]
> Check if you have a system logger installed. This is proabbly the reason why it fails. A lot of Void linux users had the same problem, because the distro doesn't ship with one pre-installed.

What do you mean by system logger ?
I've searched for it and don't know what you mean.
