### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by jedi2610** [Spotifyd/spotifyd#655]
Compiling librespot v0.1.3
   Compiling spotifyd v0.2.24 (/home/jedi/src/spotifyd)
error[E0063]: missing field `gapless` in initializer of `librespot_playback::config::PlayerConfig`
   --> src/config.rs:732:24
    |
732 |         player_config: PlayerConfig {
    |                        ^^^^^^^^^^^^ missing `gapless`

error[E0560]: struct `librespot_core::config::ConnectConfig` has no field named `linear_volume`
   --> src/main_loop.rs:172:25
    |
172 |                         linear_volume: self.linear_volume,
    |                         ^^^^^^^^^^^^^ `librespot_core::config::ConnectConfig` does not have this field
    |
    = note: available fields are: `name`, `device_type`, `volume`, `volume_ctrl`, `autoplay`

error[E0027]: pattern does not mention fields `play_request_id`, `position_ms`
  --> src/process.rs:65:9
   |
65 |         PlayerEvent::Started { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing fields `play_request_id`, `position_ms`

error[E0027]: pattern does not mention field `play_request_id`
  --> src/process.rs:69:9
   |
69 |         PlayerEvent::Stopped { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing field `play_request_id`

error[E0560]: struct `librespot_core::config::ConnectConfig` has no field named `linear_volume`
  --> src/setup.rs:97:13
   |
97 |             linear_volume,
   |             ^^^^^^^^^^^^^ `librespot_core::config::ConnectConfig` does not have this field
   |
   = note: available fields are: `name`, `device_type`, `volume`, `volume_ctrl`, `autoplay`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0027, E0063, E0560.
For more information about an error, try `rustc --explain E0027`.
error: failed to compile `spotifyd v0.2.24 (/home/jedi/src/spotifyd)`, intermediate artifacts can be found at `/home/jedi/src/spotifyd/target`

Caused by:
  could not compile `spotifyd`.

To learn more, run the command again with --verbose.

i solved it by adding --locked to the command cargo install --path . --locked
but i'm not able to use pulseaudio as backend 
using alsa does not show my pc as a device in spt even while spotifyd in running.

**Comment by SirWindfield** [comment]
The readme should by now mention that you have to use `--locked` like you already discovered.
Does pulseaudio not produce any sound at all? Alsa is a whole beast in itself and it has almost always been a wrong configuration from the user side that it didn't work properly. Sadly, it's super hard to help out on that as audio setups differ a lot between OS and hardware as well.

If you have trouble with any of the backends you could always use `rodio` by compiling it yourself. That backend is afaik guaranteed to work on any system without any additional configuration. Take a look at the readme to see how to compile the binary yourself :)

I don't think that we currently provide binaries for linux that contain rodio. #610 has been merged today and some work is being done in #653. After that I will probably trigger a new build to generate new binaries. Those will actually contain all audio backends on all systems if you select the `all`-flavor binary :)

**Comment by jedi2610** [comment]
okay i'll give rodio a try. but i wanna try one last time.
can you check if my config is correct and spotifyd i detected on my phone but when i choose spotifyd i cannot hear any sound although it shows as the song is currently playing. a weird thing is that i set the device name to a different name but even then it shows up as spotifyd

i'm running Ubuntu 20.04 if that helps

![image](https://user-images.githubusercontent.com/30691152/89440979-13fbdd80-d76a-11ea-8bef-4346cee1d840.png)

**Comment by SirWindfield** [comment]
Looks right. You sure that you installed pulseaudio on your system? The other parameters (`mixer`) shouldn't be needed. You can remove it. But I doubt that that will make a difference :)

**Comment by jedi2610** [comment]
yeah i do have pulseaudio installed on my system

**Comment by SirWindfield** [comment]
Try to run `spotifyd --no-daemon --verbose`. Maybe more information is in there.

**Comment by jedi2610** [comment]
Here is the output:

![image](https://user-images.githubusercontent.com/30691152/89443609-21b36200-d76e-11ea-9be7-03d2bb494e81.png)

**Comment by SirWindfield** [comment]
Do you see the panic message? `Caught panic with message: unknown backend pulseaudio`. Pretty thje linux build is not available with pulseaudio. #610 fixed this but I didn't create new builds yet. 

If you run `spotifyd -h` you probably only get the alsa backend listed. You have to compile it yourself sadly. I should work with pulseaudio though. Just need to compile it with that.

**Comment by jedi2610** [comment]
yeah i do get alsa backend listed
and here is the output 
https://termbin.com/hx8m

it seems like there is a problem with the port or something
i even tried to run it with a different port number but the output is same

**Comment by SirWindfield** [comment]
You need to remove the proxy entry in the configuration file.

> Using proxy "http://proxy.example.org:8080/"
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }

**Comment by jedi2610** [comment]
man i'm so dumb i just now noticed that

**Comment by jedi2610** [comment]
any solutions?

**Comment by SirWindfield** [comment]
Good question. A lot of people had that problem. I had no time to investigate it though. You might be missing a syslog logger on your system, which causes this issue. The log should contain a line telling you that it failed to initialize logging. 
https://github.com/Spotifyd/spotifyd/issues/576

For now you just have to run it using `no-daemon` until I fix it :)

**Comment by jedi2610** [comment]
okay, alr cool. and one more thing every time i start spotifyd it sets the volume level to 94% which is annoying as i'm using earphones and it just blows my head out. is there a fix? and also i'm now able to control the playback using media control keys or playerctl or alsamixer even though i added the feature flags for media controls

**Comment by SirWindfield** [comment]
it depends on your environment if the media keys do indeed send commands through your running DBUS instance. You'd have to check yourself to see if they do and if not try to find a fix for it. There is not much I can do for you on that department.

Regarding the volume: It's a known issue and I remember merging a PR that fixes it but maybe it broke again (or my mind plays on me). I'll take a look.

**Comment by jedi2610** [comment]
alr cool thanks, i'll close this issue now

**Comment by jedi2610** [comment]
running the command from this [comment](https://github.com/Spotifyd/spotifyd/issues/211#issuecomment-524861935l) outputs:
qdbus: could not find a Qt installation of ''. do you think you can help me on that?

**Comment by SirWindfield** [comment]
Sorry, no clue on that one!

**Comment by jedi2610** [comment]
@SirWindfield  does the snap package version support playerctl and other stuff or does it just support alsa?

**Comment by SirWindfield** [comment]
Just alsa, it's broken though. I don't have rights to push to the registry :(
