### ISSUE TITLE
Channel error after playing first song

### ISSUE THREAD

**Issue by davidfstein** [Spotifyd/spotifyd#657]
**Description**
First off, thank you for making this, its awesome. I am using spotifyd with spotify-tui. When I load spotify-tui and play a song, it works well. However, usually by the second or third song, the audio will stop. Running with --no-daemon I see the following:
```
Loading config from ".config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Connecting to AP "guc3-accesspoint-b-99k2.ap.spotify.com:443"
Authenticated as "1229877582" !
Using alsa sink
Country: "US"
Loading <Stars> with Spotify URI <spotify:track:1MZLBTrZrVAcAnLjA3bbtb>
<Stars> loaded
Loading <He's The Moon> with Spotify URI <spotify:track:16y9EHfDv2ANmDzxrs4zQp>
channel error: 2 0
Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
```

**To Reproduce**

**Logs**
<details><summary>Click to show logs</summary>
oading config from ".config/spotifyd/spotifyd.conf"
CliConfig { config_path: Some(".config/spotifyd/spotifyd.conf"), no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: Some("shadowfax"), bitrate: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None } }
Found shell "/usr/bin/zsh" using SHELL environment variable.
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=8
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:33959
adding I/O source: 4194305
registering with poller
adding I/O source: 8388610
registering with poller
event Writable Token(4194305)
event Writable Token(8388610)
loop process - 2 events, 0.000s
adding I/O source: 12582915
registering with poller
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://apresolve.spotify.com/")
event Writable Token(12582915)
loop process - 1 events, 0.000s
consuming notification queue
resolving host="apresolve.spotify.com", port=80
scheduling Read for: 0
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 2
sending packet to V6([ff02::fb]:5353)
scheduling Read for: 3
loop poll - 544.938µs
loop time - Instant { tv_sec: 664, tv_nsec: 764210839 }
loop process, 29.814µs
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
received packet from V4(192.168.1.72:5353)
received packet from V4(192.168.1.72:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
received packet from V6([fe80::1225:2553:cfbf:fdfa]:5353)
received packet from V6([fe80::1225:2553:cfbf:fdfa]:5353) with no query
scheduling Read for: 2
scheduling Read for: 2
loop poll - 108.313µs
loop time - Instant { tv_sec: 664, tv_nsec: 764352174 }
loop process, 6.29µs
scheduling Read for: 1
scheduling Read for: 2
loop poll - 7.468µs
loop time - Instant { tv_sec: 664, tv_nsec: 764369082 }
loop process, 7.389µs
event Writable Token(4194305)
event Writable Token(8388610)
loop process - 2 events, 0.000s
loop poll - 29.693284ms
loop time - Instant { tv_sec: 664, tv_nsec: 794072689 }
loop process, 41.154µs
connecting to [2600:1901:0:524d::]:80
adding I/O source: 16777220
registering with poller
scheduling Write for: 4
event Writable Token(16777220)
loop process - 1 events, 0.000s
loop poll - 22.873275ms
loop time - Instant { tv_sec: 664, tv_nsec: 817196313 }
loop process, 37.588µs
read_keep_alive; is_mid_message=false
scheduling Read for: 4
should_keep_alive(version=Http11, header=None) = true
Client::encode has_body=false, method=None
reclaiming write buf Vec
flushed 47 bytes
flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 179.163µs
loop time - Instant { tv_sec: 664, tv_nsec: 817506144 }
loop process, 10.921µs
event Readable | Writable Token(16777220)
loop process - 1 events, 0.000s
Conn::read_head
read 648 bytes
Response.parse([Header; 100], [u8; 648])
Response.parse Complete(230)
maybe_literal not found, copying "Via"
parsed 7 headers (230 bytes)
incoming body is content-length (418 bytes)
expecting_continue(version=Http11, header=None) = false
should_keep_alive(version=Http11, header=None) = true
Conn::read_body
decode; state=Length(418)
flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 47.068035ms
loop time - Instant { tv_sec: 664, tv_nsec: 864591032 }
loop process, 17.292µs
Conn::read_body
decode; state=Length(0)
incoming body completed
scheduling Read for: 4
maybe_notify; read_from_io blocked
read_keep_alive; is_mid_message=false
scheduling Read for: 4
signal: Want
flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
wants_read_again? false
poll_want: taker wants!
pool dropped, dropping pooled ("http://apresolve.spotify.com")
loop poll - 138.945µs
loop time - Instant { tv_sec: 664, tv_nsec: 864842524 }
loop process, 24.616µs
Connecting to AP "guc3-accesspoint-b-bknf.ap.spotify.com:443"
adding I/O source: 20971525
registering with poller
scheduling Write for: 5
read_keep_alive; is_mid_message=false
scheduling Read for: 4
client tx closed
State::close_read()
State::close_write()
flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 4
signal: Closed
loop poll - 198.593µs
loop time - Instant { tv_sec: 664, tv_nsec: 896358368 }
loop process, 26.598µs
event Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 41.772928ms
loop time - Instant { tv_sec: 664, tv_nsec: 938169893 }
loop process, 32.352µs
scheduling Read for: 5
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 295.731812ms
loop time - Instant { tv_sec: 665, tv_nsec: 253105488 }
loop process, 30.833µs
flushing framed transport
writing; remaining=135
framed transport flushed
scheduling Read for: 5
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 156.568049ms
loop time - Instant { tv_sec: 665, tv_nsec: 418291931 }
loop process, 30.338µs
attempting to decode a frame
frame decoded from buffer
Authenticated as "1229877582" !
new Session[0]
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
new Player[0]
Using alsa sink
new Spirc[0]
new MercuryManager
input volume:65535 to mixer: 65535
attempting to decode a frame
frame decoded from buffer
Session[0] strong=3 weak=2
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
Country: "US"
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
writing; remaining=414
framed transport flushed
loop poll - 338.382µs
loop time - Instant { tv_sec: 665, tv_nsec: 419177290 }
loop process, 17.271µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 41.471031ms
loop time - Instant { tv_sec: 665, tv_nsec: 460672175 }
loop process, 21.975µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 37.901346ms
loop time - Instant { tv_sec: 665, tv_nsec: 498607922 }
loop process, 22.915µs
subscribed uri=hm://remote/user/1229877582/ count=0
loop poll - 3.883µs
loop time - Instant { tv_sec: 665, tv_nsec: 498678598 }
loop process, 10.427µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 29.469112766s
loop time - Instant { tv_sec: 694, tv_nsec: 967806385 }
loop process, 19.945µs
kMessageTypePause "" webapi-3e0d5d8e981d45b48e42d60595430eb3 1836439216 1597416759444
scheduling Read for: 5
flushing framed transport
writing; remaining=346
framed transport flushed
loop poll - 86.718µs
loop time - Instant { tv_sec: 694, tv_nsec: 968089359 }
loop process, 11.566µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 58.934472ms
loop time - Instant { tv_sec: 695, tv_nsec: 27040861 }
loop process, 23.455µs
loop poll - 3.598µs
loop time - Instant { tv_sec: 695, tv_nsec: 27098997 }
loop process, 12.596µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
unknown subscription uri=hm://collection/collection/1229877582
attempting to decode a frame
frame decoded from buffer
unknown subscription uri=hm://collection/collection/1229877582/json
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 3.468682822s
loop time - Instant { tv_sec: 698, tv_nsec: 495799028 }
loop process, 23.162µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 3.235641637s
loop time - Instant { tv_sec: 701, tv_nsec: 731477079 }
loop process, 19.767µs
kMessageTypePause "" webapi-3e0d5d8e981d45b48e42d60595430eb3 1836445980 1597416789005
scheduling Read for: 5
flushing framed transport
writing; remaining=346
framed transport flushed
loop poll - 103.727µs
loop time - Instant { tv_sec: 701, tv_nsec: 731736631 }
loop process, 16.555µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 52.698142ms
loop time - Instant { tv_sec: 701, tv_nsec: 784460793 }
loop process, 22.369µs
loop poll - 3.524µs
loop time - Instant { tv_sec: 701, tv_nsec: 784518839 }
loop process, 16.703µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 6.878630429s
loop time - Instant { tv_sec: 708, tv_nsec: 663173978 }
loop process, 13.842µs
kMessageTypePause "" webapi-3e0d5d8e981d45b48e42d60595430eb3 1836452901 1597416795765
scheduling Read for: 5
flushing framed transport
writing; remaining=346
framed transport flushed
loop poll - 84.251µs
loop time - Instant { tv_sec: 708, tv_nsec: 663429594 }
loop process, 11.398µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 47.672698ms
loop time - Instant { tv_sec: 708, tv_nsec: 711122315 }
loop process, 29.961µs
loop poll - 3.516µs
loop time - Instant { tv_sec: 708, tv_nsec: 711191940 }
loop process, 12.968µs
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
received packet from V4(192.168.1.144:5353)
scheduling Read for: 1
scheduling Read for: 1
received packet from V6([fe80::1cf0:3406:d5cc:dec3]:5353)
scheduling Read for: 2
scheduling Read for: 2
loop poll - 6.776270624s
loop time - Instant { tv_sec: 715, tv_nsec: 487480085 }
loop process, 8.622µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 514.799156ms
loop time - Instant { tv_sec: 716, tv_nsec: 2291526 }
loop process, 26.519µs
kMessageTypeLoad "" webapi-3e0d5d8e981d45b48e42d60595430eb3 1836460108 1597416802690
State: context_uri: "spotify:playlist:37i9dQZF1E39647s669QL1" index: 10 position_ms: 0 status: kPlayStatusPlay position_measured_at: 1597416809896 context_description: "Daily Mix 1" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 10 track {gid: "\202w=\024]%I\324\271s\353B.7\331\221"} track {gid: "v\373/\376g\223F)\256\323\274\025\336\345M|"} track {gid: "\317va/p.D\311\270\263B\273\212\326En"} track {gid: "\335\333\312g\0340Os\235G\260\024\326\241K\322"} track {gid: "vg\304\344\363\340Ir\2434\nK\275\224OR"} track {gid: "\220\204A\343\026~I)\253\305\277g\217\355\344\250"} track {gid: "\320\365u\005\326\007A\177\210\323L\3612)\302\001"} track {gid: "Ue*\330\273\227F=\227\0379)\330\310\336'"} track {gid: "n\266[\310<\226DA\254\374Q\243\3019C\021"} track {gid: "v\363G|\004\206A3\261-f \346\241\342\025"} track {gid: "\336U$\233\347\226M\366\272\353*\013\030\244\030#"} track {gid: "_Wic\234k@\360\240\372\325Q\367q\336y"} track {gid: "\206\026\312y\303\023G\304\264*>$;I\340\344"} track {gid: "\234\327\202\272\332\227D\272\275\200`\370\233\2167\377"} track {gid: "\376-\260\373\226\327N\254\270;?\222\300,\312\273"} track {gid: "Jw\3575\226,F)\234\230\360VO\017\236A"} track {gid: "\371\230I5JtMV\217\202\337\235\342\347\024m"} track {gid: "\221G\350-\307\031C{\222uj\305\020>x\362"} track {gid: "\363\306\355\263D$KJ\274\306\024r\010g\235\037"} track {gid: "\261 /\232\270eB*\202\314\324Q\364\336\rR"} track {gid: ":\322\207\362\260\276C9\241#\363\212\227S\234\325"} track {gid: "$T\030\223\036\374D \261\306\340\027 \231\226="} track {gid: "iB\304\306\341\302F\314\231\020,9\331O X"} track {gid: "w+B\326\022\371A\326\275\326\006X\354\021D<"} track {gid: "\"(\360kY\217F\367\200.\210U\222\0303w"} track {gid: "\362\177\314\374\327\342G3\250\017\344.\370\321\330?"} track {gid: "OD;\223\034\000F\021\231\213\006\3446\377\306`"} track {gid: "%\204=a\232kA\371\206\253<\034Tj#?"}
Frame has 28 tracks
Loading context: <spotify:playlist:37i9dQZF1E39647s669QL1> index: [10] of 28
command=Load(SpotifyId { id: 295530702816010449619437882355168319523, audio_type: Track }, true, 0)
scheduling Read for: 5
flushing framed transport
writing; remaining=1086
framed transport flushed
loop poll - 121.825µs
loop time - Instant { tv_sec: 716, tv_nsec: 8895622 }
loop process, 19.658µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 47.399081ms
loop time - Instant { tv_sec: 716, tv_nsec: 56323744 }
loop process, 28.762µs
Loading <Motion Sickness> with Spotify URI <spotify:track:6LxcPUqx6noURdA5qc4BAT>
new AudioKeyManager
Downloading file d84847203f003b3722c77312449e21835ae8f627
requesting chunk 0
new ChannelManager
scheduling Read for: 5
flushing framed transport
writing; remaining=102
framed transport flushed
loop poll - 290.127µs
loop time - Instant { tv_sec: 716, tv_nsec: 56658222 }
loop process, 15.232µs
consuming notification queue
loop poll - 23.313µs
loop time - Instant { tv_sec: 716, tv_nsec: 56703273 }
loop process, 14.812µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 40.672246ms
loop time - Instant { tv_sec: 716, tv_nsec: 97398105 }
loop process, 24.712µs
loop poll - 3.522µs
loop time - Instant { tv_sec: 716, tv_nsec: 97461284 }
loop process, 15.685µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
loop poll - 76.038384ms
loop time - Instant { tv_sec: 716, tv_nsec: 173522694 }
loop process, 20.847µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 5
flushing framed transport
framed transport flushed
channel error: 2 0
loop poll - 159.454872ms
loop time - Instant { tv_sec: 716, tv_nsec: 333008434 }
loop process, 56.689µs
Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
loop poll - 8.845µs
loop time - Instant { tv_sec: 716, tv_nsec: 333088323 }
loop process, 20µs
drop Player[0]
loop poll - 136.626µs
loop time - Instant { tv_sec: 716, tv_nsec: 333254893 }
loop process, 16.965µs
loop poll - 2.133µs
loop time - Instant { tv_sec: 716, tv_nsec: 333304159 }
loop process, 22.241µs
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
scheduling Read for: 1
received packet from V6([fe80::1cf0:3406:d5cc:dec3]:5353)
scheduling Read for: 2
scheduling Read for: 2
loop poll - 178.39062ms
loop time - Instant { tv_sec: 716, tv_nsec: 511726923 }
loop process, 19.491µs
event Readable | Writable Token(4194305)
event Readable | Writable Token(8388610)
loop process - 2 events, 0.000s
received packet from V4(192.168.1.144:5353)
scheduling Read for: 1
scheduling Read for: 1
received packet from V6([fe80::1cf0:3406:d5cc:dec3]:5353)
scheduling Read for: 2
scheduling Read for: 2
loop poll - 3.072071087s
loop time - Instant { tv_sec: 719, tv_nsec: 583830953 }
loop process, 24.054µs

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Arch 5.4.57-1-lts
 - Spotifyd: 0.2.24
- cargo: 1.45.1

**Comment by wolfgangwalther** [comment]
Exact same error here. Sometimes it's before the first song is even played, sometimes it crashes in the middle of a song and sometimes after quite a few. The only thing that's reproducible so far is, that it **will** happen at some point :/

**Comment by masonpawsey** [comment]
Same error here too.

```
channel error: 2 0
Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
Player thread panicked!
```

I saw some issues with short (~30 second) songs, but I'm getting some rather nondiscriminatory crashes

**Comment by Semmu** [comment]
Hi folks,

I have the same issue and in my case it is always with specific songs, such as
- Gnarls Barkley - Crazy ( https://open.spotify.com/track/1vxw6aYJls2oq3gW0DujAo?si=6Rx3KGdiQeK97NLDCZmqHw )
- Szymon - Golden ( https://open.spotify.com/track/1yYoPm5wj4KQFJ68NR5hUM?si=6J916RgcSa69-RrCpkS_Sg )
- Joep Beving - The Gift ( https://open.spotify.com/track/0PCduL4v5QEEKqeRUv7TEC?si=qaBS4WEXSsK50mrEcvVWfg )

I am using spotifyd version 0.2.24 and did not touch anything software related in a long while, but these songs became buggy suddenly. Maybe Spotify re-coded them and they can't be processed now somehow?
My exact logs are these:
```
Aug 17 17:28:30 saraswati spotifyd[25913]: Loading <Golden> with Spotify URI <spotify:track:1yYoPm5wj4KQFJ68NR5hUM>
Aug 17 17:28:30 saraswati spotifyd[25913]: channel error: 2 0
Aug 17 17:28:30 saraswati spotifyd[25913]: Caught panic with message: called `Result::unwrap()` on an `Err` value: ChannelError
```

I would love if this could be fixed, nowadays I have to restart the service manually many times a day :disappointed: (actually I thought about hooking up the shell command to a smart-home physical button :joy: )

Thanks for your work!

**Comment by terinjokes** [comment]
It looks like users of librespot who aren't using spotifyd are reporting the same issue as of the weekend: https://github.com/librespot-org/librespot/issues/519.

**Comment by davidfstein** [comment]
That thread does not bode well for our chances of seeing this fixed anytime soon. For those looking for a quick workaround, I switched to the pulseaudio backend. It seems to run into the channel errors less often

**Comment by wolfgangwalther** [comment]
I have been using pulseaudio from the start, so I doubt that would actually help.

**Comment by masonpawsey** [comment]
[Looks like this issue has been fixed from Spotify's side](https://github.com/librespot-org/librespot/issues/519#issuecomment-678092129)
