### ISSUE TITLE
No sound when running as a service on RaspberryPi

### ISSUE THREAD

**Issue by guillaumedavidphd** [Spotifyd/spotifyd#658]
**Description**
When I run `spotifyd` from the command line, everything works as intended. When I set it up as a service using the provided `spotifyd.service`, there is no sound. `systemctl --user status spotifyd.service` shows the service running without any error messages.

**To Reproduce**
1. Run `spotifyd --no-daemon` from the command line
2. Use the Spotify app to connect to the Pi's `spotifyd`
3. Play music.
4. Kill the process and run `systemctl --user start spotifyd.service`
5. Check that everything started correctly with `systemctl --user status spotifyd.service`
6. Use the Spotify app to connect to the Pi's `spotifyd`
7. No sound!

**Expected behavior**
I'm expecting the service to run similarly to what I'm doing from the command line, and so I'm expecting either sound or at least an error message.

**Logs**
<details><summary>Click to show logs</summary>

Aug 14 10:50:28 raspberrypi systemd[367]: spotifyd.service: Succeeded.
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Loading config from "/home/pi/.config/spotifyd.conf"
Aug 14 10:50:29 raspberrypi spotifyd[4173]: CliConfig { config_path: Some("/home/pi/.config/spotifyd.conf"), no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: Some("Spotberry"), bitrate: None, initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: None } }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Found user shell: Some("/bin/bash")
Aug 14 10:50:29 raspberrypi spotifyd[4173]: No proxy specified
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: build; num-workers=1
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Using software volume controller.
Aug 14 10:50:29 raspberrypi spotifyd[4173]: starting background reactor
Aug 14 10:50:29 raspberrypi spotifyd[4173]: adding I/O source: 0
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Zeroconf server listening on 0.0.0.0:41149
Aug 14 10:50:29 raspberrypi spotifyd[4173]: adding I/O source: 4194305
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Writable Token(4194305)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: adding I/O source: 8388610
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Writable Token(8388610)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: adding I/O source: 12582915
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Writable Token(12582915)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: park; waiting for idle connection: "http://apresolve.spotify.com"
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Http::connect("http://apresolve.spotify.com/")
Aug 14 10:50:29 raspberrypi spotifyd[4173]: consuming notification queue
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 0
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 1
Aug 14 10:50:29 raspberrypi spotifyd[4173]: sending packet to V4(224.0.0.251:5353)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Readable | Writable Token(4194305)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: resolving host="apresolve.spotify.com", port=80
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 2
Aug 14 10:50:29 raspberrypi spotifyd[4173]: sending packet to V6([ff02::fb]:5353)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Readable | Writable Token(8388610)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 3
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 31.235141ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 254585884 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 82.998µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V4(192.168.0.115:5353)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V4(192.168.0.115:5353) with no query
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V4(192.168.0.115:5353)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V4(192.168.0.115:5353) with no query
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 1
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V6([fe80::d5af:4555:2a1b:f74c]:5353)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V6([fe80::d5af:4555:2a1b:f74c]:5353) with no query
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V6([fe80::d5af:4555:2a1b:f74c]:5353)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: received packet from V6([fe80::d5af:4555:2a1b:f74c]:5353) with no query
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 2
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 856.976µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 255574857 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 77.998µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 19.457464ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 275157318 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 126.997µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: connecting to 34.98.74.57:80
Aug 14 10:50:29 raspberrypi spotifyd[4173]: adding I/O source: 16777220
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Write for: 4
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Writable Token(16777220)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 11.61468ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 287857969 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 93.997µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: read_keep_alive; is_mid_message=false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 4
Aug 14 10:50:29 raspberrypi spotifyd[4173]: should_keep_alive(version=Http11, header=None) = true
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Client::encode has_body=false, method=None
Aug 14 10:50:29 raspberrypi spotifyd[4173]: reclaiming write buf Vec
Aug 14 10:50:29 raspberrypi spotifyd[4173]: flushed 47 bytes
Aug 14 10:50:29 raspberrypi spotifyd[4173]: flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: wants_read_again? false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 835.977µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 289156933 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 83.998µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Readable | Writable Token(16777220)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Conn::read_head
Aug 14 10:50:29 raspberrypi spotifyd[4173]: read 648 bytes
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Response.parse([Header; 100], [u8; 648])
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Response.parse Complete(230)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: maybe_literal not found, copying "Via"
Aug 14 10:50:29 raspberrypi spotifyd[4173]: parsed 7 headers (230 bytes)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: incoming body is content-length (418 bytes)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: expecting_continue(version=Http11, header=None) = false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: should_keep_alive(version=Http11, header=None) = true
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Conn::read_body
Aug 14 10:50:29 raspberrypi spotifyd[4173]: decode; state=Length(418)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: wants_read_again? false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 164.891464ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 454181394 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 80.998µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Conn::read_body
Aug 14 10:50:29 raspberrypi spotifyd[4173]: decode; state=Length(0)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: incoming body completed
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 4
Aug 14 10:50:29 raspberrypi spotifyd[4173]: maybe_notify; read_from_io blocked
Aug 14 10:50:29 raspberrypi spotifyd[4173]: read_keep_alive; is_mid_message=false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 4
Aug 14 10:50:29 raspberrypi spotifyd[4173]: signal: Want
Aug 14 10:50:29 raspberrypi spotifyd[4173]: flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: wants_read_again? false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: poll_want: taker wants!
Aug 14 10:50:29 raspberrypi spotifyd[4173]: pool dropped, dropping pooled ("http://apresolve.spotify.com")
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 679.981µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 456892319 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 85.998µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: Connecting to AP "guc3-accesspoint-b-mgp2.ap.spotify.com:443"
Aug 14 10:50:29 raspberrypi spotifyd[4173]: adding I/O source: 20971525
Aug 14 10:50:29 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Write for: 5
Aug 14 10:50:29 raspberrypi spotifyd[4173]: read_keep_alive; is_mid_message=false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 4
Aug 14 10:50:29 raspberrypi spotifyd[4173]: client tx closed
Aug 14 10:50:29 raspberrypi spotifyd[4173]: State::close_read()
Aug 14 10:50:29 raspberrypi spotifyd[4173]: State::close_write()
Aug 14 10:50:29 raspberrypi spotifyd[4173]: flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: wants_read_again? false
Aug 14 10:50:29 raspberrypi spotifyd[4173]: shut down IO
Aug 14 10:50:29 raspberrypi spotifyd[4173]: deregistering handle with poller
Aug 14 10:50:29 raspberrypi spotifyd[4173]: dropping I/O source: 4
Aug 14 10:50:29 raspberrypi spotifyd[4173]: signal: Closed
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 1.236966ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 480675665 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 91.998µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Writable Token(20971525)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 48.910655ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 529730316 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 91.997µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:29 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process - 1 events, 0.002s
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop poll - 51.381587ms
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2715, tv_nsec: 763613883 }
Aug 14 10:50:29 raspberrypi spotifyd[4173]: loop process, 94.997µs
Aug 14 10:50:29 raspberrypi spotifyd[4173]: flushing framed transport
Aug 14 10:50:29 raspberrypi spotifyd[4173]: writing; remaining=144
Aug 14 10:50:29 raspberrypi spotifyd[4173]: framed transport flushed
Aug 14 10:50:29 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 174.295216ms
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 103820535 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 88.997µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Authenticated as "gdvisuals" !
Aug 14 10:50:30 raspberrypi spotifyd[4173]: new Session[0]
Aug 14 10:50:30 raspberrypi spotifyd[4173]: new Spirc[0]
Aug 14 10:50:30 raspberrypi spotifyd[4173]: new MercuryManager
Aug 14 10:50:30 raspberrypi spotifyd[4173]: input volume:65535 to mixer: 65535
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Session[0] strong=4 weak=2
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Country: "US"
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:30 raspberrypi spotifyd[4173]: flushing framed transport
Aug 14 10:50:30 raspberrypi spotifyd[4173]: writing; remaining=850
Aug 14 10:50:30 raspberrypi spotifyd[4173]: framed transport flushed
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 1.557958ms
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 113781262 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 88.997µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: new Player[0]
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Using alsa sink
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:30 raspberrypi spotifyd[4173]: flushing framed transport
Aug 14 10:50:30 raspberrypi spotifyd[4173]: framed transport flushed
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 52.031572ms
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 165948830 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 81.998µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:30 raspberrypi spotifyd[4173]: flushing framed transport
Aug 14 10:50:30 raspberrypi spotifyd[4173]: framed transport flushed
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 1.958946ms
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 168040773 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 78.998µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: subscribed uri=hm://remote/user/gdvisuals/ count=0
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 30.999µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 168390763 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 81.998µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:30 raspberrypi spotifyd[4173]: flushing framed transport
Aug 14 10:50:30 raspberrypi spotifyd[4173]: framed transport flushed
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 44.747772ms
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 213259532 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 83.998µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Modify_watch: Watch { fd: 14, read: true, write: false }, poll_now: false
Aug 14 10:50:30 raspberrypi spotifyd[4173]: adding I/O source: 25165828
Aug 14 10:50:30 raspberrypi spotifyd[4173]: registering with poller
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Dropping AConnection
Aug 14 10:50:30 raspberrypi spotifyd[4173]: scheduling Read for: 4
Aug 14 10:50:30 raspberrypi spotifyd[4173]: D-Bus i/o poll ready: 14 is NotReady
Aug 14 10:50:30 raspberrypi spotifyd[4173]: handle_msgs: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 490.986µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 229588084 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 86.998µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: event Readable | Writable Token(20971525)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process - 1 events, 0.000s
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: frame decoded from buffer
Aug 14 10:50:30 raspberrypi spotifyd[4173]: attempting to decode a frame
Aug 14 10:50:30 raspberrypi spotifyd[4173]: scheduling Read for: 5
Aug 14 10:50:30 raspberrypi spotifyd[4173]: flushing framed transport
Aug 14 10:50:30 raspberrypi spotifyd[4173]: framed transport flushed
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 28.78921ms
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 258510291 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 84.998µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Polling message stream
Aug 14 10:50:30 raspberrypi spotifyd[4173]: msgstream found Ok(Ready(Some((Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired")))))
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Polling message stream
Aug 14 10:50:30 raspberrypi spotifyd[4173]: msgstream found Ok(Ready(Some((Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired")))))
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Aug 14 10:50:30 raspberrypi spotifyd[4173]: Polling message stream
Aug 14 10:50:30 raspberrypi spotifyd[4173]: msgstream found Ok(NotReady)
Aug 14 10:50:30 raspberrypi spotifyd[4173]: kMessageTypeNotify "Web Player (Firefox)" c41cb379ae5cb5ab7cfe6fc5c7a3f8f99d123bf8 1847080449 1597427430170
Aug 14 10:50:30 raspberrypi spotifyd[4173]: kMessageTypeNotify "Bedroom + 1" 2626ebc796a7656d84a95d0da1f4a3b9914d3e4a 1847080449 1597427430170
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop poll - 37.999µs
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop time - Instant { tv_sec: 2716, tv_nsec: 259824255 }
Aug 14 10:50:30 raspberrypi spotifyd[4173]: loop process, 86.998µs

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster) kernel 5.4.51+
 - Spotifyd: 0.2.24
- cargo: 1.45.1 (f242df6ed 2020-07-22)

**Comment by guillaumedavidphd** [comment]
No takers?

**Comment by slondr** [comment]
@guillaumedavidphd Can you confirm that this is still a problem on v0.3.0? We haven't pushed any changes that I would expect to fix this, but I'd like to double-check before trying to solve the issue

**Comment by guillaumedavidphd** [comment]
I'll check and will follow up.

**Comment by 1uk4smusic** [comment]
> @guillaumedavidphd Can you confirm that this is still a problem on v0.3.0? We haven't pushed any changes that I would expect to fix this, but I'd like to double-check before trying to solve the issue

I just started with Spotifyd and this error also occurs for me

I can connect to my raspberry pi (running spotifyd 3.2.0) and play a song, it also shows me in the journalctl, that it loaded the song, but there`s no sound. If i start spotifyd manually it works fine...

**Comment by MisterMorgan** [comment]
I have absolutely the same issue, that in the Version 0.3.4 when spotifyd is running as a service ther is no sound.
Will this problem be fixed?
