### ISSUE TITLE
Problem with compilation, config.rs, Cache, expected 2 parameters

### ISSUE THREAD

**Issue by gkurdej** [Spotifyd/spotifyd#66]
Hi,

I have problem with spotifyd compilation. I receive error as below. 

```
Compiling spotifyd v0.1.0 (file:///home/kodi/Pobrane/spotifyd-master)
error[E0061]: this function takes 2 parameters but 1 parameter was supplied
   --> src/config.rs:128:43
    |
128 |             .and_then(|p| Some(Cache::new(p)))
    |                                           ^ expected 2 parameters

```
rustc 1.18.0 (03fc9d622 2017-06-06)
cargo 0.19.0 (28d1d60d4 2017-05-16)
ubuntu 17.04

Wrong version of compiler or library? 
I have no idea, how to deal with it :(

**Comment by SimonPersson** [comment]
I've pushed a commit that solves this. Thanks for reporting!
