### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by flokli** [Spotifyd/spotifyd#67]
Can you start tagging some sommits, so `git describe --tags` is able to produce a version number?

Even if it's just `v0.0.1`, it would simplify packaging a lot.

Thanks for working on spotifyd! :tada:

**Comment by SimonPersson** [comment]
Sure, I just pushed a `v0.1`.

Thanks for pointing out the need for tags for packaging, I didn't think of it. Which distro are you looking to package it for?

**Comment by flokli** [comment]
Sure! Today I started helping Varakh in packaging [spotifyd for Archlinux (AUR)](https://aur.archlinux.org/packages/spotifyd/).
I changed the PKGBUILD to use the git versioning scheme just now.
