### ISSUE TITLE
initial_volume don't work as expected

### ISSUE THREAD

**Issue by dPeS** [Spotifyd/spotifyd#679]
**Description**
When I put initial_volume in conf it is >always< 100 on android app when starting playing music

It seems that config value is not read properly -> pls check attached log

**To Reproduce**
input config:

[global]
initial_volume = 30
volume_controller = softvol
device_name = salon
bitrate = 320

run cmd:
 /usr/local/bin/spotifyd --verbose --on-song-change-hook /home/pi/song-change-hook.sh --config-path /etc/spotifyd.conf --no-daemon

**Expected behavior**
not 100% on start

**Logs**

Sep 20 11:10:48 airpi spotifyd[1375]: Loading config from "/etc/spotifyd.conf"
Sep 20 11:10:48 airpi spotifyd[1375]: CliConfig { config_path: Some("/etc/spotifyd.conf"), no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: None, password: None, password_cmd: None, use_keyring: false, on_song_change_hook: Some("/home/pi/song-change-hook.sh"), cache_path: None, no-audio-cache: false, backend: None, volume_controller: Some(SoftVolume), device: None, control: None, mixer: None, device_name: Some("salon"), bitrate: Some(Bitrate320), volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None } }

**Versions (please complete the following information):**

/usr/local/bin/spotifyd --version
spotifyd 0.2.24

**Additional context**

in one place that variable is u16 int in other it's a string - maybe that is a clue

**Comment by CherryMan** [comment]
The last release (v0.2.24) was back in January, while `initial_volume` was shipped in July (probably due for a release), so if you didn't build `spotifyd` from source it's possible that the feature isn't included. Try building the project from source if you didn't.

**Comment by dPeS** [comment]
@CherryMan oh! I will retest asap then and put info here, thanks!
