### ISSUE TITLE
InvalidEnumValue(12)

### ISSUE THREAD

**Issue by uweschmitt** [Spotifyd/spotifyd#68]
I use `v0.1`.  When I try to connect to  `spotifyd` is get:

```
08:43:59 [INFO] Request::new: addr=192.168.0.248:59014, "POST / HTTP/1.1"
08:44:00 [INFO] Response::new "HTTP/1.1 200 OK"
08:44:00 [INFO] Connecting to AP "lon3-accesspoint-a39.ap.spotify.com:4070"
08:44:00 [INFO] Authenticated as "fostex666" !
08:44:00 [INFO] Using alsa sink
08:44:00 [INFO] Country: "DE"
08:44:01 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value:WireError(InvalidEnumValue(12))
```

**Comment by mistralol** [comment]
Also started seeing this issue today. Was working fine yesterday using most recent version of the arm "spotifyd-2017-07-02-armv7.zip"

Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [INFO] Response::new "HTTP/1.1 200 OK"
Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [INFO] Connecting to AP "lon3-accesspoint-a54.ap.spotify.com:4070"
Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [INFO] Authenticated as "xxxxxxxxx" !
Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [INFO] Using alsa sink
Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [INFO] Country: "GB"
Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: WireError(Invali
Jul 09 20:40:13 amp spotifyd[5057]: 20:40:13 [INFO] Request::new: addr=10.172.0.77:40542, "GET /?action=getInfo HTTP/1.1"
Jul 09 20:40:14 amp spotifyd[5057]: 20:40:14 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"

**Comment by boxofrox** [comment]
FYI, I found both `InvalidEnumValue(12)` and `InvalidEnumValue(13)` in my logs.  Assuming they're related.

**Comment by boxofrox** [comment]
Looks like a fix was applied in plietar/librespot#213.  Just need to figure out how to rebuild `spotifyd` against the latest librespot master branch.  Maybe `cargo update` is in order to update the `Cargo.lock`?

**Comment by SimonPersson** [comment]
Yes, `cargo update` and `cargo build --release` should update librespot. Try it out, if it works I'll push a fix.

**Comment by boxofrox** [comment]
`cargo update` worked.  Initial testing is positive.  Can play, pause, stop, track forward and backward, and adjust volume without issue.  `InvalidEnumValue` doesn't appear in the logs anymore.

**Comment by SimonPersson** [comment]
Thanks for verifying that. I've pushed an update.
