### ISSUE TITLE
Spotifyd as system service

### ISSUE THREAD

**Issue by chmod750** [Spotifyd/spotifyd#681]
**Description**
Spotifyd as a service can be used only as user service which means logged session.

**To Reproduce**
https://github.com/Spotifyd/spotifyd/wiki/Installing-on-a-Raspberry-Pi
These steps work but it is a user service and not a system one.
Any definition through /usr/lib/systemd/system/spotify.service cannot be used. Error message: Failed to get D-Bus connection.

**Expected behavior**
Being able to automatically execute spotify as a service without being logged.

**Versions (please complete the following information):**

- OS: Raspbian 5.4.51-v7l+
- Spotifyd: 0.2.24

**Comment by Intruder66** [comment]
For me, configuring /etc/systemd/system/spotifyd.service with
```
[Service]
ExecStart=/home/pi/.cargo/bin/spotifyd --no-daemon
Restart=always
RestartSec=12
```
and then executing
`sudo systemctl start spotifyd.service`
and
`sudo systemctl enable spotifyd.service`
makes spotifyd run as a service without me having to log on to the system. Or is this not what you meant?

**Comment by jbg** [comment]
I have a similar problem. Using the alsa backend and running a systemd service with --no-daemon as above, spotifyd panics on startup when trying to connect to the dbus session bus. Why is it trying to connect to dbus?

```
Caught panic with message: Failed to initialize DBus connection: D-Bus error: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead (org.freedesktop.DBus.Error.NotSupported)
```

**Comment by DAT4** [comment]
I have exactly the same error as jbg on a raspberry pi. I followed the tutorial on how to install spotifyd on a raspberry pi, but I set up the service file in /etc/systemd/system/ instead of /etc/systemd/user (idk if it makes a diffeence.)

**Comment by jbg** [comment]
Yes, it definitely makes a difference. It needs to be a user service so that it runs in your session and can access the session DBus. I have no idea *why* it needs DBus, but it works fine as a user service.

**Comment by DAT4** [comment]
Okay, I just ran it as a service in my `.config/systemd/` folder and with the `systemctl --user start` command, and I get exactly the same log except that it is loading the config file from the user instead of the root.

**Comment by robinvd** [comment]
@jbg dbus is used for play/pauze integration, and for the keyring.

@jbg  @DAT4 how did you install the binary? if you compile without dbus support the error should go away.

**Comment by jbg** [comment]
@robinvd Arch Linux package. It works fine as a systemd user service for me on "out-of-the-box" Arch, maybe @DAT4 doesn't have a session dbus for whatever reason.

It would probably be better if it could still start up when compiled with dbus support but no dbus is available.

**Comment by DAT4** [comment]
@robinvd I firstly installed it with `snap` on **raspbian** but I couldn't find out where by binary was installed and I think I didn't get anything to work with that.

So then I installed it by downloading the **ArmHF Full 0.2.24** [from the releases page](https://github.com/Spotifyd/spotifyd/releases) and I just moved it directly into `/usr/bin`.

**Comment by robinvd** [comment]
@jbg yeah that would be much better, i see there is actually a TODO comment at that error https://github.com/Spotifyd/spotifyd/blob/5db64d0a62f76a2814bd0b29d7ebc4c4a3e9c53c/src/dbus_mpris.rs#L160

in the meanwhile compiling from source without dbus would fix that

**Comment by takov751** [comment]
To solve this problem I created a pull request , where I recommend to create a restricted system user which only has access to its own small directory and audio and the systemd service runs as the user[](https://github.com/Spotifyd/spotifyd/pull/721)
Tested on a raspberry pi2b , using it for days did not lost connection not even once

**Comment by doragasu** [comment]
I have also this problem on a RPi4, with the package installed from the official repos. Starting as normal user works, but starting as system user causes the daemon to panic because of the DBus problem. I have also tried running the system unit as a restricted user with access to audio group without success.

Could it be possible to reopen this issue?

**Comment by doragasu** [comment]
OK, got it to work. In case it is useful for somebody, these are the steps I followed (on a RPi4 running ArchlinuxArm):

1. Create an unprivileged spotifyd user:
```bash
# useradd -r -s /usr/bin/nologin spotifyd
```
2. Add the user to the audio group:
```bash
# usermod -aG audio spotifyd
```
3. Put your config file in `/etc/spotifyd.conf` and make it readable only by spotifyd user (or better use a more secure way of setting your credentials):
```bash
# chown spotifyd:spotifyd /etc/spotifyd.conf
# chmod 400 /etc/spotifyd.conf
```
4. Put the following unit file in `/etc/systemd/system/spotifyd.service`:
```
[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
User=spotifyd
Group=spotifyd
ExecStart=/usr/bin/dbus-launch /usr/bin/spotifyd --no-daemon
Restart=always
RestartSec=12

[Install]
WantedBy=default.target
```
5. Reload systemd daemon, start and enable the system service:
```bash
# systemctl daemon-reload
# systemctl start spotifyd
# systemctl enable spotifyd
```
The daemon should be running nicely and start with your system. Additionally it will run as the unprivileged `spotifyd` user for improved security.
