### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by mainrs** [Spotifyd/spotifyd#682]
I've been maintaining the crate for some time now. Sadly, I do not have a lot of time left to even review PRs. I spent most of my time that I dedicate to programming on university projects and open source libraries that I happen to use in them. That doesn't leave the time needed to properly review/merge and publish new versions of Spotifyd.

I hope there are some people with Rust knowledge that would be willing to help me out and keep the project up and running. It doesn't (and shouldn't!) be a single person as it is a lot of work. I'd prefer 3+ people. That way, PRs can be properly discussed if the need arises and there will always be one person who can (peer-)review PRs.

If someone is interested, just comment on this issue!

**Comment by Plecra** [comment]
#602 certainly looks interesting to me! I'll have to find time to read through the code and see if I'm equipped to help here 😁

**Comment by marcelbuesing** [comment]
I would be willing to try.

**Comment by Ben-PH** [comment]
I'm keen.

**Comment by MarinPostma** [comment]
I'm interested

**Comment by kmilewczyk** [comment]
I would love to

**Comment by slondr** [comment]
I'm willing to help out somewhat, if you'd like more people involved.

**Comment by SimonPersson** [comment]
Super happy to see that so many has shown an interest in contributing! As @SirWindfield said, none of us have been able to dedicate the time that this project needs/deserves for some time now.

How do we proceed, practically? Should we just add everyone who has shown an interest here to the organisation?

**Comment by SirWindfield** [comment]
The only two options I have in my mind are these:

1) Create a new team and add everybody as a member to it. Basically forming some kind of "core" team. Maybe even setting up master as a protected branch so reviews need to happen before merging can be done.
2) Those that have interest can start to review and comment on PRs that are ready to be merged. maybe even resolving issues. I'd push the merge button then and we decide later on who we add depending on their activity for example.

If we set up the branch as protected I'd just go for option 1. We have enough people that showed interest which would result in enough review candidates.

**Comment by SimonPersson** [comment]
@SirWindfield - option 1 sounds fine to me. Will you set it up?

**Comment by SirWindfield** [comment]
Will do so today!

**Comment by SirWindfield** [comment]
@Plecra
@marcelbuesing
@Ben-PH
@MarinPostma
@kmilewczyk
@slondr
@rrichardson

I've added you all to the @Spotifyd/maintainers team.

**Comment by MarinPostma** [comment]
How do we communicate with each other?

**Comment by SirWindfield** [comment]
I've created a backup branch `backup_before_maintainers` that contains a snapshot of the current repository. No one should have push access to it except for administrators if I set it up correctly. If something goes horribly wrong we can use that to revert it (just in case).

Communication can be done inside the team view: https://github.com/orgs/Spotifyd/teams/maintainers. You should see a box where you can start a discussion :)

**Comment by SirWindfield** [comment]
I will keep the issue open for some more days, maybe we're able to find some more people that want to get involved :) Thanks for helping me out :3

**Comment by al-jshen** [comment]
Hi, I'd like to help out! :)

**Comment by Ben-PH** [comment]
I'm getting a 404 when I click through to it.

**Comment by notashutosh** [comment]
I'd like to help!

**Comment by SimonPersson** [comment]
@al-jshen and @notashutosh - I've sent you invites to the team.

@Ben-PH - what link is not working for you?

**Comment by JojiiOfficial** [comment]
I'd like to contribute as well.

**Comment by robinvd** [comment]
Would love to help! I use this project for hours a day as well.

**Comment by SirWindfield** [comment]
Sure thing! Just for later reference, if you are one of those individuals that wants to contribute to the project your't need to be in the maintaining team to do so. Resolving issues, maybe asking for the progress on ones that have already been started and peer-reviewing PRs (commenting or starting a discussion on the implementation details) can also be done without push access.

Maintainers are mostly responsible for merging and reviews, as well as other meta stuff. Some will probably also try and implement bug fixes or new features. But the size of the projects results in a lot of new issues, duplicate issues that have to be filtered, or even simple support questions that you guys will be responsible to resolve.

They're more of the puppeteers who setup the stage properly :)
That being said, I think a core team of 7 is good enough for the being. 3 requests are pending, so it would be a total of 10 members. @JojiiOfficial and @robinvd would probably be the last persons I'd add to the team. I feel that more would actually negatively impact development.

**Comment by Ben-PH** [comment]
@SimonPersson  got it working

**Comment by filalex77** [comment]
I want to help too!
