### ISSUE TITLE
System service with Pulseaudio backend - Could not start audio: Connection refused

### ISSUE THREAD

**Issue by deenigewouter** [Spotifyd/spotifyd#685]
**Description**

I compiled and installed the binary on Raspbian with the Pulseaudio backend. Running spotifyd --backend pulseaudio from the terminal works like a charm. When I set spotifyd up as service however, with the included service file in 'contrib' and copying the binary to /usr/bin, I get the following message whenever I specify --backend pulseaudio in the service config: 'Could not start audio: Connection refused'. The same happens when I run run it with root privileges. Specifying a user in the service config doesn't fix the issue.

**To Reproduce**
1. Create a service file with the following in it:

```
[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
User=patch
ExecStart=/usr/bin/spotifyd --backend pulseaudio --no-daemon --device-name test
Restart=always
RestartSec=12

[Install]
WantedBy=default.target
```
2. Enable the service with sudo systemctl enable spotifyd.service
3. Reboot or do sudo systemctl start spotifyd.service

**Expected behavior**

I expected the service to run like the binary does when running it from the command line without Pulseaudio refusing the connection. I suspect the service is run as root instead of patch, causing Pulseaudio to refuse the audio stream.

**Logs**
<details><summary>Click to show logs</summary>

Log of the service with the --verbose flag:

```
● woutspot.service - A spotify playing daemon
   Loaded: loaded (/etc/systemd/system/woutspot.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-09-30 12:36:10 BST; 46s ago
     Docs: https://github.com/Spotifyd/spotifyd
 Main PID: 1601 (spotifyd)
    Tasks: 3 (limit: 4915)
   Memory: 5.0M
   CGroup: /system.slice/woutspot.service
           └─1601 /usr/bin/spotifyd --verbose --backend pulseaudio --no-daemon --device-name test

Sep 30 12:36:57 patchbox spotifyd[1601]: flushing framed transport
Sep 30 12:36:57 patchbox spotifyd[1601]: writing; remaining=53
Sep 30 12:36:57 patchbox spotifyd[1601]: framed transport flushed
Sep 30 12:36:57 patchbox spotifyd[1601]: received packet from V4(192.168.1.47:5353)
Sep 30 12:36:57 patchbox spotifyd[1601]: scheduling Read for: 1
Sep 30 12:36:57 patchbox spotifyd[1601]: sending packet to V4(224.0.0.251:5353)
Sep 30 12:36:57 patchbox spotifyd[1601]: event Readable | Writable Token(4194305)
Sep 30 12:36:57 patchbox spotifyd[1601]: loop process - 1 events, 0.000s
Sep 30 12:36:57 patchbox spotifyd[1601]: scheduling Read for: 2
Sep 30 12:36:57 patchbox spotifyd[1601]: loop poll - 771.522µs
Sep 30 12:36:57 patchbox spotifyd[1601]: loop time - Instant { tv_sec: 1190, tv_nsec: 504136290 }
Sep 30 12:36:57 patchbox spotifyd[1601]: loop process, 22.907µs
```
Log of the service without the --verbose flag:

```
● woutspot.service - A spotify playing daemon
   Loaded: loaded (/etc/systemd/system/woutspot.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-09-30 12:32:05 BST; 12s ago
     Docs: https://github.com/Spotifyd/spotifyd
 Main PID: 1469 (spotifyd)
    Tasks: 3 (limit: 4915)
   Memory: 7.7M
   CGroup: /system.slice/woutspot.service
           └─1469 /usr/bin/spotifyd --backend pulseaudio --no-daemon --device-name test

Sep 30 12:32:05 patchbox spotifyd[1469]: No proxy specified
Sep 30 12:32:05 patchbox spotifyd[1469]: Using software volume controller.
Sep 30 12:32:10 patchbox spotifyd[1469]: Connecting to AP "gew1-accesspoint-b-2lfd.ap.spotify.com:443"
Sep 30 12:32:10 patchbox spotifyd[1469]: Authenticated as "deenigewouter" !
Sep 30 12:32:10 patchbox spotifyd[1469]: Country: "NL"
Sep 30 12:32:10 patchbox spotifyd[1469]: Loading <Singing Winds, Crying Beasts> with Spotify URI <spotify:track:0vBCQeiEKRy6eJmrf5zz4H>
Sep 30 12:32:10 patchbox spotifyd[1469]: <Singing Winds, Crying Beasts> loaded
Sep 30 12:32:11 patchbox spotifyd[1469]: Could not start audio: Connection refused
Sep 30 12:32:11 patchbox spotifyd[1469]: Could not start audio: Connection refused
Sep 30 12:32:16 patchbox spotifyd[1469]: Could not start audio: Connection refused
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Raspbian 10 (buster)"
- Spotifyd: 0.2.24
- cargo: cargo 1.46.0

I'm using the device as an audio fx processor, which uses Jack. Any program that uses Pulse gets automatically routed to Jacks output. Thats why I'm using Pulse instead of the alsa backend.

**Comment by jbg** [comment]
> I suspect the service is run as root instead of patch, causing Pulseaudio to refuse the audio stream.

Absent a serious bug in systemd, this will not be the case with the systemd unit you pasted.

Does a systemd user unit work? (get rid of the `User=` line, put the file in `/etc/systemd/user` or `~/.config/systemd/user`, enable with `systemctl --user enable spotifyd` and start it with `systemctl --user start spotifyd`).

I suspect the issue might be the pulseaudio socket path being different for a system unit due to the default value of `RuntimeDirectory` for system units.
