### ISSUE TITLE
Songs played don't show up in "Recently Played"

### ISSUE THREAD

**Issue by Jake-Gillberg** [Spotifyd/spotifyd#687]
**Description**
Songs played using spotify-tui and spotifyd don't show up in "recently played" playlist.

Unsure if this is a spotifyd or spotify-tui problem.

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
- OS: nixos-20.09
- Spotifyd: 0.2.24
- cargo: idk, built using the default nixpkg in nixos-unstable

**Comment by Jake-Gillberg** [comment]
https://github.com/Rigellute/spotify-tui/issues/602

**Comment by Jake-Gillberg** [comment]
Ah, just found out that the issue stems from librespot. https://github.com/librespot-org/librespot/issues/342

**Comment by robinvd** [comment]
Thanks for finding the cause! Then we will have to wait for that issue.

**Comment by Jake-Gillberg** [comment]
Sounds good. Closing the issue here.
