### ISSUE TITLE
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by stuart12** [Spotifyd/spotifyd#69]
spotifyd crashes every few days with the following messages. I'm running spotifyd with --verbose. Is there a way to get even more debug?

> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 4359732 }
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 8311 }
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413020, tv_nsec: 719785147 }
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: event Ready {Readable} Token(1)
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 123690 }
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: scheduling direction for: 0
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: kMessageTypeNotify "47spots" 47spots 486 1499670821962
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 6635 }
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413020, tv_nsec: 720290662 }
> Jul 10 09:13:42 hpmini110 Spotifyd[17281]: loop process - 0 events, Duration { secs: 0, nanos: 489102 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 42, nanos: 90133371 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 810955040 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: event Ready {Readable | Writable} Token(12)
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: notifying a task handle
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 259532 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 23885 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 811284902 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: event Ready {Readable} Token(9)
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: attempting to decode a frame
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: frame decoded from buffer
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: Session[0] strong=2 weak=6
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: attempting to decode a frame
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: flushing framed transport
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: writing; remaining=11
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: framed transport flushed
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 1117259 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 9638 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 812477869 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: event Ready {Readable} Token(9)
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: flushing framed transport
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: framed transport flushed
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 426035 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 7333 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 812970184 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 0 events, Duration { secs: 0, nanos: 101829 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 51410864 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 864540776 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: event Ready {Readable | Writable} Token(12)
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: notifying a task handle
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 186129 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 17390 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 864779076 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: event Ready {Readable} Token(9)
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: attempting to decode a frame
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: frame decoded from buffer
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: attempting to decode a frame
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: flushing framed transport
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: framed transport flushed
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 380917 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 4889 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413062, tv_nsec: 865200292 }
> Jul 10 09:14:24 hpmini110 Spotifyd[17281]: loop process - 0 events, Duration { secs: 0, nanos: 55175 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 2, nanos: 917364511 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413065, tv_nsec: 782648473 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: event Ready {Readable | Writable} Token(12)
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: notifying a task handle
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 305209 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 28844 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413065, tv_nsec: 783046641 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: event Ready {Readable} Token(9)
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: attempting to decode a frame
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: frame decoded from buffer
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: attempting to decode a frame
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: scheduling direction for: 5
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: flushing framed transport
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: framed transport flushed
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 852349 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop poll - Duration { secs: 0, nanos: 9848 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop time - Instant { tv_sec: 5413065, tv_nsec: 783971765 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: event Ready {Readable} Token(1)
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: loop process - 1 events, Duration { secs: 0, nanos: 273221 }
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: consuming notification queue
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: scheduling direction for: 0
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: kMessageTypePause "Xperia Z3 Tablet Compact Wifi" 2a930d0ca96580788381dd0c6497b2422c0ac11c 3 0
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop Spirc[0]
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop Session[0]
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop AudioKeyManager
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop AudioFileManager
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop ChannelManager
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop MercuryManager
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop MetadataManager
> Jul 10 09:14:27 hpmini110 Spotifyd[17281]: drop Dispatch
> Jul 10 09:14:27 hpmini110 systemd[1]: spotifyd@homeassistant.service: Main process exited, code=exited, status=101/n/a
> Jul 10 09:14:27 hpmini110 systemd[1]: spotifyd@homeassistant.service: Unit entered failed state.
> Jul 10 09:14:27 hpmini110 systemd[1]: spotifyd@homeassistant.service: Failed with result 'exit-code'.
>

**Comment by uweschmitt** [comment]
Looks like the already resolved issue https://github.com/Spotifyd/spotifyd/issues/68

**Comment by stuart12** [comment]
thanks, yes, Spotifyd works now.
