### ISSUE TITLE
Spotifyd login problem

### ISSUE THREAD

**Issue by TechieAndroid** [Spotifyd/spotifyd#690]
Sorry I normally fill out a bug report properly but it's late at night for me and I'm really tired plus I don't think this problem warrants a report. If it's not easily fixable the I'll document every detail.

spotifyd 0.2.24 from community repo in Arch
spotify-tui from AUR

I've tried to get spotifyd to actually output information using the --verbose flag but that does nothing for me (literally outputs nothing at all).

Now I'm not 100% sure this is the issue but I believe that the config file isn't using the username and password I've given it. I've tried wrapping the UN and PS in quotations and also tried substituting my UN for my email.

I feel like whatever syntax it's looking for, I'm probably not using it. Please clear up this in the readme or at least the config file.

Do you use the email for the UN field or the UN on the profile, do you need to wrap the UN and PS in quotations?

Anyways back to my problem.
I don't believe spotifyd is running properly because spotify-tui doesn't show my device in the list of devices even though I specifically set it in the spotifyd config.

**Comment by robinvd** [comment]
Does it work correctly when stating the username/password details from the command line?

**Comment by TechieAndroid** [comment]
No unfortunately it does not. I tried both methods while also trying UN/Email combinations.

Maybe it won't work because I'm on a family plan.

**Comment by merit-schelcj** [comment]
Also running into bad credentials issue with a family plan.

**Comment by JojiiOfficial** [comment]
I'm on family plan and for me it works.

**Comment by robinvd** [comment]
Im also on a family plan, so i dont think thats the issue

**Comment by schelcj** [comment]
I tried the user/pass on the command line and it worked, so I went back to the config and removed the quotes from these two values and it's working now.

**Comment by TechieAndroid** [comment]
Here's what happens when I try to use the command line to start spotifyd.

$spotifyd -u username -p password -d arch-laptop
```
error: The argument '--password <string>' requires a value but none was supplied

USAGE:
    spotifyd --device-name <string> --password <string> --username <string>

For more information try --help
```

**Comment by JojiiOfficial** [comment]
@TechieAndroid Try to surround the password with double quotes.

**Comment by TechieAndroid** [comment]
> @TechieAndroid Try to surround the password with double quotes.

That's what I did in the beginning, I don't get any output. I know this is a deamon but c'mon surely there's a way to know it the program is working, right?

**Comment by JojiiOfficial** [comment]
Did you pass `--no-daemon` when you tested the `--verbose` option?

**Comment by TechieAndroid** [comment]
I've never used the --no-daemon flag. And --verbose doesn't output anything either.

Do I need both flags to get a verbose output?

**Comment by JojiiOfficial** [comment]
Yes you do. Try everything you did before together with `--no-daemon`.

**Comment by TechieAndroid** [comment]
> Yes you do. Try everything you did before together with `--no-daemon`.

Thanks for helping me with that.

Okay so now I know exactly what's causing my problem, it's a panic that gets triggered by bad credentials and causes the program to quit.

`Caught panic with message: Authentication failed with reason: BadCredentials`

The thing is, I know I'm using the right credentials I literally just tested them and they work. On top of that I have it saved in google and rechecked to make sure I typed it correctly and I did, plus I haven't changed my password or username since I signed up on spotify so I know they're correct.

Which leads me back to the conclusion that it must be due to being on a family plan. Maybe if I was the admin of the plan it would work, I don't know.

**Comment by JojiiOfficial** [comment]
I'm not the admin of our family plan and yet it still works for me. I assume you have some special characters in your password which lead to a bad input. Be sure you escape them. If this is not the reason, try to change the password to a 'simple' one which only contains words and numbers.

**Comment by TechieAndroid** [comment]
Okay so that only escape character I know of is \ and it's not working. Do you know what one spoifyd needs? I thought it would be using the bash escape character since I'm running it from the terminal.

Here's what I've tried: `$spotifyd -u "username" -p "pas\$word" -d "arch" --no-daemon --verbose`

**Comment by JojiiOfficial** [comment]
I was talking about the bash escape character. Try echoing the password and check if its escaped correctly. If you get the right echo output, it should not be an escaping problem.

**Comment by TechieAndroid** [comment]
> I was talking about the bash escape character. Try echoing the password and check if its escaped correctly. If you get the right echo output, it should not be an escaping problem.

Good point. I echoed it and it came out fine with the \ added.

I guess I can try changing to simpler password but at this point I feel like it's gotta be something else.

**Comment by JojiiOfficial** [comment]
If the output was fine and you passed the pw to spotifyd the same way you did to echo, then I'm pretty sure its not the password. I just logged in into the spotify web interface and searced for options which could disallow such apps but I didn't found any. Maybe the family plan admin can give such rights?

**Comment by TechieAndroid** [comment]
Yeah, I don't know. I just checked on our master account and it looked exactly the same as my account. It's interesting to note that the app's sections are independent of each user on the plan so that would affect it, I know because I have spotify tui allowed on mine (and it works) but nobody else is using it on their accounts.

Maybe spotifyd needs app api access to spotify the same way spotify tui does?

**Comment by JojiiOfficial** [comment]
Spotifyd and Spotify-tui use the same api (rspotify). Spotifyd uses v0.8.0 and spotify-tui v0.10.0. I haven't looked at the changelog but maybe simply try to compile it with v0.10.0. I don't think it'll change that much but its worth giving it a try.

**Comment by mtorromeo** [comment]
I'm having the same issue with the Arch Linux package of the tagged 0.2.24 release (which is using an even older version of rspotify than 0.8) but running a build from the latest master's commit, with no changes, works fine, so whatever the issue was it's now fixed.

Maybe it's time for a new release?

**Comment by J-Cake** [comment]
> Here's what happens when I try to use the command line to start spotifyd.
> 
> $spotifyd -u username -p password -d arch-laptop
> 
> ```
> error: The argument '--password <string>' requires a value but none was supplied
> 
> USAGE:
>     spotifyd --device-name <string> --password <string> --username <string>
> 
> For more information try --help
> ```

This worked for me. I had the configuration file saved at the home directory (`~/.config/spotifyd/spotifyd.conf`) with the correct credentials etc. I ran the program with `--no-daemon` and got the panic. I then ran the daemon with the credentials in the command line `$ spotifyd -u <email> -p <password> --no-daemon` and it worked. It also worked without the `--no-daemon` after I tried it. So, thanks for the help

**Comment by robinvd** [comment]
@mtorromeo it definitly is! https://github.com/Spotifyd/spotifyd/pull/716

**Comment by TechieAndroid** [comment]
I'm still getting the same BadCredentials error. Is there any progress on this being fixed?

**Comment by J-Cake** [comment]
Have you tried with the CLI args?

**Comment by TechieAndroid** [comment]
> Have you tried with the CLI args?

Is that different than what I've been doing?

spotifyd _username_ _password_ _devicename_

**Comment by robinvd** [comment]
I think the syntax is `spotifyd -u someusername -p somepass`

**Comment by TechieAndroid** [comment]
> I think the syntax is `spotifyd -u someusername -p somepass`

Yeah that's what I've been doing but, as I said already I still get the badcredentials error.

**Comment by slondr** [comment]
@TechieAndroid Does the problem still exist on v0.3.0? Try specifying in the config file using the new TOML format.

**Comment by TechieAndroid** [comment]
> @TechieAndroid Does the problem still exist on v0.3.0? Try specifying in the config file using the new TOML format.

Why would the config file be different? Does it parse the config differently than the cli args?
Here's the output:

```
Loading config from "/home/recompiler/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom,lume"] } }', src/config.rs:477:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
using spotifyd v0.3.0

**Comment by slondr** [comment]
My hunch was that the quoted-string TOML format would mask any issues with password content, but it seems I was wrong. What's the full backtrace with `RUST_BACKTRACE=1`?

**Comment by TechieAndroid** [comment]
> My hunch was that the quoted-string TOML format would mask any issues with password content, but it seems I was wrong. What's the full backtrace with `RUST_BACKTRACE=1`?

Actually, RUST_BACKTRACE=1 wasn't enough, I had to do RUST_BACKTRACE=full.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: Some(71), col: 17, at: Some(2222), message: "invalid type: integer `90`, expected a string", key: ["global", "initial_volume"] } }', src/config.rs:477:67
stack backtrace:
   0:     0x55d9cade1180 - <unknown>
   1:     0x55d9cae0919c - <unknown>
   2:     0x55d9cadd9467 - <unknown>
   3:     0x55d9cade3880 - <unknown>
   4:     0x55d9cade35cc - <unknown>
   5:     0x55d9cade3ee3 - <unknown>
   6:     0x55d9cade3ab9 - <unknown>
   7:     0x55d9cade160c - <unknown>
   8:     0x55d9cade3a79 - <unknown>
   9:     0x55d9cae06d61 - <unknown>
  10:     0x55d9cae06b83 - <unknown>
  11:     0x55d9ca7909a3 - <unknown>
  12:     0x55d9ca77b6da - <unknown>
  13:     0x55d9ca77d113 - <unknown>
  14:     0x55d9ca75d759 - <unknown>
  15:     0x55d9cade43b1 - <unknown>
  16:     0x55d9ca77be32 - main
  17:     0x7fb9414d4152 - __libc_start_main
  18:     0x55d9ca7170ee - <unknown>
  19:                0x0 - <unknown>
```

**Comment by JojiiOfficial** [comment]
@TechieAndroid could you paste your config (with your credentials being redacted)?

**Comment by TechieAndroid** [comment]
> @TechieAndroid could you paste your config (with your credentials being redacted)?

```
[global]
# Your Spotify account name.
username = ""

# Your Spotify account password.
password = ""

# A command that gets executed and can be used to
# retrieve your password.
# The command should return the password on stdout.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
password_cmd = "command_that_writes_password_to_stdout"

# If set to true, `spotifyd` tries to look up your
# password in the system's password storage.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
use_keyring = true

#
# If set to true, `spotifyd` tries to bind to the session dbus
# and expose MPRIS controls. When running headless, without a dbus session,
# then set this to false to avoid binding errors
#
use_mpris = true

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "alsa"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
device = "alsa_audio_device"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
control = "alsa_audio_device"  # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS

# A command that gets executed in your shell after each song changes.
on_song_change_hook = "command_to_run_on_playback_events"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = ""

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 160

# The directory used to cache audio data. This setting can save
# a lot of bandwidth when activated, as it will avoid re-downloading
# audio files when replaying them.
#
# Note: The file path does not get expanded. Environment variables and
# shell placeholders like $HOME or ~ don't work!
cache_path = "cache_directory"

# If set to true, audio data does NOT get cached.
no_audio_cache = true

# Volume on startup between 0 and 100
initial_volume = 90

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 1234

# The proxy `spotifyd` will use to connect to spotify.
proxy = "http://proxy.example.org:8080"

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, tv,
# avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
device_type = "speaker"
```

**Comment by robinvd** [comment]
ah i see in code `initial_volume` is a `String` but the readme says just `90`

**Comment by JojiiOfficial** [comment]
Yes. Also you have to comment out or replace the proxy. Otherwise you will get another error.

**Comment by robinvd** [comment]
yea i think that was missed in the pr to TOML

**Comment by JojiiOfficial** [comment]
I created #778 which aims to fix it.

**Comment by TechieAndroid** [comment]
> ah i see in code `initial_volume` is a `String` but the readme says just `90`

I copied it directly from here: https://github.com/Spotifyd/spotifyd

**Comment by JojiiOfficial** [comment]
Yep thats right. We missed this one out when upgrading to the new config format. Also the proxy is set wrong. Maybe we should comment configurations out, which will break the functionality by holding the default value. This'll probably fix issues for people who copy-paste the whole config and don't look at any value.

**Comment by Aimmig** [comment]
Currently it seems like some "special characters" in the password field are not well behaving. Somehow those special characters are interpreted as escape chars. Changing the password isn't a big deal, so just as a note if anybody is wondering about "unknown  escape char" errors ....

**Comment by TechieAndroid** [comment]
> Currently it seems like some "special characters" in the password field are not well behaving. Somehow those special characters are interpreted as escape chars. Changing the password isn't a big deal, so just as a note if anybody is wondering about "unknown  escape char" errors ....

Yeah but the problem there is that you risk further decreasing your passwords security. And I've already had someone break into my family plan before so I have to keep it secure.

I've personally never been a fan of having them in plaintext either, but that is out of the scope of this bug report.

**Comment by robinvd** [comment]
There is a password_cmd setting, that gets executed at startup. You can set this command to get the password from a password manager or system keyring

**Comment by TechieAndroid** [comment]
It was low priority anyway.
