### ISSUE TITLE
Spotifyd service won't start

### ISSUE THREAD

**Issue by Solay07** [Spotifyd/spotifyd#694]
**Description**
Spotifyd service won't start

**To Reproduce**
run: systemctl --user start spotifyd

the content of the service is as follows

    Description=A spotify playing daemon
    Documentation=https://github.com/Spotifyd/spotifyd
    Wants=sound.target
    After=sound.target
    Wants=network-online.target
    After=network-online.target
    
    [Service]
    ExecStart=/usr/bin/spotifyd --no-daemon
    Restart=always
    RestartSec=12
    
    [Install]
    WantedBy=default.target

**Expected behavior**
start the spotify service

**Logs**
<details><summary>Click to show logs</summary>

    ● spotifyd.service - A spotify playing daemon
             Loaded: loaded (/etc/xdg/systemd/user/spotifyd.service; disabled; vendor preset: enabled)
             Active: inactive (dead)
               Docs: https://github.com/Spotifyd/spotifyd
           
    Oct 21 20:55:38 solay-pc systemd[2480537]: spotifyd.service: Failed with result 'exit-code'.
    Oct 21 20:55:50 solay-pc systemd[2480537]: spotifyd.service: Scheduled restart job, restart counter is at 20.
    Oct 21 20:55:50 solay-pc systemd[2480537]: Stopped A spotify playing daemon.
    Oct 21 20:55:50 solay-pc systemd[2480537]: Started A spotify playing daemon.
    Oct 21 20:55:50 solay-pc spotifyd[2669399]: Loading config from "/home/ernest/.config/spotifyd/spotifyd.conf"
    Oct 21 20:55:50 solay-pc spotifyd[2669399]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(25), col: 10, at: Some(739), message: "", key: [] } }', src/config.rs:468:67
    Oct 21 20:55:50 solay-pc spotifyd[2669399]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Oct 21 20:55:50 solay-pc systemd[2480537]: spotifyd.service: Main process exited, code=exited, status=101/n/a
    Oct 21 20:55:50 solay-pc systemd[2480537]: spotifyd.service: Failed with result 'exit-code'.
    Oct 21 20:55:55 solay-pc systemd[2480537]: Stopped A spotify playing daemon.
</details>

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [x] alsa_backend
- [x] portaudio_backend
- [x] pulseaudio_backend
- [x] rodio_backend

**Versions (please complete the following information):**
- OS: Archlinux with kernel 5.9.1
- Spotifyd: 0.2.24
- cargo: 1.47.0

**Additional context**
My spotifyd config file

    [global]
    # Your Spotify account name.
    username = "username"
    
    # If set to true, `spotifyd` tries to look up your
    # password in the system's password storage.
    #
    # This is an alternative to the `password` field. Both
    # can't be used simultaneously.
    use_keyring = true
    
    # The audio backend used to play the your music. To get
    # a list of possible backends, run `spotifyd --help`.
    backend = pulseaudio
    
    # The volume controller. Each one behaves different to
    # volume increases. For possible values, run
    # `spotifyd --help`.
    volume_controller = alsa  # use softvol for macOS
    
    # The name that gets displayed under the connect tab on
    # official clients. Spaces are not allowed!
    device_name = spotitui
    
    # The audio bitrate. 96, 160 or 320 kbit/s
    bitrate = 160
    
    # The director used to cache audio data. This setting can save
    # a lot of bandwidth when activated, as it will avoid re-downloading
    # audio files when replaying them.
    #
    # Note: The file path does not get expanded. Environment variables and
    # shell placeholders like $HOME or ~ don't work!
    cache_path = "cache_directory"
    
    # If set to true, audio data does NOT get cached.
    no_audio_cache = true
    
    # If set to true, enables volume normalisation between songs.
    volume_normalisation = true
    
    # The normalisation pregain that is applied for each song.
    normalisation_pregain = -10
    
    # The displayed device type in Spotify clients.
    # Can be unknown, computer, tablet, smartphone, speaker, tv,
    # avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
    device_type = computer

**Comment by JojiiOfficial** [comment]
Could you please try to comment out line 25 and try again to start it.

**Comment by Solay07** [comment]
After comment out the line 25

    backend = pulseaudio

The error marks it on line 18

    volume_controller = alsa

and after commenting on line 18 the error appears on line 2 which is the username but this is correct

    username = my_username

**Comment by JojiiOfficial** [comment]
Look at the example. You may notice that every string is inside double quotes ("). All of your strings are not inside double quotes, so try to add that as well.

**Comment by Solay07** [comment]
That worked.

I apologize for the noob error
