### ISSUE TITLE
New release/future of releases

### ISSUE THREAD

**Issue by robinvd** [Spotifyd/spotifyd#702]
Now that we have a new config format, and multiple reports of users using the new format with the old binary. I think it would be a good idea to make a new release on crates.io

@SirWindfield what is currently the setup for releasing to crates.io and who is allowed to do that?

**Comment by massdregs** [comment]
Where can we get the new config file?

**Comment by slondr** [comment]
> Where can we get the new config file?

@massdregs It's in the readme

**Comment by SirWindfield** [comment]
I usually made sure that CI passed and I tested it locally on my Ubuntu VM to make sure that I get audio with pulse audio. After that, I create a new release stating which changes have been made:
```
git tag -a v0.x.x
```

It opens the editor and I manually add the changes and commit save and quit the editor afterwards. Then just push the tag. The CI will take care of the rest. If everything works fine and the artefacts have been generated, follow up the above with 

```
cargo publish
```

This will publish the version to crates.io. 

So basically:

1) Make sure everything works.
2) Make sure to create a release commit like "Bump version to 0.x.x". Just take a look at the commit history.
3) Create a git tag against that commit.
4) Push the tag to the repo.
4.1) Wait for CI to finish (there shouldn't be any problems if master passed all tests though).
5) Publish to crates.io

Optional 6) It would be probably better to create a changelog file and follow https://keepachangelog.com/de/1.0.0/. A lot of people use spotifyd and having to go through the releases to know what changed is utterly inconvenient. In the case you guys decide to create a changelog file, make sure to push the changelog changes after the versions have been published and not in-between or before. 
Pushing the changelog changes afterwards and not in-between makes sure that the versions published do work and use the same git reference across GitHub and crates. 
I usually do not push the changelog beforehand as I use automated tooling for changelog generation that I wrote some months back (@conventional-changelog-rs). It's not complete right now, a cargo subcommand is missing.

<details><summary>More about the tooling I use</summary>
You'd have to follow conventional commits so the tool can extract all the information it needs. https://github.com/SirWindfield/git-cm helps with that. When publishing a new release, you'd then run `next-semver | cargo next` to set the next version. Create a bumping commit: `chore(release): bump version to 0.x.x` and push the commits plus a new tag. If everything published succesfully, I run `changelog` to generate the new changelog and push it as well using a separate commit: `chore: update changelog`. 

The tooling basically needs to be run after pushing the newest tag as it uses git tags to derive the newest version and create the changelog accordingly.

A repository that uses the tooling can be found here. Take a loot at the commits and the changelog file :)
https://github.com/SirWindfield/cargo-create

Sadly I do not have a lot of time right now, but working on the projects inside that organization has currently the highest priority of my projects. I need something like that for all of the projects I do and I couldn't find anything that offered library and binaries for working with conventional commits :)
</details>

**Comment by SirWindfield** [comment]
Btw, I think you guys should be able to publish. I've set up a GitHub team and gave you publish permissions on crates.io. Lemme know if it doesn't work (just ping me).

**Comment by robinvd** [comment]
thats a very helpfull writeup, thx @SirWindfield 

@Spotifyd/maintainers then if most/all agree i think i it is a good idea to make a new release. I can do the steps above.

I do think a changelog would be a good idea!

> Pushing the changelog changes afterwards and not in-between makes sure that the versions published do work and use the same git reference across GitHub and crates.

so you're saying change `## [Unreleased]` to ` ##[0.x.x]` as a step 6?

**Comment by SirWindfield** [comment]
yep, basically!

**Comment by StaticPH** [comment]
What is currently blocking a new release that includes (any) changes from the last ~12 months?
Also, is the 0.2.24 release known to work on Windows, and there simply isn't a provided binary available for download, or does proper Windows functionality rely on changes made since the release?

**Comment by slondr** [comment]
@StaticPH The config file format mostly. See #698

**Comment by SirWindfield** [comment]
> Also, is the 0.2.24 release known to work on Windows, and there simply isn't a provided binary available for download, or does proper Windows functionality rely on changes made since the release?

I've been out of the loop for some time but IIRC the only Windows working stuff was a PR that has been opened some time ago that enabled the default backend to be rodio and used windows services instead of daemons.

**Comment by robinvd** [comment]
@StaticPH https://github.com/Spotifyd/spotifyd/pull/716/files was blocking the release, with that approved just now :) we have a new release. CI will hopefully soon push the new binaries. And after that i'll make a crates.io release.

**Comment by robinvd** [comment]
Also i think we can close this issue when we have completed a release

**Comment by slondr** [comment]
In the meantime, I'll push all the oustanding issues on the .25 milestone to .26

**Comment by JojiiOfficial** [comment]
Closing this since the new release has been published!
