### ISSUE TITLE
New to programming, I'm getting a segmentation fault 11.

### ISSUE THREAD

**Issue by willemmel** [Spotifyd/spotifyd#703]
Hi,

I've been trying to install Spotifyd for a few weeks now, and every week I'm getting closer to finally get it working.
My config file now finally stopped spitting errors, but when i try to run spotifyd --no-daemon, it posts the following:

```
Mac-mini-van-Willem:spotifyd-master willem$ spotifyd --no-daemon
Loading config from "/Users/willem/.config/spotifyd/spotifyd.conf"
Using software volume controller.
Segmentation fault: 11
```
I'm on a Mac Mini running 10.10.5, Spotifyd 0.2.24 and Cargo  1.47.0
How can I fix this?

**Comment by robinvd** [comment]
how did you install spotifyd? i.e. `cargo install spotifyd` or from the releases page

can you run `spotifyd --no-daemon --verbose` and post the output

**Comment by willemmel** [comment]
I installed it using the releases page, and I even did a complete reinstall yesterday the same way.

This is the output of `spotifyd --no-daemon --verbose`:
`Mac-mini-van-Willem:~ willem$ spotifyd --verbose --no-daemon
Loading config from "/Users/willem/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: Some("taken out for privacy"), use_keyring: false, on_song_change_hook: Some(""), cache_path: Some("cache_directory"), no-audio-cache: true, backend: Some(PortAudio), volume_controller: Some(SoftVolume), device: Some(""), control: Some(""), mixer: Some("PCM"), device_name: Some("MacMini"), bitrate: Some(Bitrate320), initial_volume: Some("100"), volume_normalisation: false, normalisation_pregain: Some(-10.0), zeroconf_port: Some(1234), proxy: Some("http://proxy.example.org:8080"), device_type: Some(Speaker) } }
Found user shell: Some("/bin/bash")
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
build; num-workers=2
registering; token=Token(18446744073709551615); interests=Readable
registering with poller
starting background reactor
Using software volume controller.
Segmentation fault: 11`

**Comment by willemmel** [comment]
Didn't quite fix it, but got it working by installing Ubuntu on the second harddrive (it's a server Mac Mini with two HDD's instead of an ODD). It works fine on there!
