### ISSUE TITLE
Spotifyd still not showing up as a device

### ISSUE THREAD

**Issue by massdregs** [Spotifyd/spotifyd#704]
**Description**
Running the command `spotifyd --verbose` or running the daemon `systemctl enable --now spotifyd` runs without any messages, but when opened in either spotify-tui or spotify-qt, it doesn't appear in the device list

**My config file**
<details><summary>Click to show logs</summary>
`[global]
# Your Spotify account name.
username = "my_name" # This is a placeholder for my actual name

# Your Spotify account password.
password = "my_password" # Also a placeholder

# A command that gets executed and can be used to
# retrieve your password.
# The command should return the password on stdout.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
# password_cmd = "command_that_writes_password_to_stdout"

# If set to true, `spotifyd` tries to look up your
# password in the system's password storage.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
# use_keyring = true

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "alsa"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
device = "alsa_audio_device"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
control = "alsa_audio_device"  # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS

# A command that gets executed in your shell after each song changes.
# on_song_change_hook = "command_to_run_on_playback_events"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = "my_device"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 160

# The directory used to cache audio data. This setting can save
# a lot of bandwidth when activated, as it will avoid re-downloading
# audio files when replaying them.
#
# Note: The file path does not get expanded. Environment variables and
# shell placeholders like $HOME or ~ don't work!
# cache_path = "path_to_cache"

# If set to true, audio data does NOT get cached.
no_audio_cache = true

# Volume on startup between 0 and 100
initial_volume = "90"

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 1234

# The proxy `spotifyd` will use to connect to spotify.
# proxy = "http://proxy.example.org:8080"

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, tv,
# avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
device_type = "computer"`

</details>

**Expected behavior**
My device shows up in the device list of either spotify-tui or spotiy

**Logs**
<details><summary>Click to show logs</summary>

Oct 30 22:36:44 HP8470p kernel: audit: type=1130 audit(1604068604.331:1192): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=spotifyd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 30 22:36:44 HP8470p kernel: audit: type=1131 audit(1604068604.331:1193): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=spotifyd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 30 22:36:44 HP8470p systemd[1]: Started A spotify playing daemon.
░░ Subject: A start job for unit spotifyd.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit spotifyd.service has finished successfully.
░░ 
░░ The job identifier is 14395.
Oct 30 22:36:44 HP8470p audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=spotifyd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 30 22:36:44 HP8470p kernel: audit: type=1130 audit(1604068604.335:1194): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=spotifyd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 30 22:36:44 HP8470p spotifyd[534425]: event Readable | Writable Token(20971525)
Oct 30 22:36:44 HP8470p spotifyd[534425]: loop process - 1 events, 0.000s
Oct 30 22:36:44 HP8470p spotifyd[534432]: No config file specified. Running with default values
Oct 30 22:36:44 HP8470p spotifyd[534432]: No username specified. Checking username_cmd
Oct 30 22:36:44 HP8470p spotifyd[534432]: No username_cmd specified
Oct 30 22:36:44 HP8470p spotifyd[534432]: No password specified. Checking password_cmd
Oct 30 22:36:44 HP8470p spotifyd[534432]: No password_cmd specified
Oct 30 22:36:44 HP8470p spotifyd[534432]: No proxy specified
Oct 30 22:36:44 HP8470p spotifyd[534425]: loop poll - 113.072891ms
Oct 30 22:36:44 HP8470p spotifyd[534432]: Using software volume controller.
Oct 30 22:36:44 HP8470p spotifyd[534425]: loop time - Instant { tv_sec: 75389, tv_nsec: 310185879 }
Oct 30 22:36:44 HP8470p spotifyd[534425]: loop process, 49.74µs
Oct 30 22:36:44 HP8470p spotifyd[534425]: attempting to decode a frame
Oct 30 22:36:44 HP8470p spotifyd[534425]: frame decoded from buffer
Oct 30 22:36:44 HP8470p spotifyd[534425]: Caught panic with message: Authentication failed with reason: BadCredentials
Oct 30 22:36:44 HP8470p spotifyd[534425]: deregistering handle with poller
Oct 30 22:36:44 HP8470p spotifyd[534425]: dropping I/O source: 5
Oct 30 22:36:44 HP8470p spotifyd[534425]: shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
Oct 30 22:36:44 HP8470p spotifyd[534425]:   -> transitioned to shutdown
Oct 30 22:36:44 HP8470p spotifyd[534425]:   -> shutting down workers
Oct 30 22:36:44 HP8470p spotifyd[534425]: deregistering handle with poller
Oct 30 22:36:44 HP8470p spotifyd[534425]: dropping I/O source: 0
Oct 30 22:36:44 HP8470p spotifyd[534425]: dropping I/O source: 3
Oct 30 22:36:44 HP8470p spotifyd[534425]: deregistering handle with poller
Oct 30 22:36:44 HP8470p spotifyd[534425]: dropping I/O source: 1
Oct 30 22:36:44 HP8470p spotifyd[534425]: deregistering handle with poller
Oct 30 22:36:44 HP8470p spotifyd[534425]: dropping I/O source: 2

</details>

**Versions (please complete the following information):**
- OS: Arch Linux
- Spotifyd: 0.2.24
- cargo: 1.47.0

<!-- **Additional context**
I installed spotifyd-full-git from the AUR.

**Comment by timlag1305** [comment]
I ran into the same issue when I used the systemd file. The problem I had is that my credentials weren't properly read from the config file. If I started spotifyd with `--username` and `--password` and filled in those parameters, my credentials worked.

**Comment by timlag1305** [comment]
I would guess this has to do with #698. Make sure your credentials aren't in quotes in your configuration file.

**Comment by massdregs** [comment]
I did what you said, and removed the quotes, but it started panicking

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(5), col: 11, at: Some(119), message: "", key: [] } }', src/config.rs:468:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

I also did `spotifyd --username "my username" --password "my password", but still nothing.

**Comment by timlag1305** [comment]
Then it must be a different issue. I would run spotifyd --username "my username" --password "my password" with the `--no-daemon` and `--verbose` flags and check if the logs are different from what you posted above. I'm new to this software so I'm really shooting in the dark here.

**Comment by timlag1305** [comment]
Unrelated, but I'm surprised your `systemctl` command worked. The package in the Arch repositories installs the spotifyd systemd file as a user file that needs to be started like `systemctl --user enable --now spotifyd`.

**Comment by massdregs** [comment]
When I put my username and password in quotes in the config file, this error

**Comment by suruaku** [comment]
> I would guess this has to do with #698. Make sure your credentials aren't in quotes in your configuration file.

Not only credentials, I got en error when any of parameters was in quotes(except device_type). This command is good for debugging ```spotifyd --no-daemon --verbose```.
I would try to run it with the simplest config with username, password, backend and device_name.

**Comment by massdregs** [comment]
So, did you get rid of the quotes? I removed everything from the config except for the username, password, backend, device name, and device type. Still nothing

**Comment by suruaku** [comment]
Yes, I don't have any quotes. My device type is `speaker` btw. Does running `spotifyd --no-daemon --verbose` show anything useful? Or `systemctl --user status spotifyd`? My systemctl config is in `.config/systemd/user/spotifyd.service` and spotifyd version same as yours (0.2.24)

**Comment by Skarlett** [comment]
> I ran into the same issue when I used the systemd file. The problem I had is that my credentials weren't properly read from the config file. If I started spotifyd with `--username` and `--password` and filled in those parameters, my credentials worked.

This is the general issue I've had, we should probably open a thread for that one specifically.

**Comment by massdregs** [comment]
I finally got it to work. I don't know what I did differently, but it works.
<details><summary>My config</summary>
```
[global]
username = "myname"
password = "mypassword"

backend = "alsa"
device_name = "ArchLinux"

initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10

device_type = "computer"
```
</details>
