### ISSUE TITLE
Support playback speed for podcasts

### ISSUE THREAD

**Issue by ericonr** [Spotifyd/spotifyd#707]
Spotify's podcast player supports setting the playback speed (which works when I'm, for example, listening on my phone), but playback by spotifyd isn't affected. This is a great feature to have, since people have very different comprehension needs and podcasts have different talking speeds as well.

**Describe the solution you'd like**

Ideally, it should allow itself to be controlled by simply setting playback speed in the player (so receiving it as an external command); another option would be having some dbus controls for it or something similar, though that wouldn't be the best user experience.

**Describe alternatives you've considered**

I don't think there is one for this case, unless it's possible to somehow make the sound server request audio faster from spotifyd.

**Comment by ericonr** [comment]
It is still a valid feature request, I think. I just haven't had time myself to look into it, nor has anyone else been interested in it.

**Comment by ericonr** [comment]
Ping

**Comment by ericonr** [comment]
Ping

**Comment by ponimas** [comment]
@ericonr Why was that issue closed as completed?
