### ISSUE TITLE
[Bug] Config Parse Fail

### ISSUE THREAD

**Issue by CynthSakurai** [Spotifyd/spotifyd#708]
I currently have `socklog-void` installed, symlinked, and running in the background (`socklog-void` installs both `socklog-unix` and `nanoklogd`, both of which are supposed to be enabled according to the wiki here: https://docs.voidlinux.org/config/services/logging.html) as recommended here: https://github.com/Spotifyd/spotifyd/issues/576#issuecomment-653817766. Spotify was installed via XBPS using the package `spotifyd`. My config file is located at ~/.config/spotifyd/spotifyd.conf and has been modified as follows:

```
[global]
# Your Spotify account name.
username = "username"

# Your Spotify account password.
password = "password"

# A command that gets executed and can be used to
# retrieve your password.
# The command should return the password on stdout.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
password_cmd = "command_that_writes_password_to_stdout"

# If set to true, `spotifyd` tries to look up your
# password in the system's password storage.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
use_keyring = false

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "pulseaudio"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
# device = "alsa_audio_device"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
# control = "alsa_audio_device"  # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS

# A command that gets executed in your shell after each song changes.
on_song_change_hook = "command_to_run_on_playback_events"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = "device_name_in_spotify_connect"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 320

# The directory used to cache audio data. This setting can save
# a lot of bandwidth when activated, as it will avoid re-downloading
# audio files when replaying them.
#
# Note: The file path does not get expanded. Environment variables and
# shell placeholders like $HOME or ~ don't work!
cache_path = "cache_directory"

# If set to true, audio data does NOT get cached.
no_audio_cache = true

# Volume on startup between 0 and 100
initial_volume = 90

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 1234

# The proxy `spotifyd` will use to connect to spotify.
# proxy = "http://proxy.example.org:8080"

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, tv,
# avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
device_type = "speaker"
```

Whenever I try to use `spotifyd` I get this error:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Unknown variant `\"pulseaudio\"`, expected one of `alsa`, `portaudio`, `pulseaudio`, `rodio`")', src/config.rs:415:42

The exact same error happens with `spotifyd --no-daemon` as well. 

I have no clue what I can attempt to do to fix this or what might might be causing this. I do not currently have spotifyd.service created or symlinked but I don't think that matters in this case (if someone would be kind enough to tell me how to create it and where to link it with a runit system it would be greatly appreciated, the readme is somewhat confusing in some parts). Alsa and pulseaudio are installed with audio fully functional. If additional info is required whatsoever just let me know and I will be more than happy to provide it. 

Edit: Apologies for the editing. The code block wasn't working properly and me being the derp I am didn't realize that a preview tab was available. Oops.

**Comment by JojiiOfficial** [comment]
Did you try it without double quotes?

**Comment by CynthSakurai** [comment]
I have tried with both single and double quotes, yes. It makes no difference as to what the error is or how anything functions as far as I can tell.

**Comment by ZweiEuro** [comment]
Archlinux, same error

**Comment by ZweiEuro** [comment]
I fixed it by deleting everything but login data, and then removing the " from pw and login. that's not how it should work but it works for now

**Comment by CynthSakurai** [comment]
Can confirm, @ZweiEuro is correct. If you are getting this error removing the quotation marks will fix it. It is also worth noting that if an authentication error appears next and you can't seem to log in, changing your password to one without alphanumeric characters will fix it. Closing the issue, and thanks for the help Zwei, I appreciate it. Don't know why I didn't think of that.

**Comment by ZweiEuro** [comment]
@CynthSakurai  I wouldn't consider this closed as it is still a bug, also 'without alphanumeric' explained why I couldn't get login to work (it just managed to parse the config) but really it should

**Comment by CynthSakurai** [comment]
@ZweiEuro My apologies, I closed it because it fixed the issue without thinking about the bug itself which may cause others grief unless they find this thread. Reopened so the team knows.

**Comment by ZweiEuro** [comment]
@CynthSakurai Just to make it easier to find, can you tag the issue as a bug, and edit the name to add 'config parse fail' or something like that? 
A main thread crash is rather broad but since we already know it's because of the config style it will narrow the issue down to the input parser at boot (which starts in main thread).

**Comment by joaofauvel** [comment]
The config file format has changed. Check issue #701 and #702
