### ISSUE TITLE
Update README with info about premium

### ISSUE THREAD

**Issue by easy90rider** [Spotifyd/spotifyd#71]
After I spent 2 hours trying to make it work with my PI I realized that I need premium...

Please add this to the README so that others don't waste their time with it ...

**Comment by SimonPersson** [comment]
Fixed.

**Comment by Modelmat** [comment]
Sorry for necroing an old issue, but why does this only support premium accounts?

**Comment by SimonPersson** [comment]
The underlying library, librespot, made that decision. I think it's a fair compromise, Spotify are rather nice for not shutting us down completely for running a reverse engineered client of their protocol. Let's not try their patience.

**Comment by Modelmat** [comment]
Okay, thanks.
