### ISSUE TITLE
Spotifyd stopping audio from normal spotify

### ISSUE THREAD

**Issue by Mercaman216** [Spotifyd/spotifyd#715]
Description
Spotifyd seems to mute my normal spotify, even after uninstall

1. download and install spotifyd using Cargo
2. Use it with Spotify-Tui
3. Stop Liking it
4. Delete both
5. No sound from Spotify?

Expected behavior
Sound from normal Spotify

Logs
no logs

Versions (please complete the following information):
- OS: Ubuntu 20.10
- Spotifyd: 0.2.24
- cargo: 1.43.0

Any help would be greatly appreciated:)

**Comment by robinvd** [comment]
Could you elaborate on the steps, so i can try and reproduce them. What do you mean with “stop liking it” and “delete both”.

**Comment by Mercaman216** [comment]
> Could you elaborate on the steps, so i can try and reproduce them. What do you mean with “stop liking it” and “delete both”.

by stop liking it, I wanted to say that I didn't really find the need of spotifyd on my computer even though its a smart program, Its not exactly a step in the process, just an emotional state

and by delete both, is that I removed spotifyd by doing the command "cargo uninstall spotifyd" and deleted spotify-tui from the app store

**Comment by robinvd** [comment]
If you have issues after uninstalling spotifyd, then this is most likely an issue with spotify

**Comment by Mercaman216** [comment]
do you have any suggestions on how to fix it?

**Comment by JojiiOfficial** [comment]
Probably a dumb question but did you try to switch back the spotify output to the local phone/local pc? And what non working client/app are you talking about in detail?

**Comment by Wael2727** [comment]
its probable that spotifyd contains spotify librarys/packages so try to install spotify with all its original dependencies and requirements 

if that doesnt work then make sure that it sends sound but you just dont hear it

**Comment by Wael2727** [comment]
dude. let us know how you fixed it so you could potentially help others

**Comment by Mercaman216** [comment]
I just reinstalled Ubuntu, I didn't find a way to fix it unfortunately
