### ISSUE TITLE
Running spotifyd results in main thread panic

### ISSUE THREAD

**Issue by momoKB** [Spotifyd/spotifyd#718]
preface: first time reporting a bug, so please forgive my ignorance of proper protocol, I promise I will learn to do better.

**Description**
running spotifyd results in thread panic

**To Reproduce**

1. install **spotifyd-full-git** via yay
2. setup config file in /home/sk/.config/spotifyd/spotifyd.conf
```
[global]
# Your Spotify account name.
username = username

# Your Spotify account password.
password = password

device_name = sk

backend = pulseaudio
```

3. run spotifyd in terminal

` [sk@skarch ~]$ spotifyd thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(49), message: "", key: [] } }', src/config.rs:468:67 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

>>

```
[sk@skarch ~]$ RUST_BACKTRACE=full spotifyd --verbose --no-daemon
Loading config from "/home/sk/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(49), message: "", key: [] } }', src/config.rs:468:67
stack backtrace:
   0:     0x55ec2b890c40 - <unknown>
   1:     0x55ec2b8b8d2c - <unknown>
   2:     0x55ec2b888d47 - <unknown>
   3:     0x55ec2b893340 - <unknown>
   4:     0x55ec2b89308c - <unknown>
   5:     0x55ec2b8939a3 - <unknown>
   6:     0x55ec2b893579 - <unknown>
   7:     0x55ec2b8910cc - <unknown>
   8:     0x55ec2b893539 - <unknown>
   9:     0x55ec2b8b68c1 - <unknown>
  10:     0x55ec2b8b66e3 - <unknown>
  11:     0x55ec2b2383e3 - <unknown>
  12:     0x55ec2b22b76a - <unknown>
  13:     0x55ec2b22d083 - <unknown>
  14:     0x55ec2b20e759 - <unknown>
  15:     0x55ec2b893e71 - <unknown>
  16:     0x55ec2b22bec2 - main
  17:     0x7fd63620f152 - __libc_start_main
  18:     0x55ec2b1c70ee - <unknown>
  19:                0x0 - <unknown>
```

**Expected behavior**
spotifyd runs

**Logs**
<details><summary>Click to show logs</summary>

  

</details>

**Compilation flags** 

ID=arch
BUILD_ID=rolling

- Spotifyd: 0.2.24
- cargo: 1.47.0

<!-- **Additional context**
symlinks are setup as described in this git

**Comment by ryan77627** [comment]
I was getting a similar error, specifically this one:
 ```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: UnquotedString, line: Some(1), col: 11, at: Some(20), message: "", key: [] } }', src/config.rs:468:67
```

The solution for me (since it's referring to an Unquoted String) was to go into my spotifyd.conf file and change all values to go from this:
```
[global]
username = username
password = password
device_type = computer
bitrate = 320
...
```
to this:
```
[global]
username = "username"
password = "password"
device_type = "computer"
bitrate = 320
...
```
(Notice how all the strings have quotes and the integers don't)

I'm not sure why you're getting a NumberInvalid error since there aren't any numbers in the spotifyd.conf you provided. It just seems to be a parsing issue with the config

**Comment by robinvd** [comment]
very sorry for the confusion. We just updated the configuration format, and are planning a release to update the packages (see https://github.com/Spotifyd/spotifyd/pull/716). also see https://github.com/Spotifyd/spotifyd/issues/712 for similar/same issue

**Comment by JojiiOfficial** [comment]
Closing this as duplicate. Please reopen it, If the error still persists in future.

**Comment by davisi3** [comment]
I added in quotes my username, password but I still got this. thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Unexpected('/'), line: Some(7), col: 13, at: Some(132), message: "", key: [] } }', src/config.rs:477:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
