### ISSUE TITLE
Caught panic with message: Authentication failed

### ISSUE THREAD

**Issue by mistralol** [Spotifyd/spotifyd#72]
It seems when I move from work to home (where spotifyd is running). When using the computer and then getting the spotfiy client to play on the pi using spotifyd it will die with the following error message.

Jul 14 18:39:29 amp spotifyd[3500]: 18:39:29 [INFO] Response::new "HTTP/1.1 200 OK"
Jul 14 18:39:29 amp spotifyd[3500]: 18:39:29 [INFO] Connecting to AP "gew1-accesspoint-b-kqcn.ap.spotify.com:4070"
Jul 14 18:39:30 amp spotifyd[3500]: 18:39:30 [ERROR] Caught panic with message: Authentication failed

Once the service restarts. It will then work as normal. This has happened multiple days in a row. So I am quite sure it can be reproduced quite easily.

**Comment by indiscible** [comment]
I had the same issue because I was using the same login on the pi and on the computer.
In your spotify account you can request a different username and password for the device.

**Comment by mistralol** [comment]
I was using no auth details on the device. I cannot find where to create a 2nd username / password for the pi. But what I do know if I add the same details as my spotify account it does work. he problem is this doesn't work terribly well with multiple users in multiple locations.

**Comment by Magicking** [comment]
Looks like some servers from the pool apresolve.spotify.com cause failed authentication with good password while some other works.

**Comment by Ch4rlus** [comment]
Hm. I'm running into the same issue : With the exact same credentials, I have to launch the daemon about 4-5 times for it to start succesfully without the "Caught panic with message: Authentication failed" error

**Comment by SimonPersson** [comment]
Should be fixed by #75. Thanks for reporting.
