### ISSUE TITLE
spotifyd panics  `Couldn't initialize logger`

### ISSUE THREAD

**Issue by Wael2727** [Spotifyd/spotifyd#720]
**Description**

**To Reproduce**
1. launch spotifyd
keep in mind i have no config setup and ive tried with and without one
and have rust installed

**Expected behavior**

**Logs**
```
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: None })), backtrace: None })', src/main.rs:40:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Verbose Logs ( `RUST_BACKTRACE=1 )**
```
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: Some(stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: main
   9: __libc_start_main
             at ../csu/libc-start.c:308
  10: <unknown>
) })), backtrace: Some(stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: main
   9: __libc_start_main
             at ../csu/libc-start.c:308
  10: <unknown>
) })', src/main.rs:40:26
stack backtrace:
   0:     0x556246387ce5 - <unknown>
   1:     0x5562463b1a5c - <unknown>
   2:     0x55624637f863 - <unknown>
   3:     0x55624638a680 - <unknown>
   4:     0x55624638a3cc - <unknown>
   5:     0x55624638acd1 - <unknown>
   6:     0x55624638a8bb - <unknown>
   7:     0x5562463af6d1 - <unknown>
   8:     0x5562463af4f3 - <unknown>
   9:     0x556245cd1af6 - <unknown>
  10:     0x556245d0c5e3 - <unknown>
  11:     0x55624638b1d8 - <unknown>
  12:     0x556245cd1d22 - main
  13:     0x7f521074cdeb - __libc_start_main
                               at ../csu/libc-start.c:308
  14:     0x556245ca123a - <unknown>
  15:                0x0 - <unknown>
@!
```

**Compilation Logs**
```
   Compiling openssl-sys v0.9.53
   Compiling alsa-sys v0.1.2
   Compiling httparse v1.3.4
   Compiling protobuf v2.10.0
   Compiling proc-macro2 v0.4.30
   Compiling idna v0.1.5
error: failed to run custom build command for `alsa-sys v0.1.2`
Caused by:
  process didn't exit successfully: `/home/wael/spotifyd/target/release/build/alsa-sys-56db419867972fa5/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', /home/wael/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-sys-0.1.2/build.rs:4:38
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
- OS: Void Linux
- Spotifyd: 0.2.24_4
- cargo: 0.47.0_1

**Comment by JojiiOfficial** [comment]
How exactly did you launch spotifyd? Why did you attach a non successful compilation log (how is this related to the issue)? How could you even launch spotifyd with a compilation error?

**Comment by Wael2727** [comment]
i launched spotifyd 'xbps-query'
that didnt work so i compiled it from source 'meson'

**Comment by Wael2727** [comment]
i got new compilation logs:
```
   Compiling openssl-sys v0.9.53
   Compiling protobuf v2.10.0
   Compiling quote v1.0.2
   Compiling time v0.1.42
   Compiling crossbeam-utils v0.7.0
   Compiling tokio-current-thread v0.1.6
error: failed to run custom build command for `openssl-sys v0.9.53`

Caused by:
  process didn't exit successfully: `/home/wael/spotifyd/target/release/build/openssl-sys-2a886da122fcf6d7/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.53

  ', /home/wael/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.53/build/find_normal.rs:150:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by JojiiOfficial** [comment]
That is another issue. You need to have `openssl-dev`, `librust-openssl-sys-dev` or `librust-openssl-dev` installed. I'm not quite sure which of them is exactly required, I assume its `librust-openssl-sys-dev` though.

**Comment by Wael2727** [comment]
none of these exist. ive searched in the void linux repositories and source void-packages

**Comment by ericonr** [comment]
Using the version from the Void repository, run `strace spotifyd --no-daemon` to see what file it's trying to open and can't find.

**Comment by Wael2727** [comment]
```openat(AT_FDCWD, "/usr/lib/pulseaudio/tls/haswell/x86_64/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/tls/haswell/x86_64", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/pulseaudio/tls/haswell/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/tls/haswell", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/pulseaudio/tls/x86_64/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/tls/x86_64", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/pulseaudio/tls/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/tls", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/pulseaudio/haswell/x86_64/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/haswell/x86_64", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/pulseaudio/haswell/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/haswell", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/pulseaudio/x86_64/libpulsecommon-13.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/pulseaudio/x86_64", 0x7ffed2bcc7c0) = -1 ENOENT (No such file or directory)```

**Comment by Wael2727** [comment]
wait.. all of these are already installed..??

**Comment by JojiiOfficial** [comment]
@Wael2727 I don't know what exactly you were expecting from strace'ing the binary but its usual applications to access lots of shared libraries. The one you're missing is not in there though. You need the openssl headers and shared libraries. I don't know exactly which void-packages you need to have all dependencies. Maybe have a look at the required build depends from the xbps source file.

**Comment by Wael2727** [comment]
currently it has compiled 288 ...things and it is taking waay to long...
even compiled alot of things i have already installed

**Comment by JojiiOfficial** [comment]
What you're compiling are partly rust bindings which you still have to compile (since they're bindings to libraries you already have installed but in rust). It's a known problem for rust to take very long at compiling. You can use sccache to improve the caching of already compiled stuff, which helps if you're compiling the same things over and over again (for example if you're compiling multiple different rust applications). If you're just trying out something, don't use `--release`.

**Comment by Wael2727** [comment]
alright, i **think** i fixed it, but don't close it, i still havent found the library that spotifyd needs.

run spotifyd with --no-daemon but you will have issues trying to stream audio.

**Comment by ericonr** [comment]
@Wael2727 please post the complete strace (in a gist, preferrably).

@JojiiOfficial I know for a fact the packaged version of `spotifyd` works on Void, with multiple backend options even. Build issues are usually caused by Void using LibreSSL instead of OpenSSL.

**Comment by Wael2727** [comment]
installing OpenSSL with void linux is very difficult and i couldn't do it, really probably the reason spotifyd could not run so thanks for telling me that

right now i have switched to arch linux and it works fine to i guess i will stick with this for now.
thanks for the help

**Comment by JojiiOfficial** [comment]
I'm not that familiar with void and the used SSL/TLS library. Spotifyd depends on openssl but in case void uses something else, it can be hard to get compiled properly. A way to prevent that would probably be to compile spotifyd with musl support so no library gets linked dynamically. I don't know if you can link openssl that easy though.

**Comment by ericonr** [comment]
`openssl-sys` for Rust supports both OpenSSL and LibreSSL, so building spotifyd in Void is fully possible (and has been done, as I am currently using it - and it's also an officially maintained package).

>A way to prevent that would probably be to compile spotifyd with musl support so no library gets linked dynamically. I don't know if you can link openssl that easy though.

I wouldn't recommend a fully static build with a SSL library, even if the usecase here is rather constrained. Anyway, it shouldn't be necessary.

I could have tried to help with the strace output, but one wasn't provided :/

**Comment by drumsetmonkey** [comment]
I had this same issue on Void Linux and was able to solve it by installing `socklog-void` and `socklog`. After doing that I could run spotifyd fine without the need for the `--no-daemon` option
