### ISSUE TITLE
pipewire support

### ISSUE THREAD

**Issue by basedtho** [Spotifyd/spotifyd#722]
**Is your feature request related to a problem? Please describe.**
looks like pipewire is the next big thing in linux. at least in arch pulseaudio is going to be replaced with pipewire soon

**Describe the solution you'd like**
pipewire support

**Describe alternatives you've considered**
pipewire-pulse package doesn't do it. i still hear no sound after installation

**Comment by fourstepper** [comment]
I am running pipewire and I am having no issues with pipewire itself - how are you running the daemon? Do other apps work?

**Comment by basedtho** [comment]
@fourstepper do you have pulseaudio installed? i uninstalled pulseaudio and pulseaudio-alsa (i'm on arch), and installed pipewire and pipewire-pulse. sound in qutebrowser works, but not in spotifyd. though i set `backend = pulseaudio` in spotifyd.conf, i thought it should work?

**Comment by basedtho** [comment]
it uses alsa backend by default

**Comment by basedtho** [comment]
problem solved by installing pipewire 0.3.16

**Comment by fourstepper** [comment]
I use alsa as well as the spotifyd backend, no need to use the pulseaudio backend
