### ISSUE TITLE
Bad credentials with complex symbol password

### ISSUE THREAD

**Issue by guyfedwards** [Spotifyd/spotifyd#724]
**Description**

**To Reproduce**

1. set password containing `#` in `$HOME/.config/spotifyd/spotifyd.conf`
2. run `spotifyd --no-daemon`
3. See error 'Bad credentials'

Passing the same password as `--password` flag to cli works fine

**Expected behavior**
Password authentication should work from config file

**Logs**
<details><summary>Click to show logs</summary>

  
Loading config from "/home/guy/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: Some(PulseAudio), volume_controller: None, device: None, control: None, mixer: None, device_name: None, bitrate: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None } }
Found shell "/bin/bash" using SHELL environment variable.
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=4
registering with poller
Using software volume controller.
starting background reactor
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:36193
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
adding I/O source: 8388610
registering with poller
loop process - 1 events, 0.000s
event Writable Token(8388610)
loop process - 1 events, 0.000s
adding I/O source: 12582915
registering with poller
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://apresolve.spotify.com/")
event Writable Token(12582915)
consuming notification queue
loop process - 1 events, 0.000s
scheduling Read for: 0
resolving host="apresolve.spotify.com", port=80
scheduling Read for: 1
sending packet to V4(224.0.0.251:5353)
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
event Readable | Writable Token(4194305)
loop process - 1 events, 0.000s
scheduling Read for: 2
sending packet to V6([ff02::fb]:5353)
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
scheduling Read for: 3
loop poll - 2.688873ms
loop time - Instant { tv_sec: 245730, tv_nsec: 480725959 }
loop process, 51.691µs
received packet from V4(10.69.49.164:5353)
event Readable | Writable Token(8388610)
loop process - 1 events, 0.000s
received packet from V4(10.69.49.164:5353) with no query
scheduling Read for: 1
scheduling Read for: 1
received packet from V6([fe80::42:83ff:feec:1cb8]:5353)
received packet from V6([fe80::42:83ff:feec:1cb8]:5353) with no query
scheduling Read for: 2
scheduling Read for: 2
loop poll - 260.009µs
loop time - Instant { tv_sec: 245730, tv_nsec: 481049729 }
loop process, 27.927µs
loop poll - 8.967225ms
loop time - Instant { tv_sec: 245730, tv_nsec: 490056614 }
loop process, 40.985µs
connecting to [2600:1901:0:524d::]:80
adding I/O source: 16777220
registering with poller
scheduling Write for: 4
event Readable | Writable | Error | Hup Token(16777220)
loop process - 1 events, 0.000s
loop poll - 1.001699428s
loop time - Instant { tv_sec: 245731, tv_nsec: 492057759 }
loop process, 61.256µs
connect error Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
connecting to 34.98.74.57:80
adding I/O source: 20971525
registering with poller
deregistering handle with poller
dropping I/O source: 4
scheduling Write for: 5
event Writable Token(20971525)
loop process - 1 events, 0.000s
loop poll - 12.053468ms
loop time - Instant { tv_sec: 245731, tv_nsec: 504812036 }
loop process, 36.509µs
read_keep_alive; is_mid_message=false
scheduling Read for: 5
should_keep_alive(version=Http11, header=None) = true
Client::encode has_body=false, method=None
reclaiming write buf Vec
flushed 47 bytes
flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 487.212µs
loop time - Instant { tv_sec: 245731, tv_nsec: 505595577 }
loop process, 31.784µs
event Readable | Writable Token(20971525)
loop process - 1 events, 0.000s
Conn::read_head
read 594 bytes
Response.parse([Header; 100], [u8; 594])
Response.parse Complete(176)
maybe_literal not found, copying "Via"
parsed 5 headers (176 bytes)
incoming body is content-length (418 bytes)
expecting_continue(version=Http11, header=None) = false
should_keep_alive(version=Http11, header=None) = true
Conn::read_body
decode; state=Length(418)
flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
wants_read_again? false
loop poll - 20.803436ms
loop time - Instant { tv_sec: 245731, tv_nsec: 526448517 }
loop process, 465.851µs
Conn::read_body
decode; state=Length(0)
incoming body completed
scheduling Read for: 5
maybe_notify; read_from_io blocked
read_keep_alive; is_mid_message=false
scheduling Read for: 5
signal: Want
flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
wants_read_again? false
poll_want: taker wants!
pool dropped, dropping pooled ("http://apresolve.spotify.com")
loop poll - 1.606371ms
loop time - Instant { tv_sec: 245731, tv_nsec: 529003498 }
loop process, 119.835µs
Connecting to AP "gew1-accesspoint-b-vqdv.ap.spotify.com:443"
adding I/O source: 25165828
registering with poller
scheduling Write for: 4
read_keep_alive; is_mid_message=false
scheduling Read for: 5
client tx closed
State::close_read()
State::close_write()
flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None }
wants_read_again? false
shut down IO
deregistering handle with poller
dropping I/O source: 5
signal: Closed
loop poll - 1.462144ms
loop time - Instant { tv_sec: 245731, tv_nsec: 549167315 }
loop process, 123.633µs
event Writable Token(25165828)
loop process - 1 events, 0.000s
loop poll - 34.038768ms
loop time - Instant { tv_sec: 245731, tv_nsec: 583395677 }
loop process, 112.897µs
scheduling Read for: 4
event Readable | Writable Token(25165828)
loop process - 1 events, 0.000s
loop poll - 36.547418ms
loop time - Instant { tv_sec: 245731, tv_nsec: 644215565 }
loop process, 28.749µs
flushing framed transport
writing; remaining=142
framed transport flushed
scheduling Read for: 4
event Readable | Writable Token(25165828)
loop process - 1 events, 0.000s
loop poll - 119.324087ms
loop time - Instant { tv_sec: 245731, tv_nsec: 770948503 }
loop process, 14.314µs
attempting to decode a frame
frame decoded from buffer
Caught panic with message: Authentication failed with reason: BadCredentials
deregistering handle with poller
dropping I/O source: 4
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
dropping I/O source: 3
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
┌ guy ~/Dropbox/Documents/Notes
└ ☲  spotifyd  --no-daemon
Loading config from "/home/guy/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Connecting to AP "gew1-accesspoint-b-dzl6.ap.spotify.com:443"
Caught panic with message: Authentication failed with reason: BadCredentials
┌
</details>

**Compilation flags** 
using AUR package community/spotifyd

**Versions (please complete the following information):**

- OS: Linux archlinux 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux
- Spotifyd: community/spotifyd 0.2.24-2
- cargo: cargo 1.33.0 (f099fe94b 2019-02-12)

**Comment by JojiiOfficial** [comment]
Could you try to compile the latest version of spotifyd and surround all strings inside your config with double quotes? I guess this'll fix it since we changed the configuration parsing recently.

**Comment by massdregs** [comment]
Possible duplicate #701

**Comment by slondr** [comment]
Should be resolved with v0.2.25 (#716)

Let us know if the issue persists
