### ISSUE TITLE
OpenBSD build: struct `ConnectConfig` has no field named `linear_volume`

### ISSUE THREAD

**Issue by burne251** [Spotifyd/spotifyd#726]
**Description**

I'm trying to port over spotifyd to the OpenBSD Ports tree, but ran into an issue. The below errors are on a fresh, vanilla copy of spotifyd- the only changes made were configuring it to think Linux is the target_os for the function in utils.rs, and adding a patches section to the .toml file because a local version of openssl had to be used since OpenBSD had a newer version of libressl than was listed in the config.

**To Reproduce**
Command run was cargo build --release --no-default-features --features "pulseaudio_backend,dbus_keyring,dbus_mpris"

**Expected behavior**

Should build, librespot built without any issue and checking the registry, they have the "missing" fields

**Logs**
<details><summary>Click to show logs</summary>

   Compiling spotifyd v0.2.24 (/home/charlie/Code/Porting/wip/spotifyd)
error[E0063]: missing field `gapless` in initializer of `PlayerConfig`
   --> src/config.rs:680:24
    |
680 |         player_config: PlayerConfig {
    |                        ^^^^^^^^^^^^ missing `gapless`

error[E0560]: struct `ConnectConfig` has no field named `linear_volume`
   --> src/main_loop.rs:172:25
    |
172 |                         linear_volume: self.linear_volume,
    |                         ^^^^^^^^^^^^^ `ConnectConfig` does not have this field
    |
    = note: available fields are: `name`, `device_type`, `volume`, `volume_ctrl`, `autoplay`

error: pattern requires `..` due to inaccessible fields
  --> src/process.rs:65:9
   |
65 |         PlayerEvent::Started { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: ignore the inaccessible and unused fields
   |
65 |         PlayerEvent::Started { track_id, .. } => {
   |                                        ^^^^

error: pattern requires `..` due to inaccessible fields
  --> src/process.rs:69:9
   |
69 |         PlayerEvent::Stopped { track_id } => {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: ignore the inaccessible and unused fields
   |
69 |         PlayerEvent::Stopped { track_id, .. } => {
   |                                        ^^^^

error[E0560]: struct `ConnectConfig` has no field named `linear_volume`
  --> src/setup.rs:97:13
   |
97 |             linear_volume,
   |             ^^^^^^^^^^^^^ `ConnectConfig` does not have this field
   |
   = note: available fields are: `name`, `device_type`, `volume`, `volume_ctrl`, `autoplay`

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0063, E0425, E0560.
For more information about an error, try `rustc --explain E0063`.
error: could not compile `spotifyd`
  

</details>

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [ x pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: OpenBSD, snapshot, latest commit 03c020efffdc59299fc644eccda2603a9859cb33 on git
- Spotifyd: Git commit 39106ed8ed270247b1203cc2eed5b05121c90cf7
- cargo: 1.48.0

**Comment by robinvd** [comment]
Thanks for the issue! I cant really help you with this from my linux machine, but keep it open te help/discuss with other people doing the same thing
