### ISSUE TITLE
No sound, Spotifyd keeps shutting down

### ISSUE THREAD

**Issue by edwardsaunders7** [Spotifyd/spotifyd#731]
I have configured my config file, and passed it into spotifyd using the -c /path command. This all works and presents no errors.

When starting Spotifyd it runs without problems, and displays as a device that I can stream music to. However, when attempting to stream music, no sound plays from my computer. I know that my config does work - as I have it working on a separate device running the same distro, using the same config file.

I have double checked that the backend is correct (pulseaudio).

Any ideas?

Running Manjaro KDE Plasma 5.8.18-1

Running Spotifyd-full-git

**Comment by JojiiOfficial** [comment]
Where are debugging logs? What does pavucontrol say, does it get recognized as playback application?

**Comment by edwardsaunders7** [comment]
I have changed nothing, and it has now started to work - I am unsure why. I will mark this as resolved.

Previously Spotifyd was shutting down with error code 101 - this error has seemingly fixed itself
