### ISSUE TITLE
Spotifyd compiled, but doesn't run in terminal (also no .config folder)

### ISSUE THREAD

**Issue by huronics** [Spotifyd/spotifyd#734]
So I'm using Ubuntu 20.04 and i waited for spotifyd to get done compiling after i got all the neccessary packages. compiled and was set up flawlessly, or so i though. when i type spotifyd in my terminal i get the "command not found" as if it had never existed in the first place. along with the fact that when i checked my config folder and nothing is in there, checked /etc/xdg/spotifyd and nothing there either. is there a step i'm missing or did something go wrong?

**Comment by JojiiOfficial** [comment]
Could you please be a bit more specific about what you did. Did you clone it. What command did you execute to compile it?

**Comment by huronics** [comment]
hi, i went to the green button that says "code" on the page and downloaded the zip folder. after that i extracted the file, cd into the directory, and ran cargo build --release. and again it had compiled fine but there was no folders for the config and the terminal doesn't acknowledge that it exists even after a reboot.

**Comment by JojiiOfficial** [comment]
The binary is located at `./target/release/spotifyd` so you have to execute this file in order to get it to run. You can move it to `/bin/` if you want it to be accessible from everywhere
