### ISSUE TITLE
Add link to Docker instructions to README?

### ISSUE THREAD

**Issue by joonas-fi** [Spotifyd/spotifyd#737]
## Idea

I'm not sure if many people like/expect to run Spotifyd as a Docker container, so that doesn't probably warrant this project to have Docker instructions..

But I'm thinking there could be a third party community project for those that are interested.

## My suggestion

I recently made a Docker image and thus I have a repo: https://github.com/joonas-fi/spotifyd-docker

I also wrote a blog post on how ALSA/PulseAudio works from a container (also linked from my repo): https://joonas.fi/2020/12/audio-in-docker-containers-linux-audio-subsystems-spotifyd/

If this sounds good, I can send a PR adding my Docker image GitHub project URL to README.

## Alternatives

- https://github.com/GnaphronG/docker-spotifyd - no instructions on how to use the Docker image
- https://github.com/jvkassi/docker-spotifyd - seems like an older approach, and Docker run flags imply no audio is being emitted

**Comment by robinvd** [comment]
I haven't though about running spotifyd in docker myself, but i might be a good idea.

any opinions from @Spotifyd/maintainers ?

**Comment by JojiiOfficial** [comment]
I don't think this is necessary. Which advantages does it have running such an  'audio player' inside a container?
I wouldn't mind adding this link to the readme though. There'll probably be some people looking for that and it doesn't change anything on the existing spotifyd, so why not.

**Comment by MarinPostma** [comment]
Your blog post is very interesting! I rejoin @JojiiOfficial opinion, the use case is super niche, and this information needs to exist somewhere. O don't think its place is in the readme though, since it's more of a specific usecase, but maybe in a github discussion?

**Comment by joonas-fi** [comment]
> Which advantages does it have running such an 'audio player' inside a
container?

Advantages:

- Security: if a vulnerability granted access to an attacker, she can't do
much unless she manages to escape the container.

- Installation: Docker is also a packaging format. I try to install
everything I need via Docker, so what my server runs/needs is mainly Docker
compose files (files which specify which containers to run with which
config), so when I need to migrate computers I just transfer those
declarative config files and don't need to manually install/configure
anything.

**Comment by joonas-fi** [comment]
So I guess my question is this:

Would you accept a PR to add mention about Docker usage to `README` with a link to https://github.com/joonas-fi/spotifyd-docker
