### ISSUE TITLE
No audio on Raspberry Pi

### ISSUE THREAD

**Issue by pleasurface** [Spotifyd/spotifyd#753]
**Description**
Hi! I know this doesn't belong here, but I'm pretty new to programming and I just have no idea how to get the audio working with spotifyd. Can anyone help me? I installed spotifyd as descriped in https://github.com/Spotifyd/spotifyd/wiki/Installing-on-a-Raspberry-Pi and it works fine, I can choose my Raspberry as a device. Still, there is no audio at all. I'd prefer to play the audio on a bluetooth speaker (which is successfully connected to the pi!). 

**Expected behavior**
Hear audio

**Versions (please complete the following information):**
- v0.2.24 for armv6

**Comment by robinvd** [comment]
could you try not starting from a systemd file but just using `./spotifyd --no-daemon`. What might also help is seeing if there is any data in pulseaudio (if you are using pulse on your pi)
