### ISSUE TITLE
Metadata fetching isn't cached and will cause API rate limiting

### ISSUE THREAD

**Issue by p4block** [Spotifyd/spotifyd#754]
**Description**
After switching to spotifyd I found that my "Artist - Song" indicator on waybar/polybar would stop showing randomly. 

The indicator works by executing `playerctl metadata` commands every second or so. It seems like spotifyd is just passing the call to spotify's API without remembering the last result if the current song hasn't changed. 

I could rewrite the indicator to work using the "run script on song change" feature of spotifyd, but all other players support caching the metadata (first time I've had an issue with this approach)

**To Reproduce**
Run `playerctl -p spotifyd metadata title` a few times

**Expected behavior**
Command works every time, I don't get rate limited 

**Logs**
The service logs indicate a lot of:
`Couldn't fetch metadata from spotify: Err(RateLimited(Some(14)))`
</details>

**Versions (please complete the following information):**

- OS: Arch
- Spotifyd: 0.2.24-2

**Comment by p4block** [comment]
Thanks to this bug I finally switched to a different media player applet script that doesn't spam queries every second, however I believe that doing so shouldn't cause rate limiting (this is the only player where I found that behavior)

**Comment by robinvd** [comment]
i forgot where you can find this, but if you get rate limited a lot, you can use your own spotify app key and avoid sharing the rate limit with other people

**Comment by robinvd** [comment]
see https://github.com/Spotifyd/spotifyd/issues/507 for rate limit errors. closing this, but if you still have issues dont hasitate to reopen!
