### ISSUE TITLE
Special characters in password causes BadCredentials

### ISSUE THREAD

**Issue by juxuanu** [Spotifyd/spotifyd#756]
**Description**

If your password contains special characters (mine contained `# ^ ! * @`) probably the parser does a wrong job and and the Spotify's response is BadCredentials when `spotifyd --no-daemon` is run.
**To Reproduce**

1. Edit your config file with a correct password containing a special character such as any of these `# ^ ! * @`.
2. Try to launch the program with `spotifyd --no-daemon`.
3. See the error BadCredentials. Probably a parsing error.

**Logs**
<details><summary>Click to show logs</summary>

  
Loading config from "/home/icar/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Connecting to AP "gew1-accesspoint-b-hlvr.ap.spotify.com:443"
Caught panic with message: Authentication failed with reason: BadCredentials
</details>

**Versions (please complete the following information):**

- OS: ArchLinux
- Spotifyd: 0.2.24-2
- cargo: 1.23.1-1

**Comment by JojiiOfficial** [comment]
This issue should've been fixed with the new config format. Try out the latest git commit.

**Comment by juxuanu** [comment]
Then this issue can be closed. I changed my password instead.

Thanks!
