### ISSUE TITLE
Static bind port in config

### ISSUE THREAD

**Issue by mib4fun** [Spotifyd/spotifyd#77]
Hello,

Is it possible to add a listen port directive in the config and cli ?

**Comment by SimonPersson** [comment]
I'm not sure what you are asking for, really? We don't really open any port for listening in Spotifyd.

Or did you mean [Spotifyd/spotifyd-http](https://github.com/Spotifyd/spotifyd-http)?

**Comment by mib4fun** [comment]
Yeah, closing
