### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [Spotifyd/spotifyd#771]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of GNU/Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code. With GPG signatures it is possible for packagers to verify source code releases quickly and easily.

In order to securely package your software I am kindly requesting GPG signatures for the source tarballs. If you are not yet familiar with secure source code signing I suggest using [GPGit](https://github.com/NicoHood/gpgit) which automates the process of secure source code signing and also has a quick start guide on GPG for learning how to use it manually.

The project was initiated by me because too many people wanted automatic tooling or at least a basic GPG setup guide. Feel free to do it differently. If you have any questions, I'm here to help.

Thanks in advance.

**Comment by robinvd** [comment]
small question: using the github .zip download you can always the sure you have the code as is on the release (as long as you trust github), is that not enough?

**Comment by robinvd** [comment]
Thanks for your answer!  If you have any links to these hacks i would love to read about them.

As for this repo, we publish the source and binaries through github ci. So if this is possible to incorporate into this setup i would be open for it

**Comment by NicoHood** [comment]
https://news.ycombinator.com/item?id=14281808

Sorry it was linuxmint, not opensuse:
https://blog.linuxmint.com/?p=2994

I am not sure, as the private key must stay private on your computer, so you should not upload it into any public repository. What does the CI do beside creating a zip? Does it download external dependencies and integrates those into the release? Or does it compile the sources into a binary? Cause if that is not the case, you can simply run Gpgit locally. I've also added github integration, so it is nearly as automated as the Github CI. Since you know your workflow best, maybe it is worth to try in a testing repository?

**Comment by robinvd** [comment]
> as the private key must stay private on your computer, so you should not upload it into any public repository

i would then be stored in github secrets. If done locally we would have to choose someone from the maintainer team who does that everytime, and stores their key safely

**Comment by NicoHood** [comment]
I think a local signing is better, cause if you compromise Github, you also got the key. One of the maintainers should keep the key secure.

**Comment by JojiiOfficial** [comment]
If your threat model is that high, use a distro you trust and which will package it for you, or even better build it yourself. There is always a possibility (even though only a very tiny one) that the code can get compromised when github gets hacked. If you feel better i think its possible to add hash sums or auto signing in automated builds. We are multiple maintainers so someone must be the one signing it. What tells you, the signer doesn't compromise the binary (eg. by accident cause of malware)? Don't get me wrong, you're right with this concern but if you want that step of security, its better you build it yourself or let this be done by a distro you trust. Arch for example has (next to gpg) checksum validation which stores the hashsum of the binary first and when the package gets build, it verifies those hashsums.

**Comment by NicoHood** [comment]
You are right. It is just an additional security mechanism. I am already using Arch, I am a Trusted User/Maintainer. Luckly we have all those mechanisms which other distros do not have. And luckly we also have a good working reproducible build option. I personally do not add packages without signatures (anymore), as I am also responsible for the security of my packages. But you are totally right, there are still not all questions answered and things can always get even better. So that decision is up to you guys, If you decide to add some signatures, let me know :-)

**Comment by slondr** [comment]
Most of the commits are already signed with GPG. I don't see the point of this, beyond trying to advertise your project on other projects

**Comment by NicoHood** [comment]
Adding GPG signatures for the releases is still relevant.

**Comment by SirWindfield** [comment]
I'd be open to add signatures to the CI infrastructure. But I don't see the benefit to be honest. Using the binaries from the CI already means you trust GitHub. The signature doesn't add any value to it. You'd have to store it in their intrastructure as a secret anyway. Might as well just use the unsigned binaries.

Having someone locally sign it puts all trust into them. Which is far less ideal and IMO worse than putting trust into the CI. At least from CI builds you see exactly what steps were run (which can't be said for having someone locally sign them).

**Comment by NicoHood** [comment]
Still an issue
