### ISSUE TITLE
Error compiling on Linux Mint 20

### ISSUE THREAD

**Issue by sysnerd** [Spotifyd/spotifyd#779]
I want to know if I can get some help finding where to put the config file for Spotifyd using Snap. I am unable to compile the application every time I try to compile it normally I get the following below. I just want to get this working in snap if possible :(, please help

hread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-sys-0.1.2/build.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `spotifyd v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installSeycpj

**Comment by robinvd** [comment]
You are missing one or more dependencies, you can find which ones you need at https://github.com/Spotifyd/spotifyd#compiling-from-source

**Comment by sysnerd** [comment]
Hello, thank you for your reply robinvd. I am running Debian and have already pre installed those packages. Running Linux Mint 20. Not sure why these messages are coming up. Make sense that there was an error under libs. Funny enough alsa-lib-devel is on this system. huh, I wish I could figure it out.  I am reading this code and it's making more sense. Will try to figure it out. Thanks robinvd, I just need to read the description a little more.
