### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by shakakibara12** [Spotifyd/spotifyd#786]
hello please help me, i am getting this error message

**```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(49), message: "", key: [] } }', src/config.rs:477:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```**

this is my current config

```
 [global]
 username = username
 password = password
 backend = pulseaudio
 device_name = Manjaro
 bitrate = 160
 cache_path = home/user/.cache/spotifyd
 no_audio_cache = true
 initial_volume = 90
 volume_normalisation = true
 normalisation_pregain = -10
 device_type = computer
```

**Comment by viktor-grunwaldt** [comment]
I have the exact same error, running Manjaro with 5.10 linux.

**Comment by coccovax** [comment]
Same error running on archlinuxarm on Raspberry PI3 B+

**Comment by robinvd** [comment]
please see the pinned issue https://github.com/Spotifyd/spotifyd/issues/765. Im working on a better error message that is not as confusing as this

**Comment by coccovax** [comment]
thanks @robinvd
I updated configuration file with new syntax, but now I have another error message:

`value: Os { code: 20, kind: Other, message: "Not a directory" }', /build/.cargo/registry/src/github.com-1285ae84e5963aae/librespot-core-0.1.1/src/cache.rs:31:49`

that I think it's about cache, but `cache_path` value is set as a string and is valid path.

**Comment by robinvd** [comment]
glad it helped!

as for the new error, there was a similar issue, see https://github.com/Spotifyd/spotifyd/issues/772#issuecomment-762429057, but that was with an invalid path, you could try just commeting it out.

Ill add that panic to my todo list for better error messages haha

**Comment by JojiiOfficial** [comment]
A valid path to a directory or file? Is it relative or absolute? Does it work with cache commented out?

**Comment by spoergsmaal** [comment]
i get the exact same issue as OP on macOS Big Sur 11.1, has anyone been able to fix it?

**Comment by robinvd** [comment]
@spoergsmaal which of the 2 issues are you having?

**Comment by spoergsmaal** [comment]
> 
> 
> @spoergsmaal which of the 2 issues are you having?

the same as OP:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(49), message: "", key: [] } }', src/config.rs:477:67 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by JojiiOfficial** [comment]
@spoergsmaal 
Could you send the config files line 49 (or even better 45-55)?
