### ISSUE TITLE
several questions...

### ISSUE THREAD

**Issue by balbuze** [Spotifyd/spotifyd#79]
Hi!
Thank you for you work! 
I have some questions... Up to now, I'm using librespot. I just compiled spotifyd, it works, but what is the main differences against librespot ? (I saw the volume control etc).
When I use it, I can see with the --no-daemon option : 

> 
22:14:27 [INFO] Request::new: addr=192.168.1.59:50520, "GET /?action=getInfo HTTP/1.1"
22:14:28 [INFO] Loading track "Christine"
22:14:29 [INFO] Request::new: addr=192.168.1.59:50526, "GET /?action=getInfo HTTP/1.1"
22:14:31 [INFO] Track "Christine" loaded
22:14:31 [INFO] Request::new: addr=192.168.1.59:50532, "GET /?action=getInfo HTTP/1.1"
22:14:33 [INFO] Request::new: addr=192.168.1.59:50538, "GET /?action=getInfo HTTP/1.1"
22:14:35 [INFO] Request::new: addr=192.168.1.59:50544, "GET /?action=getInfo HTTP/1.1"
22:14:37 [INFO] Request::new: addr=192.168.1.59:50550, "GET /?action=getInfo HTTP/1.1"
22:14:39 [INFO] Request::new: addr=192.168.1.59:50556, "GET /?action=getInfo HTTP/1.1"
22:14:41 [INFO] Request::new: addr=192.168.1.59:50562, "GET /?action=getInfo HTTP/1.1"
22:14:43 [INFO] Request::new: addr=192.168.1.59:50568, "GET /?action=getInfo HTTP/1.1"
22:14:45 [INFO] Request::new: addr=192.168.1.59:50574, "GET /?action=getInfo HTTP/1.1"

> 
is it the a adress I m supposed to connect to ? It still changing... Or something I missed ?

**Comment by SimonPersson** [comment]
Hi!

> but what is the main differences against librespot ?
Spotifyd is a UNIX daemon written on top of librespot. It can daemonize, log to the syslog, create a PID file, and other things you'd expect from a well behaved UNIX daemon.

You are supposed to run the program and start playing music. Is it not working?

**Comment by balbuze** [comment]
What a quick answer!
It works with no problem!
I wrote a plugin for volumio https://volumio.org using librespot. I'm looking for solution to improve it, by displaying album art , using command buttons directly from Volumio'Ui.

**Comment by SimonPersson** [comment]
Cool! You're idea should be doable using spotifyd and the API's provided by Spotify, such as https://developer.spotify.com/news-stories/2017/04/10/new-endpoints-beta-web-api-connect/.
