### ISSUE TITLE
Timeout in API request causes panic, but spotifyd doesn't exit fully

### ISSUE THREAD

**Issue by iFreilicht** [Spotifyd/spotifyd#793]
**Description**
Spotifyd will randomly crash on my machine. Sometimes during playback, sometimes while paused.
After running `spotifyd --no-daemon`, I managed to catch the error message:

```
Couldn't fetch metadata from spotify: Err(RateLimited(Some(1)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(1)))
Caught panic with message: called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://api.spotify.com/v1/me/player", source: TimedOut }
```

Additionally, spotifyd doesn't exit fully when this happens:

```
$ prep spotifyd # While running
383908
383959
$ prep spotifyd # After crashing
383908
```

I always have to `pkill spotifyd` before starting it again, else Spotify on my phone is not going to detect the new instance.

I am aware the rate limiting is my fault, I have a script to show the current track using `playerctl` and it runs playerctl quite frequently.

**To Reproduce**
1. Start spotifyd
2. Play music through it
3. Wait for crash

**Expected behavior**
I would expect spotifyd to handle timeouts gracefully, and to shut down fully when it crashes.

**Logs**
The log is about 36.5MiB, I compressed and attached it.
[spotifyd.tar.gz](https://github.com/Spotifyd/spotifyd/files/5851007/spotifyd.tar.gz)

**Versions (please complete the following information):**

- OS: Manjaro
- Spotifyd: 0.3.0-1 (acording to `pamac`, `spotifyd --version` just says 0.3.0)

**Comment by robinvd** [comment]
Definitly a bug that should be fixed, thanks for reporting!

**Comment by JojiiOfficial** [comment]
That RateLimit error seems to be interesting too. Is this a known issue?

**Comment by robinvd** [comment]
ive read about ratelimit issues before but not seen the error in a log like this

**Comment by willthong** [comment]
I have exactly the same issue and receive the same error message. I am also using a `playerctl' script to show the current playing track.

Versions:

- OS: Arch Linux
- Spotifyd: 0.3.2

**Comment by iFreilicht** [comment]
@stale It was confirmed and hasn't been fixed yet.

**Comment by adrianomitre** [comment]
I am suffering from same issue both on spotifyd 0.3.2 and on [the most current commit as of this message](https://github.com/Spotifyd/spotifyd/commit/f4909621da43636185f2d2ffe4392178b8d654b6).
