### ISSUE TITLE
config option for shuffle

### ISSUE THREAD

**Issue by SilPan** [Spotifyd/spotifyd#797]
`spotifyd` disables *shuffle* (at least) on every restart.

I usually have *shuffle* turned on.

So it would be cool if `spotifyd` could either preserve the status of if *shuffle* is enabled, or have a config/commandline option to set an initial value if shuffle should be enabled.

From what I have seen documented here [https://developer.spotify.com/documentation/web-api/reference/#endpoint-toggle-shuffle-for-users-playback](https://developer.spotify.com/documentation/web-api/reference/#endpoint-toggle-shuffle-for-users-playback), this should be easy to implement.

I am aware of [#626](https://github.com/Spotifyd/spotifyd/issues/626), but the issue got closed and tagged with *wontfix* due to inactivity, as far as I can see.
It sais something sbout a todo list there?

**Comment by robinvd** [comment]
I see there is currently no option for this on librespot, but it should not be too hard to add

**Comment by jackvstrickland** [comment]
I have created a PR for the above work in librespot: https://github.com/librespot-org/librespot/pull/666

**Comment by robinvd** [comment]
Looks good! Im not involved in librespot so i cant merge/approve it. But when that is merged/released we can add it to spotifyd!

**Comment by sashahilton00** [comment]
Merged.
