### ISSUE TITLE
Import songs from local files

### ISSUE THREAD

**Issue by alex-con** [Spotifyd/spotifyd#799]
**Problem**
I am listening to multiple songs that are not available on spotify so I import them on every device or use the download function. As I can not do that with spotifyd I can not listen to my manually imported songs.

**The feature I request to solve my problem**
I consider to implement an additional option in the configuration file `local_songs_path` where you can provide a path to your local songs.

**Alternative solution**
Another way to solve my problem is implementing a download feature for playlists as spotify is able to download local songs from other devices within the same network.

**Comment by JojiiOfficial** [comment]
How exactly would you select them though? Imagine having a headless raspberry pi setup. How would you select one of these songs your playback?

**Comment by alex-con** [comment]
When there is a local song played spotify sends some information about it: the fact that it is a local song, artist, album, song title and song length in seconds. When starting the daemon you could collect the necessary metadata of all audio files in the given directory with a reference to the song. Now when a local file is played select the song by comparing the provided data with your collected data and play the linked song.
Is this a way to go or am I missing something here?

**Comment by JojiiOfficial** [comment]
I don't know exactly what you mean by "Spotify sends some information about it". It goes all through Spotifys servers, we can't change that. Since librespot is open source, we could implement such a feature in some ways (obv. not through spotifys server though). But we can't display additional songs in the app.

**Comment by alex-con** [comment]
I have got spotifyd on my raspberry pi. So when I use this device to play the music and I am selecting a local song to play with my phone information about that local song are sent to the raspberry. Spotifyd skips the song
`Skipping track <"spotify:local:Lil+Peep:2016+%28EP%29:angeldust:111"> at position [12] of 90`
that is the output I get containing the information mentioned above.

**Comment by alex-con** [comment]
I investigated a bit more, if I just play/click on a local song spotifyd returns `No more tracks left in queue` and stops playing the rest of the queue. But if the next song is played when the current song ends or by skipping the current song manually, it is skipping the song if it is a local song.

**Comment by Johannesd3** [comment]
This might be interesting: https://developer.spotify.com/documentation/general/guides/local-files-spotify-playlists/

**Comment by puyoxyz** [comment]
why wontfix? this is a pretty important feature for me

**Comment by puyoxyz** [comment]
> I don't know exactly what you mean by "Spotify sends some information about it". It goes all through Spotifys servers, we can't change that. Since librespot is open source, we could implement such a feature in some ways (obv. not through spotifys server though). But we can't display additional songs in the app.

[omg look a local file in the official spotify iOS app woooow ](https://user-images.githubusercontent.com/15311104/131776000-0a3b5068-8822-48a6-95a1-177d1e50a66f.png)

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
I think we should rediscuss this
