### ISSUE TITLE
Using notifyd to have some kind of overlay

### ISSUE THREAD

**Issue by hellow554** [Spotifyd/spotifyd#80]
When you typically use some kind of music player you have an [overlay](https://bbs.archlinux.org/viewtopic.php?id=172965) with some information, e.g. album cover, artist and tracktitle. Sometimes you also have buttons for pause, next and previous.

Is there a plan or a chance to have this with spotifyd as well?

**Comment by SimonPersson** [comment]
I have no plan of integrating this in `Spotifyd`, but possibly as a separate project. I think it could be implemented as a separate process using the [Spotify Connect web API](https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/) and the `onstart`/`onstop` handlers. Tell me if you'd like to make an attempt yourself and I'll link it from the README! :)
