### ISSUE TITLE
I don't know what's wrong

### ISSUE THREAD

**Issue by BenLai95** [Spotifyd/spotifyd#803]
┌─(~)───────────────────────────────────────────(benlai@laihongbindeAir:s000)─┐
└─(21:16:28)──> spotifyd --no-daemon                           101 ↵ ──(Mon,Feb01)─┘
Loading config from "/Users/benlai/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(60), message: "", key: [] } }', src/config.rs:477:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mekahell** [comment]
You must use quotes into you config file like this example https://github.com/Spotifyd/spotifyd/blob/master/docs/src/config/File.md. This error is thrown by the TOML parser because quotes are missing.

**Comment by ECon87** [comment]
I get the same error. It used to work fine last week. Now they values have to strings (i.e., quotes needed) or numeric or boolean

**Comment by JojiiOfficial** [comment]
@ECon87 that is because of the last update where we moved the config format to toml. See #765

**Comment by BenLai95** [comment]
fixed! thanks
