### ISSUE TITLE
Spotifyd crashes when run on FreeBSD

### ISSUE THREAD

**Issue by daemonspudguy** [Spotifyd/spotifyd#804]
Here is the output:
`Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }`
What does the mean? How do I resolve this?
EDIT: it appears to be related to Spotify Connect.

**Comment by hotratx** [comment]
In the file spotifyd.conf, try change username from password api to email to login.

**Comment by daemonspudguy** [comment]
What? I am using my email.

**Comment by hotratx** [comment]
Try enclose this parameters in apostrophe
  -username = "David" 
  -password = "123"
  -backend = "pulseaudio" 
  -device_name = "90"
  -cache_path = "cache_directory"
  -initial_volume = "80"
  -device_type = "computer"

**Comment by daemonspudguy** [comment]
That didn't do a damn thing.

**Comment by JojiiOfficial** [comment]
Spotifyd creates an open port 1234. The error message you get says that this port is already being used. Either you already have a spotifyd instance running, or something else is already listening on port 1234. Check for open ports on your system and for spotifyd already running, or change the port used by spotifyd using `zeroconf_port = <FREE PORT>` in the configuration file.

**Comment by daemonspudguy** [comment]
I've tried multiple ports, same result.

**Comment by daemonspudguy** [comment]
I figured it out! You need to disable avahi.

**Comment by Johannesd3** [comment]
If you don't want to disable avahi, try to add the feature flag `with-dns-sd` to librespot in the `Cargo.toml` file.

Librespot will interfere with Avahi on Linux as well, but unfortunately there's no error message and it goes unnoticed.
