### ISSUE TITLE
Gapless support

### ISSUE THREAD

**Issue by TonioRoffo** [Spotifyd/spotifyd#85]
There seems to be a small gap between tracks (~0.3 seconds)

Are there any plans to remove this in the future and support gapless playback?

**Comment by SimonPersson** [comment]
I agree that it's a bit frustrated, especially on live albums... I have no plans to work on it right now, but I can try to help you out if you want to attempt it yourself and have any questions.

**Comment by acegallagher** [comment]
I'd be interested in picking this up, has there been any other progress made on it?

**Comment by SimonPersson** [comment]
@acegallagher - It appears that some progress is being made, see https://github.com/librespot-org/librespot/issues/21.

**Comment by mwieler** [comment]
[lIbrespot now has gapless play ](https://github.com/librespot-org/librespot/pull/430). If it hasn't already been done, let me know how I can help spotifyd use the updated version of librespot, so its users may also benefit.

Thanks to the spotifyd maintainers & community for making such a fantastic product available for us to use.

**Comment by JockeTF** [comment]
I created a [branch with the bare minimum changes](https://github.com/JockeTF/spotifyd/tree/gapless-minimal) for this to build.

It's mainly for those who don't want to wait for a proper release, so don't expect anything fancy!

**Comment by edio** [comment]
@JockeTF thanks. FYI, there's a PR alredy that provides gapless. I tried it and it works flawlessly.
I think it's worth linking it to this issue, so people could build spotifyd for themselves
#596

**Comment by JockeTF** [comment]
I believe this is very much still relevant, Mr Bot!
