### ISSUE TITLE
Alsa errors but sound works

### ISSUE THREAD

**Issue by sebastianst** [Spotifyd/spotifyd#87]
Even though sound works, the logs show the following errors:
```
19:09:37 [INFO] Using alsa sink
ALSA lib conf.c:4884:(parse_args) Unknown parameter 1
ALSA lib conf.c:5017:(snd_config_expand) Parse arguments error: No such file or directory
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:HDMI,3
19:09:37 [ERROR] Couldn't set volume of alsa device.
```
Relevant parts from config:
```
backend = alsa
device = hw:HDMI,3 # Or change according to `aplay -L` or `aplay -l`
volume-control = alsa # or softvol
```
Alsa devices:
```
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Generic [HD-Audio Generic], device 0: ALC671 Analog [ALC671 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Generic [HD-Audio Generic], device 1: ALC671 Digital [ALC671 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
Alsa PCMs:
```
# aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
hdmi:CARD=HDMI,DEV=0
    HDA ATI HDMI, HDMI 0
    HDMI Audio Output
hdmi:CARD=HDMI,DEV=1
    HDA ATI HDMI, HDMI 1
    HDMI Audio Output
default:CARD=Generic
    HD-Audio Generic, ALC671 Analog
    Default Audio Device
sysdefault:CARD=Generic
    HD-Audio Generic, ALC671 Analog
    Default Audio Device
front:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    Front speakers
surround21:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Generic,DEV=0
    HD-Audio Generic, ALC671 Digital
    IEC958 (S/PDIF) Digital Audio Output
```

Now comes the weird part. If I change the config to read `device = hw:HDMI`, I *don't* get the `ALSA lib` errors, but sound *doesn't* work.

**Comment by sebastianst** [comment]
Could it be that it makes sense to introduce a second configuration variable `control_device` that sets the alsa control device, which generally is not the same as the out put device. In my case, I think it would need to be set to `control_device = hw:HDMI`.

**Comment by SimonPersson** [comment]
I have to say that I'm no ALSA expert. You might be right in that we should add a `control_device` setting, although you would have to look into it yourself as I don't have any hardware with multiple audio interfaces to test it on really. Just out of curiosity, what happens if you leave the device out of the config file? You should get your ALSA default I think.

**Comment by wvangeit** [comment]
I had a similar issue, but setting volume-control = softvol solved the issue for me

**Comment by eisnerd** [comment]
I had this same problem because I'm using alsaeq. I probably could have worked around it by sorting out my asoundrc, but I was struggling with that. I've added a `control` config option for the control/mixer device. I also found that you have to specify the correct case for the `mixer` option. For example, I got an error when specifying `master` instead of `Master`.

**Comment by SimonPersson** [comment]
Thanks @eisnerd, I merged your PR. I'll close the ticket, feel free to reopen if the problem persists.

**Comment by goyometeojorito** [comment]
And can you know in what file you have to configure that?

**Comment by Cherkah** [comment]
I had a similar issue,  when i check 
`systemctl status --user spotifid
sept. 28 18:24:06 HOST spotifyd[11114]: ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL PCH
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [ERROR] Couldn't read volume from alsa device with name "PCH".
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [INFO] Connecting to AP "gew1-accesspoint-a-07kf.ap.spotify.com:443"
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [INFO] Authenticated as "SCRED" !
sept. 28 18:24:06 HOST spotifyd[11114]: ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL PCH
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [ERROR] Couldn't read volume from alsa device with name "PCH".
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [INFO] Using alsa sink
sept. 28 18:24:06 HOST spotifyd[11114]: ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL PCH
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [ERROR] Couldn't set volume: Error("snd_mixer_attach", Sys(ENOENT))
sept. 28 18:24:06 HOST spotifyd[11114]: 16:24:06 [INFO] Country: "FR"`

but setting device = sysdefault solved the issue for me
