### ISSUE TITLE
Spotifyd doesn't start automatically with DBus support enabled.

### ISSUE THREAD

**Issue by NNEU-1** [Spotifyd/spotifyd#895]
**Description**
Hi, 
I've got a little issue with Spotifyd. 
I used to run it in the default configuration without an extra compilation flags.
It was set up to show as the machine name in the .service file 
ExecStart=/usr/bin/spotifyd --no-daemon --device-name "%H"

after enabling DBus support by recompiling with the according flags and settings in the .conf file, the device will still show in Spotify, but no longer be able to connect.

if I start Spotifyd by typing it into the command prompt, a second device shows up in Spotify as "Spotifyd@{HOSTNAME}".
I can connect to that device and use the DBus successfully.

Any ideas what causes this issue and how it can be fixed ?

Thanks !

</details>

**Compilation flags** 
- [x] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Yocto Zeus
- Spotifyd: 0.3.0

**Comment by robinvd** [comment]
What is the hostname? Sometimes spaces or other special characters mess things up

**Comment by NNEU-1** [comment]
That’s not the issue. The host name only contains upper case letters and no special characters or spaces.
Also, that wouldn’t explain the difference between the behavior with or without the DBus option enabled.

**Comment by NNEU-1** [comment]
I have observed the issue more in-depth, and perhaps my original description of the problem is a bit misleading.

The following configuration:
- Compiled with DBus support 
- ExecStart=/usr/bin/spotifyd --no-daemon --device-name "%H"
  in the .service file

exhibits the following behaviour:
- service starts properly 
- device shows as Hostname in Spotify (as intended)
- Spotify cannot connect to the device

then, if I start Spotifyd in the terminal, it will launch as another device. 

So perhaps this is not a "doesn't autostart" issue, but a "doesn't connect" one.
Strangely though, it does seem to be related to the addition of the DBus option.

**Comment by NNEU-1** [comment]
Hello again,
I tried to install Spotifyd on Ubuntu to see if the problem also occurs there as well.

Again, installed with the DBus_mpris feature. 

The problem is similar to what I experienced earlier on the yocto machine.

Spotifyd autostarts and appears as connect client. However, there is no music playback and no possibility to interact with DBus.

`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
`
Then again, as in yocto, if I start Spotifyd in the terminal, I can see a second connect client which is fully functional with DBus and playback.

I hope this makes it easier to reproduce and hopefully get some suggestions.
Thanks !

**Comment by NNEU-1** [comment]
I have now discovered that the issue is fixed by running spotifyd as a user service.
However, I would prefer it to run as a system service so that no login is required for the service to start.

Again, any kind of feedback would be highly appreciated.

**Comment by robinvd** [comment]
as what user is the system service started? and can you try starting it from that user

**Comment by NNEU-1** [comment]
originally I had no user specified in the .service file. 
It was just like the one offered here on Github, with the addition of the hostname attribute. 

I also tried adding "User=root", with no success.

It only worked once I made it a user service (user is root).
I removed the audio and network targets and moved the service to /usr/lib/systemd/user/ (instead of /lib/systemd/system/)

**Comment by mativ123** [comment]
The spotifyd dbus service goes by another name which you can find by running this command while spotifyd is running:
```
dbus-send --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```
The command gets all available dbus services
