### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by zachriggle** [Spotifyd/spotifyd#906]
**Description**

Spotifyd crashes immediately while parsing my config file.

```
$ spotifyd --no-daemon
Loading config from "/Users/zachriggle/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(60), message: "", key: [] } }', src/config.rs:477:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

I have attached my exact config: [spotifyd.conf.zip](https://github.com/Spotifyd/spotifyd/files/6064700/spotifyd.conf.zip)

```
zip spotifyd.conf.zip /Users/zachriggle/.config/spotifyd/spotifyd.conf
```

But it is here for convenience

```ini
$ cat /Users/zachriggle/.config/spotifyd/spotifyd.conf
[global]
# Fill this in with your Spotify login.
username = zachriggle

# You'll be using the macOS keychain to specify your password.
use_keyring = true

# How this machine shows up in Spotify Connect.
device_name = "loaner"
device_type = "computer"

# This is the default location of Spotify's cache, so just replace LOGIN_NAME
# with your macOS login name (type `whoami` at a Terminal window).
cache_path = "/Users/zachriggle/Library/Application Support/Spotify/PersistentCache/Storage"
no_audio_cache = false

# Various playback options. Tweak these if Spotify is too quiet.
bitrate = 320
volume_normalisation = true
normalisation_pregain = -10

# These need to be set, but don't need to be changed.
backend = "rodio"
mixer = "PCM"
volume_controller = "softvol"
zeroconf_port = 1234
```

**Expected behavior**

Should not crash.

**Logs**
<details><summary>Click to show logs</summary>
<pre>
$ RUST_BACKTRACE=full spotifyd --no-daemon --verbose
Loading config from "/Users/zachriggle/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(2), col: 11, at: Some(60), message: "", key: [] } }', src/config.rs:477:67
stack backtrace:
   0:        0x10375b31e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3b6ed74a60c4de30
   1:        0x1037961ae - core::fmt::write::h72dd6ddbc116ef3c
   2:        0x10375a70a - std::io::Write::write_fmt::h033803ce14d847cc
   3:        0x1037716f9 - std::panicking::default_hook::{{closure}}::h040276b51a1a4749
   4:        0x10377141e - std::panicking::default_hook::h2a43ed83163cecb9
   5:        0x103771c8a - std::panicking::rust_panic_with_hook::h15f3dba6c099e04e
   6:        0x10375b9d5 - std::panicking::begin_panic_handler::{{closure}}::h33fb39231ad9a88d
   7:        0x10375b498 - std::sys_common::backtrace::__rust_end_short_backtrace::hd5ec6f84e4df1d34
   8:        0x103771803 - _rust_begin_unwind
   9:        0x1037ae5af - core::panicking::panic_fmt::h7889f3b8e7c118f7
  10:        0x1037ae115 - core::result::unwrap_failed::h095cbf11d4909cd8
  11:        0x1032d6d8a - spotifyd::config::CliConfig::load_config_file_values::h479f137e7275a99c
  12:        0x1032f102c - spotifyd::main::h054ba173f7d9cf7b
  13:        0x1032bbefa - std::sys_common::backtrace::__rust_begin_short_backtrace::hed7ed1a7f6d0ec35
  14:        0x1032e2c0c - std::rt::lang_start::{{closure}}::h9fec380ea0ffa835
  15:        0x10377707e - std::rt::lang_start_internal::h1881ffd15d3416e4
  16:        0x1032f1759 - _main
</pre>
</details>

**Versions (please complete the following information):**

```
$ spotifyd --version
spotifyd 0.3.0

$ sw_vers
ProductName:	macOS
ProductVersion:	11.3
BuildVersion:	20E5186d
```

**Comment by JojiiOfficial** [comment]
Maybe wrapping your username with double quotes works?

**Comment by celeryclub** [comment]
For future reference you can use this tool to validate your config: https://www.toml-lint.com/.
