### ISSUE TITLE
Song information for `onstart` and `onstop` commands

### ISSUE THREAD

**Issue by toxinu** [Spotifyd/spotifyd#91]
Is it possible to retrieve song information for to hook commands?

**Comment by SimonPersson** [comment]
It is not possible yet, but I have a pull request in review in the librespot project which will make it possible.

**Comment by SimonPersson** [comment]
The `onstart` and `onstop` hooks have been replaced with `onevent`. When the event program runs it receives an environment variable `TRACK_ID`, which is a Spotify track id. I plan to expose the metadata directly in ticket #61, but for now you can use the track id to look up metadata using the Spotify API.
