### ISSUE TITLE
No dbus PropertiesChanged event

### ISSUE THREAD

**Issue by NNEU-1** [Spotifyd/spotifyd#910]
Hi,

I just noticed that I am not getting any PropertiesChanged events on the dbus from Spotifyd.
I know that this was already an issue with regards to metadata, but I am not getting any events at all.

I am using version 0.3.0. Sending dbus commands to Spotify works fine. 

any help would be greatly appreciated !

**Comment by NNEU-1** [comment]
Actually, it does seem to be doing something on the dbus, but now what's expected.
Here is the message from the dbus-monitor if an event occurs:

`mc.1614800695.512200.1.:1.25.org.freedesktop.DBus./org/freedesktop/DBus.org.freedesktop.DBus.Hello
mr.1614800695.512630.1.org.freedesktop.DBus.:1.25.1
sig.1614800695.512938.38.org.freedesktop.DBus.<none>./org/freedesktop/DBus.org.freedesktop.DBus.NameOwnerChanged
sig.1614800695.513213.2.org.freedesktop.DBus.:1.25./org/freedesktop/DBus.org.freedesktop.DBus.NameAcquired
mc.1614800695.515761.2.:1.25.org.freedesktop.DBus./org/freedesktop/DBus.org.freedesktop.DBus.GetNameOwner
err.1614800695.516116.3.org.freedesktop.DBus.:1.25.2
mc.1614800695.518771.3.:1.25.org.freedesktop.DBus./org/freedesktop/DBus.org.freedesktop.DBus.StartServiceByName
err.1614800695.519127.4.org.freedesktop.DBus.:1.25.3
sig.1614800695.603915.39.org.freedesktop.DBus.:1.25./org/freedesktop/DBus.org.freedesktop.DBus.NameLost
sig.1614800695.604067.40.org.freedesktop.DBus.<none>./org/freedesktop/DBus.org.freedesktop.DBus.NameOwnerChanged`

**Comment by robinvd** [comment]
I think this is a duplicate of https://github.com/Spotifyd/spotifyd/issues/668

**Comment by Maik1999** [comment]
I opened #618 a while ago but it gone stale. Should be the same problem.
Also there exists the WIP PR #575.

**Comment by NNEU-1** [comment]
> Also there exists the WIP PR #575.

Unfortunately I couldn't try it. 
Cargo Bitbake is spitting out an error when I try to create a recipe for it. 

`No package.homepage set in your Cargo.toml, trying package.repository
Unable to determine git repo for this project
thread 'main' panicked at 'byte index 10 is out of bounds of ``', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/str/mod.rs:2721:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I vaguely remember having had this problem before, but I can't remember how I fixed it.  

It that version does indeed work as it's supposed to, why didn't it make it into the master ?

**Comment by coxackie** [comment]
This is at the moment the only annoying part of the spotifyd implementation for me. Seems quite important, so not sure why it has not been chased after.

**Comment by eladyn** [comment]
I assume that this issue can be closed now :)

**Comment by NNEU-1** [comment]
Fixed as of 11. March 22
