### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by georgefst** [Spotifyd/spotifyd#911]
The [v0.3.1 binaries](https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.1) report:
```
$ ./spotifyd -V
spotifyd 0.3.0
```

And indeed, it seems the version [hasn't been bumped](https://github.com/Spotifyd/spotifyd/blob/1da300cdaf5c5f47df6b4a32eb81041d9422bf0f/Cargo.toml#L8).

Presumably it's an accident that the builds were triggered before #909 has been merged.

**Comment by JojiiOfficial** [comment]
Right. I forgot that the Cargo.toml needs to be updated before a new release should be bumped, my bad. Neither did I see that PR. The release I bumped had another approach, which was to finally fix the ov_callback issue #719. I think we should delete that release and merge #909 with the master branch. 

@Spotifyd/maintainers @SirWindfield What do you think?

**Comment by SirWindfield** [comment]
Hm. Not sure if it is a good idea to delete already published stuff, even if it is wrong, you never know who depends on it once it's online. Maybe editing the release with a [yanked] in the title and just publishing 0.3.2 instead might be a better idea.

**Comment by JojiiOfficial** [comment]
Sounds good. Should I make a PR to change the Cargo.toml's version to 0.3.2 or will you change it?

**Comment by SirWindfield** [comment]
Would be nice if you could do it! :)

**Comment by JojiiOfficial** [comment]
Sure!

**Comment by tomodachi** [comment]
Nice  to see This was already reported, just noticed myself :)

Would also be nice if the release was tagged in git. The latest version tagged is  0.3.0

**Comment by JojiiOfficial** [comment]
The release v0.3.1 should be tagged, I don't know where you saw something else.

**Comment by JojiiOfficial** [comment]
A [new version](https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.2) has been created!
