### ISSUE TITLE
Documentation Clarifications

### ISSUE THREAD

**Issue by jtemple967** [Spotifyd/spotifyd#918]
**Is your feature request related to a problem? Please describe.**
I was able to set up the spotifyd daemon on my raspberry pi but there were a few steps that I had to figure out via trial and error.

**Describe the solution you'd like**
There are 2 areas in the documentation for configuring spotifyd that need clarification:
1. In the "Config File" section it mentions updating the "username" with your Spotify user.  Note that this is not the user name as it appears in the Spotfiy client or the email that you use to log in to Spotify, it is the user name displayed in the account dashboard within Spotify and is (at least in my case) a long string of letters and numbers.  I tried the first two without success and tried the user name in the dashboard and it worked.
2. In the "Config File" section it also needs to be mentioned that the user will need to run "aplay -L" command and use one of the values listed in the config file surrounded by double quotes for the "device" option.  In my example I ran "aplay -L" and changed the line to:
device = "default"

**Describe alternatives you've considered**
N/A

**Comment by JojiiOfficial** [comment]
1. What exactly didn't work out the first two trials? Did it say "BadCredentials"? For me it works with both, email and that long random string aka username. Also I can't find that passage you're talking about in the documentation.
2. Which documentation are you referring to? Giving a quick peak into the [example config](https://spotifyd.github.io/spotifyd/config/File.html), it says you need to run `aplay -L`.

**Comment by jtemple967** [comment]
1. Well I'm pretty sure it only worked with the long random string, not with the email. Let me try that again and make sure I didn't have my wires crossed.   I should have also included a link to the specific part of the documentation:
https://spotifyd.github.io/spotifyd/installation/Raspberry-Pi.html#config-file
2. Use the same link provided above for the section I'm referring to.  And you're correct, it does say "# Given by `aplay -L`" in the example config but I honestly assumed that "alsa_audio_device" was an acceptable default value since the documentation only says: 
_Input the following data. Change the username, password, device_name, and the bitrate._
and doesn't mention needing to change the device as well.  

Again, these are very minor things, just trying to help someone else save a few minutes getting this configured.  I'm listening to Spotify right now as I type this on my RPi.  I have it hooked up to a small Kinter Tripath amp and 2 vintage JBL speakers.  Nice way to add some ambient music to the work from home office!

I'm actually buying an older RPi tomorrow from someone so I can use my RPi 4 for other programming projects!
![PXL_20210317_175032428](https://user-images.githubusercontent.com/1199892/111514443-bf690980-871f-11eb-86a6-8c4ca137bbb1.jpg)

**Comment by jtemple967** [comment]
Just confirmed that using the Spotify user id shown in the application does indeed work. I must have done something wrong when I tried it originally.
