### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by Condorello** [Spotifyd/spotifyd#92]
Hi, i'm trying to run spotifyd on a pure debian machine using latest compiled binary.
It starts and i can see the the player in spotify connect, anyway when i start to stream to this speaker the daemon crash with:

  `16:37:16 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"`

Here my config file (i want to output to pipe @ /media/sata_disk/Musica/spotify):

`[global]
username = USER
password = PASSWORD
backend = pipe
device = /media/sata_disk/Musica/spotify
volume-control = softvol
onstart = command_run_on_playback_start
onstop = command_run_on_playback_stop
device_name = AltecLansing
bitrate = 320
cache = /tmp > /dev/null 2>&1`

P.S. the same config works fine with pure librespot on raspberry, my i want to manage this on my debian server if possible... thanks in advace for your kind support and your great works!

**Comment by SimonPersson** [comment]
@Condorello - Do you really have `onstart = command_run_on_playback_start` in there? That should probably be removed, unless you actually have a program named like that installed?

**Comment by SimonPersson** [comment]
I'll close this for now. Feek free to reopen if the issue persists using the latest version once you have fixed the config.

**Comment by thegreyfellow** [comment]
Hi I'm not sure if I should open a new issue but I think I'm having the same problem here, here is the logs:

```
➜  ~ RUST_BACKTRACE=1 spotifyd --no-daemon
20:21:52 [INFO] Loading config from "/Users/mac/.config/spotifyd/spotifyd.conf"
20:21:52 [INFO] Using software volume controller.
20:21:52 [WARN] Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
20:21:52 [INFO] Connecting to AP "gew1-accesspoint-a-kbvb.ap.spotify.com:443"
20:21:53 [INFO] Authenticated as "<USERNAME>" !
20:21:53 [INFO] Country: "US"
20:21:53 [ERROR] Caught panic with message: Could not find device
20:22:03 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
20:22:03 [ERROR] Player thread panicked!
```

I am using [spotify-tui](https://github.com/Rigellute/spotify-tui), which works perfectly with Spotify Desktop app, I am on OSX, using this config:

```
# ~/.config/spotifyd/spotifyd.conf
[global]
username = <USERNAME>
password = <PASSWORD>
backend = portaudio                                      # run `spotifyd --help` for possible values
device = alsa                               # run `aplay -L` for possible values
mixer = PCM
volume_controller = alsa                                    # or alsa_linear, or softvol
device_name = mac             # must not contain spaces
bitrate = 320                                            # or 96, or 320
cache_path = cache_directory
no_audio_cache = true                                    # use credentials-only caching
volume_normalisation = true
normalisation_pregain = -10
```

**Scenario**: 
- run `$ RUST_BACKTRACE=1 spotifyd --no-daemon`
- run `$ spt # spotify-tui`
- then spotifyd crashes instatly right after I try to start a song.

Any help would be appreciated 🙏

**Comment by SirWindfield** [comment]
remove the `device = alsa` line in your config and you should be gucci :D

**Comment by thegreyfellow** [comment]
Thanks a lot @SirWindfield you're the man, and I think this should be added either here or/and in Spotify-tui Readme, thanks again 👍

**Comment by SirWindfield** [comment]
A rename to alsa_device, alsa_mixer etc would probably be the best idea :)
