### ISSUE TITLE
vim ~ / .config / spotifyd / spotifyd.conf

### ISSUE THREAD

**Issue by TonyDJ59** [Spotifyd/spotifyd#923]
**Description**

**To Reproduce**

**Expected behavior**

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [x] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: 
- Spotifyd: 
- cargo:

**Comment by JojiiOfficial** [comment]
Could you please provide more information about the "bug"?

**Comment by JojiiOfficial** [comment]
Closing: Not an issue / No info provided.
