### ISSUE TITLE
Spotifyd is not showing up on any of the spotify devices

### ISSUE THREAD

**Issue by Xanaxus** [Spotifyd/spotifyd#926]
**Description**

Installed the spotifyd and SPT but Spotifyd is not showing up on any of the spotify devices
---
**To Reproduce**

---
**Expected behavior**

Need to be registered as a device
**Logs**
<details><summary>Click to show logs</summary>
spotifyd --no-daemon --verbose
Loading config from "/home/iva/.config/spotifyd/spotifyd.conf"

CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, use_mpris: Some(true), on_song_change_hook: Some("command_to_run_on_playback_events"), cache_path: Some("/home/ivan/.cache/spotifyd"), no-audio-cache: true, backend: Some(PulseAudio), volume_controller: Some(Alsa), device: Some("alsa_audio_device"), control: Some("alsa_audio_device"), mixer: Some("PCM"), device_name: Some("I"), bitrate: Some(Bitrate160), initial_volume: Some("90"), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: Some(1234), proxy: Some("http://proxy.example.org:8080"), device_type: Some(Computer) } }
Found user shell: Some("/bin/fish")
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=4
registering with poller
Using alsa volume controller.
starting background reactor
ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL alsa_audio_device
Couldn't read volume from alsa device with name "alsa_audio_device".
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:1234
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
adding I/O source: 8388610
registering with poller
loop process - 1 events, 0.000s
event Writable Token(8388610)
loop process - 1 events, 0.000s
adding I/O source: 12582915
registering with poller
event Writable Token(12582915)
loop process - 1 events, 0.000s
park; waiting for idle connection: "http://apresolve.spotify.com"
Http::connect("http://proxy.example.org:8080/")
consuming notification queue
resolving host="proxy.example.org", port=8080
scheduling Read for: 0
found interface Interface { name: "wlo1", addr: V4(Ifv4Addr { ip: 192.168.0.102, netmask: 255.255.255.0, broadcast: Some(192.168.0.255) }) }
scheduling Read for: 1
sending packet to 224.0.0.251:5353
found interface Interface { name: "wlo1", addr: V4(Ifv4Addr { ip: 192.168.0.102, netmask: 255.255.255.0, broadcast: Some(192.168.0.255) }) }
scheduling Read for: 2
sending packet to [ff02::fb]:5353
scheduling Read for: 3
loop poll - 1.49151ms
loop time - Instant { tv_sec: 27236, tv_nsec: 168565984 }
event Writable Token(4194305)
loop process - 1 events, 0.000s
loop process, 291.685µs
event Writable Token(8388610)
loop process - 1 events, 0.000s
loop poll - 32.772259ms
loop time - Instant { tv_sec: 27236, tv_nsec: 201651168 }
loop process, 102.431µs
Failed to resolve Access Point: HTTP error
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
Using proxy "http://proxy.example.org:8080/"
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
dropping I/O source: 3

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.10.23-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
- Spotifyd: spotifyd 0.3.2

- cargo: cargo 1.50.0

**Comment by robinvd** [comment]
from your logs `Using proxy "http://proxy.example.org:8080/"` i dont think that is a valid proxy

**Comment by Xanaxus** [comment]
I changed the proxy to the same used by the Spotify-tui : ```http://localhost:8888/callback```
<details>
<summary>My Config</summary>

# A command that gets executed and can be used to
# retrieve your password.
# The command should return the password on stdout.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
# password_cmd = "command_that_writes_password_to_stdout"

# If set to true, `spotifyd` tries to look up your
# password in the system's password storage.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
# use_keyring = true

#
# If set to true, `spotifyd` tries to bind to the session dbus
# and expose MPRIS controls. When running headless, without a dbus session,
# then set this to false to avoid binding errors
#
use_mpris = true

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "pulseaudio"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
device = "alsa_audio_device"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
control = "alsa_audio_device"  # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS

# A command that gets executed in your shell after each song changes.
on_song_change_hook = "command_to_run_on_playback_events"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name ="Ivan"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 160

# The directory used to cache audio data. This setting can save
# a lot of bandwidth when activated, as it will avoid re-downloading
# audio files when replaying them.
#
# Note: The file path does not get expanded. Environment variables and
# shell placeholders like $HOME or ~ don't work!
cache_path = "/home/ivan/.cache/spotifyd"

# If set to true, audio data does NOT get cached.
no_audio_cache = true

# Volume on startup between 0 and 100
# NOTE: This variable's type will change in v0.4, to a number (instead of string)
initial_volume = "90"

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 1234

# The proxy `spotifyd` will use to connect to spotify.
proxy = "http://localhost:8888/callback"

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, t_v,
# a_v_r (Audio/Video Receiver), s_t_b (Set-Top Box), and audio_dongle.
device_type = "computer"
</details>

---

Should I also change the  `device` as on running `aplay -L` I was not able to find `alsa`
<details>
<summary> output of aplay -L </summary>

null
    Discard all samples (playback) or generate zero samples (capture)
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
speex
    Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
default
    Default ALSA Output (currently PulseAudio Sound Server)
sysdefault:CARD=PCH
    HDA Intel PCH, ALC295 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    Front output / input
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
hdmi:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 3
    HDMI Audio Output
hdmi:CARD=PCH,DEV=4
    HDA Intel PCH, HDMI 4
    HDMI Audio Output
usbstream:CARD=PCH
    HDA Intel PCH
    USB Stream Output
</details>

**Comment by eladyn** [comment]
Hi!

You probably won't need anything set in the `proxy`-setting, just comment it out or remove it from the file. A proxy would only be necessary if you can't (or don't want to) directly access spotify.

Hope this helps!

(If you put your configs / logs into a [fenced codeblock](https://www.markdownguide.org/extended-syntax#fenced-code-blocks), they would be much more readable :grin:)

**Comment by Xanaxus** [comment]
Hey it works!!!! now and sorry for not putting the codeblock my bad
