### ISSUE TITLE
Unable to install spotifyd on new M1 Mac

### ISSUE THREAD

**Issue by v-za** [Spotifyd/spotifyd#927]
Unable to install spotifyd on Mac

`brew install spotifyd
Error: spotifyd: no bottle available!
You can try to install from source with:
  brew install --build-from-source spotifyd
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
`

**Comment by robinvd** [comment]
on https://github.com/Spotifyd/spotifyd/issues/768 is someone who successfully builds it on m1 macs. I personally dont know anything about brew, but building from source should work!
