### ISSUE TITLE
crashes immediately on startup if `credentials.json` is not valid JSON

### ISSUE THREAD

**Issue by dmcpton** [Spotifyd/spotifyd#928]
**Description**
Suddenly at some point in this afternoon spotifyd went from running perfectly, to crashing immediately on startup.

**To Reproduce**
spotifyd --verbose --no-daemon

**Expected behavior**
spotifyd starts up and becomes available as a device in Spotify Connect

**Logs**
<details><summary>Click to show logs</summary>

```
Loading config from "/home/$(whoami)/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, use_mpris: None, on_song_change_hook: None, cache_path: Some("cache_directory"), no-audio-cache: true, backend: Some(Alsa), volume_controller: Some(Alsa), device: Some("default"), control: Some("default"), mixer: Some("PCM"), device_name: Some("dmc-laptop-daemon"), bitrate: Some(Bitrate160), initial_volume: Some("90"), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: Some(5907), proxy: None, device_type: Some(Computer) } }
Found user shell: Some("/bin/bash")
No proxy specified
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
registering with poller
build; num-workers=8
registering with poller
Using alsa volume controller.
starting background reactor
Couldn't read volume from alsa device with name "default".
adding I/O source: 0
registering with poller
Zeroconf server listening on 0.0.0.0:5907
adding I/O source: 4194305
registering with poller
event Writable Token(4194305)
adding I/O source: 8388610
registering with poller
loop process - 1 events, 0.000s
event Writable Token(8388610)
loop process - 1 events, 0.000s
PANIC: Shutting down spotifyd. Error message: called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
  -> transitioned to shutdown
  -> shutting down workers
deregistering handle with poller
dropping I/O source: 0
deregistering handle with poller
dropping I/O source: 1
deregistering handle with poller
dropping I/O source: 2
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Pop!_OS (Ubuntu) 20.04
- Spotifyd: 82bc875efc4e1b2e0e1c2e489e3dd4f2e6a5b97b
- cargo: cargo 1.51.0 (43b129a20 2021-03-16)

**Additional context**
This might have happened while my drive was out of space, I'm not sure (been having an issue with excessive kernel logs filling up my disk that I am ignoring because I can't afford to break my machine by accident right now). Also, right around the same time it crashed (music stopped), I went to open.spotify.com and got no response (I forget the exact issue, might have been no internet), but that problem went away right after.

I'm happy to look into this myself, I just need pointers on where to look. I tried running `grep "EOF while parsing a value" -r -C 10 src/` but that didn't give me anything.

**Comment by dmcpton** [comment]
Well, I think I just found the issue totally by chance. I stumbled into `~/cache_directory` (I really should have changed that from the default config, but oh well), where I noticed `credentials.json`. I ran `cat credentials.json` on a hunch, and sure enough -- no content, as if I had merely run `touch credentials.json`. I then just run `rm credentials.json` and tried running spotifyd again -- sure enough, problem solved!

I still think there is a bug worth fixing here, but I'm not sure whether it's the fact that somehow overwrote credentials.json to be an empty file, or if it's not handling an empty `credentials.json` file gracefully (possibly both). A quick google search suggests that `serde` is trying to deserialize this as JSON, but panicking because it's an empty file. I'd be interested in addressing this (I'm learning Rust right now), but I just need pointers on where to get started.

**Comment by dmcpton** [comment]
Ah okay, found the issue. The problem is actually in librespot, not spotifyd. I'm not sure what the protocol for this sort of thing; should I close this issue?

Specifically, the problem is in the implementation of the `Credentials::from_reader` function in `librespot-core-0.1.5`.

spotifyd calls librespot's `Cache::credentials` function with the cache from the config here: https://github.com/Spotifyd/spotifyd/blob/82bc875efc4e1b2e0e1c2e489e3dd4f2e6a5b97b/src/setup.rs#L125
which then calls `Credentials::from_file`, which then calls `Credentials::from_reader`, which contains the problematic line:
```rust
serde_json::from_str(&contents).unwrap()
```

Reading their repo, it looks like they've done a bunch of work to do better error handling, at least on the dev branch, I can't figure out if that's made it into the current version. Regardless, updating the librespot dependency will fix the problem, either now or in the next version.

**Comment by robinvd** [comment]
Thanks for the issue (and the solution). We can keep the issue open until we upgrade to the newer (fixed) version i think
