### ISSUE TITLE
Make alsa mixer name configureable

### ISSUE THREAD

**Issue by empi89** [Spotifyd/spotifyd#93]
For my system the alsa mixer is "PCM" and not "Master", thus with mixer control "alsa" I always got this error:

`[ERROR] Couldn't set volume of alsa device.`

I have fixed this by changing the mixer name in 
https://github.com/Spotifyd/spotifyd/blob/master/src/alsa_mixer.rs#L14
and 
https://github.com/Spotifyd/spotifyd/blob/master/src/alsa_mixer.rs#L42
and compiled the source code again.

However it would make things easier to have this configureable.

Thanks for this nice piece of software!

**Comment by SimonPersson** [comment]
Fixed in latest commit! :)
