### ISSUE TITLE
can't see a machine running spotifyd on my "Duo account"

### ISSUE THREAD

**Issue by alembiq** [Spotifyd/spotifyd#938]
**Is your feature request related to a problem? Please describe.**
Im running spotifyd on my router which is used to play music in my kitchen & I have a Spotify Duo account.
Before when using RPI and [raspotify](https://github.com/dtcooper/raspotify), both my and my GF (the other account on my Duo subscription) were seeing the RPI as a speaker in the "devices to connect and listen on".

Both raspotify and spotifyd are configured to use my account, but both accounts are linked by the Duo subsription.

I would love to have the same feature here, for both of us being able to use spotifyd as a shared spotify device for both accounts in Spotify Duo Subscription.

**Describe the solution you'd like**
Same solution that is in [raspotify](https://github.com/dtcooper/raspotify).

**Comment by eladyn** [comment]
In order to advertise the player and to be able to select it from any account, you can just leave `username`, `password`, `username_cmd` and `password_cmd` empty. Spotifyd will then accept anyone who tries to connect to it and will be visible to anyone on the same network.

Hope this helps!

**Comment by alembiq** [comment]
nice, will try when i get back next week :) thanks

**Comment by alembiq** [comment]
yeah, i forgot.....

nevertheless, even when i commented out `username` and `password` my fiancee cannot see the device in the network - checked both on mobile and computer :(
while i can see it both on my computer and mobile and both of us are sitting on the same network

it's making me confused

**Comment by honza** [comment]
I'm having the same issue.

**Comment by honza** [comment]
I solved the problem in my setup. I removed the username and password from `spotifyd.conf`, and then set the `zeroconf_port` to `1234`, and opened the port on the Linux machine that runs spotifyd.
