### ISSUE TITLE
dbus-launch command not found on alpine linux running wayland

### ISSUE THREAD

**Issue by wuzhe** [Spotifyd/spotifyd#939]
**Description**
can't launch the daemon

**To Reproduce**

`spotifyd --no-daemon`

**Logs**

<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
Loading config from "/home/username/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Connecting to AP "guc3-accesspoint-e-2spx.ap.spotify.com:443"
Authenticated as "1220530659" !
Using alsa sink
Country: "CA"
Caught panic with message: Failed to initialize DBus connection: D-Bus error: /usr/bin/dbus-launch terminated abnormally without any error message (org.freedesktop.DBus.Error.Spawn.ExecFailed)
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Alpine Linux 3.14
- Spotifyd: 0.3.2

**Comment by jessicah** [comment]
Ran into this too on a headless ubuntu server install. Installing `dbus-x11` fixed it, I guess DBus commands just end up failing?

**Comment by jessicah** [comment]
@wuzhe I found adding `--use-mpris false` might be what you're looking for... ideally it should catch the exception and disable mpris though...

**Comment by robinvd** [comment]
@jessicah this should indeed fix the problem! and not panicing but instead a soft error would be better
