### ISSUE TITLE
librespot fork

### ISSUE THREAD

**Issue by jimduchek** [Spotifyd/spotifyd#94]
librespot appears to be no longer maintained... It's looking like https://github.com/ComlOnline/librespot is taking over?  I'm not sure if it's too early to swap (or if any of the other forks might be more suitable), but that seems to be where a lot of the fixes/features are going.

**Comment by SimonPersson** [comment]
Thanks for reporting! I've updated the dependency to
[librespot-org/librespot](https://github.com/librespot-org/librespot/blob/master/src/main.rs) now.
