### ISSUE TITLE
Static noise when using spotifyd, no issue when using spotify client (both via tui).

### ISSUE THREAD

**Issue by Hashiraee** [Spotifyd/spotifyd#947]
When I use spotifyd instead of the normal spotify client (through spotify TUI) i get a weird static noise when playing my tracks.

Here is my config:
[global]
username = *****

password = *****

device_name = "spotifyd"
device_type = "computer"

cache_path = "/Users/*****/Library/Application Support/Spotify/PersistentCache/Storage"
no_audio_cache = false 

bitrate = 320
volume_normalisation = false
backend = "rodio"
mixer = "PCM"
zeroconf_port = 1234

Is there anything wrong?

**Comment by diegoulloao** [comment]
same problem here

**Comment by stadarn** [comment]
I hear the same thing on my computer. Mac Mini 2012 with MacOS 10.15 (Catalina)

**Comment by schickling** [comment]
I'm facing the same problem.

**Comment by diegoulloao** [comment]
No solution after six month????

**Comment by schickling** [comment]
It worked for me after switching to the [rodio backend](https://github.com/RustAudio/rodio).

**Comment by diegoulloao** [comment]
> 

I think it's only form Linux SO

**Comment by diegoulloao** [comment]
> It worked for me after switching to the [rodio backend](https://github.com/RustAudio/rodio).

I think it's only form Linux
