### ISSUE TITLE
If alsa backend is missing, and there is only one backend, fails to run without -b flag

### ISSUE THREAD

**Issue by erikh** [Spotifyd/spotifyd#949]
**Description**

spotifyd defaults to alsa backend, but if you enable features for different backends (such as pulseaudio) it will fail to run without specifying it with `-b`, even though the help text clearly states there is only one backend.

**To Reproduce**

```
cargo install spotifyd --force --no-default-features --features dbus_mpris,dbus_keyring,pulseaudio_backend
spotifyd -B 320 -u <user> -p <password>
```

Should see something like this:

May 09 10:21:50 islay spotifyd[83932]: No config file specified. Running with default values
May 09 10:21:50 islay spotifyd[83932]: No proxy specified
May 09 10:21:50 islay spotifyd[83932]: Using software volume controller.
May 09 10:21:50 islay spotifyd[83932]: Caught panic with message: Unknown backend: alsa.

**Expected behavior**

It either picks the pulseaudio backend, or doesn't try to load alsa at all.

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: pop OS 20.10. libpulse-dev package to provide pulseaudio support.
- Spotifyd: 0.3.2
- cargo: cargo 1.52.0 (69767412a 2021-04-21)

if you folks have a good solution you're happy with, I'm delighted to try making a patch as I get time.

**Comment by erikh** [comment]
feel free to reopen if you plan on fixing or addressing this.

**Comment by JojiiOfficial** [comment]
You're disabling alsa with the `--no-default-features`. This seems not to be a bug.
