### ISSUE TITLE
Volume control unstable with softvol

### ISSUE THREAD

**Issue by usul27** [Spotifyd/spotifyd#95]
When using the "softvol" ALSA module to implement volume control, the vole control from Spotify works unreliable. Sometimes it works fine, sometimes it doesn't.
If it isn't working, there are error messages:

Feb 09 18:48:06 raspberrypi spotifyd[504]: 18:48:06 [ERROR] Couldn't set volume of alsa device.
Feb 09 18:48:06 raspberrypi spotifyd[504]: 18:48:06 [ERROR] Couldn't set volume of alsa device.
Feb 09 18:48:06 raspberrypi spotifyd[504]: 18:48:06 [ERROR] Couldn't set volume of alsa device.

Using "alsamixer" or "amixer" with the same mixer control always works without issues.

**Comment by usul27** [comment]
It might be a good idea to improve error logging here to see what exactly happens:

        ) {
            Some(_) => (),
            _ => error!("Couldn't set volume of alsa device."),
        };

**Comment by SimonPersson** [comment]
I've pushed a commit that improves volume handling, and implements logging. I'll close the issue, feel free to reopen if this doesn't solve the issue!
