### ISSUE TITLE
Multi-platform media key suport

### ISSUE THREAD

**Issue by jpochyla** [Spotifyd/spotifyd#956]
**Is your feature request related to a problem? Please describe.**
MPRIS integration supports media-keys (and related functionality) on Linux, but Mac and Windows support is missing. It would be nice to have it, at least on Mac (as I'm not sure it's possible to do on Windows, without a window created).

**Describe the solution you'd like**
There is a crate with a multi-platform interface for these, [Souvlaki](https://github.com/Sinono3/souvlaki). If you're interested, I'd be happy to send a PR integrating it on Mac. Bigger task would be to add MPRIS there, probably replacing the MPRIS usage in spotifyd.

**Comment by codepuncher** [comment]
Can we reopen this? Something worthwhile to be implemented I'd say.
I often switch between Arch and macOS stations so not having multi-platform media keys is a shame.

**Comment by codepuncher** [comment]
Seems that this is already [reported as a bug](https://github.com/Spotifyd/spotifyd/issues/956) by the maintainer (although closed due to being stale).
