### ISSUE TITLE
on_song_change_hook triggered multiple times

### ISSUE THREAD

**Issue by Barbarossa93** [Spotifyd/spotifyd#957]
**Description**

As stated in the title, the song_change_hook is triggered multiple times. I've found that this happens because of running cava and [lyrics-in-terminal](https://github.com/Jugran/lyrics-in-terminal) at the same time. When I run both prorgams, the hook is triggered three times, if running either cava or lyrics-in-terminal, the hook is triggered twice, and with neither the hook is triggered once.

**To Reproduce**
1. Start spotifyd, spotify-tui, in separate tmux pane or terminal, cava and lyrics-in-terminal
2. Play a track
3. Hook executes multiple time (in my case, the hook was a script that created a notification)

**Expected behavior**

Hook should only execute once.

**Logs**
See attached

**Compilation flags** 
- [x] dbus_mpris
- [x] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS:  Arch Linux
- Spotifyd:  0.3.2
- cargo: 1.52.0

[spotifyd.log](https://github.com/Spotifyd/spotifyd/files/6518114/spotifyd.log)

**Comment by Barbarossa93** [comment]
My first thought that it could be something to do with dbus, but I don't think cava listens to dbus?

**Comment by Syakhisk** [comment]
Hey, I'm new, how can you get access to the hooks because I want to create the notification on the song change too

**Comment by alorgill** [comment]
Same here.

**Comment by xav-ie** [comment]
Hey, just an FYI -- if you run in --no-daemon mode you can get a more complete output and you can see that the reasons it is firing so many times is because of different events like "endoftrack", "play", or "change". I would appreciate if this was added to the wiki somewhere because I did not want to install spotify-tui and only use spotifyd.... 

Anyways, here are some events that I am getting:
```
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"TRACK_ID": "6ilStQsc2cozlrjmseAJ7N", "PLAY_REQUEST_ID": "1", "PLAYER_EVENT": "endoftrack"}
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"TRACK_ID": "7c8rXgRsYlpV2EJUwCNTFG", "OLD_TRACK_ID": "6ilStQsc2cozlrjmseAJ7N", "PLAYER_EVENT": "change"}
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"DURATION_MS": "192244", "PLAYER_EVENT": "play", "PLAY_REQUEST_ID": "2", "POSITION_MS": "0", "TRACK_ID": "7c8rXgRsYlpV2EJUwCNTFG"}
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"DURATION_MS": "192244", "PLAY_REQUEST_ID": "2", "TRACK_ID": "7c8rXgRsYlpV2EJUwCNTFG", "POSITION_MS": "64672", "PLAYER_EVENT": "play"}
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"PLAY_REQUEST_ID": "2", "PLAYER_EVENT": "preload", "TRACK_ID": "7c8rXgRsYlpV2EJUwCNTFG"}
Loading <Trouble in Paradise> with Spotify URI <spotify:track:5ubnEmiVtiHc2bBBTlYzFb>
<Trouble in Paradise> (229817 ms) loaded
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"PLAYER_EVENT": "preloading", "TRACK_ID": "5ubnEmiVtiHc2bBBTlYzFb"}
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"PLAY_REQUEST_ID": "2", "TRACK_ID": "7c8rXgRsYlpV2EJUwCNTFG", "PLAYER_EVENT": "endoftrack"}
Running "/home/x/.config/scripts/songchanged.sh" using "/usr/bin/zsh" with environment variables {"OLD_TRACK_ID": "7c8rXgRsYlpV2EJUwCNTFG", "TRACK_ID": "5ubnEmiVtiHc2bBBTlYzFb", "PLAYER_EVENT": "change"}
```

This may be helpful if you want to build something for a bar and keep the duration accurate, but I want to filter and only notify for song change.
Here is a script I use along with `playerctl` and `notify-send`:
```bash
#!/bin/bash

CLIENT="spotifyd"
# filter out preload, play, pause, etc... events
if [ $PLAYER_EVENT = 'change' ]
then
		#now get artist, title, album art link and song link from metadata
		artist=$(playerctl -p $CLIENT metadata artist)
		title=$(playerctl -p $CLIENT metadata title)
		albumUrl=$(playerctl -p $CLIENT metadata mpris:artUrl)
		# songUrl=$(playerctl -p $CLIENT metadata url) # you can make the notification clickable with notify-send.py
		# https://github.com/phuhl/notify-send.py
		tmpImagePath=$(mktemp)
		curl "$albumUrl" -o "$tmpImagePath" && notify-send "${title}" "${artist}" -i "$tmpImagePath"
		rm $tmpImagePath
fi
```
You should get a nice notification with album art, artist, and song name on a song change! It works but I am sure it can be improved by catching the preload events and caching the image by `mpris:trackId` for the key. Too lazy to figure that out though.
