### ISSUE TITLE
spotifyd not found in list of devices on spotify-tui

### ISSUE THREAD

**Issue by sogens** [Spotifyd/spotifyd#958]
**Description**
spotifyd no defices found api error code 404 when the service says its active 
enable the service with systemctl --user enable spotifyd && systemctl --user restart spotifyd then reset my computer to get a api error code 404 error code

**Expected behavior**
I open spotify-tui and it says it cant find the spotifyd daemon running when it is infact running and systemd says its running

**To Reproduce**
<!-- Steps to reproduce the behavior:
enable the service with systemctl --user enable spotifyd && systemctl --user restart spotifyd then reset my computer to get a api error code 404 error code

then check to make sure its active and running.. it is

**Expected behavior**
I open spotify-tui and it says it cant find the spotifyd daemon running when it is infact running and systemd says its running

```


**Compilation flags** 
I used spotifyd-full-git for the arch user repository with all features enabled

**Versions (please complete the following information):**
<!-- DO NOT use words like `latest`. Please specify the exact version/commit hash -->
- OS: Arch Linux 
- Spotifyd: spotifyd 0.3.2
- cargo: cargo 1.52.0

<!-- **Additional context**
this problem happens every single time I reboot my computer or when it goes to sleep and I have to manually reset the spotifyd service with systemctl --user restart spotifyd

**Comment by azzarello** [comment]
I can also confirm this same issue with the same steps to reproduce.
System Info:
- OS: pop-os 20.10
- spotifyd: 0.3.2 (installed through cargo)
- cargo: 1.52.0
- spotify-tui: 0.24.0 (also installed through cargo)

**Comment by nunestiago** [comment]
My steps are: load Spotifyd, open Spotify, change the device to Spotifyd and then I can use it on TUI.

* OS: Ubuntu
* spotifyd: 0.3.2 (installed through cargo)
* cargo: 1.52.0
* spotify-tui: 0.24.0 (also installed through snap(yes, snap))

**Comment by BGazotti** [comment]
Same here. Gentoo, spotifyd 0.3.2, cargo 1.53.0, spotify-tui 0.24.0. I have to open the official app on my cell phone, connect to the spotifyd device there, and only then it shows up on spotify-tui.

**Comment by Xanaxus** [comment]
I am also facing the same issue, but for some reason when I say `killall spotifyd` it says no such process found.


  -  OS: Ubuntu
  -  spotifyd: 0.3.2 (AUR)
  -  cargo: 1.53.0
   - spotify-tui: 0.24.0(AUR)

**Comment by dimas-cyriaco** [comment]
Same here.

It does not show on spotify-tui list. If shows in the android app list, but does not play audio.

* OS: Arch
* spotifyd: 0.3.2 (installed from the community repo)
* spotify-tui: 0.24.0

**Comment by BGazotti** [comment]
Update: it started working as expected after I explicitly added the spotifyd config file path through --config-path when starting up spotifyd. Can anyone else confirm this fixes it?

**Comment by dimas-cyriaco** [comment]
Yes, my problem was the config file too. Running with `--no-daemon` helped debug.

**Comment by hectorgrey** [comment]
In my case, I had to both explicitly add the `--config-path` and `--no-daemon` for spotify-tui to detect spotifyd immediately.

**Comment by hectorgrey** [comment]
So, after a little digging around, I think I know why it wasn't detecting the config files: in config.rs, the expected filename is spotify.conf, while the default config file is spotifyd.toml.  After renaming the config file, I no longer had to specify the path.  Question is, which fix should be implemented - change the expected filename to config.toml, or change the default config file to a .conf?

**Comment by dails08** [comment]
Even specifying config-path and no-daemon, I don't see spotifyd in spotui even when it seems to be up and running.  No errors in the verbose output.

**Comment by eladyn** [comment]
@dails08 There are several possibilities that can cause `spotifyd` not to appear in clients. It would probably be easiest, if you'd just create a new issue and provide information about your specific situation in the template.
