### ISSUE TITLE
Track ID not changing with on_song_change_hook 

### ISSUE THREAD

**Issue by chopnico** [Spotifyd/spotifyd#959]
**Description**
The Track ID doesn't seem to change when running on_song_hook_change

**To Reproduce**
Simply changing the song and looking at the logs.

**Expected behavior**
I would except the track ID would match the song that triggered the onevent

**Logs**
```
May 29 17:12:04 hildegard spotifyd[30784]: Running "/home/<omit>/.config/spotifyd/command -id <omit> -secret <omit>" using "/bin/bash" with environment variables {"DURATION_MS": "352000", "PLAYER_EVENT": "play", "POSITION_MS": "0", "TRACK_ID": "3gOJUhQe0AHfLR9Wby6c4J", "PLAY_REQUEST_ID": "23"}
May 29 17:12:05 hildegard spotifyd[30784]: Running "/home/<omit>/.config/spotifyd/command -id <omit> -secret <omit>" using "/bin/bash" with environment variables {"TRACK_ID": "7euBZraCkFV5bbct6mn2KP", "PLAYER_EVENT": "change", "OLD_TRACK_ID": "3gOJUhQe0AHfLR9Wby6c4J"}
May 29 17:12:05 hildegard spotifyd[30784]: Loading <Beyond The Lost Sky> with Spotify URI <spotify:track:4Rvcs1jHrpTzBzpItH3wuA>                
May 29 17:12:05 hildegard spotifyd[30784]: <Beyond The Lost Sky> (379946 ms) loaded                                                             
May 29 17:12:44 hildegard spotifyd[30784]: Running "/home/<omit>/.config/spotifyd/command -id <omit> -secret <omit>" using "/bin/bash" with environment variables {"PLAY_REQUEST_ID": "24", "PLAYER_EVENT": "load", "POSITION_MS": "0", "TRACK_ID": "7euBZraCkFV5bbct6mn2KP"}
May 29 17:12:45 hildegard spotifyd[30784]: Running "/home/<omit>/.config/spotifyd/command -id <omit> -secret <omit>" using "/bin/bash" with environment variables {"PLAYER_EVENT": "play", "PLAY_REQUEST_ID": "24", "TRACK_ID": "7euBZraCkFV5bbct6mn2KP", "POSITION_MS": "0", "DURATION_MS": "319866"}
May 29 17:12:45 hildegard spotifyd[30784]: Loading <Unfinished Sketch Of An Unforgettable Lady> with Spotify URI <spotify:track:6mWzytEIxRov2cuZCjjRyl>
May 29 17:12:45 hildegard spotifyd[30784]: <Unfinished Sketch Of An Unforgettable Lady> (193960 ms) loaded     
```
</details>

**Versions (please complete the following information):**

- OS: Debian 10
- Spotifyd: 0.3.2
- cargo: 1.42.1

**Comment by chopnico** [comment]
Also, unless I'm reading these logs wrong, the ID doesn't even match what's currently playing. In this example, "Unfinished Sketch Of An Unforgettable Lady" loaded with the track ID "6mWzytEIxRov2cuZCjjRyl", but the log above has "7euBZraCkFV5bbct6mn2KP".

**Comment by dionysiusmarquis** [comment]
I can also confirm that somethings seems to be odd. After building from master recently the `PLAYER_EVENT` behaves differently. I won't get any `start` anymore e.g. This breaks my current setup in which I pause other audio sources as soon as Spotify starts.

**Comment by J-Cake** [comment]
I may be experiencing this issue. What are your symptoms?

For me, when I select a song to play, the currently playing song restarts, and the selected song is ignored. I overcome this by queuing the song I'd like to play, and skipping the current one. What's frustrating, is that this is also required when using the official spotify app for my phone, when the `spotifyd` client is selected.

**Comment by NinjaJc01** [comment]
I can also confirm this, I've tried 2 devices and both the releases and builds on both of those.
Track IDs seem out of sync with what's actually playing, although it's sometimes just a track behind.

**Comment by hamid-elaosta** [comment]
I've been writing a display driver to pair the Pimoroni Pirate Audio with spotifyd, the track IDs were way off, many times not changing at all when a track changes, and when it does change its several tracks behind.

I initially thought the issue was in my display service but after some testing I'm certain now spotifyd isn't updating TRACK_ID correctly.

I'm running the latest release of spotifyd for armv6 on a Pi Zero W, using the latest Raspbain Lite.

**Comment by eladyn** [comment]
If anyone is interested, I pushed a fix for this in #1047. If you want, I'd be happy if you could test it and report back if it works (or doesn't).

**Comment by hamid-elaosta** [comment]
@eladyn This is great thanks. I'm not familiar with Rust but if I can figure out how to cross-build this for Pi I'll try it out.

**Comment by hamid-elaosta** [comment]
@eladyn Finally got a chance to test this. I can confirm that it is now working for me when built from your branch!
