### ISSUE TITLE
Doesn't work (thread 'main' panicked)

### ISSUE THREAD

**Issue by hrqmonteiro** [Spotifyd/spotifyd#961]
**Description**
Doesn't work, when i launch i get:

```
thread 'main' panicked at 'Couldn't initialize logger: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: None })), backtrace: None })', src/main.rs:39:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
- OS: Void Linux
- Spotifyd: spotifyd 0.3.2
- cargo: 1.52.0

**Comment by seth-scherer** [comment]
When on void linux you require a syslog daemon for Spotifyd to work.

https://docs.voidlinux.org/config/services/logging.html

Following the steps listed here fixes this issue.
