### ISSUE TITLE
No Playback

### ISSUE THREAD

**Issue by ytzelf** [Spotifyd/spotifyd#97]
I'm running spotifyd on a raspberry 3 w/ raspbian stretch lite.
The raspberry is connected to  an Allo Boss DAC : 

> pi@raspberrypi2:~$ aplay -L
null
  Discard all samples (playback) or generate zero samples (capture)
default:CARD=BossDAC
    BossDAC,
    Default Audio Device
sysdefault:CARD=BossDAC
    BossDAC,
    Default Audio Device
dmix:CARD=BossDAC,DEV=0
    BossDAC,
    Direct sample mixing device
dsnoop:CARD=BossDAC,DEV=0
    BossDAC,
    Direct sample snooping device
hw:CARD=BossDAC,DEV=0
    BossDAC,
    Direct hardware device without any conversions
plughw:CARD=BossDAC,DEV=0
    BossDAC,
    Hardware device with all software conversions`

I'm issuing the command
> sudo ./spotifyd --backend alsa --bitrate 320 --username XXX --password XXX --no-daemon --volume-control alsa --device hw:CARD=BossDAC,DEV=0 -v

My raspberry appears correctly in the Spotify Android app, logs react to skipping / seeking / volume BUT song stays at 0:00 and total duration shows 0:00 as well... I can paste detailed debug ouput if needed but standard log pretty much stops after
> 14:24:38 [INFO] Loading track "Run to You"
14:24:40 [INFO] Track "Run to You" loaded

**Comment by SimonPersson** [comment]
Please post the full log. I'm not sure it will help, but it's certainly better than nothing.

Have you tried to run it without specifying `--device`?

**Comment by SimonPersson** [comment]
I'll close this for now. Feel free to reopen if with a full log if the issue persists.

**Comment by husudosu** [comment]
I've the same issue.
My setup is: 
- Raspberry PI 3 with the newest Raspbian
- Sound Blaster Omni 5.1 USB Sound card

> null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dmix:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Hardware device with all software conversions
default:CARD=S51
    SB Omni Surround 5.1, USB Audio
    Default Audio Device
sysdefault:CARD=S51
    SB Omni Surround 5.1, USB Audio
    Default Audio Device
front:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    Front speakers
surround21:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    Direct sample mixing device
dmix:CARD=S51,DEV=1
    SB Omni Surround 5.1, USB Audio #1
    Direct sample mixing device
dmix:CARD=S51,DEV=2
    SB Omni Surround 5.1, USB Audio #2
    Direct sample mixing device
dsnoop:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    Direct sample snooping device
dsnoop:CARD=S51,DEV=1
    SB Omni Surround 5.1, USB Audio #1
    Direct sample snooping device
dsnoop:CARD=S51,DEV=2
    SB Omni Surround 5.1, USB Audio #2
    Direct sample snooping device
hw:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    Direct hardware device without any conversions
hw:CARD=S51,DEV=1
    SB Omni Surround 5.1, USB Audio #1
    Direct hardware device without any conversions
hw:CARD=S51,DEV=2
    SB Omni Surround 5.1, USB Audio #2
    Direct hardware device without any conversions
plughw:CARD=S51,DEV=0
    SB Omni Surround 5.1, USB Audio
    Hardware device with all software conversions
plughw:CARD=S51,DEV=1
    SB Omni Surround 5.1, USB Audio #1
    Hardware device with all software conversions
plughw:CARD=S51,DEV=2
    SB Omni Surround 5.1, USB Audio #2
    Hardware device with all software conversions

I have a MPD (Music Player Daemon) too, which works with this audio device: 
surround51:CARD=S51,DEV=0
- Of course I tried to stop MPD, before starting spotify daemon
- As you suggested tried to run spotifyd without specifying audio device, no positive results. 

I'm using config file:
```
backend = alsa
device = surround51:CARD=S51,DEV=0
mixer = PCM
volume-control = alsa # or alsa_linear, or softvol
#onevent = command_run_on_playback_event
device_name = sudosu-mpd
bitrate = 320
cache_path = /tmp/spotifyd
volume-normalisation = true
normalisation-pregain = -10
```
[You can find my verbose log here (Onedrive)](https://1drv.ms/u/s!AlIDARy55xh46AcQpS2It4BmqJgN?e=fHnIjd)

When daemon running, can be found by spotify and I can start playing on it, but no sound coming out. 
If you need any more info, let me know!

**Comment by tbranyen** [comment]
@husudosu I'm having a similar problem. I extracted the spotifyd command from systemd service file, and ran it as my normal user in the terminal and it works perfectly. I'm thinking it has something to do with the `audio` group, as I only have `User=<my_user>` specified in the service. Later today I'll try with setting the Group and see what happens.

**Comment by husudosu** [comment]
@tbranyen 
I tried to run spotifyd daemon from PI user, but no success :(.

> `Loading config from "/home/pi/.config/spotifyd/spotifyd.conf"
No proxy specified
Using alsa volume controller.
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL surround51:CARD=S51,DEV=0
Couldn't read volume from alsa device with name "surround51:CARD=S51,DEV=0".
Connecting to AP "gew1-accesspoint-b-mbs6.ap.spotify.com:443"
Authenticated as "husudosu" !
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Using alsa sink
Invalid CTL surround51:CARD=S51,DEV=0
Couldn't read volume from alsa device with name "surround51:CARD=S51,DEV=0".
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL surround51:CARD=S51,DEV=0
Couldn't set volume: Error("snd_mixer_attach", Sys(ENOENT))
Country: "HU"`

So by some reasons with PI user, spotifyd could not use my Sound Blaster card. The PI user member of the Audio group by default. Of course I turned off MPD service, when I tried to run spotifyd.

**Comment by SirWindfield** [comment]
Your audio configuration is not right @husudosu. `Invalid CTL surround51:CARD=S51,DEV=0`, seems like your control device isn't set correctly.

It would also be nice if you would open new issues instead of necro-posting on old ones. That way I can keep up easier with them :)

If you don't want to configure it manually, you can always use the `rodio_backend` which should work and play on the default device of your system.
