### ISSUE TITLE
cannot set it up on RPi4

### ISSUE THREAD

**Issue by KenjiYANAGAWA** [Spotifyd/spotifyd#973]
**Description**

I am trying to install spotifyd on my RPi4 and this is the error I get.
What should I do? 

-------------------------------------------

pi@raspberrypi:~ $ ./spotifyd --no-daemon

Loading config from "/home/pi/.config/spotifyd/spotifyd.conf"
Using alsa volume controller.
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL alsa_audio_device
Couldn't read volume from alsa device with name "alsa_audio_device".
Failed to resolve Access Point: HTTP error
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
Using proxy "http://proxy.example.org:8080/"
Caught panic with message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }

**To Reproduce**

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend
I didn't compile it by myself

**Versions (please complete the following information):**

- OS: 
- Raspbian GNU/Linux 10 (buster)
- Spotifyd: 
- v0.3.2 spotifyd-linux-armv6-slim.tar.gz
- cargo:

**Comment by vacy** [comment]
since that proxy did seem odd to me (example.org) and i had same issue I chose to start spotifyd with --proxy "" and that is working fine

**Comment by vacy** [comment]
update... i had the example proxy somewhere in the config that i copied from the wiki. took it of the config and its all fine.

**Comment by JojiiOfficial** [comment]
Closing since it seems to be fixed. Please reopen if the issue still persist without using "http://proxy.example.org:8080/" as proxy.
