### ISSUE TITLE
XFCE Pulseaudio-Plugin doesn't react

### ISSUE THREAD

**Issue by etkmichi** [Spotifyd/spotifyd#975]
**Description**
After the service was set up and enabled/started the plugin for pulseaudio panel module for volume and media control doesn't react.

**To Reproduce**
On linux arch and manjaro:
1. Install spotifyd 0.3.2
2. Setup service according to doc:
  sudo nano /etc/systemd/user/spotifyd.service
  copy-paste:
  https://github.com/Spotifyd/spotifyd/blob/master/contrib/spotifyd.service
  systemctl --user start spotifyd.service
3. Click on tray/panel icon for pulseaudio control (Xfce PulseAudio Panel Plugin - https://docs.xfce.org/apps/pulseaudio-plugin/start)

**Expected behavior**
Xfce PulseAudio Panel Plugin opens and provides volume control slider and playback controls (playback controls - not for spotifyd, only media players or web players)

</details>

**Compilation flags** 
i forgot already... but i think it was default or with pulseaudio backend

**Versions (please complete the following information):**
- Spotifyd: 0.3.2

spotifyd.conf :
...user credentials...
backend = "pulseaudio"
device_name = "ALongNameWithoutSpaces"
bitrate = 160
no_audio_cache = true
initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10
device_type = "computer"

spotifyd.service:
[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/spotifyd --no-daemon
Restart=always
RestartSec=12

[Install]
WantedBy=default.target

**Comment by samtoxie** [comment]
Experiencing the exact same problem here (first noticed it about a month ago, stopped me from using spotifyd then but wanted to give it a new try).

Using Arch Linux and installed from community/spotifyd on the latest version

```
[global]
username = "Hackerman"
password_cmd = "1337xdlulz"
device_name = "spotifyd"
device_type = "computer"
cache_path = "/home/samtoxie/.local/share/spotifyd-cache"
bitrate = 160
backend = "pulseaudio"
use_mpris = true
```

Systemd file
```[Unit]
Description=A spotify playing daemon
Documentation=https://github.com/Spotifyd/spotifyd
Wants=sound.target
After=sound.target
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/spotifyd --no-daemon
Restart=always
RestartSec=12

[Install]
WantedBy=default.target
```

Couldn't find anything in the logs for spotifyd and not sure if and where the panel plugin logs stuff

**Comment by etkmichi** [comment]
Latest update seemed to solve the problem.

On manjaro it just worked after a while, don't know why. 
On arch it worked after the latest package upgrades.

At least libcap is used by spotifyd.

Update log on arch:
upgraded libcap (2.50-2 -> 2.51-1)
upgraded pcre (8.44-1 -> 8.45-1)
upgraded at-spi2-core (2.40.2-1 -> 2.40.3-1)
upgraded enchant (2.2.15-4 -> 2.3.0-1)
upgraded harfbuzz (2.8.1-1 -> 2.8.2-1)
upgraded pango (1:1.48.5-1 -> 1:1.48.7-1)
upgraded libdrm (2.4.106-1 -> 2.4.107-1)
upgraded llvm-libs (12.0.0-2 -> 12.0.1-1)
upgraded mesa (21.1.3-1 -> 21.1.4-1)
upgraded gtk3 (1:3.24.29-2 -> 1:3.24.30-1)
upgraded harfbuzz-icu (2.8.1-1 -> 2.8.2-1)
upgraded iproute2 (5.12.0-1 -> 5.13.0-1)
upgraded libksba (1.4.0-2 -> 1.6.0-1)
upgraded libmfx (21.1.3-2 -> 21.2.3-1)
upgraded linux-lts (5.10.46-1 -> 5.10.48-1)
upgraded nspr (4.31-1 -> 4.32-1)
upgraded python (3.9.5-3 -> 3.9.6-1)
upgraded texinfo (6.7-3 -> 6.8-1)
upgraded webkit2gtk (2.32.1-1 -> 2.32.2-1)
upgraded xorg-server-common (1.20.11-1 -> 1.20.12-1)
upgraded xorg-server (1.20.11-1 -> 1.20.12-1)

**Comment by shreyasminocha** [comment]
I don't know, I can still reproduce this. Sometimes spotifyd would show up in the Media Player Controls plasmoid, but the "Now Playing" track would be a few minutes behind. Clicking pause would pause playback, but the progress bar would continue to move along and the pause button won't toggle to a play button. When I'd resume playback manually, the progress bar would reset to it's true position. Other times, spotifyd wouldn't show up in the plasmoid at all. Even then, `playerctl` would recognize `spotifyd`, but doesn't recognize that it's playing something.

```
$ playerctl --list-all
firefox.instance1469
plasma-browser-integration
spotifyd
```

**Comment by etkmichi** [comment]
I'll have to reopen this issue again, problem is still there. 
It seem that if spotify is playing a song the plugin somtimes reacts on a click in the tray.

**Comment by etkmichi** [comment]
i started xfce4-pane with debug mode.

$ PANEL_DEBUG=1 xfce4-panel
  ```
** (wrapper-2.0:1704): WARNING **: 10:24:07.415: Binding 'XF86AudioLowerVolume' failed!
  (wrapper-2.0:1704): pulseaudio-plugin-WARNING **: 10:24:07.415: Could not have grabbed volume control keys. Is another volume control application (xfce4-volumed) running?
  ** (wrapper-2.0:1704): WARNING **: 10:24:07.415: Binding 'XF86AudioPlay' failed!
  (wrapper-2.0:1704): pulseaudio-plugin-WARNING **: 10:24:07.416: Could not have grabbed multimedia control keys.
  (wrapper-2.0:1703): libsystray-CRITICAL **: 10:24:07.417: sn_item_invalidate: assertion 'item->properties_proxy != NULL' failed
  xfce4-panel(external): actions-2: child is embedded; 7 properties in queue
  (wrapper-2.0:1704): Gtk-WARNING **: 10:24:07.429: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner PulseaudioButton)
  (wrapper-2.0:1702): Gtk-WARNING **: 10:24:07.441: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)
```
without spotifyd running:

```
(wrapper-2.0:2542): libsystray-CRITICAL **: 10:31:59.316: sn_item_invalidate: assertion 'item->properties_proxy != NULL' failed

(wrapper-2.0:2541): Gtk-WARNING **: 10:31:59.327: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)

(wrapper-2.0:2543): Gtk-WARNING **: 10:31:59.339: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner PulseaudioButton)
```

**Comment by DorBreger** [comment]
I suffer from this issue as well, on Arch Linux, Linux 5.13. I did notice however than when I start spotify-qt, everything works as expected, with the volume buttons reacting and the pulseaudio plugin working. If any logs are needed I will happily provide them.

**Comment by ch3st3r08** [comment]
I'm having the same problem in my Debian bullseye, 5.10 kernel, using Xfce 4.16. I recently installed spotifyd, and followed the installation instructions, but then after a couple of minutes, I realized I couldn't use the xfce4 Pulseadio Plugin, then, went to its configuration, and tried open its settings, but it kinda messed up my panel. 

I was to give up on it, till I read @DorBreger answer. So, starting my Spotify-tui program, (which connects to spotifyd), kinda made it work again. I don't why this is happening, but i'm looking forward for a solution.

**Comment by Timonheu** [comment]
I am experiencing the same problem on Manjaro, 5.10 kernel, using Xfce 4.16. Similarly to @DorBreger and @ch3st3r08 , my Xfce pulseaudio plugin is completely unresponsive, but becomes responsive for a while when I start a song using Spotify-tui. My current workaround is just starting Spotify-tui periodically, but if there is any way I can provide logs I'd be happy to help.

**Comment by DorBreger** [comment]
I tried solving the problem by disabling "Enable keyboard shortcuts for volume control" in the pulseaduio plugin's menu, and setting custom keyboard shortcuts to increase and decrease volume. Unfortunately this still didn't fix it.
