### ISSUE TITLE
Startup takes 2 minutes until device is online

### ISSUE THREAD

**Issue by mustaphazorgati** [Spotifyd/spotifyd#986]
**Description**

It takes about 2 minutes before my device is online. Personally I think this is too long and should/can be improved

**To Reproduce**

Start spotifyd

**Expected behavior**

I expect the device to start a little faster. When you look at the log you see that it takes a little longer than 2 minutes until the device is connected and ready to use.

**Logs**
<details><summary>Click to show logs</summary>

```
Aug 03 22:47:22 mustapha-pc spotifyd[3338]: Loading config from "/home/mustapha/.config/spotifyd/spotifyd.conf"
Aug 03 22:47:22 mustapha-pc spotifyd[3338]: No password specified. Checking password_cmd
Aug 03 22:47:22 mustapha-pc spotifyd[3338]: No password_cmd specified
Aug 03 22:47:22 mustapha-pc spotifyd[3338]: No proxy specified
Aug 03 22:47:22 mustapha-pc spotifyd[3338]: Using software volume controller.
Aug 03 22:47:22 mustapha-pc spotifyd[3338]: Checking keyring for password
Aug 03 22:49:31 mustapha-pc spotifyd[3338]: Connecting to AP "gew1-accesspoint-a-5x8v.ap.spotify.com:443"
Aug 03 22:49:31 mustapha-pc spotifyd[3338]: Authenticated as "XXXXX" !
Aug 03 22:49:31 mustapha-pc spotifyd[3338]: Country: "DE"
Aug 03 22:49:31 mustapha-pc spotifyd[3338]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Aug 03 22:49:31 mustapha-pc spotifyd[3338]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Manjaro Linux 21.1.0
- Spotifyd: spotifyd-full-git 0.3.2.8.gd6b1ea5-1
- cargo: rust 1:1.53.0-2

**Comment by Chreece** [comment]
Could you share your hardware? I'm just curius... indeed 2 min is a long time... 
Spotifyd on my i5 MiniPC runs immediately and raspotify on Pi0W needs 1 sec to run...
I guess you have a better setup as a Pi Zero...

**Comment by JojiiOfficial** [comment]
I think its a keyring issue (you forgot to tick the `dbus_keyring` flag), maybe there is a 2 minute timeout for looking up if a stored password exists. Try to compile it without all default flags `--no-default-flags` and only with the audio backend you need (eg. `--flags pulseaudio_backend`)

**Comment by mustaphazorgati** [comment]
Hey guys!
Thank you for your replies.
Meanwhile I did figure out what the issue was. It was a network issue. My primary DNS server, a raspberry pi, broke. That caused the system to behave weird. Not only with spotifyd, but with other systems aswell.

@JojiiOfficial that's a good tip, but I didn't compile it myself. I used spotify-full-git, which already had almost all flags pre-compiled.

Anyway: After repairing my pi DNS server it now works like a charm. Startup times are about 1 second. See the attached log.
Just out of curiosity. Do you guys know what those unhandled DBus messages are? They appear in the log, but don't seem to influence spotifyd... 
```
Aug 19 21:34:40 mustapha-pc spotifyd[3007]: No password specified. Checking password_cmd
Aug 19 21:34:40 mustapha-pc spotifyd[3007]: No password_cmd specified
Aug 19 21:34:40 mustapha-pc spotifyd[3007]: No proxy specified
Aug 19 21:34:40 mustapha-pc spotifyd[3007]: Using software volume controller.
Aug 19 21:34:40 mustapha-pc spotifyd[3007]: Checking keyring for password
Aug 19 21:34:41 mustapha-pc spotifyd[3007]: Connecting to AP "gew1-accesspoint-a-1wmt.ap.spotify.com:443"
Aug 19 21:34:41 mustapha-pc spotifyd[3007]: Authenticated as "XXX" !
Aug 19 21:34:41 mustapha-pc spotifyd[3007]: Country: "DE"
Aug 19 21:34:41 mustapha-pc spotifyd[3007]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Aug 19 21:34:41 mustapha-pc spotifyd[3007]: Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired")) 
```
