### ISSUE TITLE
Unable to `cargo install`

### ISSUE THREAD

**Issue by Icelk** [Spotifyd/spotifyd#989]
**Description**

I'm unable to build with any features.

**To Reproduce**

It building and installing successfully.

**Logs**
<details><summary>Click to show logs</summary>

```
Caused by:
  failed to select a version for the requirement `stream-cipher = "^0.3"`
  candidate versions found which didn't match: 0.99.99, 0.7.1, 0.6.0, ...
  location searched: crates.io index
  required by package `aes-ctr v0.3.0`
      ... which is depended on by `librespot-audio v0.1.5`
      ... which is depended on by `librespot v0.1.5`
      ... which is depended on by `spotifyd v0.3.2
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [ ] alsa_backend
- [ ] portaudio_backend
- [x] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS:  Arch
- Spotifyd:  v0.3.2
- cargo: 1.54.0

**Comment by chughes-pika** [comment]
I'm having the same issue here

**Comment by f0rki** [comment]
Running with `--locked` seems to work, but prints the following warnings:
```
$ cargo install --locked --force --features dbus_mpris,pulseaudio_backend
,dbus_keyring spotifyd
    Updating crates.io index
  Installing spotifyd v0.3.2
warning: package `aes v0.3.2` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: package `aes-soft v0.3.3` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
[...]
```

It seems the problem is that several packages were yanked from crates.io?

**Comment by Icelk** [comment]
Can confirm. Thanks for the tip!
Seems bad to use the 10-ish dependencies which were yanked, for whatever reason. Can't help to notice most of them are cryptography-related...

**Comment by f0rki** [comment]
@Icelk I think the work in the PR #977 to upgrade to librespot 0.2 should also fix this issue (no more deps on yanked versions).

**Comment by Icelk** [comment]
@f0rki Great! Should we keep this open until the PR is merged?

**Comment by Icelk** [comment]
This seems resolved now.
