### ISSUE TITLE
Feature Request: Scrobbler

### ISSUE THREAD

**Issue by PedroHLC** [Spotifyd/spotifyd#99]
Overall spotifyd is fantastic!
The only feature I'm missing is a Last.fm scrobbler.
For not having to really implement it, a configurable option for calling a system command (replacing $title, $artist, album) when a song is fully played would be enough...

*EDIT*: I think playback is done by librespot, so librespot have to implement it first right?

**Comment by PedroHLC** [comment]
That's what I've used, and it worked, but it also scrobbles songs I skip, any ideia on how to filter it?

```shell
#!/bin/bash
# Requires CURL, JQ ( https://stedolan.github.io/jq ) and scrobbler ( https://gitlab.com/hauzer/scrobbler )

[[ $PLAYER_EVENT -ne "change" ]] && exit

# Settings
# generate one in https://beta.developer.spotify.com/console/get-track/?id=&market=
SPOTIFYDEV_TOKEN="<ADD YOUR OWN HERE>"
# must add it before on scrobbler
SCROBBLER_USER="pehlc"

TRACK_DATA=`curl -X GET "https://api.spotify.com/v1/tracks/${OLD_TRACK_ID}" -H "Authorization: Bearer ${SPOTIFYDEV_TOKEN}"`
TRACK_TITLE=`echo $TRACK_DATA | jq '.name'`
TRACK_ARTIST=`echo $TRACK_DATA | jq '.artists[0].name'`
TRACK_ALBUM=`echo $TRACK_DATA | jq '.album[0].name'`

echo $TRACK_DATA
exec scrobbler scrobble "$SCROBBLER_USER" "$TRACK_ARTIST" "$TRACK_TITLE" now -a "$TRACK_ALBUM"
```

**Comment by SimonPersson** [comment]
I see your issue. I think that's not entirely trivial to implement in librespot right now though (although if you would like to attempt it, I'd be happy to give some pointers). For your use case you might get away with having a heuristic based on time, something like this in the beginning of your script:

```
TIMESTAMP_FILE=/tmp/spotifyd_change_timestamp
SKIP_LIMIT=15

OLD_TIMESTAMP=`cat $TIMESTAMP_FILE`
date +"%s" > $TIMESTAMP_FILE
if [ -f $TIMESTAMP_FILE ] && (( $OLD_TIMESTAMP > `date +"%s"` - $SKIP_LIMIT )); then
        # Probably skipped track, don't scrobble.
        exit 1
fi
```

I'll reopen the issue to remember that we might need more fine grained events.

**Comment by mariusor** [comment]
If I may offer an option. 

Add MPRIS support to spotifyd and then anyone can use [mariusor/mpris-scrobbler](https://github.com/mariusor/mpris-scrobbler)[1] project for submission. It also supports the open-source last.fm alternatives: libre.fm and listenbrainz.org.

[1] Disclosure, it's my project.

**Comment by SimonPersson** [comment]
@mariusor - agreed, this would be my preferred solution. As you can see, I suggested in a previous comment that there must be software that solves this problem generically once we have mpris support. Thanks for linking us to your project, it looks like a good fit.

**Comment by wezzynl** [comment]
There's also [this project](https://github.com/bobbo/spotify-connect-scrobbler) which scrobbles songs playing from any connected Spotify Connect enabled client.

**Comment by mariusor** [comment]
@SirWindfield could you can give us a reason for the abrupt closure of this ticket?

**Comment by SirWindfield** [comment]
It's not in spotifyd's scope to implement scrobbing. Either more support has to be added to librespot itself to notify if a song has been skipped, allowing `onevent` scripts to work properly (like the one you created).
The alternative (and the better option as we have control over it) is to fix the MPRIS support and use 
[mariusor/mpris-scrobbler](https://github.com/mariusor/mpris-scrobbler). This is currently tracked in [in this project](https://github.com/Spotifyd/spotifyd/projects/2). 

@wezzynl also mentioned an even better alternative that uses the Spotify Connect API and would work out of the box.

I see no reason to keep this one open.

**Comment by mariusor** [comment]
Yes sorry, I thought this is the ticket about MPRIS support (issue #61).

**Comment by SirWindfield** [comment]
No problem :)
